== Chapter II

[.letter-heading]
To his Wife

[.signed-section-context-open]
Philadelphia, 9th month 30th, 1786.

[.salutation]
Dear wife,

Thine of 8th month 27th I have, affording satisfaction;
but still wish one in thy own hand-writing, and the dictates of thy own heart only.
When I write thee, thou hast my heart, my own heart, and I want thine, in thy letters,
not another`'s, nor any part of another`'s,
except simply as it may be conveyed by thee in a line of remembrance,
which is very acceptable from all my dear friends: or, as they find freedom to write,
in their own name; in which way an epistle from the dear sister who, I suppose,
wrote thine, would be quite as welcome,
as to have the language of her heart in thy letters.

Dear Joseph Mitchell, my beloved companion, after three weeks illness,
(the latter part had a heavy fever,) departed this life,
and left me as yet destitute of a partner.
Many dear Friends affectionately sympathize with me in this trying dispensation.
His burial was attended by divers solid Friends, and a large number of people,
at Buckingham, about thirty miles hence, the day before yesterday;
when divers living testimonies were borne to the efficacy of truth,
and the exemplary life of the deceased.
It was a blessed, good meeting; and I have abundant satisfaction,
that he came from home in the Lord`'s light, and in the Lord`'s time too;
and that he that called him forth was with him;
nor do I at all doubt his having obtained a mansion in the regions of eternal blessedness.
Mourning, mingled with joy, is my present portion in this proving situation.

Great have been my own painful conflicts and exercises of spirit,
separate from dear Joseph`'s case; but I find it livingly true,
that as my tribulations in Christ abound, my consolations much more abound;
for wonderful, yea, wonderful has been the Lord`'s kindness,
and almost transporting his assisting hand and counsel to my poor soul, at times,
in this land, perhaps beyond all I ever knew before;
but trials I expect still deeply to taste of.

I came to this large city with no other expectation than to suffer
almost continually and distressingly during my stay here;
but it has been a good open time to my poor spirit,
and way has been made for my little communications,
even in the hearts of the faithful and experienced here,
to my great humiliation before the Lord, who fights our battles for us.
This has been much the weightiest meeting I ever attended,
especially the select meetings, where also my way has been unexpectedly open,
and the brethren feel with me.
Oh!
I have seen that the Lord can do more for us, as we abide in the silence of all flesh,
in one hour, than all our wit, wisdom, and contrivance, can do in many years.
The awfulness, the solemnity, and reverent abased waiting before the Lord,
in these highly favored meetings, bows my soul in grateful admiration of that glory,
that so often, and so abundantly and overshadowingly,
filled the Lord`'s house on these precious and important occasions.
Ah me! may I ever humbly retain a sense of it,
proportionate to the gracious condescension of an all-powerful God, to poor, unworthy,
and, as to him, unprofitable servants.

I expect the day of adversity will soon be set over against this precious day of prosperity.
But as the prosperous day is, and has been, far more in a humble,
silent feeling of divine fullness and sufficiency, than in words,
even in that which in great degree swallows up and supersedes many words,
I have some hope of escaping without such deep returns of painful stripping as
have sometimes followed the most open and freely flowing verbal communications.
However, the way has been pretty open in that sense too;
but as it has been thankfully felt, that a very few words, in right authority,
do much more than a multiplicity out of it,
the business of these meetings has been conducted with the fewest words,
and yet with far the most life, of any I ever attended.

I have not time now for a circumstantial account of dear Joseph`'s illness and end,
but trusting beyond hesitation that all is well with him, I draw towards a close;
wishing thy comfort and encouragement in my absence,
and thy advancement in that precious truth,
in comparison of which all other things are trifling.
My endeared love is feelingly towards thee, and to our dear babes.
Tell them, be good little children.
Their father greatly desires it.
My dear love to father, Phebe, Remember; all father Anthony`'s family; Daniel Aldrich,
with all my dear friends.
Tell Elisha Thornton and Jaazaniah Barrett, I much intended writing to them,
but abundant prevention hinders at present;
therefore let them peruse this letter as if directed to them,
and may they remember me with a line, which I much desire, for I feel them near my heart,
and have done, in my pilgrimage through this land.

As to outward things, I must recommend thee to Heaven, and my dear friend Benedict,
and other kind friends occasionally.
Let brotherly love and sweetness continue among you.

+++[+++The]
time of +++[+++my]
return +++[+++is]
very uncertain.
In fullness of affection, I am thy truly loving husband,
who wishes to return to the enjoyment of domestic satisfaction,
in the company of thee and thine, who are mine, as soon as permitted.

[.signed-section-signature]
Job Scott

[.letter-heading]
To his Wife

[.signed-section-context-open]
Philadelphia, 10th month 9th, 1786.

[.salutation]
My beloved,

I am yet in this great city; here I have been held, scarce knowing for what,
but could find no way out.

I have a few meetings, now given out, a little way in the country,
and expect to go out tomorrow to the first,
but have yet found no companion to join me for more than a few days.
Edward Hallock and Tidiman Hull are here, and intend to be with me a little time,
after which I hope for suitable company, as I cannot see the way homeward yet:
so must desire thee to labor for resignation, without promising thyself soon to see me.
My heart is often with thee, my endeared; but here is a large field,
and the bulk of the meetings in Pennsylvania are so nearly situated,
(as my map shows,) as I seemed to view them, when at home, in my own mind,
that it greatly confirms my prospects;
but what I have felt at times has much more confirmed them.
Suffering and rejoicing have both much abounded, and a good degree of evenness,
(for me,) has been preserved under both,
although the misery has sometimes been as much as could well be borne.
But all is amply made up at seasons, blessed be our Helper.

I often wish thy lonesome hours may be sweetened by the incomes of that
presence which lifts my poor soul over one trial after another,
beyond my own expectation.
I even marvel at myself, how I bear up under the trying dispensation,
in the removal of dear Joseph, as well as I do.
I have thought thy great fears that I might not return,
might have some reference to his allotment, rather than mine.
However, though I still hope to see thy face again, it may be otherwise.
I have been much about this city, and into many houses, but am yet hearty;
the smallpox not much in town, though some.

Do, my dear, exhort, command, and restrain our dear babes, as need may be.
My spirit mourns in secret over the almost unbounded
deviations which prevail here among many,
who scarce wear any part of our mark;
and I see it to be much owing to parents missing an early restraint and control.
Alas! many have thus gone from the right way,
till the slain of the daughter of my people, are a great number.
It makes me wish ardently that my own, and my dear New England Friends`' children,
may be early and constantly subjected, lest little else be left, before long,
but the name of plainness and moderation among us.

Outward affairs, I commit to thee and Benedict; to whom is my endeared love,
as also to his wife, mother, and children; and to all my dear friends, as thou sees them.
I often feel many of them near me, with wishes for good.
I much wish a line from thy own hand, and own heart;
and tell my friends not to forget that a line at times is refreshing.

I feel great risings of affection towards thee, in which I must conclude, and remain,
as ever, thy loving husband, and sympathising, unshaken friend,
wishing thy advancement in the precious, ever-blessed truth,

[.signed-section-signature]
Job Scott

[.letter-heading]
To his Wife

[.signed-section-context-open]
Bristol, 18 miles from Philadelphia, 10th month 16th, 1786.

[.salutation]
Dear wife,

I wrote thee twice from Philadelphia, since which I have attended meetings every day,
till today; and have been shut up in suffering silence in all of them,
except a short sentence or two,
(without much satisfaction,) just at the close of one meeting.
A number of the last, I did not appoint, my way being quite shut up,
but had freedom to attend them as they came in course, or were appointed by others.
This day I have quite laid by; every door and gate being quite barred up,
for several days, if not locked and bolted.
It has been a most trying dispensation.
Gladly would I have seen the way home; but that was covered as with Egyptian darkness.
Patience and hope have been almost my only comfort.
I have just now, at night, seen a little light spring up, as out of darkness;
and a way seems open to go forward to a little number of meetings.
I have lately had the very sympathising company of James Thornton,
and divers other kind Friends.
I lodged a few nights past at James`'s, and found him a nursing father indeed.

Up and down, my dear heart, is still my way, as heretofore;
but I bear it rather more quietly; and in my downs,
I hope for a joyful uplifting by and by; and when _up,_
I remember what`'s likely soon to come, and so am kept lowly,
or in a good degree of evenness.
No doubt all will work for good.
My dear love to all my dear friends.
Tell my dear babes, I don`'t know when I shall see them, but want them to be good,
and to obey their mother.
Give my kind love to father, etc.
In endeared affection, I am thy truly loving husband,
in that which many waters cannot quench.

[.signed-section-signature]
Job Scott

[.letter-heading]
To his Wife

[.signed-section-context-open]
Philadelphia, 11th month 2nd, 1786.

[.salutation]
My dearest,

I this day came again to this place, in order to attend the Quarterly Meeting;
the select begins on seventh-day.
I have been in the country to a considerable number of meetings,
and the last three days before this, was at three Monthly Meetings.
The eleven first meetings I was at, after I left this city,
I was shut up in profound silence, except a very few words at the close of the first.
Trying was this dispensation; but in it I learned much patience.
I thought I knew before what it was to suffer, and want;
and also something of true patience: but I find we have much to learn,
even after we think we have learned much.
"`Day unto day uttereth speech, and night unto night showeth knowledge.`"
I think I have seen the Lord`'s hand in the deeps, under this exercise; and in the event,
in some respects, more than ever; and am beyond all doubt confirmed,
that he hath his way in the whirlwind, as well as in the cloud and thick darkness.

"`Ye have heard of the patience of Job, and have seen the end of the Lord.`"
This language is made very familiar; for indeed, he hath an _end,_
and an important end too, in all these provings.
I now know, that when he shuts none can open.
I read it, and believed it, and, in good degree, felt and experienced it before;
but now I know it in the deeps, in a manner past all human penetration,
or natural apprehension; and what is more than all that, I rejoice in it too; yea,
I greatly rejoice that it is so, and that I have thus exercisingly found it so.
For, by thus fully learning this part of the lesson, I have been led feelingly,
and to my great admiration, to dip far deeper than ever,
into a clear experience of the other part, that "`when he opens none can shut.`"
And, blessed be his holy name, after I gave all up, and, not daring to shrink back,
concluded to go on, and be a fool, a spectacle, and a sign, in dumbness and silence,
or whatever he pleased, I felt the word of his power,
and the eternal influence of his divine life to arise in my soul,
in majesty and mighty dominion: and in the fresh openings of the vision of light,
my trumpet was prepared to sound; and the openings being indisputably clear,
great was my confirmation; yea, and consolation also;
for it was like a resurrection from the dead.
And indeed, a good, honest old woman said to me after meeting,
"`I am glad I was at thy resurrection today.`"

Many, my dear love,
were the kind Friends that sympathised with me in my baptism into death:
and how could they but rejoice with me in the aboundings of that
which was evidently felt to be "`the resurrection and the life?`"
My way has been opened, and good ability given, in every meeting since, save one.

And now I feel much more like suffering in this city,
than I did any time whilst here before.
I _then_ very clearly _saw_ the great deviations; but _now_ I not only _see_ but _feel_ them too.
I was _then_ commanded not to judge after the sight of the eye,
nor reprove after the hearing of the ear; so I felt in good degree quiet and easy:
but I _now_ feel burdened to the life; and what I may find to do, or whether any thing,
I know not: on the Lord alone, is my reliance.
May his help be so waited for, as to be witnessed, preserving in the patience and quiet,
and in silence or otherwise, as his will may be; for I wish to have none of my own.

After this Quarterly Meeting come several more, which I think of attending;
so that I expect to be here but a few days, and away again.
I don`'t hear much of the smallpox in the city at this time.
When here before, I rambled almost all over it, and got many new,
and some choice acquaintance.

I can see nothing like home yet; not even in the deepest dippings;
for though ardency of affection would make me rejoice to be able to say as George Dillwyn,
in a letter to a friend this way, said respecting himself as to Ireland,
that "`the spirit of the Lord had sealed his discharge;`" yet, my beloved,
when I look home, the road is covered with a gloom of thick darkness, from end to end.
May my God, and thy God, give thee faith and patience to endure my absence,
and every trial, like a woman, with fortitude and resignation.
My endeared love salutes thee, and the dear babes I left in thy bosom.
To the Lord I commit and commend thee; and to him and to thee, I commit them.
Pray watch over them; tutor and restrain them in his fear, and in his counsel:
and though I can give little encouragement of a sudden return,
I wish thee not to think I shall be held here, as David Sands in the east.
I expect no such detention; but wish so to clear my mind in this land,
as that I may enjoy my family and friends, when I return,
and not suffer a number of months`' torment, like a dear friend of mine tells me he did,
after his return from New England.
I wish, ardently wish, to be with thee once more; but believe, beyond all hesitation,
were I now to come to thee,
in the strength of that feeling affection which abounds towards thee,
I should have little, or no satisfaction in thy company.

I heed very little, any man`'s pointings out for me;
some would hold me longer in one place;
others would be willing I went to this or that place.
But I mind my own business; for I find they are, in this respect, mostly, if not all,
physicians of no value; and I have but one to look to, to open and show me my way,
and him I find all-sufficient on every occasion, and in every trial.
Oh! may thy acquaintance with him, and reliance on him, be more and more increased,
as indeed, mine has been, in my pilgrimage through this land.

I almost fear my dear friend Benedict`'s patience will be pinched,
but wish it may not fail.
My love is affectionately to him, and all his;
wishing his care continued over my family and affairs.

My love to father, Phebe, sister and brother Lapham, their children;
father and mother Anthony; brothers and sisters all, and all my dear friends.
A line from them I much desire, and above all, from thee, my beloved;
do try to favor me in this respect, for I am now, as ever, but now especially,
thy feelingly affectionate husband,

[.signed-section-signature]
Job Scott

[.letter-heading]
To his Wife

[.signed-section-context-open]
Kennet, in Pennsylvania, 1st of 12th month, 1786.

[.salutation]
Dear wife,

About eight days past, I received thy very acceptable letter of the 28th of 10th month,
with one from James Smith of the same date,
and one from thy father of the 1st of 11th month, all truly acceptable.
Thy expression of sympathy with me in my trial in the removal of dear Joseph,
has a sweetness in it,
unknown to such as merely compliment each other with unmeaning expressions,
and know not that union of souls which adds true satisfaction to the one,
in every feeling sympathetic sentence of the other; especially, when far separated,
and under great tribulation; which has mostly been my case, since Yearly Meeting.
I rejoice in thy patience,
and have been obliged to exercise much of that necessary disposition myself;
else I know not that I could have endured.
If the _spoil_ has, I hope the _toil_ has not, been divided between me and thee;
for I wish thee happier, than in my absence to share my sorrows,
unless it might add to thy improvement.

What will come next, is beyond my short-sighted ken:
for I thought my eleven days captivity, mentioned in a former letter,
was near the utmost I had to expect.
But, alas!
I was not many days liberated from that, till I was plunged again,
so as not to be able to open my mouth, in a meeting for worship,
from the 9th of 11th month till yesterday the 30th,
being quite shut up in fifteen public meetings, and divers meetings for church affairs.
I suppose I am a wonder to many.
But my tongue clave to the roof of my mouth.
I could no more utter words with peace, in these meetings,
than I can at other times keep silence with peace.
Dear John Storer, William Jackson, Samuel Hopkins, and divers others,
have manifested deep sympathy with me, in this trying season.
A number of the last days, I have felt no more clear sense of divine good,
than if I had never known good in my life; saw no way to move,
and dared not move homeward; yet omitted writing,
not knowing but I must be obliged to skulk away home in the dark,
as a defeated soldier that flees before his enemy.
But as I endeavored to keep the word of patience, after all seemed to be gone,
and not a spark remaining, to my perception,
from which life could ever be again renewed,--blessed be the helper of the helpless,
light sprang up again out of seeming total obscurity; and when I was raised upon my feet,
(which was at a meeting I had been twice at before,)
I had very hard work to keep from running headlong.
It was like the rushing of a mighty torrent of water,
like a flood that seemed as if it would sweep myself and all away in it.

This day I have been at no meeting.
I hope if my way continues open,
my exercise may not be so much in the flood-like pressing forward,
but more in the gentleness;
though I cannot be sorry I have had the experience
of yesterday`'s irresistible breaking forth of waters:
for I very often have to say, after varied exercises,
"`Day unto day uttereth speech,`" etc.
And after all, I never expect to get to heaven, till all that is in me dies,
that cannot bear the Lord`'s chastising hand, without a murmur,
or even an unsubjected rising motion of heart,
contrary to a full renunciation of my own will and entire submission to his.
Therefore may his hand not spare, nor his eye pity, till all that is in me bows,
and remains wholly bowed, to endure with perfect patience,
his whole good pleasure concerning me.
And, my best beloved here below, my second self, may this too, be thy blessed experience.
I often wish to enjoy thee when we meet again,
as one whose advancement in the divine life, has added a sweetness and endearment,
surpassing the love of our first espousals.
Oh! may thy progress in that of getting rid of weakness and infirmity outstrip _mine:_
not as having more need, but because I so sensibly feel mine surrounding me,
in the midst of all my probations,
that I can but wish to be far outdone by her whose welfare is as interesting to me,
nearly if not altogether as my own.
But may thy refinement not cost thee such pangs as I find necessary to pass through.

I expect if I go on William Jackson will go with me,
and no man in Pennsylvania could please me better.
He knows the path of my feet, has drunk a cup like mine,
and known the sword that never fails.
Tell my dear children, their poor father`'s desire is, that they may be good children,
and obey their mother, or he shall be sorry for them when he comes home.
And Oh! my dear love, do watch over and restrain them.

I can`'t see the way home very soon.
I often fear it will fall so hard on my dear friend Benedict,
in the care of you I left behind, that for his sake, as well as yours and my own,
I could beg to be released, but must submit.
I once more presume to desire his care extended over you, in such +++[+++a]
way, as He who I trust cares for you, may open.
My heart is full on this occasion, but I must close.

[.signed-section-closing]
Thy heart affected husband,

[.signed-section-signature]
Job Scott.

[.salutation]
My dear,

I am now at Birmingham, the 5th of 12th month.
The day after I wrote the foregoing long letter, was a most glorious day.

[verse]
____
Truth reigned triumphant over all.
My soul, set free, rejoiced, and worshipped Him
That ever lives. But all`'s shut up again,
And deep distress last night possessed my soul.
Oh! that I might return to thee, dear love,
And leave my woe. But woe on woe would then
Be mine, should I desert my post and flee.
For this is death by law; and more than death--
`'Tis inward hell; and part too, would, I fear,
Be thine, should I return unlicens`'d home.
I mean, thou`'d have to sympathise in woe,
And be the partner of a wretch forlorn.
What shall I do? Distress awaits me here;
And horror threatens each attempt to fly.
I must submit. No other way I find.
My will must bow. My portion I must take,
Altho`' the cup be gall. And if I right
Endure refining fire, I trust I yet
Shall reign, and triumph over all. Amen.
Dear heart, farewell. May God`'s eternal love,
His everlasting presence comfort thee,
And keep thee safely till my safe return.
So prays the soul that loves thee, and is thine,
____

[.signed-section-signature]
Job Scott.

[.letter-heading]
To Daniel Anthony, and Others

[.signed-section-context-open]
Birmingham, Penn. 12th month 4th, 1786.

[.salutation]
Dear father and mother,

My love salutes you, with all the children.
I received thy letter of 1st of 11th month, with one from my dear wife,
and one from James Smith; all truly acceptable.

I see no way home yet, though I go on very heavily;
perhaps they never had such a visiter here before.

I am now in the heart of the very spot where my mind centred before I left home:
in one of the thickest settlements of "`Friends`" in all Pennsylvania;
though I then knew not that a single Friend lived any where here;
but I find I had a very clear sight of Friends who compose two Quarterly Meetings.
I felt deep and heavy exercise for myself in this place before I left my outward habitation;
but alas! one half was not told me.

After eleven silent, suffering meetings in another Quarter,
I had a few very open good seasons; then came into this part of the country,
and have been at their two Quarterly Meetings; four of their Monthly;
several Preparative, and many particular meetings;
and I was twenty days unable to open my mouth in any meeting for public worship,
though in that time I was at fifteen, and at several select, etc., in all which +++[+++I was]
almost wholly silent, my tongue cleaving, as it were, to the roof of my mouth.
Since that I have had two blessed meetings; high days, not to be forgotten;
but all is shut up again, for how long God only knows.
Oh! how often do I look towards home, but all is dark and gloomy.
I dare not desert my post, for it is death by the law;
and indeed it is death here to abide.

I am, and have mostly been, since Yearly Meeting, tried as to a hair`'s breadth;
no human help is able to direct, support, or deliver.
Dear William Jackson is my sympathizing companion, a workman indeed; I love him much.
If my way opens, and I go on, I expect much of his company.
No man in Pennsylvania stands before him in my list; I am an infant to him;
I wonder how he can give up to join me,
but it must be through deep sympathy with my exercised soul.
Dear John Storer, and many other Friends likewise, have very near sympathy,
and speak comfortably: but vain is the help of all mankind;
my distress is incurable by all their art.
I am a sign and wonder to many; but I pray for patience,
and at times can believe I shall yet come through and overall rejoicing; and then, anon,
faith almost fails.

So far as my depressed state allows, my love is to all my dear friends in your parts.
I have not had a line from one of them though I long ago wrote Moses,
and could gladly read a note from him, and as much so from divers others;
but they know not the path of my feet; they feel not my exercise,
nor dream of my probations I suppose, and if they knew the whole,
and wrote me day by day, +++[+++it]
would not avail, unless to show their love, and for a moment please a friend;
but could not heal the wound.
Yet let them not withhold, nor thee: for sweet is the remembrance of a friend.
But I must close;
relying only on that arm of strength which ever was the good man`'s shield, and is:
and though not seen, is near, and will, no doubt, in time that`'s best, itself make bare.
Till then, let faith and resignation ever be mine,
lest floods of doubt and darkness overwhelm.

But what am I about!
Adieu.
I rest thy truly loving, (in degree,) if not at this dull time,
thy feelingly affectionate and ardent son,

[.signed-section-signature]
Job Scott

[.letter-heading]
To his Wife

[.signed-section-context-open]
Philadelphia, 12th month 12th, 1786.

[.salutation]
My dear,

I wrote thee lately from the country, I think Birmingham.
I came this evening to the city, for my way quite closed up in the country.
I have not opened my mouth in public since my said letter.
The Lord only is fully knowing to the depth of my trials: but, blessed be his holy name,
he has not forsaken me.
I this day, among a handful of Friends in the country,
was very unexpectedly mounted on the King`'s horse, triumphing over all doubt, distress,
and opposition.
For the Lord`'s trumpet was given me to sound.
I hope the sound was certain.
When I turned back toward the city, I meant to come home to thee, my dearest,
unless more light appeared.
But I cannot see home, any otherwise than under a dark cloud;
and I cannot feel my work in the country here to be by any means completed;
yet I must leave it undone, unless the Lord`'s holy presence goes with me; for, alas!
I can do nothing.
So I think to wait a few days to see which way the wind will blow;
for it bloweth where it listeth.
And though I yet see no way for much further service,
I dare not allow thee to hope to see my face very suddenly.
The Lord only knows the end of all my exercises.
I beg for patience, and wait his directions.

I received a very acceptable letter from my dear friend Benedict,
and another from Elisha Thornton.
They came not to my hands till this evening,
and I do most heartily acknowledge their kindness.
May they not forget me,
and may none of my dear friends forget me in the time of deep tribulation.
Tell those who have kindly written to me,
they are not sensible of the satisfaction it affords in some trying seasons;
but they must not expect I can often write to them.
I am often too low to undertake it; therefore let them peruse those I write thee,
and take a share with thee in my affectionate remembrance, for I love them,
and many other Friends among you, dearly.
Give my endeared love to all that love the Lord among my acquaintance.

Dear William Jackson is yet my tenderly kind companion;
he and some others think I shall scarcely get cleared
out for home till next spring or summer.
He stayed when in our land much longer than he expected; so no wonder he thinks I must.
I endeavor to mind the Master, and not man,
and shall come home as soon as ever I see the light shine clearly on New England,
and a way cast up to walk in thitherward.
But do, dear heart, abide in patience.
I long at times to be with thee; but must give up all for peace sake,
and to be with the Lord.
And Oh!
I pray his holy presence may be with thee, and more than supply my place.
If my absence is thy chief trial, thou hast much the easiest time of it.
For, much as I wish thy company, I assure thee,
thy absence is but one of my small probations, in comparison.
But I must not, I dare not repine.
I will be well if a right improvement is kept to.
May the everlasting arm support thee.
My dear love to my dear babes, to father, Remember, Phebe, all Benedict`'s family.
May the Lord reward his care and kindness,
and all who have remembered thee in thy temporary widowhood.
Do, my dear, write as often as thou can.
Let my dear children be nurtured in the fear of the Lord, who only can bless,
and also can blast.
Farewell, my dearly beloved, farewell in the Lord.
Keep in his counsel; rely on his arm: it is an arm of full sufficiency,
in which there is no lack.
I rest affectionately, thy faithful, loving husband,

[.signed-section-signature]
Job Scott

[.letter-heading]
To Joshua Sharpless, Chester county, Pennsylvania

[.signed-section-context-open]
Westbury, Long Island, 1st month 26th, 1787.

[.salutation]
My dearly beloved friend, Joshua Sharpless,

I received last evening the sorrowful account of thy great trial,
in the removal of thy dear, precious wife:
and though I have not the least doubt that thy loss, and our loss, is her eternal gain;
yet it did very closely exercise my mind,
both in sorrow for the loss (in this life) of my own very dear friend,
and in deep sympathy with thee and the dear children.
May the everlasting arm be your support, the Shepherd of Israel your unfailing preserver;
as he certainly will be, if rightly sought unto, and leaned upon.
Now is the time, dear Joshua; now is an especial time, wherein it is greatly necessary,
and will be greatly useful and comfortable to thee, and the dear lambs left in thy bosom,
to "`be still and know that he is God.`"
He has all power in his holy hand: and "`shall not the Judge of all the earth do right?`"
He surely will; he surely has done right.

Oh! let this consideration quiet and stay your minds: and if your minds are stayed on God,
your souls will be kept in perfect peace: for this is a promise that fails not,
but holds good to all that are rightly stayed upon him.
To mourn, is human; and, if in federation, I think is also lawful:
but Oh! to submit and from the heart to give up all, and say, "`Thy will be done;`" this,
this is truly christian.
May your souls, my dear friends, and my own too,
feelingly and fully adopt this language,`" Thy will be done.`"
It is the best, yea, the only cure, for many unavoidable afflictions and grievances.
I include myself, because my soul has keenly felt the wound;
and I could not for some time, consent to believe the mournful relation.
She was truly one of my choicest friends.
Dear jewel, how I loved her! even more than I was willing she should know.
When first I saw her in the select Quarterly Meeting at Concord, (where I fixed on her,
though a stranger,
to be Edith Sharpless,) I felt my soul secretly and fervently knit unto her:
and this affectionate regard increased to the last of our acquaintance,
and flows forth at this time with unabated ardour,
as if on the departure of a very near and dear relation.
So that, dear Joshua 1 feel nearly for thee: and my dearly beloved children,
you dear and tender lambs, I feel also, and that very affectionately,
with you and for you; and do with heartfelt fervency "`beseech the living God,
to hold you in his hand.`"

And may you, dear children, love the Lord with all your hearts,
and choose him for your portion, and for the lot of your inheritance.
I did dearly love you, my dear little friends, when I was with you:
and now I feel a great increase of it; both towards you and your dear father: to whom,
may you be ever dutiful and obedient.
This will greatly tend to comfort and to cheer his grieved soul,
and to bear up his drooping spirits.
I hope your conduct will be such, as may make his heart rejoice: yea,
I hope he may at this present time rejoice in some of you, if not all.
Oh! that he may never have cause to mourn over any of your conduct!
And, O dear Joshua! though I wish thy rejoicing to be ultimately in the Lord alone,
yet I think thou mayst rejoice in the pledges of his love:
and if dear Edith`'s dear babes, follow on to walk in her footsteps,
I think thou mayst in some sense enjoy _her_ in the enjoyment of her lovely offspring.

I feel a special wish that the two eldest may lead
the others on in the ways of virtue and sobriety,
and in strict obedience to thee, their afflicted father.
Much depends on the conduct of the eldest children in any family,
and especially where the mother is removed.
I know a little by experience; for when I was ten years old, I felt,
as I suppose some or all of you feel:
for the stroke of death rent from me a most tender and beloved mother, and I,
with two sisters, one brother, and our poor disconsolate father,
was left to mourn in sadness and sorrow, far beyond what I had ever known before.
Indeed I remember it now (in great degree) as if it was yesterday;
and I well know that I then verily thought I should feel
as great distress while life remained as I felt then.

But I was but a child, and was greatly mistaken.
I found cause of joy in something else, after she was gone,
and gradually became resigned to my lot:
so that I can experimentally sympathize with you, dear children,
and would not have you be too much cast down.
The Lord can make up to you all the loss; yea, and much more, if you love him,
and lean upon him.
He has done it for me, and, blessed be his holy name,
he followed me with visitation after visitation, till he drew me to close in therewith;
and then he filled my heart with his goodness,
and caused my cup to overflow with his love and divine
presence to my unspeakable joy and consolation:
that I verily believe her prayers were heard on my account, and the rest of her children;
for after my giving up to Truth`'s requiring, my sisters soon followed my example.
I was the eldest; and believe my footsteps were really useful to them,
as well as the advice I had often to give them from time to time.
My dear little brother died, an innocent lad, at seven years old;
and myself and sisters all became, I trust, truly religious, and by request,
members of Friends`' Society.
And I have often thought, we have been as well provided for, both inwardly and outwardly,
as if our dear mother had stayed with us in this world of troubles.
And she has escaped many afflictions by being removed; and went, I doubt not,
well prepared to a mansion of unmixed joy; as has, I firmly believe, your dear mother,
forever to sing praises to him,
who graciously redeemed her precious soul from transgression.

It is much to my satisfaction that she was with me at a few meetings.
I felt as if I could not be easy without more of her dear company than I had had before;
and when we last parted, I told her, I felt much easier to part, and take leave of her,
than I ever could before: but little did I think of what has taken place;
though I now believe, my very unusual weight of darkness and distress,
with some uncommon thoughts upon death, which I had, one evening, at your house,
and in her company,
might be laid upon me as a forerunner of what I felt
on hearing the heavy news of her death.
Indeed, I know not that the like account of any friend in Pennsylvania,
would so nearly affect me.
But she is gone, I trust to everlasting glory; let us all bless the name of the Lord,
and prepare to follow her.
Accept, dear Joshua, and all you dear children,
my sincere love and affectionate sympathy; for I truly am your sympathetic friend,

[.signed-section-signature]
Job Scott

[.letter-heading]
To Joshua Sharpless

[.signed-section-context-open]
Uxbridge, 14th of 5th month, 1707.

[.salutation]
My dear friend,

Thine of the 26th of 3rd month I seasonably received,
and felt much satisfaction in thy so full account of dear Edith`'s last days;
but more in thy being so well borne up under thy trials in her removal;
and what added still more to my joy was the account in regard to the dear children,
of the good desires "`begotten in most or all of their tender minds,
to follow that which makes for peace.`"
May this continue to be the fervent engagement of not only _most_ but _all_ of them;
not only for a short time, but till they go hence to meet with their dear mother,
and be seen of men here no more.
I loved them dearly and travailed for their advancement in the right way.
I felt deeply with them, though absent, in their great affliction;
and not a little did I feel for thee.
Well, may thou look beyond the unworthy instrument;
for he wrote no cunningly devised fable, but what he felt too impressively on his mind,
to enjoy satisfaction in the omission of;
and doubts not that has been the case with others, whose hearts have been animated,
and their bosoms warmed with living flowings of divine good, for communication,
in deep sympathy with your exercised souls.
Thus gracious and compassionate is he who is at times felt to be
the rock of our salvation and our only horn of divine strength.

I have not at present that sensible feeling flow, as at some other times;
and may I never counterfeit it: for I have found, that adds death to the soul.
You must not expect much at this time; only this, I feel, I deeply feel that I love you,
and I hope I may say it is "`in the Lord.`"
May he preserve you through all trials, temptations, and besetments,
to the praise of his own excellent and eternal name,
and to your unspeakable consolation and joy.
Oh!
I feel great need to dwell deep and keep near the living fountain of strength and preservation.
Never perhaps was I more entirely stripped of all sense of his presence,
than much of the time since I came home;
though on getting home I had the unquestionable answer of solid peace;
and for some days my peace flowed as a river.
My discharge from your land was sealed on my soul
with rejoicing that I had been among you,
and felt some of your spirits.
May I ever abide in that which only can preserve a right
sense of those blessed seasons I had in some of your houses,
and in some meetings.

I suppose my late poverty is all for the best,
and wish the dear children not to be discouraged at it; it is a path they must tread,
if faithful.
The land of God`'s people is spiritually, as outwardly of old,
"`a land of hills and valleys.`"
I have ever found it so; ups and downs have attended me through life;
and I expect it will continue so, and am fully convinced it is best it should be so.
Only let us be careful not to sink too low, nor give out and grow careless:
of both these things there is great danger; I feel it so in myself.
Oh! may you and I ever watch unto prayer, lest we take our flight,
either in the winter of trial and desertion, when the divine beams of the spiritual sun,
seem faintly to shine upon us; or in the sabbath of ease,
when carelessness is apt to creep in.

My dear love is to many dear friends, as P. S. and her husband; the dear Wistar children;
(may they love and serve the Lord,
and be sure not to put it off too long;) thy mother and sisters,
with such other of my dear friends, as thou finds freedom to mention me to.

Don`'t forget, dear Joshua, to write; and when thou feels it, don`'t omit it;
then is the time.
Thy feeling communication did my soul good;
not so much because thou expressed a lively sense of mine,
as because of that precious savor and evidence of divine support,
which runs through the whole of it.
Dear Edith, I doubt not, rests forever in Abraham`'s bosom, in the paradise of God.
May we so follow on, as to meet her there, and rejoice with her forevermore, is,
dear Joshua, the desire of thine and thy dear children`'s real friend,

[.signed-section-signature]
Job Scott

[.letter-heading]
To Joshua Sharpless

[.signed-section-context-open]
Uxbridge, 25th 7th month, 1788.

[.salutation]
Dear Joshua,

I seasonably received thy very acceptable letter of 9th month 30th--87,
and can assure thee my long silence is not the fruit of forgetfulness, or want of love,
either to thee or thy dear children: nay, verily,
you have a place of endeared record on my heart.
I love you with unfeigned affection and endearment;
and thy account of your "`feeling near and dear to
each other,`" etc. is sweet to my mind.
Oh! may the everlasting unslumbering Shepherd of Israel watch over you, sustain, protect,
and preserve you, through every trial, temptation, and besetment.
O dear children! love the Lord, the God of your exercised father;
and who was eminently the God of your dear mother, and serve him with perfect hearts,
and willing minds and he will be your God also; he will hold you in his holy hand,
and fill your souls with good things;
and your real joy will be far beyond what a life of unprofitable amusements, company,
and conversation ever can afford.
Have a very special regard to the judgment and advice of your experienced father:
consult him on all occasions of importance: consult him early,
and do not go contrary to his advice, even though he advise against your inclinations.
I trust he knows better than you do, what will be good for you,
and I think he will be as indulgent as truth will allow;
and I believe the Lord often blesses children who are obedient to their parents.

And now, dear Joshua 1 have not much to say to thee,
only be thou strong and very courageous in the Lord,
as was said to one of thy name formerly; and I have no doubt the Lord will be with thee,
in every trouble; and through all, as thou looks to him, make thee more than conqueror.

My dear love is to all them that love the blessed truth.
Mention me to the Wistar children.
I have breathings of spirit to the Helper of the helpless, on their accounts.
Oh! that they may dedicate their time and talents to the service of the truth.
I rest, in heartfelt affection, thy sure friend,

[.signed-section-signature]
Job Scott

[.asterism]
'''

[verse]
____
A Farewell Salutation on Leaving Home.

My dear and much beloved wife,
`'Tis truth`'s great cause at heart;
Which I still prize above my life,
That causes us to part.

No worldly glory, wealth, or joy,
Invites me from thy arms:
Mayst thou protect our infant boy,
And all our babes, from harms.

And may that God, who reigns on high,
And calls me from thy smile,
In every danger, still be nigh,
And sweeten every toil.

Oh! may he hold thee in his hand,
And on him stay thy soul;
While I may toil from land to land,
Or on the ocean roll.

Be he thy husband, portion, peace,
Thy guide, protector, friend;
Thy faith in him, may he increase,
Thy cause may he befriend.

If I thy face should see no more,
(Which yet I think I may,)
That hand that wounds to heal, adore,
Thy will be done, still say.

He knows why he commands me hence,
And let his will be done;
I trust he`'ll be thy sure defense,
And save thee through his son.

His son has died for thy offense,
For mine, he gave his life;
Then let not all the ties of sense,
So bind the man and wife

To one another, that his will,
May not direct their course:
Though love their hearts may ever fill,
Nor time their souls divorce.

The cords of best affection, draw
Their thoughts from clime to clime;
No distance can their love destroy,
No more than length of time.

Yet may they bow to his commands,
Who knit their hearts in love,
And traverse the most distant lands.
If ordered from above.

I love thee more than pearls or gold,
Where`'er I go, my dear,
My heart on thee quits not its hold,
At home, far off, or near.

Yet one I must prefer to all,
And him I must obey;
When he leads on, attend his call,
And stop when he says stay.

Oh! give me up, let him dispose
Of me, and all that`'s mine;
What`'s best for us, he fully knows,
And let his will be thine.

And you my little children dear,
Be good, and love the truth;
Of every sin or fault keep clear,
Now in your early youth.

Your mother`'s voice gladly obey,
To her be ever kind;
Her love, with love again repay,
Her precepts always mind.

And may the Lord, the God of might,
Who calls your father hence,
Direct your course and his aright,
And be our sure defense.
____

[.signed-section-signature]
Job Scott

[.letter-heading]
To his Wife

[.signed-section-context-open]
New York, 15th of 3rd month, 1789.

[.salutation]
My best beloved,

My affectionate love salutes thee,
in that which I trust neither sea nor land will ever be able to erase from my soul.
Oh! how my heart is affected, when I think of thee,
and the little flock I left with thee, to watch, and feed, and guide.
Oh! how my heart heaves, when I look back at the parting, solemn scene.
Never was I from you before,
when it was so hard to put aside the fresh remembrance of the last adieu.
My eyes run down with tears, when I view the poor little weeping boy and girls,
following their father down to the road, not knowing when they should, if ever,
see him again.
The dear little helpless innocent too, the one among them all,
which must engage thy constant care--by night, by day,
thy charge--Oh! how my heart is melted when I think on him! and how my bosom beats,
whenever I think on thee; on thee, my chosen, much beloved and lonely mate.

May Heaven protect thee, while I range from clime to clime.
May Heaven protect thee, till we meet again.
May Heaven protect not only thee, but thine.
Thine now they are, though once I called them mine: mine still they are,
as thou thyself art mine: and thine, I feel myself to be,
in bonds and ties that distance cant dissolve.
Oh! read my tears, whenever these lines thou reads.
Just what I have, I write; just what I feel, I say; for I`'m a husband--I`'m a parent too.
I feel the exquisite connection--tender tie: I know the source whence sighs proceed,
whence bosoms beat!--and tears, in spite of all philosophy`'s cold prate, will flow.

O my dear love! my partner!--Ah! my friend,
canst thou sympathise with me in my views of coming scenes of woe?
I look forward in full expectation of many a draught of wormwood, mixed with gall;
but must say, as I have read somewhere,

[verse]
____
"`Since God, in mercy, has decreed this cup,
Most willingly therefore, I drink it up.`"
____

"`Most willingly`" indeed: I believe I ought to _feel_ so.
But, Oh! when I look forward at tribulation upon tribulation,
and backward at those I love, and view the partner of my life, combating varied woes,
I am ready to say, How can I go on?
I do verily expect to go heavily.
Many a heartfelt sigh, yea, many a deep fetched groan, will doubtless bear me company.
But let me not repine.
I dare not desert my post, lest death should be the consequence.
And though dark and gloomy is my _forward_ view,
yet a gleam of light now and then shines sweetly on it; whereas darkness, _total_ darkness,
covers every backward glance.
I must go on.
I`'m made to bow, and that is all I can say.
I feel almost as if I should scarce deserve any wages, should I labor ever so faithfully;
for if I dared to, I think I certainly should turn my back upon the service.
I don`'t believe I am able to give thee much of an idea, how it seems to me.
But if ever thou feels thy mind lifted up to him that rules on high,
in ardent supplication for thy mate, ask heaven`'s King to grant him faith.
Oh! may he hear thy cry! and if to faith, he patience adds, it will do.

I cannot say much about my outward affairs; my heart is too full.
I leave all to thee, and thy dear parents.
On them rely; but more than all, rely on Heaven.
And if I never see thee more, or if I do, the Lord Jehovah hold thee in his hand,
preserve thy soul, and make thee know,
that all true joy is in submission to his will divine; that he has a right,
an undisputed right, to call or send his poor unworthy servants where he will.
And none who rightly bow, will dare to question or withstand.
Be thou resigned; be he thy stay.
Cast on him all thy cares.
He`'ll hear thy sighs; thy wants supply; and in his own due time,
I trust he`'ll bring us face to face again; and cause our souls to leap for joy.
Till then farewell.
My love is warm to all the _five_ dear lambs.
Tell them, be good, till father comes again, and then they`'ll be his joy.
My love, pray give to him from whom I sprang.
May heaven preserve him in declining age.
And may an holy smile revive the drooping soul of
that dear girl I left with thee--thy sister dear,
and mine.
And may the rest as one farewell; my love is to them all.

[.signed-section-signature]
Job Scott

[.letter-heading]
To his Wife

[.signed-section-context-open]
Philadelphia, 25th of 3rd month, 1789.

[.salutation]
Dear wife,

My tender and endeared love salutes thee this morning in a fresh feeling of that affection,
which I am renewedly confirmed, neither time nor distance, storms nor tempests,
will ever be able to erase from my mind.

Yesterday we visited Samuel Smith and his exercised wife.
Dear Samuel is just cleared out for England.
His concern received in my heart, both in this visit and in the select meeting,
such a seal and sanction of truth, that no kind of doubt remained.
And, O my best beloved here below,
how wast thou brought into fresh and heart-tendering remembrance,
whilst things were opening in the encouraging line, pertinent as I believed,
to his dear bosom companion`'s tried state and condition;
wherein I had to make mention of thee,
and the dear babes I have resigned to the care of their heavenly Father,
and their affectionate mother.
The mention of these things, as they then feelingly revived,
was moving to the minds both of dear Samuel and his tried companion;
who I hope will give him up with a good degree of cheerfulness.

I much desire to hear how thy mind is supported under thy exercises, in my absence.
Do write me as soon as well may be.
I have become much more stayed in my mind, than I was.
That almost constant overwhelming of excessive affectionate remembrance,
is greatly removed: instead whereof, a firm, unshaken, may I not say,
holy endearment remains.
I have all the confirmation I can wish for,
that I am in the way of my indispensable duty, and about my Heavenly Father`'s business;
so that with such an evidence, I could freely risk my body on the rolling ocean.
The Helper of Israel has been gracious to my soul,
and made my cup to overflow beyond all expectation.

We got to Haddonfield Quarterly Meeting in Jersey; the select on fifth,
and the more public meeting on sixth day last.
Had been much shut up ever since we came from home, and my poor mind very closely tried,
under various sensations and considerations, till sixth-day,
when light shined above the brightness of the sun, and way opened to admiration.
On sixth-day evening, we arrived safely in this city.
Our home has been with our very kind friends James Bringhurst and wife.
On seventh-day, the general select meeting began,
when my way opened into depths of instructive communication,
which I almost trembled under the weight of; but got through with abundant satisfaction,
in a steady bottom way.

First-day, an open time in the morning at Pine-street meeting.
Afternoon and evening, contrary to the common course of such as have visited this city,
I felt constrained to attend at Market street meeting;
though there were meetings both at Bank and Pine street, both morning, afternoon,
and evening.
I was shut up at the great house, both meetings, yet felt still engaged,
on second-day after the select meeting, to go once more, to the great house;
there being meetings at all three of the places this day also.
This third time, silence seemed commanded over the meeting;
though much had been said at this place yesterday, by divers,
after a solemn silence for a space of time, the way opened, and relief was obtained;
which was also eminently so in the select meeting in the morning,
though in a way of very close doctrine, greatly unexpected by me,
when I parted with thee.
But give up I must, though almost with amazement.
The commission, I believe, was felt,
and inwardly acknowledged by all the real judges in Israel then present.
Yesterday, a laborious season at Bank Monthly Meeting; but victory was gained.
Today, Pine street Monthly Meeting comes on, and sixth-day, that at Market street.
Seventh-day select meeting at Wilmington, and on first-day,
a general Yearly Meeting there--(not business:) our
way is not yet clearly opened further than there.

Daniel and I are nearly yoked.
He has a little acceptable service, and Friends feel nearly with us.
I don`'t wish a more open door in their hearts, I mean, to receive us;
though a more open one to receive that cross that rightly crucifies,
would do good to the souls of many.
We are well, and Friends generally so.
I have seen many of my dear acquaintance, to my comfort; with whom truth prospers.
And the solemn, feeling manner, in which church affairs move in meetings,
under divine influence, weight, and harmony, makes me mourn afresh over poor New England,
my beloved country.
Oh! may the only Helper of the helpless, more and more be given way to,
and come into his throne and dominion, in all our meetings.
He can do more for us in one hour, than we can for ourselves in years or ages.

The boat goes soon.
I could write many things, but must hasten.
Dear Warner Mifflin`'s concern for England is doubtless well founded.
But though the Monthly and Quarterly Meetings have approved it,
the general meeting of ministers and elders think he cannot go orderly,
till the Yearly Meeting points out a way for elders to visit the churches,
seeing there is no letter of discipline for it.
And his concern being especially to build up Israel in the line of order,
Friends think he must go _orderly._
He is very submissive, and his concern feelingly weighty.

My heart flows with love to thee, my dear, the dear children, my dear father,
dear father and mother Anthony, our dear, beloved Remember, and all the family;
neighbors Ethan, Sayles, and Dexter, and all their families;
dear Abigail Dexter in particular; cousin Robert and Mercy, with their children;
uncle James and aunt; Woodbury and Hannah; brother and sister Lapham and theirs,
with all my other sympathizing friends.
Do remember dear Asa Smith.
Oh! may he be stayed!
May he be guarded, or danger will attend him.

Do, dear father Anthony, write soon, and often.
Let me know your welfare,--dear Remember`'s condition.
The Lord her God preserve and comfort her.
And above all, do let me hear how my beloved Eunice bears up, and gets along.
My heart is oft in travail for her.
May holy care defend her.
May joy divine console her.
I rest her most affectionate friend and loving husband,

[.signed-section-signature]
Job Scott

[.postscript]
====

P+++.+++ S.--Trials are many, snares many;
but the enemy has scarce got any advantage in any way that I know of.
I soon expect another plunging, but wait in patience and submission.

====

[.letter-heading]
To his Wife

[.signed-section-context-open]
Baltimore, 9th of 4th month, 1789.

[.salutation]
Dearly beloved,

We arrived here last evening.
Today is Friends`' mid-week meeting.
We are not very well, yet rode twenty miles after meeting yesterday.
I wrote thee from New York, and again from Philadelphia.
We were favored in Philadelphia, and two or three meetings this side,
much beyond expectation.
I think I never was let deeper into some of the heavenly mysteries,
than at some times since I left home: but the Lord knows how to deal with all his.
I never knew greater emptiness than has now of late attended me.
We have felt the way much shut up, yesterday quite so,
and for several late meetings almost so,
though we could scarcely feel quite easy to be wholly silent.

Oh! the wonderful difference between having the wide and deep ocean, as it were,
to sail upon, with a full and strong, though steady, gentle wind, and full spread sail,
with proper ballast, and being penned up in some narrow, little, crooked, shallow,
muddy creek, almost becalmed, or what little gale there may be, only by gusts,
and then gone; yea, perhaps a more powerful one,
directly arising from a quite different point of the compass,
almost to the total puzzling and bewildering of the too inexperienced steersman.
There is indeed such a vast difference in these two circumstances,
that I don`'t know that any can fully understand the mystery thereof,
but those who learn it by living experience.
I have almost concluded I am not so much of a mariner
as to make it safe for me to hoist sail,
or weigh anchor, without a very fair wind, and pretty clear sky; yet,
"`not my will,`" remains very much my constant language.

Trials deep attend me; yea, such as would once have been almost insupportable:
but I dare not do other than bear all with patience;
feeling and knowing that all I can endure, is not more than is both justly due,
and will work together for good to my poor exercised soul.
Oh! that he whose I am, and whose I wish still more to be, may not pity or spare,
till not only part,
but all and every part in me that cannot abide the operation of devouring fire,
is wholly consumed, and done away.
I feel the holy fire often to burn in me as an oven, and therein I abundantly rejoice;
for I seem to have no hope at all of uninterrupted happiness in any state,
short of a perfect redemption from all that in any degree defiles.

O my best beloved on earth! may thou and I so yield to that blest influence,
which we often feel, as that no opposition may remain in me, or thee;
but full conformity prevail to every sacred impulse, which it may produce.
For sure I am, there will be a let to peace, a hindrance of full joy will still remain,
till all within us bows, and every rising motion is restrained,
that would an independent sceptre sway.
For Christ, our holy head, must reign, till, by his everlasting, mighty power, all rule,
all separate authority, he has put down.
Oh! then--(blest day may it soon arrive!) Oh! then shall God be all in all.
"`It is finished,`" we can say,
as well as he who on the cross submitted to the will divine,
and through a perfect death to all that death could seize on, conquered even death; yea,
burst its bands; broke through the very grave; and after all his pains and toils,
ascended up on high: where now he intercession makes for man,
and will sufficient aid supply to every willing mind,
to combat Satan in the field of fight; and finally, to overthrow him,
and to reign in undisturbed enjoyment, where his arrows cannot come,
nor all his presentations __aught avail.__

May this, dear love, be thine and mine to know.
It is the best wish my heart can pour to heaven for thee;
and may it not be poured in vain.
And when thou hast interest with the throne of grace, I ask no greater favor,
dearest dear, than this: __remember me.__
And for my preservation, please to pour thy soul in such a wish as I for thee have poured.
Then, when we meet again,
(if God vouchsafe to us the joy again to meet once
more,) our souls shall bless that holy power,
that, far apart, or near, cements together in sincerest bands;
and makes the rightly yoked in love, in sympathy, and true endearment, truly dear; yea,
makes them in himself __each other`'s__ joy.
Amen.

We see not forward with much clearness, but expect to proceed Southward,
and perhaps shall be at the Yearly Meeting of Virginia, at Wayne Oak,
the third seventh-day in the fifth month.
I much desire to hear from thee, and all the family, etc.
Do not delay to write.
Do, my dear father Anthony, write as often as well may be.
Let me know how things are.
Is dear sister Remember living?
Is she better?
Is she kept in the faith and patience of the saints?
I often think of her; often travail for her.
May the Lord bear up, support, and preserve her through all; if she be yet alive.
I think if it may be the Lord`'s will, I can abundantly rejoice to see her face once more.
Let her write, or dictate to dear father, Joseph, Ruth, or some of you,
a line or two (all that she has to impart) to her exercised brother.
And do, my dear wife, let me know freely how thy mind is supported in my absence.
I am often with thee in spirit; and when at liberty, intend to hasten to thee in body.
Oh! trust in the Lord, and resign me to him and to his service.
My tender love is to my dear children.
Keep them in the fear of God, and in the way of truth.
Do, dear children, be good little boys and girls.
Love, and obey your dear mother,--love one another.
Use no bad words.
Tell no lies.
Do no bad thing; and then your poor father will love you.
Learn to read and write, and work.
Don`'t love play too well, but love your books.

My love to all my dear friends, relations, and neighbors, as if named,
especially to my dear old father.

We have now been to meeting here, quite shut up, but patient and content;
for we cannot open; and flouncing does but plunge deeper in the mire.

I am, with fullness of fervent affection, thy much tried, yet still preserved husband,

[.signed-section-signature]
Job Scott

[.letter-heading]
To his Wife

[.signed-section-context-open]
Baltimore, 10th of 4th month, 1789.

[.salutation]
My dearest,

I wrote thee yesterday, from this place, where we arrived the eve before last.
Were yesterday at meeting here, quite shut up; as at several late meetings,
though greatly favored at divers before.
We seem hitched here; see nothing that holds us, nor any way hence;
are waiting in patience.
What, or whether any thing further will open, we know not.
If not, thou may before long see me again: though I have no such expectation.
I thought I would, if I could, avoid my old path; but mine it is, and I must walk in it;
and am thankful I can yet say, I am content.
My yesterday`'s letter was a pretty long one, so I forbear much enlargement now.
I also wrote one to our dear father and mother.
I omitted yesterday to mention,
that our dear friend Nicholas Waln is expected to attend our next Yearly Meeting.
I think he has increased in weight considerably, since I was this way before.
His preaching did my soul good.
May he be received as a brother beloved, and prove useful in our land.
I don`'t fully know his prospects.
He did not see much more with clearness, than Yearly Meeting when I last saw him.

This is my fourth to thee, dear love.
Oh that I might get one _from_ thee: if I dared, I should long for it.
Don`'t delay it, I beseech thee.
One or more is ardently expected from father Anthony; let it not be long first.
Love to you all, though the _common,_ is far from a mere _formal_ conclusion;
for the fullness of what I oft have to feel of it, is beyond the ready reach of words;
so rest thine, etc.,

[.signed-section-signature]
Job Scott.

[.letter-heading]
To his Wife

[.signed-section-context-open]
Alexandria, in Virginia, 25th of 4th month, 1789.

[.salutation]
Dear wife,

We yesterday set foot in this state, and expect to stay here till second-day morning;
and then proceed southward, so as to reach the Yearly Meeting, at Wayne Oak,
on the third seventh-day in next month, taking meetings in the way.
This is the fifth letter I have written thee since we parted,
and not a word have I heard from thee.
I grow anxious to hear; indeed,
was not my own will more than usual kept under in this painful journey,
I think the deep distresses I have to pass through,
in addition to the almost longing desires to hear from home,
and close thoughtfulness about you, would be sufficient to divest me in degree,
of a proper resignation.
But, blessed be he on whom my soul seems firmly anchored,
I have yet been kept in patience through all;
though it seems at times as if I could scarcely bear up any longer.

We have had a number of precious meetings, as much, or nearly as much so,
as ever I have known.
I don`'t know but rather more strength and clearness
have sprung out of perfect weakness and obscurity,
at some few times, than I have known before.
But since we left Philadelphia and Wilmington,
our good times have been mostly where the people were chiefly not Friends,
principally Methodists, who have got to be a kind of ranters,
as to some odd and vehement actions, yet mostly, as far as we find, moral,
and many of them very tender and reachable.
Much openness we find among them,
and much need they have of being guarded against _making_ haste, against imagination,
and violent self-activity.
Perhaps more devotion, such as it is, has scarcely been known, than is among them.
And, however hurried and mistaken they are,
I hope the Lord owns the sincerity of many of their souls.
I cannot find there is much tenderness among their settled teachers.
I believe _they_ strive hard to prevent their reading Barclay, etc.,
and to kindle and keep up a burning impetuous activity and devotion,
that shall admit of little or no standing still; yet I hope some will, in time,
find the sure foundation.
I have thought it may be much for their sakes,
that I felt such almost irresistible impressions to visit this land.

Truth is at a very low ebb indeed among Friends, and divers meetings,
formerly large and flourishing, exhibit scarce any thing now but desolation.
When we are at meetings with Friends only, we suffer almost unto death,
and it then seems as if we could scarcely get along much further.
Negro slavery has almost ruined this country, both as to religion,
and the outward soil of the earth.
Friends`' children have been brought up in idleness.
Many scarcely called on to do an hour`'s business of any kind.
From infancy to settlement in families of their own,
they have spent much of their time in riding about for pleasure.
The consequence has been almost the extinction of society.
Oh! that my children may be brought up to industry.
Let them work, and read, and write, as much as may be good for them.
Some Friends`' eyes are opened in this land,
and a few families bring up their children to business; a _very few_ have,
whose children are now grown up.
Except these, there is little appearance of the Quaker among the youth in these parts.
O happy New England! that thy sons and daughters have to do for themselves,
and are not so generally endangered by that idleness, which a tyrannical command,
and disposal of fellow men, has introduced in these, as to religion,
almost desolate states.

O my dearest inheritance, short of things divine! bear with my so expressing myself;
for things have so turned in my mind since I left thee,
that it seems to me I shall never have much more enjoyment of all that this world affords.
I seem cut out from it all, and have before me as to that a dreary journey through life;
yet +++[+++I]
do not repine, fully believing if I press rightly on,
I shall finally have a humble mansion, where the wicked cease from troubling,
and my weary soul will be at rest.
There may thou also ever reign with him,
and those who thither find the way through scenes of woe;
at least through suffering scenes and many a pang.
I do indeed still find liberty to promise myself much satisfaction in thee,
and our dear babes, if we should live, and be allowed to enjoy each other`'s company.
But as to other things, wherein I have sometimes strove to find satisfaction,
I am almost ready to say, with one I have read of, "`All things else forsake me,
save my duty, my God, and my prayers.`"
Though I might not of myself have worded it just so.

Think not, by all this, that I mean to abandon a proper care of family affairs.
Never had I less thought thereof; but it must be from necessity,
not from expectations of much satisfaction in this world.
I almost fear thou and others would suspect my head was turned a little,
should I mention the gloom that seems to spread over, and surround all earthly prospects.
Never did things appear to me before just as they have since mid-winter.
I feel willing, in great degree, to suffer all that is best for me,
and to have as little enjoyment of earth as I deserve,
(perhaps that is none,) and yet am also willing to have as much as I can in the truth.
For I have no faith in crosses of my own making or imposing.
But, alas! this is not our home.
Our scene of enjoyment lies beyond this world,
and in that godliness which is true gain below.

Oh! how have I been detained!
How have things on this footstool held fast my soul
from that full accession to the mount of myrrh,
which is, even in this state of existence, not only attainable,
but the only undisturbed resting place for the mind of man.
Oh! let us, my dear partner, let us count nothing too dear to give up,
that we may win him, who only is the pearl of great price.
Let nothing hinder our, not weak, but vigorous breathings of soul,
after him and the joy of his all-consolidating presence.

I expect it will be difficult for thee, or others, to get letters to me,
after the Yearly Meeting at Wayne Oak, in this state.
But do write me as often as thou canst, and some of thy lines may reach me.
I never so much desired to hear from thee, as since I came into this land.
The time looks very long that I may be from thee;
even if it should not be longer than I first expected.
It may not be so long, but I know almost nothing how long it may be.
I have been with thee in dreams, a few times, to great satisfaction.
But I lately dreamed my dear Lydia fell in the well, and was almost drowned.
I drew her out alive, with great joy.
Do keep them from the well, and the curb up in good order.
It may not be best to despise even dreams.
I also wish thee, and all the family, to be very careful of fire.
Secure it well at night, nor leave it carelessly in the day.
I want much to know how thou art borne up in my absence;
and whether our dear sister yet liveth.
I feel much for her, earnestly desiring, if she lives, she may be kept in,
and consolidated by the truth; believing, if life is lengthened,
she will have but little other joy than what truth alone affords.
But perhaps, before this time, she is no more in this probationary state.
Well, if she is gone, I hope she`'s gone to endless peace.
Of these things, what thou canst, pray let me hear; also, my dear children`'s welfare,
as also, my beloved father`'s. My love is to him, and thee, and all.
Tell my near neighbors, I think of them with a degree of affection;
as likewise my relations, and friends.

Dear father and mother Anthony, I don`'t find much to add, to send you,
but endeared love, including all my dear brothers and sisters.
May they all seek the Lord for their portion,
and choose the God of Jacob for the lot of their inheritance.
Do, dear father, not neglect what would afford me so much satisfaction,
as to receive frequent accounts from thy pen, how things are with mine and thine.
Indeed, I almost say, all mine are thine, and thine are mine.
The band is increased, the knot is stronger tied.
May nought prevail to sever, loosen, or untie.
Be kind to those I left in charge with thee.
And in return, may Heaven to thee and thine, be kind.
I lately read in [.book-title]#Elwood`'s Sacred History,# that Moses, when called to visit his brethren,
in their Egyptian afflictions, left his wife and family, with Jethro, his wife`'s father,
and received them of him, in the wilderness, after they came from the house of bondage.
Thou canst, perhaps, as well conceive as I express, the feelings of my soul,
when this revived, in fresh remembrance, her whom most I love, with hers and mine;
and how I left them all with thee, and with the rest of thine.

Daniel has been ill, but is better.
We get on but slowly, though hope to mend our pace.
The way has seemed shut up, but we now look forward; are nearly united; up together,
and down together, at almost every turn.
Daniel says, he came to be my companion.
He is truly made eminently so.
Deep have we dipped together in tribulation, and feelingly partook each other`'s joy.
His love is to my dear Eunice, and my own father, with thine and mother, etc.
Give mine to all my friends in town and country, as thou see them.
Thou know who they are.
Friends`' arms are open enough to receive us;
and those who have trod the path have deeply sympathised with us, in inward pain;
and also joined with us, in songs of inward heartfelt joy.

Farewell, dear wife, and all, farewell,
in that which never fails to keep the lamp of love alive,
where it is in fullness known and lived in.
In which, with fullness of affection, I remain dear love, thy loving, exercised husband,
and, dear parents, your dutiful and grateful son,

[.signed-section-signature]
Job Scott

[.letter-heading]
To his Wife

[.signed-section-context-open]
Virginia, 35 miles below Alexandria, 4th month 30th, 1789.

[.salutation]
Dear wife,

Trials of various kinds, through life, betide thy deeply proved husband.
Some of those he has had to pass through, since he was thine,
thou art well acquainted with, and some the Lord only fully knows the depth of.
Almost every objection that one could have, I seemed to have, to excuse my leaving thee,
to perform the present embassy.
But all my objections together, would not afford any consolation of mind,
in the thoughts of withstanding my duty.
I gave up.
But before, and since I came from home, my portion was, and has continued to be,
mingled much with wormwood; although through unmerited favor,
my cup has sometimes overflowed with unmixed sweetness and joy.

But, how short-lived are our agreeable seasons!
A new, and not a little afflictive probation is now allotted me.
My dearly beloved, my bosom friend and companion, on whom I often leaned and relied,
in times of trial, in this remote land, is, and has been so much unwell,
that he has concluded to leave me.
We both much doubt his being able to go through the southern country.
If I dared to do it, I should urge his continuance with me, but I dare not,
lest I should have to leave him behind me.
On the other hand, if I dared to return home with him, I surely would do it.
I scarce know how to look forward, and to face, alone, every varied trial,
that I seem in full expectation of having to encounter in this journey.
But when I turn my back on it, and look home, as I have again and again tried to do,
it seems like refusing to do an important part of my most important day`'s work;
and such a part too, that without my being at least given up to go through,
and finish it, I can have no hope of receiving my penny, at last.

Oh! the bands, the necessity, that some are under, of going whither,
in their own creaturely choice, they _would not._
Well, let me not repine.
Let me not go on too grudgingly.
For, adored be the name of him, who thus binds, and brings under this necessity,
he has done more for my poor soul, than I can ever requite him for.
He has washed me in his own blood; has redeemed my soul from the worst of thraldom;
has himself become my bow, my battle-axe, and weapon of war.
Oh! therefore, let me never revolt from his law again,
nor turn my back in the day of battle; nor decline going into the hottest of the fight,
when he commands, and in his service.

I have not been so long together, tried with entire insensibility of all good,
in this journey, as before.
But the weight, Oh! the pressure and weight of the work, both in meetings,
and for hours before they begin, is far beyond what, in general, I ever knew before;
insomuch, that I am, at times, ready to cry out aloud under it.
But then, I remember, that he that loved us, before we loved him,
has endured for my sake, far more exquisite distress,
than it is probable I can ever have to bear.
And I also am often put in mind, that if _through_ and _after_ all this tribulation,
I can be allowed au humble mansion in the kingdom of true rest,
I cannot have cause to murmur; but abundant cause to shout aloud,
and sing redeeming grace forever.
By thoughts like these, has my mind been very frequently and suddenly hushed and stayed,
when almost ready to give way to an agonizing,
and overflowing torrent of distressing sensations.

How often have I wished I could, if but for a few moments,
pour forth my grief into thy bosom,
that I might feel the soothing influence of a few heartfelt, relieving,
sympathising sighs!
But, no; I must not yet that bliss enjoy.
Instead thereof, must bid farewell, and part with him, who only has that place, in part,
supplied; and lean henceforward on my God alone.
Oh! may his mighty arm be known by me, in every trying scene.
And may the same, my dear, bear up thy drooping soul; till we once more,
(which yet I trust we shall,) may meet again; and face to face,
relate what varying scenes we`'ve waded through; yea, in each other`'s bosom pour,
not as by pen and ink in part, but unrestrained, our tale of woe, though not unmixed,
I hope, with solid joy; with thanks to God for favors, undeserved; and not the least,
that love and life are ours.

I wrote thee from Alexandria last seventh-day.
This is my sixth letter.
I have a solid satisfaction in writing to thee, and some relief of mind.
But how much more so would it be, if I could as often have a line from thee.
I have not yet had the satisfaction of one word from home since I left it.
But I must wait with patience.
It is your welfare I want to hear of, and as that depends on the Lord,
to him I must still recommend and resign you.
Keep near him, O my dearest love, keep near him;
and strive to keep all mine and thine as near his holy way as possible.
For, though a thousand slight it on the right,
and ten thousand turn from it on the left hand, it remains the only way of safety.
"`To whom shall we go?`"
He only "`has the words of eternal life.`"

Dear Daniel and I part, as we have travelled together,
in near and dear harmony and affection.
That the Shepherd of Israel may preserve him, till safely returned to his native land,
and thence, be it long or short, to the end of his pilgrimage here below,
is the fervent desire of my soul.

My dear love is to thee, our dear children; my beloved parents, all three;
dear sister Remember; my dear brother and sister Lapham;
all my dear brothers and sisters; the neighbors, relations, and friends.
So, for the present, farewell, my dear love, in much endearment and heartfelt affection,
farewell.
From thy lonely mate, though sorely tried husband,

[.signed-section-signature]
Job Scott
