== Chapter III

To his Wife

Wayne Oak, 13th of 5th month, 1709.

Dear wife,

I am now in a very shut up condition; was last first-day at meeting here.
After meeting, went ten miles towards a meeting place, thirty miles below,
intending to have a meeting there, and return here to the Quarterly and Yearly Meetings,
now soon coming on.
But my way was so clouded I could not go forward; so I returned on second-day.
Indeed I was, and am quite unwell; my stomach, bowels, head,
and whole nervous system much out of tone; yet think I should have gone on,
had my way not shut up.
Yesterday I took medicine, which weakened me much.
Oh! said I in my heart, that my dear Eunice could now be with me,
to sympathise and assist in my distresses,
both of body and mind! as I felt assured thou would have done,
if I could have been favored with thy company.
But I resigned.
Perhaps it was a virtue of necessity; for what could I have done but resign.

I remain in as stripped, empty, and desolate a state, as ever I knew;
have no kind of inward enjoyment as to any thing divine,
unless I reckon upon a small degree of faith and patience.
However, I am not so distressed or cast down as I often have been;
though I feel as little like rising again, as I ever felt, as far as I know.
I mean to attend the Quarterly Meeting, (the select is tomorrow,) and the Yearly,
and then if my way does not open to go forward, I must return homeward;
for it is in vain to press forward in the dark.
And I fully believe, he that called me away from thee,
and all my dear connections in life, is able and willing to open with clearness,
the way to any service he requires.
So if he does not open, I shall think myself at liberty to return to you again.
Yet, as Maryland Yearly Meeting at Baltimore would be apt to take me on the return,
and some other detentions,
I thought best to try to forward this salutation of endeared affection,
and information of my present state, thinking it may reach thee before my return,
especially as my path, heretofore, has been much out of my sight, as a man.
So that if I get back to the Yearly Meeting at Baltimore, thinking then soon to see home,
I may be turned away, round some way as yet quite unseen, into the Carolinas,
etc. or otherways over the mountains.

It is much my choice, seeing I am now so far southward,
to go now as far down as I am to go.
But, alas! what can my choice do in it?
If it is the divine will to turn me back awhile,
he can spread clouds of impenetrable darkness between me and the south.
And if, after I have been through what may be for me to the northward,
it is his will I go south again, he can make darkness light before me.
Be it therefore as he will, and not as I will.
I stand much given up.
I find that each degree of my own will is an enemy to peace: therefore +++[+++I]
wish my own slain, as often as it strives to rise.
I have been led much in a constant death to it, in many respects,
more so than ever before: and I find it must be so, or I plunged in perplexity.

Well, my dearest, whatever becomes of me,
may the everlasting Shepherd hold thee in his holy hand, consolidate thy soul,
bear up thy spirit, protect, and provide for thee, and all mine.
If I may be allowed to return to the enjoyment of you again, either soon or late,
I trust I shall be willing and glad to do all within the reach
of my poor abilities for your comfort and accommodation.
Meanwhile, my beloved, let thy trust be in the Lord,
and endeavor to renew thy acquaintance with him.
For though I have no fresh sense of the benefit thereof,
otherwise than by faith and recollection,
yet it is the best thing I can recommend thee to, for comfort, in life or in death.

I never have heard a word from home, till, a few days past,
I received a very welcome letter from dear Moses Brown;
and though that was dated 13th of 4th month, it gave me much satisfaction,
both as to the other contents, and the rejoicing information of thine,
and the family`'s welfare; especially as he mentioned thy looking pleasantly,
or appearing "`agreeably pleasant.`"
May my heavenly Master so sweeten thy cup as to make thee often appear so,
is my heart`'s desire to him on thy account.
I have not yet received any other letter,
though Moses mentioned our dear father`'s having written one for me.

19th. I am much better, almost well; good appetite,
and much better digestion than for divers weeks past.
But what is better than all that,
I am admitted again to have free access to the tree of life,
in the midst of the paradise of God; and have, in the Quarterly and Yearly Meeting here,
found, though things are low, that the "`shout of a king`" is still among us,
and have been made to shout (even aloud) for joy, in a sense thereof:
so that now I can encourage thee, dear love, in a degree of living sensibility,
to "`trust in the Lord forever,`" for it is a certain sealed truth,
that "`in the Lord Jehovah is everlasting strength.`"
Trust in him--Oh! trust in him in every trial.
To whom else can we go?
He, and he only, has the words of eternal life.
Choose him for thy joy, thy portion, and thy peace.
Then shall we, as we both so choose, whether absent or present,
be one another`'s joy in the Lord.
Thou hast often been brought into my fresh remembrance,
with the most endeared and heartfelt affection, since my last parting with thee,
such a parting as I never knew before.
Never did I before, when absent, so ardently wish to see, and be with thee again,
as for certain moments, at divers times, I have now done;
yet durst not give way to indulge even this wish, in its full emotions,
feeling that it would lead me from a proper resignation.

My way is not yet opened how to proceed,
(Yearly Meeting not yet over,) but I don`'t see much ground
to expect I shall be at liberty to return to thee,
my dear, perhaps not these many months yet.
There are divers places to which my mind has glanced,
where there are no Friends`' meetings.
I have been very satisfactorily at several such,
and don`'t much expect I have done with them yet.
I had an open, powerful meeting at Richmond, called the principal place in Virginia.

Is there any need of my desiring thee to be careful
in bringing along our dear infants in the right way?
I hope thou wilt never neglect it.
Give my dear love to them.
Tell them their dear father, who dearly loves them,
wants them to be sure to be good little children.
Oh! how my heart has moved in me, when I have remembered my last parting with them,
as well as with thee, especially the dear little helpless lamb,
which most immediately claims thy unremitted attention.
Oh! love him, and take all due care of him, for his poor father`'s sake,
as well as his own.

20th. I am now given up to endeavor to have divers
meetings elsewhere than in Friends`' meeting places.
Perhaps I must spend near a week without getting much, if any further southward, taking,
if way is made for it, about five or six such meetings, and one or two, in the way,
among Friends.
O my beloved!
I depend on it, without any kind of doubt, that many painful, dark,
and deeply depressing seasons will attend me, if I go through; but darker still,
and far more dismal,
is the prospect of turning my back on whatever the light opens clearly,
and sets before me.
So that I have now little or no hope of seeing thee, for what will seem to me,
(such is human weakness,) a long time.
However, I mean to make as short work as I can with safety;
but had rather stay some time, now +++[+++that]
I am out, than ever to have to encounter this dreary climate again.
I don`'t speak of outward climates, for there is little in them as yet to me.

My dear love is to my poor old father.
I hope he may be preserved in health, patience, and good nature in his old age;
witnessing more and more of a victory over all heats and passions,
that so the remainder of his days may be comfortable and happy.
My love to all my relations, friends, and neighbors: and let love abound in the family,
and in the neighborhood.
This is the seventh letter I have written thee, since last I saw thy face, my dear.
Oh! that I could receive one with thy signature.
It is what I much desire.
But if I may, or may not enjoy that happiness, I remain, with ardency of affection,
thy deeply exercised, loving husband, and the affectionate father of all thy children,

Job Scott

To Remember Anthony, Providence

Wayne Oak, Va. 5th month 18th, 1789.

Dear sister,

I have often had thee fresh in my remembrance, since last I saw thee,
and divers times have been almost ready to write thee a few lines, as things presented.
But the uncertainty of thy being in the body,
or having made thy escape to a better mansion, has hitherto restrained my pen.
But my friend Moses Brown having informed me, in a kind letter of 13th of 4th month,
that thou wast slowly mending, I not only rejoiced in the agreeable information,
but felt more liberty to write; although even now,
the thought that I may be addressing one, whose eyes may never read these lines,
almost makes me hesitate; but be that as it may,
my soul salutes thee in the good will of him that
dwelt in the bush that burned and was not consumed;
which wonderful manifestation of his power,
seems to me not altogether unlike his dealings with thee; for indeed,
marvelous in my view, has been the preservation of thy natural life,
through circumstances of extreme sickness and affliction,
which it might much more rationally have been supposed,
would have consumed thy frail tabernacle long before this day,
than that thou shouldst have been, on the 13th of 4th month last,
in the land of the living.
Indeed, I have adored his power, his goodness,
and the making bare his eternal arm in and respecting thee.
May I ever adore his holy name, till I go hence no more to be seen of man.

And, O my dear sister! may it be thy unceasing and unabated desire and engagement,
to bless, magnify, and adore his wonderful workings,
and the displays of his matchless providence towards thee, and for the preservation,
bearing up, and consolation of thy drooping deeply exercised soul,
under extremity of trials, both mental and corporeal.
And may thou not only adore, but adoring,
be led to trust in him as a never failing refuge
and supporter on every future occasion of adversity,
however discouraging or painful; for if he continues thee in the body,
he will be with thee if thou dost not forsake him.
Can he that has so wonderfully been with thee in six troubles forsake thee in the seventh?
Nay, verily; his faithfulness can never fail.
His love cannot possibly wax cold to those whose faithfulness and love to him are maintained.
Only cast thy care upon him, and thou art sure of preservation, sure of comfort,
and that in the best time,
though he may withdraw for a season sufficient to teach thee that his work is before him,
and then, that when he cometh, his reward is with him.
I have at least some experience of these things; and though emptied, yea,
very lately emptied of all, and stripped inwardly, as naked as I came into the world,
and tried to an hair`'s breadth, yet blessed be his name forever,
he never yet let me sink so low as not to raise me up again.
I have had to exalt his praise, and sing his glory in the assemblies of the people.

It is now Yearly Meeting here.
Yesterday +++[+++there were]
two large meetings for public worship,
wherein he evinced that his own eternal power is the authority of our meetings,
and that he himself is president amongst us.
May I never forget how he has helped me through many and various besetments,
and never more be afraid to trust in him, even though he slay me.
His compassions fail not, they are new every morning.
Therefore he is worthy of being not only praised, but, what is often more difficult,
and a greater test of true love on our part, faithfully obeyed,
in everything he may require of us.
Indeed it seems at some weak moments, (when I look outward,
though inward enough at the same time to see and feel my own great weakness,)
as if I could scarcely live through all that he lays upon me,
and requires of me.
Yet I find as I give up without reserve and in absolute dependance on his aid,
I am carried through all from time to time;
and perhaps there is nothing more difficult to come, than what has already come.
How then can I doubt?
How can I disbelieve?
Indeed, I cannot as my eye is single,
for then I see there is nothing impossible with him,
who has marvellously shown himself to be, and to have been on my side,
and never to have failed me, when I have not failed to have my bow abide in his strength.
Indeed when I have vilely cast away the shield of the mighty,
what marvel if the enemies have prevailed?
Why, hereby we learn that there is not another name given under heaven,
whereby men can be saved.
Let us then carefully attend to it, and see that we neglect not so great salvation.

I do not glory in my experience.
To me belongs blushing and confusion of face.
But I glory in the power of the cross of Christ, and in the help afforded through him;
and my soul can declare that he lives forevermore.
Death hath no more dominion over him, nor over those whose crucifixion, death,
and burial with him have been complete, who have resisted unto blood,
striving against sin, and in this resistance, have fully offered up all, body, soul,
and spirit, a living sacrifice made by fire, a burnt offering to the Lord.
Oh! my sister, here is trying work.
Let this cup pass from me, is a very natural request;
but if it is not possible for this cup to pass from us, except we drink it,
Oh! that we may truly say "`Thy will be done.`"
And I assure thee it is not possible for it to pass from us any other way,
than by our drinking it, or what is awfully more against us, our remaining, at least,
in degree, unvictorious and in captivity; for to this hour we must come,
and this hour with all its agonies we must endure; yea, all the wormwood,
and all the gall, or we shall not be able to say, "`it is finished.`"
Without blood even under the law there was no remission.
It remains the same, and though Jesus has once passed through it all,
and trod the winepress alone, he has not thereby exempted us from the like baptisms.
On the contrary he queried with those who seemed desirous to sit with him in his kingdom,
"`Are ye able to drink of the cup that I drink of,
and to be baptized with the baptism that I am baptized with?`"
These are the terms still.
It is true, remission of sins that are past, is only through his blood,
but as to actual sanctification,
it is they only who suffer with him that can reign with him.
And if we are planted with him, in the likeness of his death, we shall arise with him,
in the likeness of his resurrection.
Be it therefore, dear child, thy willing experience to die daily with him,
who has set us an example that we should follow his steps.

If any part of thy unworthy brother`'s experience can afford thee
any encouragement to press forward in this work and warfare,
it is all freely dedicated to thy service, and furtherance in the way of life.
Thou hast known much of the travail of my soul, the strugglings and breathings,
and somewhat of the besetments attending my pilgrimage,
and after all my varied probations, ups and downs, shortcomings and preservations,
this is my verdict, this is my report:
strong is the Lord God on the side and in defense of all
those that love him and keep the word of his patience.

Let my best beloved, my dear wife, our dear parents, brothers and sisters,
have the benefit, if any there can be, of these free communications to thee;
and if thou art no more among the living here below, but gone to a better habitation,
let those who survive, excuse the flowings of good will to one,
I truly loved and travailed for; and though it even should be so,
that these lines reach not thine eye, nor thine ear, they may not be wholly lost.
However, if they ever do obtain thy attention,
know thou that they come accompanied with pure good will and cordial affection,
warm from the heart of thy often deeply tribulated brother,

Job Scott

P+++.+++ S.--If thou still livest, and art able to indite, and hast any thing of thy exercises,
health, or otherwise, which thou wishest to communicate, I would have thee attend to it;
if not, I wish not to put thee upon it.

To Moses Brown, Providence

Wayne Oak, Va. 5th month 18th, 1789.

Dear friend,

Thy very acceptable letter, of 13th of 4th month, I received the 9th of this,
at R. P.`'s, at Curles, who just then received it under cover from J. P. It was, indeed,
very acceptable, for I had not heard a word from home since I left it,
nor indeed have I yet, except thy letter only.
Why father Anthony`'s, that thou mentions, is not come to hand, I know not.
Thou may well suppose how anxiously I wait and wish to hear further from my own family,
and from my friends, as well as how eagerly I fed, indeed still feed,
upon the contents of thy kind information, especially my family`'s health,
but most especially the pleasantness thou saw in my dear bosom companion.
May the Lord still bear up and comfort her.
May her days and months indeed roll on pleasantly, till I return to her,
and the dear little ones, which for the precious cause`' sake, I left in her bosom,
is the desire of my soul for her;
and may her and my friends not be unduly unmindful of them.

Most likely before this reaches thee, thou wilt have received one from me,
addressed to J. C. and thyself, giving account that I am left alone; my dear Daniel,
having, through bodily weakness, left me and returned home.
Oh! what a trial at parting, and since.
J+++.+++ L. arrived here the day before yesterday,
with certificates to attend this Yearly Meeting now (or these days) sitting.
He tells me he heard of Daniel`'s passing through Philadelphia, somewhat mended,
but heard of no letters for me.

I have, since parting with my companion, passed through a most wintry season,
stripped naked, and exposed to the cold;
but through remembrances of former deliverances and help, underneath scarce perceived,
I was in good degree willing to suffer.
I thought I might likely return home after this meeting, and indeed, don`'t know,
but I must as yet; for as it has been, and is with me at present, I dare not go forward,
yet I don`'t much expect now, but that the way will open to go on.
This I must wait for, and if this fails I must return.
My path is a tried one, much and often shut up;
though the two meetings for worship yesterday, and the one today,
were large and very open; much gospel labor was bestowed,
to how much purpose I dare not say, but fear but very little to too many.
However, I am now, through favor, comfortable both in mind and body,
though lately much otherwise in both.

Thy account that my dearly beloved sister rather gains strength, though slowly,
is very agreeable, though I had long ago resigned her to the divine will.
If she is continued in life, may her life be continued hid with Christ in God,
where all true consolation is hid also.

Perhaps thou may yet have to think further,
"`whether thou might not as well have been`" in this country as at home;
though I am willing to hope with thee,
that "`Providence has wisely directed in the matter.`"
I hope the same wise direction may be attended to in the controversy about oaths,
and also about slavery.
Keen strokes of wit, though they hit their target, and are mortifying to the opponent,
don`'t always, even where they command silence,
make way for the spreading of the testimony of truth,
so much as a more moderate and meek reply might do.

I am glad, E. M. gets forward acceptably.
May she still prosper and go on from stature to stature.
Thy desires for my preservation,
etc. were to my comfort and the renewal of true brotherly affection.
May I still have a place in the remembrance and prayers of all who wish well to Zion.
Great indeed is my need, and often, yea, far oftener than the morning,
are my cries for preservation, to him who only has the power.

Thou expressed the satisfaction some of you had,
in hearing we were acceptably received among Friends.
I have grounds to believe we were so, and that I am so here.
I have every mark of it that I wish,
nor am I at present afraid of their manifestations of it,
for I go as heavy laden as I can well bear, most of the time;
and even when not so closely stripped as at some seasons, the weight of the meetings,
which I often feel for hours before they begin, as well as in them,
is such as renders me almost unconversible.
This kind of burden is much greater upon me, than ever before this journey,
under which I am fully satisfied, many times for hours before meeting,
of much approaching service; and feel it as evidently, or nearly so,
as when constrained to stand up.

I find when truth is felt to rise, or its stream to run somewhat like a torrent,
a great difficulty in keeping enough in the moderation; but in divers other meetings,
the life is so low from first to last, that I can but just find the safe stepping stones,
and advance from one to another of them with much weakness and moderation.
But even in this, if I keep as low as the seed, I find peace.

In true love and affectionate good will to thee, my dear friend, and all thine,
I conclude and am thy exercised friend,

Job Scott

P+++.+++ S.--J. L. wishes his love mentioned to thee, thy wife and children;
and by thee to Patience Brayton when convenient.

To his Wife

First-day morning, 31st of 5th month, 1789.

My dearly beloved wife,

I am now at Gravelly Run, over James`' river, Virginia;
have been to a number of meetings on the other side,
among people mostly not of our society;
which in my last I informed thee I was then just given up to engage in:
but I found little satisfaction in it.
Indeed I have found little in any thing, since the date of that letter,
about two weeks past, till yesterday.
It has been one of the most stripping times I ever knew.
It seemed nearly impossible ever to enjoy good, in any considerable degree, again.
And yet I found something to do; hard work indeed! almost like doing without strength.
Is not this to "`walk with moderation in the valley, without might?`"
Truly,
I have been deeply experiencing the gloom and distress which
I had such awful forebodings of before I left home.
But through some, (not to say much,) experience of the disadvantage,
rather than advantage, of greatly sinking under these strippings,
I have been mostly more cheerful than in some former trials;
yet scarcely able to be sociable at some pinching moments.

It came into my mind yesterday, before meeting, when I felt as empty as an empty cask,
and when it seemed as if I could never again be filled,
that if unexpectedly the meeting should prove a time of favor, I should be ready to say,
"`Surely the Lord is in this place, and I knew it not.`"
But when the time came, it was indeed as good of a time, as almost any I have ever known.
Waters broke forth in the desert, and out of the parched ground flowed springs of water.
Oh! that I may ever trust in him, who knows when and how long to empty,
and why he does so: seeing, after he has emptied,
he finds an acceptable time to pour his water into his poor empty buckets,
and thus to cause his tried and thirsty seed to be in many waters.

Thine, and thy dear father`'s very welcome tokens of affectionate remembrance,
dated 5th of 4th month, I received last second-day.
And truly,
Solomon knew what he said in comparing "`good news from
a far country,`" to "`cold water to a thirsty soul.`"
I was in the midst of my greatest discouragements;
had long waited for a line of consolation,
till I had even despaired or ever seeing the letter that my kind friend
Moses Brown had informed me our dear father had written me;
and as I had got where it might be difficult for letters to find me,
I did not much expect to get any very soon, if at all;
and this added not a little to my trial: but when the letters came,
my bosom beat for joy, though they were of so old a date.

Thine, indeed, was short, but sweeter to my taste than honey, or the honey-comb.
O my dearest! never give way to think thou canst not write; for, verily I say unto thee,
thou canst.
And if thou couldst feel the satisfaction I felt, and still feel in thy few lines,
thou wouldst not be backward to let me know thy heart,
if it were but in a few broken sentences, flowing from that sacred repository of mine,
where are centred, (as to things short of heavenly,) most of my joys.
Oh! write me again, and again, dear love.
I have written thee seven before this; this is the eighth.
I grudge not the time, nor the pains; though pains herein I have none.
My pen moves with pleasure whenever it is moved towards thee.
I have divers times of late, had the satisfaction of thy company in sleep.
I scruple not to call it a satisfaction; for so it was to me.
But enough.

My way has been much hidden; clouds have intervened;
that I have thought much of returning, even since my last;
but could never feel the bands taken off.
I expect I must crawl on through the other southern states, perhaps mostly,
almost without might.
But the divine will be done.
I have received too much kindness from him whose I am, and wish ever to be,
for me now to be willing to turn my back on his service,
or draw away my shoulder from his ark,
even though he should keep my feet much of the time in the very bottom of Jordan,
as has of late been mostly the case.
For, blessed be his holy name, the stones of memorial are now and then brought up,
with songs of heartfelt joy, as was yesterday eminently the case.

I have none principally to recommend thee to, but him that by day sleeps not,
nor slumbers even by night.
On him, dear heart, rely;--he will succour thee and thine, if trust is in him,
as it ought to be, reposed.
No doubt herein overshades my mind.
To him, in confidence deep-anchored, I resign my all, and therefore thee,
as most beloved of all that`'s truly mine,--and with
thee those dear pledges of his love and ours;
as, next to thee, a place they surely claim, and in my heart a place they surely have.
Oh! teach their tender minds the fear of him, without whose fear, true wisdom none attain.

I have a number more meetings to take in Virginia, going down; and if I go through,
there will be divers more on the return, further back in the country,
both in Virginia and Maryland.
So that if I get to the Yearly Meeting at Philadelphia in the fall,
I must have one or two considerable journeys afterward, as, over the mountains,
and what is called the eastern shore of Maryland, and in the Delaware state,
where Warner Mifflin lives--a peninsula where I have not been.
I have had a severe cold, and been much unwell; but now am nearly well.
My dear parents must excuse me this time; opportunity fails me to write them.
My dear love is to them all three; all the children, theirs and mine; all my relations,
friends, and neighbors; and most of all, dear heart, to thee, wherein farewell.
I remain thy faithful and affectionate husband,

Job Scott

To his Wife

Pascotank, North Carolina, 20th of 6th month, 1789.

Dear wife,

I got to Carolina last second-day, and have, in order to get forward,
had six meetings in the last four days.
But it is almost too much for me; the weather being very warm, I sweat much,
especially in meetings; so that I am not so well as I have been for several weeks past.
Since my drooping health about Yearly Meeting time in Virginia,
I have been uncommonly well and hearty, till now a few days.
Hot weather began here, (or where I was,) about the time I began to be well,
and suited me much better than the colder weather before.
But its steady continuance, and increasing degree, with much fatigue,
are almost too much for me.
However, I am about, and am better than yesterday;
though I was yesterday at two meetings ten miles apart, and after the last,
which began at five o`'clock in the afternoon, I rode ten miles more.
So that I hope I may not be much unwell this time.

Dear John Lloyd has been agreeably with me since Yearly Meeting in Virginia,
till last first-day, when,
after a most heavenly and almost transporting opportunity
with a considerable number of Virginia Friends,
whose faces we expected to see no more,
we were obliged to submit to a separation ourselves,
as his certificate did not extend here.
I expect a dear friend (James Ladd) to meet me in a few days, from Wayne Oak, Virginia,
to join me for at least a short season.
He is an approved minister.
I know little of his gift.
Friends speak very well of him; and I have reason to think so of him,
I am glad I am to have his company; though being alone is not so trying as it was.
I find I have but one to depend upon, and am happy in being reduced, I hope,
very nearly to an absolute dependance on him; and find the more I am so,
the more he is all things to me;
so that there has seemed to be little or no lack for some time past.
It is true, I am pretty often quite shut up; but believing it is best so,
and quietly in faith submitting to it, the way soon opens again,
with unexpected strength, utterance, and enlargement.

Thus, according to the desire expressed, my dearly beloved, in thy dear letter,
I am to have a smoother path than I had some time past.
But I am almost afraid to mention it; for I suppose it is as true,
that after a calm often comes a storm, as that after a storm comes a calm.
But, Oh! the benefit of resignation!
Great has been my need of it.
Great my help from it.
Indeed, I don`'t know how I could have got along,
or scarcely how I could have lived without it.
I was shut up from all open prospect.
I was stripped naked, and emptied of all but faith,
a little grain of faith and resignation; and they have removed mountains.
My way seems comfortably open.
I look forward with much more satisfaction than I ever expected to,
not only toward the southern limits of the present journey, but also through life.
Blessed, forever blessed and adored, be the name and marvelous power of the Lord,
my God and redeemer.
May I, may thou, and all that we love, and all that love the truth, forever trust in him;
not only in prosperity, but in the deepest adversity.
Oh! he has wonderfully stood by me,
and supported my soul in the most trying moments of my life, or I had utterly fainted.
He is good indeed.
My poor soul knows he is good; and I often have to proclaim his goodness aloud,
and call on others to come taste and see that he is so.

There is oft a very open door, and highway ready cast up;
but at divers other times the door seems scarcely open,
but that it may be gradually opened; and instead of a plain highway,
only a little dim path in the woods, as it were; yet footsteps may be seen.
And though there is a degree of fear to rise up and walk in so obscure a path,
lest it should lead astray, or run quite out into the wide wilderness,
where no path or footstep is; yet whenever a gentle command is heard, to arise,
and follow on in that small path, it has never failed,
as care has been taken to step safely, and slowly,
to lead on gradually into a plainer and more open road;
and often has brought me into the King`'s highway, with songs of joy.

I am to get round to the Yearly Meeting at Philadelphia, if in reason to be done,
and Master`'s approbation: but expect it will rather crowd hard on my constitution.
Do not fail, I desire of thee,
to let me have the satisfaction of a letter when I get round to that great city;
so that I may have some pretty late accounts, how it is with thee and all ours.
For though I don`'t feel so anxious about any thing, as I have done,
yet it is very sweet to me to hear of thy welfare, content, and happiness;
and of those with thee.

This is my ninth letter to thee, since I saw thee.
I may write again from Charleston, South Carolina; how soon, don`'t yet know.
My dear love is first and ferventest, dear heart, to thee; and then to our dear babes,
whose footsteps may their watchful mother safely guide.
Tell them their father loves them dear, and greatly wishes they may all be good.
Give my hearty love and affectionate goodwill to my own dear father, and remember me,
as occasion offers, to all my relations, friends, and neighbors,
especially my dear sister Lapham, her husband and children;
and don`'t forget my particular remembrance of, and love to dear Daniel Aldrich,
and Asa Smith.
Many more I could name, but they are too many, so leave it to thee, and conclude,
with a fullness and fervency of heartfelt affection, yet in calmness and serenity,
thy oft tribulated, but now much comforted husband,

Job Scott

To his Wife

Jack Swamp, Northampton co.
N+++.+++ C. 26th of 6th mo.
1789.

My dear, dear wife,

I wrote thee from Pascotank, last 7th day, the 20th of this month,
and also our dear parents; but yesterday I received a letter from dear Daniel Aldrich,
written from New York, 10th of last month,
and having an opportunity to forward a line to him,
I also squeeze out time to inform thee, that I am so far in health as to keep travelling,
but have been for about a week a good deal complaining.
Bile now gathers on my stomach and distresses it, more or less, most of the time;
and in consequence my head is dizzy and uneasy, and my ideas a little affected by it.
Have been more cheerful for several weeks, on the whole, than I had any hopes of,
my way very clearly cast up before me, though it had been much otherwise, before.
Yesterday a companion met me here with a certificate
from near where Yearly Meeting was held in Virginia,
in order to go on awhile with me, he don`'t know how far.
I am trying to get round to Philadelphia Yearly Meeting;
but if I get within three or four hundred miles, by about that time,
I think it must be by pretty close pushing.

My heart is often with thee, the babes, etc. but am borne up latterly pretty well.
Blessed be my gracious helper, whose favors are far more than I think myself worthy of;
yet I am at times +++[+++I am]
much depressed, and am now looking out for such a scene,
as day and night succeed each other.

Daniel mentioned, in his letter from New York, that Amy Thurston was there,
and said when she left home our dear sister was bravely, and my family in usual health.
This account with thy one, father`'s one, and Moses Brown`'s one letter,
is all that I have heard from home since I left thee.
How much was meant by my dear Remember`'s being bravely, I don`'t know,
but was glad to read so good an account.
My dear love is to her and all the family.
May her faith be unshaken in his power, who has wrought wonders for her.
My love to my poor dear father.
I wish him happiness here, and hereafter.
Tell my dear children, I love them dearly, and beg of them to behave well,
and be good little Friends.

Do, my most tenderly beloved, write me as often as thou canst,
and desire our dear father to do the same.
Thou don`'t know the satisfaction of a line from a dear wife, or near friend,
in a strange land, where I change my acquaintance almost every day.
Thou hast thy dear friends about thee.
I, as soon as I begin to get an agreeable acquaintance with a friend, must part,
and go among strangers again.
True, I find something that often sweetens every bitter cup: but still,
I can but often greatly wish another line from thy dear hand and heart; for there it is,
in great degree, that my joys are centred, except the joys of love divine;
to which the love of soul with soul united, bears a near resemblance,
and is but the next degree below.
May they both ever increase.
And may the Lord my shepherd hold thee and me, and all ours, in his holy hand,
is the sincere and fervent desire of thy sincerely and fervently affectionate husband,

Job Scott

Extract of a Letter to a Friend

Northampton, N. C. 6th month 26th, 1789.

With gratitude, I acknowledge the receipt of thy kind letter, of 16th of last month,
yesterday.
I have had none from home later than 14th of 4th month.. One from my dear wife,
one from her dear father, and one from my dear friend, Moses Brown.
I wish much to hear again from my family, but must submit.
My health is but low, the heat being extreme.
Some time past, my way seemed much shut up; but,
blessed forever be the leader of the blind in the way they know not,
my way was at length clearly opened,
and I have travelled as in a way cast up before me for several weeks.
I have indeed some times of depression still, but nothing to complain of.
On the other hand +++[+++I]
have been favored with unexpected enlargement and satisfaction.

A dear friend from Virginia, James Ladd, met me yesterday,
with a certificate to accompany me,
and seems given up to go with me as far as way may open.
I am trying to get to your (Philadelphia) Yearly Meeting, but have no hope of doing it,
without leaving many meetings to return to.
If I find as much engagement to appoint meetings from among Friends, as I have done,
it is not likely I shall be at your Yearly Meeting.
I have had divers meetings to good satisfaction where no Friends live.

To his Wife

Core Sound, North Carolina, 5th of 7th month, 1789.

My dear,

I am now writing thee the eleventh letter, having before written thee ten,
since I left home.
I dare not complain of my not having received but one from thee,
for I know not but thou may have written, and the letters miscarried,
or not come to hand.
But I may, without complaint, inform thee that I feel, often feel,
such anxious risings of desire to obtain a renewed token
of thy affectionate remembrance of thy poor husband,
that it requires the exercise of considerable resignation, to keep in proper submission.
Indeed, it is no small trial to be absent from thee so long,
especially as I have no prospect of being soon at liberty,
even to think much of returning, though there are seasons, wherein, if I had wings,
I believe I should soon be with thee; for never did I leave thee,
when I oftener had thee present in my mind,
than this time;--never more feelingly bore thee on my heart,
or in my affectionate remembrance.
It is in the effusions, or flowings forth of this heartfelt and fervent affection,
that I am now engaged to write thee so soon after two late letters.
I don`'t know that I have much to inform thee, except that I am in good health,
much mended of late.
But a Friend being bound hence soon to Baltimore, my heart leaped within me,
in the fresh remembrance of my best beloved on earth, my bosom friend,
my wife--dear tender name.

O my dearest! thou hast been much with me, in mind, of late, both by day and by night.
Oh! that it may not be owing to any evil that has befallen thee.
May the Lord my God preserve, watch over, and defend thee.
May guardian angels surround, and protect thee in all thy ways,
and through every trial and affliction.
O my God and Father! hold, I pray thee, the dear object of my heart`'s affection,
my chosen companion, my endeared Eunice, and her little tenderly beloved infants,
in thy holy hand.
Shield them,
O holy Shepherd! if it be thy holy will and good pleasure--shield them from all harm,
and preserve them through every danger.
Be more than the kindest husband to her in all her besetments,
and fill her oft-afflicted soul with heavenly consolation.
Be more to her, and my dear babes, than any earthly father.
Touch their tender hearts with an early sense of thy goodness.
Impress their minds with desires to know and serve thee.
Take them into thy powerful protection.
Make them thine, and keep them so forever.
And, O all-gracious, holy God!
I am engaged to intercede with thee on behalf of my aged father.
Oh! that he may find a place of acceptance with thee, and obtain thy royal favor!
May his heart be deeply engaged to live near thee, now in his old age,
and to walk worthy of thy approbation;
that so his spirit may find a resting place at last, a mansion in the realms of glory.

Thus, dear love, was my heart in motion, and my intercessions ardently poured forth,
when the hour of more public devotion called me away, else might my other parents, now,
I trust, thy guardian friends, have shared the benedictions of my flowing soul;
for they are likewise near; yea, very near my anxious heart, a place they often find,
while I far, far remote from thee and them, constrained, am forced to spend my days;
at least awhile,--though not condemned, I hope,
to longer exile than for good shall prove, at least to me, dear heart,
if not to thee and many more.
Oh! may you patiently my absence bear, and more your souls ascend,
in supplication for my faithful stay, my firm reliance on the arm divine,
and upright perseverance, till the work be done, than for my sudden, or too soon return.

The work is great before the view of my mind; wide the field,
and in some places white unto harvest.
But, alas! few indeed are the faithful laborers in this land, as few, perhaps,
as in any my feet have ever trod.
I often think, if Friends in these states were deep in the life of truth,
and the ministry in true gospel authority, that many who are awakened,
especially among the noisy Methodists,
would flock unto our Zion as doves to their windows.
But, alas! when they look towards Friends,
they can see or feel little to draw or fix their attention:
so they continue in their tumultuous devotions,
though very sensible of truth`'s impression when its testimony is livingly declared.
Oh! how the everlasting gospel flowed with life and power this day!
Few untendered hearts were in the meeting.
Many were thoroughly melted.
May they be moulded into the image of him who made
this a day of blessed visitation to their souls.
But, alas! how soon these tender impressions wear off in too many,
and like water spilt on the sand, are not to be found!

I am now far southward, in North Carolina, but find, contrary to my late expectations,
that I cannot well go hence, directly for Charleston, in South Carolina,
because it is a long road, and no Friends on the way; so I must return,
as many others have before me, near one hundred and twenty miles northward,
and thence one hundred and forty or fifty miles westward to New Garden, etc.
Thereabout is a large settlement of Friends, and many meetings.
All these things considered,
I have quite given up getting to Philadelphia Yearly Meeting,
unless I go northerly from New Garden, and come south again,
which I have almost wished to have liberty to do,
as the extreme heat operates so on my nervous system,
as almost to discourage my going further south at present.
But I have not yet seen that I may be allowed to
exchange this extreme heat for a cooler climate,
and if I do, I suppose I must ride seven or eight hundred miles, going and returning,
or at least, I expect, five or six hundred more than I need to.
And whether I do so or not, the journey will be, I believe,
much greater than some of my friends expected.

I have already rode, by my account, 1,750 miles,
and don`'t expect to get through at any rate short of 4,000,
if I do much short of 5,000. Meetings lie, many of them, very far asunder,
scattered through this wide extended country.
Let none of my friends, therefore, at home, be blaming my long stay,
while Friends here are thinking I drive too hard.
Some say I shall not stand it, unless I slack my pace.
I hope to be preserved in the right medium and motion,
and to return to thee in the right time;
when I trust our joy in each other will be with fullness of heartfelt endearment,
and sweetness of unshaken love.
Oh! my dear, if I could finish my day`'s work aright, without thus staying from thee,
I would soon turn my back on Carolina.
Soon would I revisit New England`'s loved abodes, soon mingle sigh with sigh,
and tear with tear, dear love, with thee.
But, no: my peace, my lasting peace, is staked on faithfulness to him,
whose awful word commands this separation from my dearest dear,
constrains me longer in this land to toil,
and says I must not yet to thee and thine return.

Do, my dear, afford me a few lines of love, and let me know how it fares with thee,
the babes, etc.
My dear love is to all my relations, friends, and neighbors,
and in an especial and feeling manner, to my dear afflicted sister Remember,
whom I often remember with much sympathetic good will and endearment,
and for whose faith, preservation, and perseverance,
my supplications have oft ascended to the throne of grace.
A line from her, if she yet liveth, would be very acceptable.
Do put our dear father upon writing.
I have had only one letter from him, one from thee,
and one from Moses Brown in all this time.
I almost pant for accounts from home, as the hart for the water brooks.
Don`'t forget my love to dear aunt Cornall, and her family,
particularly P. Truth would do that girl good if she would bend to its influence.
Aunt too must bend more yet.
With much love to thee, my dearest, to our dear babes, all my parents, etc., I remain,
in fullness of affection, warm flowing from the heart, thy oft-sorrowing,
oft-rejoicing husband,

Job Scott

To his Wife

Holly Spring, in the back settlement of North Carolina, near New Garden,
the 30th of 7th month, 1709.

Dear wife,

My spirit salutes thee in the love of our Lord Jesus Christ;
and in a fresh sense of those cementing bands wherein we have been made one in him,
am I at this time engaged to implore the God and Father of all our tender
mercies to hold thee and our dear lambs in his holy hand.
May he comfort thy soul with the oil of gladness,
bring thee more and more into an acquaintance with the wonders of his inward, hidden way;
and make every difficulty, and every trial, work good unto thee,
in the furtherance of thy progress in the path of purity, patience,
and perfect resignation.
Many trials, I doubt not, will attend thee;
and though I have mine in great fullness and variety,
yet I often deeply feel for thee in thine.
Indeed how can I otherwise than feel for thee, seeing of a truth,
thou art as it were graven upon the palms of my hands, and on the table of my heart?
Hence, often, very often arises a secret sigh, and therewith a silent intercession,
"`Lord God of my life! keep her,
Oh! keep her precious soul in thy holy care and protection.
Watch over her, by day and by night, and fill her heart with thy divine consolation.`"

But Oh! my dearest, it is but a small part of what I feel,
that I can convey in this manner.
I often long for one more favored opportunity, to pour out my whole heart,
and many painful exercises, into thy dear bosom.
Oh! methinks I often feel, at this great distance, some hearty,
sympathetic overflowings of thy soul towards thy tribulated husband,
in his many and varied conflicts.
Whether we may ever have the happiness to meet again in this life, I know not;
but I live in the faith that we shall, to the mutual joy and rejoicing of our souls.
I have, since I last wrote thee,
passed through some of the most painful and distressing seasons, that I almost ever knew.
I seemed much of the time for many days, as if I could scarcely live,
or get my natural breath.
Indeed, I often thought, were it not for my fervency of love to thee, and the dear babes,
with a few other dear relatives, death would not be unwelcome to me: but then I also saw,
that that would not do the work of my soul`'s thorough refinement,
and perfect submission, nor finish the work which my blessed Redeemer has engaged me in,
for the souls of others; a work, the weight whereof, as it cometh upon me daily,
I have no words to convey an adequate idea of,
to any that have not learnt it in a school of like painful experience.
But I see oftener than the morning, that I must not murmur, nay, not even inwardly;
nor indeed have I any cause: for all these dippings, strippings, bowings down,
and painful sinkings, are necessary preparatives, and strength, utterance, and ability,
without lack, seem to be the almost daily consequence.
The work goes on and prospers, to my great admiration; yea,
and prostration of soul before him, without whom I am nothing, and can do nothing.
I often marvel, and am almost amazed at that wonderful fullness,
and strength of divine energy, wherewith I am day by day furnished, as it were,
out of the depths of emptiness, and want of all things.

Oh! great, very great is the field of labor in this land.
I had a baptizing sense of it, repeatedly before I left home,
and of that extremity of depression and bitterness
which I have had so largely to partake of.
But the marvelous liftings-up, enlargement, and almost unmeasured fullness of light,
life, and ability, I then saw nothing of;
and could scarcely believe the Lord would condescend
to deal so bountifully with so unworthy a servant.
But it is for the precious seed`'s sake, that lies oppressed, and as it were,
buried alive in thousands in this land; though raised, and rising,
in individuals here and there.
Oh! the tenderness, the brokenness, the sighs, and tears,
which seem irresistibly to flow forth, and abound, from meeting to meeting,
among many whose hearts seem pierced with the pure power of the word of life.
In many meetings, especially where the most are not Friends,
the canopy of light and love, in brightness and in awful weight, spreads over us,
through nearly or quite the whole meeting.
Openings are wonderfully clear.
Doctrines flow like oil; and it seems like sailing with wind and tide,
with the whole wide, and unobstructed ocean before our barge.
But mostly, when few are present but Friends, it is hard getting the batches up;
long silence, and painful; and when way is made,
it is much by way of lamentation over Zion, the wound of the daughter of my people,
etc. with a word of consolation to the heavy-hearted mourners, who, being few in number,
often sigh inwardly, over the desolations.
May their number greatly increase.

I used, some years past, if I was highly favored, to feel for a good while after,
often for many days, great cheerfulness and consolation; but now,
I sink right into my own nothingness, and feel as empty as ever,
saving a clear and comfortable evidence, that I am in the way of my duty.
So that I get a pretty full clearance at almost every place;
and that I do not go beyond my commission.
So I droop on till the next meeting; though for an hour or two before it begins,
I often feel the weight of it, as heavy almost as I can endure.
I have indeed, now and then, a time of great relief and refreshment, out of meeting;
but am much the greater part of the time, heavily laden, and in the deeps;
but it is grown so familiar to me, that I believe I sometimes rejoice as one relieved,
when yet my weight of exercise is such as would once have made me groan under it.
But I must not enlarge in these hints,
else I could fill several sheets with my various ups and downs, etc.

My dear companion, James Ladd, is a choice Friend, about fifty; +++[+++he]
has a little, lively, sound testimony in most meetings;
left a dear wife and divers children, to take part in these arduous exercises.
I love him dearly.
He is, I trust, of much use to me, and others.
He thinks I have a little of the hypo sometimes.
I don`'t pretend to deny it; nor do I know that it is often otherwise with those,
who so often wade the depths, and descend to the bottom of Jordan.
I much doubt whether many of them are always clear of something
that must and will be called by that name.
Nor is it strange, for every nerve, perhaps,
is often strained almost to its utmost bearing, in the fiery trial,
and the ardent warfare.
I sweat in nearly every meeting, through shirt, jacket, and coat.
This keeps my health low, and my head dizzy, in degree, most of the time, or this,
with great heat and bad water.
My constitution is closely tried, but is borne up to admiration.
I try much to do my work easier; but it seems almost in vain.
Thou know, that in any work, mowing, or hoeing, etc. what my hand finds to do,
I do it with nearly all my might, even though I strive to be moderate;
so it is in meetings.
I think, now I will be deliberate, moderate, and gentle.
And so I am, for a little space; sometimes for a good while; but by and by,
the current almost irresistibly carries me away with such ardour and earnestness,
that the sweat flows, so as to run from me almost in streams; and though I often lower,
and try to make less sail, I am soon again with full-spread sails, and a strong gale,
tide also oft making the same way.

Well, I must try to do my work as I can, or not at all.
And, not at all, affords no peace.
I often look homeward; but find no liberty to return.
My bands are strong about me; my draft lively, and feelingly impressive.
There seems no room, at seasons, to doubt in the least degree, my being,
not only in the way of my duty, but my indispensable duty.
I never expect greater clearness in any case, and can freely,
(if it is prudent so to express myself,) risk my eternal condition upon it;
and give up my all to his disposal, who has a sovereign right to me, and all my services;
being sometimes enabled, in truth and the depth of prostration, to say,

"`Thy will is welcome, let it wear

It`'s most tremendous form;

Roar winds, rage waves: I know that thou

Canst save me by a storm.`"

Oh! have faith in him,--have faith in him, my dearest, best beloved.
He is a never-failing helper to all that rightly rely upon him.
He has wrought wonders for the deliverance of my soul.
He has again and again, made bare his omnipotent arm, and evidently evinced,
that therein there is no lack.
Blessed and adored be his holy name forever.
I know of nothing but duty to him, that would keep me from thee;
but I am under such inexpressible obligations to his infinite majesty,
that I dare not entertain a secret thought of flinching from his requirings.
I often wondered at his sending me; had many objections, and some very weighty ones.
I thought, why are not such and such sent; and not one in my circumstances.
But all would not do.
And now I hope I shall remain given up to do his will,
and finish the work he has for me to do.
Then, I trust, I shall once more bless his holy name,
for the safe and pleasant enjoyment of her, that is much of my portion in life,
and of her lovely babes.

31st. It may be some satisfaction to thee, to understand, that for about a week past,
I have not been so painfully depressed, as for some time before;
though the weight of the work comes upon me daily, and is pressingly heavy,
and bears me much down, till I get through it; for till then, I cannot shake it off.
If I think I will be cheery, and not enter into pleasant conversation, it avails not,
to get rid of the weight, for there it will be; and I rejoice that I am,
much of the time, content therewith, even when it causes great depth of distress.
And as I here abide, a hope arises that, if I continue here to abide,
(I mean in the faith and patience of the saints,) I shall be so refined, in due time,
as to be able to dwell with devouring fire, and everlasting burnings,
without being thereby pained, or the smell of fire being perceived upon me.

Oh! the baptisms, the burnings, the washings, and repeated purifyings,
requisite to the thorough redemption of the immortal soul!
Well, may his hand not spare, nor his eye pity, till judgment is brought forth,
not in part only, but to perfect victory.
O my dear! let us press forward to the mark, for the prize.
Let nothing be suffered to detain or retard us.
The crown is certainly at the end of the race, whatever doubters may say to the contrary.
Oh! how will it fare with such as have let go their hold, and cast away their confidence,
yea, vilely cast away the shield of the mighty, as some have done?
The breathings of my soul have been fervently to Israel`'s God,
that they may be once more quickened, and encouraged to trust in him,
and endeavor to lay hold on eternal life, before it be too late.
For though they have sadly slipped,
yet great is the mercy and forgiveness of him with whom we have to do.
So that if the righteous, through unwatchfulness,
"`fall seven times,`" yet if his heart is engaged,
and his spirit fervently bent upon ascending the hill of difficulty, and his looking,
and his cry be rightly unto God, he may and will "`rise again.`"
But he that quite lets go his hold, and turns his back on the precious truth, will,
with "`the wicked, fall into mischief.`"
And it may be depended on, for it is an eternal truth,
whatever the deluded souls may boast,
that "`there is no peace to the wicked;`" and there will be none.

Oh! that our friend Amasa may be favored with a spark of faith, a ray of hope,
and ability to renounce his three potent enemies, "`the world, the flesh,
and the devil.`"
Oh! that he may feelingly and heartily believe that "`the wages of sin is death;`" that
if he continues to "`walk after the flesh,`" he must and will continue to die;
but that "`if through the spirit,`" he "`mortifies the deeds of the body,
he shall live.`"
Oh! that he could feel the certainty and never-failing reality of these things,
and submit unto that power of God, which is daily upon him,
whether he will own it or not; and he can no more get from it,
than he can get out of his own skin.
It is as evident to me, that the power of God is more or less operative, upon all men,
during their day of visitation, as that there is a God at all,
or as that the influence of the outward sun is felt
by all who are within reach of its rays,
and are not past feeling.
Men may struggle to be rid of it; may deny its influence;
may laugh at those who know they feel it; may turn every way;
and yet the flaming sword will turn as many ways against them; the worm will gnaw;
the fire will burn, without their leave, and in spite of all their cunning.
I know what I say: and yet happy are those who give it leave to burn; or more properly,
who bow to its operation, and resign up to its purifying flame,
all that need to be consumed by it; for these will be redeeming by its refining virtue:
whereas, in the others,
it remains "`a fire that is not quenched,`" which will "`burn
to the lowest hell,`" if they continue impenitent.

Oh! my dear, I know and am assured,
that every man is a fool that makes light of these things.
He sports with life and death.
He trifles with his own soul.
If he would open his eyes, or be willing to see, he might clearly see, and feel too,
that the hand of God is upon him, that his peace is destroyed,
that he is at war with Heaven,
and is sure to be defeated in his vain hope of escaping the righteous judgment of God.
My bowels are moved while I write.
I travail that his soul, (dear Amasa`'s,) may rest with God in peace,
in the day of solemn reckoning.
Oh! that he may in time believe, what he must find and feel to be true,
whether he will or no.
Oh! that he may have an heart truly and reverently to say,

"`Though he slay me, yet will I trust in him.
I will bear his rod, and my own burden, because I have sinned against him.
I will wait patiently upon him, and submit to his holy indignation.
I feel that I am in his hand; I feel his power upon me; and though I have denied it,
laughed at, and striven hard to be rid of it, yet there it will be,
as a fire in my bosom.
I have often thrown water upon it; quenched it; made sport over it;
done all I could to stifle and drown it; and for a season, and many seasons,
have so braced up my mind against it, that I have thought I had well nigh got rid of it,
and yet there it will appear against me; it will burn; it will condemn;
it will interrupt my false rest.
Oh!
I begin to believe it is in great lovingkindness to my soul, that I am thus followed.
I begin to find there is no escaping from the all-righteous
sentence of this just witness and judge,
this holy principle.
I thought it was something natural, something of man; but I find it too hard for me.
It baffles all my art and endeavors to escape its tormenting remonstrances.
Surely, it is of God.
Surely, in order for my sanctification and redemption, was it placed in my heart.
God could not place it there only to afflict, and to answer no good end.

"`Well, I once lived a short time in a good degree of obedience to its dictates;
I then found peace.
I have since laughed at that peace,
but I begin to think it would be worth more than all the world in the hour of death.
If I then had peace, and now have pain, in spite of all my shuffling to be rid of it,
it must be something real.
If it was only imaginary, I should have banished it long ago;
for I have scarce left a stone unturned in my endeavors to eradicate it from my breast.
Peace, then, I find there is none, but in subjection to this inward law.
This will not allow me peace in sin.
My very pretenses and boasts that I have had peace in sin, have,
by my manner of speaking and acting, clearly evinced to each discerning eye,
that I was but playing the hypocrite in said pretenses.
Well, did this divine witness, which I have so laughed at,
ever condemn me for what I was not guilty of?
Never, in all my life.
But whenever I have done well, I have been accepted, and found peace.
And when I have done ill, sin has been laid at my door.
For though I was not willing to grant houseroom to
that which brings home the sense of sin and guilt,
yet it would be at my door.
It would knock; it would condemn;
and I begin once more to conclude it will condemn forever if I go on in my sins,
and that if I die in them, where Christ is gone I shall never go.
Therefore, I will endeavor, with divine help, which I find is still near,
and has long been waiting, to break off from my sins by repentance.
I will seek peace once more with my God, before his Holy Spirit ceaseth striving with me;
lest my house be left unto me desolate,
and the things that belong to my peace be hid forever from my eyes.`"

Oh! that this may be his happy experience, and the heartfelt language of his soul,
is the travail of his fervent christian friend, and thy fervently affectionate,
as well as oft tribulated, and often consolidated husband,
whose prayers for thy preservation and peace, are oft ascending to the throne of grace,

Job Scott

My dear children,

Your poor father loves you much, and wishes much to see you;
but wishes more to have you do well.
Do, I desire it of you, if you wish your dear father to be glad to see you,
when he comes home, mind and be good children.
Obey your mother.
Be kind and loving to her, and help her all you can.
Be kind to your poor old grandfather, and love him.
Be loving to one another.
Don`'t strike, by any means.
Never tell a lie.
Speak no bad words.
Read your books several times every day.
Write as much as you well can.
Find some work to do, and don`'t play too much.
Remember, we must all die, and give an account of our conduct to him that made us;
and if we do bad, we shall displease him.
If we do well, he will bless us, and make us happy forever.
And thou, my dear son Oziel, thou art the oldest, do try to be a good boy,
and not learn thy sisters, and dear little brother, any naughty tricks;
but set them a good example.
If thou and they grow naughty, it will grieve thy father`'s heart;
but if you all do well, he will be glad to see you, when he comes home; till which time,
he heartily bids you all farewell, and assures you that he remains your loving father,

Job Scott

To +++_______+++ +++_______+++

Providence, N. C. The back settlements of Friends, not far from Cane Creek, New Garden,
8th mo.
3rd, 1789.

My dear friend,

Having passed through many painful services,
and sometimes seasons of unspeakable enjoyment,
and having in the constraining of the truth, had divers meetings hereabouts,
have been to Cane Creek Monthly Meeting, a time of renewed visitation to many;
it was acknowledged by the sensible to be.

Dear W. D. and J. C. are alive in the holy root;
their endeared sympathy has been a cordial to my drooping mind.
J+++.+++ took a certificate to visit South Carolina, and Georgia;
he expects to go soon after their Quarterly Meeting, which begins seventh day next.
I expect to be at it, with my dear companion James Ladd of Virginia, a solid,
exercised Friend, who has a little lively sound testimony in most of the meetings;
I understand he is more enlarged sometimes,
when the weight of the meetings falls principally on him.

We also expect to go south after the Quarterly Meeting.
We shall, I expect, go first to Charleston, then to Georgia,
then to meetings about Bush River; these places lie somewhat triangular, and J. C. will,
I expect, go round the other way; so that I hope to meet him somewhere on the way.

I had, when I left Philadelphia,
strong desires and expectations of getting round to the Yearly Meeting there,
in the 9th month;
but see now no way of getting on faster than to be
back here to this Yearly Meeting in the 10th month,
after which there will be in the back settlements of Virginia and Maryland, Delaware,
and Eastern Shore of Maryland, as much as I can do, I believe, and do my best,
by the spring meeting at Philadelphia next year.
I have drove rather too fast sometimes already, though no further on.
The weight and toil of the service wear much on my feeble ability, both of body and mind.
I sweat +++[+++in]
abundance, and have frequent slight chills, with vertigo,
so as to increase my exercises in some degree; but I dare not repine,
for I am wonderfully borne up and helped along, ability being given,
and divine enlargement witnessed far beyond my most sanguine expectations.
Yet a cup of bitterness is repeatedly filled unto me,
whereof I must and do drink for the greater part of the time, but,
the divine will be done, is very constantly the language of my soul.

I have not received a letter from New England, since the one from thee.
This is a case that has required much exercise of resignation,
for I never have been more desirous to hear from
home than while I have been in the southern climates;
I hope you have not forgotten your exercised though unworthy friend.
Well, be it as it may, I have not forgotten you,
but have many of you often in a fresh remembrance,
desirous of your firm standing in the life of the precious truth,
and in the lively sense and savor of the holy seed.
Oh! how often are my cries to the Lord for preservation,
both for myself and for my much loved friends.

Please to mention my endeared love,
(which is not in formality but in truth,) to such as thou thinkest proper.

Do, my dear friend, let me have a line as soon as thou well canst,
if so be that the great Master and Father of the
family has kept the door of love and freedom open,
which I am not yet willing to doubt.

I hope I need not say much,
by way of desire for the extension of sympathy and kindness to my dear widowed wife.
I trust the Shepherd of Israel will befriend her,
and that her friends will not forsake her.

With real love to thee and family, I conclude, thy affectionate, deeply proved,
yet supported friend,

Job Scott.

To his Wife

Marlborough, N. C. 6th of 8th month, 1789.

Dear love,

Although I have, a few days past, written the two enclosed sheets,
yet it is in my heart once more to salute thee before I send them forward.
For that fullness of endearment which I feel, is not soon exhausted,
nor can I with pen and ink express it all;
and if it is as desirable to thee to hear often from me,
as it is to me to hear from thee, it must be pleasant to know how it fares with me now,
even though few days have passed since the other sheets were written.
Know then, dear heart, my health is but low.
I just keep moving; feel weak in body; stomach weak and uneasy; head dizzy;
ideas a little confused at times, on check of perspiration.
Yet be not alarmed.
The everlasting arm bears up, and wonderfully supports my mind through all.
In almost every, or in many places, "`bonds and afflictions abide me.`"
My mind is abundantly depressed, yet truth eminently and often reigns over all;
then my cup is filled, and overflows.

After Quarterly Meeting at Centre, I expect, if well enough, to go for Charleston,
South Carolina, thence to Georgia; thence back to Bush river in this state;
thence to the Yearly Meeting at Centre aforesaid.
(The Yearly Meeting begins on seventh-day,
after the fourth sixth-day in 10th month.) After all that,
if favored to get through with that,
there is a wide field of labor in the western parts of Virginia, Maryland, Delaware,
and the Eastern shore of Maryland, etc.
So that I have not even a hope of seeing thy face
till some time after the spring meeting at Philadelphia,
next year.

Ardent are my desires, and that often, to see thee,
but I dare not much indulge that ardency.
Young says, "`wish ardent, ever wrong.`"
Whether it be always wrong or not, I know our desires may be too ardent;
and I sometimes fear mine are growing so: therefore they are soon checked.
For in resignation only I find peace, and therein I find it abundantly,
even in tribulation.
Seek it, my beloved: lay hold of it; love it in every trial,
and cast thy care on him that never fails; then, I have no doubt,
thou wilt be carried through, provided for, and graciously preserved.

Do let me hear from thee, and know thy state.
My heart is with thee.
My spirit sympathizeth with thine, and my prayers are often put up to him,
who is able to help, that in all thy afflictions, he may be near,
and do infinitely more for thee, than the kindest husband can.
Don`'t expose thyself, nor endanger thy health.
Look not too much at any expense that every necessary attendance and supply may occasion.
I had rather it would cost all my little outward substance, than to lose thee,
or have thy health ruined.
Thou art more to me, an hundredfold, than all my little worldly interest.
That, we may, (with Master`'s help,) rub along without;
but were I to be deprived of thy dear company,
I evidently feel that it would more nearly try my resignation,
than the loss of all outward estate, even had I much more than I ever shall have.
Therefore, I wish thee to see well to thy own health;
and may now express my earnest desires that our dear
children be kept in the way of truth;
in some little business; from too much play, and running about.
Do have them read often, and write as much as may be.
Guard them against lying, and all bad words.
Don`'t let them strike one another, nor quarrel.
Let them keep mostly at home.
Don`'t whip, or chide unnecessarily, nor yet too much spare the rod.
Endeavour, dear love, to attain to, and maintain an even calmness of mind,
guarding against all fretfulness.
Be kind to my dear old father.
He is my father, and I have much heartfelt love and affection for him.
Let us make the best of all things, and do the best we can, under all our difficulties;
and then, though we may have erred in some things, the Lord will undoubtedly be with us,
bless us, and comfort us, and our dear children,
as they are brought forward in the truth.

Dear Zachariah Dicks desired me to give his endeared love to thee.
He expressed it very affectionately, though a stranger.
He is alive in the true vine.
He took me aside after a highly favored meeting, and said to me thus: "`We must now part.
I don`'t expect to see thee again, till our Quarterly Meeting,
and I wish thee to be encouraged.
I have near and dear unity with thee.
I don`'t know when ever I met with a friend that
I felt more of an endeared love and affection for.`"
These words flowing from a heart of sensibility, nearly affected my mind,
and drew tears from my eyes; for I felt very low, and was humbly bowed, and much emptied;
(though highly favored, a little before;) I felt myself indeed, as a pilgrim,
and as a stranger in a strange land, yea, as an unworthy messenger.
Marvellous are thy dealings, O my God, with my soul!
I said to my dear friend, "`Thy words are as a cordial to my mind,
and much to my encouragement; for I go drooping along, no man fully knows my path.`"
To this, he feelingly replied, "`I believe it--I believe it.`"
Thus the Lord, not only bears up, by his invisible presence,
but also begets a near sympathy in his faithful servants,
and sometimes causes them to speak a few words fitly, and in season;
which are truly "`as apples of gold, in pictures of silver.`"
Blessed be the Lord for all his favors.

Centre, 9th of 8th month.
Truth is still eminently near, and supports.
I have had three good meetings, the last three days;
that yesterday was the select Quarterly Meeting, where things opened wonderfully,
though quite unknown to me, till after the openings and expression of them,
when in the course of the business, great confirmation appeared.
Such confirmations I have often had; but I find it is only as I know nothing,
and attempt not to do any thing, but simply as it is immediately impressed and opened,
that I find peace, or get at the state of things;
and am thankful that I find myself more and more unable to move in my own time,
being emptied of all.
Yet in this state, there seems no lack of matter, after a little patient waiting,
out of all haste, or creaturely desires, my own will quite laid aside,
and so in the renewed opening and ability, on every occasion.
I am more constantly and largely employed, than ever before,
even to the constant wearing upon my feeble frame;
but he that assigns the degree of labor, graciously proportions the ability.
Hence, I dare not repine;
nor think of drawing away the shoulder from the work and service.

May thy mind be borne up in patience, till I return rejoicingly,
to enjoy the much wished satisfaction of thy dear company with that of the children,
and other dear relatives and friends.
My love to neighbors, relations, and friends,
particularly my own dear father and our dear parents.
It still continues fervent to them and all theirs.
Our dear afflicted sister, in particular, if living; whose state I much desire to hear.
Her consolation in the Lord, I often feel a rising petition to the Father of mercies for.

In fullness of heartfelt affection, I now conclude, and rest thy exercised husband,

Job Scott.

To his Wife

Charleston, S. Carolina, 27th of 8th month, 1789.

Dear wife,

I yesterday arrived here, and received thy,
and my dear father`'s letter of 13th of 5th month,
being the first and only letter from home, since the one of 4th month from him,
inclosing one from thee, that being the only one I have had from thee since I left home.
Both them and this were long coming, but very welcome when they did come.
I have much desired more from thee, but am learning in all things to submit,
and submit wholly, for I find no other way of perfect peace.
I have written and sent thee 12 letters before this.
I am now pretty well for me; have had divers meetings since I last wrote,
as well as before, where there are no Friends, to great satisfaction and relief of mind.
I go to these places, in the necessity, and get through far beyond expectation.
The work is the Lord`'s, and he shows himself abundantly able to carry it on.
Great is the openness and tenderness among Methodists, Baptists, etc.,
but much greatest among the Methodists.
They are the burning and shining light of this country.
It seems to me like John Baptist`'s ministration,
"`to prepare the way of the Lord,`" in order that Christ "`may be made manifest to Israel.`"
Their doctrines are nearer Friends, than any others; their lives religious;
their hearts tender: but,
alas! they are abundantly mistaken in the great haste they are making.
I fear it will hasten many into flat formality,
and into a loss of the tender lively thing they now feel.
But, Oh! there is little among Friends, to instruct and settle them;
else I believe many would flock to our society.
However, I am well assured, the Lord is at work among them, and has done great things,
for many of them.

I expect to be here a few days, and then go for Georgia.
Friends in that state are about 200 miles from here.
Thence I expect to move north to Bush river, a few or divers meetings there;
thence to Yearly Meeting at Centre, in North Carolina,
so round to the other meetings in Virginia, Maryland, Pennsylvania, and Delaware.
It will, doubtless take me till spring meeting at Philadelphia.
Indeed, I have little openings, at times, so extensively,
in regard to people of other professions,
that I am now and then doubtful of getting home under
a longer time than I have yet spoken of;
but as I have hitherto found myself excused, with only attending Friends`' meetings,
and here and there, (though pretty often,) a meeting at the larger towns,
and some particular places, where there are a good many Methodists, etc.
I am encouraged in a hope, that I shall still be so excused;
and that others will be sent to other places.
For it may be scarce credible in New England,
what a field is open for labor in these states.
I receive daily and abundant confirmation, that my coming was of divine necessity,
and in the right time.
The Methodists count considerably more than a hundred thousand members,
in Europe and America, and are daily, and rapidly increasing; and yet Wesley,
their founder, is still alive, and rides and preaches much;
and they say almost continually.
I believe some of them here,
begin to doubt the safety of their hasty and constant preaching, and other activity;
part of which is very tumultuous.
These things induce me to hope,
"`the Lord of the harvest`" will send more faithful laborers into this land.
But his will be done in all things.

I have never wished the enjoyment of thy company more, than since I left thee.
And though my will has been much bowed, and given up,
yet I continued to have such fullness of affectionate desire towards home,
that when I looked forward, my journey seemed very long and tedious.
But of late, though I feel thee, the babes, and others, as near as ever,
and desire to return to you, in the Lord`'s time, as heartily as ever;
yet I feel much more of a thoroughly contented mind; not only believing but feeling,
that Master`'s will is ever the best that can happen to me, or take place respecting me.
The language of my inmost thoughts is much on this wise: "`I am the Lord`'s,
and in no degree, at my own disposal.`"
I don`'t say, I live always up to this.
Would I could say it; yet, I go on from day to day, mostly in that line.
"`And though much bitter in my cup is thrown,`" I drink it with very little repining,
and find it promotes health, gives a good appetite, and increases digestion.
Thus giving strength for very constant and arduous employment.

I never found myself under such constant necessity,
or indeed qualification for extensive labor,
in nearly every meeting as I have since Yearly Meeting in Virginia.
Some about home may be ready to think Job has got into a line of constant service,
by some easier way than his old path.
But, alas! my dearest, his old path is what he ever expects to walk in, under the cross,
if faithful; and "`in deaths oft.`"
A path "`the vulture`'s eye hath not seen;`" a path seen by none fully,
but the all-seeing eye of Heaven.
Here is my consolation--here my repose, that it is seen, and I hope, directed too,
by that holy eye.
And my faith is in +++[+++a]
good degree unwavering, and much of the time, wholly so, +++[+++so]
that if I henceforward continue faithful, as I know not but I have of late,
I shall want no good thing, spiritual or temporal; for who can want,
whose shepherd is the Lord of hosts?
And I think I can in humble confidence say, in much abasement of soul before him, "`Lord,
thou art my shepherd.`"

O my dear, dear wife, thou know somewhat of the many pangs, and deep tribulations,
through which I have had to pass, in order to the reduction of the creature.
I rejoice now in them all, even in many a bitter pill, which want of stability procured;
even whilst I mourn under an abasing sense of that want of stability and strict faithfulness,
which has made so many bitter pills necessary.
For, blessed forever be the Lord, my only helper, he has followed me through all;
laying the axe to the root of the corrupt tree, in order to hide pride from my soul,
and every other evil,
that at length the government of all within me may be wholly upon the shoulders of him,
whose right it is.
For I believe Christ must reign, even in us as individuals,
till he has put down all other rule, power, and authority in us;
destroyed not only all direct sinfulness, but even all independent action;
bringing us to the loss of all things; reducing us,
till we gladly count all things as dross and dung, that we "`may win Christ,
and be found in him,`" having nothing of our own righteousness,
our own activity in things religious; all this being as filthy rags.
Oh! how the world mistakes this mystery!
All our own righteousness must surely be renounced, and even done away;
all things must become new; all things of God;
feeling him to be the only spring and motion.
This is being found in Christ.
This is not having on our own righteousness; yet not the least room for sin of any kind;
on the contrary, a perfecting strict holiness in the fear of the Lord.

Oh! that I may never stop short; never give sleep to my eyes, nor slumber to my eyelids,
till this is attained.
I have the most unshaken belief, both of the possibility, necessity,
and unspeakable advantage of it.
But Oh! it is through many deaths.
Let us, dear love, entirely deny,
and give up all that would hinder this best of all experiences.
Let death do all its office in us; for till then,
Christ cannot render up the kingdom to the Father, that God may become all in all.
For till then, there will, in the nature of things, be some enemy, or enemies remaining:
and he must reign in his mediatorial capacity, reconciling us unto the Father,
till all enemies are, not in part only, but entirely subdued and destroyed.

Hence it is, that the last enemy that shall be put under, or destroyed, is death.
For when mention is made of the putting down of all enemies, and all rule and authority,
it is evident, that by which they are put down is excepted, or remains,
till all the rest are put down.
And as all those who know these to be put down in themselves,
feel it to be by and through death,
the "`death of the cross,`" so they will find there must be,
and is room for the repeated operations of this death, this being buried with Christ,
by baptism, into death and sufferings, from time to time,
till all other enemies are put under; till our whole will bows, and remains bowed;
till all in us that would act, rule, or exercise authority out of the holy seed,
is done away entirely.
When this is done, death has no more dominion, no more work to do in us;
but being swallowed up in perfect victory over all our enemies,
God does then indeed become "`all in all`" in us.
Here Christ has finished the work he came to do; saved us from our sins,
put an end to sin, finished transgression, and brought in everlasting righteousness.
And thus, presenting us to the Father, without spot or wrinkle,
as "`the righteousness of God in himself,`" or made pure and holy in him,
he renders up the kingdom wholly to the Father,
as having thoroughly done the office of mediator between God and man,
by joining us to the Lord in the one spirit.

Here is the great mystery of godliness.
Oh! that thou and I, my best beloved, my chosen bosom friend, may earnestly, not faintly,
but with full purpose of heart, press forward to this blessed mark.
And I may tell thee,
that I am at length fully convinced there is no other certain way of attaining it,
than by submitting to a constant death of all that is wrong.
For death must continue its work till all is put down.
And it is above all things necessary, that we get about, and keep about this great work,
dying daily till it is accomplished;
that we give up our whole life without even any secret reserve.

Oh! how many have been ruined by their reserves: giving up only in part;
having only a half-way religion; striving to serve God and mammon,
or something else beside God; living to themselves in gratifications, which,
so far as indulged, never fail to keep the soul from dying into perfect life and liberty.
Oh! the bondage!
They bow down alway; never rise superior to the power of the oppressor.
They see that rest or ease is seemingly good; so they bow down as between two burdens,
and "`become servants unto tribute.`"
They have so much religion as makes wrong indulgences
a burden to the tender-breathing life,
yet so much reluctance to the entire "`death of the
cross,`" as makes their religion a burden.
So, between these two burdens, they are rather distressed tributaries,
than free subjects of either kingdom.
My soul knows, and has deeply groaned under this cruel bondage: but,
blessed be the Lord of liberty, he has so engaged my heart to follow him, that it is,
and has been for some considerable time, the fixed, steady intention of my mind,
through holy aid, to make war in righteousness, not in part only,
but in true righteousness, with all evil of every kind.
For I am, beyond doubt, assured, that no other state will ever afford unshaken peace.

If all that profess to believe in perfection, did really believe in it,
and steadily press after it,
I believe God`'s kingdom would soon come on earth as in heaven,
far more extensively than there is now any room to expect it soon to do.
For, alas! where are they who even intend steadily, and unceasingly,
henceforward to deny themselves, take up their constant cross, and follow Christ fully,
and wherever he leads.
Few, I believe, with full purpose, even intend this; and without intending it, aye,
and earnestly wrestling and laboring for it too,
we shall never ascend to the top of the hill.
We may have good desires at times; and now and then be alarmed, and resolve,
and re-resolve; and yet make very little progress.
And this, I fear, is too much the case, with the great bulk of even our society.
Far be it from me to say to the least in Israel, stand by thyself.
The Lord knows I often abhor myself in dust and ashes.
But I see that this irresolute, half-way of being religious, will not do:
the whole heart is called for.
There is no moment when we may omit the watch, or please ourselves in things forbidden,
with impunity: no, no.
Our whole lives are short enough to finish the work our God has for us,
even were we constantly engaged in the good fight, against every evil motion.
But, until we engage in it without reserve, sin will have dominion over us; will reign;
will more or less bring us into bondage.
And while this is the case, we are in imminent danger,
that we shall yet finally centre in the bondage of sin and corruption;
the thraldom of worldly-mindedness, ease, dissipation, or some state or other,
into which we may be spewed, as it were, out of the Lord`'s mouth.

I little thought of all this, when I began;
but I generally write just what most impresses my mind.
Unto whom, or whether to any, this may be of use, I know not.
Perhaps it may another day, to my own soul; therefore +++[+++I]
wish it preserved.
For I desire, above all things, to be aroused, from time to time, from every false rest,
till I become "`perfect and entire, wanting nothing.`"
Let this be also thy most ardent pursuit; then am I assured, our joy in the Lord,
and in each other, will be full, and that no man, no adversity, no height, nor depth,
can ever destroy it, or take it from us.
Oh! trust in the Lord forever.
He still remains a source of everlasting, never-failing strength.
Live near him;
then his arm will most certainly be underneath and bear thee up through all.
I am much with thee of late, in spirit, both day and night; yet feel in +++[+++a]
good degree happy, in the divine will, and firm assurance of my own and thy preservation,
if we love the Lord fully,
and that he will not suffer an hair of of our heads to fall to the ground,
without his providence; for all things must work for good to them that fully love him.
I have cast my care upon him.
I stand resigned to his holy will.
Do thou so too, and all will be well.

Though I have given thee and all up to Heaven`'s all-wise disposal,
yet I feel that thou art much of my portion in this life.
Thou art engraven on my heart, and livest in my soul`'s affections.
God Almighty keep thee: the angel of his presence preserve, watch over, and defend thee.
To him, I dedicate thee.
To him, I recommend thee, with all that`'s mine, beside thee,
and all that`'s near to my soul.
I expect no good, out of his will; therefore, I cheerfully trust myself, and my all,
to his absolute disposal.
This I would have thee do; not too anxiously wishing any thing, even my return.
It will be in good season, if I abide in his will and direction, waiting his time,
and before that, it cannot.
Meanwhile, be it thy care, to train the tender lambs to virtue.
Make them know their places.
Bow their wills to discipline; yet beware of all austerity; nor use too frequent blows,
or chidings.
A steady hand maintains dominion, though mixed with much paternal sweetness, mildness,
and affection.
Give my endeared love to my father.
I wish his present and eternal welfare,
and desire that the Lord my God may put it into his
heart to be kind and loving to thee and the children.
I am sensible, that true patience, if he abide in it,
will do much more to make his old age happy.
Read this to him, and may he feel my heart`'s good will towards him.

I was rejoiced in hearing that my much beloved sister, our dear Remember,
was still mending, and more so,
in her being "`resigned and happy,`" and desiring her preservation in that holy good,
which she has so eminently witnessed.
I often bow the knee to the God and Father of our Lord Jesus Christ,
in profound reverence and thankfulness, for his gracious dealings with her,
and in fervent supplication for the continuance of his all-sustaining aid, unto her.
May she ever trust in him.
She has great cause.
She knows he is a never-failing helper.
My dear love salutes her, and all her dear brothers and sisters.
May they choose the Lord for their portion.
There`'s nothing beside can ever make them happy; nay, nothing out of his will and favor,
is of any worth to their souls.
I often wish their welfare.
But let them bear in mind, there is no way to the crown, but the single way of the cross;
and here`'s the only true substantial liberty.

In fullness of heartfelt affection, I remain thy true and ever loving husband,

Job Scott.

Second-day morning, 31st. We are soon to start for Georgia.
Feel clear of this place, though there is not so great openness here, as in many places.
My ardent wishes still ascend, dear love, for thee and thine.
Oh! walk with holy Jesus.
Be thou pure; then may we live, if I`'m so too, to be each other`'s portion in the Lord.
Waking early this morning, the journey before me, as at many other times,
looked so great, and I felt so weak, that for a moment, I was ready to faint.
But remembering that my strength was not in my own arm,
and feeling evidently that I had no liberty to flinch or turn back,
a little courage was revived, and faith given,
that all things required may be done and finished through him,
without whom nothing good has ever been done.
So I once more surrendered my all; and, lifting up my heart to Heaven,
for my own and thy preservation, concluded to press forward through every crowd.

Do, dear love, as soon as well thou canst, convey to thy deeply tried husband,
the feelings of thy heart--thy ease, thy weal, or woe.
Tell him that loves thee more than stores of gold,
how thou hast weathered out the storms of life; how thou hast been resigned, preserved,
borne up, and stayed; or sunk, depressed, and grieved; while he`'s been from thee,
in the toils of war; in hope, through fields of fight, if faith be kept,
to purchase peace; at least, escape the rebel`'s or deserter`'s fate.
Farewell, dear soul.
In love, that diminution knows not, bid I thee farewell.

Job Scott.
