== Chapter IV

Extract of a Letter to a Friend

Centre, 10th month 9th, 1789.

This Yearly Meeting is very large, and attended with some solid weight,
and with a good degree of concord.

The matter of joining the Eastern Quarter to Virginia Yearly Meeting,
has been before a very large committee,
and they agree to report it as a matter too weighty to be now resulted.
Truth eminently overshadowed the committee,
and many solid Friends were clear it would take place in time,
if Friends kept their dwelling in the light.

Our dear eastern Friends so love their western, that it makes hard work for them, as yet,
quite to give up to it; but their conduct was truly commendable.
One dear woman, on the committee, said with tears,
that though it would be very hard parting with her western friends,
the Lord`'s will be done.
On the whole, the Lord`'s arm is able to bring it about, and I have no doubt, will do it.
Divers other weighty matters were very solidly before the committee,
and the Master`'s help was graciously felt, and some souls humblingly bowed.
Blessed be his name forever.

Dear Richard Ridgway and Jonathan Wright are acceptably at this meeting,
which I suppose will close today, or tomorrow morning; I may then soon see Virginia,
as I have had pretty full opportunity to get clear of the Carolinas and Georgia.

+++_______+++ Yearly Meeting is over, and ended under as solemn a covering as I ever knew one.
The holy oil swam atop of all.
The Lord`'s name was exalted; his people`'s souls greatly tendered and refreshed.
It was a time not to be forgotten.

To his Wife

Centre, 24th of 10th month, 1789.

Dear and tenderly beloved wife,

I received, the day before yesterday, the second letter from thee, dated 4th of 9th month.
Long had I waited,
(and endeavored to wait patiently,) to get a fresh token
of thy affectionate remembrance of thy oft-stripped,
and deeply proved husband.
Oh! how my heart has often panted,
(if I may so express it,) after a line from thy dear hand and heart.
Well, at length, I rejoice, with great joy, both in thine,
and our dear father`'s two letters.
My soul blesseth the name of our gracious Helper on thy account.
May the guardian angel of his holy presence still encamp around,
and safely defend thee and thine, from all harm; and fill thy cup with that peace,
that earth cannot afford thee.
My prayers have oft ascended,
(whilst my heart has affected mine eyes,) to the throne of grace on thy behalf.
Oh! trust in him!--forever trust in him, dear heart, and he will never forsake thee.
I have often felt deeply for thee,
but as constraining love and real necessity have
drawn my mind to continue my labors in this land,
I was made to give all up; and, dedicating my whole heart to the Lord`'s service,
I believed he would shield thy soul and body, if thou loved and looked unto him,
from injury; and now am glad thou endeavored to be resigned.

I expect, ere this, thou hast got my two last letters, both very long ones;
the first from here, and hereaway, before I went more southerly,
the last from Charleston.
That was my 13th. By both +++[+++it]
may be seen, I was not to be at Yearly Meeting at Philadelphia.
Nay, my dearest.
He who gives us life, breath, and all things, has, I believe I may say, constrained me,
much against my natural inclination, to be here at this late season.
Don`'t, I entreat thee, give way to any anxiety on account of my detention.
I believe, without a shadow of doubting, that even my life was spared, some years ago,
in extreme sickness, at brother Lapham`'s, before I was thine, or thou mine,
even when I seemed nigh unto death,
upon the express condition of my laboring faithfully in the Lord`'s vineyard;
many parts whereof, were then, in the clear vision of light,
set before me as plainly as ever I saw trees in a forest; insomuch that when,
next morning, I had such an extreme ill turn, that I seemed almost dying,
I had no doubt but I should live, get well, and go on the Lord`'s errands.
But, alas! how slowly and poorly I have got forward,
much of the time since that awful and ever-memorable season.

But however I may have lagged, or stumbled along,
he has marvellously made bare his holy arm, again and again, for my help and deliverance.
Wonderful indeed have been his dealings with me,
in the course of my floating pilgrimage on earth`'s unstable shore!
Thou, dear heart, art well acquainted with some of the turnings of his hand upon me,
and displayings of his power and goodness towards, and for me.
May he ever be adored by me and thee, and that with profoundest reverence.
He has made a way for me in this wilderness land, time after time,
when and where I just before saw no way; indeed,
where it seemed almost impossible a way should be made.

The extreme strippings and loss of all things, to which I am often reduced,
I have no words to convey a full idea of;
but have known more of perfect submission in such seasons, than ever before.
My life, and my all, are much of the time, freely given up;
even at times when I can scarce forbear groaning out aloud--times
when I feel as if I could not live much longer,
without relief.
But as I bow to it, and say, "`Lord, thy will be done: I will, through thy holy help,
endeavor to bear, as well as I can, whatever thou see best to lay on me,
or require of me,`" he is graciously pleased, from time to time, to appear,
dispel the clouds, scatter my enemies, and beyond all expectation,
to arm me with the whole armor of God;
making way to the hearts of the people of all ranks and denominations;
tendering their very hearts in a manner truly marvelous, and to my great confirmation,
that I came into this land in the right time.

Dear James Ladd is yet with me.
We have had many meetings among Methodists, Baptists, Presbyterians, some Dunkers,
Mennonists, Nicholites, and Church people;
and the Lord seems to be shaking their sandy foundations.
The openness is such,
that I find it specially needful to guard carefully
against being led out to appoint meetings,
without real necessity; especially as Friends are forward in proposing;
and I have declined many places,
where we might have been received with open arms and hearts.
And yet in some few meetings, I as clearly feel, they prepare war against us,
by inwardly bracing against us, and shutting us and our testimony out,
as my eyes see their faces.
These are settled in the form; full of their dead faith and performances.
And, being in the ground of things,
exactly in the state of the old scribes and Pharisees, like them,
they shut up the kingdom of heaven; not entering themselves,
nor suffering those who gladly would enter.
Among such it is almost, if not sometimes quite impossible,
for many mighty works to be done.
There is more openness among publicans and harlots; and some of these, I believe,
will be so wrought upon, and humbled down, as to enter the kingdom,
while great professors, and strict in outward devotions, will be shut out,
and even many such in our society, as well as others.
For I find "`the letter killeth`" everywhere;
and scribes and Pharisees abound among Friends, nearly as much as among any.
And though zealous of the law, and outward discipline and order,
are still greatly shutting up the spiritual heavenly kingdom,
against themselves and others.

Oh, what care!--what toil and pains!--what earnest labors,
to build up society!--to cleanse the camp, and extend the testimony.
And, alas! alas! after all, how much, and mournfully,
this is carried on in man`'s strength and wisdom.
Oh! how hard it is for self to be still, and all flesh silent before the Lord,
till he arise, and abilitate.
Many Friends, in our and this land, are so far from full reliance on the Lord,
that they seem as if they thought the great cause would be deserted,
and the testimony fall to the ground,
if the arm of creaturely ability was not stretched out to support it,
and scarce dare to wait for life and help divine lest it should be too long in coming.
Surely this is lack of faith in Israel`'s never failing Helper,
and an unwise trust in the arm of flesh.
Even some who began in the spirit, seem now attempting to be made perfect in the flesh;
as Paul hinted to the Galatians.
And it matters not, what it is they are engaged in,
so that it be in their own strength and wisdom; it is still flesh,
in the apostle`'s sense of the word.
It is not confined to circumcision, days, or times;
but comprehends all creaturely performances;
and these have greatly eaten out the life of religion in almost, if not quite,
all societies.

I have been abundantly constrained to bear testimony, from place to place,
among Baptists, Methodists, etc.,
against this vain endeavor to be made perfect in the flesh; lifeless preaching, praying,
singing, dipping, eating, drinking, etc.;
and I feel the same want of life in great part of the buildings up, etc.,
in our own society, that has so distressed my mind among others.
Oh! that the Lord were rightly trusted in and waited for.
He would not tarry longer than best; and when he did appear, the healing,
helping virtue would be with him, and he would do more for us,
in our meetings of discipline, in one hour,
than a host of us can do for ourselves in our whole life-time.

How my soul has been affected in beholding all societies
too much clothed with the linsey-woolsey garment;
a little smattering of divine influence, and a great mixture of creaturely invention,
activity, and zeal.
And yet, alas! a right zeal is mournfully wanting.
And too many that have seen the insufficiency of man, are settled in the other extreme,
and instead of waiting with their lips in the dust for help, are sitting down at ease,
caring but too little for any of these things; and some,
glad to find a hole in an exercised brother`'s garment; whereas,
every right spirit mourns.

But why should I dwell on the various ways wherein religion is obstructed in others?
Have not I enough to do in watching against the enemies`'
subtle workings against the life in myself?
Oh! how many snares!--how many ways to be hurt!
May the Lord, without whom I am nothing and altogether vanity, hold my right hand,
direct my feet, keep my heart, and finally make my way perfect before him.
David said, "`As for God, his way is perfect.`"
It seems he had good cause to say so, for he could also say, "`He maketh my way perfect.`"
Oh! that I may be able to bear like testimony.
But truly he does so for us all, as far as we are wholly given up, at all times,
to do and suffer his will.
Our help is only in him.
All our destruction and imperfection is of ourselves.
And we keep ourselves long complaining, by not fully submitting.
+++[+++The]
great part of the many bitter pills and potions is greatly owing to want of resignation.
"`This duty gives up little more, than anguish of the mind.`"
It sweetens many a bitter cup.
And if thou, my sweetest portion in life, the love of God excepted,
canst be resigned to the Lord`'s will in my absence,
I have the most unshaken assurance he will fill thy cup with blessing,
and divide the spoil equally with those who "`stay by the stuff,`"
and those "`who go forth to war;`" as my friend J. A. writes me,
he had to think, when dear John Simpson visited thee and thine.

My soul rejoiced in hearing that that worthy servant was favored in my family,
and that the hovering wing of divine good was eminently among you.
The Lord Almighty keep you all to his glory, your own,
and my poor soul`'s peace and consolation.
Give my love to Jonathan.
Tell him I really thank him for his kind letter,
and his proposing my dear wife and family to John`'s attention, but want of time,
amid the crowd of this Yearly Meeting, now in being,
and writing letters which I cannot well avoid, prevents my writing to him at present.

I rejoice that thy health has been better than usual,
and especially that thou hast thereby been the more cheerful.
See how good the Lord is!
My health is much improved by cooler weather, and is now tolerable;
though what I went through in the extreme heat,
I believe thou wilt scarcely ever have a complete idea of.
I marvel how I got along; both body and mind were so greatly afflicted.
But as Christ is head over all things to the church, so he is to each lowly member;
and still makes wind, waves, and when he pleases, all things obey him,
and all works good to the truly humble.
I have seen his hand in the deeps, his wonders in the mighty waters.
My soul prostrates before him.
My eyes run down with tears in remembrance of his gracious dealings,
and my heart is moved within me while I thus commemorate his goodness.

I sometimes am just ready to let in a fear that some
dear Friend may think my style a little affected.
But, Oh! let them feel deeply with me, and for me, and I trust all will be well,
and will sit easy on their minds.
I am far from thee, and other endeared connections; and when I write,
my bosom heaves with feelings of affection to thee and them; and my heart, as it were,
swells with gratitude to Him that has made darkness light before me,
and stood by me in the hottest battle.
Many painful conflicts has he led me safely through.
And though I am in deaths oft, yea, "`die daily,`" nevertheless I live; yet not I,
but Christ that liveth in me.
Though I suffer loss, I dare not repine;
for he maketh me again and again to possess all things.
And though I know certainly I am poor, and have nothing, yet +++[+++I]
hope the Lord, through me, though mean and abundantly unworthy,
is in some degree making others rich; and filling their souls with songs and hallelujahs.
Blessed be his holy name forever.

29th. Yearly Meeting is over.
A more trying, stripping, and conflicting time, I scarce ever knew,
than during part of this Yearly Meeting; nor more consolation and wonderful goodness,
than in the solemn close of it; a close, as weighty, solemn, and soul-tendering,
and I trust, as long to be remembered by many, as ever I knew in my life.

Dear James Ladd is yet with me, but I don`'t expect him much longer.
Dear Zachariah Dicks says, "`Don`'t, dear Job, by any means,
forget to give my most endeared love to thy dear wife.`"
Do write to me, my dearly beloved, as soon as thou canst:
a letter from thee is as marrow to my bones.
Nurture the dear children in the right way of the Lord.
Give my dear love to my dear father.
May he trust in the Lord in his old age, and gain a nearer acquaintance with him,
before he goes hence, to be seen of men no more.
Who knows but that is what the Lord is lengthening out his days for.
May he keep in the patience, and not be fretful.
I believe fretting grieves the Holy Spirit.

I now enjoy what more than makes amends for all afflictions.
May thy soul enjoy a portion thereof.
And now, in dear love and affection, I rest thy true and faithful husband,

Job Scott

To his Wife

Amelia, Virginia, 14th of 11th month, 1789.

Dear love,

I wrote thee largely from Centre, North Carolina, at Yearly Meeting time there,
a little more than two weeks since.
Some few days past I wrote to Thomas Arnold, and soon after, I took a severe cold,
and repeating it several times, it brought on a hard cough, head-ache,
and considerable fever; but I hope the worst is over.
I have kept travelling, though scarcely able.
I have rode about 17 miles today; and since I left home, by accounts,
3,708. This is my 15th letter to thee.
And since I cannot be with thee, as my heart desireth, I hope my letters,
if they reach thee, will afford thee some satisfaction.
I hope thy dwelling may be where thou may daily receive
far greater satisfaction than earthly things can afford.
All our real good is in God.
Other things ares in a lower sense, goods,
as he is pleased to give us real enjoyment in them; but by and by,
we must be separated from them all, not for a short time only, but forever.
How needful then, that we be so prepared to take satisfaction in him only,
as that this great change may not deprive us of our happiness.

Oh! the depth of poor James Nayler`'s expressions,
respecting the spirit which he felt!--every word, indeed,
of said expressions is deep and weighty, but I mean in particular this: "`In God alone,
it can rejoice, though none else regard it, or can own its life.`"
Ah! dear James, the Lord thy God taught thee this through many tribulations:
and there is a little remnant, a very small number, who have nothing at all to boast of,
who are, in some little degree, learning the same lesson.
And Oh! my dear wife, thy poor husband is fully convinced, through many overturnings,
that until we get to this state, our happiness will be liable to interruptions.
Indeed, it is wisely ordained that it should be so,
by him in whom alone is any permanent unshaken bliss.
And as we find it so, day after day; everything wherein we promised ourselves delight,
more or less failing and disappointing us; this has a tendency, if we are well-disposed,
to drive us nearer to God, by weaning us, little by little, from other things.
Thus came the wonder of his age, the blessed John Woolman,
to witness his works go so fully beforehand to judgment, that he was dead,
whilst yet alive in the body.
Oh! the strippings and mortifications through which this is attained;
so that it was said of him,

"`Redeem`'d from earth, and earth`'s perplexing cares,

Redeem`'d from lawful, and unlawful self,

Thy mind was tutor`'d, fitted and prepar`'d,

T`' enjoy the highest privilege of man;

A fellowship celestial, whilst below,

A near communion with eternal good.`"

Oh! this work of redemption.
Few know what it is;
and fewer still are willing to dwell in the furnace long enough to have it fully effected:
for he who only can effect it, baptizeth with fire.
This is very distressing to that in man, that loves ease and pleasure.
But this refiner has his fan in his hand, and surely will, if submitted to,
not in part only, but thoroughly purge his floor; and,
by burning up the chaff with unquenchable fire, will gather the wheat into his garner.
May thou and I, dear heart, and all that have known the beginnings of this work,
so endure it, love it, and keep to it, that it may be finished; even though we witness,
before we can say with Christ, "`it is finished,`" as he witnessed,
the mingling of wormwood, or vinegar and gall.

My soul knows that this is the way; and had it been strictly walked in,
I might before this, have known my calling and election made sure forever.
Well, my deepest and sincerest desire for myself is,
that I may henceforward cleave incessantly to that which burns up the dross, tin,
and reprobate silver.
I wish none of it to remain; for each dreg of it retards our growth in the divine life.
Oh! what an excellency my soul sees in the life and
spirit of such as have been truly faithful;
as John Woolman, etc.; and as William Penn said of some, so say I,
with living desires that I may realize it in a happier world: "`Oh! blessed men!
Oh! blessed spirits; let my soul,
or may my soul dwell forever with yours:`" or to this import.

I have no clear prospect of seeing home before next spring,
though my dippings are so in the deeps,
that I often feel as if I could not go on much further.
But as I never went down (till now) so low as not to rise again,
I cannot doubt of being carried through all,
if my life continues to be freely offered up as a sacrifice to him,
to whose goodness I owe it; as indeed it has in great degree been,
most of the time since I saw thy face, though I assure thee,
no otherwise than through "`burning and fuel of fire.`"
But be it longer or shorter that we are separated, I hope and believe our meeting again,
will be with fullness of love, endearment, and joy; and that our hearts will, as it were,
live in one another meanwhile.

The work is too weighty and pressing on me, to think of fleeing from it.
I know it is of the Lord, and many are the witnesses of it.
My dear companion leaves me tomorrow, or next day;
but I dare not doubt of having suitable company.
My love to my dear old father.
I wish his happiness in time, and forever.
May he know a preparation for death, before he goes hence.
Do, my dear, do all thou can for his comfort.
It will tend to the weightiness of thy own crown, in the end.
My love is also to dear father and mother Anthony, and all my dear brothers and sisters,
both mine and thine.
And with many good wishes, it is also to my own dear children,
which the Lord has given us.
Oh! may they be preserved in the innocency, till life divine may open in their souls.
My prayers are oft to Heaven, for them and thee,--when none around me know,
but that sleep profound my eye-lids close.
As usual, I mention my love also to other relations, my neighbors and friends;
and I can scarcely close without expressing my wishes for
the preservation and consolation of our dear sister Remember.
I oft think of her trials and afflictions of body and mind.
May they all work good to her soul; and they will, if she faints not,
but holds out to the end.
Oh! may she not be suffered to let in discouragements.
He that has been with her, is God over all.
He never can fail her, if she rightly trusteth in him; even though he slay her,
may she still trust in him.
This is the desire of my soul for her, and for you all.

I rest thy ever affectionate husband,

Job Scott

To Moses Brown and Wife, Providence

Lees burg, 12th month 10th, 1789.

Dear friends, Moses Brown and wife,

I just now received, (on my arrival at this little town, or village, in Virginia,
about 188 miles from Philadelphia,) your kind letters, the one from the wife,
dated 11th of 10th month, the other from you both, of 28th of the same month;
both were truly acceptable.
The account of my dear wife`'s being in a mending way is peculiarly so,
and I felt great thankfulness that care has been
taken that she should not want for medical assistance.
I have written to her and dear father Anthony several times,
especially desiring she might not be neglected in that,
or any necessary accommodation or assistance.

I expect, from your accounts, she has had a pretty low time,
though you do not exactly say so.
I suppose you thought it best to be sparing; however,
I wish all necessary care may be extended according to her state.
I am long detained from her, but I hope she will be preserved in patience.
I am almost certain if she could feel the necessity that is laid upon me, powerfully so,
indispensably constraining me to go on from place to place,
she could not even wish me to draw away the shoulder,
or turn my back on the fields of labor which have been and are opened before me,
with a clearness truly admirable, at least to myself.
Though I am long from her and my friends, I am very diligently moving on;
stay no longer at a place than just to take a meeting, in scarce any instance;
and have travelled till about 10 at night, several nights within a week, to avoid delay;
though I fear to do the like again; my health but ill allows it, though as well as usual.
I still hope to be at liberty to return pretty directly after spring meeting;
but if I do, +++[+++I]
must rather drive or leave some places where my first prospect extended,
and leaving them feels like bringing their weight on my shoulders, or rather my heart,
to New England.
As to my own will, I remain abundantly given up; but if I knew my dear wife,
or solid friends, were uneasy, or fearful of my staying too long,
I believe I should labor to stifle my lively exercises in regard to some places.

If I may be allowed to say it, I am helped along beyond all expectation,
to my great admiration, thankfulness, and humiliation.
I find as I have no ability of my own, and strive not to have,
I am supplied with that wherein there is no lack.
But, to keep the balance, am frequently tried with the loss of all,
and with lowness and depression, which, were I to tell you of,
you would conceive but a faint idea, were it not for something of a like experience.
But all is in wisdom and in goodness;
it is my Master`'s will that a cargo of considerable weight, whatever its worth may be,
should be transported from place to place on board my little bark:
this requires necessarily the spreading of a considerable sail; and this, it is evident,
could not be safely done without ballast,
or a balance of weight proportional to the spreading of a considerable sail;
this weight must, as is purposely designed, bear down.
Here is the only safe sailing, and even so,
a reef or two in the sails is often necessary,
and sometimes no sails at all can safely be spread.
It is pleasant to the mariner to spread sail largely, and in a pretty full gale;
but the safest sailing is not always when the sails are most extended.
But blessed be the Helper of Israel, he knows when to take or order down our topsails,
and will, when he pleases, make us know our dependance.
I rejoice that it is so.
I desire that his hand may turn, and overturn in me,
till I rest wholly from my own works, as he did from his,
and move only as he may move me.
I am not sensible of much else since I left my own land,
yet see clearly that frequent aboundings require a balance of proportional abasement.

I am glad dear New England has been visited; may it not be in vain.

My love is feelingly to you and your friends.

I have had the epidemic; divers have died with it; it spreads, I hear, to Georgia.
If I had been at home, +++[+++I]
should have thought a bed best for me, but have kept travelling; +++[+++I]
am much mended, but cough daily, and much of the time.
I sweat still in meetings, and so can scarce avoid taking cold.
Beside, my line of exercise affects the lungs considerably;
but holy oil often flows over and atop of all, and oil, you know, is healing.
I have no cause to complain.
Friends are very kind, and the best Friend abundantly the kindest.

Don`'t be backward in writing; I am glad of your letters;
and do let me know if Friends are fearful I shall stay too long; it would pain me;
I am straitened lest they should,
and yet almost under a compulsion to proceed a little further;
but all according to first and lively prospects.
I have scarce ever been twice at a place,
unless on account of Yearly or Quarterly Meetings,
and have omitted going to some remote places.
How it will feel when I get home, I must leave, but I hope not very painful.
Do be plain with me.
I have no view of detention much longer than spring meeting,
but begin after all my diligence to doubt if I can get along directly after,
without leaving the wages of solid peace behind me.

Do encourage my dearly beloved to trust in the Lord, and give me up freely,
till I can return with that clearness which may allow of love, cheerfulness,
and mutual consolation, without alloy.
I believe some have stayed too long.
May it never be my case.
Nor yet the other hand error.
There is a right line of duty; I think I am sure we may know it,
and that solid peace is in it.
May all I love observe it.

I find many solid Friends from place to place, also many outward-court worshippers.
But it is a day of blessed, yea, extensive visitation to many of several folds,
almost throughout these extensive lands.
I have indubitable confirmation that I am here in the Lord`'s time.
He seems at times to be shaking not the earth only, but also heaven;
and that which many have thought very heavenly, is made to vanish as a scroll.
May He send forth more laborers.
There is much room for it.
I almost marvel how some can stay at home.
Yet let none run unsent.

Farewell, dear friends, in love that is unfeigned, wherein I am your constant friend,

Job Scott

To his Wife

Fairfax, Virginia, 170 miles from Philadelphia, first-day, 13th of 12th month, 1789.

My dear wife,

I received thy letter of 9th month, and have written thee, once or twice since.
This is my 16th. I have a few days since,
received letters from dear Moses Brown and wife, very acceptable,
giving accounts of thy state.
I rejoice, that thy health is improving, and hope, before this,
that thou art well as usual.
If so, do, dear heart, let me have another token of thy love.
Do write me a little of thy condition; how thou gets along; how patience holds out.
I have lately scarce any greater exercise,
than what arises from thoughts of thee and the family.
I hope thou wilt hold fast both faith and patience:
I find myself obliged to labor for it, or I should flinch from duty, to get to thee.
My desires to get home are as earnest as I dare let them be, on my own account:
but what calls my attention home, is much more on thine, than my own account.
My love to thee, and the dear babes, is, I believe, fully equal to what it ought to be.
But I have so often been made to give up all, since I saw thee,
and submit my own will and desires to be crucified and slain,
that under the pressure which I still powerfully feel upon me,
to labor further in this land, I could in some degree cheerfully, as to myself,
give up to be delayed in my return home, many months longer,
rather than bring the bands home with me, wherewith I am girt about;
and feel the weight of the service now required,
with the additional weight of unfaithfulness.

Do, my dear, a little while longer, give me up freely, and trust in the Lord:
he will not fail thee, if thou dost; but bless and sustain thee.
I feel too great +++[+++a]
necessity pressingly upon me, to leave this country yet awhile:
though I have no new prospects since I left home;
or nothing but what was clearly included in my lively views and openings at that time.
I travel, some think, almost imprudently, by day and night, to get along;
and I assure thee, it is greatly for thy sake.
I am scarce ever twice at a place; but after meeting at one place,
put on almost immediately for the next.
Friends almost marvel, how I could get through last week`'s travel and labor.
It is Quarterly Meeting here.
If I go over the Allegheny mountains, to Redstone,
I see no possibility of getting ready to come home,
till a few weeks after spring meeting.
When I left home, and for seven or eight months after,
I as fully expected to go to Redstone, as any where at all.
That place has been lately much visited.
Peter Yarnall has just come from there.
I am asking a release;
but don`'t feel quite so clear of that part of the vineyard as would be pleasant,
if I go not.
If I go, I expect it will be in a few days.

I am well assured, the death of my own will, so far as attained,
has saved me from many a bitter pill, since I left thee;
and made many a bitter one much easier endured.
But I have lately been a little thoughtful, whether I should not look toward home,
with an eagerness that would end in a loss to my own soul,
and the defrauding of my fellow creatures.
If so, in my loss, thou also, dear love, wilt likely feel part of the smart,
and taste with me the bitterness.
But let us be patient.
Let us be faithful.
It will not be long, I trust, at longest, till I may be at full liberty to return,
so as not to lose my reward.
Meanwhile, be careful of thyself and infants.
I understand the dear babe is grown, though it looked at first unlikely to live long.
Nurse it carefully, and nurture the older ones in the right line.
I wish them to read, write, and work a little, and by all means, be good children,
live in love, obey thee, and those they should obey.

I have, since I wrote thee last, passed through a dark vale, in which my trials,
in some respects, exceeded all I had known before.
But I may tell thee more fully of it, when we are face to face; and may now tell thee,
the stream of enlargement, has been more full and constant since,
than for so long before, during this journey; if not a good deal more than ever.
And I rest unshakenly assured, all will be well, if faithfulness continues to the end:
but otherwise, +++[+++I]
have nought to expect but wretchedness.

Give my dear love to dear father Scott.
His glass is swiftly running;
may his soul be fitted and made ready for a better world than this.
Also my love is to dear father and mother Anthony, and all theirs;
especially our dear afflicted sister.
May she not cast away her confidence in him who cannot fail her, if she rightly loves him.
Also to dear sister Lapham, husband and children, and all my relations, neighbors,
and friends.

Do urge dear father Anthony to write to me.
I did expect more letters from you.
Perhaps you think it is best to disappoint my wishes, for my good.
I hope I am, in degree, resigned to it; though I think sometimes,
if your souls were in my soul`'s case, it would bring your pens to paper oftener.
Redstone, is yet more of a heavy stone, than I could wish to bring to New England,
yet am not certain I shall go there.

In fullness of heartfelt affection, and with prayers for thy preservation and patience,
I remain thy ever-loving husband,

Job Scott

To his Wife

East Nottingham, 5th of 1st month, 1790.

Dear wife,

I wrote thee about the middle of last month, at Fairfax.
I hope I am since fully excused as to Redstone;
and have gone through the meetings in Virginia, Maryland, and Pennsylvania,
except the Eastern Shore of Maryland, and a small number of meetings now before me.
I am now at dear George Churchman`'s. He has very lately buried his wife,
and is going with me to a few meetings.
I have no steady companion, but get along through ups and downs,
so as to find relief from place to place, and feel clear.
This is about 52 miles from Philadelphia, but I am now bound further off,
pretty far down the Eastern Shore of Maryland,
and take the meetings there and in the state of Delaware.
So that I now expect to be clear after spring meeting, to come home,
taking a few meetings in Jersey, that I have never been at.
Dear William Matthews and Elisha Kirk, both of York,
(Pennsylvania,) where I was a few days past, were much unwell.
William confined to bed, exceeding weak, and Elisha`'s symptoms very threatening.
Peter Yarnall +++[+++is]
out in truth`'s service.
His dear little wife Hannah is very cheerful, and gives him up nobly.
She is a choice little woman.
I felt nearly with her, especially as her case brought thine so fresh in view.
I also saw my beloved friend Isaac Everett`'s wife.
She is pretty cheerful too,
and says she believes she could have no comfort in her dear husband`'s company at home,
when he ought to be abroad.

Oh! my dearly beloved, I often admire more at poor women,
with families of children around them, being given up, and kept so,
through their husbands`' long absence, than I do at those who go forth being given up.
For we feel the deep and pressing necessity, the "`woe unto us,`" if we refuse;
and this constraineth us, that we dare not turn our backs:
but that our dear lonesome wives, should bear up under every trial, in our absence,
without a murmur, (they not so sensibly feeling our weight of necessity,) this is truly,
at times, to me admirable; but I consider,
"`he that hath called us is holy,`" and able to do all things.
May he still give thee, my dearest, true patience,
and preserve thy mind in cheerfulness and resignation.
And in thy submitting wholly unto that which alone can thus preserve thee,
I am well assured, thy peace, in the end, will "`flow as a river.`"
My spirit is often with thee, sleeping and waking,
and my silent intercessions still ascend on thy behalf, that guardian angels may attend,
and keep thee safe from harm.

The foregoing I wrote before meeting.
We have since been blest with showers of celestial rain, in a large heavenly meeting here.
I am often made to marvel at the sheddings forth of the holy anointing oil,
in our meetings.
Many times, when constrained to stand up, I feel as if I could scarce possibly get along;
and yet keeping low, and guarding against everything creaturely,
I often find that before I am aware of it, as Solomon says,
my soul is like the chariots of Amminadib.
Great is the openness and tenderness, among multitudes.
And I have a fullness of divine evidence that "`my labor is not in vain, in the Lord.`"
Do try to give me up freely till spring; the more freely, the fuller, I believe,
will be thy joy.
I should long, if I dared, to get home sooner,
but find my peace is not full but in full submission.
However, the time will not, I trust, be long, till we meet again in joy.
Do all thou can, I pray thee, for the dear children`'s preservation.
May they be good, obedient children, and love one another.
Give my dear love to my relations and friends.
Worldly matters are submitted to thy, and thy dear parents`' disposal, till I return.
My health is middling.
I still cough.
I sweat, and then take a little cold.
This prevents full health, but +++[+++I]
am favored to keep along, and move faster than some think advisable;
but I have solid peace, and believe delays are dangerous.
This is at least my seventeenth letter to thee.
Do write me once more, between this and spring.
I crave it of thee, as thou lovest me, and wishest my consolation.

And now, in the overflowings of love and endearment, to thee and the dear children,
and to our beloved Remember, I bid thee a hearty and affectionate farewell,
resting thy true and loving husband in life, and I hope till death,

Job Scott

To his Wife

Third-Haven, Eastern Shore of Maryland, 26th of 1st month, 1790.

Dear wife,

I have just finished a letter to our dear father,
but I could not pass thee by without a line in addition thereto.
For though I refer thee to that for particulars, these may let thee know,
that neither heights, nor depths, tribulations, nor bliss, time nor distance,
have separated thee from my heart,
or in any wise extinguished that lamp of love which
glows and burns with unabated ardour in my soul.
Oft have I wished to hear, dear love, how time has passed with thee,
and if thy head above the waves was borne.
Oft has my soul been tendered and put forth in mental, fervent supplication,
when no eye has seen, nor listening ear has heard, but Heaven`'s alone; and that,
I hope and trust, has not been shut against my flowing tears.
Time long has seemed, but now begins the moment to look near,
when not with pen and ink I shall convey, as now, in broken fragments,
only part of what I feel, but face to face reveal, if that can be, the whole.

Meanwhile, to God, I still commend thee, as before.
On him alone rely; rightly rely on him, and sure I am, his help will never fail.
I have proved him in the storm; in many a battle fought; in perils manifold; in dangers,
fears, and depths of woe: he`'s held my hand; yea more, he`'s strung my bow.
The weapons formed against us haven`'t prevailed; no, not at any time,
when near him we`'ve abode, and, in his holy armor, brave resistance made.
No, no, my dearest dear: so far from that, the very bow of steel has oft been broke,
and snapped before us as the scorched tow.
Our enemies in battle have encamped;--we`'ve seen them plain;
seen their strongholds,--and all their proud entrenchments have surveyed: indeed,
with terror too, till faith arose.
But when the word, the awful word, that winds and waves obey,
was heard,--and we therein bid rise and slay,--a
dreadful slaughter more than once was made.
Goliath fell, and his Philistine troops, dismayed,
became as driven stubble to our mighty bow.
One chased a thousand, two ten thousand vanquished, put to flight.
For his the battle is, who never in battle yet was foiled; and,
till he conquers all things, never will be.
I rest assured, dear love, and so mayst thou, that he will reign,
till every knee shall bow, and till, in mercy or in judgment, every tongue,
however stout, however vile, shall own his sway;
and that he`'s favored all with all they need,
(if but improved,) to wing their souls for heaven.
So all that fail will own,--because they must, at that dread hour,--the fault is theirs.
Oh! now`'s the time, the season now is ours: and if we but improve aright our now,
our now will bless our souls with many a cup of consolation here,
and lead to full fruition when the toils of life are over.

This is my 18th letter.
Do give me one more, and tell me how thou art, and how +++[+++are]
our babes.
My love, above all forms, is fresh to them and thee; to my own father,
thine and mother too, and all thy brothers, sisters, and my own,
with other relatives and friends, the neighbors all.
I hope they`'re kind, and thou to them in what thou can;
at least that harmony and love prevail; no frets, no jars, at home, nor yet abroad:
for love is best; yea, if an enemy should yet arise, love conquers many a foe,
and over all will one day reign.

I remain thy ever affectionate husband,

Job Scott

P+++.+++ S.--I think thou may expect me in three or four weeks after spring meeting.
I am not quite certain that I shall not leave Philadelphia before that meeting.
If so, sooner home.
But don`'t look out too much.
Patience is best for thee and me.
I have had occasion for much of it; though of late, +++[+++I have been]
much favored with cheerfulness: but not without some bitter cups by the way,
which yet resignation has greatly sweetened.

To his Wife

Philadelphia, 24th of 2nd month, 1790.

Dear wife,

I came here on seventh-day, the 20th inst., after a wearisome journey.
I had been favored to finish all I had in prospect on the other side this city;
and came here full of the pleasing hope of being at liberty
to pass on directly after the meetings on first day,
into Jersey, and so home to thee, dear love, and to the rest of my family and friends;
but I still find I am not my own.
My life that is hid with Christ in God, must be lost,
unless I give up that of my own will.
Home draws upon me, like cart-ropes; or rather what its operation truly is,
like the drawing cords of strong love.
It goes not a little against my inclination, to be now obliged to write thee,
instead of the much more desirable salutation of a personal visit: especially,
as I was almost flushed with the expectation thereof.
But, my dearest, thou very well know, the cross has been much the allotment of my life,
when faithful to my God; and in the cross I must, yea, I must be still at his disposal.

I never felt in this city before, as I have done now.
The weight that has borne me down since I came here last,
I believe words can give thee but a very faint idea of.
My way was formerly when here, cast up before me, and made abundantly easy.
But, alas! dear love, my way now is in the very bottom of Jordan.
May my feet stand firm, and the stones of memorial be brought up thence, is my prayer,
by night and by day, to Israel`'s unslumbering Shepherd.
I was at the three meetinghouses on first-day, select, on second-day,
and at Bank Monthly Meeting yesterday.
All to me exceedingly laborious.
If my life might have suffered no loss by silence,
I believe they would not have heard my voice in their streets:
but being powerfully constrained, I gave the alarm, in all said meetings.
And in all but that on first-day evening, in a much more close line, than as a man,
I wished.
But, "`not my will,`" is what I am, and have been abundantly reduced to.
The testimony which truth gives me in these meetings, as to number of words,
is very short, compared with my service through the south; and yet, one testimony here,
seems more laborious and wearing, than three in a like state of health there.
Pine street Monthly Meeting, begins almost just now.
I dare not turn Jonah, and flee from it.

I see no way out of this place at present, any more than a blind man;
but have an assurance that I am rightly and indispensably detained here as yet:
and shall embrace the first openings of true liberty to return home.
For, if leave was now given me,
nothing but wings would be wanting to prevent my flying to thee.
I still please myself with a hope of getting along before spring meeting;
though that hope is greatly checked by my unforeseen detention here,
and by my seeing no way hence, and feeling, as it were,
the weight and pressure of all the city upon me.
Why I was suffered to feel so light and easy, and to look homeward so pleasantly,
before I got here, feeling nothing to prevent my going right on, I know not;
unless to confirm me, by the great,
and greatly unexpected weight and confinement which I now feel,
that it is of him who is over all, and whom I must obey, even at the peril of my life.
Every blessing I enjoy is of him.
Out of his will I have no consolation.
Therefore, +++[+++I]
must come and go, and stay, at his command.

And, O my precious partner in life!
I beg thee still to love him.
Lean wholly upon him.
Give me up cheerfully to him; and then, I am well assured,
he will not only be thy inward, great reward, but will give me to thee,
in his own good time, in fullness of love.
My heart glows with it while I write.
I am almost ashamed, at times,
that my letters are so replete with the emanations of overflowing tenderness and affection.
But yet, when I take my pen again, it seems not to be restrained.
And as what thus flows, seems not to offend my Heavenly Father, I let it flow,
however it may seem to earthly friends.
He knows the sincerity and warmth of my heart thee-ward; and I think,
allows me in expressing the emotions thereof.
Unto him, I still, as all along, commit the care and keeping of thee,
and of all that are mine; and am comforted in feeling that he careth for you.

Thou can scarcely conceive how it seems,
to have a dear little daughter of the age of our last, and never to have seen her.
Nurse her up, my dearly beloved, as the pledge of our love in the absence of each other.
May she be like Ruth of old; at least, may our God be her God, and our people her people.
Where we go, in the truth, may she go; and where we are buried,
(by baptism into death,) there may she be buried.
This is my desire and prayer to God for her, if she lives, and for all our children.
Tell them, I send them my love.
I much desire them to do well in all things; obey thee; love one another; read,
and write, and work, but not too much play.
If they are good, and do well, tell no lies, nor use bad words, the God that made them,
will love them; I, their dear father, shall love them, and good friends will love them.
But if they are bad, it will grieve their Maker; their father, their mother,
and their friends.
Tell them I am pretty well, have gained the flesh I lost in summer;
or its loss is supplied, though I then got very low in body and mind too.

Oh! could I have believed it possible,
to live through all I have seen and felt since I left home?
God over all has preserved me, even in deaths, or I must have given up the ghost.
But I have nought to complain of, rather let me bless his name forever.
His wonder-working power has been displayed.
His holy arm has often been made marvellously bare.
He has magnified his name above all praise.
Let me love him while I live; trust in him, though he slay me; and "`in his nod divine,
have absolute repose.`"

Father`'s last account of our dear sister Remember`'s
state of health was very welcome to my mind.
Oh! that she may ever bow low before him,
that has so marvellously wrought for and restored her;
and ever improve her health and every talent to his glory and praise,
whose name is worthy to be had in everlasting remembrance by her,
and the whole house of Israel.
Amen.

I have been to Monthly Meeting at Pine street.
It is now past nine at night.
My line was still very close, but not in my own will.
For I rather commiserate the frailty of human nature, than delight in finding fault.
But I find no safe way, but in strict faithfulness to the clear openings of light.
Our dear women Friends from Ireland, visit the families here in a very close way.
It is very eminently a searching time: surely, not for nought.
Surely good will come of it to some souls.
The balsam of life seems given to the brokenhearted seekers among them:
though the threshing instrument is prepared for others.
It is, on the whole, a day of high visitation to this city.

I see no way out yet; and, seeing I must be, +++[+++I]
am given up.
I have received but two letters from thee, since I left thee.
Oh! how I have desired more; but must be given up to that also.
None from any of you since the 11th month.
This is my 19th to thee.
And now, my dear, as I expect before long to be with thee,
I hope thou wilt be prepared to receive me, whether before or after spring meeting,
without much of a shock.
A joyful meeting of the nearest friends after long absence, often overcomes their hearts,
and powerfully affects some, even to fainting, especially feeble and weakly persons,
as I conclude thou hast been of late.
Whether this caution may help or hurt, I know not; but am in much love and tenderness,
thy tribulated husband,

Job Scott

25th of 2nd month.
My mind is much as it was.
I feel somewhat relieved, since meeting yesterday;
and the extraordinary weight is in degree removed; yet no very small degree remains.
I see not when I may go hence.
It may be directly after this week.
However, I shall get home with all the expedition that I can, in clearness.
So, as before, I remain thy exercised husband, in fullness of unabated affection,

Job Scott

To his Wife

New York, 13th of 3rd month, 1790.

Dear love,

Getting here so much sooner, than, when I wrote thee from Philadelphia,
I was clear in expecting, though I had some such hope, I feel easiest to inform thee,
that I came here just before night yesterday, and am in tolerable health.
Here, I found dear Isaac Everett.
Here he is now by my side, and desires his love mentioned to thee and the family,
and also to Friends.
He is a veteran in the Lamb`'s warfare.
The sheaves of solid peace, I trust, will reward his faithful services.

As for me, poor and needy I left dear New England, and poor and needy I expect to return;
though not without relief of mind.
I find my dear Master is too wise, to trust me with any more cash,
than just to purchase necessaries, pay expenses, and discharge all debts;
and I am therewith content.
For, if I can return, clear of debt, well clothed, and able to labor for daily bread,
what can I complain of?
Or what signifies a purse full of gold, unless wanted for real use?
A hard-earned morsel is sweet to the taste,
whilst a life of ease and fullness is oft less tasteful, and also less healthful:
and beside, they who have more than the necessary supplies,
are very apt to indulge in superfluities; yea, to be taking the jewels,
and decking and adorning poor frail self.
On the whole, as I believe Agar`'s prayer the best that can be granted us in temporals;
so, I am well satisfied when I can be so far favored in spirituals:
the middle path is safest and best.
So, dear heart, thou may look for me, I believe, in a week, or at furthest,
as far as I know, in two, to return to thee, in rather a lowly state of mind,
very little if at all abounding; and yet, I hope, content,
and more than a little glad once more to behold and enjoy the dear company of her,
and of those, above all things most near and dear in life, and most of all beloved.

Many have been my afflictions, dangers, and trials,
since I took my last solemn leave of thee and them.
But though I have not always so escaped every wile, as to avoid, at all times,
every error; yet, blessed forever be his holy and all powerful name,
who has all along been near, and many times marvellously so, I have often,
through his aid alone, come off more than conqueror;
yet greatly in the subjection and abasement of self.
And in the faith that never failed me, I now trust and believe, that,
be the future gales of life adverse or prosperous, if I still trust in him,
he will never leave me nor forsake me.
Trust in him, dear love, with all thine heart, forever;
even though the fig-tree fail to blossom, etc.,
for those that trust in him will never be confounded.
His name is everlasting.
His power is over all: and he is on his way, to make the place of his feet glorious.
Let us be so inward as to discern the signs of the times;
and so attentively and devoutly exercised,
as to join in the life of the ancient living ejaculation, "`Arise, O Lord God of Israel,
into thy resting place; thou, and the ark of thy strength,`" This was, I believe,
nearly the language made use of when the cloud was taken up from the tabernacle.
And when the cloud returned, and rested on the tabernacle, the language was changed; and,
if now rightly recollected, was on this wise: "`Return, O Lord,
unto the many thousands of Israel.`"
Oh! there is deep instruction in it.
How has my soul bowingly struggled and pleaded with the Lord,
in times of darkness and clouds, that light might spring up, and he, the God of armies,
return to the remnant of his exercised Israel.
And then, when he has gloriously arisen, how has the language been, "`Spring up,
O well,`" more and more.
Sing unto it, O all ye inward worshippers.
"`Arise, O Lord God of hosts, into thy resting place; thou, and the ark of thy strength.`"

My soul is humbled in me while I write,
in remembrance of his marvelous and manifold dealings and deliverances.
How has he commanded the morning to arise, after midnight darkness!
How has he broke through the clouds!
He has often made darkness his secret place; and, as out of the midst of it,
has appeared as the sun at noon-day.
But words will utterly fail to commemorate the one
half of his goodness to the children of men.
"`Come, then, expressive silence, muse his praise.`"

John Pemberton, Samuel Emlen, John Parrish, and Warner Mifflin are here,
and have been for some weeks, attending on Congress, in regard to slavery.
Their success is yet uncertain.

My dear love to all as heretofore, and expecting soon to be with you, I conclude,
thy ever affectionate husband,

Job Scott

Extract of a Letter to a Friend

North Providence, 5th month 28th, 1790.

I look back on my late visit with solid satisfaction;
my mind is greatly relieved thereby; and whether it be of any use to any but myself,
or not, it can never be unprofitable to my own soul,
if I should dwell under a right sense of the Lord`'s wonderful dealings,
through the course of it.
I view with peculiar satisfaction and thankfulness
the kindness of Friends from place to place,
where my lot was cast.
May every care, attention, and favor be duly acknowledged by me,
and rewarded by the Lord, according to his own good pleasure.

I find my mind now engaged in family cares, and glad of being at liberty therefor.
It is pleasant to be sometimes at home; but there is need of constant watchfulness there,
a well as abroad.
Without it +++[+++there is]
no safety, and with it scarcely any danger,
as he that calls to the watch will not desert the watchful.
Thus greatly depends our preservation on our own vigilance, though we are nothing,
and can do nothing of ourselves unassisted,

Job Scott

To Daniel Anthony, Providence

Third-day, 28th of 6th month, 1791.

Dear father,

We know not what will be:
but our dear Eunice seems to be hastening towards another state of existence;
to which she seems pretty much resigned.
I find the bands of affection strong, and feelingly awakened, as things draw on:
nevertheless, as nothing now is, or presents to expectation,
but what has been anticipated, I am made in degree to submit to all things;
though how I shall get on through the painful scenes of life, deprived,
and yet surrounded as will likely be the case, he only knows who knows all things.
His will be done.
His name be blessed and praised; and if his mighty power preserve my soul,
and provide a dwelling-place for me and mine, in glory,
I submit all else to his disposal,
and desire cheerfully to drink of every cup he mingles for me; be it wormwood, gall,
or aught my further renovation renders needful.

The dear creature is desirous of a little more of thy company,
before the scene is fully closed.
Do try to favor us with it.
It is a time of trial; and may not prove unuseful, even to thee,
her ever-affectionate father,
as I hope it will not be to her not less affectionate husband.
She thinks she shall likely never more see her dear sister Ruth; yet, I think,
much desires it, +++[+++and]
has divers times feelingly mentioned her,
and the kindness shown by her in times of distress; as also dear Joseph, etc.
If any way might open for them to be informed, I should be glad, but I am not,
and I don`'t think she is, over urgent.
However, such scenes are often lastingly sealed,
with great advantage to near relations who are present at them.

So I rest it all, and am, as I think I ever have been since I stood in that relationship,
thy sincerely affectionate son,

Job Scott

+++[+++The above was written about a week before his wife`'s decease.]

To Margaret Haines, Philadelphia

Providence, 8th month 25th, 1791.

Dear friend, Margaret Haines,

I just now have received an acceptable letter from thee;
and though I have scarce known how to attempt answering a letter for many months past,
and have felt as near sinking this morning, as almost at any time;
yet I thought I would try to let thee know I yet live,
and have not forgotten my dear friends in your city, or elsewhere;
but at times have remembered, with much endearment,
some of the seasons which our God has given us together.
Thou and thy dear daughter have been among the remembered;
and I wish your unshaken establishment to the end;
but how can one who much of his time of late, sinks almost below consolation,
hold out encouragement to others?
I am sure the deep, hidden trials of the Lord`'s tried servants,
are often such as none knows of, but he only; and it is enough that he knows them,
and will certainly arise for our deliverance, if we abide in the covenant.

Oh!
I desire above all things to abide therein steadfastly, and endure all trials,
however severe, to the end; and am sometimes enabled to say heartily,
"`Though he slay me, yet will I trust in him.`"
Indeed "`unto whom shall I go?
He only has the words of eternal life;`" and out of him, and out of his favor,
I am sure there is no true joy.
All the world has nothing to give us, worth having, in exchange for the peace of God.
So that though it seems at times almost impossible to bear up,
under the mighty and depressing weight of exercise and inward agony,
yet I see clearly there is no way to get from it or shrink under it,
but it will double our difficulties.
God, who is all goodness, knows why the path of some is so thorny,
and their morsel so often eaten in extreme bitterness; and therefore,
seeing "`it is the Lord, let him do as seemeth him good.`"

As to the removal of my dear wife, my dearest possession by far and by almost all,
in this world; it is indeed a stroke of the divine hand,
to me more piercingly trying than I have believed I have any friend in this world,
that is, or has been fully sensible of.
I have not perhaps seemed to wear a great deal of outward mourning;
and as I have had all the assurance that heart can wish,
that my great loss is her greater gain,
I have been carried through without much murmuring;
and I suppose without seeming to observers to be over much affected.
But truly, my dear friend, my prospects seem to be all broken up,
and the world seems all wilderness, from shore to shore.
No business, no company, no conversation affords much satisfaction,
and a great part of the time, not any.
But why do I open so much of my own weakness?
I have often thought no mortal should ever know the extremity of my disconsolation;
and perhaps I ought to keep to it.
But without expecting or intending it, thus much has almost stolen from me.
I hope thou wilt make no ill use of it;
and perhaps my tears will for the future (as almost wholly hitherto) flow in secret;
though some effusions thereof, at times, have seemed almost irresistible,
even when and where I wished to suppress them.

But to have done with the heart-affecting subject,
I believe at times the design in this and every other affliction,
is to wean me altogether from the world;
and if I am but enabled to stand firm through all,
it will be no matter how deeply I drink the cup of suffering.
But, Oh! the danger of giving out, and taking my flight in the winter.
As to the sabbath day, I have for a long time seen but little,
if any danger of my taking flight thereon;
though once I thought I was in danger of that too.
But now my cup is bitter and ardent.
Lord! preserve my soul through all tribulations,
and suffer not the waters of Meribah to exceed in bitterness
my little ability to endure the provings thereof.

Please to mention my true love to dear Samuel Emlen, Samuel Smith, Thomas Scattergood,
and other of my dear friends, as thou see them, and thinks proper;
not forgetting dear James Thornton.
Oh! he has been as a father to me, when my soul was in deep waters.
The Lord bear up and support him through all to the end; indeed the others also;
that this may be the case with them all, is more than usually the fervent,
feeling desire of my heart at this time.
And if either of them shall find any thing to communicate by way of letter,
I think it will be received as a token of brotherly or fatherly regard.
But I suppose their life don`'t lie in letter-writing;
and I don`'t wish any one to go out of his proper sphere or allotment,
to gratify a creaturely wish in me or any other.
Indeed, though it is agreeable to hear from our friends,
and find they sympathize with us, yet I find all this does very little for us.
The Lord must be our teacher and our consolation; and if we ever become wholly his,
we must consent to be with him where he is; to fast, suffer, and die, as he orders.
And if he enjoins us to be dumb, and to open our mouths or our complaints to none living,
I believe it is safest to obey him.

Oh! none know the trials, but the tried.
However, there is this consolation, they have, if they will keep to it,
a tried rock for their foundation.
None ever failed that built and dwelt upon it.
It endures all winds and weathers; indeed, it is everlasting.
Oh! that our souls may know and keep to it, through all; and then come what will come,
our habitation will be in safety, and our refuge, the name of the Lord.

In much, and endeared affection, I conclude, thy exercised friend,
and tribulated brother, I hope I may say, thy fellow servant and laborer in the Lord,

Job Scott

P+++.+++ S.--Whether I am ever again to be loosened,
and engaged in any other part of the Lord`'s vineyard, but just about home;
or to be confined here to a scene of cares, tribulations, and perils, the Lord knoweth;
and his will be done in all things.

To Mary Ridgway and Jane Watson, Ireland

Providence 9th mo.
15th, 1791.

Dearly beloved friends, Mary Ridgway and Jane Watson,

As I cannot easily, if ever at all, forget your late visit to us,
nor that sympathy of souls, which I think I am sure was then deeply felt;
and as my mind is often as it were with you, since you left us, partaking,
in idea at least, of travail and conflict,
as well as relief and enlargement of your deeply exercised spirits from place to place;
it will not I trust seem strange to you, that I thus early pursue you in this manner.
Indeed,
although I am deeply sensible of far too great want of conformity in my stubborn will,
(though much broken and bowed,) to the will divine;
yet having no kind of expectation in the least,
ever to enjoy any kind or degree of solid good, or substantial satisfaction, out of,
or contrary to, the divine will and counsel; my looking is almost wholly to the Lord,
for consolation and enjoyment.
When in his light I can see my way, and in his life can find myself alive with him,
I then have true joy.
When the life is imprisoned, and cannot arise, and more especially,
when I find myself deviating from the right way of the Lord, I must and do mourn;
though even this is in the patience, whenever I am truly and fully preserved.
Well, this being the case, and finding very few travelling in this path,
almost all having their this, and that, and the other source of joy;
their many things that they are taking comfort in, such as it is;
whilst poor I am cast off, and forbid to take, or even seek,
much satisfaction in any thing but the life and power of truth.

Oh! how nearly and dearly this brings and binds to my heart, those few here and there,
who are traveling in the same narrow way,
and especially such whose life I feel and see to be almost wholly hid with Christ in God.
And surely if it is the joy of the servant to be with his master,
where he is in his sufferings, or in his reign;
his true-hearted servants and followers will rejoice to be with each other,
wherever and in whatever exercise they are, in his service; and though absent in body,
they will often be present in spirit, and therein, one another`'s joy in the Lord.
And truly, next to the consolation of the Master`'s company and smile,
is the company and heartfelt fellowship of these, one with another.
And Oh! that my life may be so preserved in and by the life of truth,
as that nothing may ever rob me of the precious privilege of this blessed fellowship.
Alas! all earth and ocean have scarce any thing worth having,
to give in exchange therefor.
Disappointment and insufficiency to satisfy the soul, attend all things here!
In God alone is true joy.
Yea, even the joy of his servants in one another is, at bottom,
but the joy they have in him;
and the moment any one of these departs from the joy that is in him,
to a life in joys that are out of him,
this one can no longer be or give true joy to the other,
who remains confined to the joy that is alone in him.

I do not mention these things for your information,
but merely as the present flowings of my own heart.
It is much my allotment not only often to be in, but to remain in travail and in pangs,
and I dare not give much way even to desire the weight removed before the Lord`'s time,
or wish to have his time hastened;
for he must reign till he has put all enemies under his feet in me,
if ever I reign finally with him.
And therefore, as it is through death, dying daily,
and being buried with Christ by baptism into death,
that any one of his and my enemies have ever been put under his and my feet,
why should I have any opposition in me to the continuance of the pangs of that death,
which itself can never be destroyed or taken away,
till by it all other enemies are put under; for, till then,
the work of mediatorship must continue; till then, we cannot say with Christ,
"`it is finished;`" till then, death cannot be swallowed up in victory,
nor God become all in all.
All which must yet be the case in every soul where Christ has so reigned,
as finally to put all things under him, thus of twain making one new man,
the only way to make true peace.
For this being completed, Christ, the mediator between God and man, of course,
or rather in the very completing or finishing it,
renders up the kingdom wholly to the Father, and God becomes all in all.

Oh! can any thing be too much or too long to suffer
or endure for the full accomplishment of all this?
Indeed,
when I can thus "`see the end of the Lord,`" what he designs to work and bring about,
by all bitter cups and fiery baptisms,
it abundantly reconciles my mind to this painful death and suffering, and begets in me,
I hope, a little of the "`patience of Job.`"
May it never fail me, and may I never turn aside for all my trials,
though they have grown, and though they ever so greatly may grow heavier and heavier,
and though in that depth of them, neither sun, moon, nor stars appear,
but "`darkness be over all the land, even from the sixth hour to the ninth hour.`"
And truly, such is my total darkness, at times, that I am wholly as a blind man;
I neither see nor know any thing; all past experience is as nothing.
Oh! the strippings of this state!
But I always find it ends in enlargement, if rightly abode in, and not fled from;
and sometimes after these seasons,
the openings and discoveries are unlawful to be uttered,
because scarcely any can believe them, or because they do not belong to them.

Oh! it is delightful to stand on Mount Nebo, and to view things far off, and near,
from the top of Pisgah.
But sometimes I think it most probable that some
of the excellent things beheld from thence,
will prove, as to me, abortive, and that I shall be buried,
(Oh! that it may not be on this side Jordan!) before I arrive
at the completion of all that mine eyes have beheld,
as I thought, in the visions of light.
However, that the Lord`'s will may be done in me, with me, and by me, in all things,
is almost my only wish.
My prospects for the world, are very nearly, if not quite wholly cut off.
If I may have food, and raiment, and preservation, what more can I ask?
What more can I have?
Wealth, honor, power, pleasure, all that earth affords, is emptiness,
as to satisfying an immortal soul.
Earth`'s phantoms I have indeed pursued, as most men and women still do;
but blessed forever, and magnified over all, be the power,
that has in some degree weaned me, though it has been through many deaths.
I now think it is no matter where I am, what I am about, what I suffer, what I enjoy;
whether I spend my days among my acquaintance, or wholly among strangers in remote lands;
where or how I lay down this body, so that all is according to the will of God.

The stroke, indeed, of his awful hand,
which rent from my bosom forever the dear partner of my heart,
and partner of my joys and pains, was like a sword pierced through and through my heart.
But he made me endure it without murmuring.
Indeed I durst not murmur.
And now +++[+++that]
she is gone, what have I in all the earth to delight in?
My children are near, my love and good wishes are towards them,
but I seem obliged to give them all up, and all things with them.
The dear little girl is just alive yet, though unlikely to continue long.
The Lord gave, and the Lord hath taken, does take, and will take away.
Blessed be the name of the Lord.

"`Good when he gives, supremely good,

Nor less when he denies,

E`'en crosses from his sovereign hand,

Are blessings in disguise.`"

The rest of mine are as well as usual.
Dear sister Remember, whose love is alive to you,
with desires for a place in your remembrance, is not very well.
Our dear parents as usual; myself as when you saw me.
Moses Brown as usual, his wife a little ill; and Friends generally much as you left them.

I thought a few lines would be all when I began,
and perhaps it will be well if I have not written too much.
However, with endeared love to you and dear Jesse,
and with living desires that the Strength of Israel may be with you,
and sustain you through every peril and probation, not only in this journey,
but to the journey`'s end of life,
and that the crown of unfading blessedness may be yours forever,
in the mansions of glory, and that in order thereto,
you may steadfastly continue with Christ, through and to the end of all his temptations,
I conclude, and am your exercised friend,

Job Scott

To Daniel Anthony and Family, Providence

New London, Conn+++.+++, 2nd month 17th, 1792.

Dear father, etc.,

This day we crossed the Thames, and came to this place.
Have had several meetings in this state, but all held in silence, as to myself,
till yesterday at Stonington, where my shackles were removed,
and my deeply exercised soul greatly relieved.
My imprisonment was, perhaps,
never more distressing in any journey than for most of the time since I left home.
Our way seemed almost wholly shut up.
I even concluded twice, to return home in my bonds;
and although that prospect was all darkness and distress,
yet there seemed no alternative, till, blessed be the name of our God,
he at last opened our minds, the day before yesterday, to come on this way.
David has said a little in most of the meetings,
but has felt himself rather fettered in all of them.
We both aim to possess our souls in patience, and not run of ourselves.
We are now pretty well.
Tomorrow, at eleven o`'clock,
we have a meeting appointed at the Congregational meetinghouse.
The success depends on aid divine; we can do nothing of ourselves.
I rejoice that I sensibly know it, yet despair not of doing all things required,
and more is never necessary.
Oh! how all societies err in striving to do something of themselves.
We painfully feel it here also; but I have time for hints only.

My love, unabated, is to the whole family and to Friends,

Job Scott

To Daniel Anthony, and Family

Salem, Mass., 7th month 3rd, 1792.

Dear parents, etc.,

I am as well as usual.
We were at Boston on first-day.
There I had no evidence, but rational and recollective,
that such a thing as true religion is.
Present experience of it I knew not that I had any.
Yesterday we were at Lynn.
I think there are many who, in degree, pant for life, among the youth there;
though to me the spring of life was low.
Low it still is, and my mind is low in it.
I have no more temptation to be proud, that I am sensible of,
than a man in the pillory or stocks.
It looks unlikely that my way will be much open in this visit,
or that the water will rise much above the ankles.
Well, low as it may be, I am glad I know it is not I that can raise it.
May Israel`'s only Helper help me to avoid attempting it.
If it were not for past experience, I should, I think, expect to return home soon,
and indeed, it looks not unlikely that must be the case,
though I cannot turn my back upon the east.
I think to try to reach the meeting at Newberry tomorrow, twenty-five miles,
and next day at Almsbury, three miles further.
I am easy as to outward company, and believe it best to be in degree so as to the inward.
With love, I am still yours,

Job Scott
