== Chapter V

Extracts from Letters

The will of God is ever best for us; and I am beyond a doubt confirmed,
that every attempt to escape from what he appoints,
and each impatient thought or motion under it, but adds to our affliction; and that,
until we bow without reserve, and without an inward murmur,
to the all-righteous sway of his sceptre in and over us, we shall remain, in some degree,
unhappy, and in pain.
But when all within us bows, the work`'s cut short; we see, we feel,
we own his hand in all; in all we kiss the rod.
Then he who hath appointed it most sweetly reigns.
His will`'s our law; and every word that from his mouth proceeds,
whether according with our wish as men, or quite opposing each mere human scheme,
sustains our life; that life, which, hid with Christ in God, has thus,
through loss of every other life, prevailed.
Oh! this is life indeed!
This, this is answering life`'s design.
Hard though it is for mortals thus to bow; yet once their resignation +++[+++is]
fully made, there`'s more true sweet in bitters thus received,
than in an unsubjected mind was ever known, in all the sweetness of its sweetest sweets.

Job Scott

Oh! how often I think what a blessing it is to have
lived to advanced age in the life of truth;
to have almost weathered out the storms, probations, and manifold temptations of life,
and to be nearly arrived on that happy shore, that haven of eternal rest,
where Satan himself can no more assault us: where the wicked,
(who oft in life molesting,) must cease from troubling, and where the weary, tried,
and often tribulated soul, forever finds its holy rest.

Ah me! what unknown conflicts, perils, and snares have I yet to encounter!
O my God! my only helper! keep, I pray thee, and preserve my soul,
lest after all I have known of thy love, thy aid, thy wonders in the deep,
and turning of thy holy mighty hand and arm, in many, yea, mighty waters,
I unhappily let go my hold on thee, and slide, as many have slidden before me,
from the line of holy commandment.
But whither has this unexpected effusion of heart transported me!
Forgive me, if I divert from the common laws of letter-writing.
I have my ebbings and my flowings, and may be too much influenced by them;
but what shall I do with such tender emotions as
I sometimes feel when looking at the faithful,
who have almost run their race, and are, as lively hope represents it,
nearly at the fruition of endless enjoyment!
My heart expands at times under the lively sensations hence produced,
in a manner better felt than described.

But then, Oh! the painful balance presented in view, of dangers awaiting us,
whose race in religious exercise was long since theirs commenced.
How many have fallen on the one hand and on the other!
The world, the flesh, and the devil, how potent these! how they allure!
How many, once in a good degree escaped the world`'s pollutions, have again listened,
have again been ensnared, till finally centred in the bondage of sin and corruption!
And how many have concluded it safest to avoid much thoughtfulness about religious things,
lest they should fail in their attempts and resolutions.
But, alas! alas! there is no possible place of safety,
but in a deep religious acquaintance with the living God.
And what will be the woeful, the final,
direful end of those who live and die without this blessed acquaintance!
No plea will then avail; it will not do to say in that awful hour,
I was afraid I should not hold out, and so I declined even to begin.
No, no; as our works and lives have been, our reward will surely be,
all our pleas notwithstanding:
we shall receive a reward according to the deeds done in the body;
not according to some imaginary purgation which some vainly hope will take place afterwards.

Job Scott

I don`'t marvel that the letter-learned teachers of our day, who run unsent,
who are always ready, and never qualified with divine power,
are ignorant that a true gospel minister is clothed
with baptizing authority from on high.
It is much the business of that class of men to bring
down or represent the service of the gospel,
as being level to the abilities of creatures.
If they were never to preach, till divinely prepared,
their pay would probably not soon become due.
Therefore they wish not to be under the necessity of waiting for that qualification.
The shortest cut is,
to insinuate or maintain that man can preach the very gospel of Christ,
without divine inspiration.
This many do say, though not all.
Having then brought down the gospel ministry, as it were,
within the reach of their own powers, if they can bring Christ`'s baptism there too,
they will seem to have the work pretty much in their own hands.
This must remain a great difficulty with them,
unless they can find something that human ability is equal to the performance of,
that shall pass for christian baptism.
Nothing bids so fair to be received instead of Christ`'s saving baptism,
as John`'s water baptism.
This, therefore, is christened with the name of Christ`'s ordinance,
and passes current as such among the people.

Job Scott

5th of 10th month, 1792.

Things are so superficial amongst us, that some few of us,
who perhaps get a trifle deeper, are ready to think we have attained a very good depth.
Even such might tremble, if pure truth were to arise,
and strip all naked that is not "`clothed with the sun.`"
Oh! excellent state of the church!
Oh! different,
vastly different from our day! "`Clothed with the
sun,`"--"`the moon,`" all that is changeable,
and a great deal that is borrowed, "`under her feet,
and crowned with a crown of twelve stars.`"
Where are the stars now?
Is their shining ceased?
Is the "`gold become dim, the fine gold changed?`"
Are some now become as brittle,
"`earthern pitchers,`" that were once properly "`comparable to fine gold?`"
I often fear greatly for myself when I think of others;
and especially when I have to use the scourge of small cords.
But it will not do to look back, or let go our hold, or give up the cause and testimony.

Oh! let death come over all that would live and act in independency.
Christ must reign till all rule but divine is put down; and the sooner, the better;
for we shall never know a principality or power in us, made subject to him,
but through death.
Burial with him by baptism into death, therefore, is a blessed experience.
It is the prayer of my soul that I may know it thoroughly.

Live in love and prefer one another.
Cursed be that in any, that would be grudging or jealous, without just grounds,
of another`'s greatness.
Lie low; sit low; live low.
He that sits upon the ground seldom falls lower.
Delight to see each other prosper, and grow in the truth, and do all you can,
to promote it, and to keep each other`'s way open among the people.
United, you may stand firm, and be each other`'s joy in the Lord.

Job Scott

Extracts From Letters to Remember Anthony, Just Before Setting Out on the Voyage to Europe

There are very few things that I seem to be allowed to take much satisfaction in,
in this world.
I now and then partake of a cup of consolation in divine things that is truly inexpressible;
but this it is not my lot to enjoy, but through deep probation.
Among the few things, short of celestial, which afford solid satisfaction,
that of true and affectionate, cementing friendship, stands foremost.
There is something in it, when truth is its foundation, that indeed forbids us to say,
it is not heavenly; at least, there is somewhat of divinity in it.
It is often counterfeited; and something very unlike it assumes its name,
and passes for genuine.
But a counterfeit ever implies, that there is somewhere a reality.
Happy are they who find it.
It is an inestimable treasure, a source of heartfelt satisfaction and enjoyment.
It is true, as the poet says, "`Friends grow not thick on every bough.`"
So much the more valuable, where they do grow.
The few I have the happiness to be sure of, are chosen and tried.
I believe they would be willing to suffer much with me, and for me, if needful;
and I think I could with them.
There is a precious fellowship in sufferings; and those who know it present,
feel nearly for each other, absent.

I trust, if I cross the briny ocean, thou dear heart, and a few more that I know by name,
and by inward acquaintance, will have in my breast,
a place of cordial and fervent remembrance.
I have no idea that time or distance,
will ever deface the impressions that are of truth`'s making,
and stamped on the heart in deep and living characters.
Health, well improved, is a blessing; but the Author of all real blessings,
can make sickness and sorrows more truly profitable to us,
than health or plenty might be.
Let us ever bow unreservedly to his holy will, in all things,
and expect no true joy in any thing, out of his appointment and approbation.
This advice is easy to give; and if it is hard to comply with,
it is my travail and engagement of soul to be found fully in it.
I don`'t expect I ever can have any solid enjoyment out of the divine will;
and though my own often strives to run counter,
I find the shortest way to reconciliation, is the instant surrender of mine,
to his that`'s ever good and gracious.
If he permit my foot again to tread New England`'s shores, his name be ever praised.
I may then rejoice once more, face to face, with those the nearest friends in life;
those that are flesh of my flesh, and bone of my bone.
But if a watery grave he dooms my lot; or, my bones to mingle with the dust,
beyond the Atlantic,--his will be done.
I shall then, if found worthy, unite with the hierarchies of heaven,
in praises and hallelujahs forever.
But I often feel as if I should never be worthy of a harp in that celestial assembly.
That I must leave.
The way is cast up, from time to time before us; if we will walk in it, we may.
And that we may, is what I wish above all things, for myself, and for thee.

Farewell.
Remember me in thy nearest approaches to the throne,
or within presence chamber of thy God.
And whether on Columbia`'s shores, old ocean, or on Albion`'s isle,
or wherever winds or waves may waft me, I trust I shall,
with endearment and sincerest affection, remember thee.

Job Scott

P+++.+++ S.--The foregoing I leave with thee, for thy satisfaction, if any it may afford thee.
Our constitution is such,
that though our true satisfaction is only in the heavenly places in Christ Jesus;
and there we may find it, whether a friend on earth pities, remembers, or regards us,
or not; yet we sometimes derive something pretty sweet and consolatory,
from the fixed and well-grounded assurance,
that we live in the hearts and affections of our friends.
Be assured then, my long, sincerely, and affectionately beloved,
that my heart is not conscious of any abatement.
There are friends in many different relations, as father, mother, husband, wife, sister,
brother, son, daughter, etc.
There is something sweet in them all.
But whatever be the relation, or whether there be any outwardly or not,
there is a cordial, a relish, an inexpressible endearment felt,
where hearts are rightly united in friendship,
that I believe really vicious persons scarce ever feel, or have a clear idea of.
And this is not diminished.
No, dear soul.
I feel thee, I shall feel thee in this endearing relationship.
I go: for truth forbids my stay.
But wherever I go,
I trust I shall not forget I have a little sister that has felt with my afflictions;
that has sighed for my distresses; that has shared with me and mine, in many a woe.
May the dew of heaven rest upon her.
May the innocence of the lamb procure her protection;
the fortitude of patience and true resignation, through every dark passage and probation,
sustain her; and the live coal from the altar,
prepare and fill her heart with thanksgiving and acceptable devotions.

Remember me; remember her that`'s taken from me forever;
and remember mine and hers that are still survivors.
What thou canst, do for them.
It will add so much the more to the score of obligation, and the rewarder of all, will,
I trust, reward thee.
If I review not the mansion where so many scenes have revolved,
nor set my foot upon the plains that surround it; forget not thou,
that once thou hadst a friend, a companion, a brother that loved thee.
Be assured, if favored with the exercise of his intellectual faculties,
(shouldst thou hear he is no more,) that in his last agonies, he remembered thee,
with sincerest desires for Heaven`'s all-gracious care and protection over thee.
And when I am gone forever, though the tear be wiped from thine eye,
live in thine heart the never dying friendship; and let the evidence of its immortality,
flow down upon his tender and bereaved offspring.

Job Scott

I rejoice with joy unspeakable, and, in the depth of gratitude, I bless my God,
that this day, whilst I was steadfastly endeavoring to stand faithful,
and keep my foot on all that would divert from his counsel, he has, in a way unexpected,
given me the victory, and bruised Satan under me.
My trials have been many and various.
Almost every way that could be conceived, has my path been straitened.
On the right hand and left, the lion has roared.
My friends have felt little of my anxiety.
Joseph`'s brethren saw the bitterness of his soul, and had no compassion;
mine have seemed to have very little sight or sense of my deep probations.
Perhaps my God left them to insensibility for my trial and improvement.
May they be gathered into that, wherein nothing will be laid to their charge.
May the blessings of Heaven be showered upon them, as they draw near, and wait for them.
My heart feels nothing of unfriendly resentment.
Though my passage be lengthened by their delayings;
though I see tremendous roarings of the elements, that might have been avoided; or,
though the waves should close upon me forever,
I pray the God and Father of our Lord Jesus Christ, to be with, comfort,
and preserve them.

Job Scott

To Daniel Anthony, and Family

Boston, 28th of 11th month, 1792.

Dear parents, sisters etc.,

I am well and cheerful, at Boston;
expect Thomas Arnold and Smith Brown will leave me this morning, and return home.
The ship sails not till next third-day; perhaps not then.
I expect to go to Lynn tomorrow or next day, and may stay till second-day.
I feel for you.
There is a possibility, and is there not a danger of too great sensibility of oppressive,
injurious, or overbearing treatment?
Is it not best to submit all to God, trust firmly in him,
and think as well as possible of all,
especially all who have really some good things found in them?
"`Father, forgive them,`" etc.,
is the language at heart feelingly and sincerely of every one that
is Christ`'s. It is comfort to him who feels the disposition;
and it gives him the best of all victories, over his enemies.
"`Amor omnia vincit.`"
"`Love conquers all things.`"
It is the mark of discipleship; the saint`'s cement among themselves;
and their conquest over the very spirit of oppression.
A word to the wise is enough.
I rejoice that this great lesson is in good degree learned by several of you,
whom I dearly love; but we need often to learn it over, and get deeper in it;
for nature is revolting back to its old bias and feelings.
I very sincerely wish you the enjoyment of Heaven`'s best and richest blessings,
and commending you all to God, with fullness of unabated affection, remain yours, etc.,

Job Scott

To Daniel Anthony, and Family

Boston, 4th of 12th month, 1792.

Dear father, etc.,

Yesterday I returned from Lynn, where I went on sixth-day last.
Friends there and here are mostly well; so am I, and more cheerful than I expected,
though I feel like "`a worm and no man.`"
My mouth was not opened in their large meeting at Lynn.
I don`'t find that my will ordered it, but believe it was ordered well.
Mark and captain Glover say, the ship will sail tomorrow, wind and weather favoring.
Its name is the Mercury.
I have no doubt of comfortable accommodations on the passage.
No great things are needful for me.
Give my love to father Scott, and tell him I have thought much of him, since I left home,
and wish him comfort in his old age, and a mind truly resigned.
May the Lord be with him.

And dear parents,
I feel desirous to express a willingness that you should
avail yourselves of every advantage on the place,
which you think will not injure the estate.
I don`'t know that mentioning this can be of any use, but it rested with me.

Live all in love; speak kindly and tenderly to each other.
Soft expressions turn away wrath, and endear friendship.
Trust in God.
It is not formality, or words of course, to say, he is a never-failing helper.
Have recourse to his all-sufficiency, and readiness to assist, on every trying occasion.
I would trust in him, even though he were to slay me;
even if my own imprudence were to plunge me into sorrow and difficulty.
I have none in heaven or earth to rely upon besides him.

Men are almost ever changing.
The man most attached to us today, tomorrow may set up a cry against us;
may undermine and forsake us; may speak us fair, and retain our confidence,
yet treacherously and slyly insinuate something against us.
On the other hand, one that even seems to persecute us, and delight to oppress,
may pluck us out of difficulty; may soften, relent, and kindly embrace us.
Let then our eye be to him, who turns hearts "`as streams in the south.`"
Let us not be too much pleased with the smile of mortals,
nor let their sourest frowns depress, or in any degree perplex or vex us.
Let us not think them much the better for favoring, nor much the worse for opposing us.
God teaches us, if we are docile, in all these things, to see him,
the only ground and source of stability, goodness, and consolation,
and to despair of it from every other quarter.
Here he becomes our "`all in all.`"
Here, we become "`complete in him.`"
Here we repose secure, above the fear of contingencies,
(except as influenced by our own deviations,) and rest satisfied in ourselves,
through the aid of Omnipotence, beyond the noise and strife of archers.

Don`'t forget me in any of my painful peregrinations.
I trust you will not be forgotten by me.
I feel you near, in endeared relationship,
and that not confined to the outward connection; the best of it is invisible.
Many waters cannot quench, nor floods drown, nor time, I trust, nor distance, erase it.
I don`'t feel as if I was straining points, or trying to exceed reality,
and living sensation.
It is but the effusions of the heart I am expressing; and these need no decoration.
From the heart they flow sincerely; and therefore I rely upon it,
they will find their counterpart in yours;
and that we shall live in each other`'s remembrance.
And may the arms of Omnipotence sustain us.

Let me hear from you as soon and as often as you well can, and inform me your state,
and material occurrences; and how it is with all my dear little motherless, and now,
as it were, fatherless children.
But have they not fathers and mothers provided?
Yea: blessed forever be the name of the Lord.
He is rich in mercy, and plenteous in provision for his servants.
My very soul is humbled in me; mine heart affects mine eyes,
in contemplation of his goodness.
I feel no worthiness in me, of the many favors vouchsafed.
"`With my staff, (said Jacob,) I passed over this Jordan,`" etc.
Oh! the passage at Jordan!
Oh! the probation, at the river of judgment!
God only knows the provings and perils of his people.
They are judged of very superficially by thousands, who assume the seat of judgment;
who think they know; and who even can with the left hand,
fling stones to an hair`'s breadth, and not miss.
And yet, alas! they know not how he proveth his at Massah,
nor after what sort he striveth with them at the waters of Meribah.
What ye know of these things, my dear relatives, under that roof,
in your own experience and provings, know for yourselves; and God also knowing them,
be therewith content.
He sees every falling tear; and every sigh his holy ear will hear;
and our safety in tribulation may be much greater, in hidden obscurity,
veiled from the penetration of mortals, than in exposure to their notice and caressings.

I have much exceeded the length of my expectations;
and in near and affectionate remembrance, I here may close,
wishing you the blessings of Heaven, and an hearty and fervent farewell.
Yours, etc.

Job Scott

P+++.+++ S.--My love to Friends.
I expect to sail in a day or two.
The Lord on high is mightier than the sound of many waters.

To Remember Anthony, Providence

Boston, 12th month 4th, 1792.

Beloved sister,

Though I feel thee included in the address of my heart this day to our dear parents,
and also the rest of my dear sisters and brothers,
yet I may express my desires for thy firm unshaken reliance on All-sufficient Goodness.
Rich in mercy towards thee, has been the infinite Jehovah,
and if he yet lead thee through straits, perils, sinkings, and deep probations,
Oh! trust in him forever, nor suffer his wonders ever to be forgot.
His arm has been made bare for thy deliverance.
The sea has been divided for thy passage;
thou hast trod on dry ground through the midst thereof.
"`Jordan was driven back.
The mountains skipped like rams,`" etc.
Hold fast, therefore, the beginning of thy faith and reliance steadfast to the end,
and then I trust he will be with thee through all.

Be good to Ruthy and James; but not too good.
Indulgence may ruin them.
Don`'t cast away thy little James in adopting his little sister.
Thou accepted her at last with open and broken heart.
Have her therefore as thy own, till I return, if I ever do so, if not, keep her.
If I return, keep her, or return her, according to thy good pleasure.
Have an eye to all her brothers and sisters.
Watch over and advise them for their good.
Write to them, and desire father, Joseph, Richard, and Alice, to write to them.
Keep up the acquaintance and affection.
Encourage them to learn, and when they can write,
encourage them to write to thee and the family,
and to tuck a line in for me when some of you are writing one.
And let me hear from thee by a line,
and tell my dear brothers and sisters a line from them will be truly acceptable.
Tell dear sister Alice I crave her kind care and attention to the dear children.
Don`'t forget my dear old father; be good to him, be kind to him, thou and all of you,
and make him comfortable.
I trust you will be faithful in this, and I rejoice in the confidence of it.
May his old age be happy!
May his knowledge of God be increased,
and the blessing of Heaven be on you for your kindness to him.
Teach the children to love and respect him.
Teach them civility to all persons, and tenderness to all creatures.

I enclose a little piece called The Birds`' Nest, in substance,
from a book entitled The Children`'s Friend.
If thou think`'st it will inspire compassion into their hearts, let them hear it,
or have a copy of it.
The verses On a Child in the Cradle, I took from the same book.
My simplicity may excite a smile, but truly my heart was touched in reading them;
so I copied them for thee.
They may be better for the children to learn, than some that children do learn.
I desire thee to do a little at teaching them to read.
I hope thou may not be a loser by any care bestowed on them.
But above all bring them along in the nurture and admonition of the Lord.

My dear love to all my children, and to my two little sisters.
Bid them be good girls.

Dwell deep in the holy root, and therein thou wilt,
as is thy brother`'s ardent wish for thee, dear sister, fare well.
Thy affectionate brother and friend in the travail of the gospel,

Job Scott

To Daniel Anthony and Family, Providence

Dunkirk, 7th of 1st month, 1793.

Dear father, mother, etc.

Having, through the kind providence of a gracious God, arrived safe here,
the day before yesterday, I now give you an account of my voyage.
We sailed from Boston 5th of last month, and I got here +++[+++the]
5th of this.
The ship had not, till just now, got into harbour.
The very first night from Boston, the cry was, "`All hands ahoy.`"
They were soon all on deck, and the ship put about to return to the harbour;
for she proved very leaky; and the leak rapidly increasing, that is,
from 100 to 600 strokes an hour, in the course of a few hours.
The captain, mates, and crew, were alarmed.
But she soon leaked less on this tack; and they put about again, and stood out to sea.
She still leaked much when put about;
next day the captain and several men searched on the outside,
but could not find the leak.
After awhile it moderated,
when returning cheerfulness glowed in the countenances of captain, mates, and men.

Sixth-day, 7th of the month, the leak greatly increased, to near 1,000 strokes an hour.
Sadness again resumed its empire over the countenances of the crew.
The captain knew not what to do.
At length, he put about again, and sailed homeward.
The weather was pretty rugged all the time of this increasing leak,
and part of the time stormy.
After awhile the captain had a hole cut through the second deck,
and searched inside for the leak, and soon found it,
being an open augur bole of about an inch and half augur, at the ship`'s stern,
so high up as not to leak constantly.
This being stopped, the number of strokes was soon reduced to 25 an hour.
Oh! what a change of countenance this wrought.
All soon seemed as if they had forgotten all their sorrows.
They put ship about, and went to sea in earnest.

Second-day 10th of the month, the wind arose,
and roared tremendously all night and all next day and night.
The men tied up the sails, lashed the helm, and lay to,
or let the ship drift in the wind and waves.
About the middle of the time,
the captain said he had not seen so violent a gale
of so long continuance for eight years.
So said the rest.
All said it was truly terrible, but we had sea room enough--a great consolation.
It stormed near all the time; but most violently the last night.
This night, I assure you, the storm and wind were dreadful.
Fowls died; the one sheep, though between decks, nearly died; divers spars broke loose,
and were lost, though pretty strongly lashed; and a good new whale boat on deck,
well lashed, was much broken.

Oh! the rising surges of the breaking, foaming waves!
Oh! the rocking, pitching, rolling, of our ship!
I thought of Addison.
"`When wave on wave, and gulf on gulf, overcame the pilot`'s art.`"
But as the scene was new to me, my description may be thought to border upon exaggeration.
However, blessed be the Strength of Israel, my only hope, my only stay, I felt resigned,
and stilled and stayed through all; though very little light shined sensibly on my heart,
now, or at all during the whole voyage.
But I saw God`'s wonder in the mighty waters.
It seemed at times as if the briny waves would soon swallow us up;
yet I never really lost my confidence,
for all this was no more than for months I had firmly expected to meet with.
You know it was sealed on my soul, that the loud roar of wind,
and the dread rolling of the waves, would awfully attend my passage.
And now indeed it proved my hold on Heaven.
I said in my heart, It is the Lord; let him fulfill his purposes.
Let him do just what he will with me, in time and in eternity.
Nought else beside his holy will can ever be good for me;
and why should I wish even the most disagreeable parts of it averted, mitigated,
or shortened.
I thought I had had his holy promise who cannot lie,
that I should live through these dreadful tossings on the bosom of the ocean,
and once more set my foot on firm ground, yea, bless his holy name,
in wonders yet to come on shore.

I cannot say, I had no reasonings in regard to the divine superintendency;
but I well remembered the clearness of prospect wherein I had,
even before I went into Connecticut, seen this dispensation on the ocean.
I also livingly remembered the holy warmth, energy,
and assurance that attended the promise of safety through all;
and though it was now the divine will that the evidence
of divine things should be low in my mind,
yet I could not cast away my confidence.
Indeed, low as the evidence was now as to Deity itself,
I yet seemed almost or quite certain, that if the Lord liveth,
and if I had ever known his holy word at all, I surely had had it, and might rely on it,
in this instance.
Here my foot fixed; and my all I surrendered up to his disposal,
not once wishing myself on shore, nor in another vessel:
for I never had even hoped to escape this tempest, for good part of a year before.

Fourth-day, 12th, about noon we got under sail again,
though still the roar of elements with awfulness remained.
We got on slowly for about twelve days from Boston, then had good, fresh, fair winds,
and made good speed, till we got soundings in the English Channel.
Second-day, 31st, afternoon, we made the Lizard.
Third-day, 1st month 1st, 1793, soon after midnight, just as new-year commenced,
we had another fresh strong gale, with rain till near night this day.
This was awful, but trifling to the other.
After this, calms and contrary winds, and, about Calais, contrary tides detained us.
At length we cast anchor, on seventh-day, the 5th, just a month from Boston,
not in the road, but about four miles from the harbour.
Anxious to be with Friends next day at meeting,
I went on board a pilot boat among Flemmings and French, all strangers,
and got safe to dear William Rotch`'s, where I now write, and am very kindly entertained:
he and his family all well.
Benjamin and wife in London.

We had scarce any sunshine the whole passage, but much wet.
I never was very sea-sick, yet scarcely ever ate with much relish; +++[+++I]
seldom wished to eat at all, but ate to live, and ate enough to nearly keep my flesh.
Slept almost none, many nights: on the whole, +++[+++I]
might sleep a third of what was usual,--I think not more.
The ship rolled abundantly.
I feel and see the motion yet disagreeably.
The house seems going up and down continually, but I am otherwise very well,
and have been throughout.
I have great satisfaction in being here.
Was at meeting yesterday, and rejoiced in moderation,
in hopes the spring of life was not finally closed;
though I had scarce felt it on the passage,
nor seen that I could ever again set one foot before the other;
yet my faith never quite failed me.
I had some deep provings, wherein all former experience failed to prevent great sinkings.
Oh! thought I, at a few broken seasons, if I ever again set foot on Columbia`'s shore,
and those I left beneath my humble shed are living,
we surely shall mingle tears in remembrance and relation of our adventures,
during absence; at least what mine eyes have seen, and heart has felt,
will never be forgotten.
I don`'t see which way I may go hence yet; perhaps none for some days,
or till my head is a little settled.
My love is not on the decline to any of you.
Please communicate it as from my heart to my own dear father, all my dear children,
brothers and sisters, relations and friends.

12th. It is just a week since I got to Dunkirk, and here I am yet, well in health,
my head well settled,
though my mind has been sunk even into the contemplation
of almost immediate return to your land;
but my prospects begin to grow more pleasant.
I expect to go hence on second-day for Dover, and likely soon for London.
Dear William Rotch, and Robert Grubb, a choice living Friend of Ireland, now here,
I expect will be my company.
William I think will spend some time with me if I stay in England,
but not go into Ireland.
At present I can see no further than London, and it would not be strange to me, if there,
and thereabout, I should spend the winter; though I think,
if I had got away according to my own prospects, opened, I still trust,
in the light of Israel, my way might have opened early into Ireland.
But I resign all, and am, in fullness of love, yours, etc.

Job Scott

P+++.+++ S.--Do write me as soon as well may be.

To Remember Anthony

Dunkirk, 7th of 1st month, 1793.

Dear sister,

I feel nearly excused from writing thee at this time,
as I have written largely to father and the family.
There, please to read my unabated regard for you all.
It is low water with me, but I may inform thee,
that thou hast had a place of feeling remembrance with me,
in all my tossings on the mighty ocean.
Oh!
I think thou canst have but a faint idea of the awfulness of the
tremendous scene I have described in my letter to father.
But what are all the tossings our bodies can endure?
Or what matter where, when, or how they moulder into dust, if so it may be,
that the part which cannot die be united with the one eternal source of all good?
Utter annihilation is the most dreadful to me of all possibilities.
I can with more consolation endure the idea of a degree of eternal pain,
than of total extinction.
And unworthy as I feel myself of the smiles of Heaven,
there are but very few moments when the evidence of immortality is strong in my soul,
but that I can look forward towards future existence with divine consolation.
I as much depend on receiving the just reward of all my works,
as I depend on life out of this body.
But there is nothing in the idea of a full recompense for all my misconduct,
that is at all terrifying, when I look towards futurity.
But, Oh! "`abhorred annihilation!`" what is it can possibly give it,
even to the most abandoned mortal, such "`dreadful charms?`"

Whenever I am assured the Lord liveth, as, blessed be his name, I sometimes am,
and have the living evidence that "`souls can never die,`" there
is nothing in all the possible determinations of the divine will,
that I can fear.
In short I then find nothing to fear but the deviations of my own will;
and nothing to hope or wish but the complete accomplishment
of the divine will in all things.
And in proportion as mine becomes swallowed up in the divine, I find,
as William Law expresses it, "`every day has lost all its evil.`"

This manner of communication was altogether unexpected; and whether it be for thy sake,
or any other in the family, I know not.
May God Almighty hold thee and me, and all his own, in his holy hand forever.
May we, and all we love, live near, and yield wholly to him,
and then we are sure of "`possessing all things.`"
This is my prayer to Heaven, dear sister, for thee, and for us all;
and I scarce know another wish for any thing in the universe.
"`All else beneath the sun, God knows if best bestowed or not, and let his will be done.`"

Remember me to all my dear little motherless children.
Be kind to them; cultivate them.
Bring them forward in God`'s holy fear, and in reverence of his inward appearance.
Live all in love.
I must now close; and I do it in fullness of sincerest brotherly affection,
resting thy still often and deeply exercised friend and brother,

Job Scott

To Moses Brown, Providence

Dunkirk, 1st month 7th, 1793.

Dear Friend,

I arrived here in good health, except the effects of motion at sea,
the day before yesterday having been as well during the passage,
(which was from the 5th of last month, to the 5th of this,) as the sea would permit.
In the forepart of the passage we had an awful gale and storm for two whole nights,
a day and nearly a half; another we had in the English channel, but lighter.
Except these and an alarming leak, just after we got out of sight of land,
which was found and stopped, we had a favorable passage,
though scarce any clear sunshine, or but little, the whole voyage,
and a good deal of wet weather.
My mind has been quiet through all,
though I have little more than just to live by faith and not by sight.

I rejoiced a little in Friends`' small meeting here, yesterday; and find,
(so far as experience can find and I have proved,) the Helper of the helpless is omnipresent.
I met with him in Dunkirk, to my comfort,
though but few here may have a very sensible acquaintance with him.
I am well satisfied in being here, but see little or nothing forward yet;
I find my regard for Friends at home does not decrease by absence,
nor by distance from them; though I can say but little now,
of any thing more than good wishes.
If thy wife is living, please to let her know I have not forgotten her afflictions,
but am assured all works good, that is well borne and improved.

If Friends inquire after me, tell them I yet love the brethren;
but I see no way to name particulars.
I think I have felt sincere desires for a growth in the divine life,
in our Monthly Meeting; but my prayers have been, I hope not selfishly, though mostly,
for myself, my own preservation, direction, and safe movements.
It is low water, where my mind is now nearly aground;
yet faith and patience abide with me, steadfast companions.
I have but one wish respecting myself in time past, and but one for time forward:
that I had been, and that I may be, singly observant of, and devoted to,
the manifestations of the divine will, comprehends all my desires at present.
As to all temporal enjoyments or sufferings, "`thy will,
O my great and gracious God! be done forever,`" is all I ask about them.
The visitations of his Holy Spirit to my dear little children,
and their early subjection thereto,
weighs inexpressibly more with me than all earthly acquisitions.

Job Scott

To Remember Anthony, Providence.

First-day evening, 1st month 13th, 1793.

Dear sister,

I am yet at Dunkirk, well, and well relieved.
For after a favored, open time at meeting today,
we appointed a meeting at six o`'clock this evening;
in which the stone was so rolled from the well`'s mouth,
that I expect to go hence tomorrow morning at eight, which is sunrise here;
and I expect to go, clear of the place, which I have not been before.
Dear Robert Grubb is a living, lovely Friend.
The journal of his dear deceased wife, Sarah, is just out of the press; an excellent,
instructive book.
Some passages of it I wish to send thee,
as I think they might greatly encourage thee to yield up,
in full faithfulness to all the Lord`'s holy requirings;
but I have no time to transcribe them.
It may be, from England, I shall try to send thee and the family, one of the journals.
Be that as it may, there is nothing I desire more feelingly for thee, than faithfulness,
and full dedication to the Lord`'s call and appointment.
If that takes place and continues, I shall rejoice, if I live to see thy face again,
to behold thee shining in the beauty of holiness,
and grown strong in the name of the Lord.

Farewell, farewell, says thy affectionate, and at the same time, consolidated,
though often stripped and deeply tried, brother,

Job Scott

To Daniel Anthony and Family, Providence

London, 28th of 1st month, 1793.

Dear father, mother, etc.,

A vessel being to sail tomorrow for New York, I am not easy to omit writing,
though I lately wrote you and Moses Brown, from Dunkirk.
This will likely come to hand first,
as no vessel was expected to sail thence for America till towards spring,
but as in that I gave a pretty large account of my voyage,
and the tremendous things seen on the bosom of the deep, I omit repeating it.
I lived through it all, supported by unfailing help,
and came to this great metropolis last sixth-day,
the 25th. Crossing from Calais to Dover, I took a great cold,
and was very ill at Dover several days,
so that last second and third-day I was an house-keeper, but on fourth-day,
by post-chaise, came to Rochester.
Fifth-day, stayed their meeting.
Sixth-day, came here, and attended the Meeting for Sufferings,
as also two sittings of it on seventh-day.

Yesterday attended Gracious-street and Devonshire-house meetings;
bound fast in silence in both,
as again today in the morning meeting of ministers and elders; though I was helped,
in two of the sittings of the Meeting for Sufferings, to break through the cloud,
and rise above the too superficial spirit in which far too
many of the members are thinking to build up Zion.
They will never be strong men in the Lord till they know that forward,
always ready spirit, more limited and subjected;
and I obtained great relief in faithfully telling them so.
Some of them mind little what a poor New England man thinks and says.
They are rich, wise, full, and would seem to know all things, as it were;
but truth was over them at last:
and yet I see little prospect of much room for me among them.
I think it would be as welcome to my natural will, to live on bread and water,
among my dear friends in New England,
as to continue under the painful weight of what a
part of the time I feel in this great city.
However, there is a living remnant here that my soul truly loves;
and if the great Father of the family pleaseth, he can and will open the way: if not,
my will is still in submission,
and in the midst of deepest trials I have nothing to complain of.

I lodge at deaf John Elliot`'s, Bartholemew Close.
The family is kind, and so are Friends in general.
My cough is much mitigated, though still considerable;
but I am obliged to live sparingly in this climate
or I don`'t know that I could keep about at all,
but by and by I may get seasoned.
Dear William Rotch is agreeably with me; he bore me company from Dunkirk,
and may accompany me some time.
I see no way hence at present, but may likely spend the winter in and about London,
though I don`'t know.
Ireland lives with me, but the way is closed at present;
probably it might have been open, had I arrived some time sooner;
but I hope all will be well.
We are obliged to travel with passes from authority,
an alien bill having lately passed here requiring it.
Great preparations are making for war.
The Meeting for Sufferings have just addressed the king, or prepared an address,
wishing the prevention of human bloodshed, and just touching on the slave trade.
It is expected Parliament will, before long, again discuss the question of abolition,
but the event is wrapped up in uncertainty.

I feel that I am in my place and proper business,
though depths of trial and distress almost make me flinch, at seasons;
but I yield to divine allotment.
Love abounds in my heart, to you all.
Do please to express it affectionately to my own dear father, and all the family,
with my other relatives and friends, not by any means forgetting my dear little children;
they are often near my heart, where the rest of you are borne with me,
from place to place, in my travels.
May the everlasting Shepherd keep you, me, and them, forever,
and may my dear father Scott, so gather inward,
as to feel the evidence and fullness of divine life, before he closes with time,
and launches into awful and endless eternity.

From Dunkirk I wrote dear sister Remember.
I have now only to say to her, that it is my soul`'s fervent desire,
that she may be in all things, strictly faithful,
and consult no more with flesh and blood.
Faithfulness in the little, ensures rule over more,
and leads into the green pastures of life; may her feeding and rest be there,
beside the still waters, is my fervent prayer for her.
Do, dear father Anthony, Remember, and any of the family that can,
let me have a line from your hearts, as soon as may well be; tell me how you are,
how my dear babes are, and my relations and friends, and what else may occur.
From Dunkirk, I enclosed to Remember a line to Jesse Batty`'s wife.
If nothing in regard to any of her religious movements renders it quite unsafe,
do forward it.
I wrote it under some real engagement.
May nothing discourage her progress.

In the spiritual and natural relationship, I am still affectionately yours, etc.

Job Scott

To Daniel Anthony, and Family

London, 5th of 2nd month, 1793.

Dear father, etc.

I have been at London since sixth-day before last; have had a hard cold and cough,
but am now as well as usual.
See no way from hence at present.
My way has been almost wholly shut up, till within a few days;
but begins gradually to open.
I sometimes rejoice in the subjection of my own will, though in a low estate,
and under a weight of as great conflict and pressure as can well be rejoiced in.
Persuaded I am, that One sits at helm, and always guides the bark,
(so far as we resist not,) who knows what is best, and guides wisely;
putting on board but the necessary ballast; and therefore,
though if all movements were as painful as some, life would be almost insupportable;
yet as prosperity and adversity are set against each other,
and no aboundings come but through abasement,
I am helped at tunes to "`rejoice in tribulation,`" and neither in aboundings nor abasement,
am I so entirely swallowed up in my own state, as not to feel sensibly with you,
my dear relations, in your trials and wadings.

May you and I ever trust in the Lord,
and then we shall have a friend whose succours exceed all human aid,
and amply supply the want of earthly treasures, and of friends among the mighty.
Yet let us not imagine we are more overlooked than we really are, among mortals.
I am sure all Christ`'s true disciples, are, so far as they are disciples,
friendly to each other, wherever they are known to each other as such;
and that which makes them cold and jealous, is not in the root of true discipleship.
Oh! what a long and painful wilderness many make for themselves,
by declining a complete burial, and planting with Christ in the likeness of his death.
But, alas! till this is known there never will be
a full arising in the likeness of his resurrection.

I wrote you from Dunkirk, and once before, (via New York,) since I came to London;
to those letters I refer you for some particulars.
The chief of this, I write the day after the date, i. e. 4th, evening.
Yesterday I was at Devonshire-house Monthly Meeting, quite shut up,
unless a little in discipline.
Today rejoiced in the dominion of life over all,
in the Monthly Meeting of Grace-Church-street; at both these houses,
I had before been a silent and uncomplaining pilgrim.
They do their business with great dispatch; and do it very well, as much in an hour,
I think, as sometimes takes us six,
though once in a while they get caught in the striving state a little,
and then they act like us.
There is in London and Westminster, a considerable number of precious Friends,
male and female; the more I dip with them the better I like them and love them.
They are lenient in their feelings towards offenders, yet valiant for the discipline.
Some of them want a little more reducing;
but Master is overturning in them for their good:
and they bid fair to be perhaps more than a little useful.

If you see dear sister and brother Lapham,
please give my dear love to them and their children,
and tell them I hardly gain time to write you.
The same to brother and sister Hazard; brother and sister Spencer;
and Peter and Sarah Hoxsie; my love is to them all, and all theirs,
and livingly to all my own dear children.
Oh! don`'t you forget them, they are yours, as well as mine:
have an eye to them and take a kind notice of them.
If way opens, I hope dear sisters Remember and Alice, will not omit to go and see them,
and cultivate the acquaintance and relationship.
Their dear mother`'s removal, I hope will never lessen their regard for you,
nor yours for them.
The relationship, to me is precious; I feel you near my heart:
and as to the two dear lambs in your immediate keeping,
what shall I say more than I have said?
Watch over them as those that must give account to God,
and let dear sister Remember have all the satisfaction in esteeming little Ruthy her own,
that she could have, had I left home to return no more, and had given her to her:
though I see nothing, but I may yet greet you face to face, on loved Columbia`'s shore:
how soon is not mine now to have scarce any idea of.
If any of my relatives are removed by death, or married, please tell me.
Do write to me, any of you that can, and tell my friends I cease not to love them.
Dear father Scott, has a near place in my heart.
I feel more and more for him; may his dwelling be in the holy life of truth.
In more than natural affection, I remain steadfastly yours.
Farewell.

Job Scott

To Daniel Anthony, and Family

London, 23rd of 2nd month, 1793.

Dear father, etc. etc.

I wrote from Dunkirk, and twice from this great city, before now.
From here, the first went in a ship for New York, the other to Philadelphia;
this I expect will go for Boston.
I am yet detained here, though I see little service in it,
unless to pluck up by the root, again and again, every sprout of my own will,
and make me have no choice as a creature.
My path is in the very depth of extreme abasement.
I even despair of conveying more than a faint idea of it.
I can very rarely rejoice, unless in agony; and scarce know how to hold up my head.
I have had a few good times here; but all seems shut up again,
and I go from meeting to meeting, dumb with silence; and were that all,
it would be very tolerable, for I don`'t covet to be heard.
But, Oh! the inward shutting up, and withholding of almost all consolation from me!
Oh! the darkness that may be felt!
I seem as blind as night, or nearly so.
I see no way at all from this place,
and yet I can scarcely think I am to be here much longer this time,
though I don`'t know but I mast stay here a wonder and a gazing stock.
If so, I wish to bow to it; and to each bitter dispensation.
Perhaps drinking the very dregs is no more than is best for me.

I am very apprehensive that my detention in New England,
has put me by the first right time for Ireland.
That nation is much veiled to me at present, though I believe nothing was ever,
in all my life, more intelligibly, nor more powerfully sounded in the ear of my soul,
than my call to Ireland was, repeatedly day and night,
before I opened my concern to Friends.
And at the same time I was as clearly informed within,
that difficulty would be made about my seasonably getting away, and who would make it,
as almost ever I was beforehand, of any besetment;
and I have rarely ever seen any obstructions more clearly to arise from the toiling,
working will, and wisdom of man.
However, we are all to have our reward according to our works.
There is not the least spice of ill-will, or desire of retaliation alive in my heart,
that I am sensible of.
Be even in the time of my trial, when I was almost sure the detention was wrong,
I did travail inwardly with my God, for their deliverance from that mistaken wisdom.
May they learn by that occasion, to surrender their own wills to divine influence;
when that is the case, the great Lord of the family can soon seal a sense on one mind,
of the duty he enjoins another.
But it was permitted; if for some wise purpose, I know not yet, what it is;
though I thought in the time of it, it could not subject me to more pain,
than might be my necessary portion.

I have, a second time, been much unwell,
with a return and great increase of my cold and cough; +++[+++I]
kept house some days; but am now about again, though unwell.
This air affects my head and lungs much, and so my spirits suffer extreme sinkings,
almost too painful for me to describe.
Bread and water for life, with cheerfulness and good spirits,
would be at least an hundred fold more welcome, if best,
than my present drooping and depressed state.
If dear Thomas Arnold, after all his low spirits, cannot feel a small spark of sympathy,
I don`'t know who to expect it from, out of the one dear family,
and circle of other relatives; to the whole of whom, and other friends,
do give my love as opportunity favors.
Dear William Rotch is still acceptably with me, and may continue some time.
I desire to hear from you if heaven allows it to be so, as soon as well may be.
Do write me, and tell me how you get along, how my dear children are, my own dear father,
etc. etc. Let him know my love increases to him,
and may his increase to the blessed truth, in old age.
Amidst all my pangs and strippings, I now and then feel, and feel beyond all doubt,
that it is in true wisdom I am driven, or drawn, from dear New England.
In a great deal of love, I am yours, etc.,

Job Scott

To Remember Anthony, Providence

London, 2nd month 35th, 1793.

I am painfully journeying; my health is but low, and my spirits, perhaps,
never lower in my life, than much, yea, most of the time here.
When my head is lifted up above all adversity, it is through low plungings;
this was the case yesterday, in three meetings, and a sweet family visit.
Truth reigned over all; as again today, in the morning meeting of ministers and elders.
Yet, alas!
I droop again, but am trying to give thanks in all things.
Shall we murmur or repine at the necessary portion of pain, poverty, and sufferings?
Forbid it, gracious Heaven! and teach us in all to bless, "`nor least for the severe.`"
I am earnestly striving to give up all, bear all, and be and do just what,
and nothing but what, the will divine ordains; and often do I feel a fervent travail,
that this may be also thy constant care and concern.
This world, with all its joys,
can never afford solid peace to one who has so evidently and feelingly seen its emptiness,
as, through the goodness of our God, thou hast often done.
Bitter I know thy cup is often made, but may thou drink it willingly,
and then thy bitter water will be turned into wine.
Be faithful in all things, I beseech thee, even unto death,
and then the crown of life will unfailingly be thine.

Do what thou canst for my dear children;
teach them the fear and reverence of their Creator, and of his inward appearance.
I wish them plain, but much more wish them solidly grounded in the inward work,
not making too much of any outside thing.
I hope thou and +++_______+++ may find a little time to visit them,
and keep up the acquaintance and the love.
Do convey my heartfelt love and good wishes to them, so as they may feel it,
and to my dear father.
I ardently wish his last days may be his best, and that his end may be in peace.
I desire thee, and the rest of you, to do what you can for his comfort.
May you all live in love, and increase in your love to the precious truth.
I much desire our meetings may be held, and business acted in the life.

And may the blessing of Heaven rest on the heads of our dear parents and their children.
Live so as to be a comfort to them in their declining years,
and amid all their probations and discouragements.
I feel them near, very near, even in that relationship,
which is beyond all outward affinity.

I begin to think I may pretty soon leave London,
but don`'t expect to leave my bonds and afflictions, long at a time, any where:
may they become more and more welcome to me, and work the end designed.
I scarce expect any other satisfaction in life henceforward, than what is divine;
all else seems to forsake me: even health I have almost done expecting to enjoy.
I think my frail house is decaying, my nerves weakening,
and my lungs more and more clogging and failing.
But if favored with the divine presence, all will be well.

I am thy fervently affectionate brother,

Job Scott

To Daniel Anthony, and Others

London, 23rd of 3rd month, 1793.

Dear father, mother, etc.,

This is my 5th letter, including one from Dunkirk.
I have not yet got quite away from London, though +++[+++I]
have been out several times, a few days at a time;
so that I have been at very few meetings here for several weeks.
I seem to be getting released from the city by degrees.
Next week is to be Quarterly Meeting here; after that I may go into the country.
My health is greatly mended; my cough almost gone; my spirits, though often very low,
better than I expected when I wrote last; so that I get on rather more cheerfully;
my lungs or breast still a little sore.
My way is, at last, as open, I believe, among Friends and others, as is best,
and I have no distrust of the great Opener`'s sufficiency
and readiness in all future movements.
He doubtless may wisely shut up, and humble renewedly,
and bring into strict dependance on his openings;
and thus his most trying dispensations prove useful.
Dear Samuel Emlen and Sarah Harrison are yet in Ireland,
over which place there is an entire veil as to me at present,
though once seen as in open sunshine.
I can say little of future journeyings; for though the way opens fast enough,
it is little more than as "`day unto day uttereth speech;`" but this speech,
being not in an unknown tongue, is so well understood, as to bring with it,
and leave behind, the sure evidence of divine approbation: what more should be desired?

John Tabor is well, in England.
I have a letter from him.
He thinks we may meet at Yearly Meeting.
Sarah Hoxsie`'s letter I duly received some time past,
and rejoiced in the information that all my dear children were well,
my dear father still recovering, and the rest of you well.
Please forward my love to the dear children, and to her, and her husband and children.
I believe I must omit writing her at present,
though I thank her for her kind information, and much attention, and may, some time,
find time to write her.
Let also the rest of my children be informed of my unabated love,
and wishes that they may do well.
I hope way may open for them to get a little more learning,
and that such of them as get more than they can pay for,
may not finally be felt as burdens to those who assist them in getting it.
My love please mention to father Scott.
I rejoiced his health was better.
May the gracious design of his lengthened life be fully answered,
and he prepared for joys everlasting.
Don`'t forget my dear love to dear sister Lapham and all hers,
brother Hazard and all his, sister Spencer and all hers, and other relations and friends.
Dear William Rotch is yet very acceptably with me, and likely will be some time.
He is highly respected in England.

As I aim to write only what occurs readily, I have at this time little else than facts,
information, love and good wishes; and good wishes for your dear family,
I don`'t know that I ever more sincerely and sensibly felt, than during my last absence.
Heaven`'s best blessings has often been my prayer for you,
and not without some secret confidence that you would be therewith favored; if so,
let us in all other things be content.
The devoted to pursuits after wealth, are almost all of them rendered dwarfish.
He that opens his eyes must see it; and he that feels it rightly, must bewail it.
Scarce any thing is easier than profession, and activity in church affairs;
and where much of this is, there most people think must be, or is, true religion.
And yet how are the hearts of many, many, many of these centred in the earth.

My dear father and mother, if you can lift up your heads above the world,
and unite with divinity,
rejoice that your portion is unspeakably better than gold and silver;
and in this blessed inheritance may all your children and grandchildren be living partakers.
I crave it for me and mine, incomparably more than all earth`'s enjoyments;
and craving it for myself and mine, I can but crave it for you and yours,
for I know no way, in this respect, to divide them.
They are all near to me;
and I trust I shall ever feel nearly interested in their welfare;
and those among you who have known the overturnings of the divine hand,
and seen Jehovah`'s wonders, will, I trust, remain, in some sort, as bone of my bone.
May the Lord, my God and their God, preserve all these in his holy hand forever.
Give me up, I pray you, the Lord`'s time, and to his will and service; and then,
if we meet again, it may be in the enjoyment of that love and fellowship,
which the world knows not.
My heart is full; my eyes not unaffected;
and in this fullness of unfeigned and unstrained affection, I am, as I have been,
sincerely yours, in the several relationships of brother, son, and friend,
and ever-feelingly in regard to my own half dozen, their affectionate father,

Job Scott

To Moses Brown, Providence

London, 3rd month 23rd, 1793.

Dear friend,

I wrote thee from Dunkirk, and whether since, I don`'t remember;
though once or twice I should, but for want of time.

I have received no letter yet but Sarah Hoxsie`'s:
that tells me of the health of children, relations, and friends, the 10th of 1st month,
in which I rejoiced, but could gladly receive fresher accounts.
I hope thou and other friends will not neglect to
write to me as often as conveniently may be.
It will be truly acceptable.

My health, but very low nearly all the time I have been in England,
is lately much mended: my cough nearly gone; but breast still sore.
This I have very little hope, ever to find entirely removed.
It seems firmly seated; and is now of about two year`'s standing.
The fumes of tobacco much relieve the uneasiness,
but the soreness is more or less almost continual.
My prospects were so gloomy when I last (till now) wrote dear father Anthony,
that I did not know but my frame was hastening to dissolution;
but I am now pretty cheerful; am able to get about very comfortably,
and go on to pretty good satisfaction, as to myself;
getting pretty full relief from place to place.
I trust, if faithful, I shall just have spending money; and cash to pay my debts,
though of long standing in this land, and now due with interest upon interest;
after all which I hope to be content to return home, if permitted, with nearly,
if not quite an empty purse,^
footnote:[Possibly some reader may require to be informed that this language is metaphorical.]
where, however I may be received in poverty by my friends, I trust,
if allowed again to join them, I shall rejoice in their endeared society.

Our dear friend William Rotch is very acceptably still with me, and I hope like to be.
He expects his wife and daughters over soon, from Dunkirk:
he sends much love to thee and all thy family.

I think after Quarterly Meeting here next week I may get into the country.
I have been out a little several times, though not yet quite loosed from London.

Dear Samuel Emlen and Sarah Harrison, yet in Ireland.
He not very well; she better than lately.
Not much expected here till Yearly Meeting.

Many occurrences here, some in society and some in the nations,
might afford some entertainment; but the times restrain the freedom of my pen,
and perhaps it is best to be restrained.
However, there is a love and good will, that all earth`'s commotions restrain not,
and which nor absence nor distance can extinguish or abate.
This, dear friend, I often feel towards thee,
and many other dear friends in dear New England.
May the life come so up to dominion over all,
as that no obstruction may remain to a perfect coalition, and cementing,
living fellowship and union among all the members of our Israel.
There is no other rock or foundation on which this
divine fellowship can be abidingly established,
but the life, and where that is abode in,
many little differences in sentiment and appearance are swallowed up by love.
Oh! how true love, when it prevails in and melts the heart, covers a multitude of faults,
or things which may appear as faults, when love is waxed cold.
May earth and all its mighty matters be ever unable to cool the
love of those who have truly loved the Lord Jesus and his disciples.
Mine I think I may safely express to thee, thy wife and children,
and desire the sincere expression of it conveyed to such friends as fall in thy way;
and thou and they may rest assured that at 3,000 miles distance, I sometimes travail for,
if not with you.

May the God and Father of our Lord Jesus Christ preserve my spirit and yours,
in living nearness to himself,
and above the harmful influence of this world and all its wealth, cares, snares,
and amusements, is the sincere desire of thy sincerely affectionate friend,

Job Scott

To Daniel Anthony, and Family

London, 1st of 6th month, 1793.

Dear father, mother, etc.,

Not a line have I received from any of my friends in dear New England since I left it,
but Sarah Hoxsie.
This is a real disappointment, but should be patiently endured;
yet let me pressingly request your future communications may be as often as well may be.
My health, (except extreme nervous depressions,
and the soreness of my breast,) is pretty well;
much better than for divers weeks first in England.
I have been in the country, (though there mostly in towns,) about seven weeks;
attended the annual meetings in Wales, and at Bristol;
sat all the public meetings in silence at both places, except one at that in Wales,
appointed afterwards, and when Friends were departed.
Three out of five I have sat in silence, at this Yearly Meeting in London,
and seven in Bristol.
My way is mostly more or less open among other people, and often greatly so;
but among Friends I am very much in silence,
especially in large collections from divers parts.
At these are many ministers, and many appearances;
altars set up under almost every green tree; the trees seem to flourish,
are full of leaves, many blossoms, and some unripe fruit,
but too little that is ripe and wholesome.
My sufferings at such meetings are inexpressible,
with very little sense of service for me,
unless by the example and influence of deeply travailing silence.

Dear William Rotch has been very acceptably with me,
till a few days before I returned to London to the Yearly Meeting,
which began for ministers, etc. the 18th of 5th month,
and for discipline the 20th. The last sitting of the select meeting was on fourth-day,
the 29th. I have not been very active in discipline,
though my way was more open therein than I expected.
In some things I obtained much solid satisfaction, but more so in the select meeting,
wherein way opened to leave the weight of my deeply bowed spirit upon them,
respecting ministry, and some other things, in a manner to me altogether unexpected;
blessed be the name of the Lord.
Dear Samuel Emlen and Sarah Harrison are very acceptably among us.
John Tabor is here also, and William Rotch`'s wife and daughters.
J+++.+++ Storer, Thomas Colley, etc. etc. attended.
Dear Deborah Darby and Rebecca Young have cleared out for America,
and expect to sail from Liverpool, aiming to reach Philadelphia Yearly Meeting.

I expect to go pretty soon into Ireland, where, most assuredly,
bonds and afflictions will abide me.
I am trying not to complain, but am oft sunk very near below all consolation,
not even that of hope excepted; but as I aim at patience,
(often hard to find or abide in,) I am again made to set up my Ebenezer, and acknowledge,
"`Hitherto the Lord hath helped us.`"
May he, dear relatives, be so leaned upon by you and me,
as to be known our never failing source and succour
through all the storms and seeming ills of life,
and our portion forever.

My dear love salutes my own dear father, if living.
Oh! that his end may be in the sunshine of divine favor;
through full submission to the influence of divine power upon him.
A submission which none ought to delay for a moment.
I desire you may, and trust you will endeavor to make him happy and comfortable;
and may he be resigned and pleasant.
It will do him no good to be fretful, but may, in degree,
prevent the preparation for a peaceful close of life.
The dear children I feel near my heart,
and much desire their careful tuition in the fear of the Lord,
and in reverence of what they feel of his power and spirit upon them.
Let my dear love be carefully communicated to them all,
with a solemn charge that they rebel not against divine light within them,
nor against those who have the care and oversight of them.
If I live to return, I much desire to find them in the innocency of truth.
Omit not my love to all my relations; brothers and sisters Lapham, Hazard, Spencer,
and all theirs; aunts, uncles, and cousins, and all my friends.
I think some of them would do but a friendly part to write me, both relatives and friends.
They should not wait for me to begin.
I have much to attend to, and some letters to write; but, if they wrote,
I believe I should write them.
If they don`'t write, please inform me how they are.

Friends here are growing in plainness, and I hope in more weighty things.
A very large number of young women have their bonnets much lower crowned,
and more decent, than our dear R. and A. and many more in New England.
I think, on the whole, life is rising among Friends in England; but, alas,
the ministry!--the ministry!--my sufferings in spirit are inexpressible,
on account of its low and very unskilful state in this nation; but, perhaps,
least said is soonest mended.
The Yearly Meeting was conducted much more in the true life,
and in christian condescension, than ours in general are.
If a Friend here was to be as tenacious and urgent, and repeat his prospects as often,
and reply and argue, as some among us have done,
his credit would sink low with his brethren.
I was glad the Lord Jesus, and not mere man, was president,
and that his awful presidency kept down the spirit, and will, and wisdom of the creature.
This indeed was the case, more, much more than I expected.
Oh! that dear New England might witness so great a favor.

In the aboundings of true christian, filial, and brotherly affection,
I bid you all a fervent farewell, and rest yours, etc.

Job Scott

To Remember Anthony, Providence

At John Elliott`'s, London, 6th mo.
2nd, 1793.

Dear sister,

I write to thee not only as feeling nearly with thee in thy exercises and tossings,
but as thou hast in some degree a particular oversight,
(if my wish is answered,) of my dear children,
not only the two lambs at our father`'s house, but of all of them,
I wish thee to feel thyself in degree charged with a care respecting them.
Be free and faithful in caution and counsel to them, and, if needful,
to those who have them; though I hope that will be unnecessary.

I have received, as a present from William Tuke, his wife Esther, and son Henry,
the father, mother, and brother of Sarah Grubb, one of her valuable journals.
If I send it, I wish thee to take charge of it till I return.
Read it, and desire the family to read it, particularly our dear brothers and sisters;
and if my deaf old father can read it, it may do him good.
It is a choice book of living experiences, written in the life;
and some parts may answer to thy own trials and experiences, as face to face in a glass.
And may thy faith be strengthened, and faithfulness increased,
that so light may more abound, and no cloud or dimness spread over thee.
I may send with it, Esther Tuke`'s, and the yearly epistle.

Three little girls have written to the children.
If I send their little childish letters, please forward them.
That from Ann Bevan is the production of a dear little girl,
of a greatly beloved family in London.
Her father is John Bevan.
She sends a little book, too, to my dear Sarah.
May it be useful to her tender mind.
The others +++[+++were]
written by two dear little girls in Bristol.

My getting along thou wilt perceive something of
by my letter to our dear parents and their children.
Is it not almost hard that I have never got a line from any one of you?
Have you forgotten me?
Well, I have not forgotten you, and trust I shall not; but do let me hear from you.
Do, dear sister, write me, and encourage father, and some of the rest of the dear family,
to write me as often as may well be.
If you were as long from home you would know how to feel for me,
and when you write give me what information you can.
If you direct to John Elliott, Bartholomew`'s Close, London,
he will forward letters to me in Ireland or elsewhere, as need may be.
If Lydia or Sarah should write a few lines to their little friend Anna Bevan,
they may be enclosed in thy letter to me; for I depend on thy writing,
and don`'t disappoint me.
Give my love to all my relations and friends.
I have written thee several times before.
The letter I now write father, is I think the fifth.
When you write, let me know how many you have received.
I think in a day or two to go for Ireland.

Try to keep up the love and acquaintance among my dear children,
and between them and their father`'s and mother`'s relations.
It is too dear to be lost, or to languish.

Please to forward the letter to Peter Hoxsie for his wife.
It contains one for brother Hazard.
Let that also for brother Lapham be forwarded.
A few particulars more I might mention, but the time allows not of it.
So farewell now and forever.
As heretofore so now, I remain thy truly affectionate brother,

Job Scott

To Moses Brown

London, 6th month 3rd, 1793.

Dear friend,

I am now expecting soon to go for Ireland.
I have wrote father Anthony, and may, perhaps, direct to thy care a book or two,
and some letters for him and the family.
I have never got a line from one friend in New England, but Sarah Hoxsie.
It would be pleasant to hear from home, if I might enjoy such a favor.
I hope thou wilt not fail to write me as often as well may be.
My health is now middling; my sore breast remains, and nervous affections.

Deborah Darby and Rebecca Young are equipped for our continent,
and think to sail from Liverpool, in hope to reach Philadelphia Yearly Meeting.
Some others on this side the water, think of crossing the Atlantic;
but perhaps no movements will be made just yet,
though I think it rather likely one or two may open such a prospect before another year.

We this day hear George Dillwyn and his wife, and Elizabeth Drinker,
were taken and carried back to Philadelphia.
Friends here were in daily expectation of their arrival.
Dear Samuel Emlen and Sarah Harrison are here, to great acceptance.
John Tabor, William Rotch, wife and daughters, are here also.
No very late news from Dunkirk.
J+++.+++ Storer, Thomas Colley, and Elizabeth Gibson, all attended the Yearly Meeting.
The health of all the above mentioned is pretty well for them, respectively.
Dear Samuel glides smoothly on as usual.
Poor Sarah drinks large draughts of wormwood and vinegar.
My own cups are such as wisdom fills; let me not, therefore,
complain of their bitterness,
lest murmuring against necessary potions make still bitterer ones necessary.

The Yearly Meeting here has been large and solid;
much more in truth`'s life and authority than I expected;
for the mournful state of the ministry gave me a
gloomy prospect in regard to the Yearly Meeting.
There is much preaching in England, but too little of gospel.
There are many teachers, but few fathers.
A few sound elders here and there, are preserved;
but too many in that station delight in a sound, crave eagerly to be fed by the ears,
and scarce know how to endure silence: and often,
very often my business has been to starve them,
not being able to utter one word in the life of the gospel;
and may I never add to the number, already too great in this land,
who minister with little or nothing of that holy ability.
A few are yet preserved whose trumpets give a certain sound; yea,
often sound an alarm to +++[+++spiritual]
war; while some do little else than cry peace;
and sometimes not with the strictest propriety.

There are some wise arguers in the Meeting for Sufferings;
hence that meeting is not the most lively:
but in the Yearly Meeting truth`'s holy presidency
kept creaturely wisdom from much undue exertion.
May so precious an experience more and more prevail in the dear land of my nativity.
It is more to be desired than gold or silver.
It is better than the unsubjected efforts of the most brilliant natural endowments.
May we more and more press after it.

My love continues to thee, thy wife, and all thy family; in which I draw to an end,
and am thy steadfast friend,

Job Scott

Extract of a Letter to a Friend

Liverpool, 26th of 6th month, 1793.

I fear too many overrate their own, and a few others`' services,
though at the same time they may underrate those of the many.
Nor let me cry up my own humility, and, if not divinely abased, and kept rightly low,
grow proud under a notion of superior self-nothingness.
Let me tell thee that I most sincerely think and feel,
that all I ever can be instrumentally exertive in,
will be of almost infinitely small amount, or account,
in the final settlement of all things,
otherwise than as submission to divine power may have prepared my own heart,
or rather permitted divine power to prepare it, for good.
I feel daily that I have no good thing but what I receive.
If I am at any time a little rightly humbled, and sensible of my own inability,
unworthiness, and nothingness, as to good of myself, this is all bestowed,
and wrought in me.
I naturally thought myself somebody, and as long as I live, I should, I believe,
be apt to have the same thought, if not, by power above human, daily abased;
and as abasement is well thought of, +++[+++I]
should be liable to plume myself with a notion even of that, if not prevented by grace.
And after all I can know of abasement, growth, and usefulness,
I think all the varied exercises, humblings, and employments,
barely sufficient (if that) to make me know myself, and prepare me,
(may I yet experience it,) for a temple of God, wherein he may be "`all in all.`"

I often admire that I am employed at all; and daily find more than a small unfitness;
yea, something that would both stand and go alone.
Indeed I do not expect to get perfectly and perseveringly rid of it,
very far on this side the grave.
I truly hate it, and if I was able, should lay at it with the sword,
and serve it as David did Goliath, cut off its head, and kill it utterly.
But if I pretend to slay it myself, I thereby add to its life and strength;
and so find I must wait patiently for the sword of the Lord,
to go forth against it from time to time, till, through many deaths, it may finally die.
And then I am sure nothing in me can think much of
any or of all the good that I can have done.
Indeed, it feels to me even now, though in a very imperfect state,
as if it is much more necessary on my own account, than on any other,
that I be thus exercised, employed, and tried from day to day.
I scarce ever act to my own entire approbation.
I think that it is not pride, or that I much desire to appear complete to others.
When others are best pleased, I sometimes feel most inward abhorrence to think that,
hidden from all men, and beyond the vulture`'s ken, lies lurking still,
a part of self unslain, or if once slain, again alive.
I am afflicted at my very heart on account of, and oft constrained to testify against,
self activity in religion;
and yet feel daily a want in myself of being what I would have others be; that is,
all they are "`by the grace of God.`"
I know it is sufficient for them and me;
but my progress is slow indeed in the necessary reduction it is leading to.
Perhaps it is best so.
A gradual attainment may be better borne than a rapid one.

Job Scott

Extract of a Letter to a Friend

Liverpool, 26th of 6th month, 1793.

Let us be willing, not only to be thought to be, but to be known to be fallible.
It is good for self to be of no reputation, though, perhaps,
it is as hard a thing to learn to be willing, rightly willing, to have it so,
as any lesson of self-denial; and I believe few ever attained to it,
without many humblings, not only within themselves, but in the sight of others: and,
even after the wound has been a deadly one for a season,
I believe it has too often been the case,
that that which has thus received "`a wound by the sword,`" has again lived.
Oh! we need a great deal of mortification and hewing,
to fit us for any place of abiding use in the building.
I can see clearly that Christ must reign in us, till he puts down all enemies, yea,
all rule and authority but his own,
bringing every principality and power into entire subjection to him,
before he can render up the kingdom to the Father, and God become all in all.
But it is one thing to see it, and another to experience it done.
I am glad to see it, and am aiming to be so much nothing in myself, and all that I am,
by divine influence, as to experience it effectually done in me, and for me.

And, dear friend, if I wish thee well, I must wish it done in and for thee.
Thou wishest it for thyself;
then let death pass upon all that moves or acts independently, or adds to the word.
This is not written because I see thee in more need of caution than others,
but because I want thee to be perfect and entire, wanting nothing.
Not as if I saw thee so near this state,
as to think a little kind hint from me would soon set thee right.
No, my loved friend, many deaths will be necessary for both thee and me,
before we arrive to "`the measure of the stature and fullness of Christ.`"
In this state, I believe nothing will be omitted,
that life moves in us towards the performance of, nor any thing moved in without life.
Yea, I believe, many things will be felt, and found to be in the motion of life,
and sufficiently so too, under very gentle pressure;
yet the Shepherd`'s voice being known, his word steadfastly believed in,
and he faithfully followed, without any attempting to climb up, or get forward,
either without, or further or faster, than he is lifted up in us, and draws us,
we shall be safely kept, and know him to increase in stature in us,
and in favor with both God and man.

And in this safe, lowly, watchful way, we shall not go on without him, nor lose him,
and leave him behind in the crowd; as some have done,
even soon after their setting out with him, and intending carefully to keep him company;
but as he maketh not haste, we must go his pace, or leave him.
Some leave him behind, and outrun him;
some grow offended with the gradual opening of his doctrine, and,
instead of abiding with him, or outrunning him, go "`back and walk no more with him.`"
But let us stick by him, and follow him through all:
he still has the "`words of eternal life.`"

Job Scott
