== Chapter VI

[.letter-heading]
To Daniel Anthony, etc.

[.signed-section-context-open]
Liverpool, 3rd of 7th month, 1793.

[.salutation]
Dear parents, and all,

I am now at this dark, dark, dark place.
Have been here about a week, (wind bound,) waiting a passage to Ireland;
unwell most of the time, but about.
Have been at three meetings here in course; yet scarce any satisfaction,
and durst not appoint a meeting without better authority than I`'ve yet found; indeed,
don`'t expect I shall at all.
I go into a few families, and but a few; but scarce a dawn of light appears.
It is not all, I think, owing to place, but a dispensation to me.
However, I feel pretty patient under it, and think it not very hard to fast,
if life depends on it.
And why should we have so much will, and choice of, or about, our fare?
He who provides, does it wisely, and best.
And should we not correct a child for complaining
of the best provision we could make for him?
And what is all the provision we can make for ours, to what he makes for his?
If there is food in his house, delicious and nourishing, and we have at seasons,
and always when best, and in best proportion, tasted of it,
why murmur at a preparation for better relish (when
before long it may again be supplied) effecting now,
through the fast?
But if it even were so that the house could not afford, and never had afforded any real,
solid, and sustaining bread; then why complain at the want of what is not to be had?
But is not present hunger, and extreme desire of what often has been enjoyed,
and is now withheld, strong evidence that something is, for which we pant?
Had all as yet enjoyed been vain, why now so craving for its weak return?
why now so restless for a thing of nought?
But since it is real, and been oft enjoyed, and often intermitted to increase the joy,
let patience, during intermission, have its perfect work.
Not only duty this requires, but __present peace,__
and quite intolerable might that fast become, if patience quite should fail,
which in her blest society may well be borne.

I think I write but what I know, and speak of what I feel: for even now,
it is but by faith I live, through patience`'s aid, and scarce at all,
if in the least degree, by sight, or taste, or smell.
I recollect, it is true, the past, and in that recollection +++[+++I]
find repose or hope, and never yet till now, though often tried with fasting, stripping,
tears, having been quite abandoned, famished, or forgot, how can I doubt?
how can I cast away my hope?
how can I disbelieve?
Why should the best of friends, the Guardian sure,
stand by me faithful through all former straits, and in the seventh,
or seven hundredth trouble, fail?
Oh! no: most sure, he will not fail, nor less evince himself our Alpha,
than he`'s already our Omega been.

Stand fast, therefore, my soul,--my dearest friends stand fast,
and firm reliance still maintain on him who cannot, surely cannot fail,
from first to last, a single soul that to him cleaves.
He hears the ravens cry, nor hears their cry in vain;
a sparrow can`'t unnoticed by him fall.
Then surely his holy hand will screen from harm his chosen, who him choose,
and him their best portion make.
These must and will be safe, whether the fig-tree bloom, or fruit adorn the vine;
whether the flock supply the fold, or herd renew the stall, these will be safe;
and when refreshment comes again,--again it surely will come,
from him whose presence only can refresh the soul,--they`'ll sing!
They`'ll tune their harp and sing!
They`'ll in the Lord rejoice, and in the God of their salvation joy.
This is my faith, my firm unshaken faith,
even now when nought but faith and patience string my bow.
What then, when light again shall shine, love flow, and strength divine prevail,
can prove too hard?
But hush!--enough!--forbear!
A word of love express to nearest friends, and all dear babes included,
(may they love the light, and learn its law,) and bidding all farewell,
wind up the scroll.

[.signed-section-signature]
Job Scott

[.letter-heading]
To Martha Routh, Manchester, England

[.signed-section-context-open]
Dublin, 10th of 7th month, 1793.

[.salutation]
My dear friend,

We are safe arrived, after a voyage of near a week.
Our outward trials, contrary winds, sea-sickness, disagreeable company, etc.,
were considerable; but were mere trifles, compared to my inward trials.
Never, perhaps, was I more reduced and empty; indeed I had scarce a grain of true faith,
and my going to Ireland, looked and felt like attempting to beat the air;
though many a lively view had I heretofore had of that place.
I am now there.
But, alas.
I feel neither bow nor battle-axe nor any weapon of war; nor yet the watering-pot.
Canst thou feel for me?
But why should I expect any to feel for me?
I must bear my own burdens; and doubtless if I bear them rightly they will be good for me.
I have received very comfortable accounts from home, as late as 12th of 5th month.
This is "`as cold water to a thirsty soul.`"
All my dear children and near relations were comfortably well.

My dear little Ruthy says, "`Father is gone on the great waters, but he`'ll come again,
when I grow a great girl.`"
Thou see my dear friend how I amuse thee with trifles.
Trifles sometimes, and in some states we are in, are pleasing to ourselves,
and we don`'t know but they may please others.
But, I believe, thou hast exercises, too serious to admit of many trifles.
And whether thou feelest with me in mine, or not, I do feel with thee in thine.
However, I trust if thou standest still, not desiring to run, or stay,
thou wilt see the salvation of God; the sea will be divided,
and a firm foundation will appear.
Oh! that it my be steadfastly kept upon!
If thy dippings are increased and light withheld, marvel not at it; be still, be patient,
and wait; light will again shine.
I believe if we were not often stripped, and clodded too,
we should not long remain enough dependent on divine aid,
and the renewed shinings of holy light.

Oh! it takes a great deal to keep out self, and all its unauthorised activity.
I pray daily to be kept willingly in true nothingness and abasement.
I pray that it may be the case with all my brethren and sisters.
I trust thou often feels the same prayer in thy heart.
And as we here abide, in perfect stillness, as to all the motions of self,
and willing to suffer and do all that is required,
he who is the great Former of all things will make of us that which he pleases.
This thou know well enough, then why should I tell thee of it?
Why, because I feel thee near, travail with thee, and write just what I have to write.
I don`'t know yet how I may move; indeed it seems as if I could not move at all:
but if I bow rightly all will be well.

My love to thy husband, and friends in Manchester,
and to dear Deborah Darby and Rebecca Young.
Does not my spirit go with them?
I think it does.
But may the Lord go with them, preserve them, and cover their heads in the day of battle.

[.signed-section-closing]
In the fullness of heartfelt affection, I am thy friend,

[.signed-section-signature]
Job Scott

[.letter-heading]
To Daniel Anthony, etc.

[.signed-section-context-open]
Dublin, 30th of 7th month, 1793.

[.salutation]
Dear father, etc.

I am just returned from about a two weeks`' journey, here in Ireland;
and expect in a day or two to set off again for the north of this nation.
Have been mostly pretty well, since I came to Ireland,
with the exception of a few days`' pretty severe illness.
Friends are very kind and attentive,
and I have a prospect of very agreeable company (not public).
Perhaps by the Half-year`'s Meeting to be held here, the beginning of 11th month,
I may be near ready to leave Ireland; whether directly for England,
or by way of Scotland, I don`'t yet know.

Thy letter of 6th and 12th of 5th month, with dear sister Remember`'s,
were more welcome than many other welcome things; more, I believe,
than you will readily be aware of.
I got them on my first landing in this city, the 9th of this month, very low in mind,
indeed.
I felt as if it was utterly in vain for me to attempt visiting the meetings;
and yet I did not feel as if I durst attempt the
rolling waves in an escape for dear New England,
though I thought of it.
The letters were just at that juncture, I suppose, much more sustainingly felt,
than they might have been in some other state of mind;
and almost made amends for the long want of information from you and the dear children:
though even now I have mentioned this, I scarce like to let it go,
lest it encourage you to delay writing, which I much desire you may not do,
for truly suspense in regard to the state and welfare of the nearest friends in life,
is painful.

I was pleased to hear from so many of them, besides those under the _one_ old roof;
and request that in the next letters,
(may it not be long first,) I may have a like extensive information;
for I wish to hear from as many relations and friends, as I well can.
I have not much to write you now: this letter is just to acknowledge yours;
and to tell of my health, and where I am.
Though I really felt when I got to Ireland,
as if I should certainly be more shut up in this land,
than I had ever been any where before, or at least get on with greater difficulty,
yet blessed be the alone sure Helper, my way has been very open, and I get much relief,
though now for two or three meetings,
it has been hard "`getting the hatches up;`" and scarce attainable to much satisfaction.
So that if abasement is good, I still have, and seem likely to have my portion of it.
Oh! how altogether unable to go alone, or relieve my own soul!
Well, it is all for the best.
I don`'t wish at all to be independent.
I wish to be more and more patient, and quietly to wait.
The end of the whole race will before long arrive,
and then the past pains and difficulties will be little regarded.
May you all, dearly beloved, hold on in faith and patience;
and believe yourselves as well off as the thousands who
are daily suffering more or less loss of the best birthright,
through the love and enjoyment of worldly things, a mess of pottage.

As some of you may have written more than once,
it may be right to inform that I have received only what bears date 6th and 12th,
and Remember`'s the 8th of 5th month, all in one.
I was glad to hear of dear father Scott`'s recovered health,
and wish him health in every sense of the word.
When I think of him he feels increasingly near to me;
may his stay in this troublesome world,
be continued till his soul may be prepared for a mansion of eternal blessedness.
I doubt not your care and kindness towards him;
and acknowledge it as a kindness to me also, for I much wish his comfort every way;
and do desire he may be duly sensible of the kindness of
our great Creator in continuing him so long in life,
and raising him so many times from a very low and alarming state of health.
Surely, if he sees and feels it rightly,
he must view it as designed to give him full time to prepare for death;
which I hope he will carefully attend to.
Oh! may he be aware of the evil surmises,
and insinuations of such as make him believe they are his friends,
but whom I know to be his enemies, and to be governed by an evil disposition.
May the Lord Almighty open the dear old man`'s eyes to see them as they are,
and to shun their poison, however gilt over, and alluringly presented.
It has already retarded, yea, greatly retarded his progress in the best things.
Give my dear love to him, and tell him,
I most sincerely wish him all health and happiness, here and hereafter, forever.
Salute me, to all my dear relations and friends.
I cannot write to any of them now,
but begin to think it time to get a line from some of them.

I am glad my dear brothers have got well through the smallpox,
seeing they took it upon them;
though I am more and more convinced of the inutility of inoculation.
Some of my own sentiments are confirmed by those of the great Doctor Fothergill,
and divers European physicians now living, who believe if inoculation was quite dropped,
the small-pox would probably soon cease entirely in these nations.
Joy to Levi and his Rispah: I hope it is all well, I feel no objection at all to it.
I hope I don`'t overrate my dear William Rotch, nay, I _believe_ I do not.
I left him in London with his wife and daughters,
but I sent him a copy of thy salutation and remarks.
I am pleased thou sometimes rememberest the precious seasons of communication, unity,
and similarity of sentiment; seasons still precious to my soul, and still endearing,
and I trust will remain lastingly so; yea, if no evil genius intrude,
as lasting as life in the body.

Success to Doctor T. G.; I heartily wish him success in every good thing,
especially in the increase of true religious experience and stability.
I wrote from Liverpool about the 26th of last month: has that letter,
or those letters arrived, or any from Dunkirk?
I congratulate dear sister Ruth on her fine acquisition.
You know I don`'t think much of names; (many are called by the great name,
that have little but a name;) but I am very free the dear boy should bear my poor name:
I think it shows, at least, I am remembered among those I wish a place with.
Most affectionately remember me to all my dear children, and all those who have them.
I gladly hear dear Lydia has been so much at school,
and that dear little James and Ruthy learn their books.
Tell them their father hopes to come again before Ruthy grows a great girl,
though he desires it may not be before she is a good one.
I am limited for time,
or I might particularly acknowledge dear sister Remember`'s very acceptable letter.
May she keep the word of patience through all her trials;
but the only sure way to be kept in patience, is to observe a strict faithfulness.
I wrote about the beginning of 6th month, and sent [.book-title]#Sarah Grubb`'s Journal,# etc.
Have they arrived?
If they have, may dear Remember, and all the family,
improve by the many precious observations therein contained.
If dear father Scott can see to read, I think he will like to read the Journal.

[verse]
____
May he who bore me o`'er the main,
And still preserves my life;
In faith and hope your souls sustain,
Till vict`'ry ends the strife.
____

In the unfeigned love of the everlasting gospel, I bid you all farewell,
and am in nature`'s, and the bands of grace, yours, etc.

[.signed-section-signature]
Job Scott

[.letter-heading]
To George Churchman, Nottingham, America

[.signed-section-context-open]
Dublin, 31st of 7th month, 1793.

[.salutation]
Dear friend,

When I first landed here the 9th inst.,
I received thy acceptable letter of 4th month 29th. Since
then I have been about a two weeks`' journey southward,
and returned here the day before yesterday.
Tomorrow I expect to go for the north; and may probably be ready to leave Ireland,
soon after the Half-year`'s Meeting in the 11th month.
A few days of considerable illness excepted, I have been mostly,
since I came into this nation, in a tolerable good state of health.
When I first landed, and during the whole passage from Liverpool,
(which was tedious and lasted near a week,) I felt as if it would be utterly
in vain for me to attempt visiting or appointing any meetings.
I had found it hard to get forward with much relief to my own mind, in England;
much more so, than in your country, or the southern states of dear North America.
But I felt, during this trying, baptizing passage, and increasingly so on landing here,
as if all was over; and that if I attempted any movements here,
I should not only find great difficulty, but impossibility in the way.
Though "`Ireland!
Ireland! the Lord thy God hath service for thee in Ireland,`"
had rung day and night in the ear of my soul,
for some time before I opened my concern to my dear friends at home.
Alas! all sense of such feeling language and impressions, was wholly removed from me,
as soon as, and for some time before, I arrived at the land,
thus livingly pointed out to me.
But my way has, through divine assistance, been pretty open,
and most of the meetings I have yet had,
have afforded much solid satisfaction to my mind;
though I have generally to begin in a low spring,
and lay very low to keep in it as I move along, or I should find no relief at all.
Indeed, it is almost beyond my attainment to keep steadily down to so low a spring,
in such a manner, as to witness the waters to rise and flow over all.

But, blessed be the Helper of Israel, this has sometimes been the case,
in a very soul-satiating manner.
After which I have to go down again into stripping, and the total loss of all things.
I have no idea that my visit here, or in any part of Europe,
will amount to much more than the ease of my own mind.
Indeed,
though in some former travels I have been helped and favored beyond my previous expectation,
I believe that few traces have been ever, any where, left behind me.
I have no desire to set up any monuments, to proclaim after me,
that Job Scott has been here.
And I think Providence has so ordered it that none has been set up.
I do not know that I should do well to judge, but I have at least feared,
that some who have travelled, have desired to leave monuments of remembrance behind them,
and have rather aimed, and striven to do some great things.
Well, let me not vainly prefer myself, because I think this is not my case.
I ought to be humble; but if I go to thinking I am so, I may be proud even of that.
I confess, I am convinced, that I have no true humility, but what is, as it were,
daily beat into me.
And yet I have nothing at all in me, or belonging to me, but what, rightly viewed,
must tend to humble me.

I never was more out of conceit of myself than latterly.
I marvel that I am at all employed in the great work;
and it often seems as if the design of it must be mainly, my own thorough reduction,
and preparation for bliss.
And yet after all is done for me, I feel myself, miserable, blind, and naked.
It is true, my horn is often filled with oil, and poured out upon others;
but it seems soon to run off from them, and I am left totally destitute and empty,
and can scarcely endure, with becoming patience, my fullness of inner anguish,
and feelings as of total desertion.
I try to be patient; and I remember many former deliverances;
but I find all that won`'t do, till patience is wrought in me,
and I feel myself dependent for it upon superior assistance.

Oh! it is a tried path!
I feel at every nerve, and seem almost "`tremblingly alive all over.`"
But all is well that is not rendered otherwise by human interposition.
Pray for me that I may bear the burden and heat of the day, and flinch not till, nor at,
the end.

Thy letter, with one from home full of good news, and several from England,
received at the same time, were as cordials to my very drooping spirits.
But such cordials are soon spent, and the spirits sink again.
Perhaps there is no other way, but to pass through much of these sinkings.
Some will say, "`Bear up.`"
Alas!
I can do but little at bearing up, and find I must be borne up,
or sink below all consolation.

Friends in Ireland and England are very kind and attentive;
and yet I cannot forget my dear friends in America.
Please to mention my love to such of them as thou see, and thinkest proper to name me to;
and in a special manner to all the dear children.
"`May they more and more choose the Lord for their portion,
and renounce everything that would hinder their progress towards the heavenly Canaan.`"

My service, if any, is very principally among those not of our society.
I seem as if I could do little or nothing for the
good of our poor (shall I say) decayed Zion:
though I hope things are rather reviving in some places.

[.signed-section-signature]
Job Scott

[.letter-heading]
Extract of a Letter to a Friend

[.signed-section-context-open]
Near Charlemont, 8th mo. 23rd, 1793.

The longer I live, the meaner I think of human activity,
and the more certain I am it is to be,
and will be baffled and confounded in all its mighty movements in religious things,
except as under divine influence.
And it is not much matter how many mortifying things we meet with;
the sooner we are completely dead and buried,
the sooner we shall rise in newness of life.
My business seems much like taking down old, ill-built, dirty, decayed,
and dangerous buildings; which assuredly must be taken down and removed,
that "`that alone which cannot be shaken may remain.`"
And strong are my desires that the knowledge of this abiding substance may greatly increase,
both among us and others; and I firmly believe it will,
as old Babylon comes to be shaken and sunk as a millstone, to rise no more:
which great good work I trust he who is omnipotent, is arising to effect in the earth.
Oh! that we as a people, were prepared to receive the doves at our windows,
when they grow weary, and find no true rest for the sole of the foot,
among the many waters on which the whore sitteth,
and hence become concerned to flee to Zion`'s ark for safety.

[.letter-heading]
Extract of a Letter to a Friend

[.signed-section-context-open]
Near Charlemont, 8th mo. 24th, 1793.

If my little experience at all enables me to judge,
there is never any good obtained by unfaithfulness, delay,
and disputing the ground by inches;
unless when that foolish withholding brings us indirectly,
and that through a double heated furnace, to a more perfect surrender at last.
The divine will is always good for us.
Nothing can be required too hard; nor which if given up to,
will ever fail to work good to our souls.
I think I am not left to guess this, but that I do livingly know it.
And, Oh! that all whom I love, may escape, shall I say, that bed of hell,
which unfaithfulness has sometimes plunged my poor soul into.

[.signed-section-signature]
Job Scott

[.letter-heading]
To Richard and Martha Routh, Manchester

[.signed-section-context-open]
Charlemont, Ireland, 29th of 8th month, 1793.

[.salutation]
My dear friends Richard and Martha Routh,

I received, in due season,
your very acceptable communications of 14th and 18th of 5th month;
but my constant travelling and attendance of meetings, (in which I have,
for some time past, had much more solid satisfaction,
than I at all expected,) have prevented my acknowledging
the satisfaction which your said letters afforded me.
I have nearly finished my visit in this northern part of Ireland,
and expect after the Quarterly Meeting, now just at hand, to proceed southward.
My health is on the whole, but middling;
yet such as to allow me pretty constantly to continue my peregrinations,
and arduous exercises.
I often remember you with sincerest affection,
and wish that you and I may ever be found in our proper places and services.
And as we cannot hasten right times, so let us not omit them, lest they return not again;
and so we miss the reward of faithful improvement.
I don`'t say this from any evidence that any thing suffers,
but from a desire that nothing may, improperly.

I thank thee, (if that word may be used,) dear Martha, for dear William Rotch`'s letter.
I love him dearly; rejoice with him, in the good accounts he receives,
and feel with him in his painful expectations.
But let us steadfastly believe "`all things shall work together
for good,`" to those who rely on Divine All-sufficiency.
Thou expresses a hope that we shall meet again.
I cordially unite with thee in that hope; but must submit all to divine disposal.
I rejoice in the fellowship already enjoyed,
and much desire that my abiding may be so under the divine, preserving influence,
that wherever we meet, be it in Europe, or in dear America,
the cementing influence of the same precious fellowship,
may be graciously and rejoicingly continued.

I feel that I am but a poor, frail worm of the dust, as it were,
and yet have abundant cause to bow low in thankful acknowledgment
of that unreserved fullness of the heavenly treasure,
which is again and again, to my humbling admiration, vouchsafed to me,
even in this poor earthen vessel.
The pangs and the perils attendant on this painful warfare,
I know thou art familiarly acquainted with, so I need not much enlarge about them.
And yet, if thou knew nothing of them,
it might be less safe to tell thee that "`bonds and afflictions abide me.`"
But, after all, I have no right to complain.
The Lord my God hath dealt, and still deals bountifully with me,
though he often proves my soul as at Massah, and strives with me, all for good,
yet through many painful plungings, as at the waters of Meribah.
But no matter how many trials and provings,
so that through all he continues still gloriously to arise,
he and the ark of his strength.

Low lies the life in these cold, northern climes;
and truth has too much fallen in the streets of our poor faded society.
Long has the call been continued to them "`to return.`"
Is it strange then, that the feet of the messengers are turned to the highways and hedges?
My little services lie mostly among other societies; amongst whom is much the most,
both of enlargement and substantial relief to my tribulated soul.
Blindness has happened to Israel, at least in part:
and is it till the fullness of the Gentiles shall come in?
Or will others be raised up to take the crown?
I sometimes think many that are first, shall be last, and many last, first.

Among Friends, I often feel a stupid, lifeless silence, prevail over all;
as dead a form as any in the land;
a death which I sometimes don`'t rise superior to the oppression of,
through a whole meeting.
But amongst others, I mostly witness the glorious liberty of the sons of God;
though my work among them is, pulling down the old buildings, overthrowing altars,
cutting down groves, and denouncing judgments and downfall to old Babylon and antichrist,
now sitting in the temple.
_They_ generally hear with an attention which is almost expressive of assent,
whilst our own members hearken, as to matter very suitable to others,
but which _they_ have little or no concern in; being, in their own estimation,
far advanced beyond so lifeless, and so formal a state!
Alas! alas!
I know not where to go to find greater formalists, than many among ourselves.
Indeed, I think sometimes, total stagnation has taken place with many.
But enough of this doleful--and let me look well to myself.

In more love than I can in words express, dear friends, to you both, I conclude,
and am your friend,

[.signed-section-signature]
Job Scott

[.letter-heading]
To William. R., Liverpool

[.signed-section-context-open]
Grange, near Charlemont, 8th month 31st, 1793.

[.salutation]
My dear friend,

I have lately written to +++_______+++, as well as once before, some time past,
in both which I mentioned thee,
and perhaps expressed something of my travail of spirit on thy account;
but still my mind continues so much engaged about thee,
that I am inclined to address thee particularly.

Thy profession (which I trust is real) is that of
standing open to the discoveries of truth,
in whatever way they may be made.
If my concern and communications in no degree assist thee,
in regard to any such discoveries, they may at least tend to my own relief of mind,
and I think I shall run little risk of giving offense to
such a man as thou professest and appearest to be.
Dost thou seriously doubt the living sensible influences, openings,
and manifestations of divine truth, to and upon the minds of men?
Dost thou doubt whether there is, or may be, livingly and evidently felt,
a restraining and constraining operation of divine power,
which depends not wholly on any rational deductions or conclusions in the mind?
Are we in the hand of God?
Do we feel its immediate grasp?
Would it form us just according to the divine will,
and prepare us to enjoy God as our supreme consolation,
if we submitted wholly to its pressure or influence?

To me this is as evidently, and, as far as I have submitted, as experimentally the case,
as any natural thing is evident and experimental.
I know it so well, and certainly, to be so,
that I am often dipped into deep and living concern and desire,
that others may be so redeemed from hindering reasonings,
as to come clearly and heartily to believe and know it for themselves.
Till a man does believe it,
I believe there is great danger of his doing violence
to the very seed of the everlasting kingdom;
for until this seed takes root, and obtains some growth,
it is often the least of all seeds in the garden of the heart, and therefore,
by too many, despised or overlooked, or pretended not to be seen, felt, or discovered.
It is too small, low, and common, to be readily acknowledged as the pearl of great price,
by the great masters of reason.
"`Have any of the scribes believed on him?`"
etc. "`He came to his own, and his own received him not.`"
The Jews knew him not, though professing to wait for him,
and expecting his coming about that time.
He came little, mean, and low, and seemed to them as a very common and ordinary man,
as to appearance, parentage, and connections.
His brethren were with them, and what could be expected from him!
And I tell thee, my dear friend, the very _power_ and _principle_ by which he,
mean as he seemed, wrought all his mighty works, and overcame all the motions of sin,
is in _thee,_ and all mankind.
Had he not worked with it, and in it, he had never wrought those works,
nor bruised the serpent`'s head, nor died unto sin.
And unless thou workest with, and in it, thy salvation will never be wrought out.

Oh! the excellency of faith!
It was through living, feeling faith in this holy principle in the heart,
that the holy ancients wrought righteousness.
All the righteousness which pleases God, profits the soul,
or is the righteousness of faith,
is in the spring and virtue of this precious word near in the heart.
This is the word of faith, which the apostles preached, endeavoring to bring people,
beyond the knowledge of Christ after the flesh, to the revelation of him __in them,__
the hope of glory;
and this they labored to effect by turning them from darkness in themselves,
to the light in themselves,
as the alone way of turning them effectually from the power of Satan,
bearing rule in them, to the power of God in them, that _that_ might come to bear rule.
And were it not for the light and power of God in man,
I think he would be likely to remain ever unable to reason rightly about divine things.
Nothing would be divine in his experience, and religion, if professed,
would be no better than a dream.
And even as it is, with the very hand and power of God pressingly upon him,
he still reasons very perversely, and even denies his feeling the power of God;
says it is something else he feels, or that he feels it no other than reason.
I suppose God knows all things, and is never mistaken; man reasons, errs,
and mistakes too, near continually.
But I am firm in the faith,
that he who keeps closely to what he feels of the power of God, submits wholly to it,
and resigns his human faculty of reason to its rectification,
will be conformed to all the will of God respecting him; whether he is able,
as a rational creature, to demonstrate the truth of every proposition in Euclid,
or unable to comprehend the simplest among them.

God is doubtless _one_ in all things,
and I say not that his _operation_ is not one in all as to _himself;_
but whether it be so or not,
we see his operation produces effects and things in great variety;
and though he fills all things,
all are not in the same manner and degree susceptible of his power,
and sensible of his presence.
Man he has made peculiarly the habitable parts of his earth;
peculiarly are his delights with the sons of men; but he designed us for law, government,
discipline, self-denial, and a daily cross.
All this we could not be subject to, that I know of,
if something in our nature was not prone or inclined to actions, or indulgences,
which were to be refrained from.
Hence the strife between the human and the will divine.
The hand and power of God immediately opposes those designs, actions, and indulgences;
forbids them; condemns the creature for them; and operates as light,
giving the mind to behold their inconsistency with the law of God and peace of the soul.
Let a man turn every way to get ease under this operation, and till he yields to it,
he shall be often by it, during his day of gracious visitation, "`nobly pained.`"
Go where he will, his accuser goes with him, not daubing with untempered mortar,
and crying peace,
(as what he calls reason too often does,) but setting his sins in order before him,
and urging and pressing upon him, in a very feeling manner, to yield up,
and become as unresisting clay in the potter`'s hands.

O dear William!
I believe, as firmly as I believe I live, that thou before this day,
would much more eminently than has yet been thy experience,
have come forth as tried gold, and been formed as a vessel of honor and use,
in the Lord`'s house, made of beaten gold,
and holding the wine of the heavenly kingdom to thy own unspeakable consolation;
had thou in early life, and steadily on till this day, turned to, believed in,
and fully submitted to the power of God upon thee, which thou hast, from day to day,
felt the presence of.
Indeed, I can scarce forbear to marvel,
that such a man should doubt the divinity of what
he has so long felt livingly striving in him.
The whole scope of the gospel, is __Christ in man.__
His outward appearance, or his coming in that one body, seems to me evidently designed,
to lead men to a living discernment of, and faith in the Emmanuel state, God with man,
and man with God, in the work of salvation.
And it seems to me, that if thy mind had not become puzzled, and darkened by reasonings,
not simply in the openings of light and impressions of divine life,
thou wouldst now very readily (thy feelings being such as
they are) give into and heartily embrace the plain,
clear doctrines of the gospel; Christ inwardly our life, our hope of glory;
God working in man; man working in and with God.
I think thou would clearly see,
that God has determined to hide divine mysteries from all the prying of mere human wisdom,
and reveal them to the babe in man, that is born of the incorruptible seed.

Ah! thou may puzzle, and strive to comprehend, as long as thou canst.
The vulture`'s eye, (though very prying,
and therefore comparable to human wisdom,) shall never see these things.
But keep only thine eye single to divine light in thee,
and thou shalt assuredly experience its blessed increase, even to a fullness of light.
All that need be seen and known of duty and divine things,
shall infallibly be seen and known.
But, Oh! have a care thou overlook it not, by raising thy expectations too high.
It is that little, low thing in thee, which thou shalt finally confess and acknowledge,
is, and all along has been to thee, the very gift, word, spirit, power, and life of God.
I am sure thou know not what it would have done for thee,
nor how powerfully it would have worked in thee, had thou been rightly turned to it.
It wrought mightily in Paul; it works mightily in many now, who keep to it,
and work with it, as the leaven of the kingdom.
It is as possible now, to shut up the kingdom against ourselves,
as it was when Christ accused the Jews of doing it.
And I scarce know a more effectual way of doing it,
than by putting human reason in place of heavenly light and leaven,
and relying upon its dictates, undirected _by_ the _light._

I well know this has too long continued the veil over my mind.
The veil is only done away in Christ, inwardly believed in, the hope of glory.
I know what I say, and moreover know, as well as I know thy face from another man`'s,
that rightly believing thus on him, and hearkening to his teachings,
leads to great and glorious discoveries,
and to a very clear discernment of the states of individuals, and meetings,
entire strangers;
and that altogether independent of the mere exercise of human reason or information; yea,
directly in contradiction to all pre-apprehensions, and to what,
judging as a rational creature,
(except merely in the divine openings,) looks most likely to be the case.
This is certain and repeated experience.
Those who know it not, may doubt it; and so I suppose they did in every age;
yet thought themselves wise, and rejected the counsel of God against themselves.
But their unbelief shakes not at all the faith of those who know it,
as well as they know their right hand from their left.

Well, I have said what I well can at this time, and per this sheet.
It is off hand, with no correction; it is confidently expressed, and,
in point of sentiment, I am undoubtingly persuaded,
what I mean will be found agreeable to truth,
whether it is so worded as to bear a critical examination or not.
This indeed is hard to do;
and perhaps little of the scriptures will be found
proof against each kind of treatment and examination.
I expect rather thy candour than criticism.
I recommend a close and feeling attention, for thy precious soul`'s sake,
to the contents; and with a great deal of pure love to thee, and thy dear wife,
I now conclude, and am very sincerely, thy friend,

[.signed-section-signature]
Job Scott

[.postscript]
====

P+++.+++ S.--And +++[+++I]
would very gladly receive a letter from thee,
with as few or as many remarks on the foregoing as thou pleasest.

====

[.small-break]
'''

[.postscript]
====

__P+++.+++ P. S.__--Animal, rational, and divine operations, all depend on God;
but are three distinct things: the rational and divine,
as distinct as the animal and rational.
Is a snail, because he crawls by power from God, _rational?_
Not a whit more is _reason,_ that faculty of the human mind,
which is a constituent part of a complete and sound man,
and which eminently distinguishes him from a mere animal, __Christ in man.__
But the light that enlightens all men, is Christ.
The things of a man, i. e. rational things, are known by the spirit of a man;
the things of God only by the help of the spirit of God,
as a very distinct thing from man`'s spirit.
"`God revealeth them unto us, by his spirit.`"
The word "`us,`" here comprehends man`'s reason and spirit,
unto which God`'s spirit reveals divine things.
And why is it harder to conceive a three-fold recipiency,
or susceptibility of uncreated power or influence, than a two-fold only?
why any more difficulty in the distinction between simply rational, and properly divine,
than between animal and rational?

====

[.signed-section-signature]
J+++.+++ S.

[.letter-heading]
To a Friend

[.signed-section-context-open]
Near Moat, Ireland, 9th month 27th, 1793.

[.salutation]
Dear +++_______+++,

Yesterday was to me almost one of the darkest days I ever knew,
and I thought as distressful as I could well endure.
The day before, we had a pretty good meeting at Ballimurry, where truth was in dominion.
After meeting we rode to Athlone, where I had expected to have a meeting,
but could not venture to have one appointed, my mind was so low,
and so little light appearing; so we rode on, and came late that evening here.

As after a storm comes a calm, a storm is almost certain to succeed again in turn.
Many ups and downs have I had since coming to Ireland.
Oft in bonds and deaths, and oft delivered and raised.
But all former experience was yesterday quite insufficient to stay my mind.
I strove for patience, but found it was a gift, and not much at my command.
I walked out divers times.
I tried to seek God, and commit my cause to him, but he hid himself in thick darkness,
and seemed to stand aloof to my cry.
I read the Bible and Dell; good doctrine, pure, and spiritual;
but my soul refused to take comfort in it, or rather, all comfort was withheld,
and though I sought it carefully, I found it not.
I was ready to rave, and burst out in loud groans.
I could have cursed my birthday like a true Job,
for I could scarce esteem life or existence a blessing.
I was almost dumb all the day with silence,
and I suppose was a gazing stock to some of the company.

Now +++_______+++, do I complain improperly?
Do I murmur?
I wish not to.
But, perhaps, the best state is that wherein we bear all, and tell no one of our anguish.
I think Samuel Fothergill advised S. Hatton "`not
to pour forth her complaints to any mortal.`"
If this is absolutely necessary, when shall I attain to it?
I wish to give up all, and seek no comfort or relief in any way contrary to divine wisdom.
But I find God`'s people did utter their complaints of old, and sometimes largely too.
Was it their weakness?
Or affords it some consolation to those who come after them in the same painful pilgrimage?
Well, if thou thinkest I complain too extravagantly,
know for certain the half is not told thee.
But after long tossings and violent commotions,
as of all the elements in furious and loud uproar, the waves at length subsided a little,
and at his voice, whom they ever obey, the wind and sea were still.
This was not till in the evening; and even after this till bedtime, and indeed today,
the dispensation of almost total silence continues.
I had a pretty good night`'s rest, and awoke this morning in a state of some real relief.
But through the preceding exercise, I felt as if I was all over bruised,
and every nerve over-stretched and strained.
I ate breakfast, read, and walked.
The sun shines gloriously; the birds sing sweetly; the wind whistles pleasantly;
and all the face of nature is beautiful: but my soul remembers the wormwood and gall,
and seems forbidden to seek or take delight in any of the pleasant things of nature.
Well, let me be weaned to any degree that Wisdom dictates, and have no will,
but that the will divine may be done in all things.

[.signed-section-signature]
Job Scott

[.letter-heading]
To a Friend

[.signed-section-context-open]
Moat, 9th month 28th, 1793.

[.salutation]
Dearly beloved,

I have received several kind messages of love and encouragement from thee,
which I now thankfully acknowledge.
I esteem them, as I think they certainly are,
lively evidences of thy fatherly care and regard towards one of, perhaps,
the most tossed and tried of the flock.
But ought I not to be afraid to complain to thee?
Thy repeated watchword to me is, to keep the word of patience,
and to let patience have its perfect work.
I assure thee I do earnestly endeavor so to do: but dear James Thornton told me,
"`The true patience is a divine succour, a gift, a thing that must be felt,
supporting the mind.`"
And, alas! my feeling so little of it, at times, when I so sincerely desire it,
and so faithfully strive to exercise it,
almost convinces me that I am not to be much sensible of its support, but when,
and in such wise, as that I may feel and acknowledge it is more of God than man.
The dispensation I have been under these two or three last days, has been so tribulating,
that notwithstanding my honest endeavors to bear all patiently,
I have been almost ready to open my mouth, and curse my day.
I strove to think, as at more joyful moments, that life was a blessing,
and to be thankful that __I am;__ but, perverse as it might be,
I could scarcely feel glad that I ever existed,
or forbear wishing I had given up the ghost at the moment of my birth,
and been carried at once to the grave.

Well, my dear friend, I am often fully satisfied, that God never afflicts unnecessarily,
nor lays more upon man than is best.
And seeing these deep and heavy sufferings are repeatedly,
and a good deal towards constantly, laid upon me, and, as it were, fast bound about me,
so that I cannot shake them off,
nor rise much above the sore depression which attends them; may I not,
must I not conclude, a God all wise, and perfect in goodness,
knows I stand in need of them?
Perhaps, without them I should not be, even in that little degree that I now am,
preserved in the line of true humiliation and obedience.
And if I go mourning all my days, and thus witness preservation to the end,
Oh! how much better it will be, than to rejoice now, and in conclusion, mourn and weep.

I have almost a continual quarrel with old Babylon, and her several sorts of priests.
Had one told me, seven years ago, that I should be engaged in such a constant war,
from place to place, with almost all that _men_ deem sacred,
and that I should continue going forth from day to day, with scarce more,
and sometimes scarce so much, as a sling and stone,
I think I should scarcely have believed it;
and perhaps should have turned away back in discouragement.
Sometimes, indeed, I seem helped to bathe my sword in blood,
till the whole host of opposers are made to flee before me; but at other times,
I feel to myself much like fighting upon the retreat,
and the forehead of Goliath remains unpierced, and he seems to me to stalk off,
with erected front, still bidding defiance to the armies of Israel.
I think he will yet come down wonderfully, even in this land,
though I don`'t expect to be here to see much of it.

My health is, on the whole, about middling, though oft a good deal drooping.
It is sometimes, some cause of comfort to me, that thou hast some faith respecting me;
but I have often little or none, respecting myself.
Yet I can at this moment, bless the holy name of Israel`'s God,
that he sometimes gives me faith that seems invincible,
and which I then feel to be his precious gift, and of his own immediate operation,
and not a mere exertion of human confidence.
"`Let me die the death of the righteous,`" etc. is my serious request; and to attain it,
I fervently desire I may be enabled faithfully to live the life of the righteous.
Many deaths it has already cost me, and how many more soever it may require,
I much more ardently desire I may rightly submit to, and endure them, than I now do,
or ever did, desire the increase of gold or silver.
+++_______+++ is my very agreeable and useful companion;
especially useful in giving notice of meetings, in a proper manner, among the people;
and more depends on this than many are aware of.

[.signed-section-signature]
Job Scott

[.letter-heading]
To Moses Brown, Providence, Rhode Island

[.signed-section-context-open]
Dublin, 11th month 7th, 1793.

[.salutation]
My dear friend,

Thy letter of 6th month 9th, though long finding its way, was truly welcome to my heart:
be so kind as to continue letting me hear from thee,
for thy truly sympathizing letter was reviving to my mind.
My wadings and discouragements were then, and had been for some time,
nearly inexpressible, and for aught I know, quite so.
I strove all that in me lay for patience and submission,
but scarce could refrain crying out, being, in my own feelings,
almost ready to open my mouth and regret the day that gave birth to my existence;
but through silence in and out of meetings, and bearing my burden as well as I could,
death at last was swallowed up by victory, and truth reigned marvellously overall.

But, alas! as I descend in order to ascend,
so from the highest ascension I soon descend again, almost into the lowest places.
I find but very short intervals of pleasantness,
and but very rarely much freedom in conversation.
I have had several times, since and before I got thy precious token of remembrance,
of sinking very low; but if little else is for me but bitterness,
I fully believe it is for no other reason than because that is best.
The all-wise Disposer knows what we can bear,
and can make of gall and wormwood a precious balsam for the soul.
My own will does not like so much of it; but I rejoice, and bless God,
that through the repetition and continuance of deep probation,
that "`own will`" of mine is very evidently dying on the cross.
Planted in the likeness of death, I experience oftener than daily,
and no otherwise than through this, do I arise in the newness of life.
When these things are mentioned, one understands scarce any thing of it,
another a little, another a little more, and so on, as in degrees.
I trust I am not now writing to one who is ignorant,
or but slightly acquainted with conflict and probation.
I note thy own expressions,
of having to "`live by faith,`" and of sufferings in divers respects;
I wish to catch the hint, and not only live more and more,
but be _willing_ to live more and more, by faith, through all sufferings.

I was glad to hear of thy +++_______+++`'s more comfortable state; may sickness and health,
and blessings, and trials of every kind, be rightly improved, and work the end designed.
Sorrow springs not out of the dust; we are in the hands of one who deals wisely with us.
"`In all I bless (says Young) but most for the severe.`"
Indeed, our nature is such, that I suppose the severe, in general,
most effectually prepares us as temples of the living God.
We are designed to be partakers of the divine nature, if Peter saw right,^
footnote:[2 Pet. 1:4]
and to be filled with all the fullness of God, if Paul was not mistaken,^
footnote:[Eph. 3:9]
or I in recollecting him; but this only in proportion as emptied of ourselves, indeed,
put to death in the flesh and quickened in and by the spirit.
This is the alone way of salvation forever: the mystery of godliness being,
through all time, and in each individual,
"`God manifest in the flesh,`" and more and more manifest,
till a fullness of dominion and glory.
This is my prayer for my own soul and for yours.

Thy account of +++_______+++ was truly acceptable: the dear old man has very increasingly,
for a few of the last years of my life, obtained a place in my affections and prayers;
may the Lord Almighty, if he be still in the body,
be graciously pleased more and more to quicken, and make him alive,
in the knowledge and obedience of the ever blessed truth,
before he goes hence to be seen of men no more.
I request thee to make known to him, if living,
my fervent affection and travail of soul for him.

The account of removals was and is mournfully affecting;
that of dear +++_______+++ most of all so; but thy account of his humiliation after separation,
and the hope that he might be able to do more for the honor
of truth than the meeting could do by any testimony,
was rejoicing to my very soul.
The Lord has done great things for him.
He has seen wonders in the deeps; may he never become an utter cast-away,
is my fervent prayer to Israel`'s God.
Present my dear love to him and his, and say to him on my behalf:
let not go the faithful word; let neither heights, depths,
nor any art or address of the grand seducer, separate thee from the love of God,
once so livingly experienced, and prized above thy other chiefest joys.

Ah! dear friend, what are we after all experiences, if we neglect the holy watch,
and keep not low in deep abasement of self.
For me, may I be stripped of all accounted dear by man,
which to the things of time pertain;--may suffering be my portion
till the solemn close;--may nothing ever salute my ear,--my eye
no joyful sight behold;--may pleasant meat be never mine,
nor in the night serene repose, but grief and tossing number all my hours;--rather, yea,
rather far, than Satan`'s arts prevail, to rob me of the boon of life,
to make me slight the precious pearl, let go my hold, or ever turn my back on him,
that`'s done so much for me, or ever desert his glorious cause.
Lord! hold me ever in thy holy hand.
My heart through stripes,
(if stripes are needful to the work,) to thy blessed will incline.
Bend all my stubborn will.
My eye keep open to behold thy way, and pierce mine ear to hear.
Instruct me by thy rod; and in conclusion make me wholly thine.
Then through eternal ages, shall my soul, in deep prostration, celebrate thy praise.
Amen.
Amen.

Had I known how I should have been led to wage almost constant war with Babylon,
and her merchants and merchandize, before I left home,
I don`'t know that I should have been given up to come:
but the divine be done in all things.

I have been at all the meetings of Friends in Ireland, and divers among others,
and was expecting to see England directly after the national meeting here, now just past,
but am like a prisoner in Dublin, and scarce know but I must go back to some places,
(unusual motion for me,) but am waiting to know the Master`'s will,
and when I hear the Shepherd`'s voice I am ready to obey;
at least I don`'t know but I am.

[.signed-section-signature]
Job Scott

[.letter-heading]
To Daniel Anthony, and Family

[.signed-section-context-open]
Dublin, 7th of 11th month, 1793.

[.salutation]
Dear father, etc.

I have just finished a letter to dear Moses Brown, if thou see that,
it may excuse my repeating some things to thee, and if he sees this,
it may supply some additions to him.
Thy very acceptable lines from Newport, time of Yearly Meeting,
and the letter before that, came pretty duly; but as I had,
just before the first arrived, written thee,
(may be from Liverpool,) and very shortly before that from London;
and as I have been very closely engaged, I may have omitted writing thee, now too long.
Dear sister Remember`'s, were also very welcome--two whole ones,
and a piece joined to Sarah Hoxsie`'s, in 8th month.
This is the last account I have had; and then my dear daughter Lydia, was ill of a fever.
I desire to hear if she lived through it; and if so, how her health,
and that of the rest is.

I have just got through a very trying visit to Ireland; +++[+++I have]
been at all the meetings, and thought to go soon for England;
but since the National Half-year`'s Meeting, now just over, I am shut up here;
and don`'t know whether I must go back, or not.
I left and passed through some places, very hastily, to get to said meeting,
and scarce feel easy to leave Ireland; but as I don`'t find strength,
and clearness yet to return, perhaps after a few days, I may get away for England: if so,
it is likely I may spend the winter in the north of England.
My health is but indifferent, and has been so, nearly all the time I have been in Europe;
some pretty low times I have had, in body and mind, sore breast and lungs, etc.

Friends in Ireland are of the kindest sort,
many of them would be most agreeable company to one
who was at liberty to enjoy agreeable company;
but this is seldom my case.
I am mostly under as much probation as I can well live through,
even so that it often requires a good deal of submission
to be rightly thankful for existence;
which during many painful, anxious moments, scarce seems a blessing.
But my heart is often hushed and awed into humble acquiescence with all the divine dispensations;
and then I see and feel it is not in vain that __I am.__
May I ever so abide the turning of the holy hand, as not to _live_ in vain.
Dear Samuel Emlen, pretty well for him, in London, visiting Friends`' families,
in his usual way of freedom.
George Dillwyn and wife well.
Sarah Harrison, very industriously employed; has been through North and South Wales,
and Scotland, since she left Ireland; gets on bravely, and to satisfaction.
Elizabeth Drinker +++[+++is]
in England, well received, and produces sealed commission.
Poor I, have had some precious seasons, now and then,
which demand my reverent acknowledgements, notwithstanding all my abasements.

Thy account of removals from stations in the select meeting, is truly mournful.
I much desire dear +++_______+++ may yet be favored to have his last days his best.
Thy expressions of union and fellowship, beyond what any earthly thing could produce,
were very grateful to my poor soul; I think I can add an hearty amen to them.
May we ever so walk as to experience a blessed increase in that best of all fellowships.
I am trying to take all patiently, and go through all willingly.
Indeed I do go on willingly; but it is as I am driven,
and because I can find no other way of peace.
However, if continued tribulations attend me to the end, it is little to be minded,
if the end be in peace.

Do write me often, and give me such information as thou thinks well to do.
Are all mine and thine well?
Do they do well?
Is there any growth in the truth?
or other alterations?
Is dear father Scott alive?
is he quiet?
has truth laid any deeper hold of him?
I have latterly been anxious for his eternal welfare;
and desire nothing may be omitted for his present comfort.
Let him know my love is not at all diminished towards him; nor my desires for his good.
To dear sister Lapham, her husband and children, present my salutation of endeared love;
as also to all my other relations; and all my dear friends.
If my dear friend Thomas Arnold has no feelings nor sentiments to convey,
I forgive his silence.
I thought some of my friends would have written me, but thyself, sister, Moses Brown,
and Sarah Hoxsie, are all.
Let my dear worthy mother be assured I remember her with feelings of love;
the Lord reward her, for all her kindness to me and mine.
In that which changes not, farewell.
I am thine--I am yours,

[.signed-section-signature]
Job Scott

[.salutation]
Dear sister Remember,

A piece of a letter may pay for a piece, and thine though a piece, was very acceptable;
and don`'t omit any opportunity to do the like again.
I oft remember my dear babes, left in part under thy care;
and hope any attention bestowed on them by thee, and the rest of you,
may be recompensed into your bosoms, with sweetness of true peace.
But don`'t I owe thee for a whole letter, or two?
Well, I am too poor to pay now, and I pray thee have me excused:
be so kind as to write me again, and I hope I shall one day be able to write as of old.
If not, the divine will be done.
But poor as I am, I sincerely wish thy encouragement,
and preservation in the highway of holiness.
Let nothing be able to turn thee aside, nor to relax thy pursuit.
This world scarce affords one true joy out of the life of truth,
and all the bitter cups to be met with in the way of truth,
are better than silver or gold.
My health thou wilt hear of by the foregoing, and also my progress, and state;
so I cannot add much.
Words made or forced, do no good.
I wish to be limited in writing, as well as in speaking.
In conversation I am so, almost to an extreme.
I believe many wonder what it means, in this land;
but how can I talk when I have nothing to say, and when my heart is full of anguish?
No grief for outward things, is equal to the pangs of Zion`'s travelers.
No outward thing is too dear to be parted with for truth;
but a total erasure of all sense of good in the soul, requires great patience to endure.
But let us trust and hope through all.
The day always follows the night.
I never knew it fail; and trust it never will.

_8th._ I am now clear of Dublin, after two meetings today; one very large this evening;
but I now see nothing else likely to do, but going back towards the south of Ireland;
whether as far as Cork, I don`'t know; nor whether I may see Dublin again.
I have got some relief from my late burdens and imprisonment;
but seem still in a tried state about future procedure.
I think to go tomorrow for Ballitore, about 28 Irish miles southward;
and must be dependent on divine aid from day to day.
I beg you will remember me, and not omit to write.
Love to all relations and friends.
I am affectionately thine, and yours, all.

[.signed-section-signature]
Job Scott

[.letter-heading]
Last Letter from Ireland

[.signed-section-context-open]
14th of 11th month, 1793.

[.salutation]
Dearly beloved parents, (all three,) brothers and sisters, relations and friends,

I am now at Ballitore, twenty-eight Irish miles from Dublin,
and I suppose undoubtedly entered five days into the small-pox;
the eruption began yesterday, and is very greatly increased today.
I am very agreeably attended by physicians and the kindest of friends.
I believe this is, on several accounts,
one of the most favorable situations for having this disorder, in the nation,
but my physicians are apprehensive that it will not prove the most favorable kind,
nor perhaps of the most unfavorable.
My distress of body, through extreme difficulty of breathing, etc. has,
for a short space of time,
been almost equal to any thing I can suppose human nature capable of, but,
(it is now half-past nine at night,) this has been a very comfortable day; and just now,
and for several hours past, I have been almost as easy as at any time in my life;
I think certainly never more so in mind.
I feel no kind of alarm; but the issue is certainly very doubtful.
I feel easiest to address you in this manner,
principally that you may know that my mind enjoys a fullness
of that which removes beyond the reach of all sorrow,
but I have some other matters also to mention.

I made my will very directly after the decease of my much beloved wife;
it is now easy to my mind, and I desire it may be faithfully executed.
I have steadily desired my dear father Anthony would lend what advisory aid he well can,
in regard to the government of my dear children, both in temporals and spirituals.
They are placed so that I have been pretty easy,
but I could wish them to get a little more learning
than some of them are at present in the way of;
and although I do not wish much of the world`'s polish,
yet it is at this awful moment my desire,
that they may not be brought up with much rusticity; for this, I believe,
has not very often contributed either to civil or religious usefulness.

There is scarce any thing that makes longer life desirable,
but to finish the field of religious labor,
which I had hitherto mostly thought was not yet done,
especially with regard to digesting my journal and some other writings.
Indeed, it has often felt as if I should probably die in debt to the world,
if I did not even make some considerable additions upon some subjects
that may have been thought a little peculiar to myself,
but which, I still believe, are as strictly in the very life and essence of the gospel,
as I believe any truth whatever; there is not the least scruple in my mind about them.
I trust I as firmly believe in the divinity of Christ, as any man living;
but I have no more belief that there are two divinities, than two Gods.
It is altogether clear to my mind,
that that one divinity actually became the seed of the woman,
and bruised the serpent`'s head, as early as any man ever witnessed redemption from sin,
and is one in the head and all the members, he being like us in all things, except sin.
My only hope of eternal salvation is on this ground;
nor do I believe there has ever been any other possible way of salvation,
but that of a real conception and birth of the divinity in man.

It is not now a time to enlarge;
there are several sketches of this doctrine in my journal,
and several other very unfinished little essays.
On the ocean I wrote over about a quire of paper, which I believe is now in my trunk,
at John Elliott`'s, which I was ever a good deal doubtful whether some parts of it,
not particularly upon these points, were not more in a way of abstruse reasoning,
than might be best for a Friend to publish.
Be that as it may, I am very apprehensive,
that most of my writings are far from properly digested, and some of them, I believe,
might be a good deal better guarded.
Our views of things do not usually open all at once; it is so in the individual,
it is so in the world.
Things have hitherto been gradually evolving,
and it may be consistent with Infinite Wisdom,
that such a progression should always continue.

At the present day, things are considerably ripening, and I have not the least doubt,
that, before a great while, a highway will be opened through kingdoms and nations,
where darkness has long reigned, for the publication of the everlasting gospel,
in its true life and authority; and as what is revealed in the ear,
is in due time to be declared on the house-top, I have little or no doubt,
that the true doctrine of Christ will be much better
understood than has hitherto been generally the case.
I may possibly be restored to contribute my small mite toward it.
In this and all things else, I am not sensible of any wish,
but that the divine will may be done.
I think some parts of my journal abound too much with a repetition of similar exercises,
services, trials, and favors, when on religious visits.
In this respect I have steadily had an intention of making very considerable abridgments;
several other things also, in the journal, require a very careful review.
I have no wish any thing of mine should appear in print,
but from a probability of usefulness.
I have thought a considerable part of the journal might be, in some degree,
useful to some minds; but I submit all to the careful inspection, correction,
and determination of my friends.

It is almost marvelous how my strength of body and
mind holds out to address you in this manner.
I may now just mention, that nothing will be knowingly neglected,
for my comfort of body or mind, that my physicians or friends can afford;
and greater cheerfulness, and even pleasure, in doing all they can,
I have not met with among my nearest relations.
I pray the Lord, in the riches of his grace, to reward them with flowings of his love.
I suppose my love was never in a state of greater enlargement,
or less tinctured with selfishness, to all my relations and friends, the world over.
My desires for my children`'s substantial growth in the truth,
and strict adherence to all its discoveries, to the close of their days,
is by far the principal wish I have for them.
Out of the enjoyment of a good degree of this precious inheritance,
I know of nothing in this world worth living for.
Ye that know it, suffer nothing, I most cordially beseech you,
ever to divert your minds from an increasing and
fervent pursuit after the fullness of it,
even unto the measure of the stature and fullness of Christ.
I once more, and perhaps for the last time, express my living desires,
that my own dear father, (if living,) may know much more of an advancement into,
and progress in this divine life, before he goes hence to be seen of men no more.

It is now eleven, I want rest;
whether I shall be able to add further is to me at present unknown;
and however it may be, in the fullness and almost unlimited flowings of true gospel love,
I am, and trust shall ever remain, in best affection, your sincere relation and friend,

[.signed-section-signature]
Job Scott

[.signed-section-context-open]
15th of the month, half past 2, afternoon.

The disorder is pretty strongly making its progress; I can scarce get any sleep;
my strength fails a little, but I admire at its holding out so well.
The pock on the face is, if not quite, very nearly confluent;
the face considerably swelled; on the body it is pretty distinct.
The physicians speak very encouragingly, I believe in my absence as well as my presence;
but were it not that little or no sense seems given me as to the issue,
one way or the other, I believe from the symptoms as they are,
and from my knowledge of my own constitution,
and the very different climate from America,
I should pretty strongly look out for dissolution,
although my spirits are under little or no depression at all.
Perhaps I never saw a time before, when all things not criminal,
were so nearly alike to me, in point of any disturbance to the mind.
I do not know but that, when awake and capable of contemplation,
I nearly rejoice and give thanks in all.
When I verge a little towards sleep I am all afloat, from the state of my nerves, and,
from the extreme irritation, forced almost immediately,
and with very unpleasant sensations, from beginning repose;
but through all the soul seems deeply anchored in God.

Many and painful have been the probationary exercises of this life to me.
Ah! were there probability of strength, how I could enlarge,
for my heart seems melted within me, in retrospective view; but all the former conflicts,
however grievous in their time, are lighter now than vanity,
except as they are clearly seen to have contributed
largely to the sanctification of the soul;
as they are remembered with awfulness and gratitude before him who has not been wanting,
to preserve through them all; and as they seem likely to introduce, either very shortly,
or before a very long time, to an exceeding and eternal weight of glory.
Some have anxiously wished to have their time to live over again;
but though some of my early foibles and after deviations, might possibly,
on a second trial, be escaped,
yet I know not but there is quite as much reason
to think a second might fall very short of the first,
as in any degree to exceed it.

However, I have no kind of self-complacency on account of any good works properly mine.
My own works I have long seen the necessity to cease from, and trust,
through the grace of God, by which I am what I am, I have been enabled,
in some precious degree, to do so.
It is the Lord who worketh my works in me, and, magnified be his name forever,
he has often worked in me mightily, to my own humbling admiration, and, I trust,
at times, to the thankful acknowledgment of many others; and as certainly as he liveth,
he would work mightily in many thousands,
if they would but let him arise over all in them.
Indeed he worketh in all as far as they give way to his arising.
This doctrine is to me as clear and certain at this moment as ever it has been,
and I have often been constrained to proclaim it to the nations,
sometimes with almost invincible authority,
and sometimes under a great deal of weakness and obstruction.
The last has tended much to keep the creature rightly dependant and humble,
and through every dispensation the Leader of Israel has seen best what was best for me.

I may be easiest to mention my choice,
that neither of my sons should be encouraged to become a physician,
however it may be thought proper to dispose of my books, etc.
I believe a little general knowledge of medicine,
in possession of most modest and sensible men,
who would carefully avoid going out of their depth, and meddling in dangerous cases,
might prove very useful to others; but alas! it is too frequently the case,
that the most ignorant smatterers in it are the most confident,
and the most desperately venturous.
I do not say this, from the least scruple,
but that my dear boys might be initiated to a very sufficient insight,
both into the theory and practice; though I believe settling the theory,
with any tolerable certainty, at least in many parts of the business, ever has,
perhaps ever will, greatly baffle the sagacity of mortals.
The same perhaps may be said in religion: whilst the vital and practical parts are,
to the rightly opened and attentive mind, sufficiently accessible.
I believe God will, in many other things beside pure spirituals,
greatly evince that even _his_ foolishness,
(understand the expression aright,) is infinitely wiser than the wisdom of man;
going on still confounding the wisdom of the wise
and bringing to nought the understanding of the prudent.

Let my children be engaged in some innocent employments,
as much as well may be out of the way of a great deal of temptation,
and if I had need to add it, out of the way of very great accumulation; and yet,
through industry and perseverance, moderately productive.
My very soul abhors the idea that a christian can ever be at liberty,
whilst under the influence of heavenly good, to seek, or even desire much wealth,
though this disposition, in direct opposition to the life and doctrines of Christ,
has gone far towards the destruction of true spiritual religion,
I believe in almost every religious society in the world.
Alas! if there is any such thing, as the abomination of desolation,
it is mournfully seen standing in _ours,_ in almost every part of the countries,
where it ought not.

I think I have rather overdone my strength; you may think me very imprudent,
but it may ease my own mind; and I am, as before, yours, etc.

[.signed-section-signature]
J+++.+++ S.

[.letter-heading]
Epistle of Tender Caution Against Stumbling at the Faults of Others

It has been the work of the restless adversary of human happiness,
in all ages of the world, to strive to keep man in darkness, or to bring him into it.
Those who are in it, he strives to keep in it;
and those who have been redeemed in some degree from it,
he strives to captivate and beguile into it again: and his design in both is,
to prevent the enjoyment of the sweet flowings of the love of God,
and the powerful communication of the Holy Ghost.
For he knows that these enjoyments are only witnessed in the light.
He also knows the light would shine,
and even prevail to the letting the soul into the full fruition of those divine enjoyments,
if he did not with all his might strive to propagate the
kingdom and power of darkness in and over people`'s minds.

Now, the stratagems he makes use of are many and diverse; one of which,
and that not the least, it has been pressingly on my mind to write a few lines upon,
by way of caution to such as are desirous to land safe at last,
in the mansions of undisturbed felicity.
I have no desire to write one word on this occasion, but what may be of use,
and tend to strengthen those desires and strivings which the Lord of hosts delights in.
Therefore, I desire that all prejudice may be laid aside,
and my words weighed in that balance that ever is accompanied with a just weight,
and tried by that ear that trieth words, as the mouth tastes meat.

The particular snare of the adversary, that my mind is engaged to guard, caution,
and encourage against, is this, stumbling at the failings of others.
A potent engine, a powerful instrument which prevails by Satan`'s influence,
to the weakening the faith of many.
But, alas! alas! why will a spirit bound to eternity,
stumble over the failings of flesh and blood?
Why will a soul, that must finally settle accounts between God and itself, spend time,
waste time, to muse and despond at the infirmities of another?
The frailties of a thousand,
cannot impair the unchangeable truth and righteousness of Jehovah.
The hypocrisy of ten thousands cannot deprive the faithful persevering soul,
of the all-sufficient assistance of the mighty God of Jacob.

It is an everlasting truth, that there is a right way to serve God;
and though a multitude fall on the right hand,
and an host of those who have been as stars in the firmament, revolt on the left;
yet the true way-faring man, though a fool,
cannot err in that way which the Lord hath cast up for the ransomed to walk in.
We are told that the dragon`'s tail drew a third part of the very stars from heaven.
Was this told to stumble us?
Surely nay; but still the cry is, "`Come up hither,
and I will show thee the bride the Lamb`'s wife.`"
Now, the stumbler may say, "`I have strove to see the bride;
I have thought I had seen her; I have viewed her, and her beauty fades away;
her brightness disappears.`"
But, mark well! the call is, "`Come up hither and I will show thee.`"
It is not while we stand gazing at imperfections, and reasoning upon faults,
that we must expect this divine prospect.
No, no.
But, "`Come up hither, and I will show thee the bride, the Lamb`'s wife.`"
This "`come up hither,`" imports something very different from that halting,
lingering behind, and, as it were, sticking in the mire,
which my soul has truly mourned over and lamented.

I think I am a living witness, and can testify, that there are some,
who have long ago been kindly visited, and tenderly invited by the Lord,
to come and see how good he is; and who have even tasted, in a degree,
of the sweetness +++[+++of]
his love, who are yet far behind-hand with their day`'s work, are halting, doubting, and,
(may it not offend them,) are feeding on the serpent`'s food;
which was denounced by the lip of truth to be dust, and that all the days of his life.
And I also declare, under a feeling sense of divine authority,
that nothing better shall be the food, to all eternity,
of such as spend all the days of their lives in gazing at,
or stumbling over the failings of others.
But I mean not to censure.
It is their immortal souls`' welfare I have in view; therefore, I would call them, yea,
beseech and entreat them, as they tender their own salvation, to come away,--come away!
This is not your rest.
It surely is polluted.
It is a land of darkness, as darkness itself.
The shadows of the evening, yea,
the shadows of midnight are spread over the minds of the inhabitants thereof.

Oh, sorrowful! sorrowful! that any should love to dwell in utter darkness;
that any should suffer their immortal souls to be made so easy a prey to the dragon.
What will it avail thee, O soul, when thou comest before the great and final tribunal,
to say, such a man professed great sanctity, but was a hypocrite: therefore,
I was tempted to quit the service of the living God, and serve his enemy?
Or, such an one made profession of exalted piety but was a liar, a deceiver,
an abominable wretch; therefore, though I was somewhat washed,
I turned to my wallowing in the mire?
This will never justify thee at the gates of heaven,
nor procure thee an admittance thereinto.
Oh! my soul mourns on thy account.
My spirit is indeed grieved.
Come, let me query with thee.
Dost thou feel a daily striving to overcome evil in thyself?
Art thou constantly concerned to keep up the inward watch and holy warfare?
Yea, let me come closer.
Whilst thou art dwelling, musing, and feeding upon the faults of others,
art thou at the same time engaged, and panting after perfection in thy own soul?
While thou art rehearsing to thy intimate friend,
the wanderings and weaknesses of such and such,
dost thou feel longing and unquenchable desires in thy mind to
make war in righteousness against the power of corruption in thyself?
If not, the enemy of truth, it is to be feared,
may with justice challenge the praise due from thy complainings.

Oh! that that eye was open in thee, that could see thyself.
Oh! that thou hadst a heart to understand this mystery of iniquity.
But, alas! the adversary blinds thee.
For why dost thou give back because of another`'s weakness, but because of thine own?
Why stumblest thou at another`'s frailties, but because thyself art frail?
Make a pause then, and turn thy attention inward.
Set a watch upon the wicket of thy soul, and keep sentinel in deep attention there:
then wilt thou have enough to do, to view thy own imperfections,
and to guard against them so as not to stumble others.
Work enough, indeed, may be found to engage all thy care and diligence,
in labouring to cease from evil, and do good thyself.
It is less substantial than many a dream,
to give the victory over our own souls to our enemy,
because others are entangled in his snares.
Shall I quit the field and turn my back in the day of battle,
because a fellow soldier is treacherous, cowardly, or unfaithful,
when I know my all is at stake, and if I flee I must perish?
Surely nay.
I ought rather to put forward with more zeal, vigilance, and constancy;
endeavouring to encourage the fearful and unbelieving,
as knowing the salvation of their souls, as well as my own, is at stake.

Away then, thou reasoner, thou murmurer, with such pitiful musings and excuses.
The day of solemn reckoning draws near.
Thou must, ere long, appear before the Ancient of Days,
to give an account of the deeds done in thy frail, mortal body,
and to receive a reward according to thy works;
not according to the stability or instability of another.
Therefore, awake thou that sleepest, and arise from the dead,
that Christ may give thee light.
For darkness, gross darkness, is the encircling, overshadowing canopy of thy soul.
It is time for thee to hear and obey the command given to Israel of old,--to go forward;
for thou (with them) hast compassed this mountain long enough; a barren mountain,
in the wide, desolate wilderness, from the top of which, it is much to be feared,
thou mayst one day, or rather one night,
by the arising of a strong and boisterous whirlwind,
be swept off into the bottomless pit of despair, or into some quagmire, or swampy hole,
where serpents, reptiles, and venomous creatures breed and dwell.
Oh! that I could persuade thee, for thy own soul`'s sake,
to turn thy back on Satan`'s suggestions.
Oh! that thou could be prevailed upon to lift up thy heart above the world,
that so thy salvation might draw nigh indeed.

Now to conclude, let me once more beseech thee to hearken to that encouraging invitation,
which is sometimes sounded in the secret of thy soul, "`Come up hither,
and I will show thee the bride, the Lamb`'s wife.`"
Come up, is here the joyful sound: and even the spirit and the bride say, come:
and indeed, he that will come, may come: yea, verily, __may come:__
and if he improves the strength given, all the powers of earth,
and of the infernal hosts, cannot hinder him.
For "`there is no enchantment against Jacob,
nor divination against Israel,`" while sitting in their tents.
Therefore, to thy tents, O Israel!
To thy tents, O Israel!
Keep inward.
There thy strength lies.
There is thy place of preservation.
There shalt thou walk in the light of the Lord; his candle shall shine upon thee,
and his inspeaking word shall guide thee in the way everlasting.
Walking in which with fullness of peace, I desire to leave thee, and rest thy friend,

[.signed-section-signature]
Job Scott
