== Selection from the Journal of Job Scott

Forasmuch as it has pleased Divine Wisdom to lead and conduct my soul through many,
various, and afflictive dispensations;
as well as through some very comfortable enjoyments--giving
me to partake largely of afflictions,
bearing up my mind through them, bringing me forth again and again rejoicing,
after scenes of deep distress, and wonderfully preserving me through some very deep,
and perhaps somewhat unusual probations in my travel towards the land of rest--I feel,
and have often felt,
an engagement of mind to leave behind me some memorandums in commemoration
of His gracious dealings with me from my youth.

I was born, according to the best account I could obtain,
on the 18th day of the 10th month, 1751, in the township of Providence,
in the colony (now state) of Rhode Island in New England.
My parents`' names were John and Lydia Scott;
who were accounted honest people,
though my father made but little profession of religion.
My mother was more zealous, and attended Friends`' meetings when she conveniently could,
taking me several times with her, and I think another one or two of the children,
though we were all but young; for I, being the eldest,
was but ten years old when she died.
I can well remember the serious impressions and contemplations which,
at that early period of life, and for some years before my mother`'s decease,
attended my mind as I sat in meetings with her, and on the way home.
I even had longing desires to become truly religious, and to serve and fear God,
as Abraham, Isaac, and Jacob did, and others that I read or heard of.

My mother endeavored much to restrain us from being
in the company of rude and corrupt children,
and would sometimes call us together, and labor to have us sit in silence with her,
which we did.
And though I then understood but little of the intent of it,
it has since afforded me a degree of solid satisfaction
in believing that the Lord had given her to know and partake
of the sublime enjoyments and substantial benefits of true,
inward, Christian silence, and waiting upon God;
and to know that she desired us (even in our tender years) to be
made acquainted with those secret touches of divine favor which
she no doubt felt and experienced in seasons of retirement.
And though, as I observed before, I understood but little of it then,
yet I have since had reason to believe that these times were of real advantage to me,
and they have often been remembered since to my benefit.

I am fully persuaded of the great advantage, and spiritual usefulness,
to children and others, resulting from frequent, silent waiting on the Lord.
I have seen lively and convincing evidence of it,
even in children who are very young in years;
and I fully believe that the impressions of divine goodness that
have been stamped on the mind during these times (even when there
has not been a word uttered vocally) have lastingly remained,
and powerfully tended to beget a true fear and love of God in young and tender hearts.
And oh,
that parents were more generally concerned to do all they could towards
leading their tender offspring into an early acquaintance with,
and a relish after divine things; which is best learned, and most livingly,
and experientially sealed upon the soul, in a state of silent introversion,
and feeling after God.

I was told by some of my kindred who were present at my mother`'s death,
(for it being night I was not present myself,) that her departure was joyful and glorious;
and that very near her last breath was spent in fervent supplication to the Lord her God.

And now, not at all doubting that her immortal spirit is at rest in Jesus, I leave her,
and proceed to a further relation of the exercise of my own mind,
having this testimony to bear: that almost as early as I can remember anything,
I well remember the Lord`'s secret workings in my heart, by His grace or Holy Spirit,
very sensibly bringing me under condemnation for my evil thoughts and actions,
rudeness and bad words, disobedience to parents, wishing evil to those who offended me,
and all such like childish and corrupt dispositions and practices.
Indeed I can say, that over and beyond all outward instruction I received,
I was made inwardly sensible by the Spirit of Truth that these things were evil,
and that they sprang from a real root of evil in me.

I know some men argue that all we know of good and evil is by education, tuition,
or what we imbibe and receive from others;
and that the influence of custom and opinion determines and is the standard of morals.
But the fallacy of this argument may be easily shown,
as my own experience (and I doubt not, the experience of thousands) can testify.
For, in very early life,
I was made feelingly and convictively sensible that certain thoughts, wishes,
and propensities in my own mind--which no other mortal ever knew anything about,
and concerning which I had never had any human caution, counsel,
or instruction whatsoever--were of a corrupt and evil tendency,
and arose from a corrupt source in myself.
And I am in a full belief, that in every quarter of the globe, children, at an early age,
have good and evil set before them by the shinings of the light of Christ in their hearts,
with clearness and evidence sufficient to ascertain their duty,
if they honestly attend to it.
And though I am deeply sensible of the necessity and utility of careful guardianship,
cultivation, and instruction,
in order to guard children against the corrupting influence of example, invitation,
and perverse inclination, which abundantly and prevalently surround them;
yet I fear a great part of what is called Christian education or instruction
tends rather to blunt the true sense and evidence of divine truth upon the mind,
and to substitute notions and systems in its place,
than to encourage an honest attention to that Spirit which leads into all truth.
I am satisfied,
that if the teachings of men were never to oppose the teachings of the Holy Spirit,
many things would fix on the minds of children to be evils,
that are commonly encouraged as innocent and commendable.
And, on the other hand, I believe they would see pretty clearly, as they grew up,
that religion has nothing to do with the rituals and observances which are commonly
held (by a perversion of true discernment) to be of real importance in religious life.
Truly,
it is mournful to observe how many children are now
bolstered up by their blind guides into pride,
vanity, and revenge;
taught to pride themselves in a supposed superiority of abilities and attainments;
nursed up in ideas of grandeur and worldly honor; inspired with exalted notions of valor,
heroism, and human slaughter;
and at the same time settled down at ease in a round of outward religious performances,
as that which satisfies the demands of God.

In regard to my own early acquaintance with the Holy Spirit`'s operation,
though I then knew not what it was,
I have now no more doubt about it than I have about
the existence and omnipresence of God.
I am very clear, that at six and seven years of age,
the inward principle (which is the hand and power of God,
lovingly operative upon the soul), so wrought and shone and moved within me,
as to give me a sure and distinguishing sense of right and wrong, or good and evil,
in various particulars; and in some things altogether independent of human information.
It is sealed upon my heart with much clearness and certainty,
that this was the Spirit of the living God, the same that visits, woos, invites,
and strives with all (at least for a season), for God is no respecter of persons.
And I as fully believe that no man can have any clear knowledge of God,
or of his own religious duty, without the Holy Spirit`'s influence,
as I believe that the wisdom of this world is foolishness with God,
and that the world by wisdom knows Him not.
Oh how quick and powerful is this Spirit, or Word, or Witness in man,
unto the discerning of thoughts and intents of the heart!
How just and distinguishing it is in approving and condemning them,
according as they are good or evil,
not only without the aid of human injunction or information,
but often in direct disagreement with the sentiments, advice,
invitations and persuasions of my play-mates, and even those much older than myself,
and who confidently and repeatedly declared to me that such and such things were innocent,
and not at all wicked, and that nobody thought them to be so but myself.
Indeed, this testimony of Truth would and did arise and live in my heart when very young,
through the shining of divine light or influence of the Holy Spirit,
showing me those things that were evil and wicked.
And notwithstanding all those young persons could say to the contrary,
I believed that all good people would think as I did.

But when violence is done to clear conviction in the mind, death takes place,
as with Adam in the day he ate the forbidden fruit.
And in this state of death, the truth is not so easily distinguished from error,
or good from evil, as before transgression.
Evil habits gain strength; darkness covers the mind; temptation is renewed;
and though the Spirit again in some degree forewarns and bids beware, the mind,
accustomed to the stifling of conviction, too commonly rushes forward again,
and becomes more and more hardened and darkened,
until what was at first plainly condemned as evil (by the unflattering
Witness in the heart) is at length maintained to be innocent and sinless.
This is too commonly the course of poor mankind.

God makes His appearance in man in very early life,
but they too generally "`rebel against the light`" which He graciously affords them.
This prevents their "`knowing its ways`" because "`they abide not in its paths.`"^
footnote:[Job 24:13]
And how is it likely they should know the way of truth, or increase in divine wisdom,
when they sin against what God has already made known to them?
Yes, seeing they have known God (in some degree) by His shining in them,
but do not glorify Him as God by their obedience,
is it strange that they "`become vain in their imagination,
and their foolish hearts are darkened?`"^
footnote:[Romans 1:19-21]
And what is next?
Why just what follows in this Scripture passage;
for it is a very natural consequence of rebellion to be left in darkness,
and we often see it verified among men that, "`professing to be wise,
they become fools.`"^
footnote:[Romans 1:22]
"`Now we know better,
(they think) than to believe that this and the other thing is sinful.
These are trifles!
God takes no account of such minute affairs.
These careful men are overly-scrupulous.
If they give way to all these vain fears,
and allow themselves to be frightened with dreams of evil
in so many of the innocent amusements of life,
they will soon fancy nothing in the world is innocent.`"
This, and such like, is the language of that wisdom from beneath,
which governs the darkened minds of those who transgress the early convictions of truth,
and rebel against the light of heaven.
On the contrary, those who believe and walk in the light, while they have the light,
do truly become the children of it;
and therein are made the joyful children of the Day of God`'s salvation.

Before I was ten years old,
the workings of truth grew so powerful in my mind at times
that I several times resolved to amend my ways,
and to live a serious and religious life.
And though I was not one of the most corrupt boys of my age,
yet I was enough so to be made very sensible of the Lord`'s
controversy with me on account of the evil of my ways.
My mind often became exceedingly disquieted when I went contrary to divine manifestations;
though I had not yet a clear sense that this was the very power
and Spirit of God that so condemned and distressed me for sin,
and strove to redeem my soul from the bondage of corruption.

I now began to take notice of what I heard people read and converse of respecting religion;
and among other things,
I heard frequent mention in books and conversations of the Spirit
of God--how good people in former times had it in them,
and by it learned the will of God, and were enabled to perform it.
I perceived that this Spirit was often spoken of in both the Old and New Testaments,
and many other writings, and I understood that true converts in these days also have it.
But, like many others, I overlooked its lively checks, reproofs, and calls within myself;
and having no idea that I had ever known anything of it, I longed to be favored with it,
supposing it to be some extraordinary appearance,
far different from anything I had ever been acquainted with.

In the same way, the Jews, even while they were expecting Christ`'s coming,
knew Him not when He came.
They overlooked and despised His low and ordinary appearance,
thinking Him to be Joseph`'s son and born among them, and so they rejected, abused,
and finally put Him to death.
But they were mistaken in His pedigree; His descent was from heaven; and God, not Joseph,
was His Father.
In just the same way,
thousands now are mistaken as to the dignity and origin of God`'s Spirit in them.
They think that that which condemns for evil and calls to righteousness is of man,
a part of his nature and being; though it is a gift of the very life, power,
and substance of God.
Its descent is as truly from heaven, as was that of the Lord Jesus.
He came in that low, humble,
and ordinary appearance (with respect to outward show and accommodations)
teaching us thereby not to despise the day of small things,
nor overlook the littleness of the motions of divine life in our own souls.
And when He compared the kingdom of heaven (which
He expressly said was within) to outward things,
he very instructively showed that its beginnings were small,
"`a little leaven,`" "`a little seed,`" "`a grain
of mustard seed--the least of all seeds.`"
This is true in the inward, whatever we understand of the outward;
for the seed of the kingdom is "`the least of all
the seeds`" in the field or garden of the heart.
Other seeds sprout, spring up, and take the attention,
while "`the incorruptible seed,`" the "`implanted Word`" in the heart, is overlooked,
trampled under, and despised.

Oh! that children and all people would be careful in their very early years,
and as they grow up and advance in life,
to mind the "`reproofs of instruction`" in their own breasts;
they are known to be "`the way of life,`"^
footnote:[Proverbs 6:3 - "`For the commandment is a lamp, and the law a light;
reproofs of instruction are the way of life.`"]
divine life to the soul.
This something--though they know not what it is, that checks them in secret for evil,
both before and after they yield to the temptation,
warning them beforehand not to touch or taste, partake of, or commit iniquity,
and afterwards condemning them if they do so,
and also inwardly inclining them to a life of religion
and virtue--this is the very thing,
dear young people, whereby God works in you, both to will and to do.
And by this, if you cleave to it and work with it,
God will enable you to work out your own salvation with fear and trembling before Him.
Despise it not; do no violence to its motions.
Love it, cherish it, reverence it, and hearken to its pleadings with you.
Give up without delay to its requirings and obey its teachings.
It is God`'s messenger for good to your immortal soul.
Its voice in your streets is truly the voice of the living God.
Its call is a kind invitation to you from the throne of grace.
Hear it, and it will lead you.
Obey it, and it will save you; it will save you from the power of sin and Satan,
and will finally lead you to an inheritance incorruptible in the mansions of rest,
the house not made with hands, eternal in the heavens.

I entreat you, as you love your own souls, and prize an everlasting salvation;
I warn you, by the dreadful fruits of disobedience, by the pangs, remorse,
and sufferings of my own soul for sin and transgression!
Had I steadily obeyed the truth in my inward parts;
had I attended singly and faithfully to this divine monitor,
my portion would have been peace; my cup would have been a cup of consolation.
I might have rejoiced and sung, whereas I have had to mourn and weep.
For as I grew up to fifteen years and upwards, in violation of clear inward convictions,
and in opposition to the dictates of the Holy Spirit, I began to run into loose company,
learned to dance and play cards, and took great delight therein.
I was often deeply condemned, and often strove to stifle the inward Witness,
and persuade myself there was no harm in any of these things.

My father sometimes reproved me in those days for my conduct,
but sinning against divine light and visitations hardened me against his advice.
I grew more and more vain, proud, airy, and careless.
I put myself in the path of much evil communication,
and it mournfully corrupted good manners.
My taste for pleasure and amusement grew keen,
my spirits were low and languid when alone,
and I rushed into company and merriment for relief.

Thus I went on frolicking and gaming, and spending my precious time in vanity.
Often at night, or in the night, and sometimes near the break of day,
I have returned home from my merry meetings grievously condemned, distressed,
and ashamed, wishing I had not gone into such company, and resolving to do so no more.
But soon my resolutions failed me, and away I went again and again,
and thus continued making still greater strides in folly than before.
The Lord followed me close, in mercy, and often broke in powerfully upon me,
turning all my mirth into mourning.
Yet I still got over the holy Witness within, insulted the Spirit of grace,
and returned again to my haunts of diversion and merriment.

Sometimes when I have stood upon the floor to dance, with a partner by the hand,
before all were quite ready, God has arisen in judgment and smitten me to the very heart.
Oh, I still feelingly remember the majesty of His appearance within me,
when no one knew the agony of my soul; how He erected His tribunal in my bosom,
as in an instant, and in awfulness arraigned me before Him!
I felt ready to sink under the weight of condemnation and anguish,
but resolutely mustering all the stoutness I possessed, I brazened it out,
until the music called me to the dance.
Then I soon drowned the voice of conviction, became merry,
and caroused among my companions in dissipation,
until time brought about a dismissal of our jovial assembly, and called me to return,
often lonely, to my father`'s house.

Ah me!
How did it fare with me then?
I assure you, reader,
I have not forgotten those sad and mournful walks at the conclusion of my midnight revellings.
I have been broken down in deep abasement and self-abhorrence, have come to a full stand,
stopped and sat down on a stump, stone, or log, by the way, wrung my hands,
and strewed my tears before the Lord in sorrow and extremity of anguish,
bordering almost on desperation.
I have begged forgiveness, implored assistance, vowed amendment, obtained some relief,
and returned home in hope of reformation.
But alas, alas!
My resolutions were written, as it were, in the sand.
Indeed, the power of habit had enslaved me,
and almost the very next invitation of my associates overcame all of my newly-made promises.
The eagerness of my desires for entertainment and recreation,
broke through all the sanctions of my vows, and I rushed again into transgression,
as a horse rushes into the battle.
Again and again I took my swing, and drank my fill;
and again and again remorse and sorrow seized upon me.

But adored forever be the name of the Lord!
He forsook me not, but followed me still closer and closer,
and sounded the alarm louder and louder in my ears.
There was in me an immortal part, which His love was towards;
the recovery of which (from the bonds of sin and
corruption) He sought by mercy and by judgment,
by frowns and smiles, chastisements and endearments, and all in love inexpressible.

Thus He dealt with me.
When I turned at His reproofs, He smiled graciously upon me,
and relieved my soul`'s anxiety; but when I again revolted,
His rod was lifted up in fatherly correction.
The still small voice was spoken in my dwelling, as in the cool of the day,
whenever I was a little retired from noise and commotion--"`Adam, where are you?`"
There was no hiding from Him, whose penetrating eye no secret can escape,
and whose aim in reproving was only to save.
He still reproved my wanderings, and pointed out the right way,
according to the scripture declaration, "`You will hear a voice behind you, saying,
'`This is the way, walk in it.`'`"^
footnote:[Isaiah 30:21]
Indeed the way was shown to me; it was often plainly cast up before me,
but I would not walk in it.
I knew my Lord`'s will, but I did it not; my own will, I still delighted to indulged.
Oh! that others may escape my load of guilt, my bed of hell, and inward tormenting agony,
by a timely submission to the reproofs of instruction.

Sometimes I spent near all the first-day of the week (when
I should have been at meetings) in playing cards,
in idle, if not corrupt conversation, and in other vain amusements,
returning home at night under great condemnation.
Though in all this time I was much preserved from hard drinking and swearing,
yet I went to considerable lengths in jesting, joking, and vain conversation,
and sometimes joined the foremost of my companions in filthy and obscene discourses.
Then again, great shame and self-abhorrence would overwhelm me;
and once again I would vow, promise, and renew my covenant; but all was in vain,
for my covenants were not made and renewed in the right ability,
but were too much in my own strength and creaturely resolutions,
so that they soon were broken.
Sometimes I held out a week or two, other times only a day or two.
Thus time passed on, and, with an increase of years,
I found an increasing propensity to carelessness and dissipation.
But blessed be the God of my salvation,
He proportionately increased my sense of guilt and condemnation.

I had seasons of very serious consideration about religion.
What instructions I had outwardly received were mostly through meetings of Friends,
but when I came near to adulthood,
having fallen into company with some of the Baptist society,
I was drawn to attend their meetings in Providence.
Friends`' meetings were more often held in silence than suited my itching ear.
I loved to hear words, began to grow inquisitive,
and started to search pretty deeply into doctrines and tenets of religion.
The Baptist preachers filled my ears with words,
and my head with arguments and theological distinctions,
but I believe my heart was little or not at all improved by them.
I almost forsook the meetings of Friends, except yearly meetings,
and meetings appointed by traveling ministers in the service of the gospel.
But when I went to these,
oh how livingly I still remember the heavenly and heart-tendering
impressions I sometimes received under the lively,
animating testimonies delivered in the evidence and demonstration of the Holy Spirit,
and in the very life of the gospel.
Here my heart was helped, though my head was less amused than when among the Baptists.
However, as I knew not clearly what caused this difference,
and as I still desired the gratification of argumentative, systematic discourses,
I continued pretty diligently attending the Baptist meetings; and,
in my most religious seasons, I began to think of being baptized in water.

Because the head-work so far outran the heart-work
during my attendance of these wordy meetings,
I became convinced (in speculation) that this outward
performance was an ordinance of Christ;
though I have since seen, as clear as day-light,
that baptism in water was never ordained by Jesus, but was a forerunning, preparatory,
and decreasing institution; and that now, in the church, "`there is but one Lord,
one faith, and one baptism,`"^
footnote:[Ephesians 4:5]--that of the Holy Spirit and fire,
which alone can purify and make clean the inside.
Oh my heart, my very soul is fully satisfied in this matter,
having felt the living efficacy of this one saving baptism,
and known its full sufficiency without any other.

What first turned my mind to believe that the outward baptism was a Christian ordinance,
was this one argument of the Baptists:--"`Christ commanded His disciples to baptize;
no man can baptize with the Holy Spirit;
therefore the baptism He commanded was not that of the Holy Spirit but that of water.`"
This then appeared to me to be conclusive and unanswerable.
But it was my ignorance of that baptizing power (which attends all true
gospel ministry) that made me assent to the false position that,
"`no man can baptize with the Holy Spirit.`"
Man himself, in his own mere ability, I know cannot; but I also know, that of himself,
neither can he preach the gospel.
The assertion,
"`no man can preach the gospel,`" is just as true
as "`no man can baptize with the Holy Spirit.`"
Merely as man, he can do nothing at all of either.
But it still stands true that man can, and man does, through divine assistance, do both.
The real gospel was never preached,
except "`with the Holy Spirit sent down from heaven.`"^
footnote:[1 Peter 1:12]
Thus the apostles preached it, and thus it must be preached at this day;
and when it was so preached, it was indeed a baptizing ministry.
As they spoke, the Holy Spirit fell on those that heard them; that is to say,
where the living,
eternal Word was preached and was "`mixed with faith in those who heard,`"^
footnote:[Hebrews 4:2]
the Holy Spirit fell on them,
baptizing them into a living soul-saving sense of the "`power of God unto salvation,`"^
footnote:[Romans 1:16]
which is the true life of the gospel.
Thus the apostles fulfilled their commission; they taught baptizingly.
The commission was not, "`teach, and then baptize,`" as two separate acts;
it is "`teach all nations, baptizing them into the name.`"^
footnote:[Matthew 28:19. The Greek does not read "`baptizing them _in_ +++[+++en+++]+++
the name,`" but rather "`baptizing them _into_ +++[+++eis+++]+++ the name.`"]
It is one and the same act;
and those who livingly witness the gospel (the power
of God unto salvation) preached unto them,
they feel it and receive it; they are taught baptizingly,
"`in the demonstration of the Spirit and of power.`"^
footnote:[1 Corinthians 2:4]

I am fully persuaded that the use of water baptism, after Christ`'s resurrection,
was merely in condescension to the people,
for while the veil lies over people`'s understandings,
they cannot see clearly the spirituality of the gospel dispensation;
nor how it happened that the old things of John the Baptist and of Moses,
were not immediately and totally disused just as soon as they were fulfilled.
Though to the opened eye, this is not at all mysterious;
nor could it well have been otherwise, for it requires a great deal of care, caution,
and moderation, to rightly lay aside superseded observations.
The practice of circumcision also continued a considerable
number of years after the ascension of the Lord Jesus,
and was held in such high regard that some from the church in Judea
took great offense at Paul`'s not preaching it among the Gentiles.
Indeed,
many Jewish Christians were so zealous for the ceremonies of the law of Moses (even
some twenty years after the resurrection of Christ) that they feared Paul`'s presence
in Jerusalem would be offensive to the brethren unless he submitted to the rites of
purification in a way that demonstrated that "`he walked orderly and kept the law.`"^
footnote:[Acts 21:24]
Thus, we see how hard it was to drop circumcision and water-baptism all at once.
The people could scarcely bear it,
and prudence required a great deal of condescension and indulgence for a time,
in the continuance of these and other outward shadows.

But to return to my own early exercises about being baptized in water.
I could not, at that time, persuade myself that I was fit for it.
I thought it was a sacred ordinance, which none had a right to,
but such as (I now see) have no need of it, that is,
those who had first received its fulfillment and antitype, the saving baptism of Christ.

I had not yet fully given up to the motions of divine life in my own heart.
My mind was too much turned outward,
and the preaching of those I sometimes went to hear (who preached
in their own time) had a powerful tendency to keep it outward.
In this state of outward attention and inquiry,
I found nothing that could give me power over sin and corruption;
and notwithstanding all my serious thoughtfulness,
and frequent and ardent desires to become truly religious, I still, once in a while,
broke loose, and launched forth into as great degrees of vanity and wickedness as ever.

One time when under deep exercise,
after reasoning and hesitating a great part of a day about whether I had
best give up with full purpose of heart to lead a religious life or not;
at length I gave up, and entered once more into a solemn covenant, to serve God,
and deny myself, according to the best of my understanding.
But almost as soon as I had thus given up, and come to this good conclusion,
in stepped the grand adversary,
and exceedingly confused and distressed my mind with the doctrine of predestination;
powerfully insinuating that a certain number were infallibly ordained to eternal salvation,
the rest to inevitable destruction;
and that not all the religious exercises of my mind could possibly
make any alteration in my final destination and allotment.
If God had damned me from all eternity, I must be damned forever;
if he had chosen me to eternal salvation, I might set my heart at rest,
and live such a life as would most gratify my natural inclinations.
For what advantage could there be in a strict life of purity and self-denial,
if an eternal, unalterable decree had already secured my salvation?
I felt willing to hope I was a chosen vessel;
and for a short time these absurd (and may I not say,
blasphemous?) ideas so crowded into my mind,
that I was even ready to conclude that a God of all goodness had
doomed the far greater part of mankind to never ending misery,
without any provocation on their part.
I now view the doctrine of unconditional election and reprobation with abhorrence,
I almost marvel, that even under a cloud of darkness,
my rational faculties could ever assent to so monstrous a sentiment.

I held out here only a few weeks when, mournful to relate,
the influence of young company, and my vehement desires for creaturely indulgence,
broke through all my solemn vows, threw down my walls and fortifications,
and exposed me as easy prey to the grand enemy of my soul`'s salvation.
Once again I took my swing in vanity, amusements, and dissipation.
This, however, was but a short race, though a wretched one.
The Lord, in unspeakable lovingkindness,
followed me with His judgments which were inwardly revealed against sin.
The prince of darkness also followed me, with temptation upon temptation to evil,
and with various subtle insinuations and dark notions, to rid me of all fear, restraint,
or tenderness of conscience.

At length, notwithstanding all I had felt of the power of God upon me,
in reproving me for sin and inviting me to holiness,
the holy Witness became so stifled within me that I began
to entertain the notion that there was no God,
that all things came about by chance, by nature,
by the fortuitous jumble and concourse of atoms, without any designing cause,
or intelligent arrangement.
Here let it be well considered, how the admission of one false doctrine,
and the violation of divine manifestation and conviction in my conscience,
did pave the way for other false doctrines.
For not long after I had received and cherished the doctrine of irresistible predestination,
the mists of darkness did so spread over my mind,
that I not only dared to deny the eternal Deity,
but (horrible to think of!) also began to rejoice in the idea of unbounded,
unrestrained licentiousness and carnality, and that I was unaccountable for my conduct!

Oh then the depravity of taste and inclination, as well as of understanding,
into which I was plunged!
I as much marvel now that I could wish there was no God,
as that I could believe so intolerable an absurdity.
One evening in company with some of my merry companions
we conversed upon a variety of subjects,
till at length I introduced my new subject,
to see what the company could advance against it.
And being unwilling they should know how seriously I entertained the idea,
I introduced it as a mere supposition, declaring that, for argument`'s sake,
I would attempt to prove by reason that there was no God,
clearer than they could prove there was one.
Some of the company thought my extravagance and presumption quite strange;
some laughed at my nonsense; and some seemed pleased with the novelty of the idea.
At length we dropped it, but fear and condemnation soon seized upon me,
even before I left my merry companions.
I tried all I could to laugh, and to mount up above my fears;
but my heart trembled with astonishment to think how far I had gone,
and what might become of me.
I took my leave of my friends, and returned home in agony.
And now I think I should be cruel in the extreme,
were I to wish my greatest enemy to endure the fear, horror, anxiety, and amazement,
that I passed through that night, both in my journey home, and after I arrived.
I scarcely dared enter my bed-chamber, lest I should be suddenly,
and in some awful manner, brought to judgment and punished for my audacity and folly.
O young person, whoever you are that read these lines, I warn you, I beseech you:
shun such misery by timely obedience;
avoid such unutterable anxiety by cleaving to the Lord;
for it takes more and more to bend the will,
after it has grown hard through ignoring the living impressions of the Spirit of Truth.

I went on a few months longer in much the same manner.
My days were spent in vanity and rebellion;
my nights frequently passed in horror and distress!
Wherever I went, conviction went with me.
My accuser, and yet my best friend, lay close in my bosom, and,
while I continued to rebel, He tormented me both night and day; yet all in tender love,
in order to redeem my precious soul,
and bow my stubborn will to the obedience of the cross.
Yes, I have the most unshaken ground to believe that it was the immediate
power of God upon me that thus set my sins in order before me,
and pleaded with me to return to Him and live.

I continued in this way till the winter of the year 1770, when,
being about nineteen years old,
I became more fully and clearly convinced (by the immediate operations, illuminations,
and openings of divine light in my own mind) that this inward
_something_ which had long and powerfully striven with me,
disturbing my every false rest,
confuting every false and sin-flattering imagination of flesh and blood,
or of the grand adversary, and enjoining it upon me to give up all,
and walk in the ways of virtue and true self-denial,
was the true and living Spirit and power of the eternal
God--the very same that strove with the old world,^
footnote:[Genesis 6:3]
influenced the patriarchs, prophets, and apostles, and still visits, strives with,
and at seasons (more or less) influences the hearts of all mankind.
I now saw this to be the only working power of all true conversion and salvation,
and understood that, so long as this is resisted and rejected,
a separation must infallibly remain between God and the soul;
but whenever this is received, and in all things thoroughly submitted to,
a thorough reconciliation takes place.

True religion or regeneration is a reality;
and all the substantial reality of it centers in one word-- "`Immanuel,`" that is,
"`God with man.`"
And until something of this union is livingly known,
there is nothing known of true religion.
The world, under various forms of religious profession, is amused with dreams, systems,
and imaginations, while the "`one thing needful`" is too little experienced.
The one thing needful is a real union with God,
an actual joining to Him in the one Spirit.
Without this union, let a man know what he will; let him believe, possess,
and enjoy whatever he can, he is still but an alien and a wanderer on the earth.
Nothing else can ever satisfy his soul, or abidingly stay his mind.
There is no other permanent rest for the sole of his foot.
He may strive, toil, and bustle about, and many may think him in a state of enjoyment;
but it is all a delusion.
In the midst of all earth`'s caresses, if he presumes to declare himself happy,
he does violence to truth and to his own feelings,
and the truly wise can see through the lie.
If he professes religion, goes to meeting, practices the exteriors of devotion,
and talks much about faith and godliness, it may, for a moment,
quiet his mind and deceive his own soul and others;
but he cannot rest composed very long without a living union with God.
He may turn to the right and left, look this way and that, seek enjoyment in society,
in sensual gratifications, in wealth, honor, and worldly advancement; or he may read,
pray, meditate, sing, write, and dip deeply into creaturely devotion;
but without this living union, he is lost, unanchored, "`miserable, poor, blind,
and naked.`"

Having thus at length become livingly convinced that it was nothing
short of the eternal power and Spirit of God that so forcibly wrought
in me for my deliverance from the power of darkness and seduction,
I was enabled to give up to the holy requirings of God,
as these were thereby inwardly made known to me.
Nothing else could ever have so opened my mind and made known my duty to me.
The Scriptures, other good books, gospel ministry, religious conversation,
contemplation upon the works of creation and providence--all
these are very good means of information;
but none of them, nor even all of them together,
without the Holy Spirit`'s operation and evidence upon the mind,
can ever make a man sure of his duty to God in any one thing.
He may reason, and set up many rules, measures, and standards of duty and morality;
but he never will arrive at certainty without the
help of that Light which in itself is certain.
It may be said that the Scriptures are certain.
Very well, but what certifies to you that they are certain,
or that you know their true meaning?
Do not the professed masters in reasoning widely differ
from each other about many passages in the sacred writings?
And do they not all say they have reason on their side?
But believe them not, without the light and evidence of the Holy Spirit.

But to proceed--I gave up very fully and from the heart,
to serve the Lord in the way of His leadings; I forsook rude and corrupt company,
withdrew into retirement, attended meetings of Friends,
and often sought the Lord and waited upon Him in solemn, reverential silence alone,
seeking His counsel, direction, and preservation.
And He was graciously pleased to point out and cast up the way for me,
one thing after another, with sufficient clearness.
First, He showed me what I ought not to do in various particulars,
breaking me off from my corrupt practices and associations.
This was forsaking evil.
And then He taught and directed me in the practice of several particular things,
engaging me to choose and cleave unto that which is good.
I saw clearly that it was His will, and my indispensable duty,
to reverently assemble with His people for divine worship, and therein to wait upon Him,
draw inwardly near unto Him,
and (according to the apostle`'s language in Acts 17:27) grope for Him,
in order to find and enjoy Him.
I also found it my duty often to wait upon Him when alone in silent retirement;
not approaching Him in supplication except when He influenced my heart
thereto with the true Spirit of prayer and intercession.

He showed me also that religion was an internal life in the soul,
and that great attention, sincerity,
and punctuality were necessary to the growth and prosperity of it.
I saw I must not be content with attending meetings and sitting in silence,
though ever so reverently and properly,
but must live continually in an inward watchfulness and dedication of heart,
watching all my thoughts, words, and actions,
and experiencing all things within me brought to judgment,
allowing nothing to pass unexamined.
He showed me I must observe the most upright honesty
and sincerity in my dealings among men,
as in the presence of God, who witnesses all my outward actions and inward thoughts.
He taught me that men generally rely too much on external performances and appearances.
And thus guarding my mind against thinking too much of any outward thing,
He opened my understanding to behold my duty in regard
to outward plainness--giving me to see that a plain,
decent,
and not costly dress and way of living (in all things) was
most agreeable to true Christian gravity and self-denial;
and that a rich, showy, or fashionable dress, house, food, or furniture,
fed and fostered pride and ostentation in the heart, robbed the poor, pleased the vain,
and led into a great deal of unnecessary care, toil,
and concern to maintain this way of life and appearance.
I saw how such things could not afford any true and solid satisfaction,
but must unavoidably divert the mind from inward, feeling watchfulness,
hinder the work of mortification and true self-denial,
and facilitate unprofitable relationships and acquaintances with
men who would rather alienate their affections from God,
than unite their soul to Him.

Thus instructed, I bowed in reverence;
and as it became from time to time necessary to procure new clothing,
I endeavored to conform my outward appearance in this respect to the dictates of truth,
in which I found true peace and satisfaction.
Also, He instructed me to use the plain Scripture language, _Thou_ to one person,
and _You_ to more than one.^
footnote:[As has already been mentioned in the first volume of Truth in the Inward Parts,
beginning in the 17th century,
the correct and plain use of "`thee`" and "`thou`" to one
person had begun to give way to "`you`" and "`your.`"
Most modern English speakers are unaware that the words "`you`" and "`your`"
were originally _plural_ pronouns used only to address two or more people,
whereas "`thee`" and "`thou`" were used to address one person.
In the 1600`'s,
it became fashionable (originally as a means of showing honor or flattery) to
use the plural "`you`" or "`your`" in addressing people of higher social status,
while "`thee`" and "`thou`" were reserved for servants, children,
or people of lower social or economic position.
Friends stuck to what was then considered "`plain
language`" (using thee and thou to every single person,
and you and your to two or more),
rather than showing preferment by addressing certain individuals in the plural.]
The cross greatly offended me in regard to these things.
The issue of language in particular looked so trifling
and foolish to the worldly-wise part in me,
and the fear of the "`world`'s dread laugh`" so powerfully opposed it,
that I gave way to carnal reasoning.
What good can this exactness of language do?
May I not as well serve God in a less strange and contemptible way,
as to involve myself in those things that will be sure to render me ridiculous?
The world can see nothing in this but whim and superstition;
and of what possible use can a man be to others if his nonconformity
shuts him out from their favorable notice and attention?
And if it is of no harm to others, where is the harm to me, as an individual,
to continue in my customary language?
Such reasonings as these, and many more,
presented themselves in opposition to the holy injunction.
But the Lord showed me, that if I "`would be wise,`" I must "`first become a fool.`"^
footnote:[1 Corinthians 3:18]
If I would be His disciple, I must first deny myself,
take up my cross daily in whatever He required of me,
and follow Him in the way of His leadings.
It was very hard and trying to my natural will to give up to this duty.
I thought if my right hand would excuse my compliance, I would gladly sacrifice it,
rather than give up to use such a despised way of speaking,
and submit to be laughed at as one who viewed religion
to be concerned in such little things as these.

This exercise beset me day and night for some time,
during which I had many sorrowful and bitter tears, pleaded many excuses,
and greatly wished some substitute might be accepted instead of the thing called for.
But He who called me into the performance of these
foolish things (foolish to the world`'s wisdom),
was graciously pleased to show me with indubitable clearness,
that He would choose His own sacrifice; and that neither a right hand nor a right eye,
neither thousands of rams, nor ten thousand rivers of oil,
would by any means answer instead of His requirings.
If He called for so weak or foolish a thing as the words _thee_ and _thou_ to a single person,
instead of _you,_ nothing else of my own substituting would do instead of it;
for "`the foolishness of God is wiser than men.`"^
footnote:[1 Corinthians 1:25]
Let none dispute this ground with the omnipotent One, nor confer with flesh and blood;
lest by despising the day of small things, they fall away little by little.
For be assured, O you who are called of the Lord, you can never become His chosen,
unless you obey His call, and come out of all He calls you from.
If you are not faithful in the little, you will not be made ruler over much.

Perhaps few will believe the fulness of heavenly joy which sprang in my bosom,
as a well-spring of living waters,
after I at last gave up in faithfulness to this requisition.
And yet this flow of divine consolation did not last long at this time;
for though I gave up to whatever the Lord required of me,
yet as I had so long and so stubbornly rebelled against Him, He saw fit,
in His infinite wisdom, soon to hide His face from me again,
and close me up in almost utter darkness,
which rendered my days truly tedious and my nights wearisome to my soul.

I was fully convinced that God was to be known inwardly, in power and great glory,
by those who obey Him and wait upon Him.
My heart was inflamed with love towards Him.
I had seen a little of His beauty, and He had become the beloved of my soul,
the chiefest among ten thousands.
Therefore I often retired alone, and in profound reverential silence, sought after Him,
and pressingly solicited a nearer acquaintance with Him.
But knowing what was best for me, He graciously hid His presence from me.
And though this was a painful season,
yet I could not feel easy to give up seeking after Him.
I still continued my ardent silent approaches, or times of waiting.
Indeed, I waited with all the reverence, humility,
and solicitude that my soul was capable of; but all seemed in vain.
No spark or ray of light could I behold, no glimpse of heaven`'s returning favor.
Oh, the mourning and lamentation, the distress and bitter weeping,
that almost continually overwhelmed me for several months together,
for lack of the soul-enlivening presence of my God! "`Oh,`" said I in my heart,
"`will He never arise for my help and deliverance?
Well, be that as it may, I will seek Him until my dying day;
my soul cannot live without Him; and it may be,
if He hides His face from me until my last moments,
He may yet acknowledge me at that solemn end, and receive me to glory.`"
This was often, very often, the language of my heart;
and under this resolution I pressed forward in the bitterness of my soul.
I trust the wormwood and the gall, the sorrow and the sighing,
the days and nights of anguish, will scarcely ever be forgotten.
It seems to me that certain spots of earth, some particular fields and groves,
will ever (while life and sensibility remain) continue
to have a moving and affecting influence on my mind,
as often as I pass by and see them, or call them to remembrance.
Indeed, they remain peculiarly distinguished to me by the tears and the groans,
the sighs and solicitations, of which they have been the silent witnesses.

O my God!
You led me through the desert.
You weaned me from the world, and allured me into the wilderness.
There You did hide Your face from me for a season;
until the longings of my soul after You were intensely kindled.
Then You lifted up my head and spoke comfortably to me; blessed be Your holy name forever!

At length, after the Father of mercies had thus tried me,
He graciously cast an eye of compassion upon me, hearkened to the voice of my distress,
made bare His everlasting arm for my deliverance.
He gradually unveiled His holy presence to me,
and opened my heart to understand why He led me through so trying a dispensation.
I now began to discern in the mystery what I read in the
history of Israel`'s forty years travel in the wilderness,
as also "`the voice of one crying in the wilderness.`"^
footnote:[Isaiah 40:3; Matthew 3:3]
I began to see the necessity of the Lord`'s sending
His forerunner that the way might be prepared,
and the paths made straight.
I perceived how much roughness, unevenness, and crookedness had been in His way,
and so I began to know and (in measure) to love the rod, and Him who had appointed it.
And as the Master manifested Himself more and more,
I understood more and more of the mysterious ways of His working.

After some time I had many clear openings respecting the many trials, experiences,
jeopardies, and deliverances of His followers in days past;
and a hope was kindled in me that I might now go forward without meeting with such besetments,
and withdrawings of light, as previously.
For although the Lord still at times withdrew from me,
yet because His return was not long after,
and His presence was much more constantly with me,
I was ready to conclude that this might continue with increasing
brightness till I was wholly swallowed up in His love.
And, not clearly understanding the counsel of His divine will,
I was inclined to wish this my constant condition,
not then seeing (as I have seen since),
that it was not at all best for me to have a constant state of sunshine and fair weather.
Even the outward order and direction of divine providence in nature affords us instruction,
which often beautifully applies to our inward experiences.
It is not all calm and sunshine.
Indeed,
the divine wisdom orders many and great fluctuations and changes in the natural world,
insomuch that, perhaps in the most pleasant and flourishing season of the year,
after a few days of clear shining and tranquillity, there arises a most terrible storm,
with wind, lightning, thunder and hailstones.
At other times high and rushing winds follow the calmest day,
or pinching droughts succeed the most fruitful season.
Even the established order and succession of seasons
is a continual revolution of day and night,
summer and winter, seed-time and harvest.
We have cold as well as heat, darkness as well as light,
cutting frosts as well as most refreshing dews, and a variety of other changes.
All of this is in infinite wisdom and goodness,
and displays to the discerning eye the providential power and glory of the great Superintendent.
Bow, O my soul!
Adore and worship the God of your life, who is the length of your days,
and your portion forever.
His works are wondrous, past finding out, marvelous, and beyond your comprehension.
You see in part the multitude and magnitude of His wonderful works;
you behold a small part of the changes and fluctuations attending them;
and yet through all, what excellent order, harmony, and regularity are preserved!
Surely nothing less than omnipotence joined with omniscience
could possibly effect or produce all this.
And though He may exercise the souls of His chosen with various and afflictive dispensations,
yes, even "`choose them in the furnace of affliction,`"^
footnote:[Isaiah 48:10]
yet His love to them can no more fail than day and night can cease,
or His covenant with them be annulled.
It is as much in wisdom and goodness that He sometimes (as it were) withdraws,
hides from, and leaves His children,
and then again returns gloriously for their unspeakable consolation,
as is the succession of darkness and light, cold and warm seasons, in the outward world.

Many and varied afflictions are necessary to our refinement.
Hence the place of this refinement is called, "`the furnace of affliction.`"^
footnote:[Isaiah 48:10]
Through the purifying operations of these fiery trials,
the soul is gradually redeemed from the pit of pollution.
And he who becomes thoroughly acquainted with the corruptions of human nature,
in its alienation from God,
will find (if ever true humiliation and renovation is effected in him)
that nothing short of the baptism of fire can rightly cleanse the corrupt,
and humble the proud heart of fallen man.
Indeed it is a sealed truth,
that they who are without chastisement are illegitimate children, and not sons.
"`All whom the Father loves, He chastens, and scourges every one that He receives.`"^
footnote:[Hebrews 12:6]
My soul rejoices and gives thanks to God for the
deep probations and withdrawings of His presence;
as well as for the discernible experiences of His love and
the arisings of the light of His countenance upon me.
I see and acknowledge it to be needful for my growth in the divine life,
as well as for my complete emancipation from the servitude of sin,
that He should deal thus with me;
and it has afforded instruction to my mind that He is called in Scripture
by the name of "`the Lord that hides His face from the house of Jacob.`"^
footnote:[Isaiah 8:17]
Oh, what great panting of soul, what anxious longing for His return,
takes place in all the true travelers, whenever He veils His holy presence.
And how joyful is the lifting up of His countenance after these seasons upon
the drooping mind which has been thus prepared for His comforting return!
It is like the return of the clear shining sun after a rain.

Under the refining hand of God`'s power, whereby He thus humbled and abased my soul,
I was enabled clearly to see the need I would have of this excellent
qualification--__humility__--in my further progress in religious life.
I saw pretty clearly, even in the midst of my deepest depression,
that if I should be favored with unremitting peace and divine enjoyment,
I would be in danger of spiritual pride and exaltation.
Blessed be the name of the Lord for this among His many
other favors--that He taught me the necessity of humility,
and so forewarned and forearmed me against the wiles of Satan.
Oh, with what ardency of desire did my prayers ascend before Him that
He would rebuke the proud luciferian spirit in me,
and appoint my dwelling in the low valley,
where the grass is green and where the fragrant flowers give forth a pleasant smell.
I saw that on the lofty mountains often reign barrenness and desolation.
So my mind was almost constantly impressed in those
days with a love and desire for deep humility.
I saw something of its real beauty, and craved it as one of the greatest blessings.
"`Oh,`" said I, "`that I may put it on as a garment, and wear it forever; yes,
and even appear in it before my Judge in the assembly
of saints and angels in a future state!`" "`O Lord,
my God,`" was then my language, and my heart now joins it,
"`permit me never to forget my tribulations,
nor to cease my prayers to you for the continuance of this precious humility!
Let this be the first and the last in the catalogue of my requests.`"

Thus the great Leader of Israel led me on from step to step;
not by any means through a constant and uninterrupted enjoyment of his presence,
but (which for me has been far better) by frequent withdrawings, strippings,
and deep-felt emptiness, poverty, and want.
This He repeated again and again,
even after large overflowings of His love in my soul
as a river overflowing all its banks.
But, after such seasons of rejoicing,
had He not veiled His presence and clothed my soul with mourning, I might,
like ancient Israel, have "`sung His praise, and soon forgot His works.`"^
footnote:[Psalm 106:12-13]
But now, through the many tribulations and wise turnings of His holy hand upon me,
my soul is bowed,
and to this day it remains sensible of the tendering impressions of His love and goodness.
The savor of life is still fresh within me.
He has led me about and instructed me,
and (with reverence I speak it) has kept and preserved me.
May I still be preserved, and henceforth be kept safe under His all-powerful protection;
walking worthy of the same to the end of my days.
Amen.

During a great part of the foregoing exercises, I had frequent openings,
and a measure of living understanding was granted respecting the
Christian warfare and the mysteries of the kingdom of heaven.
I often believed, in the openings of divine light, that if I stood faithful,
it would be required of me to declare to others what
the Lord had done for me and shown to me,
and to entreat my fellow creatures to seek a habitation
in that kingdom that cannot be shaken or fade away.
This concern began now to grow upon me considerably,
even to that degree that I sometimes felt a living engagement
in meetings to communicate something to the people.
But, fearing I should begin in this great work before the right time, I kept back;
and even several times, when I was almost ready to stand up,
concluded I would keep silence just once more.
For I considered within myself, that if my doing so should be displeasing to the Lord,
then He would manifest His displeasure to me;
but if I should presume to speak a word in His name without His holy requiring,
or too soon, then I would not only displease Him, but also burden His people.
And in this way, I might perhaps get into, and become entangled in,
the practice of speaking from too small of motions or impressions felt,
or mournfully mistake the sparks of my own kindling for divine impressions; which might,
in consequence of my giving way thereto, be allowed to increase upon me,
to my great loss in the substantial and divine life, if not to my utter ruin.

In this guarded frame of mind I passed on for some time,
often seeking the Lord for counsel and direction in this and other concerns of importance.
And though I believe I might have publicly borne testimony in the name, power,
and approbation of the Lord somewhat sooner than I did, yet as I was not obstinately,
but rather carefully reluctant, I seldom felt much condemnation for withholding.
I did, however, a few times, feel some real uneasiness on that account.
But He who laid the concern upon me, well knowing the integrity of my heart,
and that I was bent faithfully to serve Him without either going too fast,
or tarrying behind my Guide, dealt graciously with me.
He passed by my little withholdings,
favored me with fresh and increasing experiences of His love,
and at length cast up my way in so clear and confirming
a manner as erased all doubt and hesitation from my mind,
and I uttered a few words in our meeting at Providence, on the first day of the week,
and 10th of the 4th month, 1774, to my own and I believe my friends`' satisfaction.
I felt the reward of peace in my own bosom as a river
of life for a considerable time afterwards,
sweetly comforting my mind, and confirming me in this solemn undertaking.
The words I uttered were as follows: "`My mind has often, yes, very often,
been attended with earnest desires for the good of souls,
particularly for the attenders of this meeting, and in a special manner for a remnant,
whose hearts, I believe, God has touched.
And the language of my mind has often been after this manner:
Oh! that Zion might arise and shake herself from the dust of the earth,
and put on her beautiful garments.`"
Having, in brokenness of heart,
and in great care not to exceed the bounds of divine requisition,
uttered these few words, I sat down,
and was (as it were) swallowed up in the luminous presence
of Him who inhabits eternity and dwells in the light.

After some time of heavenly rejoicing,
I began to be tried again with various exercises and conflicts of mind,
though still frequently favored with the flowing of divine
love in a very comfortable and soul-satisfying manner.
At various time I had living impressions to say a few words in public testimony,
but I still waited to be well assured.
The unspeakable consolation which I experienced on my first uttering
a few words (after having held back for a considerable time,
rather than proceeding in haste) had fully confirmed
me that there is greater safety in turning the fleece,
and proving it both wet and dry,^
footnote:[Judges 6:36-40]
than in rushing forward in the first operations or openings of the Spirit.
As I thus waited for clearness, fearing to run too fast,
I was favored to know the fire of the Lord rightly kindled upon his altar,
and to witness an offering of His own preparing.
And I am well assured that such, and such only,
are the offerings which will find acceptance with Him.

There is strange fire now, just as there was formerly;^
footnote:[Leviticus 10:1-3]
and it has no more place or approval now in gospel worship,
than it had in the offerings under the law, where we find it was strictly forbidden.
And whether or not it is now generally known and understood to be so,
the prohibition against it is as binding on all true
worshippers in our day as ever it was of old.
Oh, that Israel may ever observe this important prohibition!
I am persuaded that a due observance of it would contribute greatly
to the brightness and prosperity of our religious society,
and to the spreading and advancement of the kingdom of the Messiah.

Alas, for many of the professing Christians of our day!
How little they are aware of the prevalence of idolatry among them!
But in its source, spring, and substance,
it is the same as that idolatry which is so repeatedly
and severely reproved in the Scriptures.
For truly, every offering which is not of God`'s immediate preparation in us is idolatry,
and is no more useful to men, or acceptable to God,
than the idolatry that was common among the Jews.
The forward will and warmth of man`'s own spirit may,
at any time when he has the use of speech, prompt him to utter whatever he conceives.
But to rightly utter a request to God, or to speak on His behalf,
always requires His divine, living, and immediate assistance.

"`He that believes, shall not make haste.`"^
footnote:[Isaiah 28:16]
Indeed, whenever he rightly believes, he dares not be hasty;
for he always knows that his help is only in God; that the root must bear him,
and not he the root; that God must move him, and that he cannot move God.
He who runs into prayer, preaching,
etc. before Christ (the life) livingly moves him thereto, makes haste.
But the true believer believes in, and waits for, the living coming in Spirit of Christ,
his life; and so it is Christ that lives and acts in him.

My second public appearance in the ministry was at the lower meetinghouse in Smithfield,
the 19th of the 10th month, 1774,
when I found a living concern upon me to encourage a careful
heart-engagement before the Lord when not in our meetings;
and to press it upon Friends to draw near unto Him from day to day,
that strength may be renewed, and the divine savor of life retained,
lest we lose the living sense of what we often graciously enjoy in our meetings.
Divine life attended me in this little testimony, as in the former,
and after meeting I enjoyed the sweet influence of Him who is the God of my salvation,
in a degree that was greatly to my confirmation and encouragement.

After this I still continued to seek and wait upon God for counsel and direction;
in which frame of mind I was favored to renew and
increase a living acquaintance with Him,
and witnessed fresh instruction to my mind.
I appeared but seldom in public testimony, and mostly with just a few words at a time.
However, a few times I have been made sensible of saying too much,
for which I have felt more pain of mind than I have ever felt for withholding.
Yet, through merciful preservation,
I have seldom (to my knowledge) spoken more often or said
more than has tended to my own relief and satisfaction,
and (for all I know) to the satisfaction of my brethren.
Blessed be the name of the Lord my God!
I bow in awe before Him,
for His directing and preserving presence through many deep probations.
He has been with me in the heights and in the depths; has strung my bow,
and covered my head in the day of battle.
May I serve Him faithfully all the days of my stay here, until I go hence,
and am seen of men no more.

[.asterism]
'''

__Job Scott was a school teacher by profession,
but became a gifted and well-beloved minister in the Society of Friends.
He was known for his total dependence upon the immediate
moving and empowering of the Holy Spirit,
and his unwillingness to minister without a clear sense of the Lord`'s will.
On occasions, while preaching, he would suddenly stop speaking and sit down,
explaining later that,
having lost a sense of the authority and direction of the Spirit of God,
he could do nothing without it.
In 1792, he felt led to take a journey to Europe in the work of the gospel,
and for some months traveled and preached in England and Ireland,
both in Friends`' meetings and in those of other Christian societies.
Towards the end of the year 1793, while ministering in Ballitore, Ireland,
and staying in the home of Elizabeth Shackleton, he was taken ill with the smallpox,
and after a short but agonizing struggle with the disease,
ended his race in the 42nd year of his age.
Just prior to his decease, he wrote in his journal:
"`All the former conflicts,
however grievous in their time, are lighter now than vanity,
except as they are clearly seen to have contributed
largely to the sanctification of the soul,
and are remembered with awe and gratitude before
Him who has not failed to preserve through them all.`"__
