== Preface

It is now nearly 20 years since,
with a view to publication on the centenary of his death,
I began selecting extracts from the Journal of Job
Scott as given in his complete works (Byberry,
Penna, 1831) in two volumes which are extremely scarce in this country.
That selection remained unused, but all through the intervening years,
the concern has remained, and the following pages are based on a fresh selection,
though I cannot now,
any more than in 1893 look for any considerable interest in its publication.

Time was when Job Scott appealed to a much larger circle
of readers than he is likely to meet with today,
that is not because his style is archaic,
or because any more modern writers have treated the
deep and important subjects he writes on,
more clearly, more forcibly or truly,
but because the number of those who by actual experience
can fully understand his language is smaller.
Yet it is of the utmost importance to the Church of Christ that
this quality of spiritual experience should remain on the earth,
and bring forth its legitimate fruit,
exercising the far reaching influence designed by the Great Husbandman.

Convictions so glowing,
so searching in their practical application to various phases of life,
with spiritual perceptions, so luminous,
so harmonising to the claims of faith and reason, are now rarely met with,
and perhaps more rarely appreciated,
yet from time to time readers of previous selections from the Journal,
both in this country and in America,
have been deeply impressed:--the Journal of Job Scott has been to them,
a never-to-be-forgotten book.

The present Edition is brought out more for the sake
of seekers after Truth outside the Society of Friends,
to whom the Truths presented wear almost a new face, than for its membership,
now so full of pressing engagements and interests which alas,
often do not tend to spiritual enrichment.
Yet even among that membership there are, I trust,
those who are willing to postpone the claims of all lower interests,
to that knowledge of God which is more than burnt offering.

Those who are thoroughly in earnest after a first-hand knowledge
of Divine things cannot fail to ask themselves from time to time--

Is there an infallible way of seeking God which shall be absolutely
satisfactory to my needs and which yields in fruit all it promises?
Where is this way to be found which, finding me a man,
and as such exceedingly liable to error and delusion, will leave me more than a man,
a partaker of the Divine nature, and sitting with Christ in heavenly places,
not by mere figure of speech, but in measure of triumphant reality?
How can I go beyond words, to that which words faintly represent?
The answer to such questions is repeatedly found in Job Scott`'s writings,
and is mirrored in his own experience.

What he learned, he learned from the right Teacher in the depths;
from those depths he brought up stones of remembrance,
and in the depths he was prepared for the heights of Divine
consolation in a degree which makes his Journal an encouragement
to enter on the same path of following Christ in spirit.
At the close of his life he could confidently say--"`I think I have not,
for several years past, known much, or anything, of boasting;
I have known something of that law of grace, whereby all boasting is entirely excluded;
but I may say,
through that which has supported me under all the trials
and conflicts which have attended me through life,
to you, my beloved friends, as to dear children, Follow me,
as I have endeavoured to follow Christ Jesus, the Lord of life and glory,
and the rock of my eternal salvation.`"

In order to present the subjects treated on more readily to the reader`'s attention,
the matter, instead of being shaped as a continuous narrative,
is divided up under a number of headings appropriate to some fact,
or expression contained in the context.
