== Chapter I

[.letter-heading]
To Phebe Field, Gloucester.

[.signed-section-context-open]
Providence, 30th of 10th month, 1774.

[.salutation]
Respected friend,

By this opportunity I may just inform you, that since I last saw you,
I have often had to remember you, with earnest desires for your everlasting welfare,
and that you may be favored with strength, willingness,
and engagement in the depth of humility, to follow the light, wheresoever it leads.
And Oh! that the things of this world may not hinder your advancement heavenward.
The danger is so great, that I believe many well-meaning persons,
not knowing or thinking themselves in any very imminent danger,
have thereby been entangled in that which has made a lamentable
separation between God and their precious souls.
But I heartily wish you may escape this, and all other enchanting things,
and be preserved through all difficulties,
and through the tribulations which all those must endure,
whose garments are washed and made white in the blood (the life) of the lamb.

Think not, my friend, that your trials are harder than others.
The path which our blessed leader trod to glory,
and in which all must follow him that will be his,
was such as made him "`a man of sorrows, and acquainted with grief.`"
And if you feel poverty, and lack, and sorrow, murmur not, nor think it strange.
The Lord knows what is best for you, and that he will deal out to you.
You must expect he will lead you in the way he has led the rest of his flock.
And you may depend on him, that when he has sufficiently humbled you,
and you are made willing to give up all, and serve him in truth and integrity,
he "`will give you beauty for ashes, the oil of joy for mourning,
and the garment of praise for the spirit of heaviness,`" and he will be "`your shield,
and your exceedingly great reward.`"
So to him I commend you, hoping you will serve him faithfully,
and gain an admittance into his kingdom of glory,
there to rejoice in beholding his face forevermore.
So wishes your sincere friend,

[.signed-section-signature]
Job Scott.

[.letter-heading]
To a Friend

Feeling, in the aboundings of my Heavenly Father`'s love,
a renewed and earnest engagement for the eternal welfare
of that part in you which must endure beyond the grave,
I am inclined to acquaint you with the travail of my soul, and breathings of my spirit,
to the eternal Fountain of all good, on your account.
For, indeed, the consideration of your state, has, at times, drawn tears from my eyes,
while the desire of my heart has been, that you might come to know,
in this the day of your visitation, the things that belong to your peace;
before they may be hid from your eyes.
Oh! that you knew how to prize the unspeakable favor,
vouchsafed to you in this tender visitation,
and would improve it to the glory of him who has called you,
and to the salvation of your own soul.

But, alas! while I have been contemplating the merciful kindness of a long-suffering God,
and those ravishing delights, which nothing but disobedience deprives you of,
I have had to view the many difficulties and discouragements, yes, and the allurements,
with which the adversary of all good,
disturbs and confuses the minds of such as are desirous of travelling out of his territories,
and of being redeemed from under his dominion.
When I have thought on these things, a fear has possessed my mind, lest,
for lack of a thorough resignation, the enemy should prove too hard for you.
But when I have considered the unlimited power of him who inhabits eternity,
and dwells in the light, and who is able to remove mountains, and divide the seas,
I have had a secret hope that by his unremitted strivings,
he would prevail with you to forsake all, and follow him;
to come out and be separate from, and not touch the unclean thing;
that so he might receive you.

Oh! how I have lamented and mourned,
to see the unhappy condition of many of the visited of our God, who,
notwithstanding the holy call,
are not willing to desist from partaking of the unclean thing,
with the children of a dissipated age.
Be not offended at the sorrows I have felt on account of the captivity of those,
whose happiness I greatly desire: but bow down your ear and hear,
and obey the voice of him, who comes not to bring peace on the earthly mind, but a sword.
Submit your neck to his yoke, and your shoulders to his cross.
Allow the operation of his refining fire, and purifying soap.
Dwell under the discipline of his holy rod; and learn to give up your whole heart to him,
and to esteem his reproach, greater riches than the treasures of Egypt,
having respect unto the recompense of reward; remembering,
that if you love anything more than Christ, you are not worthy of him,
according to his own doctrine.
Therefore, consult not with flesh and blood,
neither stand gazing at the hardness of the way;
but cast your care upon him who has called you; and give up to his call.
He will enable you to answer the requirings thereof,
and to run the way of his commandments with delight.
But if you look at this, that, and the other difficulty,
and go to reasoning against the conviction in your own mind,
you will thereby drown its voice, and run yourself into confusion, and perhaps,
lose all sense of truth.

Oh! arise, arise! and trim your lamp, and provide therein the oil of the kingdom,
by standing open to receive from him who is ready to communicate, but in his own way,
the way of the cross.
Have you not stood dallying long enough to know, that _that_ will never do the work?
If so, I beseech you, now, at length,
be engaged to work out your salvation with fear and trembling;
for it is God that works in you; and would, did you but cleave close to his workings,
work both the will and the deed, but not without your consent:
for you must be a coworker with him, if ever you know a resting in and with him.
Oh!
I entreat you, do not overlook the way and means, yes,
the only way and means which he ever has offered, or ever will offer you; which are,
"`the reproofs of instruction, the way of life.`"
If you could live and employ a thousand years in search of another way,
you might search in vain.
And at last, if ever you know salvation,
you must know it by the same stumbling stone and rock of offense; through which,
(but for lack of belief therein, and obedience thereto,) you and thousands more might,
in a short time, come to witness peace to flow as a river.
This is he who has been the dwelling place of the righteous in all ages.
And, blessed be his name, he is so to a remnant in this age;
and Oh! that the number may be increased, of those who take sanctuary in him.
"`The name of the Lord is a strong tower; the righteous run to it and are safe.`"

And now, my beloved friend, let me prevail upon you,
to attend to this most important concern; and give not sleep to your eyes,
nor slumber to your eyelids,
until you have prepared a habitation for the God of Jacob to dwell in;
and are united to him in a covenant of everlasting righteousness and peace.
Which happy state I ardently desire you may attain to,
and thus rejoice upon the banks of deliverance,
with those to whom it is given to rejoice,
even those who have come through great tribulation.
Oh! that I could paint in your view that unspeakable consolation
which I so much desire you may partake of:
but language cannot describe it,
therefore I recommend you to the protection of that all-powerful arm, which,
as you rely thereon, will be underneath and sustain you;
and which I hope you will not distrust, flee from, or forsake:
but seek after a more intimate acquaintance with,
and continue your seeking until you find it;
that so you may be prepared to enter the mansions of glory,
to celebrate the praise of him who is now patiently waiting to be gracious unto you.

[.signed-section-closing]
I am your sincere friend and well-wisher,

[.signed-section-signature]
Job Scott.

[.letter-heading]
To Mary Callender

[.signed-section-context-open]
Providence, 12th of 12th month, 1775.

[.salutation]
Esteemed friend,

It is in my mind, I believe in a degree of gospel love, to let you understand,
that since I saw you last, I have sometimes had to consider the many difficulties,
which I believe have attended, and which will, if faithful,
attend your progress through this scene of sorrows and vale of tears.
For I have often thought it had fallen to your lot to be engaged in a work truly laborious,
and deeply exercising,
and it is my earnest desire that you may be preserved through and over all,
to the glory of God and your own abundant joy and consolation.

And my friend,
I have thought you had need to guard against the adversary`'s taking advantage,
in low times, to cast you under undue discouragements.
For although I am deeply sensible, that the safest dwelling place is in the low valleys,
which are often clothed with verdant greenness,
while the exalted mountains are covered with dismal barrenness;
yet there are extremes each way: for, no doubt, you have observed some holes so sunken,
as to produce no pleasant plant nor fruitful vine, but seem to wear a horrible aspect,
and are ofttimes an asylum or harbour for the serpentine brood and reptile offspring.
Therefore, let us endeavor to dwell in the medium, out of all extremes; and bear up,
as much as possible,
under the various afflictive dispensations that it
may please Divine Wisdom to lead us through.
And thus, as there is an abiding in the faith and patience of the saints,
I believe that he who has been with his people in six troubles,
will not leave them in the seventh,
but will preserve and protect them even through the valley of the shadow of death;
until he brings them into the full fruition and enjoyment of those blissful mansions,
where uninterrupted hosannas, and high praises,
will resound throughout the unlimited habitations of God, angels, and holy men.

My kind love is to yourself, and J. J., with all my friends at Newport,
not forgetting that tender plant, M. R., whose eternal welfare I much desire;
and hope your watchful care over her for good, will not be defficient,

[.signed-section-closing]
From your assured friend,

[.signed-section-signature]
Job Scott.

[.letter-heading]
Part of a Letter to a Friend

[.salutation]
My friend,

Feeling at this time a near sympathy with you, I find my mind engaged for your good,
and therein a freedom to communicate a little of my own experience,
hoping it may not be unprofitable to you.
When first I gave up to turn my mind from the world,
and to seek a resting place for my distressed soul, I found,
as I attended to the reproofs of instruction, that such things were required of me,
as were in my weak apprehension, as bitter as death.
Oh! said I in myself, must my life, from my youth, be a life of self-denial,
and I myself a laughing stock for those that have been my pleasant companions!
Lord, excuse me in those despisable things which you require of me;
and let me walk sociably and amicably among mankind;
and I will serve you in the secret of my soul,
if it be through tribulation and distress.

But alas! this sort of reasoning found no acceptance.
It was not for me to make a sacrifice of that which the Lord called not for,
and withhold that which he required.
For, says the prophet, "`With what shall I come before the Lord,
and bow myself before the high God?
Shall I come before him with burnt-offerings, with calves of a year old?
Will the Lord be pleased with thousands of rams, or with ten thousands of rivers of oil?
Shall I give my first-born for my transgression,
the fruit of my body for the sin of my soul?`"
No, no.
This is not the way, but "`He has showed you, O man,`" (and woman too,) "`what is good;
and what does the Lord your God require of you, but to do justly, and to love mercy,
and to walk humbly with your God?`"
Which can be performed no other way, but by yielding obedience to his requirings.
For when the Lord has showed what his will is,
how can we either "`do justly,`" "`love mercy,`" or "`walk humbly,`" without doing it?

Come, my friend, with whom my spirit sympathized, come,
give up yourself to the will and service of him who made you;
and whose desire is to make you happy forevermore.
Only lose your life, and you shall find it.
But if you will save your life, you must lose it; which I hope will not be your lot.
Think nothing too near, or too dear to part with,
in order to prepare a habitation for the God of Jacob to dwell in.
Why do you regard what men, or the sons of men, may think or say of you,
if you can have a dwelling place in the love of God?
"`Fear not the reproach of men,
neither be afraid of their revilings,`" said the holy prophet Isaiah.
No doubt, he knew, by blessed experience, that the scorn and contempt of mortals,
were not worth regarding, in comparison with the favor of God.
And Moses learned to "`choose rather to suffer affliction with the people of God,
than to enjoy the pleasures of sin for a season; esteeming the reproaches of Christ,
greater riches than the treasures of Egypt.`"
Do so, my friend, and give up your whole heart to serve the Lord,
and he will preserve you.
Remember that comfortable language,
applicable to such who are as worms in their own eyes, "`Fear not, you worm Jacob,
I will help you,`" "`I will not leave you nor forsake you.`"
"`When you pass through the waters, I will be with you; and through the rivers,
they shall not overflow you; when you walk through the fire, you shall not be burnt,
neither shall the flame kindle upon you.`"

To return to my own experience, I remember the language of my distressed soul,
in the days of my great exercise.
After I gave up to become a fool, and to put my mouth in the dust,
and be as clay in the hand of the potter, my daily cry was, Lord, cleanse me thoroughly,
in body, soul, and spirit, and if there be iniquity in me, do it away.
Purify me, Lord, purify me; and let not your hand spare, for my crying,
until you cause me to come forth as gold seven times tried in the fire.
If you love me, chastise me; for whoever you love, you also chastise.
Lord, chasten me, and purge away all my dross;
that no wrong thing may find even so much as a secret lurking place in my breast.
But make me wholly yours.
Make me a son, that I may cry, Abba, Father.

This, my friend, I well remember to have been my language day after day,
in the bitterness of my soul,
when mourning and lamentation were my almost constant companions;
when my nights were spent in sorrow and crying,
and my days in walking solitarily in the woods, and seeking after my beloved.
Oh! the depth of my anxiety and distress was far beyond
the ability of my tongue or pen to set forth to the full.
But my heart is filled with gratitude when I remember it,
and consider the wonderful goodness of my Heavenly Master, in thus humbling me,
and making me in some degree,
fit to receive the good things which he had in store for me; and which,
blessed be his name, he did not fail to communicate,
as I abode under his chastising hand; but, to my unspeakable consolation,
he caused the light of his countenance to shine upon me, and support me;
whereby I have been enabled to press forward toward the
mark of the prize of the high calling of God in Christ Jesus.
And now, my beloved friend, let me invite you,
in the good will of him that dwelt in the bush,
to give up everything that stands in the way of your peace,
even though comparable to a right hand, or right eye.

[.signed-section-signature]
Job Scott.

[.letter-heading]
To Lydia Tillinghast

[.signed-section-context-open]
Providence, 20th of 4th month, 1777.

[.salutation]
Respected friend,

I have often had to think of you for some time past,
and under the consideration of circumstances, which have,
and do attend your pilgrimage here below, do I at this time, put pen to paper,
in order to communicate to you a little of what I have felt on your account,
and necessary for you.
I have believed, without doubling,
(as I believe many more have,) that your heart has
been wrought upon by that divine finger,
which, as it is permitted to operate, not only gives to taste of God`'s salvation,
but enables the mind to bear up, under the most discouraging circumstances, and will,
in the end, most certainly give admittance into the New Jerusalem above,
where the smiles of Zion`'s King will abundantly outweigh all the
difficulties and hardships that are known in this vale of tears.

Now, my friend, as, through the mercy of God,
I have had some little experience of the wiles and
mysterious workings of the adversary of souls;
and also have known a being preserved from being destroyed by his wicked designs;
and as I have no doubt that he is at times busying
himself in laying snares for your immortal soul,
to cause you to fall short of the prize which is at the end of the race,
and to be received by those only who hold out to the end, and faint not by the way;
I earnestly desire that you may be preserved in the innocent
life of pure and undefiled truth and righteousness,
wherein, as you abide, you will be enabled to see,
and avoid all the snares of the wicked one,
however subtilely he may lay them to catch the unwary.

Sometimes, perhaps, he may persuade you, that there is no true religion among a people,
who are so precise about outward things, as it may seem to you, that some are.
This is a kind of reasoning, whereby he has stumbled many, and some well-minded persons.
Oh! be on your guard against it.
Remember you have yet had but a small experience of what may be required.
And although some things which others clearly see the necessity of,
may not yet be made so clear to you, yet the same power which has shown you some things,
can show you many more, if he pleases.
Therefore, be careful, and not be too hasty in judging that things are unnecessary,
because you have not yet seen them; or else,
you may condemn the living experience of many who have known far more of the love of God,
and of his requirings, than yourself.

And now in particular, respecting rising, or not rising,
to join the prayers of those who can appoint a time to preach and pray,
and go to the place, and begin immediately, without waiting for any help from above;
if I may be allowed to have any knowledge of the will and ways of the great Teacher,
I must say,
I have as sensibly been constrained to bear testimony against such will-worship,
as against almost anything else,
though I believe some have not fully seen into the
spiritual idolatry of such preaching and praying.
Will it sound harsh to you,
if I say I am confirmed it is offensive to him who will
be waited upon by all who truly worship him aright?
Indeed, let it sound as it may,
I am fully satisfied that a great part of that kind
of devotion is no better than solemn mockery,
and no more acceptable with God, than worshipping images.
For when a person imagines something or another,
without knowing whether it be right or wrong, good or bad,
what is that but an image in the mind?
Indeed, they have imagined so many abominations,
that it is enough to make any sober inquirer afraid to trust to anything they say,
without knowing it to be true.
For, alas! what have they not preached, in one age or another, as gospel truths?
Indeed, the very worst of blasphemies.
And all this for lack of waiting for the commission
and command of him who knows what is truth,
and ought to be said.
And even in our days, they proclaim from the pulpit,
things absolutely contrary to the doctrines of Christ.
Who would have thought, that after Christ had so fully forbidden revenge and war,
and commanded to love enemies, any should dare pretend to be a preacher of the gospel,
and yet preach up these things which Christ forbid.
Surely this is for lack of knowing, and waiting to hear the Shepherd`'s voice.
Another abominable doctrine is this:
that God has ordained millions of immortal souls to everlasting misery;
with many other false doctrines, under pretense of God`'s mind and will.

Oh! lamentable! lamentable! my eyes have seen so much of the nature of such work,
that I dare not in the least give it any countenance.
My conscience would condemn me, if I should;
and yet I have charity to believe there are some among them, and some who join them,
that are sincere, and act according to what they know;
but that is no excuse for those who have seen the nature of these things.
The prophets of old cried, "`woe,`" against such will-worshippers,
and the "`woe`" still remains.
And shall those who know it does,
stifle the testimony which ought to be borne against such practices.
He that joins, may be numbered among those who bid them God speed;
which an apostle forbids.
See the second Epistle of John, ver. 10.

Now, my friend, think it not strange,
that I am thus severe against this sort of preaching.
I believe many who once would have thought this hard judging,
are now fully convinced that it is strictly true; and you may yet think so too, in time,
though now it may be hid from you.
Keep near him who has the key of David; who opens, and none can shut, and shuts,
and none can open.
Have a care of carnal reasoning about spiritual matters;
they are not to be understood without the help of that key.
Think not hard of those who are desirous that you
should be rightly brought forward on your way;
lest you think hard of your best friends.
For be assured, there are some who heartily wish your present and everlasting happiness;
of which number I am one,
and one who is not a little concerned that you may be kept in patience, humility,
and tenderness, through all trials that may attend you here,
and dwell forever with the Lamb and his followers, hereafter.
Farewell.

[.signed-section-signature]
Job Scott.

[.letter-heading]
To William Turpin

[.signed-section-context-open]
Providence, 20th of 9th month, 1778.

[.salutation]
My dear friend, William Turpin,

As I may not see your face so often as before,
I feel an engagement to communicate something of the desires
that have often attended my mind on your account.
I have desired that into whatever corner of the earth your course may be steered,
it may be your constant and careful engagement to labor for the bread that perishes not,
and the waters that endure.
Be it your peculiar care to strive to enter in at the strait gate.
Be it your unremitted solicitude of mind to witness
communion with the God who gives you life,
breath, and being.
This cannot be fully known but through the wrestlings of the seed,
in the silence of all flesh;
every roving thought and idle imagination being subjected
to the obedience of the cross of Christ.
Then, when this is known, "`Spring up, O well;
all of you sing unto it,`" will be understood by
your poor (and otherwise miserable) soul.

If you will reign with Christ, you must suffer with him.
"`No cross, no crown,`" are words of truth and righteousness.
And I`'ll tell you what an ancient and experienced servant of Christ said,
a little before his departure from this scene of probation;
speaking of the Holy Spirit which he felt, he says,
"`It never rejoices but through suffering; for with the world`'s joy it is murdered.`"
Have a care, my dearly beloved, of "`the world`'s joys,`" the world`'s friendships.
Enmity with God is written upon them, and you can not erase it.
The worldly part, the changeable part, must die.
You must be buried with Christ, by baptism into death,
or have no part in the first resurrection.
Be not ashamed of the heart-tendering work of him who is, at times,
drawing near you for your refinement.
Bear his reproach.
Go with him to the cross, to Pilate, and the world.
Die with him to every other satisfaction,
than what arises from union and communion with him who was made perfect through sufferings.

This is close doctrine; but I can testify,
it leads to joys unspeakable that the world knows not of;
to a foretaste in this life of those rivers of pleasures which are at God`'s right hand.
Lose not sight, my friend, of the __light,__ your leader;
nor of the necessity of a life of self-denial, and the daily cross.
This I earnestly press, as the way to eternal glory:
it is the path the ancients ever trod to blessedness; by Jesus recommended,
as well as walked in.
Follow him in it, and your feet shall not slide, nor your recompense fail.

And now, with a heart full of goodwill, and not void of tenderness,
and sympathetic compassion,
wishing you the enjoyment of that presence which is life to the soul;
wishing you may lead a life of pilgrimage,
and be a standard-bearer through this scene of sorrows, this vale of tears;
and at last witness a happy admittance among the sons of consolation,
around the throne of God, I bid you farewell.
Forget not, by no means forget, that it must be through tribulation, if at all,
that your garments must be washed white, and you admitted to the joys I have mentioned.

I am your unfeigned, affectionate, unshaken friend, in the travail of my soul,
that Christ may be completely formed in you.

[.signed-section-signature]
Job Scott.

[.letter-heading]
To J. C.

[.signed-section-context-open]
Providence, 7th of 9th month, 1781.

[.salutation]
Respected cousin,

I have often had you in remembrance, since last I saw you,
and now believe it best to write the feelings of my mind;
and I desire to speak to that in you, which can savor words,
and which has long been visited, and yet continues long in bondage.
May I query, why is it so?
Dear cousin, why is it so?
Answer, because Pharaoh`'s heart is hardened,
so that he will not let the true Israelitish seed go forth to do sacrifice to the Lord,
the everlasting God.
Know that plagues and tribulations will attend that hardened heart, unless it submits.
And unless there is a giving up to the holy influence of that fire,
which burns as an oven, (inwardly,) your lot, I think,
will be to drag out a miserable life of emptiness and desolation of soul; when,
at the same time, I am as fully satisfied, that by a full surrender,
you might come to feed upon the bread of life, and drink of the new wine,
with Christ in his Father`'s kingdom.

I have been discouraged about writing; for, if you will not hearken to the voice within,
in vain might one rise even from the dead, to invite you.
Take this not as rough language.
It is in the breathings of my soul for your welfare,
that I am engaged thus to call upon you to make no longer delay,
lest the night overtake you; but improve the present time.
Now is the accepted time.
Now is the visitation continued.
How long before it may be too late, we know not.
Great is the consequence to your immortal soul.
Oh!
I entreat you stand out no longer.
Resist no longer the offers of God`'s lovingkindness to you!
What satisfaction can you have in the thoughts of spending all your days in thraldom,
in Egyptian bondage?
Or what reason have you to think it will ever be easier than now,
to make a full revolt from under the government of the king of tyrants?
Let your comrades laugh: and let deists argue as they please.
He who knows not the peace of God that passes mere human understanding,
notwithstanding all his wit, and all his cunning, is, as to the inward state of his soul,
in a land of emptiness,
famishing and starving for lack of that food which only nourishes to eternal life.
Farewell, says your true friend and cousin,

[.signed-section-signature]
Job Scott.

[.letter-heading]
To A. S.

[.signed-section-context-open]
Providence, 7th of 11th month, 1781.

[.salutation]
My young friend,

My view in writing, is to inform you,
that in the conversation I had with you on the subject of your going to dancing school,
I aimed at nothing but your good, and to discharge my duty to you in the sight of God,
as to one whose welfare I desired, and thought I ought to endeavor to promote.

Think not hard of me, my friend,
for the Lord knows I had no hardness in my heart toward you, but sought your good.
I would not have you shut your heart against the gentle movings of that holy principle,
in your own mind, which manifests what is right, and what is wrong,
and which justifies for doing the one, and reproves for the other;
but stand open to its teachings and influence.
And as you find this light to produce uneasiness in you for dancing,
and such like diversions, and misspent time, Oh! yield to its operation; that so,
by believing in the light, you may become a child of the light,
and of the everlasting day of God`'s salvation.

I can tell you, it was no small cross to me to deny myself the gratification of dancing,
and some other vain amusements of like nature.
But when I did give them up, Oh! the peace which flowed in my soul,
as I travelled on in the way of self-denial!
It was like the flowings of a gentle stream of joy unspeakable and full of glory.
And the wish I have for you, dear child,
is that you may witness in the secret of your own soul,
the flowings of the same celestial joy and consolation; which, if ever you do witness,
you will find it is in the way of the cross to your natural inclinations;
for the cross of Christ is the alone way to the crown of glory.

I know what I write,
and therein have the sanction of the word of truth in my own experience,
and also in the scriptures.
I am not speaking against dancing only.
I wish your redemption from all things that are contrary to the law of God,
and his unerring witness in your own soul.
And I am the more encouraged to this communication of counsel, from a belief I had,
while you were with me,
that your heart was far from that state of hardness and insensibility,
which I have discovered in some of your age.
I thought I perceived something tender in you,
that gave me to hope you might come to know the Lord for yourself,
and to your own comfort,
if nothing was permitted to divert your mind from a due
attention to that grace of God which brings salvation,
and which has appeared to you, and will if you hearken to it,
teach you to deny all ungodliness,
and to live soberly and godly in your day and generation.
With desires that this may be your happy experience,
and that you may receive these few lines as a token of unfeigned goodwill,
I bid you farewell, and am your friend,

[.signed-section-signature]
Job Scott.

[.letter-heading]
To his Wife, Eunice Scott

[.signed-section-context-open]
Smithfield, 11th month 10th, 1782.

[.salutation]
Dearly beloved wife,

I am now at Elisha Thornton`'s. It would seem pleasant to return to you,
and the lambs I left with you; but, as my mind is disposed at present,
I must desire you patiently to endure my absence,
and the toil of taking care of the babes, a little longer.
Think it not hard to render so small a sacrifice,
as to give me up to visit and sympathise with the many children from house to house,
who are at times, as it were, crying for bread, and have none to break it to them.
Farewell, says your truly loving husband,

[.signed-section-signature]
Job Scott.

[.letter-heading]
To Eunice Scott

[.signed-section-context-open]
Providence, 19th of 6th month, 1783.

[.salutation]
My dear wife,

Let it not grieve you, that a tender concern for the good of society,
and a due regard to the appointment of my brethren,
prevent my seeing you so soon as my inclination would dictate.
I expect to go to Ackoacset, Dartmouth, Nantucket, and Sandwich,
should nothing occur to prevent.
It is my earnest wish that you may be preserved in patience, with the children.
I hope I shall be enabled to give you all up rightly,
though warm affection rushes in upon me at the thoughts of so long an absence;
and the prospect of an exercising, laborious time in this visit, weighs heavy on my mind:
yet something overbalances it all,
and inspires a firm dependance on the Lord that reigns.
If we are faithful, he will provide for us,
as we feel a disposition to be willing to live upon a little.
May his holy hand hold you, and preserve you, till I come again, to enjoy your company.
Farewell, dear heart, says your affectionate husband,

[.signed-section-signature]
Job Scott

[.letter-heading]
To the Youth Among Friends, at Richmond, New Hampshire.

[.salutation]
Dear young friends,

It is nothing but a desire for your immortal souls`' eternal welfare,
that induces us to acquaint you with the deep anxiety of mind that we felt,
when closed up in silence, we went from house to house, among you.
Perhaps you may think lightly of the deep travail and distress of soul,
that the mourners in Zion pass through, on account of the careless, libertine,
and unsubjected disposition of too many of the youth and others; but be assured,
dear young people, that some have known and felt the day of the Lord to burn as an oven,
against such a disposition; have known his terrors for sin,
and his judgments and deep condemnation for transgression;
and therefore cannot but mourn over the giddy, wandering, incautious youth,
that are running headlong into that liberty, which is bondage to the true seed;
and which, even in the height of enjoyment, never did, and never can satisfy the soul.
For our Maker has so fashioned the immortal soul,
that nothing short of the enjoyment of his divine presence can satisfy it.
Earthly riches, honors, and pleasures, can no more satisfy the soul, even here on earth,
than the warmth of a candle can thaw the frozen mountains: for this is not our home;
and unless we live so in this world as to feel the presence of Him,
without whom we must be eternally miserable,
we shall as certainly be miserable here on earth also,
as the mountains will remain frozen, when once they are so,
till thawed by the rays of the sun.
For what can a little gold or silver, a little ease, or honor,
or a little short-lived carnal pleasure do toward the happiness of an immortal,
never-dying soul?
What can the company of the merry, and the gay, add to the real comfort of a spirit,
that is swiftly bound to the regions of endless eternity?
For God will bring every work into judgment; and render a reward according to our works;
according to the deeds done in the body, whether they be good or evil.

So that however the young man, and young woman, may think to rejoice in their youth,
and let their hearts cheer them in the days of their youth,
and walk in the ways of their own hearts, and in the sight of their own eyes;
yet let them know and remember,
that for all these things God will bring them into judgment.
Therefore, dear youth,
be persuaded to turn your backs upon all the allurements
and temptations of this wicked world,
now in season; for _now_ is the accepted time; now is the day of salvation; now,
the spirit of God is striving with you, for your reformation and salvation.
But if you go on in those gratifications and delights which grieve his Holy Spirit,
that thus strives with you, he may be disposed to give you up,
and leave you to your own corrupt inclinations;
for he has said that his spirit shall not always strive with man.
And Oh! how deplorable will be the case of those whom he forsakes!

The consideration of these things, ought seriously to impress all your minds,
now in your young years; for the longer you stand out,
the harder it will be to give up to the requirings of truth.
The cross is never easier borne, nor to better advantage, than in early youth;
and he that goes on in rebellion against all the precious
visitations which God bestows upon him in his youth,
most commonly grows hard and insensible in old age, and dies either in deep condemnation,
or gross insensibility.
Oh! may not this be your doleful end! but may you improve the present moments;
serve God with all your hearts; live soberly; love serious company;
keep close to Friends`' meetings, on first-days, and other days.
Keep to strict plainness, both in language and dress.
It is the way of the cross, and that is the way to the crown.
Christ himself loved plainness, and lived in it; and so do all his nearest followers.
Despise it not, dear friends, nor fear them that do despise it;
but in all things obey the dictates of the light,
that you may rest forever in a mansion of never-ending bliss.

"`Children obey your parents in the Lord.`"
This is an absolute duty and well pleasing to your Maker.
Therefore be obedient.
We are your real friends,

[.signed-section-signature]
Job Scott.

[.signed-section-signature]
Jaazaniah Barrett.

[.signed-section-context-close]
Uxbridge, 9th month 17th, 1783.

[.letter-heading]
To the Heads of Families, Both Men and Women Friends, at Richmond, New Hampshire

[.salutation]
Dear friends,

Having been for a considerable time under some degree of mournful exercise,
on the account of our so seldom having the company
of any Friends from your particular meeting,
at our meetings for discipline, we have of late had it under serious consideration,
especially since our late exercising visit among you, to write to you in brotherly love,
in order, if it may be, a little to stir up the pure mind among you:
and living desires for your everlasting welfare being felt at this time,
we hereby salute you, and in christian affection beseech you,
to stand open in your minds, individually, to receive the word of exhortation,
as at this time flowing from a real unfeigned desire and concern for your best interest;
earnestly wishing your hearts may be touched, as with a live coal from the holy altar,
and your spirits reanimated, and engaged to meet together with your exercised brethren,
to wait to feel the quickening influences of him,
who is "`the resurrection and the life;`" thereby to be enabled,
in true humility and awful reverence,
to worship aright before him who is the author of our being,
and to transact those important concerns which are
absolutely necessary in the church militant.

O Friends! may your minds be livingly impressed with a sense of the benefit,
the real benefit that is received by the truly exercised pilgrim, in being thus given up,
and in spirit devoted to the service of the Lord and of his people:
and may you understandingly contemplate, and solemnly ponder in your hearts, the real,
substantial enjoyments, that are therein witnessed by Zion`'s true travelers,
the exercised laborers in the Master`'s vineyard.
But, alas! it is a mournful truth,
what a worthy ancient of our society expressed in days past:
"`Whatsoever is not experiential is disputable.`"
For, if we dwell in an unconcerned state,
and do not feelingly experience the reality of these things,
we are liable to grow more and more insensible respecting them, till, at length,
when we hear of them, we may consider them as imaginary, delusive, and unsubstantial;
and may look upon that lively zeal and engagement
which ought ever to accompany the mind of a Christian,
for the support of good order in the church, as a following of cunningly devised fables.
May your minds be more ennobled,
and your spirits baptized into a deep feeling of the necessity of these things,
now in season; for this is your time, your day and opportunity, which, when once gone,
is gone forever, no more to be recalled.
Therefore, dear friends, "`today, if you will hear his voice,
harden not your hearts,`" but give up to his service.
Walk circumspectly before him in all your conduct and conversation,
remembering your time is short, and your adversary, the devil,
is continually seeking whom he may devour.

Oh! how needful it is to be sober and vigilant; as often as may be,
gathering together unto one place, to wait and worship together,
and sympathize with one another,
witnessing "`how good and how pleasant it is for
brethren to dwell together in unity;`" true,
inward, heartfelt unity.
Indeed, it is like the ointment that is poured upon the crown of the head,
and descends to the skirts of the garment.
Here it is that, "`as iron sharpens iron, so does the countenance of a man his friend.`"
And you may observe in the outward, in regard to a natural fire,
if the wood or brands are separated, and kept asunder, the fire goes out,
and neither light nor heat is longer preserved in them;
and instead of being bright and shining, blackness and darkness ensue among them: but,
when put properly together, although the fire may be almost gone out in each stick,
brand, and coal, how soon they begin to collect strength, and increase light and heat.
Indeed, although there may not be a single spark of fire remaining among them,
(which we trust is not your case,) yet, if put in a proper position, and due nearness,
and then a live coal be put among them,
how soon will the breath of the outward air enkindle the lire among them?
How will it catch and pass from one to another, among the brands and wood,
till a great flame is produced; and great heat, light,
and shining brightness are the consequence;
whereby even persons and things at a considerable distance receive an influence,
and are warmed, and even thawed by it.

So also is it in a spiritual sense; experience has taught and confirmed it.
Religious people, by neglecting to assemble together, grow cold and dim.
Love decreases, both to God, and one another.
Indifference and lukewarmness take place,
and the fire of true devotion is gradually extinguished.
This is found to hold good, in a great degree,
as to the neglect of meetings for church discipline.
But by rightly gathering together, and waiting to witness the live coal from the altar,
they are often, by the breath of life breathing upon them, re-enkindled.
Heat, light, and heart-tendering love and affection are increased among them.
A lively, yet well-tempered zeal,
for the maintenance of that lovely order and regularity which the gospel requires,
prevails in their minds; and, by the lively exercise of their spirits,
those who are afar off from a living acquaintance with these things,
by coming and sitting among them, and observing the weightiness of their spirits,
and the brightness of their examples, are sometimes benefited,
and enabled to glorify God in the day of their visitation.

Come, dear friends;
though we are sensible there is too little of this holy flame of light and life among us,
yet let us press forward in good earnest, and we shall find that he that made us,
will not fail to favor us with his life-giving presence, to our unspeakable consolation,
uniting us in the bonds of christian fellowship, and celestial endearment.
And then, Oh! how shall we be often drawn together, by those cords of love,
which are ever strong in proportion to our engagement to serve God in our day and generation.

We observed with sorrow, that too many of the dear youth among you,
were too unlike what truth and our christian testimony require,
both in their outward appearance, and the disposition of their minds;
and sensibly perceived that your hands were, by some means or other,
very weak in regard to laboring for a reformation in your own,
or one another`'s families; and perhaps your minds are almost discouraged.
It is our real desire that you may be strengthened and encouraged
to arise in the little might that may be afforded,
and endeavor to repair the waste places, and build the decayed walls;
not only everyone in, or against his or her own house,
but also to assist one another in an earnest labor,
to make a stand against the further outgoings of your tender offspring,
as well as to seek and labor with them for an amendment, and return to the true fold,
and to an orderly conduct and conversation.

Great need, yes, very great need there is, for such a united, as well as individual labor.
Be encouraged, dear friends, to enter into it.
And may you feel an openness and nearness to receive,
and unite with the labors of each other, in so good a work.
Guard against prejudice with all your power.
But yet where you see one another really in a fault,
admonish the offender in fear and meekness;
and let none among you be above the kind admonition and rebukes of a friend.
Let the time past suffice, and endeavor now to press forward;
striving to redeem the time; for indeed, much needs redeeming,
that has not been spent to the best advantage.
Yet, peradventure,
you may still be favored to do much more for the good and preservation
of those tender lambs left in your care in the wilderness of this vain,
tempting, alluring world, than you can at present believe.
And, in order that they may know our concern for them, and be stirred up,
we have written particularly to them;
supposing it might not be best for them to see or hear some parts of the above,
which more immediately concerns you, their parents, to consider.
We desire they may hear that to them, read in a solemn manner,
or at least have the perusal of it.

Such Friends among you, as the Monthly Meeting sees fit to appoint as overseers,
we hope you will receive in the love of Christ; not considering them,
in the faithful discharge of the trust reposed in them, as lords over God`'s heritage,
but as fellow-helpers and laborers in his vineyard.
Don`'t fail, dear friends, to come, to our Monthly Meeting,
as often as may be convenient; it may add to your peace in a dying hour.
Don`'t forget the dear youth.
Don`'t neglect them.
They greatly need some kind assistance.

[.signed-section-closing]
We rest your assured friends,

[.signed-section-signature]
Job Scott

[.signed-section-signature]
Jaazaniah Barrett

[.signed-section-context-close]
Uxbridge, the 19th of the 9th month, 1783.

[.letter-heading]
To Joseph Mosher, White Creek

[.signed-section-context-open]
Gloucester, 1st of 1st month, 1784.

[.salutation]
Dear friend, Joseph Mosher,

I almost steal these few moments, to sketch to your view,
the feeling remembrance which dwells in my heart,
of that endeared sweetness and fellowship which we have
felt with each other in that which is within the veil.
This sweet communion, my beloved friend, is of such a nature,
that though we are separated, I trust we are not separated.
I do not doubt you can reconcile this contradiction,
and feelingly understand the paradox;
for I know you have had an acquaintance with the key that opens.
May we both prize this acquaintance, and endeavor to have it increased.
May we, indeed, ever keep our eye to the key-hole, watch the turning of the key; and,
whether our outward affairs are adverse or prosperous, let us, above all things,
prize the love of God shed abroad in our souls; and, next to this,
the endeared love of living brethren.
Thus shall we resemble the inhabitants of that place, to which we wish to go.

But I did not mean exhortation, when I sat down to write;
but just to convey to your mind,
a little of that which I have often felt since we parted last; and may just add,
that after all my painful conflicts in your land, the satisfaction I felt,
the day I bent my course for home, on looking back and over the visit made,
was truly beyond my present ability to describe, and I trust,
will leave a lasting seal on my mind.
It seemed as if the heavenly hosts hovered over me, for many miles on the way,
so that tears of joy flowed irresistibly, like a river.
I was not fit for any conversation for a dozen miles, but rode alone, mostly behind.
And Oh! the heart-heaving emotions which I felt towards
many whom I had seen in your western world!
Oh! the cries which ascended for your preservation!
How often did this language run powerfully through my mind:
"`You that keep watch in heaven, watch over them.`"
But I must not lavish away too much of that ecstatic, rapturous enjoyment, I then felt.
Indeed, I have mostly since, been as poor as I was then rich;
and almost wholly shut up in silence.
Well, every dispensation, if well improved, helps on the work.
May they be patiently endured.

Friends are generally well, and some love Zion yet, and some the world.
My endeared love is to your wife.
Let her take a share of the above salutation.
She is near in my remembrance.
May she press forward.
I`'ve also much love for the children.
Dear lambs, seek and serve the God of your father;
and he will adorn you with a heavenly beauty, superior to all earthly enjoyments.
My wife joins in loving remembrance, and would be glad to see you.
A line would be very acceptable to your affectionate,

[.signed-section-signature]
Job Scott.

[.letter-heading]
To James Mott, Mamaroneck

[.signed-section-context-open]
Amawalk, 2nd of 8th month, 1784.

[.salutation]
Dear friend,

Something having endeared you to my mind while lately together,
I feel a freedom to inform you,
that notwithstanding the depth of my exercise at Purchase, yesterday,
and although I then thought I had some real openings, yet I obtained very little relief;
and doubtings have rather distressed my mind, whether anything I said,
was pertinent to any state present, and whether I had not better have been silent.

Alas! how am I tried on every hand!
Great distress of mind has attended my silent travail, from place to place:
but I think the apprehension of moving amiss, gives a more distressing sensation,
than silent suffering.
When shall I get right?
Or, must I be ever learning, and never able to come to the knowledge of the truth?
However, I must try to keep the word of patience: and, indeed,
sometimes almost all my consolation arises from the little degree thereof still retained.
I am ready to query, Can it be right for such a tossed,
unsettled creature to be so far from home, on a religious visit?
Surely if it is, and if this is anything like the path of the true messengers of Christ,
their trials and exercises must be greater than any other class of servants in his church.
Before I left my dear wife and family, I thought I felt enough to move in,
and undertake this visit; but am ready to think,
if I was now at home I should not have strength enough to leave it,
and yet I cannot look homewards with confidence of being in the way of my duty.
May the breathings of the faithful be to the Fountain of all strength and consolation,
that I may be enabled to stand so still as to see the way,
and witness the salvation of God.

[.signed-section-closing]
In endeared affection, I am your poor friend,

[.signed-section-signature]
Job Scott.

[.letter-heading]
To James Mott

[.signed-section-context-open]
Nine Partners, 6th month 11th, 1784.

[.salutation]
My dear friend,

I received your kind comfortable salutation, last evening, very much to my satisfaction,
having waded through deep waters of affliction, since I parted with you.
After writing to you I attended Amawalk meeting in silent heaviness.
After meeting, it kept increasing, till our kind friend Edward Hallock,
whom we found there, and John Griffin,
having encouraged me to continue with my companion over the North River, I set forward,
and when on the way, good old Edward`'s conversation, and relation of experiences,
a little quieted the raging of the waves;
though I had thought no man could say anything to relieve me.
So we got that night to David Sands`'s, and next day to meeting nearby,
where I was still bound as it were hand and foot; as also next day at New Marlborough.

Here I passed through an uncommon sensation, though almost without sensation;
my distress entirely forsaking me.
For having before got to the bottom of Jordan, as it were, and felt as much,
(for all I know,) as I could bear, and being at length, made to submit patiently to it,
in my humiliation, my judgment was taken away; but yet no joy nor consolation succeeded,
for my state was perfectly negative.
I felt neither joy nor sorrow, pain nor pleasure.
I knew neither good, nor evil; had no present evidence that good or evil ever existed,
or that there was anything in religion, save by remembrance;
and could willingly have gone directly home, had Daniel consented.
But is it not strange,
that I could feel entirely empty and destitute of all kind of food,
and yet feel no sense of hunger?
I suppose it was because all striving, willing, and wishing, was entirely done away,
and I was made content in my desolate condition.
And now, blessed be the hand that chastises, I have since been at Crum-Elbow, Creek,
and little Nine Partners,
in the overflowings of gospel love and divine consolation in each,
though a time of travail in the forepart of them.
Yesterday we were here at the select Preparative Meeting to pretty good satisfaction,
and I remain cheerful and happy.

As to my little testimony at Purchase, I have for several days,
been easy and satisfied that it might all be well, though when I wrote before,
I being under the very hour and power of darkness, as it were,
every suggestion of the doubtful kind, was like a fiery dart of the adversary;
but I hope the shield of faith will enable to resist them all,
and do believe those buffetings and trials, have worked to my good,
and to my unexpected enlargement.
Oh! how unsearchable are the Master`'s judgments,
and his ways past finding out by human investigation!
May I ever lie low before him, patiently endure his chastisements,
and cheerfully obey his commands.

With renewed feelings of affection,
and renewed wishes for your increase of spiritual health and salvation,
I conclude your constant friend and brother in the
sufferings and rejoicings of this our earthly pilgrimage,

[.signed-section-signature]
Job Scott

[.letter-heading]
To his Wife

[.signed-section-context-open]
Cornwall, 3rd of 8th month, 1784.

[.salutation]
Dear wife,

I am glad I can inform you that I am pretty well as to bodily health;
though my inward conflicts have, much of the time since I left you, been such,
as I can better acquaint you of when I am permitted to return to you, than to write here.
Daniel is comfortable, and goes on cheerfully, having some valuable service, I believe,
in nearly all the meetings; while poor I go bound as it were in fetters of iron,
silently bearing my burden in many of them.
The Lord only knows how and why.
However, I have at a few times, been very largely and unexpectedly comforted;
and I do not see but my being here is in wisdom.

We are very kindly received by Friends, from place to place; and in very low times,
some sympathizing words have been spoken by exercised pilgrims:
and though this doesn`'t often mend the matter as to me, yet it shows their kindness.
I have wondered how any that have gone out on such an errand,
could be proud and puffed up.
Surely, it must be, because they don`'t go down,
where some seem as if they cannot avoid going.
Oh! what an alteration must take place in my mind, from the present state thereof,
when I feel high-minded.
But, no doubt, abasement is best for me; and the greatest desire seems to be,
that I may be enabled to bear it as I ought, without quite sinking.
I have this confidence, however, that as my tribulations in Christ abound,
my consolations will much more abound: though I cannot at all times so fully believe it,
as at present.
My good wishes have often been wafted over the lands and waters that separate us,
for the welfare of yourself and the dear little babes,
as also of father and friends in general.
Mention my love to them as opportunity offers.
Accept this as a token of never-failing affection
from your constant friend and loving husband,

[.signed-section-signature]
Job Scott.

[.postscript]
====

P+++.+++ S.--Try to bear my absence patiently, that so our reward may not be lost,
and that we may meet again in fullness of affection.
Meanwhile I pray the Lord of hosts preserve and bless you and the family.

====

[.letter-heading]
To his Wife

[.signed-section-context-open]
Oblong, at Aaron Lancaster`'s, 8th month 17th, 1784.

[.salutation]
Dear wife,

I wrote you from David Sands`'s, over the North River, the 3rd of this month,
informing more particularly than time will now admit, of exercises deep and trying:
but I am at present very comfortable in mind,
having since then been unexpectedly favored, and made to rejoice through sufferings.
I wish you to bear my absence with patience; it may not be more than four or five weeks,
and I shall rejoice to return to you again, when peace of mind will admit.
I have no reason to doubt my being in the way of my duty at present,
and am owned by the Master therein, and also by his servants.
My dear love is ardent toward you and the dear babes.
May Israel`'s Shepherd be with and watch over you.
We expect soon to go northward, to Cloverick, and the new countries,
having been at all the meetings in Oblong and Nine-Partners, but one,
and that I must hasten to in a few minutes, and then, two Monthly Meetings,
and so away from these parts.
Farewell, says your constantly affectionate husband,

[.signed-section-signature]
Job Scott

[.letter-heading]
To his Wife

[.signed-section-context-open]
East-Hoosack, 8th month 29th, 1784.

[.salutation]
Dear wife,

I am at present in good health, and have been so, except a few days, since I left you.
I have written you twice, but have not heard a word from home till yesterday,
by father Anthony, who came into meeting very unexpectedly.
He was till after meeting as a messenger of death to my poor mind;
for I could not conceive what drew him here, unless to bring the sorrowful news of death,
or sickness nigh unto death.
Imagination soon strongly fixed on you, and Oh I how I felt!
I could scarcely keep my seat through the meeting,
and though I strove to put such fears away,
they would immediately return with piercing grief, as a reality.
I made out to sit through the meeting, I hope with a degree of decency,
but not without the loss of some tears.
Oh!
I hope it was a profitable season.
It taught me to feel the place you had in my heart, and to strive to give up all.

Before I rose from my seat, father told me you were all well lately.
And now, if you can feel the joy I felt,
I believe it will enable you to bear my absence a little longer, with patience,
which I dearly beseech you to strive for.
I often remember you with sincere desires for your preservation;
and also for your growth in the truth.
May the Heavenly Father watch over you and all of yours, by day and by night.
My love to all my dear friends.
Ups and downs attend me.
Heights and depths I witness:
the day of adversity being set over against the day of prosperity.
I hope I shall still be kept low and humble.
Farewell, farewell, my dear wife, says your rejoiced husband,
whose joy is great that he can yet call you his own.

[.signed-section-signature]
Job Scott

[.letter-heading]
To Joseph Mosher, White Creek

[.signed-section-context-open]
Gloucester, 27th of 5th month, 1785.

[.salutation]
My dear friend, Joseph Mosher,

Yours of the 16th of 1st month came duly to hand, and was truly acceptable,
and also refreshing.
I have often thought of writing to you since,
and have delayed it principally that I might know the right time, for, truly,
my time is not always ready.
But this morning,
(being our Monthly Meeting day,) I felt willing to try to sketch out some of my feelings,
having had to pass through proving seasons of late; wherein, after close exercises,
and deep dippings into painful poverty, I have various times had to see clearly,
and even been ready to cry out and say, "`his name that sat on him was _death,_
and _hell_ followed with him.`"

This, my dear friend, may possibly seem strange language,
though I am ready to think it may not to you; for I believe each exercised traveler,
who holds on his way, must know something of this within himself,
or else I think he will not witness the opening of the seven seals so
as to read and understand them in the lines of his own experience.
And confirmed I am, they may be, yes, and I think must be, thus witnessed;
and though this "`death`" and this "`hell,`" seem almost too much to endure at times,
yet the enlargement that follows is unspeakably comfortable,
when we come to see and feel, that he who leads us through all this for our good,
has possession and command of the very "`keys of death, and hell;`" and not only so,
but even of a truth to witness "`death, and hell too, to give up their dead.`"
Here opens a field of rejoicing, with glorious prospects, may I not say,
visions of light, even in the light of the Lamb, slain from the foundation of the world.
But though he surely was, and is slain, in a certain sense, whenever the world,
or worldly spirit, comes to have a foundation laid in the mind,
and to gain foot-hold and dominion there,
yet will he live and reign in every soul that bows to his sceptre.
For, though in a sense he was dead, yet to such he is known to be alive,
and that he lives forevermore; yes, more than that, for because he lives they live also,
and that in spite of death and hell, for death cannot hold him,
the grave cannot confine him.
He will, in rightly devoted souls, burst the bands of death, lead captivity captive, yes,
and, blessed be his name, he will give gifts unto men.

I don`'t know but I may enlarge too far,
seeing something at this time attends which makes words very easy to come at; so,
hoping you will read me in that love which plentifully flows towards you, your wife,
children, and many more in your land,
I`'ll turn to a subject which affected my mind when in your western parts,
as well as since; that is, so many Friends`' children not being members.
This I mourned about, and did believe it might in some degree be remedied,
were Friends rightly engaged to request the care of Friends for their children:
and why parents who desire to bring up their children in the way they should go,
can choose to omit it, is hard for me to conceive.
For though I know, the care of mere men, the simple sitting in meetings for discipline,
etc., cannot convert the soul, yet the care, advice, and oversight of real men of God,
the advantage of sitting in our meetings of church discipline,
where Truth`'s baptizing influence often attends
in a very instructive and preserving manner,
are such valuable blessings and privileges,
that I would not for all earth`'s treasures and enjoyments,
that my dear little babes were deprived of them.
I thought some well-minded Friends had let in a fear of disadvantage rather than advantage,
in their children`'s being members.
Oh! this, I am confirmed, is a mistaken apprehension, a very delusion; and that which,
even in the minds of goodly Friends, is almost ready to persuade them,
that a time will come, when there will be no more birth-right members,
(as this spirit is ready to call them,) and that _that_ will be a better time.
I greatly fear this is the very voice of the stranger
whom the sheep ought not to hearken to.
And if ever this language gathers the children, and those that suck the breast,
to the true fold, I am willing to be looked upon as one deceived.
No, verily; it will scatter, if I have any true sight about it at this time.

"`Let the little children come to me,
and forbid them not;`" bring them up "`in the nurture and admonition of the Lord.`"
Now this nurture, which means nourishment, nursing, and instruction,
is often administered in meetings of business, where the living members are, at times,
engaged in caution, counsel, and the admonition of the Lord.
Indeed, as often as our meetings for worship or discipline are as they ought to be,
so often Christ is there in the midst of us.
Oh! let the children to come there unto him, and forbid them not.
Why will parents eat their morsel alone, while the sea-monster draws forth the breast,
and gives suck to her young!
So long as our children behave well,
they ought to be allowed to have a right to partake with us in the favors
bestowed on our religious assembling together in a way of church care;
and to suppose there is nothing in those meetings,
nor in the care and advice which Friends bestow on their members, that tends to instruct,
strengthen, encourage, and preserve a tender youth,
would be a reflection highly reproachful and shameful to our poor society;
and if it were true, surely to exclude the tender offspring,
would not be the way to mend the matter,
but would rather tend to increase the abomination of desolation among us.

But this is not yet the case, as poor as our meetings are.
For, though our shortness may be great, and through our fault,
the meetings may sometimes be unhappily tinctured with something discouraging,
yet through his lovingkindness who still favors his people,
there are times when _that_ attends, and reigns in dominion in these meetings,
through which even men are enabled to baptize with the Holy Spirit.
Oh! the meetings!--the brokenness, contrition,
and fervency of devotion which attend these blessed seasons!
And Oh! what pity that one of the dear well-disposed youth
of our offspring should be deprived of such opportunities.
My soul, and all that is in me,
is moved with gratitude and thanksgiving to the great
Author of my existence and of every favor,
that my little lambs are at present in a way to enjoy,
as far and as fast as they are capable, these great privileges.

In much love, I remain, dear friend, a constant well-wisher to you and yours,
and to the prosperity of Zion`'s cause.

[.signed-section-signature]
Job Scott

[.letter-heading]
To his Wife

[.signed-section-context-open]
Westbury, (Long Island,) 7th month 28th, 1786.

[.salutation]
Dearly beloved,

That endeared affection which renders parting hard,
engages my pen thus early to endeavor a small supply of that satisfaction to your mind,
(and indeed my own too,) which each other`'s company, in a far greater degree, affords.
And at the same time that I own it to be not a little unpleasant to my own natural inclinations
to be thus separated from the dearest object of my affections here below,
I could wish to encourage you to bear my absence with that fortitude, patience,
and resignation, which becomes the importance of the occasion;
for had not a travailing engagement for the good of souls,
and the liberty of the captive, suffering seed, called me away,
I had not left you alone to struggle with the cares of our little flock; but,
as my engagements abroad, throw a double engagement on you at home, do, dear heart,
endeavor to acquit yourself worthily in the diligent watching over,
and guarding of those little ones, which our gracious Creator has given us,
not only as pledges of his love, but also as a field for labor and cultivation.
Be it your often concern, to seek to him for ability to perform the arduous task.
And in order to lend a little hand of help, I desire you to tell them,
that their father thinks much of them, though about two hundred miles from them.
Tell them, he wants them to be good little children, and to love one another.
Not to quarrel.
Not to lie; nor use any bad words: but to do as their mother bids them; read their books,
and keep out of all mischief; that when their poor father comes home again,
he may rejoice in his dear little babes, and in their good behavior.

O my dear wife! my heart yearns towards you and them,
with all the wishes of the husband and the father.
May the Lord my God, supply the place of both, till I "`come again rejoicing;`" and,
if it be his holy will, "`bringing sheaves of solid joy with me.`"
My dear love is to my poor old father; to Phebe; to Benedict, and all his family;
Daniel Aldrich; Jaazaniah; Elisha Thornton; William Bassett, James Smith, Israel Sabin,
and their families; with all my dear friends.
And if my dear sister Remember is with you, or comes to you,
my endeared remembrance extends affectionately to her.
May her mind be set on things above, and not on things uncertain and unsubstantial.
The same is my wish for our sister Ruth, and all our brothers and sisters.
If she is with you, let her know that though Remember was sent for,
yet she is not without a share of my affectionate remembrance and good wishes.
As occasion offers, convey my mention of love to sister Lapham, her husband, and children.

We got on to Long Island, on second-day, late at night, and pressed hard for Friends,
fifty miles the first day, on the Island; next day, got among brethren;
and without knowing of the Quarterly Meeting,
laid out so that we got to Westbury meeting the very
day the Quarterly Meeting was held there.
I may find time to write again from New York,
after attending a number of Meetings on this Island; so rest for the present,
your truly loving husband,

[.signed-section-signature]
Job Scott

[.letter-heading]
To his Wife

[.signed-section-context-open]
New York, 5th of 8th month, 1786.

[.salutation]
Dear wife,

We have now attended all the meetings belonging to this Quarter,
and expect to go very soon for Rahway, in Jersey.
The few first meetings, were times of much lowness.
The third, that is, at Oyster Bay, was the very depth and extremity of sufferings.
My distress, I thought,
was like a person almost starving to death for lack of nourishment.
Considerably more than two hours, my bands were in silence,
like the confinement of the grave, to one in whom life is still struggling.
I thought many hearts present were hard.
But at length the bands seemed in degree to burst asunder, and through a hard,
hammering exercise, a little relief was obtained.
Since which, more openness has been felt;
and as the place of dependence has not been forgotten,
some very comfortable degrees of heavenly light have shone around us.
May you, dearly beloved, participate therein at home, with the stuff,
and in the cares of the children and family;
for such were to divide the spoil with them that went to war, formerly;
and it may be so yet, through a right watchfulness.
And that this watch may ever be ours,
and that therein the Lord of hosts may watch over us, preserve and keep us,
is the fervent desire of your fervently loving husband,

[.signed-section-signature]
Job Scott.

[.letter-heading]
To Remember Anthony, Providence

[.signed-section-context-open]
New York, 8th month 5th, 1786.

[.salutation]
Dear sister,

An unworthy brother, feeling desirous of your welfare,
is willing to convey a small token of affectionate remembrance and goodwill,
wishing the one thing needful may so engage your attention,
that other things may not have an undue place in your heart.
One day, yes, one hour of divine favor, is better than all earthly joy.
Your poor brother knows what he says, by a degree of living experience;
and among other things has seen in this part of the world,
some who have foolishly and fondly stepped out of society, and thereby put themselves,
and their dear little children, out of the way of some precious enjoyments,
which are witnessed in the times of Zion`'s solemnities, by the youth and aged,
and even by the children.

You, dear sister, have had your spirit tendered at some such opportunities;
part with all else rather than part with such precious privileges.
Mourning has attended me on account of some who have too easily sold their birth-right.
Now, when they did so, they were, with Esau, faint, faint as to religious engagement;
but how long can a mess of pottage, purchased at so dear a rate,
be supposed to afford a supply of food and true satisfaction?
O, my dearly beloved! stumble not at the weakness of anyone, but press forward;
choose the Lord for your portion, the God of Jacob for the lot of your inheritance;
then will your bread be sure, and your water fail not; your joy will be like the rivers,
and your consolation like the flowing of the sea.
That this may be your happy choice and blessed experience,
is the hearty desire of your truly loving brother,

[.signed-section-signature]
Job Scott.

[.postscript]
====

P+++.+++ S.--Remember your dear sister, and the dear lambs I left in her bosom; be with them,
I desire you, as much as is convenient.
My love to father, mother, brothers, and sisters.
A line from you would be acceptable.

====

[.letter-heading]
To his Wife

[.signed-section-context-open]
Shrewsbury, East Jersey, 8th month 11th, 1786.

[.salutation]
Dear love,

This is my third letter, the first from Westbury, second from New York last seventh-day.
It does me some good, or gives some consolation,
to find so frequent opportunities to send you a token of heartfelt remembrance:
but much must not now be expected; for my chin has been just above water,
much of the time since my last.
Oh! who would wish to go on such an errand, that knows the tribulated path thereof,
if he might be excused?
However, joy comes in the morning: therefore,
I wish patience to have its perfect work in me; and may it in you too, dearly beloved.

My endeared love is first and foremost to the dear partner of my lot in life,
and to the dear babes I left under her watchful care.
Tell them, be good children;--their father says he wants them to be good children.
My love is also to my dear father; to Phebe; Benedict, his wife, and family;
with all my dear friends about you.
May none of them grow so fearful of that little innocent word, _zeal,_
as to let _ease_ crawl on upon them.
The lack of the one and the plenty of the other in this land,
makes many a heart-aching moment, to poor passing pilgrims among them.
I am more and more in love with __true zeal:__ and a Quaker must famish without it.
Dead formality and love of earth, have almost ruined our poor society.
Oh! that we might mount upwards! and,
Oh! that a diligent waiting for strength from above, to perform every duty,
may be witnessed by all my dear friends at Uxbridge,
who have yet a little zeal remaining.
And may it be especially the care of the mother, in regard to the children,
and of her bodily-absent, though in heart __often present,__
and feelingly affectionate husband,

[.signed-section-signature]
Job Scott

[.postscript]
====

P+++.+++ S.--My dear love to Remember, if with you.

====

[.letter-heading]
To his Wife

[.signed-section-context-open]
Burlington, 8th month 27th, 1786.

[.salutation]
My beloved,

I am now at Burlington, West Jersey, not many miles from Philadelphia,
but don`'t expect to go into that great city, before Yearly Meeting.
I am in good bodily health, and have been so,
except some trifling complaints of the head, etc.
This is my fourth letter to you.
Joseph is pretty well; has had three letters from his friends at Newport.
I have had not even one from any of mine.

My wadings have been much in the deeps of exercise and poverty; yet, through favor,
I have had several blessed and comfortable meetings.
After one of which, and that eminently favorable to my poor exercised mind,
an ancient Friend, almost worn out with age, namely, Joshua Thompson,
who was with Joseph Oxley at the first Yearly Meeting at Newport that I ever attended,
came to me with tears, and after very affectionately shaking hands,
asked if I had a wife; and finding I had, he said, "`I think I can truly say,
the love of my heart is with those who are freely given up,
to come up to the help of the Lord; and it is not only to them,
but also to their dear companions, who freely give them up.
And though yours is a stranger to me, yet my dear love is to her.`"
This was in great tenderness and sensibility.
Thus, my dearest, are the hearts of strangers made to sympathize with you, unknown,
and at a distance.
I hope patience may be richly your portion; and diligent perseverance your employment.
And though the small-pox is considerably in the city,
I trust to see your face again with joy and gladness;
but cannot say much about the time at present.
I should greatly rejoice to hear of your welfare,
not having heard a word since I left you.
Do tell Benedict, Jaazaniah, and Elisha, that I should take it very kind,
if they would now and then send a few lines to father Anthony, to forward to me,
informing of your state, as to health, resignation, and accommodation;
with the state of our dear babes, father, etc. with that of their own families,
and what else they have to impart.
And do, dear heart, try to let me have the satisfaction of a line from your own pen.
I much desire this favor.

I have lately had a very heart-tendering time,
in your being brought closely into my very affectionate contemplation,
in such a manner as rendered me almost unable to speak, for a little time;
though not with grief, but far the contrary.
Ardent were my wishes, that the guardian angel of the divine presence, might surround,
watch over, and preserve you.

[verse]
____
May Heaven`'s blest influence on thy heart be shed,
May angels waft sweet odours o`'er thy bed!
With angels`' food, my dear, mayst thou be fed,
And by the Truth, in truth`'s pure paths be led.

May truth`'s increase, so prosper in thy soul,
As that its growth may lead from goal to goal:
From state to state, progressive, mayst thou tread,
And more than gold '`twill crown thy husband`'s head.
____

My love is affectionately to the dear children, their grandfather; Phebe;
the rest of my dear friends, and above all, dearly beloved,
to her unto whom I subscribe myself an affectionate husband and well-wisher in the Lord,

[.signed-section-signature]
Job Scott
