== Introduction

Job Scott was descended on his father`'s side from
John Balliol and the early Kings of Scotland:
on his mother`'s side through the Arnolds of Monmouthshire, from Ynyr King of Gwent,
a territory which formerly comprised Monmouthshire and parts of Herefordshire and Glamorgan.
There are two Ynyrs known to history,
one belonging to the 6th century and one to about the 10th century;
his descent is probably traced from the latter.
The Scott family in the 16th century belonged to Scott`'s Hall in Kent.
Richard Scott emigrated to Boston in 1636 or 1637
and joined Roger Williams in laying out Providence,
Rhode Island.
He and his wife and daughter were among the first Friends of that Colony.

It was at Providence, Rhode Island,
that Job Scott was born in 1751. His father, John Scott,
does not appear to have been conspicuous as a religious character.
Of the mother, Lydia Scott,
Job says that she was "`more zealous and attended
Friends meetings when she conveniently could,
and would also gather her children about her,
and sit in solemn silence before the Lord.`"
Although her son was but ten years of age when she died,
and had not come to understand the meaning of this silent waiting,
he believed it to have been of real advantage to him,
and strongly advocated such a practice for parents,
and those who have the care of children.

Before attaining the age of ten we shall see that the workings of Truth--the
light and grace of Christ were powerful on his youthful mind.
As years advanced, the allurements of the world came in like a flood,
the light was rejected, and gay company sought after.

The following pages vividly portray the vicissitudes of Job`'s early experience;
the thirst for pleasure on the one hand, the thirst for God on the other;
the building up of a Babel of false confidences, and erroneous doctrines,
and then a yielding to the Spirit of Grace,
and a learning to wait on and draw earnestly near to the Lord,
who had so long waited to be gracious.

Just as ardently as the wayward youth had pursued pleasure,
did he now seek the Author of his being in profound reverential silence,
even when his approaches seemed in vain, and his supplications unheard:
"`You did hide your face from me for a season,
until the longings of my soul after you were intensely kindled,
then you lifted up my head and spoke comfortably to me;
blessed be your holy Name forever.`"
These are his own words; he submitted to inward chastisement,
and he was given a song of victory.

That portion of the Journal which refers to these early
trials and exercises is deeply instructive and weighty.
He was led to see not merely that "`religion is an internal life in the soul,
that great attention,
sincerity and punctuality are necessary to the growth and prosperity of it:
that thoughts, words, and actions, must be brought to judgment,
and nothing allowed to pass unexamined or willingly unapproved:
that the most upright honesty and sincerity in my dealings
among men must be observed as in the presence of God,
the witness of all my outward actions, and inward volitions.`"

He saw further that the leaven of the Kingdom working from within,
was to govern the outward life.
Dress, food, house, furniture, language,
all were to pass under the measuring line of Truth,
for the Spirit of Truth is given first as a reprover for sin,
then as a guide into all Truth.
He convinces the world of sin, of righteousness, of judgment:
none entirely escape that convincement, though many turn from it,
and are unwilling to obey it.
Job Scott, the former gay youth of the world and would-be atheist was faithful;
he submitted to judgment, inwardly revealed, turned, repented and lived,
so that his one concern now was to experience the living waters welling up within,
and thus he learned to wait in patience and silence,
so that no self activity might mar the work of the Lord in his soul.
It was thus that he was prepared for his work,
and for the peculiar calling of which he became an eminent instrument.

Since the days when George Fox and the band of those whom Isaac Penington calls "`raw,
country lads,`" went forth to draw people off from the world`'s
worships to the worship that is in the Spirit,
and in the Truth,
and away from a man-made ministry to the ministration of Life and substance,
many eminent and remarkably favoured instruments have been
raised up to participate in this ministry of Life.
Their gifts have been of an extremely varied character, as were their ages,
antecedents and natural qualities.
There was certainly no Church that has existed since the Apostles`' days that could
point to such a glorious dispensation of service committed to its faithful members,
as was the case up to comparatively recent years with the people called Quakers,
and we may add, still is so, and where the foundation principle is not only recognized,
but diligently built upon, though alas,
this ministry of the Spirit does not now characterize the main Society as a Church,
and it is in our day much more obscure and hidden.

Study in these pages Job Scott`'s account of his entrance into the public ministry.
Think of what his words mean,
think too that the meaning of these words is reflected right through his career:
in his movements away from home, among his friends,
and in many of the very pertinent and feeling little
essays which crop up again and again in his Journal,
from the depths of a rich and hard bought experience.
How entirely different is the lesson he has to teach us
from that conveyed by the ordinary religious Biography.
In the latter we may get, it is true, a mixture of industry,
learning and piety commended to our notice,
but we are not brought face to face with a battle array
of spiritual forces as we are in the [.book-title]#Journal of Job Scott#.
We feel here that there is no beating the air; every blow tells,
there is not any attempt at an advance, before the Commander gives the Word,
and there is no victory sought for the blessed Truth,
apart from man`'s willing and hearty cooperation; where that is lacking,
where those to whom the message is sent,
will not thus cooperate with the holy power which accompanies true Gospel ministry,
the disciple is not above the Master, nor the servant above his Lord;
both must suffer rejection.
The times and seasons for the visitations and invitations of Grace
are shown here to be entirely in the hands of the Master,
and the Gospel is not made cheap by the reiteration of a form of words which may be true,
but do not proceed from, nor gather to an immediate ministration of Power.

The Good Shepherd is always seen in Job Scott`'s Journal going before his sheep:
the same infallible Guide closes his mouth meeting after meeting,
and then opens it again in clear and powerful testimony,
so that looking back on his death bed to such services, Job Scott could say,
"`It is the Lord who works my works in me, and magnified be His Name forever,
He has often worked in me mightily to my own humbling admiration.
And as certainly as He lives, He would work mightily in many thousands,
if they would but let Him come over all in them.
Indeed He works in all as far as they give way to His arising.
This doctrine is to me as clear and certain at this moment, as ever it has been,
and I have often been constrained to proclaim it to the nations,
sometimes with almost Invincible authority,
and sometimes under a great deal of weakness and obstruction.`"

There appears little room for doubt that Job Scott`'s ministry
was frequently of a remarkably powerful character.
Many years ago I knew an elderly friend whose father, John Pince, had heard him preach.
At Bristol he had been silent on six occasions;
subsequently the friend followed him out to Lawrence Weston where he was fervently engaged,
taking off his coat and throwing it on the gallery rail in front:
John Pince felt as if he had never before heard ministry so strikingly impressive.

As a young man Job Scott kept school at Providence, R. I.,
but appears in his later years to have worked a farm.
His observations on wealth are worthy of note.
After expressing the desire that his children should be employed so as to be out of
the way of a great deal of temptation--he adds "`out of the way of very great accumulation;
and yet, through industry and perseverance, moderately productive.
My very soul abhors the idea that a Christian can ever be at liberty,
while under the influence of heavenly good, to seek, or even desire much wealth,
though this disposition, in direct opposition to the life and doctrines of Christ,
has gone far towards the destruction of true spiritual religion,
I believe in almost every religious society in the world.
Alas! if there is any such thing, as the abomination of desolation,
it is mournfully seen standing in _ours,_ in almost every part of the countries,
where it ought not.`"

A very remarkable experience should be noted in this brief sketch.
Shortly before leaving his native shores in 1792, never to return,
though still in the prime of life,
he received a very remarkable visitation or communication
which was attended with Divine life and freshness.
It was a message setting forth before him an extensive field of service,
the curse and blasting if he disobeyed, the blessing, if he was faithful,
the raging of the waves on his passage and the calm that was to succeed.
This was followed by twenty-eight stanzas in poetry,
full of beautiful promises of the Lord`'s help and favour.
He came home and penned it immediately.
Should a second series of Selections be issued, I hope to republish these stanzas.

In the 12th month, 1792, leaving his six motherless children in the care of relations,
Job Scott, obeying the Divine call, left his native land never to return.
He was attacked by small-pox at Ballitore, in Ireland,
where he made a triumphant end in 11th month, 1793.

Notwithstanding these favours, a few days afterwards he writes:
"`Reduced to nothing as to having any store of religious
experience or enjoyment to bear up my mind.
I felt as if all I had ever known or done,
and all that had ever been done for me was of no avail to me now.`"

In style Job Scott`'s writings are clear, precise and emphatic; he had convictions,
and they asserted themselves strongly; his aspirations were ardent,
and indifference or lukewarmness was foreign to his character; more placid temperaments,
with not less purity of aim, would express themselves less and warmly.

From the pen of "`the blessed John Woolman,`" as Job calls him in one of his letters,
we should scarcely expect language expressing such intensity of
feeling as Job Scott uses in the extract already given above,
and yet John Woolman was equally well concerned,
not merely to avoid all appearance of evil,
but also to avoid all participation with evil,
and the love of anything contrary to Divine purity.
Who shall say that the Church did not then,
and does not now need those who can knot the scourge of small cords,
and "`overturn, overturn, overturn`" the work and business of those thieves who
rob God of His place in the Temple,
where continual prayer and supplications should be offered to His holy Name.

A considerable amount of doctrinal matter is omitted from the Selections in this volume.
In a very striking, original and unconventional way,
and almost everywhere with great lucidity the doctrine of Christ as our Life,
and of the new Birth as a union of God and man is set before the reader;
requirements of space forbid extensive extracts.

The author felt that some of his writings might be "`a good deal
better guarded,`" but there is much in them that the Editor believes
would be of service yet more fully than has been the case,
in bringing about the time when, as foreseen by Job Scott on his deathbed,
"`a highway will be opened through kingdoms and nations where darkness has long reigned,
for the publication of the Everlasting Gospel in its true life and authority;
and as what is revealed in the ear, is in due time to be declared on the house- tops,
I have little or no doubt that the true doctrine of Christ will be much
better understood than has hitherto been generally the case.`"

[.signed-section-signature]
John E. Southall
