[quote.epigraph, , Luke 14:26]
____
If anyone comes to Me and does not hate his father and mother, wife and children,
brothers and sisters, yes, and his own life also, he cannot be My disciple.
And whoever does not bear his cross and come
after Me cannot be My disciple.
____

== Chapter I.

[.chapter-synopsis]
* His birth and parentage
* The early impressions of truth on his mind
* On children in general
* A series of visitations of divine love
* His frequent transgression, trials about water-baptism, predestination, etc.

Forasmuch as it has pleased divine wisdom to lead and conduct my soul through many,
various and afflictive dispensations;
as well as through some very comfortable enjoyments;
giving me to partake largely of afflictions; bearing up my mind through them;
bringing me forth again and
again rejoicing, after scenes of deep distress;
and wonderfully preserving me through some very deep,
and perhaps somewhat unusual probations, in my travel towards the land of rest: I feel,
and often have felt,
an engagement of mind to leave behind me some memorandums in
commemoration of his gracious dealings with me from my youth.

I was born, according to the best account I could obtain,
and according to the present or new style,
on the 18th day of the 10th month 1751 in the township of Providence,
now North-Providence,
in the colony (now state) of Rhode-Island and Providence Plantations in New-England.
My parents names were John and Lydia Scott; who were accounted honest people,
though my father made but little profession of religion.
My mother was more zealous, and attended Friends meetings when she conveniently could,
taking me several times with her, and I think a few times another or two of the children;
though we were all but young, for I being the eldest was but ten years old when she died.
I can well remember the serious impressions and contemplations which,
at that early period of life, and for some years before my mother`'s decease,
attended my mind as I sat in meeting with her, and on the way home.
I even had longing desires to become truly religious,
and to serve and fear God as Abraham, Isaac and Jacob,
did and others that I read or heard of.
My mother endeavored much to restrain us from being in
the company of rude and vicious children,
and would sometimes call us together, and labor to have us sit in silence with her,
which we did: and though I then understood but little of the intent of it,
it has since afforded me a degree of solid satisfaction,
in believing the Lord had given her to know and partake of the
sublime enjoyments and substantial benefits of true,
inward, christian silence, and waiting upon God;
and that she was desirous we her children might, in our tender years,
be made acquainted with at least some secret touches of that divine favor
which I doubt not she felt and experienced in such seasons of retirement:
and though, as I observed, I understood but little about it then;
yet I have since had reason to believe it was a real advantage to me;
and that it has often been remembered since to my benefit.

I am fully persuaded of the great advantage and
spiritual usefulness to children and others,
resulting from frequent silent waiting on the Lord.
I have seen lively and convincing evidence of it, even in children very young in years;
and fully believe the impressions of divine goodness
have been such to their minds at some such seasons,
even when there has not been a word uttered vocally, as have lastingly remained,
and powerfully tended to beget the true fear and
love of God in their young and tender hearts.
And O! that parents were more generally concerned to do all they could
towards leading their tender offspring into an early acquaintance with,
and relish of divine things: best learned, and most livingly,
and experimentally sealed upon the soul, in a state of silent introversion,
and feeling after God.

I was told by some of my kindred who were present at my mother`'s death (for it
being night I was not present myself) that her departure was joyful and glorious;
and that very near her last breath was spent in fervent supplication to the Lord her God.

And now, not at all doubting but her immortal spirit is at rest in Jesus, I leave her,
and proceed to a further relation of the exercise of my own mind,
having this testimony to bear, that almost as early as I can remember any thing,
I can well remember the Lord`'s secret workings in my heart, by his grace or Holy Spirit;
very sensibly bringing me under condemnation for my evil thoughts and actions,
as rudeness and bad words,
(though not frequent in the use of them) disobedience to parents; inwardly wishing,
in moments of anger, some evil to such as offended me;
and such like childish and corrupt dispositions and practices,
which over and beyond all outward instruction I was made sensible were evil,
and sprang from a real root of evil in me.
And I am in a full belief, that in every quarter of the globe, children, at an early age,
have good and evil set before them,
in the shinings of the light of Christ in their hearts,
with clearness and evidence sufficient to ascertain to them their duty,
if they honestly attend to it.
And though I am deeply sensible of the necessity
and utility of much careful guardianship,
cultivation and instruction,
in order to guard children against the corrupting influence of example, invitation,
and perverse inclination, which abundantly and prevalently surround them;
yet I fear a great part of the tuition, which too many children receive,
tends rather to blunt the true sense and evidence of divine truths upon the mind,
and to substitute notions and systems instead thereof,
than to encourage an honest attention to the teachings which lead into all truth.
I am satisfied,
if the teachings of men were never to thwart the teachings of the Holy Spirit,
many things would fix on the minds of children to be evils which they
are now instructed and persuaded are innocent and commendable.
Indeed it is mournful to observe how many of them are bolstered up in pride,
vanity and revenge;
taught to plume themselves upon their supposed superiority of parts and attainments;
nursed up in the ideas of grandeur and worldly honor; yes,
inspired with exalted notions of the merit of valor, heroism,
and human slaughter.--Thus the very image of God,
which more or less shines in the countenance,
and in the tender sensibilities and compassionate
commiserating feelings of an innocent child,
is defaced or obscured.

Observe an innocent child attentively, and though anger, passion and revenge,
are very obvious features of the first nature,
and show plainly that there is much to be subdued in them; yet it will be found,
they feel nearly and tenderly for the distress of others;
their little bosoms beat with compassion; and if they see cruelty exercised,
by one upon another, they will often, in the best manner they can,
manifest their abhorrence of the cruelty, and dislike of the cruel.
There is in them that which, as attended to, will restrain the violence of nature,
and by degrees bind the strong man, and cast him out, spoiling all his goods.
It is no substantial objection to the discernment given
to children by the holy light which shines in all,
either that they evidently know but very little,
for they have to act in but few and very small matters,
and their discernment is proportionate; or that the seeds of evil,
and propensities to evil actions, are some of the first things evident in them.

I am not insensible of the volumes of controversy about necessity and free will,
fate and choice;
but I have no mind now to meddle with any of the
common arguments pro or con respecting them.
Men muffle and blind their own understandings by
running into abstruse and metaphysical inquiries,
wherein they are scarce ever the better satisfied for their nicest investigations,
or keenest discussions.
God has made mankind universally sensible (in degrees sufficient for
their various circumstances and allotments in life) of their duty,
and enabled them to perform it, so far as they improve the means afforded them.

Adam was as certainly (so it stands in my mind)
made able to obey or conform to the divine will,
so far as revealed to him, as God is perfect goodness;
and so I am persuaded are all his offspring.
I have no more belief that God`'s revealed will required any thing of our first parents,
beyond ability to perform, than I have that God is cruel or perverse;
and as little do I believe that any infant on earth comes into the
world under a moral impossibility of conformity to the divine will,
so far as by any means whatever made manifest, which I call revealed.
Man is here, upon practical principles: nothing is or can be a law to him,
further than it is some way or other discovered;
and that which ultimately assures and seals it to him as God`'s law,
whatever outward manifestation may be made, is the Holy Spirit,
that bears witness with his spirit,
settling and satisfying his mind sufficiently what is good, and what is evil.
And I firmly believe,
if children would be as strictly and steadily conformable as they might be,
to the divine will, so far as from time to time it is gradually opened and made known,
(and there is always power with the opening) they would
soon acquire a good degree of dominion,
in the strength of divine life, over the strength of evil inclinations in them.

Our state in this life is a state of probation.
Such was the state of man originally, and such it is now.
And in order that man at first, or ever after, might be able to conquer,
or be justly punishable for desertion or defeat, he was, is, and must be,
armed with armor invincible against all the
powers that were or are permitted to assail him.
This is just our ground, our state and situation.
Subject to vanity, or to many and various temptations;
yet being inwardly armed with the Spirit of Omnipotence, so far as we stand faithful,
and fight valiantly in the strength afforded us, we are sure of victory.
Our strength or help is only in God; but then it is near us,
it is in us--a force superior to all possible
opposition--a force that never was nor can be foiled.
We are free to stand in this unconquerable ability, and defeat the powers of darkness;
or to turn from it, and be foiled and overcome.
When we stand, we know it is God alone upholds us; and when we fall,
we feel that our fall or destruction is of ourselves.

Many there are who put light for darkness, and darkness for light; bitter for sweet,
and sweet for bitter.
They call the divine light, which enlightens every man that comes into the world,
a natural light, an _ignis fatuus,_ or by some other ignominious epithet;
though the scripture declares it the very life of the holy word,
that was in the beginning with God, and truly was God.
There are many of them, who,
under a notion of advocating the true cause and doctrine of Christ,
strike violently against the very life of it;
and will not allow that the manifestation of the
spirit is given to every man to profit withal,
though the scriptures expressly assert it,
and experience confirms it to those who rightly profit by the measure received.
Many who have, from tradition and education, for a season believed the Holy Spirit,
graciously vouchsafed them,
was some very inferior thing to the true Spirit of the everlasting and most holy God,
have at length, by yielding to its dictates, and taking it for their leader,
grown wiser than their teachers,
and been indubitably instructed and assured that it was indeed the eternal Spirit, that,
from their infantile days, strove with them, for their reconciliation with God,
the eternal source of it; as it did with the old world,
for their recovery from their corrupted, alienated state.

We find that when the earth was corrupt before God, and filled with violence;
when God looked upon the earth, and behold it was corrupt,
for all flesh had corrupted his way upon the earth, Gen. 6:11-12;
when God saw that the wickedness of man was great in the earth,
and that every imagination of the thoughts of his heart was only evil continually,
ver. 5; when it repented the Lord that he had made man on the earth,
and it grieved him at his heart, 6:
at that most totally abandoned and depraved period and state of mankind,
when God was just about extirpating from the
face of the earth the whole wretched race of man,
a few individuals excepted: at such a season as this, the Lord said,
My Spirit shall not always strive with man, ver. 3.

Surely if his Spirit had striven with them until that time,
until they were so desperately wicked, and wholly corrupted,
that not only some but every imagination of their hearts was evil, yes, only evil,
and that continually; we may well believe the express scripture assertion,
that a manifestation of the Spirit is given to every man to profit withal.

If God`'s love is such to men, that he follows them by the strivings of his own Spirit,
and spares them, until, by disobedience they become abandoned and corrupted,
what greater evidence can we desire of the universality of his love,
the long-suffering of his patience and impartial vouchsafement of his Holy Spirit,
not to a few to the exclusion of the rest, but to all mankind the world over.
And what more than reasoning confirms it to be so, is,
the absolute truth of the fact in the individual experience of all.
It is true many deny it.
The Jews also denied Christ to be the Son of God.
They did not know who, and what he was; and their insulting query,
'`Whom do you make yourself to be?`'
was just as natural to proceed from them in their dark and carnal state,
as is the confidence wherewith thousands, high in profession of godliness,
now utterly disallow the Holy Spirit that is given to all, to be the Holy Spirit.
But this consolation have all Wisdom`'s children,
that '`Wisdom is justified of them all;`' and that the
unbelief of others can never make void their faith:
they are taught of God, and great is their peace.

In regard to my own early acquaintance with the Holy Spirit`'s operation,
though I then knew not what it was.
I have now no more doubt about it than I have about the existence and omnipresence of God.
It is sealed upon my heart, with as much clearness and certainty,
that it is the Spirit of the living God, and that it visits, woos, invites,
and strives with all, at least for a season, as it is,
that God is no respecter of persons.
And I as fully believe no man can have any clear knowledge of God,
or of his own religious duty, without the Holy Spirit`'s influence,
as I believe the wisdom of this world is foolishness with God,
and that the world by wisdom know him not.
Yes, so quick and powerful, so discerning the thoughts and intents of the heart;
and so just and distinguishing, in approving and condemning them,
according as they are good or bad, is this spirit, word, and witness in man;
that not only without the aid of human injunction or information;
but in direct dissent from, and disapprobation of, the sentiments, advice,
and pressing invitations and persuasions of my play-mates,
and those much older than myself, and who confidently and repeatedly declared to me,
that such and such things were innocent, and not at all wicked,
and that nobody thought them so but myself;
the testimony of truth would and did arise and live in my heart when very young,
through the shining of divine light or influence of the Holy Spirit;
that those things were evil, were wicked; and I thought,
notwithstanding all those young persons could say to the contrary,
that all good people would think as I did--and
believe they would be generally so accounted,
if all men kept strictly to the Holy Spirit`'s teachings.
But violence being done to clear conviction in the mind, death takes place,
as on Adam in the day he ate forbidden fruit.
And in this state of death, the truth is not so easily distinguished from error,
or good from evil, as before transgression.
Evil habits gain strength; darkness covers the mind; temptation is renewed,
and though the Spirit again in some degree forewarns, and bids beware, the mind,
habituated to the stifling of conviction, too commonly again rushes forward,
and becomes more and more hardened and darkened,
until what was at first plainly condemned as evil,
by the unflattering witness in the mind,
is at length maintained to be innocent and sinless.
This is the too usual course of poor mankind.

Before I was ten years old, the workings of truth grew so powerful in my mind at times,
that I took up several resolutions (or at several times resolved) to amend my ways,
and live a serious and religious life,
though I was not one of the most vicious of my years;
yet enough so to be made very sensible of the Lord`'s controversy with me,
on account of the evil of my ways.
My mind became exceedingly disquieted, when I went contrary to divine manifestation;
though I had not yet a clear sense that it was the very Power and
Spirit of God upon me that so condemned and distressed me for sin,
and strove to redeem my soul from the bondage of corruption.

I now began to take notice of what I heard read and conversed of respecting religion;
and among other things I heard frequent mention
in books and conversation of the Spirit of God;
and that good people in former times had it in them; and by it learned the will of God,
and were enabled to perform it.
I perceived it was often spoken of in both the Old and New Testament,
and many other writings.
I understood that true converts in these days also have it.
But, like many others, I overlooked its lively checks and calls in myself;
had no idea that I had ever known any thing of it; longed to be favored with it;
but supposed it was some extraordinary appearance,
different far from any thing I ever yet had been acquainted with.

Thus the Jews, even while they were expecting Christ`'s coming, knew him not when he came.
They overlooked and despised his mean and ordinary appearance;
thought he was Joseph`'s son and born among them, and so rejected,
abused and finally put him to death.
But they were mistaken in his pedigree: his descent was from heaven; and God, not Joseph,
was his father.
Just so are thousands now mistaken, as to the dignity and origin of God`'s Spirit in them;
they think it is of man, a part of his nature and being; whereas it is of the very life,
power and substance of God.
Its descent is as truly from heaven, as was that of the Lord Jesus.
He came in that low, mean and ordinary appearance as to outward show and accommodations,
teaching us thereby not to despise the day of small things,
nor overlook the littleness of the motions of divine life in our own souls.
And when he compares the kingdom of Heaven, which he expressly says is within,
to outward things, he very instructively inculcates to us,
that the beginnings of it are small,
'`a little leaven`'--'`a little seed`'--'`a grain of mustard seed`'--
'`the least of all seeds.`'--This is true in the inward,
whatever it be in the outward;
for the seed of the kingdom is '`the least of all
the seeds`' in the field or garden of the heart.
Other seeds sprout, spring up, and take the attention, while the incorruptible seed,
the word of God in the heart, is overlooked, trampled under and despised.

O! that children and all people would be careful in their very early years,
and as they grow up and advance in life,
to mind the '`reproofs of instruction`' in their own breasts;
they are known to be '`the way of life,`' divine life to the soul.
This something, though they know not what it is, that checks them in secret for evil,
both before and after they yield to the temptation,
warning them beforehand not to touch or taste,
and afterwards condemning them if they do so;
and inwardly inclining them to a life of religion and virtue-- this is the very thing,
dear young people, whereby God works in you, to will and to do; and by which he will,
if you cleave to it, and work with it,
enable you to work out your own salvation with fear and trembling before him.
Despise it not, do no violence to its motions; love it, cherish it, reverence it;
hearken to its pleadings with you; give up without delay to its requirings,
and obey its teachings.
It is God`'s messenger for good to your immortal soul:
its voice in your streets is truly the voice of the living God:
its call is a kind invitation to you from the throne of grace.
Hear it, and it will lead you; obey it, and it will save you:
it will save you from the power of sin and Satan:
it will finally lead you to an inheritance incorruptible in the mansions of rest,
the house not made with hands, eternal in the heavens.

I entreat you, as you love your own souls, and prize an everlasting salvation;
I warn you by the dreadful fruits of disobedience, by the pangs,
remorse and sufferings of my own soul for sin and transgression.
Had I steadily obeyed the truth in my inward parts;
had I attended singly and faithfully to this divine monitor, my portion had been peace;
my cup, a cup of consolation.
I might have rejoiced and sung, whereas I have had to mourn and weep.
For as I grew to fifteen and upwards, in violation to clear inward convictions,
in opposition to the dictates of the Holy Spirit, I began to run into company,
learned to dance and play cards, and took great delight therein.
I was often deeply condemned, and often strove to stifle the witness,
and persuade myself there was no harm in any of these things.

My father sometimes reproved me in those days for my conduct;
but sinning against divine light and visitation, hardened me against his advice.
I grew more and more vain, proud, airy and wanton.
I put myself in the way of much evil communication;
and it mournfully corrupted good manners.

My taste for pleasure and amusement grew keen,
my spirits were low and languid when alone,
and I rushed into company and merriment for alleviation.
Thus I went on frolicking and gaming, and spending my precious time in vanity.
Often at night, or in the night, and sometimes near break of day,
I have returned home from my merry meetings grievously condemned, distressed and ashamed;
wishing I had not gone into such company, and resolving to do so no more;
but soon my resolutions failed me, and away I went again and again,
and thus continued making still greater strides in folly than before.
The Lord followed me close, in mercy, and often brake in powerfully upon me,
turning all my mirth into mourning; yet I still got over the holy witness,
did despite to the spirit of grace,
and repaired again to my haunts of diversion and merriment.
Sometimes when I have stood upon the floor to dance, with a partner by the hand,
before all were quite ready, God has arisen in judgment,
and smitten me to the very heart.--Oh!
I still feelingly remember his appearance within me, when none knew the agony of my soul.
I felt ready to sink under the weight of condemnation and anguish;
but resolutely mustering all the stoutness I was master of, I brazened it out,
until the music called me to the dance, and then I soon drowned the voice of conviction,
became merry, and caroused among my companions in dissipation,
until time urged a dismissal of our jovial assembly, and called me to return,
often lonely, to my father`'s house, my outward habitation.
Oh! me, how fared it with me then?
I assure you, reader,
I have not forgotten those sad and mournful walks at
the conclusion of my midnight revellings.
I have been broken down in deep abasement and self-abhorrence; have come to a full stand,
stopped and sat down on a stump, stone or log, by the way; wrung my hands,
strewed my tears before the Lord, in sorrow and extremity of anguish,
bordering almost on desperation.
I have begged forgiveness; implored assistance; vowed amendment; obtained some relief;
and returned home in hope of reformation.

But alas, alas! my resolutions were written as it were in sand;
the power of habit had enslaved me; and almost the next invitation of my associates,
overcame all my engagements; the eagerness of desires for divertisements and pastime,
brake through all the sanctions of vows;
and violated the solemnity of sacred promises to my God.
I rushed again into transgression, as a horse rushes into the battle;
again and again I took my swing, and drank my fill;
and again and again remorse and compunction seized upon me.
Adored forever be the name of the Lord, he forsook me not;
but followed me still closer and closer,
and sounded the alarm louder and louder in mine ears.
There was in me an immortal part, which his love was towards; the recovery of which,
from the thralldom of sin and corruption,
his goodness engaged him to seek by mercy and by judgment; frowns and smiles;
chastisements and endearments; and all in love inexpressible.

Thus dealt he with me.
When I turned at his reproofs, he smiled upon me, and relieved my soul`'s anxiety;
but when I again revolted, his rod was lifted up in fatherly correction.
The still small voice was uttered in my dwelling, as in the cool of the day,
when a little retired from noise and commotion, Adam, where are you?
There was no hiding from him, whose penetrating eye no secret can escape;
and whose aim in reproving was only to save.
He still reproved my wanderings, and pointed out the right way,
according to scripture declaration, you shall hear a voice behind you, saying,
this is the way, walk in it.

Indeed the way was shown me; it was often plainly cast up before me;
but I would not walk in it.
I knew my Lord`'s will, but did it not; mine own, I still delighted in the indulgence of.
O! that others may escape my load of guilt, and may I say, my bed of hell,
or inward tormenting agony, by a timely submission to the reproofs of instruction.

Sometimes I spent near all the first day of the week, when I should have been at meeting,
in playing cards, idle, if not dissolute conversation, and other vain amusements;
returning home at night in condemnation, and sometimes sighing and crying,
and yet through all this the Lord preserved me from hard drinking,
though often in the way of temptation and solicitation to it.
Swearing I also mostly refrained from.
Jesting, joking and vain conversation I went considerable lengths in;
and sometimes joined the foremost in filthy and obscene discourses.
Then again great shame and self-abhorrence would overwhelm me; again I vowed,
promised and renewed my covenant; but all in vain; I had not got deep enough;
nor were my covenants made or renewed in the right ability;
but too much in my own strength and creaturely resolutions; so they were soon broken.
Sometimes I held out a week or two; other times only a day or two.
Thus time passed on; and, with an increase of years,
I found an increasing propensity to wantonness and dissipation.
But blessed be the God of my salvation,
he proportionately increased my sense of guilt and condemnation.

I had seasons of very serious consideration upon religion.
What instructions I had outwardly received, were mostly in the way of Friends;
but when I came near to man`'s estate,
falling in company with some of the Baptist society,
I was drawn to attend their meetings in Providence.
Friends meetings were oftener held in silence than suited my itching ear.
I loved to hear words, began to grow inquisitive,
and to search pretty deeply into doctrines and tenets of religion;
and the Baptist preachers filled my ears with words,
and my head with arguments and distinctions;
but my heart was little or not at all improved by them.
I almost forsook the meetings of Friends, except yearly meetings,
and meetings appointed by travelers in the service of the gospel.
But when I went to these,
O! how livingly I still remember the heavenly and heart-tendering
impressions I sometimes received under the animating
testimonies delivered in the life of the gospel.
Here my heart was helped, though my head was less amused than among the Baptists:
however, as I knew not clearly what caused the difference;
as Friends meetings remained still often silent;
and as I still wished the gratification of argumentative, systematic discourses;
I still pretty diligently attended the Baptist meeting; and,
in my most religious seasons, I began to think of being baptized in water.
For the head-work so far outrun the heart-work, during my attendance of these meetings,
that I became convinced in speculation,
that that outward performance was an ordinance of Christ; though I have since seen,
that it never was ordained by Jesus; but was a forerunning,
preparatory and decreasing institution, and has long since done its office,
and ceased in the church in point of obligation;
and that there is now to the true church but one Lord, one faith, and one baptism,
that of the Holy Ghost, which only can purify and make clean the inside.
Oh! my heart, my very soul is fully satisfied in this matter;
having felt the living efficacy of this one saving baptism,
and known its full sufficiency, without any other.

What first turned my mind to believe the outward a christian ordinance was this one
argument of the Baptists-- Christ commanded his disciples to baptize:
No man can baptize with the Holy Ghost;
therefore the baptism he commanded was not that of the Holy Ghost, but that of water.

This then appeared to me conclusive, and unanswerable.
But it was my ignorance of that baptizing power which attends all true gospel ministry,
that made me assent to this false position, '`no man can baptize with the Holy Ghost.`'
Man himself, in his own mere ability, I know cannot; but I also know,
that of himself he cannot preach the gospel.
This assertion, no man can preach the gospel,
is just as true as that '`no man can baptize with the Holy Ghost.`'
As man merely, he can do nothing at all of either; but it still stands true, man can,
through divine assistance, do both.
The real gospel was never yet preached, but '`with the Holy Ghost sent down from heaven.`'
Thus the apostles preached it, and thus alone it is still preached--and so preaching it,
it was a baptizing ministry.
As they spoke, the Holy Ghost fell on them that heard them; that is,
where faith wrought in the hearts of the hearers, and the living eternal word preached,
through the power of the Holy Ghost, was mixed with faith in them that heard it;
the Holy Ghost fell on them,
baptizing them into a living soul-saving sense of the '`power
of God to salvation,`' which is the true life of the gospel.
Thus the apostles fulfilled the commission.
They taught baptizingly.
The commission is not '`teach, and then baptize,`' as two separate acts.
It is '`teach, baptizing,`' --and those who livingly witness the gospel,
the power of God to salvation, preached unto them, they feel it, and receive it in,
and only in the Holy Ghost sent down from heaven, they are taught baptizingly,
in the demonstration of the spirit and of power.

And no preaching has a whit more of the gospel in it, than it has of the Holy Ghost,
the alone true baptizing power.
I don`'t marvel that the letter-learned teachers of our day who run unsent,
who are always ready,
are ignorant that a true gospel minister is clothed with
baptizing authority from on high.--I may not now go much
further into the discussion of the subject of baptism,
though I scarce know how to dismiss it,
so many things occur in evidence that there is and can be but one in the gospel,
and that this is and must be spiritual.

I had not yet fully given up to the motions of divine life in my own heart.
My mind was too much turned outward; and the preaching of those I sometimes went to hear,
who preached in their own time, had a powerful tendency to keep it outward.
In this state of outward attention and inquiry,
I found nothing that could give me power over sin and corruption;
but notwithstanding all my serious thoughtfulness,
and frequent and ardent desires to become truly religious, I still, once in a while,
brake loose, and launched forth into as great degrees of vanity and wickedness as ever:
and then again a turn of seriousness would come over me.
One time under deep exercise, after reasoning and hesitating great part of a day,
whether I had best give up with full purpose of heart, to lead a religious life or not;
at length I gave up, and entered once more into solemn covenant, to serve God,
and deny myself, according to the best of my understanding.
Almost as soon as I had thus given up, and come to this good conclusion,
in stepped the grand adversary,
and blundered and distressed my mind exceedingly with the doctrine of predestination;
powerfully insinuating that a certain number
were infallibly ordained to eternal salvation,
the rest to inevitable destruction;
and that not all the religious exercises of my mind could possibly
make any alteration in my final destination and allotment.
If God had damned me from all eternity, I must be damned forever;
if he had chosen me to eternal salvation, I might set my heart at rest,
and live just such a life as would most gratify my natural inclinations;
for what advantage could there be in religion, and self-denial, if an eternal,
unalterable decree secured my final end.
I felt willing to hope I was a chosen vessel;
and for a short time these ideas so crowded into my mind,
that I was even ready to conclude a God all goodness had
doomed the far greater part of mankind to never-ending misery,
without any provocation on their part.
I now view the doctrine of unconditional election to eternal life,
and reprobation to eternal destruction, with abhorrence.
I almost marvel, that under a cloud of darkness,
my rational faculties could ever be so imposed upon,
as to assent to so erroneous a sentiment.
I know of no doctrine in the world that more shockingly
reflects on the character of the Deity.

I did not indeed so drink down this false doctrine as
to relinquish my purpose of amendment all at once;
I held out a few weeks; when, mournful to relate, the influence of young company,
and my vehement desires for creaturely indulgence,
through the tolerating influence of the aforesaid insinuations,
brake through all my most solemn engagements, threw down the walls and fortifications,
and exposed me an easy prey to the grand enemy of my soul`'s salvation.
Again I took my swing in vanity, amusements and dissipation.
This, however, was but a short race.
The Lord, in lovingkindness, followed me with his judgments,
inwardly revealed against sin.
The prince of darkness also followed me, with temptation upon temptation to evil;
and with various subtle insinuations, and dark notions to rid me of all fear,
restraint or tenderness of conscience.
At length, notwithstanding all I had felt of the power of God upon me,
in reproof for sin, and invitation to holiness; yes,
though I had had some true relish of divine good, the holy witness became so stifled,
that I began to conclude there was no God; that all things came by chance, by nature,
by the fortuitous jumble and concourse of atoms, without any designing cause,
or intelligent arrangement; that it was idle, chimerical and delusive,
to think of serving or fearing a being who had no existence
but in imagination.--Here let it be well considered what a
powerful influence the admission of one false doctrine,
and the violation of divine manifestation and conviction,
has in paving the way for other false doctrines.
Not much sooner had I received and cherished one
of the grand falsehoods of the father of lies,
the doctrine of irresistible necessity, and predestination,
than in the mists of darkness which spread over my mind,
under the baleful influence thereof, I even dared to deny the eternal deity; and,
horrible to the last degree to think of, I began to rejoice in the idea of unbounded,
unrestrained licentiousness and carnality; and that I was unaccountable for my conduct,
not considering that, on my atheistical scheme, I was unprotected,
and had no more to hope than to fear; none to look up to for defense and succor;
but must be left a prey to violence, and all kinds of adversity attendant on this life.

Oh! the depravity of taste and inclination, as well as of understanding,
which I was plunged into!
I went on a few months after this, much in the same manner;
my days I spent in vanity and rebellion; my nights frequently in horror and distress!
Many a night I scarce dared enter my chamber,
or lay me down in bed.--I have the most unshaken ground
to believe it was the immediate power of God upon me,
that thus terrified my guilty soul; and that in the most fatherly goodness,
condescension and mercy, in order to prevent my going on to endless perdition,
to which I seemed to be swiftly posting.--Day after day, and night after night,
I was distressed!--the Lord setting my sins in order before me,
and pleading with me to return unto him and live.
At last I fled again to religious engagement for relief, betook myself to prayer,
and cried to the Lord, in the bitterness of my spirit.
Sometimes I begged and interceded for mercy, and power to make a stand and overcome sin,
with such vehemency as if my very heart would break!--Tears gushed from my eyes!
My soul was overwhelmed with anguish!

O! young man whoever you are, that reads these lines, I warn you, I beseech you,
shun such misery, by obedience; such unutterable anxiety, by cleaving to the Lord.
Yet after all this, young company, music, gaming, pleasure, again rallied their forces,
and had such influence over my resolutions, as evidenced them written as in dust,
though mingled with tears, with wormwood and gall, and I abandoned all again,
to enjoy the pleasures of sin for a season.
But God, rich in mercy, and long-suffering kindness, still interrupted my career,
disturbed my carnal satisfaction, and blasted all my joys.
Once more a sense of just and holy indignation kindled
up in my breast for transgression and grievous revolt.
Awfulness took hold on me; amazement swallowed me up.
I knew not which way to turn.
The wrath of an offended long-suffering God seemed closing
upon me on every side.--I felt myself in thralldom,
and almost without hope.
I knew myself a prisoner, and yet I hugged my chains.
