== Chapter II.

[.chapter-synopsis]
* His exercises continued, and particularly about using the plain scripture language
* Of Israel`'s wilderness travel, and the forerunner
* Reference to the seasons and book of Job
* On humility, and his entrance into the work of the ministry, and considerations thereon

Thus I continued still in vanity, and folly,
with intervals of deep distress and mourning, a short space longer, that is,
until about nineteen years old, when I became more fully and clearly convinced,
and that very much by the immediate operations, illuminations,
and openings of divine light in my own mind, that this inward something,
which had been thus long and powerfully striving with me, disturbing my every false rest,
confuting every false and sin-flattering imagination of flesh and blood,
or of the grand adversary, and enjoining it upon me to give up all,
and walk in the ways of virtue and true self-denial,
was the true and living spirit and power of the eternal God;
the very same that strove with the old world, influenced the patriarchs,
prophets and apostles; and visits, strives with, and at seasons more or less influences,
the hearts of all mankind.
I now saw this the only principle of all true conversion and salvation;
that so long as this was resisted and rejected,
separation must infallibly remain between God and the soul; but that,
whenever this is received and in all things thoroughly submitted to,
a thorough reconciliation takes place.

Some may think this doctrine robs Christ of the
honor of our redemption and reconciliation;
but I apprehend none can think so who understand the doctrine of salvation by Jesus.
It was through the eternal Spirit, this very Spirit that visits and strives with all,
that Christ offered up that prepared body.
It is through, and only through, the influence of the same Holy Spirit,
that any soul was ever converted to God,
or savingly benefited by the redemption that is in Jesus.
Whatever way, O soul, or by whatever means you are benefited in a spiritual sense,
it is by this Holy Spirit,
that is the immediate operative power and principle within you.

Having thus at length become livingly convinced that it was nothing short of
the eternal Power and Spirit of God that so forcibly wrought in me,
in order for my deliverance from the power of darkness and seduction,
I gave up to the holy requirings of God,
as inwardly made known to me--and clearly known were many things thus made.
Nothing else could ever so have opened my mind, and made known my duty to me.
The Scriptures, other good books, religious conversation,
contemplation upon the works of creation and providence;
all these are very good means of information; but none of them, nor even all of them,
without the Holy Spirit`'s sealing operation and evidence upon the mind,
can ever make a man sure of his duty to God in any one thing.
He may reason, and set up many rules, measures and standards of duty and morality;
but certainly he never will arrive thereat,
without the help of that which in itself is certain.
It may be said the scriptures are certain.
Very well, but what certifies you that they are certain, or that you know their meaning?
Do not the professed masters in reasoning widely
differ upon many passages in the sacred writings?
they all say they have reason on their side.
But believe them not:
nor believe that any thing is or can be certainly known
to man of the divine authority of the scriptures,
without the light and evidence of the Holy Spirit.

But to proceed:--I gave up very fully to serve the Lord in the way of his leadings;
I forsook rude and vicious company, withdrew into retirement,
attended the meetings of Friends, and often sought the Lord, and waited upon him,
in solemn, reverential silence alone, for his counsel, direction and preservation;
and he was graciously pleased to point out and cast up the way for me,
one thing after another, with sufficiency of clearness.
First, he showed me negatively, what I ought not to do, in various particulars,
breaking me off from my vicious practices and associations.
This was forsaking evil.
And then he taught and enjoined me the practice of several things positively,
wherein he engaged me to choose and cleave unto that which is good.
I saw clearly it was his will,
and my indispensable duty reverently to assemble for divine worship,
and therein to wait upon him, draw inwardly near unto him, and,
according to the apostle`'s language, feel after him, in order to find and enjoy him.
I also found it my duty often to wait upon him alone, in awful, silent retirement,
not approaching him in supplication, but when he influenced my heart thereto,
with the true spirit of prayer and intercession.
He also showed me, that religion was an internal life in the soul; that great attention,
sincerity and punctuality was necessary to the growth and prosperity of it:
that I must not be content with attending meetings, and sitting in silence,
though ever so reverently and properly;
I must live continually in an inward watchfulness and dedication of heart;
watch all my thoughts, words and actions, and know all brought to judgment;
and allow nothing to pass unexamined, nor willingly unapproved:
that I must observe the most upright honesty and sincerity in
my dealings among men as in the presence of God.
He taught me that men generally rely too much on external performances;
and thus guarding my mind against thinking too much of any thing outward.
He opened my understanding to behold my duty, in regard to outward plainness;
that a plain, decent, and not costly dress and way of living, in all things,
was most agreeable to true christian gravity and self-denial: that rich,
showy or gaudy dress, house, food or furniture, fed and fostered pride and ostentation;
robbed the poor, pleased the vain, and led into a great deal of unnecessary care,
toil and solicitude, to obtain the means of this way of life and appearance:
that it could not afford any true and solid satisfaction;
but must unavoidably divert the mind from inward feeling watchfulness;
retard the work of mortification and true self-denial;
and facilitate unprofitable association and acquaintance with
such as would rather alienate the affections from God,
than unite the soul to him.

Thus instructed, I bowed in reverence;
and as it became from time to time necessary to procure new clothing,
I endeavored to conform my outward appearance in this respect to the dictates of truth,
in which I found true peace and satisfaction.
Also he instructed me to use the plain scripture language, THOU to one,
and YOU to more than one.
The cross greatly offended me in regard to these things.
This of language in particular,
looked so trifling and foolish to the worldly wise part in me,
and the fear of the world`'s dread laugh, so powerfully opposed it,
that it was very hard and trying to my natural will to give up to this duty.
I thought if my right hand would excuse my compliance, I would gladly sacrifice it,
or yield it up, rather than give up to use such a despised language,
and submit to be laughed at, as viewing religion concerned in such things as these.
This may seem incredible to some, but it is true,
and as fresh with me as almost any past exercise.
This exercise beset me day and night for some time,
during which I had many sorrowful and bitter tears, plead many excuses,
and greatly wished some substitute might be accepted instead of the thing called for;
but he who called me into the performance of these foolish things,
(to this world`'s wisdom) was graciously pleased to show me with indubitable clearness,
that he would choose his sacrifice himself;
and that neither a right hand nor a right eye, neither thousands of rams,
nor ten thousands of rivers of oil, would by any means answer instead of his requirings.
If he called for so weak or foolish a thing as
the words thee and thou to a single person,
instead of you, nothing else of my substituting would do instead of it;
for the foolishness of God is wiser than men.

Let none dispute the ground with Omnipotence, nor confer with flesh and blood;
lest therein, despising the day of small things, they fall by little and little.
For be assured, O! you called of the Lord, you can never become his chosen,
unless you obey his call, and come out of all he calls you from.
If you are not faithful in the little, you will not be made ruler over much.
Perhaps few will believe the fulness of heavenly joy which sprang in my bosom,
as a well-spring of living waters,
after my giving up in faithfulness to this requisition.
And yet this flow of divine consolation lasted not long at this time;
for though I gave up to whatever the Lord required of me,
yet as I had so long and so stubbornly rebelled against him, he saw meet,
in his infinite wisdom, soon to hide his face from me again,
and close me up in almost utter darkness, which rendered my days truly tedious,
and my nights wearisome to my soul.
I was fully convinced that God was to be known inwardly in power and great glory,
by those who obey him, and wait upon him.
My heart was inflamed with love towards him.
I had seen a little of his comeliness--He had become the beloved of my soul,
the chiefest among ten thousands;
therefore I often retired alone and in profound reverential silence, sought after him,
and pressingly solicited a nearer acquaintance with him.
But he knowing what was best for me, graciously hid his presence from me.
And though this was a painful suspension,
yet I could not be easy to give over seeking him;
I still continued my ardent silent approaches, or waitings.
I waited indeed, with all the reverence, humility,
and solicitude that my soul was capable of; but all seemed in vain.
Oh! the mourning and lamentation, the distress and bitter weeping,
that almost continually overwhelmed me for several months together,
for the lack of the soul-enlivening presence of my God.
Oh! said I in my heart, will he never arise for my help and deliverance?
Well, be it as it may, I will seek him until my dying day;
my soul cannot live without him; and it may be,
if he hide his face from me until my last moments, he may own me at that solemn period,
and receive me to a mansion of glory.
This was often, very often, the language of my heart;
and under this resolution I pressed forward.
I trust the wormwood and the gall; the sorrow and the sighing;
the days and nights of anguish; will scarcely be forgotten.
It seems to me that certain spots of earth, some particular fields and groves, will ever,
while life and sensibility remain,
continue to have a moving and affecting influence on my mind,
as often as I pass by and see them, or call them to remembrance.
I think they must remain peculiarly distinguished to me by the tears and the groans,
the sighs and solicitations, which they have been the silent witnesses of.

Oh! my God, you led me through the desert, you weaned me from the world,
and allured me into the wilderness; there you did hide your face from me for a season;
until the longings of my soul after you, were intensely kindled:
then lifted you up my head, and spoke comfortably to me;
blessed be your holy name forever!

At length the Father of mercies having thus tried me,
he graciously cast an eye of compassion upon me, hearkened to the voice of my distress,
made bare his everlasting Arm for my deliverance, gradually unveiled his presence to me,
and opened my heart to understand why he led me through so trying a dispensation.
I now began to discern the mystery of what I read in the
history of Israel`'s forty years travel in the wilderness,
as also the voice of one crying in the wilderness:
I began to see the necessity of the Lord`'s sending his forerunner,
that the way might be prepared, and the paths made straight.
I perceived much roughness, unevenness and crookedness had been in the way.
I began to know and in degree to love the rod, and him who had appointed it;
and as the Master manifested himself more and more,
I understood more and more of the mysterious ways of his working.

After some time I had many clear openings respecting the many trials, experiences,
jeopardies and deliverances of his followers in days past; and a hope was kindled in me,
that now I should go forward without meeting with such besetments,
and withdrawings of light, as heretofore:
for though the Lord still at times withdrew from me;
yet as his return was not long after,
and as his presence was much more constantly with me,
I was ready to conclude it would continue with increasing brightness,
until I should be wholly and continually swallowed up in his love: for,
as such a state was sometimes permitted me,
I not clearly understanding the counsel of his divine will,
was apt to wish it for my constant condition; not then seeing, as I have since seen,
that it was far from being best for me to enjoy a constancy of sunshine and fair weather;
even the outward order and economy of divine providence affords instruction,
which often beautifully applies to our inward experiences.
It is not all calm and sunshine;
the divine wisdom orders many and great vicissitudes and changes in the natural world;
insomuch that, perhaps in the most pleasant and flourishing season in the whole year,
after a few days of clear shining and tranquillity, there arises a most terrible storm,
with wind, lightening and tremendous thunder;
and it may be with hailstones scattered abroad upon the face of the earth.
At other times will high and rushing winds succeed the calmest day;
or pinching droughts the most fruitful season.
Even the settled order and succession of seasons
is a continual revolution of day and night,
summer and winter, seed-time and harvest.
We have cold as well as heat; darkness as well as light;
and cutting frosts as well as most refreshing dews; and a variety of other changes.
All this is in infinite wisdom and goodness;
and displays to the discerning eye the providential
power and glory of the great Superintendent.
My soul has sometimes been enraptured while I have viewed and
contemplated the operations of his hand in these things;
together with the situation of places; rocks and lofty mountains,
sturdy oaks and tall cedars; rivers, lakes and oceans; meadows, fields and forests;
deserts and vast howling wildernesses;
with the various inhabitants of both land and water.
And over and above all these, the sun, moon and stars in their courses;
and constellations of heaven!

All these things (though far short of being sufficient food for immortal souls,
and perhaps not best to dwell much upon) have nevertheless
animatingly affected my mind in the contemplation of them;
and raised my soul in adoration to him who is the former of all things; and who,
when he was pleased to answer out of the whirlwind and
awfully to interrogate his servant Job,
for his instruction, was pleased to make the wonderful works of his hand,
and the excellent order of his government, the subjects of his demands.
And who among the sons of men can read the solemn
queries then uttered by the Divine Majesty,
and not feel some tender emotions of soul;
as--Have you commanded the morning since your days,
and caused the day-spring to know his place?
is one among the many solemn and sublime interrogatives,
by the wisdom of an all-knowing God, demanded of his servant; sufficiently declaring,
beyond all hesitation, how infinitely exalted above all human comprehension,
he is in wisdom, power and glory;
as well as amply setting forth his goodness to the sons of men,
in causing the regular returns of day and night,
and other wonderful successions and revolutions,
for the benefit and comfort of his dependent creatures.

Bow, O my soul, adore and worship the God of your life,
who is the length of your days and your portion forever.
His works are wondrous, past finding out, marvelous, and beyond your comprehension.
You see in part the multitude and magnitude of his wonderful works;
you behold a small part of the changes and vicissitudes attending them:
and yet through all, what excellent order, harmony and regularity is preserved.
Surely nothing less than his Omnipotence and
Omniscience could possibly effect or produce all this.
You see he is faithful in performing his ancient gracious promise.
Day and night, seed-time and harvest, etc. fail not.
He said not unto the seed of Jacob, seek you my face in vain.
No verily; the language of his compassionate regard on the contrary, is, Fear not,
worm Jacob, I will never leave you nor forsake you: when you go through the water,
it shall not overwhelm you; or when through the fire, it shall not kindle upon you.
It is as much in wisdom and goodness that he sometimes as it were withdraws,
hides from and leaves his children,
and then again returns gloriously for their unspeakable consolation,
as is the succession of darkness and light, cold and warm seasons, in the outward.

Many and varied afflictions are necessary to our refinement.
Hence the place of this refinement is called, '`the furnace of affliction.`'
Through the purifying operations of these fiery trials,
the soul is gradually redeemed from the pit of pollution.
It is a precious work of divine power, to hide pride from man.
And he who becomes thoroughly acquainted with the corruptions of human nature,
in its alienation from God, will find,
if ever true humiliation and renovation is effected in him,
that nothing short of the baptism of fire can rightly cleanse the corrupt,
and humble the proud heart of fallen man.
Indeed it is a sealed truth, that they who are without chastisement are bastards,
and not sons.
All that the Father loves, he chastens; and scourges every one that he receives.
My soul rejoices and gives God thanks,
for deep probations and withdrawings of his presence;
as well as for the sensible incomes of his love,
and arisings of the light of his countenance upon me.
I see and own it needful to my growth in the divine life,
as well as in order to my complete emancipation from the servitude of sin,
that he should deal thus with me: and it has afforded instruction to my mind,
that he is called in scripture by the name of the Lord
that hides his face from the house of Jacob.

Oh! what panting of soul, what anxious solicitude for his return,
takes place in all the true travelers, when he veils his holy presence;
and how joyful is the lifting up of his countenance, after these seasons,
upon the drooping mind, thus prepared for the comfortable returns thereof.
It is like the returns of clear shining after rain.
Under the refining hand of God`'s power, whereby he thus humbled and abased my soul,
I was given clearly to see the need I should have of this excellent qualification,
humility, in my further progress in religious life.
I saw pretty clearly, in the midst of my deepest depression,
that if I should be favored with unremitted tranquillity and divine enjoyment,
I should be in danger of spiritual pride and exaltation.
Blessed be the name of the Lord for this among his many other favors,
that he taught me the necessity of humility, and forewarned,
and therein forearmed me against the wiles of Satan,
which I afterwards became more fully acquainted with.
Oh! with what ardency of desire did my prayers ascend before him,
that he would rebuke the proud luciferian spirit,
and appoint my dwelling in the low valley, where the grass is green,
and where the fragrant flowers give forth a pleasant smell.
I saw that on the lofty mountains often reigns barrenness and desolation.
My mind was almost constantly impressed in those
days with the love and desire of deep humility.
I saw something of its real beauty; and craved it as one of the greatest blessings.
O! said I, that I may put it on as a garment, and wear it forever:
yes even appear in it before my Judge,
in the assembly of saints and angels in a future state.

Oh! Lord, my God,
(was then my language, and my heart now joins it)
permit me never to forget my tribulations,
nor to cease my supplications to you, for the continuance of this precious blessing,
let it be the first and the last in the catalogue of my requests.

Thus the great Leader of Israel led me on from step to step,
not by any means through a constant and uninterrupted enjoyment of his presence;
but which for me has been far better, by frequent withdrawings, strippings,
and deep-felt emptiness, poverty and lack; and that again and again repeated,
even after large overflowings of his love in my soul,
as a river overflowing all its banks.
Had he not, after such seasons of rejoicing, veiled his presence,
and clothed my soul with mourning, I might, like ancient Israel, have sang his praise,
and soon forgot his works.

But now through the many tribulations, and wise turnings of his holy hand upon me,
my soul remains bowed,
and to this day sensible of the tendering impressions of his love and goodness.
The savor of life is still fresh within me.
He has led me about and instructed me,
and (with reverence I speak it) has kept and preserved me.
May I still be preserved,
and henceforth forever kept safe under his all-powerful protection;
walking worthy of the same to the end of my days.
Amen.

During a great part of the foregoing exercises, I had frequent openings,
and lively prospects respecting the christian warfare,
and the mysteries of the kingdom of heaven.
I often believed, in the openings of divine light, that, if I stood faithful,
it would be required of me to declare to others what the Lord had done for me,
and given me an understanding of,
and to entreat my fellow creatures to seek a habitation in that kingdom that cannot
be shaken or fade away.--This concern began now to grow upon me considerably,
even to that degree,
that I felt at times in meetings a living
engagement to communicate somewhat to the people;
but, fearing I should begin in that great work before the right time, I kept back;
and even several times, when I was almost ready to stand up,
I have concluded I would keep silence this once more; considering within myself,
that if my so doing should be displeasing to the Lord,
he would manifest his displeasure to me;
but if I should presume to speak a word in his name,
and it should prove to be without his holy requirings, or too soon,
I should not only displease him, but also burden his people;
and perhaps get into and become entangled in a way of
speaking from too small motions or impressions felt,
or mournfully mistake the sparks of my own kindling for divine impressions; which might,
in consequence of my giving way thereunto,
be allowed to increase upon me to my great loss in the substantial and divine life,
if not to my utter ruin.
In this guarded frame of mind I passed on for some time,
often seeking to the Lord for counsel and direction in
this and other concerns of importance.
And though I believe I might have publicly borne testimony in the name,
power and approbation of the Lord, rather sooner than I did;
yet as I was not obstinately, but carefully backward,
I seldom felt much condemnation for withholding: however,
I did a few times find some real uneasiness on that
account.--But he who laid the concern upon me,
well knowing the integrity of my heart, and that I was bent faithfully to serve him,
without going too fast, or yet tarrying behind my guide, dealt graciously with me,
passed by my little withholdings, favored with fresh and increasing incomes of his love,
and from time to time, cast up my way with still greater clearness;
and at length in a manner so clear, and confirming,
as erased doubt and hesitation from my mind.
In the fresh authority whereof I uttered a few words in our meeting at Providence,
on the first day of the week, and 10th of the 4th month 1774,
to my own and I believe my friends satisfaction.
I felt the returns of peace in my own bosom, as a river of life,
for a considerable time afterwards, sweetly comforting my mind,
and confirming me in this solemn undertaking.

After some time of heavenly rejoicing,
I began again to be tried with various exercises and conflicts of mind,
though still frequently favored with the flowings of divine love,
in a very comfortable and soul-satisfying manner.
At various times I had lively impressions to say a few words more, in public testimony;
but still waited to be well assured.
The unspeakable consolation which I found, on my first uttering a few words,
and that after a considerable time of rather holding back, than hasty procedure,
had fully confirmed me that there is greater safety in turning the fleece,
and well proving it, both wet and dry,
than in rushing forward in the first operations or openings.
The beasts, allowed in sacrifice, were to chew the cud and divide the hoof.
Chewing the cud is a deliberate act: they chew and swallow, and chew and swallow again.
The division of the hoof being on the stepping member,
shows the danger of taking a single step in divine services,
without a clear division of things,
and the way cast up in the mind.--As I thus waited for clearness,
not being by once succeeding encouraged to run too fast,
I was favored to know the fire of the Lord rightly kindled upon his altar;
and to witness an offering of his own preparing.
And I am well assured that such,
and such only are the offerings which will find acceptance with him.
He never will reject these, any more than accept those of human obtruding.

My second public appearance in the ministry was at the lower meeting-house in Smithfield,
the 19th of the 10th month 1774,
when I found a living concern to encourage a careful engagement before the Lord,
out of meetings; and to press it upon Friends to draw nigh unto him from day to day,
that strength may be renewed, and the divine savor of life retained,
lest we lose the living sense of what we often
graciously enjoy in our religious meetings.
Life, divine life, attended me in this little testimony, as in the former.
And after meeting I enjoyed the sweet influence of him who is the God of my salvation,
in a degree that was greatly to my confirmation and encouragement.
After this I still continued seeking unto and waiting upon God for counsel and direction;
in which frame of mind I was favored to renew
and increase a living acquaintance with him;
and witnessed fresh instruction to my mind.
I appeared but seldom in public testimony, and mostly in a few words at a time,
and yet I have some few times been made sensible of saying too much;
and for which I have felt more pain of mind than I have often felt, if ever,
for withholding.
However, through merciful preservation,
I have seldom to my knowledge appeared oftener or said
more than has tended to my own relief and satisfaction,
and, for ought I know, to the satisfaction of my brethren:
blessed be the name of the Lord my God.
I bow awfully before him, for his directing and preserving presence,
through many deep probations.
He has been with me in the heights and in the depths;
has strung my bow and covered my head in the day of battle.
May I serve him faithfully all the days of my stay here,
until I go hence and be seen of men no more.
