== Chapter III.

[.chapter-synopsis]
* His exercises continued
* Passes through some discouragements
* A word of encouragement to the exercised traveler
* A view of God`'s goodness, and anciently with Noah, Abraham, etc.
* Trials about the war, paper currency and taxes
* An address to Zion
* His sickness, and other trials
* Waits in silence, etc.

AT this time I kept a school for Friends children in the town of Providence;
and having for several years past believed at times,
that it might be best to preserve some account of my
pilgrimage through the wilderness of this world,
I now began a more regular and constant journal of my exercises,
and the Lord`'s gracious dealings with me, than I had heretofore preserved.
I had before made a few minutes of some remarkable occurrences,
which (together with what was fresh in my memory,
and so recorded there as not likely soon if ever to be
obliterated) enabled me to write the foregoing account;
and thus to bring it forward to this time.

On the first day of the week, the 1st of the 1st month 1775,
I fell and received a small wound which was attended with considerable soreness and pain;
and next day having in addition to this a turn of the nervous or sick headache,
I was confined to the house:
and hope these light afflictions were not wholly useless to me,
in regard to my best interest.
O! that every trial may help to refine and prepare my soul for the city of my God.

Fourth-day 11th, went to quarterly meeting at New-Port; it held two days,
not very lively; yet a remnant were concerned to labor for the welfare of Zion.

1775+++.+++ About these days I went through great discouragements and heavy exercises;
but was mostly enabled to hope and believe it was all for my good, and would tend,
if rightly endured, to my furtherance and enlargement in divine things; and,
blessed be the name of him who led and supported me through them;
he did indeed arise for my help and consolation, even with healing in his wings;
and that too, when I was almost ready to faint, and despair of his help;
which made me hope I should trust in him, and rely upon him, for the future;
even in and through all trying dispensations.
Indeed it is easy to hope and believe we shall trust in the Lord, when he shines upon us,
and sheds abroad his love in our hearts,
making us livingly to joy and rejoice in his presence,
which was now graciously my happy experience;
but alas! when we have again and again to pass through the valley and shadow of death,
it is not so easy to stand firm, keep the faith, and trust in God.

My exercised soul has had large experience of these heights and depths;
and knows that nothing but divine power can uphold us in times of deep
probation which we must pass through in our travels towards the land of rest.
And O! that none may give out in such seasons, or faint in their minds;
it is no new thing; it is the beaten path,
and all the Lord`'s ransomed must become acquainted with it, and travel in it,
not taking their flight in the winter; and as they thus stand firm,
they will joyfully witness, in the Lord`'s time, the winter to be over,
the summer to advance, the time of the singing of birds to be come,
and the voice of the turtle to be heard in their land.
Oh! the pangs and sufferings through which some have waited
again and again for the return of these blessed enjoyments,
these moments of refreshment from the presence of the Lord;
but none have ever rightly waited on the Lord in vain.
Therefore trust in him, O my soul forever,
for in the Lord Jehovah is everlasting strength.

Fourth-day 25th, I attended our monthly meeting at Smithfield, upper meetinghouse;
found some dear friends sympathized with me in my deep probations:
and was particularly comforted by a letter from a dearly beloved friend,
written in a manner well suited to assist and encourage my
drooping mind-- May I ever walk worthy the remembrance,
sympathy and prayers of my friends.

Fifth-day, 2nd of 2nd month.
In time of silence and retirement in family devotion,
wherein we were engaged to wait upon the Lord, for the renewal of strength together,
my mind was livingly opened into a fresh and humbling sense of
the unspeakable love and goodness of God to poor, frail,
finite man in ancient days--particularly I was bowed in
consideration of his wonderful dealings with Noah;
and how he was with him in the ark;
and how he taught him to prepare it for his own and family`'s preservation:
how he was with Abraham when he left his father`'s house at his command,
and went forth not knowing where he was to go: also how he was with Israel in Egypt,
through the Red sea, the wilderness, and Jordan; with David, when he fled from Saul,
being hunted as a partridge upon the mountains; with Jonah, in the whale`'s belly;
with Daniel, in the lion`'s den; and the three children, in the fiery furnace;
with his own well beloved son,
in the great trials and temptations which he was
led through in the wilderness and among men:
also how he was with the apostles, and supported them when men rose up against them;
and through all their perils by sea and land, and by and among false brethren.
What shall I say?
he has ever been a sanctuary and safe hiding place for the righteous in all ages,
and remains to be so still;
and as truly and powerfully so now as ever.--And as my mind was thus led and opened,
earnest breathings were begotten in me, that we of the present generation,
who have known his lovingkindness, may walk worthy of the continuance thereof,
and never distrust his care and providence; assuredly believing,
that he who has been with us in six troubles will not leave us in the seventh,
if we firmly trust in, and steadfastly follow him.
But if we should draw back, his soul would then have no pleasure in us.--Oh! therefore,
says my soul, that we may be vigilant, knowing that our adversary the devil,
like a roaring lion, goes about continually, seeking whom he may devour.

In the sixth month I attended our yearly meeting on Rhode Island.
John Hunt and Nicholas Waln from Philadelphia,
and William Jones and Benjamin Sweat from New Jersey,
attended said meeting--It held a number of days,
the several sittings thereof being times of divine favor;
the souls of some painful travelers Zionward
were greatly encouraged and rejoiced in the Lord.
Dear John Hunt was livingly opened in gospel love and
authority several times among us in these meetings.

On first-day the 18th of 6th month,
a paper was sent from our deputy-governor to the Friends of our meeting,
requesting that such as had small arms would produce them at the courthouse next day,
in order that the guns in the government might be known,
and an account thereof sent to the continental congress.
After mature consideration,
a paper was signed by such male members of our society as lived within the town,
in answer to said request,
informing that our religious principles and
conscientious persuasion did not admit of a compliance.
This was carried to the deputy governor, who received it kindly, and seemed satisfied,
saying he believed liberty of conscience was the natural right of all mankind.
Thus the Lord made way for us, blessed be his holy name forever.

Much close exercise of mind I had for a considerable length of time,
on account of some particular scruples which from time to time revived with weight,
and so pressingly accompanied me, that I could not get rid of them.
It being a time of war, and preparations for war between Great-Britain and America,
and the rulers of America having made a paper currency professedly
for the special purpose of promoting or maintaining said war;
and it being expected that Friends would be tried by requisitions for taxes,
principally for the support of war; I was greatly exercised in spirit,
both on the account of taking and passing said money,
and in regard to the payment of such taxes, neither of which felt easy to my mind.
I believed a time would come when christians would not so far
contribute to the encouragement and support of war and
fightings as voluntarily to pay taxes that were mainly,
or even in considerable proportion, for defraying the expenses thereof;
and it was also impressed upon my mind,
that if I took and passed the money that I knew was made on purpose to uphold war,
I should not bear a testimony against war, that, for me as an individual,
would be a faithful one.
I knew the people`'s minds were in a rage against such as, from any motive whatever,
said or acted any thing tending to discountenance the war.
I was sensible that refusing to pay the taxes, or to take the currency,
would immediately be construed as a pointed opposition to the present war in particular,
as even our refusing to bear arms was,
notwithstanding our long and well known testimony against it.
I had abundant reason to expect great censure and some
suffering in consequence of my faithfulness,
if I should stand faithful in these things,
though I knew that my scruples were unconnected with any party considerations,
and uninfluenced by any motives but such as respect the propriety of
a truly christian conduct in regard to war at large.
I had no desire to promote the opposition to Great-Britain;
neither had I any desire on the other hand to
promote the measures or success of Great-Britain.
I believed it my business not to meddle with any thing from such views;
but to let the potsherds of the earth alone in their smiting one against another:
but I wished to be clear in the sight of God,
and to do all that he might require of me towards the more full introduction
and coming of his peaceable kingdom and government on earth.
I found many well concerned brethren,
who seemed to have little or nothing of these scruples;
and some others who were like-minded with me herein.

Under all these considerations the times looked somewhat gloomy;
and at seasons great discouragement spread over my mind.
But after some strugglings,
and a length of close exercise attended with much
inward looking to the Lord for direction and support,
I was enabled to cast my care upon him, and to risk myself and my all in his service,
come whatever might come, or suffer whatever I might suffer, in consequence thereof.
I was well aware of many arguments and objections against attending to such scruples;
and some seemingly very plausible ones from several passages of scripture,
especially respecting taxes;
but I believed I saw them all to arise from a lack of clear
understanding respecting the true meaning of said passages;
and I knew I had no worldly interest, ease or honor,
to promote by an honest attention to what I believed
were the reproofs and convictions of divine instruction.
I well knew, not only by reading, but experimentally,
that He that doubts is condemned if he eat;
and that what is contrary to faith and conviction is sin;
therefore I chose rather to suffer in this world than incur the
displeasure of him from whom comes all my consolation and blessings.

In the 9th month this year 1776, in company with my dear friend Moses Farnum,
I visited Friends at Richmond, in New-Hampshire government,
a branch of our monthly meeting.
We were twice at their meeting, and visited I believe all their families.
It was an exercising time to me;
and I was almost wholly silent both in meetings and families;
and even much restrained from conversation.
Yet I had a hope that all was working together for my good;
and I endured my trials with a degree of patience,
though I often groaned inwardly for deliverance: however the Lord brought me through all,
and gave me to rejoice in his salvation.

Fifth of tenth month.
Having for nearly a year declined taking the paper currency,
agreeably to the secret persuasion which I had of my duty therein, as before mentioned:
I have now the satisfaction of comparing the
different rewards of obedience and disobedience;
for though, from the very first circulation of said money, I felt uneasy in taking it;
yet fears and reasonings of one kind or another prevailed on me to take it for a season;
and then it became harder to refuse it than it would probably have been at first:
but growing more uneasy and distressed about it, at length I refused it altogether,
since which I have felt great peace and satisfaction of mind therein;
which has in a very confirming manner been increasing from time to time,
the longer I have refused it: and although I get almost no money of any kind,
little other being in circulation,
yet I had much rather live and depend on Divine Providence for a daily supply,
than to increase in the mammon of this world`'s goods,
by any ways or means inconsistent with the holy will of
my heavenly Father--and the prayer of my soul to him is,
that I and all his children may be preserved faithful to him in all his requirings,
and out of that love of things here below which
alienates from the true love of and communion with him.

In the 11th month this year I visited, in company with a Friend of our monthly meeting,
the meetings and many of the families of Friends on Rhode Island,
and had much satisfaction therein; for though I had hard work in some families,
and passed through some close exercises,
yet the Lord was with me and bore me up through all,
opening my way in the spring of divine life,
and furnishing with suitable matter for communication,
to the relief and consolation of my own mind,
and I hope to the benefit and comfort of others.
And it was remarkable to me, that in a very short time,
indeed not many days after I had thus discharged my duty,
and paid this legacy of love to my dear friends on this island,
the king`'s troops took possession thereof,
whereby the communication was greatly obstructed for a
considerable length of time between Friends there and the main,
that, had I not given up to perform this small service just as I did,
and when the weight of it was livingly upon me,
it is probable I might never have done it at all, or not to much satisfaction.

A sense of the Lord`'s goodness in enabling me to go in the right time,
and to find relief and satisfaction in the visit,
bowed my mind and raised desires therein,
that I might ever live like one who knows himself to be but a pilgrim on the earth,
and that God alone can sustain him.
Amen.

First-day, 8th of twelfth month.
Several Friends of our meeting at Providence became exercised in
regard to a commotion that was prevailing among the inhabitants.
It was said, and I suppose was true,
that a British fleet with troops had been seen not far from Rhode Island;
and it was supposed they were aiming to come into New-Port harbour,
and probably up the river to this town.
This greatly surprised many of the inhabitants.-- Many moved their goods,
and some their families out of town, in great haste and precipitancy.
The town seemed in an uproar; carts rattling, and teams driving all night; and,
among others,
a few Friends in this sudden consternation were
induced to move some of their effects also,
and a small matter was done at moving their families: and this being,
in the view of some concerned Friends, a weighty, serious matter,
a conference was held after the afternoon meeting upon the occasion,
some Friends of other meetings also being present,
and though nothing censorious or uncharitable
appeared in any respecting the conduct of any,
yet it was advised that Friends should be very careful to act in moderation,
and not in the hurry, but wait for clearness,
and for ability to act becoming our holy profession.
Next day this advice was further inculcated by
the meeting for sufferings which sat in town,
and which, after solid consideration, advised that Friends keep still and quiet,
and do no more, unless, upon deep and solid consideration,
the way should be clearly seen for any one to move.
It was also thought advisable for Friends in all things to
conduct so as not to increase the commotion and intimidation
which was already too prevalent among the people.
This advice was very savory to some of our minds,
whose exercise was great on this occasion; and whose travail of soul was,
that Friends might be preserved in the stability of the unchangeable truth.

Fifth-day, 12th of 12th month.
My mind was impressed so deeply with a lively sense of
the excellency and necessity of true christian charity,
that I had to speak of it in our meeting in the constrainings of the Father`'s love,
laboring to encourage Friends to cultivate this excellent virtue,
in their own minds and in each other.

First-day, 5th of 1st month 1777.
For the lack of close attention to the word of divine life in my own soul,
I made a blunder in my public testimony, which greatly humbled me,
and made me very careful and watchful afterwards.
O! it is good to trust in the Lord with all our hearts,
not leaning to our own understandings.
It was relying too much on my own understanding and
memory which brought this great anxiety upon me.
And I record it for future caution, mean-while beseeching God Almighty to preserve me,
and all his true gospel ministers in the right line of safety and divine qualification,
which is in and with the opening of the Spirit, and with the understanding also.

Fifth-day, 3rd of 4th month.
After a few words which I became concerned to express in our week-day meeting,
my mind was so clothed with the spirit of prayer and supplication,
that I was prevailed upon to kneel down and publicly address the throne of grace.
This was the first time I ever appeared in vocal public supplication;
and it was truly much in the cross, as also in great fear and reverence.
It was indeed to me an awful thing publicly to call on the name of the Lord,
and I have been many times sorely grieved at the light,
easy and unfeeling manner in which many do it.
A few weeks after this, namely, the 25th of the 4th month,
in writing a little piece on a special occasion,
after particularly and affectionately mentioning the tender feelings and
emotions of my heart towards several particular friends and acquaintances,
my soul seemed overwhelmed with love and almost
unutterable good-will to the people of the Lord,
wherever scattered, the world over;
in the fresh flowings whereof I enlarged nearly as follows:

[.embedded-content-document]
--

But above all, O Zion,
you city of the living God! what shall I say to you! all that is alive
within me is moved at your being now brought into my remembrance! how shall
I express the overflowings of that love I now feel for you;
or that ardently travailing exercise,
which in the rolling of tender bowels engages my soul for your everlasting welfare!
May the Lord of hosts encamp round about you, as a wall of fire for your defense.
May you know an abiding in your tents, O Israel!
Let not the earth, nor all its enchantments, entice you from the cross,
O Israel! the Lord alone can keep you, and he only is worthy of your closest attention.
Keep near, keep near, O chosen generation; keep near your divine teacher,
who is graciously vouchsafing to teach you himself!
Dwell deep, O you travailing souls, give not back; go on with him that has called you,
although it may be through fire and water; through frowns and reproaches:
the everlasting arm will be underneath to support you, as you make God your refuge,
and continue faithful in the glorious work of reformation,
which he is fitting some of you for.
My life in tenderness runs out towards you: you are as bone of my bone,
and flesh of my flesh.
Oh! may the Lord protect and preserve you--may the
blessings of the everlasting hills rest upon you;
and especially upon such of you as have been as it were separated from your brethren,
and devoted to the great work of the Lord in the earth; and be assured,
if you hold fast the beginning of your confidence and engagement steadfastly to the end,
no weapon formed against you shall ever prosper;
the tongue that rises in judgment against you shall be condemned,
and even though Gog and Magog wage war and oppose you,
the Lamb and his followers shall have the victory.

--

--And as I have good grounds to believe this was written in the good-will of
'`him who dwelt in the bush,`' I feel easy to transcribe it here,
and give it a place in these memoirs.

Having some time before this dismissed my school at Providence,
I opened one at Smithfield, on the 12th of the 4th month 1778, under the care,
inspection and direction of a solid committee appointed
by the monthly meeting for that purpose.
Soon after this, I took several colds one after another, until at length,
on the 26th of the 2nd month, leaving our monthly meeting,
being quite unable to sit through it, I went to my sister`'s,
where I was confined several weeks, brought very low,
and at times ready to doubt my recovery.
Indeed many of my friends and relations pretty much gave over expecting it.
I was, after a season of deep exercise and probation,
enabled to resign up life and all into the hands of him who made me,
and to say in sincerity, your will be done in life or death.
And as I lay one night in great distress of body, and deep thoughtfulness of mind,
I was drawn into an awful view of death, eternity and eternal judgment,
in a manner that I never had before;
but feeling my mind perfectly resigned to depart
this life and launch into an endless eternity,
if so the Lord my God should please to order it;
and finding all pain of body and anxiety of mind removed, I lay still some time,
thinking probably I might before long be released from all the pangs and toils of time,
into the glorious rejoicings of eternal life.

But, after a considerable length of time had passed
in inward and profound stillness and adoration,
large fields of labor were opened,
and I saw that I must travel from place to place in this and distant lands,
in the Lord`'s commission and service.
From this time I never entertained a doubt of my recovery,
although I had afterwards a return or two of the disorder more severe than before;
for these openings were in the fresh evidence of divine life, which never deceived me.
A flow of divine favor, in the sheddings abroad of the love of God in my heart,
remained fresh and living with me through most of the remaining time of my illness.
After a few days I began to recover, and pretty soon got a little about again,
and before a great while attained my usual state of health:
may thanksgiving and glory and honor be ever ascribed by my
soul to him who has been with me in sickness and in health,
supporting and preserving me in both, and enabling me to resign to his divine disposal.
May I ever live answerable to such regard of the Highest to me a poor worm of the dust.
My soul has been bowed, self has been abased;
and through deep prostration I have been made to joy in the Lord,
and rejoice in the salvation of my God and Savior.

About the latter end of the sixth month this year, an old acquaintance of mine,
being now collector of rates, came and demanded one of me.
I asked him what it was for?
He said, to sink the paper money.
I told him, as that money was made expressly for the purpose of carrying on war,
I had refused to take it; and for the same reason could not pay a tax to sink it,
believing it my duty to bear testimony against war and fighting.
I informed him that for several years past, even several years before the war began,
and when I had no expectation of ever being tried in this way,
it had been a settled belief with me that it was not right to pay such taxes;
at least not right for me, nor in my apprehension, right in itself;
though many sincere brethren may not at present see its
repugnancy to the pure and peaceable spirit of the gospel.
I let him know I did not wish to put him to any trouble,
but would be glad to pay it if I could consistently with my persuasion.
He appeared moderate, thoughtful and rather tender;
and after a time of free and pretty full conversation upon the subject,
went away in a pleasant disposition of mind, I being truly glad to see him so.
Many such demands were made of me in those troublesome times for several years:
I ever found it best to be very calm and candid; and to open,
as I was from time to time enabled, the genuine grounds of my refusal;
and that if possible, so as to reach the understandings of those who made the demand.

The Lord, who is ever attentive to the good of souls and the exaltation of his kingdom,
is on his way, and truth will more fully break forth;
righteousness will come into dominion;
the mountain of the Lord`'s house will surely be
established above all the other mountains;
but many of the called, through lack of faithful attention to the call,
may never become the chosen, and so never come forth valiantly in the testimony,
nor stand immovable, nor triumph victoriously, in the Lamb`'s warfare.

I think I have seen in the light,
that too many that have come forth in a degree of true heavenly beauty,
and through the furnace, being in some degree refined,
have afterwards loved this present world, delighted in its friendship,
rejoiced in earthly accumulations, and let go their hold on heavenly good.
Alas, for these! if they were but as diligent,
watchful and solicitous for Zion`'s welfare, and to lay up treasures in heaven,
as they are to gather something on earth,
they would be sure to grow rich in faith and good works,
and become heirs of the heavenly kingdom.
These can never,
so long as their rejoicings are so much in earth`'s enchanting pursuits and acquisitions,
rightly bear truth`'s holy testimony, or lift up its standard to the nations.
No, no: this state prepares them at least to bear a superficial lifeless testimony;
but very commonly to reason, argue and dispute, and that too, as they think very wisely,
against the rising,
spreading and increase of the testimony and government of the prince of peace.
If there is not a diligent waiting at wisdom`'s gate and in the valley of humiliation,
in the true faith and patience of the saints,
the sense of divine things is gradually lessened and lost; and instead thereof,
a kind of reasoning takes place,
wherein the divine life and its blessed testimony is stifled and rejected;
and those who stand faithful therein are censured and condemned.

And, O you exercised travailing soul, whoever you are, hold on your way;
hold fast your integrity;
be not discouraged at the lukewarmness or lack of true judgment and discerning in others;
but be valiant for the cause of truth in your day;
and then notwithstanding all the opposition you may meet with, within or without,
the Lord will be your shepherd; the holy One of Israel will watch over,
protect and defend you; and as you lean wholly to the arm of his help,
and trust steadfastly in his divine light for your leader,
he will surely uphold and sustain you through all your
combats and fiery trials in this militant state;
and when your faithful warfare here below is fully accomplished,
he will receive you into his glorious church triumphant,
there forever to join the shouts and hallelujahs of saints and angels in a
glorious and unspeakable participation and fruition of perfect blessedness.

8th month 4th. I have now freedom to commit to writing a little of what I
have thought of the custom among many Friends of calling one another friend,
instead of calling them by their proper given names,
which I think deserves serious consideration, why this way of speaking,
to those whose names we are acquainted with, is continued in.
Is it not to shun the cross?
or because calling persons by their names John, James, Peter, Paul,
etc. sounds too unmodish, or as some may think, disrespectful?
Is there nothing of the spirit of the world in thus
flinching from strict plainness and simplicity?
If I am not mistaken, we shall,
whenever we arrive to the blessed estate the apostle mentions,
of having every thought brought into captivity to the obedience of Christ,
be willing to deny ourselves and take up the cross,
even in things that appear to be foolishness itself to this world`'s wisdom,
for it is in such things that God in his wisdom is often
pleased to exercise and prove the integrity of his children,
in order to confirm and establish their humiliation and
subjection of will to him and his holy law.
Here pride has no free scope;
the spirit and friendship of the world is carefully renounced;
and the cross in all its necessary operations submitted to and embraced.
A plain decent dress, a plain house, furniture and fare in all things,
will become the humble followers of a meek and humble Savior:
plainness and simplicity of language will best adorn a real christian.

In these days I often renewed covenant with my God--sat much
alone--kept silence--and bore his yoke and rod upon me.
Many days I spent nearly, if not quite, without condemnation; and I believe without sin;
though many others were so spent, as to cause more or less of anxiety and woe:
but I even found the ministration of condemnation was truly glorious,
because it prepared my mind for and led to the
more glorious ministration of justification.
Fervent was the engagement of my mind; and often my peace flowed like a river,
and Zion`'s welfare swallowed up almost all other considerations and concerns.

Much travail did I often feel for the preservation and
growth of the Lord`'s visited children,
I mean those who had become livingly sensible of the operations of
his divine power upon their spirits--and to some of these I wrote
once in a while an encouraging or persuasive letter,
a considerable number of these I have by me, but, to avoid swelling these memoirs,
I omit them here,
as also a great part of the minutes and memorandums which I made of my exercises,
watchings,
strivings and trials in those days.--In the time of
waiting on the Lord in silent retirement alone,
which was mostly my daily practice,
it sometimes pleased him to veil his holy presence from me,
in order to prove my patience and steadfast reliance upon him;
and sometimes to command a solemn awful silence in me,
wherein he often stood revealed in majestic all-sufficiency before me,
in a manner which I have no words to convey a clear idea of to
any who have not experienced the same in themselves.
But I am assured that all, who rightly wait upon him in their own minds,
will find him a God nigh at hand,
and graciously disposed to replenish and satisfy the hungry soul.
I do not believe a man can go aside, and sit down alone, to make the experiment,
merely to see what the consequence of sitting in silence will be,
without a real hunger and heartfelt travail;
and therein be favored with the flowings of the holy oil.
But none ever wait rightly and perseveringly upon God in vain.
The incomes of his love afford more true joy, than all earth`'s richest enjoyments.
A feast of fat things, of wines on the lees well refined,
is the comfortable portion of his chosen.

In these awful approaches I beheld at times with clearness the kind
hand of the Lord in leading me through many deep probations.
I viewed his overturning influence among men, in these outwardly troublesome times;
and now and then my prospects were livingly extended in great good-will,
and rolling of bowels, towards the church in general, and some places in particular,
with a living evidence sealed on my heart, that, if I abode faithful,
I must devote considerable time in the service of the gospel in my day and generation.
My soul, under the animating influence of these openings and prospects, at seasons,
bowed in reverent prostration before Emmanuel, God with us.
