== Chapter IV.

[.chapter-synopsis]
* On taxes for war
* Visit to some families in Dartmouth, and to Moses Farnum in his last sickness
* His marriage
* Visit on Rhode-Island
* Concerning spirituous liquors
* On procuring this world`'s goods
* Thanksgiving, a Poem
* Family visit in his own monthly meeting

AT our yearly meeting this year 1779, the subject of Friends paying taxes for war,
came under solid consideration.
Friends were unanimous, that the testimony of Truth, and of our society,
was clearly against our paying such taxes as were wholly for war;
and many solid Friends manifested a lively testimony
against the payment of those in the mixture;
which testimony appeared evidently to me to be on substantial grounds,
arising and spreading in the authority of truth.
It was a time of refreshment to an exercised number,
whose spirits I trust were feelingly relieved,
in a joyful sense of the light which then sprung up among us.
On the whole, I am renewedly confirmed,
that however the burden-bearers of the present generation among us may hold on their way,
or fall short and give back, the Lord will raise up a band of faithful followers, who,
preferring Jerusalem`'s welfare to their chiefest joys,
will press through the crowd of reasonings,
and follow the Lamb whithersoever he leads them.

 In those days I passed through many trials and exercises,
unknown except to God and my own soul: but he knew my heart, and all my tribulations,
and how to carry me through them;
and blessed be his holy name! he supported and bore up
my drooping mind through every probation and besetment.
At times I clearly saw he was refining me in the furnace of affliction;
then why should I murmur or repine?
Or why do you murmur, Oh! afflicted soul, whoever you are?
for unless you endure chastisement of the Lord, you are a bastard and not a son.
By his fatherly chastisements he brings into the obedience and filial
attachment of sons--he enables to sing of mercy and of judgment;
and confirms his children in a steadfast reliance upon himself,
through every storm and tempest.
O! bless his holy name forever--exalt and praise him,
even for the turning of his hand in probation;
for the exercise of his rod in chastisement.
It is all for good, and will surely work good to all who rightly abide the trial.
Indeed every trial ought to be received with thankfulness,
as intended and working for our good.
And seeing afflictions are oft the most substantial
blessings to a true christian traveler,
let us in true resignation of heart, under each painful stroke,
ascribe goodness to our God, and, in the pathetic language of Young,
render him the tribute of thanksgiving, and say, '`For all I bless you,
most for the severe.`'

In the twelfth month this year, in company with my dear friend Elisha Thornton,
I visited several families of Friends at Dartmouth.
It was a time of great trial: I was shut up in silence,
pain and poverty of spirit in several families.
I felt like a wanderer through a trackless desert; yet,
not being easy to quit the service, I went on, but still for some time found no relief,
more than a consciousness of integrity to my God; but, magnified be his name forever,
in depth of distress he heard my cry, and arose with healing in his wings;
and was graciously pleased to command deliverance.
My tongue again was loosed; and, with tenderness and contrition,
I declared of his dealings; with gratitude, I sang of his salvation.
He clothed me with the spirit of supplication: I drew near him with renewed confidence,
and, after several seasons of relieving communication, returned home, saying in my heart,
'`it is enough.`'

The 31st of the 3rd month 1780, I went to see my much beloved friend Moses Farnum,
at Uxbridge, in his last sickness.
His disorder was paralytic.
He could not speak so as to communicate much of his mind by words;
but the lively sensibility of his mind,
and the tenderness and brokenness of his spirit were refreshing to my soul.
Many Friends were present,
and nearly all were melted into tears and heart-felt tenderness.
He was just able to make us sensible of his great peace
of mind in his late religious travels;
and that the seal and evidence of divine approbation
therein was now impressed on his mind.
Light and life appeared to triumph over all in him.
He seemed resigned to every trial;
he also manifested great gladness that in health he had
settled and disposed of his outward affairs to satisfaction.

On the 11th of the fifth month he was decently buried,
having gradually declined until death removed him from works to rewards.
I trust he now enjoys a mansion of undisturbed repose in the paradise of God.
He was in the latter part of his life a pillar in the Lord`'s house:
a faithful watchman on the walls of Zion.
And his memory is precious.

On the 1st day of the 6th month this year, 1780, at our meeting in Providence,
I was married to Eunice Anthony,
daughter of Daniel and Mary Anthony.--The following I wrote her just
after my first addresses to her on account of marriage:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
North-Providence, 22nd of 1st month. 1780.

[.salutation]
Most affectionately beloved,

After reading over several memorandums of the exercises my poor soul
has passed through in my pilgrimage through this vale of tears,
my heart salutes you in a fresh spring of that love which I feel increasing,
and hope may never wax cold towards you.
And having felt you abundantly near this evening,
I am free to write what revives for your perusal,
hoping it may be useful towards our rightly stepping along through time together.

And first, dearly beloved, let me tell you,
that however short I may be of strict adherence to the Light of Life, yet it is my crown,
my chiefest joy to feel the holy,
harmonious influences and in-shinings of the love of Jesus my Savior upon my soul;
and I feel that without this I must be miserable indeed.
I also believe that the true enjoyment of the marriage-union consists
eminently in both being engaged to draw near to the Lord,
and act in his counsel; which I not only wish,
but in a good degree expect may be our happy case.
If it should,
though we have as it were a dry morsel to partake of as to the things of this life,
yet we may joy in the Lord, and rejoice in the God of our salvation.
You know I have no great things to invite you to.--If we are joined together (the
which I trust we already measurably are) we must not expect the paths of affluence;
no no.

[verse]
____
'`This day be bread and peace our lot,
'`All else beneath the sun,
'`You know if best bestowed or not,
'`And let your will be done.`'
____

This, my dear, our minds must come to, if we intend to be happy; yet this I know,
that one who cannot lie-has promised to add all things
necessary to those who seek first the kingdom of heaven,
and in this I confide.
Let us therefore unite in seeking this heavenly kingdom, and that in the first place.
And may we, the remainder of our lives,
earnestly press after resignation to the Lord`'s will; and, above all things,
strive to please him who only can give peace in whatever circumstances we may be.
Then I trust the guardian angel of his holy presence will encamp around,
and his everlasting arms be underneath to support us.
Farewell, my dear, farewell says your sure friend

[.signed-section-signature]
Job Scott

--

While I was from home at our quarterly meeting in the 7th month, I wrote as follows:
Lord, when I contemplate on your wonderful condescension to me a poor worm of the dust;
when I remember your early and repeated calls and visitations;
and how you plucked my feet out of the mire, and led me into the green pastures of life,
filling my heart with joy and gladness after condemnation for evil,
and chastisement therefor; my soul bows in reverence before you;
gratitude affects my heart.
But alas! when I take a view of my steppings along since those times;
my lack of constant stayedness in covenant with you; the weakness of my resolutions,
and my manifold infirmities; mourning and lamentation fills my heart;
sorrow and distress surround me.
Lord, what is man, that you are mindful of him?
and the son of man that you visit him?
Were it not for your mercies I must often have been rejected;
were it not for your tender compassions,
I must have been shut up in darkness and perplexity.
But, blessed be your holy name, through judgment and correction you have,
from time to time,
reduced me to that tenderness wherein the flowings of your love are felt to be precious.

In the 12th month this year our monthly meeting entered
my name as one of a committee to visit families.
My circumstances in life, and a prospect I had of visiting families on Rhode-Island,
brought some discouragement over my mind about this new appointment;
but wishing well to the service at home, and trusting in the Lord, I gave up to it; and,
passing on from time to time, I had some close exercise,
and some seasons of solid satisfaction.

In the 1st month 1781, I went to Rhode-Island, and having suitable company,
visited about forty-six families, and attended several meetings among Friends there.
In the course of this visit,
I passed through a time of painful stripping for a short season,
yet it was a time of great openness and divine favor
through almost all the meetings and sittings.
My mind was low, humble and dependent, almost constantly looking for the way to shut up,
as had been my experience at some other times:
but now it pleased the shepherd of Israel to fit and qualify for service.
The holy anointing oil flowed livingly among us.
Truth`'s testimony was again and again exalted;
the Lord`'s name and goodness magnified and praised,
and the hearts of the true worshippers rejoiced;
and the careless sons and daughters of Zion were admonished and warned.
I returned home with thankful acknowledgments to the author of all consolation for
this blessed season of heavenly enlargement and holy confirmation;
I was greatly relieved from the exercise that had for a
considerable time been impressed upon my spirit,
constraining me into this little field of service.

A concern having been growing among Friends for some time past to
discourage the frequent and unnecessary use of spirituous liquors;
and also to dissuade all our members from dealing in them;
some labor was bestowed with such as dealt in them as an article of trade:
they appeared well disposed; and the prospect was encouraging,
that Friends would pretty soon clear their hands of that kind of commerce.
And the use of such liquors is much laid aside among Friends in New-England.
It was once thought very difficult to do some kinds of business without them;
but now it is found by experience, that business is better done, and health,
strength and harmony, better promoted without them.

31st of 3rd month 1781.
I have for years felt strong desires to be wholly redeemed
from the improper pursuit of worldly enjoyments,
and even from all desires of wealth beyond what my heavenly Father knows I have need of;
as also from all use of things,
the procuring of which would require more of my time
than would be consistent with my religious duty;
or which would cause me, or any under me, to labor beyond the true medium;
or beyond the degree which best promotes health of body and tranquillity of mind.
I have mourned to see the true standard so lamentably departed from in these respects,
among all societies of professing christians.
Multitudes are miserably toiling and drudging, from day to day, and from year to year,
scarce allowing themselves time to assemble for divine worship,
nor scarce time to rest and refresh their bodies.
And many, when they do get to their religious meetings,
are too often so exhausted by immoderate fatigue,
that they are fitter for sleep than divine worship.
I am fully satisfied if men would keep to that holy principle which bounds the desires,
and gives content in a moderate way of living,
they would enjoy more solid peace and happiness than is
often experienced in the apartments of affluence,
or in the walks of magnificence.
What is all the glitter and show of high life in comparison of,

[verse]
____
'`What nothing earthly gives, nor can destroy,
'`The soul`'s calm sunshine, and the heart-felt joy.
'`True virtue`'s prize.`'
____

Thousands are anxiously aiming to keep up an appearance, which, though far behind many,
is yet above their real ability to support without injury to their circumstances;
indeed a little straining beyond our circumstances may embarrass us through life,
keep us upon the toil, and discompose our minds, or at least absorb our attention,
so as to embitter our lives, or prevent that true quiet,
wherein we might dwell so inward and resigned as to
_acquaint ourselves with God, and be at peace._
Moreover, it is too commonly the case that even religious people, that is,
such as have been really so for a season,
when they give way to this dangerous desire of wealth,
or of living too much as they see others live, that they gradually lose ground, until,
in their planning and contriving, they get more or less in a way of over-reaching,
or at least of crowding too hard upon those they deal with,
bearing them down in their prices,
or in some degree extorting too great a price for things sold them.
There are many ways to oppress a little, take small advantages,
and exercise some degree of extortion.
And when the mind becomes habituated and gradually reconciled to a less degree,
the way is too often paved to a greater degree,
until many things will go down pretty easily which would have
sat very uneasy upon the mind in days of greater tenderness
and more conscientious exactness and holy fear.
I doubt not many have seen and deplored these things in their early progress,
thought they would not for all earth`'s glory be overtaken in them, and yet,
letting out their desires after more than is fitting for them,
have slid gradually into the same error.
I have seen the progress of this spirit with sorrow,
and mourned over some who have been grievously entangled and ensnared in it.--

Oh! you traveler Zion-ward, flee, flee for your life, from all these allurements;
take God for your portion, and his Holy Spirit for your law and limitation.
Be content with what is convenient for you; there is more true joy therein,
than in all the accumulations of avarice.
I believe it will be good for me, and all that would live godly in Christ Jesus,
often to examine impartially, Do I exercise no degrees of extortion?
am I redeemed from the love and friendship of the world?
do I not give way to desires of living above what truth or my circumstances allow of?
am I not in the use of some things which are not necessary?
If you have this belief, see to it, and endeavor to deny yourself,
and be satisfied with such things, and supplies of them,
as your heavenly Father knows you have need of.

At our quarterly meeting in the seventh month,
a committee was appointed to visit the several monthly meetings, and labor,
as ability might be given, for a reformation.
--Some endeavors were used to dissuade Friends from that use
of things which promote not the true harmony of mankind,
nor do any essential good to those who use them.
This ought to be a serious consideration with all christians,
they that are Christ`'s have crucified the flesh, with the affections and lusts.

--What then have they to do with care, toil and anxiety, to procure things needless:
with pride, vanity and indulgence,
in the use of them?--All the use of this world`'s goods,
is but to provide for our outward comfort through this passage or life,
and yet how many make themselves slaves,
or at least greatly lessen or prevent their own comfort in life,
by giving way to the influence of improper desires, and imaginary needs.

11th of 12th month 1781.
O! that I may be preserved pressing forward with full purpose
of heart towards a state of perfect freedom from sin.
I know well that no one sin can be mortified and overcome, but through divine assistance;
but as certainly as the power of God upon us can, or ever does,
enable us to overcome any one evil;
so certainly it is able to assist us to the complete overcoming of all;
and we may rely upon it he will redeem us from all iniquity,
unless the stubbornness of our wills prevent.
If Jerusalem`'s children had given up their own wills, Christ would have gathered them.
According to his own testimony he would; but they would not.

4th month 22, 1782.
_Quietness,_ as a canopy, covers mine mind.

[verse]
____
Great God your name be blessed,
Your goodness be adored,
My soul has been distressed,
But you have peace restored.

A thankful heart I feel,
In peace my mind is staid,
Balsamic ointments heal,
The wounds by sorrow made.

Though elements contend,
Though wind and waters rage,
I`'ve an unshaken Friend,
Who does my grief assuage.

Though storms without arise,
Emblems of those within,
On Christ my soul relies,
The sacrifice for sin.

Though inward storms prevail,
Afflicting to endure,
I`'ve help that cannot fail,
In Him that`'s ever sure.

Though outward war and strife,
Prevail from sea to sea,
I`'ve peace in inward life,
And that suffices me.

Though clamor rear its head,
And stalk from shore to shore,
My food is angels bread,
What can I covet more?

Though ill reports abound,
Suspicions and surmise,
I find, and oft have found,
In death true comfort lies;

That death I mean whereby
Self-love and will are slain,
For these the more they die,
The more the Lamb does reign.

And well assured I am
True peace is only known,
Where he the harmless Lamb
Has made the heart his throne.

Then, then may tempests rage,
Cannon may roar in vain;
The Rock of every age,
The Lamb, the Lamb does reign.
____

Fifth month 23rd. I feel breathings of soul to be set
at liberty from the bondage of earthly cares,
that they may have no more share of my attention than duty requires.
I have seen with heart-felt pain the ravages of a worldly spirit;
I have mourned the desolations which the love of gain
has made among many who once in degree renounced it.

O Lord, God Almighty, I pray you arise for our help; for except you, O holy Helper, help,
there is no help for us:
the people whom you have called out of Egyptian
darkness will yet perish in the wilderness,
and never enter into possession of the promised land, unless you, O most merciful,
again make bare your holy arm for our awakening and furtherance in the way of life.

Our yearly meeting this year was graciously owned,
and overshadowed by the wing of ancient goodness: the Shepherd watered and fed his flock;
he sheltered his lambs, and prepared a banquet for his chosen,
and made them sweetly rest as at noon.

After the meeting was over, the language of my heart, in thankful acknowledgment,
was a language of praise.
I knew the blessing was from heaven: I knew the rain was not at our command;
nor was the table spread, and the feast prepared,
but by the bounteous hand of Israel`'s God.
Return, O my soul, to the place of your rest,
for the Lord your God has dealt bountifully with you.

The continuation of divine favor for some little time after this,
repeatedly rejoiced my spirit.
At length, through the all-wise overturnings of him who knew how to lead me on in safety,
I was again reduced to lack, and had to feel much inward leanness.
In this state I scarce had any thing to rejoice in but infirmities; but,
relying on him whose covenant is as sure with the night as with the day,
and who never forsakes those who do not forsake him, I felt,
in the midst of my strippings, and was therein stayed,
that patience in low times is an excellent anchor, and hope bears up the soul.

Ninth month 23rd. In reading the occurrences of
Abraham`'s life in Elwood`'s Sacred History,
my heart was deeply affected.--Oh! his faith how firm! his devotion how lively!
See him leave his father`'s house, his native land, and go forth at the call of the Lord,
not knowing where he went.
See him erecting his altar to the Most High,
and calling on the name of the Lord the everlasting God.

See him on Moriah`'s mount, resigning his beloved son!
What heart unmoved can view the transactions of such a life,
or read with indifference the dealings of the Almighty with
this father of the faithful?--He was the friend of God,
and God was his friend.
O that we, who boast the light of gospel days,
were true successors in the faith of Abraham: a living faith that wrought with his works,
and by his works of righteousness, devotion and true holiness, was made perfect.

In the 11th month, in company with other Friends,
I visited upwards of seventy families within the verge of our monthly meeting;
had great satisfaction in some places, and suffered deeply in others.
The author of all good was with us, and at times greatly refreshed our spirits.
In the course of this visit I had to view with sadness
those who were overcome by the god of this world.
Others I viewed as rising above the world, and laying hold on eternal life.
These felt near my spirit in the invisible relationship,
and I rejoiced in their success in the Lamb`'s warfare.
