== Chapter V.

[.chapter-synopsis]
* His removal to Gloucester
* His sister Sarah's death
* On silent waiting in families
* Visit to the quarterly and monthly meetings
* On strict plainness and simplicity of living
* Visits families at Richmond
* The true light, sun, moon and stars, alluded to
* On the six and seven days
* On the seven seals

On the 5th of the 4th month 1782, I moved with my family to Gloucester,
within the limits of the meeting of Uxbridge, a branch of our monthly meeting,
having for some time before believed, under various considerations,
and of different kinds,
that it might be best for me to spend a portion of my time in that neighborhood,
about eighteen miles from my home in North-Providence.
I fully expected to return again some time or other, but did not know when it might be.
I remembered the movements of Abraham, Isaac and Jacob, and in the recollection thereof,
a degree of solid satisfaction was afforded me.
I had some outward prospects in removing; but I not only did not aim at wealth,
nor expect an increase of outward substance,
but I had other and I trust higher motives in it
than related to my own temporal concerns.
And, soon after I became settled there,
I found a field of service opening before me in a religious line,
a sense whereof I had for some time had upon my mind previous to this removal.
There were a few precious souls here deeply and well engaged in the cause of truth,
and with whose spirits I was often livingly united in travail for the welfare of Zion,
and building of her walls.
We had times of deep probation; and, through holy help,
many seasons of rejoicing together in the Lord.
On the whole,
I had frequent confirmations that my being here was promotive
at least of my own growth in the everlasting truth.
Lord God! of all the holy ancient, be with me I pray you,
and guide me in the way wherein you would have me to go, no matter where or when,
so that your never-failing presence goes with me in all
my travels through the wilderness of this world,
to a house not made with hands, eternal in the heavens.
Amen.

Very soon after my removal,
my dear sister Sarah Hazard died at her home in South-Kingston.
She was a religious woman.
She improved much in true christian resignation,
and died in a fresh and living sense of heavenly joy.
I attended her burial, enjoying, in the midst of my mourning,
a satisfaction in a full belief that her removal from a world of anxieties and cares,
was a removal to an inheritance in the mansions of bliss.

I have been renewedly confirmed in the great advantage to families,
and even to small children, that results from sitting down in solemn silence,
and therein waiting upon God.
I have seen the children much broken and tendered in such seasons, so that,
even when there has not been a word spoken, the tears have rolled down their cheeks,
and their looks have been evidently expressive of heartfelt sensations.
This practice also learns them silence and subjection;
it curbs their wills and habituates them to restraint, and a patient waiting,
for their parents permission, to engage in their little diversions.
The habits of silence, subjection and patient waiting for permission,
are very useful to children from infancy to mature age,
and many suffer much for lack of it.
I have also seen much advantage to children, and indeed to whole families,
from the practice of a solemn pause at meals; it learns children stillness,
decency and reverence; and, where it is done in a feeling manner,
with minds rightly turned to feel after God and experience his blessing,
and is not practised in a slight formal manner,
it tends to season and solemnize the minds of young and old.
I have seen it done in a very careless lifeless manner, with scarce any reverence;
several of the family conversing not far from the table;
and scarce any sense of the divine presence prevalent in the minds of those around it;
and perhaps the pause scarce long enough to allow of much solid sensibility
or reverential acknowledgment of the favors received from the bounty of a
gracious God in the ample provisions of his providential care for our bodies;
or his continued extension of fatherly regard to our immortal souls.
I think such an undevout appearance can be very little to the divine acceptance;
but where a proper pause is observed, and the Lord is therein seriously sought to,
the mind being feelingly impressed with a sense of his aid and assistance,
and all branches of the family are reverently silent:
it is an oblation well-pleasing in the sight of God, and very useful to such families.
I am morally certain,
that I have many a day gone through the cares
and concerns of life with much more composure,
stability,
satisfaction and propriety for the strength and assistance I have
found in drawing near to God in solemn silence in my family;
and I wish the practice of reverently adoring him in this way,
may increase more and more.

Our yearly meeting this year was a favored season:
several weighty matters were transacted in love and christian condescension
through the qualifying influence of the master of our assemblies,
who graciously owned this our annual solemnity by the
overshadowing of his love and life-giving presence.
Some suitable advices were sent down to the
inferior meetings upon sundry important subjects.

After this meeting, in company with several other Friends,
who with myself were under the yearly meeting's
appointment to visit the quarterly and monthly meetings,
I visited Acoakset, Dartmouth, Nantucket, Sandwich and Swanzey monthly meetings,
Sandwich quarterly meeting held at Nantucket, and our own at Smithfield.
We found a lack of charity in some few, very strict in outward plainness, who,
from a misguided zeal,
held others too much at a distance on account of their
not appearing equally plain with themselves in dress,
etc. which was cause of grief to me, yet I am a hearty well-wisher to plainness:
I grieve to see the sorrowful departure from it into pride and superfluity:
I never saw an instance of any very considerable departure of this kind,
but what I had reason to be convinced that a real loss was sustained by the individuals,
or their best advancement prevented.
But I have suffered much deep distress of soul
under a painful and depressing sensibility,
of that contracted, illiberal and harsh spirit,
which in some instances has the ascendancy, leading them into extremes without the life.
I know that truth leads into great regularity and circumspection of life;
and I abhor that light chaffy spirit that makes ridicule of it,
and lightly esteems the exemplary appearance and true religious zeal of the faithful.
I doubt not many libertine minds may lay hold of such remarks as the
above to justify their own deviations from the plain path of truth,
the narrow way that leads to life;
and think thereby to screen themselves from the
just judgment of truth through the brethren;
but this will not avail them; the way remains, as ever of old, a narrow way,
a way of self-denial, and the daily cross.
But Oh unhappy and deluded people whoever they are, that in their zeal for externals,
lose charity.
They depart from the life and lay hold on formality:
for all outward things in religion dwindle unavoidably into formality,
in proportion as charity is departed from,
and zeal takes place in things pertaining to the outside of the cup and platter,
without a living sense of the inward spring of life
which can never be experienced without living,
fervent charity.
Therefore let us ever keep steadily to our plain way of living, in the life of truth:
for I am assured, so far as it is rightly kept to, truth owns and supports it;
and its influence on the mind is very beneficial.
But O, that we may ever be preserved from a narrow, rash, censorious spirit;
and from over-rating any outward regularity, or exact living; lest,
as we grow in the form, we dwindle as to the life.
Although these remarks may not have a very
extensive influence in rightly guarding others;
yet I must write what I have to write and leave it,
hoping divine providence will yet build up Zion and fortify Jerusalem,
directing the course of the sincere-hearted between all the extremes,
in the sure and safe path of virtue,
where a lively active zeal is tempered with liberality of heart and sentiment,
in the flowings of true charity.

We labored in the monthly meetings as ability was afforded,
and I trust to some solid satisfaction.
I got home to my dear wife and family the 8th of the 7th month, and,
finding them tolerably well, I left home next day to attend our own quarterly meeting.
Here I was rather too active in discipline.--I have found it
my business sometimes of late to be more inward in travail,
and less active in the exercise of the wholesome rules of society than I once was,
and believe, when I have obeyed the call into this inward, still abode,
and there felt my loins rightly girded,
it has contributed much more to the right exercise of the discipline, than when,
through a desire for its proper administration, I have, by over-acting,
seemed to do a good deal for its execution.

In the night, the 9th of the 8th month,
there was a frost which killed some of the vegetables, even some Indian corn.
This being so very early in the year,
and coming after a season of many refreshing showers,
and at a time of very fair and promising prospect of plentiful crops,
my mind was led into a train of serious reflections, how the Almighty,
who had thus brought forward our fields and prospects, could cut them all off;
and how entirely dependent we are upon his bounty for every blessing.
Were his compassions to fail, his providential aids to be withdrawn, alas! we,
poor frail mortals, should soon perish.

In the 9th month I visited Friends families at Richmond, New-Hampshire,
a very distant branch of our monthly meeting.
At several of our meetings at Uxbridge, not long after this,
I had livingly to sound an alarm among Friends;
and my soul humbly rejoiced in the relief I obtained in these few favored meetings.

1784, 2nd of 2nd month.
The exercises of my mind have for some time past rather increased, insomuch that,
for a considerable part of the time, I have felt like being in the furnace,
especially in meetings, but much so out of them also.
Indeed it has felt like the power and fire of the Lord laying hold of
the remains of pride and evil in me and burning like an oven;
that is, inwardly and fervently.
--May all be consumed that cannot abide the fiery trial.

And it has been gradually from time to time opened and sealed on my mind,
that a part of the scriptures,
which many generally understand to speak only of outward things,
may be understood by the truly enlightened to convey inward and spiritual instruction.
God's design is to confound the wisdom of the wise,
and bring to nought the understanding of the prudent.
He has hid and will hide divine things from the wise and prudent,
and reveal them unto babes.

The natural man not only does not, but cannot know them,
because they are only 'spiritually discerned.'
To this purpose Christ spake in parables,
that such as had an eye inward to the divine light,
which alone gives the true spiritual discerning, might understand,
receive and know the mysteries of his kingdom,
while all the wise and learned could but guess, mistake,
stumble and be confounded.--So when the disciples asked him why he spake in parables,
he informed them it was because it was given to them to know these things,
but to others it was not given.
It was not given to them, to the exclusion of any in the same state of inward seeking,
docility and child-like simplicity.

God's design was then, and ever will be,
to hide these things from all such as are striving to
know them by their own mere natural powers:
they may and do study the scriptures, and reason very copiously upon them,
and think they clearly comprehend their meaning, and yet remain in total darkness,
as to the spiritual import,
meaning and mystery of many passages which they
are strongly persuaded they understand rightly.

Before this wisdom and creaturely comprehension the stumbling-block is,
by God's determination and counsel, laid; on purpose laid,
that man ever may stumble and fall and be snared and taken,
so long as he goes this way to work to understand divine things;
not that God determines any certain number of persons shall so stumble, and be snared,
etc. but all universally on this ground, and in this wisdom;
for through all ages it is true,
if any man thinks that he knows anything he knows nothing yet as he ought to know.
Even Paul declares, I know nothing by myself.
While Paul thought he knew something divine by or of himself,
his reasoning rose against the Messiah,
and with all his might he sought against the only true way of salvation.
So, in degree, it will be with all; if they think they know,
even any thing divine of themselves,
or by the exercise of their own creaturely faculties,
they have never yet learned any thing as they ought;
for as soon as they know any thing as they ought,
they see and know that they knew nothing by or of themselves;
but are altogether beholden to a spiritual discerning
from the divine light shining in their hearts,
to give them this knowledge.
Hence says the apostle,

God, who commanded the light to shine out of darkness,
has shined (take notice where this shining is) in our hearts,
to give the light of the knowledge of the glory of God in the face of Jesus Christ.

Here, first, it is God that has shined; secondly, it is 'in our hearts;' thirdly,
it is to give us what we had not before, and could not have without this in-shining,
that is, the light of the knowledge of his own glory; fourthly,
it is 'in the face of Jesus Christ--' his inward appearance,
whereby he causes his light to shine upon us in order that we may be saved;
that we can ever see the light of the knowledge of the glory of God,
according to the true saying, In your light shall we see light.

His light shining 'in our hearts,' is the only possible
medium wherein and whereby we can see God,
or clearly discern his glory: for it is an eternal truth,
'whatsoever does make manifest is light,' Natural light manifests natural things,
and spiritual and divine light, spiritual and divine things.
As water rises but to the height of the fountain head;
and as effects cannot exceed their cause;
so nothing short of divine light can ever fully manifest him to the mind of man.

The scriptures will ever remain in great degree a sealed book
to the mere natural understandings of the wisest of men.
Volume after volume of commentaries have been written upon them, which, I have no doubt,
have often served, as a certain author has advanced, to entomb,
rather than enshrine them; or to darken, rather than explain their genuine meaning.
Thousands pass the time of their sojourning here below,
hoodwinked and muffled up in darkness,
under the baleful influence of this kind of theological
or systematical knowledge or speculation,
falsely called divinity.
But in the midst of all this learned ignorance, and, in degree, acquired blindness,
which overruns the nations;
the God of grace is not lacking in the extension
of his own immediate rays upon the minds of men;
those who turn from, disregard and rebel against the light, are justly left in darkness,
for being, as those in Job's days, of them who rebel against the light,
they know not the ways thereof, nor abide in the paths thereof.

But those who, while they 'have light, believe in the light,' and walk in it,
'they become the children of it,' and are led into all truth.

I may now proceed with my own exercises and openings.
It was clearly given me to behold many deep things in the visions of God;
things which the wisdom of the natural man,
though high in profession of divine knowledge, would probably laugh at and despise,
and me for my weakness, were I to unfold them.
But though I may not at present be permitted to unfold much,
I may say I have seen clearly to my full satisfaction, that Moses,
in writing of creation, of the fall of man,
and of things in the upright and in the fallen state,
wrote in the pure openings of divine light,
though very little understood by men in the first nature and state.
It is also plain and evident to my mind, in the light,
that the prophets saw things in the holy light of Jesus,
and spake of them in very instructive metaphors and expressions,
though hid from and unperceived by the wise and learned.

Many a sermon has been preached by those who call themselves ministers of Christ,
upon parts of passages out of the prophets, and the rest of the scriptures;
many heads of doctrine raised from them; many divisions and sub-divisions made;
much explanation attempted; and much art and oratory displayed; and yet the life,
marrow and main importance of the passage entirely unseen and untouched by the speaker,
and little or no instruction conveyed to the hearers;
and all for lack of a spiritual discerning of
the true intent and meaning of the scriptures.

Thus also the doctrines of Christ and his apostles,
as to their most lively and spiritual signification,
are to this day hid from the wise and prudent,
and sealed up with seven seals to all who witness not
their opening By the lion of the tribe of Judah,
who alone unseals them.
To these they are gradually opened, not all at once.

I have many things, says this wonderful counsellor and opener, to say unto you,
but you cannot bear them now.
So he opens progressively, as we are able to receive, one seal after another.
There are seven seals,
because none can ever come to the full understanding of the whole mystery,
and have all the book of life laid open, until they rest, and cease wholly from man,
from themselves, and all their own workings, guessings and conceivings,
which ever will attend them more or less through the six working days,
until they come to the complete sabbath of rest on the seventh day,
wherein they rest from their own works as God did from his.

Here God becomes their all in all, their whole dependance for opening and illumination;
and therefore here the seventh seal is opened, and the heavenly mystery disclosed.

And now, in confirmation that this is the meaning of the number seven,
as comprehensive of all the seals that can possibly
seal up divine truth from man,--let us observe,
that when John calls upon him that has wisdom, (divine wisdom,
for all else ever fails) to count the number of the beast, or the number of his name,
which he expressly says 'is the number of a man,' he plainly shows us that the whole,
the utmost number of a man, and of all his workings, buildings,
comprehendings and conceivings, which make up the whole life, power, policy,
religion and worship of the beast,
is comprehended in sixes--and that there is not one seven in it all.
For, says he, his number is six hundred three-score and six, that is, 666. Here we see,
that although the workings of a man may be multiplied to ten times,
and even a hundred times of the six working days,
wherein he rests not from his own works nor comes to
the true sabbath (wherein no creaturely work is done,
not even a fire of his own sparks or creaturely animation and warmth
kindled) it is all but the number of the beast or false worship,
and man-made creeds and systems.
On the real Sabbath, wherein the true rest from everything creaturely is witnessed,
and God is all in all, the worship is divine; the seals are opened even to the seventh;
the mystery is seen; God stands revealed to the soul; his works are known;
and in the true knowledge of him,
the beginning of eternal life is enjoyed even here on earth,
for it is the real knowledge of God, not the ideal conceivings,
that is the eternal life of immortal spirits.
And until this is attained, do as much as we will in the sixes,
there is the one thing needful lacking, which, while it is lacking, cannot be numbered;
for indeed we can never number or perceive it clearly, truly and fully,
so long as the seventh seal remains unopened to us.
For until they are all opened, we shall ever be liable to be guessing, contriving,
inventing and hewing out broken cisterns to ourselves.

Many may and do suppose the opening of the seals is only hereafter;
but those to whom they are opening and opened,
know they have their opening here in time progressively:
but this is only as God is waited upon.
For unless we wait upon him for the opening,
we are ever liable to obscure our own minds and cloud our
understandings by our own busy workings and speculations:
And therefore at the opening of the seals, Chapter 6,
the call, 'come and see,' was several times repeated;
intimating that we must come quite away from our own notions and imaginations,
keep a single eye to the light of life,
waiting upon God in and through the various openings.--In this attentive, single,
waiting state, deep mysteries are opened.
But instead of peace to the carnal mind, the openings begin with the voice of thunder.
For when the lamb opened the first seal,
John 'heard as it were the voice of thunder,' ver. 1. For terrible
things in judgment accompany that abasement of creaturely pride and
comprehension through which the vail is rent,
and the seals that have shut up the understanding opened.

Zion shall be redeemed with judgment.
In this work of redemption, renovation and removal of the seals,
(for it goes on gradually together) the Lord who is light in himself,
and ever dwells in the light, that is, in his own essence,
appears to our minds as breaking through the clouds.
The clouds are in us and not in him; and in dispelling them,
that so the seals may be opened,
he appears in ways of terror and amazement to the creature,
represented by the 'noise of thunder.'
Thus we read in another place,
'Clouds and darkness are round about him,' and 'with God is terrible majesty.'
And experience abundantly confirms, that, in dispersion of the clouds,
he often appears in terrible majesty indeed; causing the thunders,
and indeed before the whole mystery is disclosed,
even seven thunders to utter their voices.
Hence we find,
Chapter 10:1, John saw a 'mighty angel come down from
heaven,' and though a rainbow was upon his head,
and his face was as it were the sun, and his feet as pillars of fire,
yet (Oh! divine instruction) he was 'clothed with a cloud.'
This cloud must be removed before the whole mystery could be revealed;
and in order to it, he cried with a loud voice, as when a lion roars;
and when he had cried, seven thunders (note their number) uttered their voices.
Less than seven would have been short of the complete rest,
wherein the whole mystery is completed.

But in the days of the voice of the seventh angel, when he shall begin to sound,
the mystery of God should be finished, said the holy angel,
as he has declared to his servants the prophets,
see ver. 7. But John was commanded to seal up those
things which the seven thunders had uttered,
and write them not, ver. 4. This I believe is often the case for a season.
Some hints are allowed to be given; but as to the full declaration of divine things,
it is often with the servants as with the master, Mine hour is not yet come.
For though the time is to come,
when that which 'is spoken in the ear,' shall be 'declared on the
house-top;' yet it is not always and at all times so to be--for it
can never be with the divinely girded,
limited and directed servants of God, as with the letter-learned scribes and pharisees,
whose 'time is always ready.'
At the opening of the second seal,
the call 'come and see,' as at the opening of the first, is heard; for the waiting frame,
the single eye, is still necessary:
and now a 'great sword' is given to him that sat on the red horse;
and also power was given him to take peace from the earth, ver. 4.

Some may suppose the meaning of this opening by the red horse
confined so entirely to outward blood and bloody persecution,
as to have no relation to the state of their
minds who experience the opening of the seals;
but it is obvious to the enlightened mind,
that many passages in scripture have both an outward or literal,
and an inward and mystical meaning; and there really is a sword known,
and peace taken from the earthly man in the rending of the vail and opening of the seals:
a sore trial indeed to such as have not yet fully submitted to have
their carnal peace in the earthly natural state broken and destroyed.
But there is this comfort, that however peace is taken from this state,
yet at the opening of the third seal, a charge is given,
ver. 6. not to hurt the oil nor the wine.

The precious things are safe through every tumult and trial,
to all who rightly endure them.
But though a little hope and consolation is received now and
then by such manifestations of divine care and protection;
yet new tribulations soon plunge the baptized soul into
fresh and oft times greater consternation.

Thus at the opening of the next seal, his name, who rides the pale horse, is death;
and hell followed with him; ver. 8.
Oh! this death, this dying to the first nature and will; to the life of self,
and all corrupt and selfish desires and gratifications; it must be known and endured,
that so the life, which is hid with Christ in God, may be enjoyed,
which never was nor can ever be without dying with him;
and here the very pains and power of hell is felt, and takes hold of the soul.

Thus, under the operation of this necessary death, hell follows with it;
so that the distressed creature, like Jonah, cries out of the belly of hell.
And though I cannot believe or conceive it probable,
or even consistent with the truth of God or of the very mystery of divine things,
that Christ, after his crucifixion, descended into hell; yet I have no doubt that,
in the course of his sufferings and agony, he really did feel, endure,
and also conquer the force and power and pains of hell;
and so must every soul in which the sufferings of
Christ that remain behind are thoroughly filled up:
and until this is witnessed,
there is never a thorough rising with him in the newness of life:
but through death and burial with him, his resurrection is known,
and in the opening of this seal there is known, and painfully endured a killing,
by various means, as the sword, hunger, death, and even the beasts of the earth.

Oh! what is it that does not rise up to torment the poor soul!
but all works together for the good of the faithful;
no matter by what the necessary death is effected, nor by how many kinds of distress;
the Lord it gracious through it all, and wounds to heal, yes, kills to make alive.
Under the operations of these various modes, or messengers of death,
the language often is,

Oh! wretched man that I am, who shall deliver me from the body of this death.
It is painful enduring the sword to wound and slay; with pinching hunger,
and famishing lack, and sore afflictions from the bestial part,
which rages the more it is disturbed by that which comes to take away its life,
until the strength of its wild nature is weakened and broken.

After these sore trials are in a good degree endured, the fifth seal opens,
and brings to view the persevering follower of the Lamb, the holy altar,
and under it the souls of those that were slain for the word of God,
and the testimony which they held, ver. 9. Here the state of sufferings and persecutions,
endured by the righteous, is seen,
and also the state of rejoicing and triumph which follows after; for here they are heard,
availingly calling on the Almighty God, holy and true, for judgment,
and seen clothed in white robes, even 'every one of them.'

What an encouraging prospect is this when opened in the true light,
by the alone opener of the seals, the lion of Judah's princely tribe!
How does it reanimate the mind to persevere through all tribulations, dangers and death,
until the crown immortal is enjoyed!

Oh! the mystery of godliness; it is great indeed,
and never rightly understood by the carnal mind.
To these the book is ever sealed, and none but he who has the key can open the seals.
Carnal minded men may read of holy souls under the altar, and of their white robes,
etc. but to understand it, the inward eye must be opened,
and the book unsealed--then the right understanding is received,
and therein divine encouragement is felt, to stand firm in the testimony of Jesus,
even though they should be joined to the number of those
fellow-servants and brethren that should be killed,
ver. 11. Therefore the poor pilgrim journeys on, strengthened and revived;
and is thus enabled to endure the remaining
tribulations which are necessary for a full refinement,
and in order to the removal of all that can be shaken,
that that alone which cannot be shaken, may remain.--In order whereunto,
he who knows how to carry on the work,
dispensing the several parts and portions of probationary exercise in infinite wisdom,
and as they can be borne, soon brings on the fiery ordeal or purifying trial,
to complete the emancipation of his tribulated seed,
and bring out the prisoner with shouts of joy.
For now the sixth seal is opened,
which leads through renewed works of wonder and amazement, terror and abasement,
even to the stripping off of almost all that ever was attained:
for now the earth is made to quake, the sun itself is darkened,
the moon becomes as blood, the stars fall from heaven, yes,
the heaven departs as a scroll,
and every mountain and island is removed--there seems nothing to depend upon,
not so much as an island in the midst of the boisterous ocean,
to set the sole of the foot upon.--The drooping soul,
notwithstanding its late animating prospects, now almost sinks into despair;
nor sun nor moon nor stars shine in their usual luster.

This state is like that of the bridegroom of souls, when he cried out, My God, my God,
why have you forsaken me?
and the very same in degree that he then endured,
when total darkness covered all the land from the sixth hour unto the ninth,
must all the seed endure.--The eternal light of heaven, the emanations of the divinity,
are now obscured by fogs and clouds that intervene,
and blackness or darkness overwhelms the mind.
The fainter light of reason, the moon, affords no aid, nor scarcely shines,
or shines dimly, as we see the outward moon through fogs and vapors, red almost as blood:
for the weighed down mind is so distressed, tossed up and down,
that distraction or a cessation of intellectual arrangement
seems almost ready to overspread the whole man.
And moreover the example of the saints, the stars of past and present times,
which in serener moments, greatly stayed the mind, and spread reviving light around,
(for says Christ, you are the light or lights of the world) yet now this is all hid,
that there is scarce any thing that looks like light from any quarter.
--This is truly in a sense,
the great day of God's wrath upon all in man that is not to dwell with him forever.

Now the very kings, the great, the rich, the mighty; the bond and the free,
are ready to hide in dens, or wish to be covered by the mountains,
from the face of the all-searching God.
A time of trial, a season of anxiety indeed,
well known in the experience of the Lord's sanctified servants.

The more extensive and general signification and meaning of these mysterious metaphors,
I am not at present to enter upon here;
nor indeed is it very much our business as individuals to inquire.
Suffice it to know pride hid from us, the haughtiness of man laid low,
and every exalted imagination brought thoroughly down.
O! blessed, though for the present painful reduction!
Rejoice, O! christian traveler,
when you are so happy as to know the stronger bind the strong and mighty in you; yes,
rejoice in the very pangs and probations through which all his
goods and riches in you are spoiled,--and be cast out,
with all his pomp,
magnificence and merchandize forever.--For nothing
shall be able to stand or abide his coming,
but what cannot be shaken.
The pure gold endures the fire, and is not hurt or lessened in its brightness,
worth or weight.--The redeemed soul that has endured the saving,
cleansing baptism of Jesus, is by him made free; and these, and only these,
are free indeed;
and having endured the great day of wrath and judgment for sin in themselves,
their works are gone beforehand to judgment;
and they are not afraid of the day or wrath to the wicked;
for perfect love casts out all such fear; they are heirs of God,
and joint-heirs with Christ; they have part in the first resurrection,
and the second death has no power over them.

And now, having passed through the very hour and power of darkness;
endured the fiery trial; drank the cup the crucified Savior drank of,
and being baptized with his baptism, they come to witness,
as he did after his temptations, the ministration of holy angels.
Indeed he has promised all those who continue with him in his temptations,
a place in his kingdom; and as the angels ministered to him in the days of his flesh,
immediately after his sore temptation and trials, so is it in his brethren's experience;
for after their deep abasement and fiery baptism
in the afflictive dispensation of the sixth seal,
their prospects open into a discovery of the powers or
ministering spirits that stand on and over all that is earthly;
as John saw the four angels standing on the four corners of the earth.
Now the four corners seem to comprehend the whole earth;
and indeed it must all be shaken in us, if ever we know the new heavens and new earth,
wherein dwells righteousness:
to these four angels it was given to hurt the earth and the sea;
not only all that is of earth or earthly, but also all that is of an unstable nature,
is liable to the stroke and must be chastised and subdued.
But in the midst of all this destruction to the earth and sea,
another holy angel appears, ascending from the east, (that is,
from where the sun of righteousness ever arises with healing in his wings) and Oh!
the unspeakable joy and consolation which now springs and overflows the soul.
For sing, O you heavens! you ransomed of the Lord on earth, rejoice and praise the Lord,
for this is the angel that has the seal of the living God.
And now, after your many deep probations and seasons of discouragements and distress,
you are remembered in the very moment of renewed trial,
and of total destruction to all that can be shaken and removed; yes,
the sealing angel is now, at the very juncture of dismay, sent forth,
commissioned from on high, to stay the hurting of the earth and sea,
until he seals you in your foreheads--even with a loud voice he cries to the four angels,
saying, hurt not the earth, neither the sea nor the trees,
until we have sealed the servants of our God in their foreheads.

And now,
O ravishing consideration! not one of all the true
Israelitish tribes is overlooked or forgotten;
but each has its twelve thousand sealed!
If you are but one of wrestling Jacob's spiritual offspring,
and wrestles rightly for the blessing until the break of day,
in that which as a prince prevails, and has power both with God and men,
you shall surely, with Jacob your father, obtain the name of Israel:
and notwithstanding all your painful fiery trials,
the power you have with God will enable you to go on
conquering and to conquer all your soul's enemies;
and the holy angel of the divine presence shall seal you with the seal of the living God;
for you belong to the number of the hundred and forty and four thousand,
which were sealed of all the tribes of the children of Israel;
or to the great multitude which no man could number, of all nations, kindreds,
people and tongues, which stood before the throne and before the Lamb,
clothed with white robes, and palms in their hands.
And you shall, when the day of indignation is over, even in this life,
and also in endless fruition, join their songs of praise with a loud voice, saying,
salvation to our God, which sits upon the throne, and to the Lamb: yes,
you shall join the angels holy anthem; with them worshipping before God, and saying,

Amen: blessing, and glory, and wisdom, and thanksgiving, and honor, and power, and might,
be unto our God, forever and ever. Amen.

It is worthy of special notice, that in the midst of all this triumph and adoration,
it is not forgotten that a path of suffering and self-denial
was the way that led to these seraphic enjoyments;
for a question being asked, what are these which are arrayed in white robes?
and from where came they?
the answer was, These are they which came out of great tribulation,
and have washed their robes, and made them white, in the blood of the Lamb;
therefore are they before the throne of God, and serve him day and night in his temple;
and he that sits on the throne shall dwell among them.
They shall hunger no more; neither shall the sun light on them, nor any heat:
for the Lamb, which is in the midst of them, shall feed them,
and shall lead them unto living fountains of waters;
and God shall wipe away all tears from their eyes.
Now, having passed the fiery furnace; come through the great tribulations;
washed their garments, and received the seal of the living God;
the mind is prepared for the opening of the seventh and last seal,
which leads into profound silence.

And when he had opened the seventh seal,
there was silence in heaven for the space of half an hour.
Here all the powers of the soul are silenced; every faculty of the creature,
and all creaturely activity, is restrained! all vocal songs of praise, and hallelujahs,
cease! the angelic chorus of holy, holy, holy,
is suspended! and God is worshipped in inward, awful adoration and reverential,
solemn silence.--Rapturous devotion, superior to the use of words,
superceding vocal sounds, and which language, in its utmost sublimity,
can scarce ever describe; but which may be felt and experienced by the sanctified soul,
in a heavenly, ecstatic enjoyment, unknown to all the sons of Adam in the fall:
an enjoyment and adoration, a transporting felicity and fruition,
even in this life in degree,
which a full idea of can never be conveyed to an unregenerate soul,
by all the arts of description--all the powers of rhetoric or
elocution--and which the carnal mind can never conceive an
adequate idea of by all the reasonings of flesh and blood,
or penetrations of human wisdom.--The wise, the scribe, the disputer of this world,
may imagine and contend in ignorance and darkness;
but can never in that state have the living knowledge and experience of these things;
while they that endure the day of trial, continue with Christ in his temptations,
drink his cup, and abide his baptisms, his agonies and death,
thus resting from all their own works, come to the true christian sabbath,
and therein worship God in spirit and in truth,
in the pure living experience of that sacred, awful,
reverential silence which is known in heaven.
These know what is meant by the smoke of the
incense which continually ascends up before God,
from the angel's hand, and from the golden altar, forever;
and are in good preparation to witness and understand the remaining wonders--
the soundings of the angels--the measure of the temple--the leaving out of
the outward court--the woman clothed with the sun-- the dragon's tail,
and many other deep mysteries, which are never clearly understood,
but as he that has the key of David opens them.
But as far as needful he fails not to open them
to all who follow him in the regeneration,
wheresoever he leads them; who are redeemed from the earth, and from among men.
These shall stand with him on Mount Zion,
and having their Father's name written in their foreheads, shall sing the new song,
receive the blessing of those who obey his commands, have a right to the tree of life,
and enter in through the gates into the City.
--They shall rest from their labors, and their works shall follow them.

Great part of the Revelations, as well as other mysterious scriptures,
is livingly known in the work and progress of regeneration,
and therein found very pertinent and descriptive, in regard to the many exercises, pangs,
probations and deliverances, which attend the soul in its seasons of refinement,
and gradual renovation.--And all this hinders not, but well consists,
with the more outward meaning and fulfillment of such parts of sacred record,
so far as they really respect things outward: but I am firm in the faith,
that many are musing and gazing after outward fulfillments,
to the very great and sometimes injurious diversion of their minds from the only work,
and fulfillment of many passages, which they may ever properly expect to experience.
The scripture is a sealed book; it is abundantly wrapped up in parable,
metaphor and mystery--yes many, very many things in it,
which men whose minds are outward will read and understand of outward things,
are mainly meant of internal operations, discoveries and overturnings,
which God in his dealings with the soul, leads it along through.--He that has an ear,
let him hear,--is a very proper intimation, and is therefore often repeated,
that the mind may be directed to an inward hearkening, in order to a right understanding:
for many have eyes, but see not; and ears, but hear not.
The eye and ear that sees and hears divine things rightly, must be divinely opened.
Many are blind because they think they see; and deaf,
by reason of their confidence that they hear.
Christ's coming was and is, that those who see and hear may be made blind and deaf;
and that the blind and deaf may see and hear;
and blessed are these who are made blind and deaf by him;
for it is as needful to true seeing and hearing, to be first made blind and deaf,
as wounding is necessary to healing, and killing to being made alive.
He that will be wise, must first become a fool that he may be wise,
and he that will see and hear, must first become blind and deaf.

O, it is a great thing to know that eye and ear closed, that ever sees and hears amiss,
and to keep them steadily shut up; and the single eye and ear properly open.
Keep to that in you, O inward traveler, that shuts the wrong eye and ear,
and opens the right;
then will you be in the number of such as our Lord pronounces blessed, saying,
blessed are your eyes, for they see, and your ears, for they hear.
