== Chapter VI.

[.chapter-synopsis]
* The folly of self-importance
* The author`'s concern, that himself and others may experience an entire reduction of self
* and perfect resignation to the divine will
* His visit to Friends of Oblong and Nine-Partners, in the state of New York

I Have several times lately very clearly seen the great
folly of thinking ourselves of much importance,
either in religious society, or in the world.
O may my soul dwell ever in true abasement;
for blessed and happy is he that knows a being brought down, yes, down low,
and there abiding; for until all self-exaltation is entirely rooted out of our minds,
we are not what God would have us to be; and his turning and overturning in us,
is in order, if not resisted, thus to make us; and until we do,
from the centre of our soul, give him all the glory,
there remains in us a source of unhappiness,
disorder and confusion.--O man! how great is the work of your salvation;
how many deaths you have to die,
before that comes to reign in you which lives forever;--for know you,
that you can never fully enjoy that life which is hid with Christ in God,
until you die to your own selfish life.
It is he that loses his life for Christ`'s sake, that shall find it; yes,
our blessed Savior declares, if any man hate not his own life,
he cannot be my disciple--and at this juncture of time
I sincerely think I do so.--Lord God Almighty,
carry on your great work in my soul, bow every exalted imagination,
and lay all that is not of your own immediate begettings in me, level with the dust,
that I may altogether, and at all times, hate my own life, with perfect hatred,
until I come livingly to know that it is your only begotten,
in whom you are well pleased, and with no man further than he dies to himself, and lives,
in the son of your love, a life unknown to the benighted sons of Adam in the fall;
and only faintly conceived of by thousands that have known a degree of renovation.
Lord! when it shall please you, awake them, arouse and alarm them,
that they may arise from their lethargy,
and be enabled to look and behold Jerusalem a quiet habitation, and be admitted,
pure and perfect, into the communion and fellowship of her ransomed sons--where you,
O most holy, rule God over all, and self-exaltation finds no admittance.

Having for some time past,
felt drawings in my mind to pay a religious visit to
Friends of Oblong and Nine-Partners quarterly meetings,
and perceiving a like concern in my friend Daniel Aldrich,
of our monthly meeting of Uxbridge, we laid our prospects before our brethren at home,
and obtaining their certificates of concurrence from our monthly and quarterly meetings,
I left my dear wife and family in much heart-felt tenderness and affection,
the 19th of the 7th month 1784,
and rode that night to my said friend Daniel`'s house about nine miles; and next morning,
taking our solid leave of his family,
we got on our way between forty and fifty miles to Coventry, in Connecticut.
21st, we got to Litchfield, near fifty miles,
and next day the 22nd got to Friends fifth-day meeting at New-Milford,
upwards of twenty miles,
though we knew not that there was a meeting there of course that day,
but the probability made us press on a little, so that we reached it seasonably;
it was very small and silent.
I suppose it not far from one hundred and thirty miles from my home to this meeting,
and near all the way among Presbyterians, who used us civilly;
and I have reason to believe there is much more openness and
charity in many of their minds towards Friends than formerly.

Next day, 23rd, had a meeting at Oblong.
This meeting was open and favored--I felt engaged to encourage some who I
believe had felt something of the operation of the fiery furnace,
to keep in it, and not give back, until it had purified and refined them.

On the 24th of 7th month 1784, we were at the valley meeting.
I suffered the meeting through, under a close exercise,
but could not find a way sufficiently open to
attempt to clear my mind by public testimony;
from there we rode to my dear uncle Thomas Comstock`'s,
and next day being first-day the 25th, were at Peachpond meeting.
After meeting we dined at a Friend`'s house,
and had a favored opportunity in the family among a
number of young and a few elderly persons.

Second-day 26th, Rode to Andrew Merritt`'s, where Friends hold a meeting for worship.
Here we had an open meeting,
wherein they were tenderly entreated to more ardency of
engagement in the things that belong to their peace,
and warned of the danger of loving any thing more than Christ;
and we parted with them in great good will, they having been mostly reached and tendered,
under a sense of the ownings of the great Shepherd and Bishop of souls.
We then attended the meeting at Shappaqua,
which was a memorable time--may we never forget the loving kindness of him
without whom we can do nothing.--He it is that opens the sealed book,
and gives ability to dip into the states of meetings,
and drop a word suitably thereto.--O, that our dependance may ever be upon him, for,
as it is, we shall witness the insufficiency of human greatness, worldly wisdom,
self-importance or creaturely contrivance, and I have reason to believe that,
as it was our engagement this day, thus to bow before him, wait upon him,
and move in his movings,
we were made instrumental to reach the pure witness in many hearts;
and to leave impressions on them that will not soon be forgotten.

After meeting we had a family sitting nearly in silence.
I felt great caution not to move in words, unless a fresh opening induced me,
fearing I might be carried too far in the fulness of this day`'s favor,
as I believe I have seen some who have kept running on
in the strength of what was at first a true opening,
until they have bewildered their own minds,
and brought sorrow and confusion upon themselves.
Oh! how strict a watch is necessary lest we take our flight upon the
sabbath-day.--Lord preserve us in a constant dependance upon you,
and the openings of your holy Spirit!

7th month 28th and 29th. We attended the select quarterly meeting at the Purchase,
and their quarterly meeting for worship and discipline; in which my tongue, as it were,
clave to the roof of my mouth;
yet was enabled to keep in a good degree in the patience.--
After which we attended meetings at Mamaroneck,
West-Chester, Purchase, Ammawalk, New-Cornwall, New-Marlborough, Crum-Elbow,
Nine-Partners, at the Creek and Little Nine-Partners,
some of which were painful exercising seasons;
but in others we experienced a good degree of the dominion of truth over all,
particularly at the last meeting,
where the love of truth was felt sweetly to flow towards a pretty large gathering,
mostly not of our society,
and the doctrines thereof were opened among them
in a good degree of life and demonstration.

Third-day 10th of 8th month.
We went to the select preparative meeting at Nine-Partners,
composed of the ministers and elders of the two
monthly meetings of Creek and Nine-Partners.
The affairs of this meeting were conducted in a degree of the savor of truth.

Fourth-day 11th, attended the select quarterly meeting to pretty good satisfaction.
I felt truth`'s dominion over all in my mind,
and rejoiced in the loving kindness of the Lord.

5th-day 12th,
attended the quarterly meeting for worship and discipline at the same
place where the two foregoing select meetings were held.
The 13th, a meeting was appointed for us at Oswego, which was a pretty full meeting,
in which the current of gospel love, power and utterance, flowed freely and refreshingly;
it was indeed a precious opportunity,
and ought to be remembered with thankfulness to the great Opener and Leader,
who out of weakness makes strong--Blessed be the Lord.
The next day were at a meeting at Appoughquague, and 15th, being first-day,
we were again at meeting at Peachpond, on second-day at the valley,
and third-day at one called the upper meeting held at Isaiah Hoag`'s,
which was a very exercising meeting; but, after deep travail,
we were assisted and enabled to sound an alarm
among them in a degree of gospel authority;
and though

I believe we felt truth and the seed of life under oppression; yet as we lay low with it,
and were made willing to suffer with it,
we were enabled to witness it to reign in dominion over all.

Fourth-day 18th. Were at the monthly meeting at Nine-Partners;
some close exercise attended the forepart of this
meeting in silent suffering with the suffering seed,
but Truth rose into dominion to the joy of our souls,
wherein we had to call the people to an inward, awful stillness and attention,
lest they be disappointed as to meeting with the master of our assemblies,
and also as to being benefited with or by the true gospel ministry;
for those who can only run when the Lord sends them,
are often closed up in profound silence by the outward expectations of the people,
not having liberty,
as they keep to the openings and shuttings of him who has the key of David,
to gratify those itching ears.
--This and considerable more they were reminded of.
In the meeting for discipline, both men`'s and women`'s,
(for we were concerned to go into theirs) they were advised to keep to their own gifts,
and not depend upon one another, to the neglect of occupying their own talents,
lest they as individuals, and the meeting at large, suffer loss thereby,
and some forward spirits be pushed forward into too great activity in
a formal manner by the backwardness and withholding of others.
Friends were advised to be no longer grasping after things unnecessary;
for the procuring of them leads us into much care, cumber and expense of time,
thereby encroaching upon the time we ought to spend at meetings, visiting the sick,
etc. and cuts us off from sufficient time for inward retirement in our families,
as well as taking care of the affairs of the church.
Now all these services, when rightly engaged in,
greatly tend to our growth and refinement,
and real comfort and happiness in this life and hereafter;
as also to the promotion of the cause of truth in the earth.
Oh! how mortals grovel here in earth and earth`'s perplexing cares,
to their great loss of more substantial enjoyments; whereas,
if willing to be bounded by the girdle of truth,
we might have plenty of time for all our religious duties,
and have sufficient to spare to educate our children.
We were also concerned to caution against keeping
superfluities and gay things to sell to others.

Fifth-day 19th. Attended the adjournment of said
meeting to pretty good satisfaction.--20th,
attended the Creek monthly meeting, after which we attended meetings at Cloverick,
Coeman`'s Patent, New-Britain, East-Hoosack, White Creek, Saratoga,
and at a Place called Pitts-Town, where there is no settled meeting,
which ended to good satisfaction.

On first-day the 5th of 9th month, we attended meeting at Danby,
where I thought truth triumphed and had the dominion;
many minds were reached and tendered.--2nd-day 6th,
we appointed a meeting at a place called Durham, about twelve miles northward of Danby,
of which notice was given, and we attended it accordingly,
and had satisfactory service therein,
though among a people not much acquainted with Friends,
and exceedingly outward in their expectations,
and unacquainted with the advantages of inward waiting in solemn silence upon God.

Fifth-day 9th. Attended the preparative meeting at Danby,
at the close of which we sat a few minutes, the men and women together;
this was a little, comfortable season,
many minds being refreshed in this our parting opportunity.
6th-day, 10th of 9th month, we took our affectionate leave of our dear friends,
and set forward for home,
accompanied by our beloved friend E. S. My mind was
much affected at and after parting with Friends,
with great tenderness and tears of joy, which, for a considerable space of time,
flowed copiously from mine eyes.
My mind was carried back to view the places where we had visited,
and my soul was melted into ardent mental supplication
for the preservation of Friends in general,
and many individuals in particular;
attended with such endeared affection and brokenness of spirit,
as has rarely been my lot to witness for so long a time together.
Oh! with what heart-felt fervency did I intercede for the help and preservation of
the little flock and family up and down in the world! the earnest requests that I
was enabled to put up for the instruction and divine assistance of the many
messengers of the Lord which are running to and fro in the earth among the people,
that their labors may prove successful, and benefit the souls of mankind:
indeed the language of solemn supplication ran powerfully
through my mind with a melting sensibility for all;
that the dead might be raised, quickened and made alive,
in that life which is hid with Christ in God.
Many individuals of my acquaintance, both in places where I had visited abroad,
and also at home in our own and neighboring monthly meetings,
came fresh into my remembrance with such ardency of desire, and breathings of soul,
for their growth, preservation and improvement,
as will not readily be conceived by such as have not felt the same.
Yes, my desires for them were conceived in intelligent language in the secret of my soul,
in a number of little, short, though sweet and melting requests for one after another,
as the Father of Spirits brought them to my remembrance.
O! how often did it flow through me as a stream of life in this way:

O most mighty and omnipotent Lord God,
commission your holy angels to attend and guard your
exercised pilgrims through this vale of tears:
let cherubims and seraphims encamp about and surround the little host of militants,
your wrestling seed while here on earth and for evermore.

O! how did my bosom heave with swelling tides of joy and divine delight! yes,
all that was in me moved!--my head, my heart, yes,
my whole man seemed encircled round with spiritual attendants! whose
melodious and ecstatic songs of praise enraptured my soul,
and lifted me above all earth`'s tumultuous cares and all its
fading joys! and in the midst of this triumphant adoration,
my eyes were opened to see and view the depths of sufferings
and abasement which my soul had passed through in my visit;
then did I see that the true wrestling seed of Jacob can never rejoice,
but through sufferings; abound, but through abasement;
nor live and reign with the Lamb that was dead and is alive, but through death.
I then was given to behold as it were around me, as I rode on the way,
an innumerable multitude of glorified spirits; and it was said in the centre of my soul,
these are they which came out of great tribulation, have washed their robes,
and made them white, in the blood of the Lamb, their ever-living Redeemer.
I saw that I must yet longer endure the cup of sufferings in this house of clay,
if I would join the songs of those ransomed souls in never-ending anthems of praise;
to which I bowed my head and heart, saying, Lord, let not your eye pity,
nor your hand spare, until you have done away all that offends in me,
and brought forth judgment unto victory in my soul:
and when I had thus submitted and offered up body, soul and spirit, into his holy hands,
a willing sacrifice,
it was showed me how good it had been for me that I had so deeply suffered; and that,
had it been otherwise, I should have missed of this feast of fat things.
Next it was showed me,
that though I had not altogether done the best
that I might have done while on this visit,
yet that I had been preserved in the meekness, littleness and humility; and,
to my inexpressible satisfaction, I was also showed, and made to see, feel and know,
that nothing was laid to my charge as an offense to stand against me;
but feeling there was now no condemnation to my soul,
I was made to join the heavenly harmony; and,
in that angelic spring of adoration which I felt, my soul within me leapt for joy, and,
at the end of this transporting chorus, my inmost language was--sing praises,
sing praises, sing praises, Amen, Amen, hallelujah!

At which it seemed as if the whole expanse of heaven rang with acclamations of joy,
thanksgiving and praise!
After which I again had freedom to enter into innocent
and pleasant conversation with my two friends,
which I had not done for miles before as we rode on the way;
but I kept the vision pretty much to myself,
save what of its effects they discovered in my countenance, and the tears I had shed,
which I had not power to restrain.-- Lord,
never permit me to forget your favors and divine communications--but
as you have begun to clothe my mind with humility,
be pleased more and more to centre me deep into it;
that I may wear it as a garment forever.

We rode over the green mountain this day, in the state of Vermont, through which it runs,
takes its name from it, importing a green mount;
it is called about thirty miles over.--Lodged in Townsend.--7th-day 11th,
we rode near forty miles to Richmond.--1st-day 12th,
we attended Friends meeting at Richmond.--2nd-day 13th, we rode forty-five miles,
and on 3rd-day 14th of 9th month, home.
Was thankfully rejoiced to find my dear wife and family well,
having been from home eight weeks yesterday, rode about eight hundred miles,
and attended religious meetings forty days.
