== Chapter VII

[.chapter-synopsis]
* Prospect of visiting Friends of Pennsylvania and New-Jersey
* Exercises and sickness preceding his journey, and occurrences therein

After my return from the foregoing visit to Friends of
Oblong and Nine-Partners quarterly meetings,
I had to pass through much probationary leanness and inward privation,
and at times through deep and various exercises; but I had not been long at home,
before a concern began to revive and spread in my mind,
which I had had some view of for several years, namely,
to make a visit to Friends of Pennsylvania and New-Jersey;
and at times it was fresh with me, but without a clear prospect of the time when.
Thus time passed on; and in some of our meetings for worship,
the weight of the service would rest on me as
something almost too great for my weak state:
but I was mostly favored to see that ability for such services was not in the creature,
but in God; and then I could cast my care on him alone, and give up; and thus submitting,
I felt or saw but little about it for some length of time; but about the 4th,
5th and 6th months 1785, it was much with me;
but yet I could not see clearly about the time when to proceed.
And at our yearly meeting at Newport, in the 6th month,
as I sat in a meeting for worship one day,
it revived with the most clearness that I had ever seen it,
insomuch that I had a query in my mind,
whether it would not be ripe to proceed to the yearly
meeting at Philadelphia in the ninth month following,
but this passing off, I thought I would not yet open it to any person.
But after this meeting my dear friend Joseph Mitchell asked me
if I had not some thoughts of going to Pennsylvania,
etc. on a religious visit.
I answered him, I have had such thoughts,
but believe nobody would yet have known any thing of it,
had not the question been put to me.

He told me he felt such an engagement to ask me,
that he believed it was right for him so to do,
and then he opened his prospect of such a visit, which agreed with mine;
and told me it had been with him in the meeting we had just
sat in more feelingly than at almost any other time.
So we concluded to keep our prospects very much in our own bosoms;
and after a few days we had a few words more together,
when I found he had felt but little of it since we conversed about it;
but before our yearly meeting ended, I had some fresh revivals of it again.

About this time I had some trying exercises in the course of my practice of medicine;
but I found patience was good in these cases,
and that divine wisdom was profitable to direct therein.
I think I may also mention, that,
after all my past experience of heavenly good and divine favor,
I had to encounter some of the most trying and potently
pressing temptations of my soul`'s enemy that ever I endured;
even so that I often for months almost despaired of overcoming.
Let him that thinks he stands, be not high-minded; but fear.
Let none think themselves safe off the watch,
because of any degree of attainment and favor.
The watch-tower remains to be our place of safety;
neither let any honest mind be too much disheartened at
the assaults of Satan.--There is a power above him,
and he that cleaves close to it shall know a victory over all the powers of darkness,
and therein witness that there is no enchantment against the rightly wrestling Jacob,
nor divination against God`'s faithful dependent,
persevering Israel.--This I think my soul has a right to set its seal to,
as I have ever come off victorious, when I have not turned my back upon the light,
our divine Leader.
Sing, O you heavens! and O you pilgrims on the earth rejoice and
triumph! for strong and invincible is the God of our salvation;
and abundantly sufficient for our help is the grace afforded us!--let all but keep to it,
and then safe are their steppings, and sure their preservation--for,
however severe their trials, the Lord will be near them;
and indeed in the midst of temptation he will often lift up a
standard that will vanquish all the influence of every evil spirit,
and set the soul on the everlasting foundations that cannot be shaken.--O,
how often did the unslumbering Shepherd of Israel, the great Bishop of souls,
arise for my deliverance,
when I seemed to myself just ready to fall a victim to the
grand adversary! how did he not only give power of resistance;
but fill my soul with the overflowing of his love
beyond all expression! worthy forever to be waited for,
worshipped and obeyed, is the Lord, the God of Israel; the mighty Friend of the faithful!

My prospects of a visit to Pennsylvania, etc. continuing,
and the time to proceed therein appearing to me to be some
time preceding the yearly meeting at Philadelphia 1786,
I endeavored to be given up to it; but the thoughts of parting with my dear wife,
and tender little children, wrought so upon me that I seemed to hold back again,
after giving up several times, until in the winter preceding said yearly meeting,
I was visited with severe sickness for a month,
insomuch that many thought I should not recover.
In the time of this illness I intelligibly heard in the secret of my soul,
in silence and stillness, this awful language, set your house in order,
for you shall die and not live.

This, though plain and alarming,
did not at all strike my mind with a belief that I was soon to leave the body;
but two things seemed specially to be set before me: 1st,
Though I had a written will by me, very nearly agreeable to my mind,
yet as it was not quite so, one sense of the word, set your house in order,
was to me as much as make your will; whereupon I sent for a Friend, who by my desire,
and according to my direction, wrote another for me,
which was soon signed and witnessed to my satisfaction.
2nd. I was fully satisfied that it was the Lord`'s will
that I should be given up to the visit mentioned above,
and that I should set my house in such order as to leave my family and affairs.
Upon this I gave up fully to the heavenly vision,
and never afterwards turned my back upon it, nor dared to depart from my covenant,
that if he would be my God, be with me, and preserve me and mine,
I would be his servant and follow him whithersoever he pleased to lead me.

However, though I dared not refuse to go on his errand, I often had low times,
wherein I almost lost sight of the once clear prospect;
yet it would again and again revive in such a
manner as convinced me that my peace was in it,
and even that my livelihood, spiritually,
as much consisted in faithfully laboring for daily bread,
and that in the way of truth`'s requirings,
as my outward living or support depended on an honest industry.
For if we will not improve our strength and abilities to this purpose,
then the sluggard that will not plow, shall beg in harvest, and have nothing;
and on the other hand, though we labor ever so earnestly,
if the Lord withholds his blessing,
how fruitless are all our labors!--so in spirituals--the man is not without the woman,
nor the woman without the man in the Lord; i. e. Christ is not without the church,
nor the church without him in the work of religion;
nor indeed is any individual soul without him, nor he without that individual,
in the work of salvation; but he works in the soul,
and through him the soul works out its own salvation.
Here is a blessed cooperation; and the very reason why the creature can and does,
in a sense, work out his own salvation, is because God works in him, begetting the will,
and giving ability to do the deed; but if after all he will not,
it will fare with him as with Jerusalem, who might often have been gathered,
but they would not; wherefore their house was left unto them desolate,
and the things that belonged to their peace hid from their eyes.

Now, after passing through various exercises,
and finally witnessing a full submission to the divine will,
in regard to giving up all to follow him in this religious visit,
and obtaining the approbation of our monthly and quarterly meetings.
I took leave of my dear wife and tender little children, in the fear of the Lord,
and in fulness of endeared natural affection, on the 21st of the 7th month 1786,
and rode to Providence, from there next day to South-Kingston, next day,
being first of the week, I met my beloved friend Joseph Mitchell, and, after meeting,
we rode on to Stoningtown in the state of Connecticut,
and next day to New-London,--and from there by water to Southold on Long-Island,
next day rode about fifty miles, and towards noon the day following, got to Bethpage,
and on the morrow, attended a meeting appointed for us there.
Joseph had good service--I was shut up as to words, but had clear openings.
It is sometimes wisely ordered,
that precious and divine openings are treasured up in the Lord`'s treasury;
but how dangerous would it be to squander them away, and lavish them out among people,
only because we are favored with the openings, however clear and even instructive,
without the word of command, and the divine necessity, to deliver them to the people.

Next day we got to Westbury quarterly meeting;
on 6th-day Joseph said a little to good purpose among them in the meeting for discipline,
and a few words at the adjournment of the select meeting;
but I was silent through all the meetings.--7th-day we had a meeting at Oyster-Bay,
and another at Matinicock in the afternoon--the first was heavy,
but Matinicock was more favorable,
and I believe we both had some favorable service there, to the lukewarm and careless,
and in the way of encouragement to a few sincere-hearted worshippers.

First-day we were at Westbury, to good satisfaction; called many to a deeper exercise,
and feelingly invited the youth to a life of
religion.--2nd-day we had a meeting at Cow-Neck,
a pretty favored time, though we both had to search Jerusalem, as it were with candles,
and to drop things very close and urgent;
yet we also had the comfortable language of
invitation and encouragement to the dear youth,
some of whom seemed tenderly affected.
Before this meeting we had a family opportunity in the morning at a Friend`'s house,
and had to labor against a spirit of grandeur, and high-mindedness,
and felt great peace in the faithful discharge of our duty,
and especially in a spring of living encouragement to a
steady perseverance in true humility and meekness,
which flowed fresh and lively to a few present,
who we felt to be already in a good degree enamored with a prospect thereof.
Third-day we had a meeting at the widow Mott`'s, an elderly Friend.
Fifth-day, being the 3rd of the 8th month, we attended Flushing monthly meeting;
a mournful time it was to me, though Joseph had to sound a little alarm among them.
We went the next day to Newtown, where a meeting was appointed for us.
Few Friends live here.--I thought, as I was speaking, according to clear openings,
the matter was too deep for most present; and therefore as if I, poor weak worm,
could steer my own course better than the great Pilot,
or better suit my subject to the states of the people, I stepped aside from the opening,
and with a view to condescend to the people`'s conditions,
struck upon more familiar and more common matters,
in illustrating truth`'s gradual teachings; but alas!
I found it is truly not in man that walks to direct his own steps in this great work,
for instead of instructing the people in it,
I soon dried up the spring of life I felt before;
and I sat down in a degree of shame and confusion,
being taught thereby to trust in the Lord with all my heart,
and lean not to my own understanding.

After this went to New York, it being seventh-day,
and Friends holding two meetings there of course on first-day, stayed until then,
at both which Joseph had pretty good service, but I was entirely shut up in silence.
Third-day 8th,
had a meeting at Rahway--my dear companion was
favored in a close searching testimony to some,
and comfortable encouragement to others.
A wide field of doctrine was opened before me, wherein, for some time,
I expected it would be my lot to labor; but as I waited,
not willing to proceed in the opening, however clear, without the word of command,
it closed again; so I was silent,
save that I just informed the meeting how it had been with me.
4th-day 9th, we attended Friends preparative meeting at Plainfield;
my mouth was opened in an alarming testimony among them in the
meeting for worship--and Joseph`'s in solemn supplication,
that the last days of such as had long been gathering rust, might,
by the fire and the hammer, be their best days.
6th-day 11th, had an exercising meeting at Shrewsbury.
Seventh-day 12th, we had a meeting at Squancum.

First-day 13th. We were at Squan meeting;
it was a very stripping time to me.-- 3rd-day 15th,
had a very laborious meeting at Barnagat, though a few exercised Friends belong there.
4th-day 16th,
another such at Little Egg-Harbour--here we saw our ancient worthy friend Ann Guant,
who had twice visited New-England in the work of
the ministry--she seemed lively in old age,
and her company was pleasant.
Fifth-day 17th, we attended their mid-week meeting at Great Egg-Harbour,
where Joseph had good service.
Sixth-day 18th,
had a meeting at the other meeting-house in Great Egg-Harbour --here it was
my lot to have a good open time both in testimony and supplication.
7th-day 19th,
had another open meeting at Cape-May in the morning to pretty good satisfaction.
Hence we rode to Mark Reeve`'s in Cohansey.
We found him recovering from great bodily illness, and in a sweet disposition of mind.
He was one of the first travelers whose ministry was powerfully reaching to my mind,
when he was in our parts many years past on a religious visit with Stephen Comfort.
It was very comfortable to be a little in company and sweet
conversation with the only one of the two now living.

First-day 20th.. We attended their meeting held at Greenwich.--2nd day 21st,
we had a meeting at Alloways-Creek.
The state of such as thought themselves rich and increased in goods,
etc. and yet had too much neglected to buy '`gold
tried in the fire,`' that they might be rich,
and '`white raiment,`' that they might be clothed, sprang fresh in my mind;
yet I believe there is a remnant among them,
who are in a good degree alive in the truth--may these be strengthened,
and their number increased.
This meeting, though very painful and dull in the forepart,
was comfortably refreshing in the conclusion.

3rd-day 22nd, we had a blessed, heavenly meeting at Salem,
though my dear companion was quite shut up; but my mind was much opened and enlarged;
and much I had to do among them in the flowings
of divine favor--Blessed be the great helper.
4th-day 23rd,
we had another favored meeting at Piles-Grove,--at least my own way seemed very open,
and my mind favored in a comfortable degree, after some time of exercise in silence:
but Joseph was still shut up--5th day 24th,
had a good open meeting at Upper-Greenwich where truth favored with matter and utterance,
to pretty good satisfaction.-- 6th-day 25th,
we had another pretty good meeting at Woodbury,
though I did not feel quite so well satisfied
with my own testimony as at some other times;
yet I had a degree of peace--7th-day 26th,
we attended the select quarterly meeting at Burlington.--First-day 27th,
attended the sore and afternoon meeting for worship,
suffering great inward lack and distress:
but through a degree of patience was enabled to endure it.

Joseph seemed comfortable, had a little to do in the meeting,
and could converse pleasantly with his friends after it; while I was so shut up that,
though some of them felt near to me, I could scarce use any freedom with any of them;
indeed I feared they would think my reserve was affected: but truly it was not;
I tried several times to use a little pleasant freedom; but the more I tried,
the more reserved and shut up I felt,
and even seemed to myself to act like a fool when I attempted to use freedom;
therefore I gave up to be as I could be,
and to endure this shutting up with all the patience I possibly could,
as from the hand of God, for what purpose I knew not.

Second-day 28th. Attended the quarterly meeting,
going into it under great weakness and lack; but soon after sitting down,
the power of the word of life arose, in freshness and dominion,
with an opening clear and living;
wherein I felt a necessity to stand up and proclaim the word of the Lord among them.
But it being a very large meeting,
and several great and eminent ministers of the gospel present,
it was no small cross to me to appear among them;
however I was pretty soon made willing to yield to the pressing motions of truth,
and therein standing up,
was favored to speak closely to the states of such as
had not been faithful to divine manifestations,
and even some who had known their heads to be crowned as it were with crowns of gold,
and yet had so fallen short that, if they did not arise and trim their lamps,
I believed the kingdom would be rent from them, their crowns taken from their heads,
and given to others that were better than they;
but I had also a comfortable prospect of many truly tender religious minds present,
and hopeful young people a valuable number; and it opened in me to say,
I believed the children were already born who would live to see a better day,
and enjoy the overspreading canopy of divine love in a more eminent degree,
through faithfulness, than what many now do.
It was a precious and heavenly opportunity,
and several living testimonies were borne by brethren present,
to the rejoicing of many hearts.

Third-day 29th. We attended the youths meeting at this place--a large, comfortable,
instructive meeting it was.
We were both silent;
but truths testimony was livingly declared by two or three gospel ministers of this land,
or of Pennsylvania:
after which we attended the adjournment of the select
meeting to a good degree of satisfaction--4th-day 30th,
were at the select quarterly meeting at the Falls, for Bucks County in Pennsylvania,
where we had some close hints to drop;
but hope there is a living remnant among them.-- 5th-day 31st,
attended their quarterly meeting,
where my mind was favored in testimony to the glorious gospel of Christ,
as effectually witnessed in and by many in our and our fore-fathers days; and which,
as I believe, will yet more abundantly be witnessed among the nations;
for I do believe the Lord is arising to shake terribly the earth,
and that multitudes will be brought to the inward knowledge of this glorious truth,
Christ in you, the hope of glory.

Joseph was silent in the meeting for public worship;
but our dear friend John Lloyd bore a living testimony among us, and a good time it was.

Sixth-day,
9th month 1st. Attended the youths meeting here--a pretty favored time on the whole.
Joseph had good service in lively testimony among them.
I was quite calm and easy, without a word in that way.
After this we attended the adjournment of the select meeting to pretty good satisfaction.
--7th day, 2nd of the month, we had a meeting at Makefield, where, after deep exercise,
truth rose at length into great dominion,
and several living testimonies were borne to the great tendering of many minds,
especially among the youth,--many of whom were present,
and pressingly and powerfully persuaded to choose the Lord for their portion.
Indeed it was a precious time to them,
and a large number of them were very much reached and
broken--may they live under a sense of it.
Backsliders were also pressingly warned,
and truth was over all--blessed be the powerful helper of the truly dependent,
for he is their only hope, and their rock of defense in all their exercises;
and they learn and know, from multiplied experience,
that without him they can do nothing in a religious line,
that will either please him or profit the people or their own souls.
But O, the wonderful and inexpressible light, life, power and dominion,
wherein he arises at times for the help,
comfort and encouragement of his faithful servants!
Words fall short in expression thereof, and language cannot reach it! therefore bow,
O my soul, in silent, humble prostration,
and reverential gratitude and awe before him the Lord God omnipotent that reigns;
bless him, praise him, and adore him forever; for he is worthy to be sought unto,
trusted in, worshipped and obeyed, and that by the whole house of Israel, can my soul,
in feeling thankfulness and awful sensibility, at this time testify and declare!
Amen.

First-day 3rd. At a meeting at Plumstead we suffered long;
but at length we felt relieved, the unfaithful were admonished, the youth invited,
and the heavy-hearted encouraged: it was a heavenly time;
light and life was felt triumphing over death and darkness! --
what shall we render unto the Lord for all his benefits?
Let us lie low before him, feel our dependency upon him,
and never presume to move in his great work without his assistance.

Second-day 4th, I went with my companion to the monthly meeting at Buckingham,
but he being much unwell with a fever, which had been preceded with an aguish paroxysm,
left the meeting soon after our sitting down: my mind was shut up, and that too,
under great exercise; but after long waiting, I had some pretty bright openings,
wherein I found strength to stand up, and was richly favored with Truth`'s help,
and I hope to some real usefulness to the Friends and people present.
In the meeting for business I found much to do among them;
though I was very sensible of a living concerned remnant there.

Third-day 5th of 9th month.
I left my dear companion at our friend Thomas Smith`'s, unable to ride much,
and went to the monthly meeting at Wrights-town, where Truth,
after a time of humble waiting, rose into good authority,
wherein I rejoiced to feel the great Master still owning us to be his people,
and favoring us with his heart-cheering presence.
I was considerably drawn out in testimony and
ardent supplication among them at this meeting;
and in the meeting for church discipline, had to labor a little to promote plainness,
and good order in some other respects, and had peace in my labors.

Fourth-day 6th. Without my companion, he being still unwell,
I attended the Falls monthly meeting, to pretty good satisfaction,
though I had close searching labor with them,
and in the meeting for business also.-- 5th-day 7th,
I attended Middletown monthly meeting to pretty good satisfaction.--6th-day 8th,
went back to see my dear companion, found him better,
and was rejoiced to see him--7th-day 9th, I had a meeting at Bristol,
was shut up in silence, except just to tell them of their lack of inward gathering.

First-day 10th, I went, accompanied by my dear friends James Moon and James Simpson,
to Trenton, in West Jersey, where a pretty large number of people, not of our society,
attended the meeting; they sat very attentive and quiet,
and I was largely opened among them in the doctrines of truth.
The people seemed somewhat reached: I trust it was a good meeting to many; however,
I did not feel truth to reign in dominion over all, as at some other times; therefore,
finding the truth of the scripture assertion, you have need of patience, that,
after you have done the will of God, you might receive the promise.

2nd-day 11th, I had a pretty good meeting at a place called Stony-brook;
and though it was long silent, yet at length, through deep exercise,
truth arose and brought comfort to some of our minds.

Third-day 12th, Had a little meeting at Upper-Freehold, called Robins`'s meeting.
Our labor was hard in silence, but in the conclusion a little life spread over us,
and a number were pretty much reached, and broken into tenderness and contrition.

Fourth-day 13th. Had a very heavenly meeting at a school-house, Upper-Freehold,
which was a great comfort to my mind, and I trust to many more; for truth was over all,
praised be the name of the Lord!
In the afternoon we had another meeting at a place called Arney`'s-town,
in which we sat long in silence; but near the close I stood up and expressed a few words,
pointing the people to Christ in spirit,
after which my friend James Simpson had considerable to say,
and I trust the meeting ended well.

Fifth-day 14th. We had a meeting at Chesterfield, called also Crosswicks.
I sat long in silence--many presentations attended my mind,
but as I waited for the word of life,
I saw there were many subjects on which a man might either
muse or speak,--several fields of doctrine,--a large scope for
choice--but alas! we cannot choose aright for ourselves,
any more than we know what to pray for without assistance.
So I was made willing to reject all these false openings however beautiful;
and sinking down into the silence of all flesh, it was freshly brought to mind,
ever remember, when you approach before your God in order to worship him,
that of yourself you can do nothing; that your business is to wait in true silence,
breathing to him for help and instruction, not presuming to stir him up,
or awake him before he please, nor to form unto yourself a graven image,
or warm yourself by the sparks of your own kindling, lest you lie down in sorrow.
If you feel your mind ever so empty and barren, keep in true resignation,
keep the word of his patience, and he will keep you in the hour of temptation.
Watch and pray continually, and trust in the Lord with all your heart,
and lean not to your own understanding.
After sitting some time under the fresh revival of these things in the meeting this day,
I stood up and declared how it had been with me in this meeting.--
This afternoon we had a very painful meeting at Bordentown,
in which we labored and had peace.

Sixth-day 15th, Had a meeting at Mansfield-Neck.
Here the seed was under sufferings; too many present sat idle,
and lived too careless and unconcerned lives; and,
after a season of suffering in silence, truth triumphed over all,
and God gave us the dominion, the victory and rejoicing;--a heavenly time it was indeed;
the faithful were comforted and encouraged; the lukewarm warned,
and called to awake and arise from their beds of ease, that Christ might give them light;
and the dear youth movingly persuaded to forsake all and come and follow Jesus;
come taste and see that the Lord is good.
Many minds were much reached, tendered and encouraged--O, my soul,
remember and adore him for all his favors,
and for every such watering and dew-descending season.

Seventh-day 16th. An exercising meeting at Mansfield.--1st-day 17th,
I attended the meeting at Upper-Springfield, which,
though through some exercise in the beginning, was a good comfortable meeting,
truth reigning over all.
In the afternoon I had a silent meeting at a place called the Mount,
it was pretty large and scarce any exercise appeared to
rest on the minds of the people.--2nd-day 18th,
I had a painful, yet, in the end, a comfortable meeting at Old-Springfield,
where met me my dear friend John Simpson,
to join me a little in the weighty service before me,
in the absence of my much beloved companion, who, he informed me, was very ill;
and James, the brother of John, having left me,
it was truly acceptable to be joined by so united a brother.
In the afternoon we had a meeting at Burlington.
I was shut up in silence,
which is the third silent meeting I have attended with Friends of that place,
but dear John had good service, of which I was glad.

Third-day 19th. We were favored with a blessed, yes,
an exceeding heavenly and watering opportunity at the
house and in the family of my dear friend John Hoskins,
among his children.
Advice and supplication flowed freely and powerfully to our great consolation together.
After this we went to Mount-Holly,
and attended a meeting that had been appointed there for me:
it was indeed a most melting favored time;
exhortation and prayer were both eminently attended with life and divine authority.
A more evident fulness of divine sufficiency in solemn supplication perhaps I never knew;
for which my heart was and is awfully bowed to the God and Father of all our mercies,
to whom I bend the knee reverently, and acknowledge him as my only helper,
and all sufficient support--however,
I had to see that things were much out of order at this place;
and was divinely enabled to point out and speak to several conditions,
believing spiritual blindness had at least in part overtaken
some who had once seen clearer--some were lame,
some were halting, some I thought were greatly withered,
and some I thought resembled the dry bones, concerning which it was queried,
'`can these dry bones live.`'--To all these states I had to speak a word of reproof,
of lamentation--and also of encouragement yet to hope;
to wait for and seek after strength, and therein to arise and press forward:
for even the dry bones did live: but above all,
the animating word of persuasion and encouragement flowed powerfully to the tender youth,
like a river of living water through my soul to
them!--blessed be the Lord for every favor.

After meeting we made a comfortable visit to our dear ancient friend,
the widow of that worthy, self-denying valiant of the Lord, John Woolman,
and to their daughter, with her husband and children.
The widow was in a meek, humble, loving frame of mind: I think the Lord is with her,
and believe he will be with her.

Fourth-day 20th. We had a meeting at Vincent-Town, and after long silence,
I had to weep a little as between the porch and the altar,
and called those met with us to do the like--for
I feared the heritage would be given to reproach,
the heathen rule over them, and say among the people, where is their God.
John joined me in sounding an alarm; and they were called to mourning,
and to teach their children lamentation!
After meeting I rode back to Mount-Holly, then to Burlington,
so crossed the Delaware to Bristol, and home with my dear ancient friend James Moon,
who had been so kind as thus far to accompany me.

Next day the 21st, the good old man accompanied me to see my companion,
whose life we had lately been informed was quite despaired of;
we found him very ill indeed,
but yet I had a degree of hope.--6th-day 22nd. Dear Joseph is yet very dangerously sick,
though we hope a little alteration for the better.--7th-day 23rd, I left him,
and rode to Philadelphia to the select yearly meeting, which was very large.

First-day 24th, I attended the three meetings: The first at Pine-Street meeting-house,
where the Lord, being graciously with me,
opened my mouth in testimony and solemn supplication; many hearts were tendered,
and my soul rejoiced--the Lord have all the glory.
Our friend James Thornton was eminently favored in a powerful testimony,
as also in the afternoon at the Bank meeting;
and our dear friend Samuel Emlen had a lively time in a short testimony after James.
In the evening attended Market-Street meeting, where our worthy friend John Storer,
from Old-England, appeared with instructive clearness and sensibility,
both in prayer and testimony.

Second-day 25th,
and 3rd-day 26th. Attended several sittings of the yearly meeting for business,
and one sitting of the select meeting, to pretty good satisfaction.

Fourth-day 27th. Word came of my dear companion,
by two physicians who had been up to visit him by mine and my friend`'s request,
that he departed this life about an hour past midnight this morning.
This caused indeed a close exercise,
and brought me to an examination whether I had done right in leaving him;
but on mature consideration, I found peace in having so done:
and several valuable Friends accompanying me,
who felt engaged to leave the yearly meeting on the occasion,
I went up to Buckingham in order to attend the funeral.

Fifth-day 28th. We attended accordingly, and had, after the interment of the body,
a large, heavenly meeting,
several living testimonies being borne to the power and efficacy of truth,
and something by one or two of his acquaintance respecting the gravity,
circumspection and usefulness of our dear deceased friend in his day and generation.
I trust it was a time that will not be soon forgotten by many present,
whose hearts were melted and tendered together.
After the meeting we returned to Philadelphia in order
to attend the remaining sittings of the yearly meeting.

29th and 30th. Attended several sittings of the yearly meeting for business,
had some little services therein to a good degree of satisfaction;
the meetings being owned and crowned by the presence of the Lord of life and glory.

10th month 1st, and first day of the week.
Attended a sitting of the select yearly meeting,
and the three meetings for worship-- Pine-Street in the morning--Market-Street
afternoon--Bank in the evening--in all which truth was in good dominion,
under the assisting influence whereof my way was open in gospel labors at each place,
I hope to the rousing of some, and strengthening of the hearts of others.

2nd day of the week, and 2nd of 10th month.
The last sitting of the select meeting was this day divinely owned,
as were several of the preceding,
with the Lord`'s glory filling the inward temple of the spiritual house in such a
manner as to induce a living remnant to cry in the secret of their souls,
blessed is he that comes in the name of the Lord: Hosanna in the highest.

In the course of this yearly meeting my mind was often
bowed in a sense of the Lord`'s condescending kindness,
not only in favoring me with strength and ability,
but also in opening the hearts of many deeply experienced ministers and elders to
receive and sympathize with me in my labors--for which the holy Name be praised,
and let all ever bow before him.

Third-day 3rd. I began to desire my way might open to leave Philadelphia;
but I found no way out--so went to the Bank week-day meeting,
and was there silent.-- 4th-day, attended the week-day meeting at Pine-Street;
had a good open time in sounding an alarm to the lukewarm, and felt sweet inward peace.
5th-day, was at Market-Street preparative meeting and was silent,
but several testimonies were borne in Truth`'s authority.
6th-day.
I attended their monthly meeting,
and was livingly and very unexpectedly opened in Truth`'s testimony against the love,
spirit and friendship of the world, and to call Friends into a labor in their families,
and among their dear offspring.
This was extensively an alarming day,
and I hope some of them will probably take the alarm.--
My soul had great peace--blessed be the holy helper.
7th-day, visited some families.
1st-day 8th, rode to Frankfort meeting, and there suffered deeply in spirit,
but got some relief by a close searching testimony among them; yet remained uneasy,
and returned so to Philadelphia.
2nd-day 9th, attended the select meeting to some good degree of satisfaction.
3rd-day 10th, I had a meeting at Frankfort; was silent until near the close,
when I told them I felt something present which exceedingly
obstructed the arising of life in the meeting.
In the afternoon we had a meeting at Fair Hill--I was silent there.
4th-day 11th, had a meeting at Germantown, in which my lot was in silence.

Fifth-day 12th, attended the youth`'s general meeting at Biberry,
and suffered still in silence, feeling myself as a stranger, a pilgrim on the earth: and,
in the depth of my distress, I said in my heart, Lord, why have you thus forsaken me?
you know I have given up all that is near and dear to me in
this world to follow you and your call into this land;
my dear wife and tender offspring I have left behind me,
and come forth thus far into a land I knew not; and I can appeal to you, O my God,
that it is only in obedience to your will and requirings--Why then am I thus left?
why feel I myself so destitute and forsaken of all good?
why see I no way cast up to walk in?
Thus, or to this purpose, I bemoaned my desolate condition,
and spread my case before the Lord my God with tears,
but all in a good degree of resignation; and after a little space,
being fully satisfied all would work for good, I was made willing to be as poor,
empty and blind, as the Lord would have me to be, and all centered in this, '`Not my will,
but yours be done.`'

Sixth-day 13th. Was at a meeting appointed by two
Friends from New York government at Abington,
my own way being entirely shut up, so that I dared not presume to appoint a meeting,
nor yet to return home, though I often looked towards home, but it looked dark.
So I should have quite stopped, had there not been a meeting for those two Friends,
which I thought I might safely attend; but still silence and suffering was my lot;
and yet the Lord was graciously pleased to preserve my
soul in a good degree of patience under all.

Seventh-day 14th. I went to a meeting appointed for the aforesaid Friends at Horsham,
and returned with my friend Joshua Morris to his house at Abington.--First-day 15th,
was at Abington meeting again, and silent in both, feeling great emptiness.
It is the Lord`'s hand, let him do as he pleases, he will not do any thing for my harm.
2nd-day 16th, stopped travelling,
and waited on the Lord for direction--towards night a little light arose,
and I thought I might go on in the morning, if the way should continue still to be open.
3rd-day 17th I attended their meeting at Gynnedd,
my tongue as it were cleaving to the roof of my mouth.
4th-day 18th, I had a silent meeting at Plymouth.
Fifth-day 19th, was at the monthly meeting at Richland--still shut up in silence.
Sixth-day 20th, attended a meeting at the same place for two marriages, still in silence;
but I am learning contentment, and to endure famine, drought and hunger, patiently.
Lord spare not until your will be accomplished in me,
and all that is in me bows to your sceptre,
and yields fully and quietly to your disposal!

Seventh-day 21st, Had a meeting at Potts-Grove, wherein Truth rose into dominion,
and my faith and assurance of the all-sufficiency of
Truth`'s openings and leadings were greatly increased;
for I had sit through eleven meetings in silence one after another,
except a very few words just at the close of the first of them.
Now in all these silent meetings, I could never once, except those few words,
find ability or openness to say a single word,
and believe my silence was wholly ordered of God, though contrary to the desires of many,
and even part of the time very unpleasant to my own mind;
but it pleased my great Master to keep me to it,
until I was made to yield and be content with whatever
he pleased to allot unto me in my pilgrimage,
however it might induce the ignorant to gaze upon me as a fool;
and after I had thus surrendered up all,
he was pleased to open my mouth in a very comfortable manner to myself,
and I believe to some others.
In this meeting I felt the power of the word of
life almost as soon as I sat down in the house,
but the opening was on a very unexpected subject,
a disposition striving to comprehend the unfathomable mysteries of the inscrutable God.
This was the subject that opened in the light and in the life,
and as I kept to the opening I had much to say on this and several other
subjects with considerable in a way of comfort and encouragement to a tried,
afflicted state; and being favored with the spirit of supplication,
the meeting ended to good satisfaction.
After meeting I was informed that such an inquisitive,
diving disposition after hidden mysteries was present in that meeting,
and also the other state of affliction and probation--
blessed be the Lord for all his fatherly dispensations,
however disagreeable to my own inclinations.

First-day 22nd. I attended (dear John Forman being with me,
as he had been for several days past) the meeting of Friends at Robinson or the Forest,
a blessed time it was.--2nd-day 23rd, we had a meeting at Reading,
and next day at Maiden Creek, both I hope profitable good meetings.--4th-day 25th,
we were at the monthly meeting at Exeter; Truth rose into blessed dominion,
and reigned over all in the meeting for public worship,
to the reaching and tendering of many hearts.
5th-day 26th, we had a meeting at Nantmil, to which dear Abel Thomas accompanied us;
my friend John Forman had good service; I was long shut up, but at length,
in the fresh openings of life, I stood up, and expressed a few words,
after which dear John Forman appeared again in a short, lively testimony;
and my spirit being drawn forth in supplication to the Lord,
the meeting ended under a feeling sense of the savor of life.

Sixth-day 27th. We had a good,
open meeting this day at Pikeland--The Lord`'s presence was our crown.
7th-day 28th, a silent meeting as to myself at Providence;
but dear John Forman had pretty good service there.
First-day 29th, we were at the Valley meeting, and both had considerable to say,
yet found scarce any relief.
2nd-day 30th, I attended Abington monthly meeting,
and was favored in the meeting for public worship with a clear opening,
wherein I had a short testimony to the reaching the witness in many minds,
and much to my own relief,
after an exercising time the day before--the whole revives the
case of those who toiled all night and caught nothing;
and yet, by carefully attending to the Master`'s directions,
they soon after caught a multitude of fishes.

Third-day 31st. Attended Gynnedd or North Wales monthly meeting, where,
after sitting a while in darkness, light sprang up and brought forth a short,
awakening testimony in close, searching language, very much to the relief of my own mind.
I also had more to do in the meeting for discipline than usual for me when abroad,
as I found my mind engaged and the way opened;
for it is my special care in all these meetings not to move or undertake in
any service but what I find a real engagement to in the openings of life;
and on the other hand, not to omit any thing which is thus clearly pointed out,
and my mind thus engaged in.

11th month 1st, and 4th of the week.
I went to the monthly meeting at Horsham, and, after viewing the camp a while in silence,
had to lift up my voice like a trumpet and sound an alarm among them,
wishing them to feel for themselves, lest before they were aware,
and while sitting carelessly at ease,
the enemy should surround them and lead them captive away.

After this I sat in a low,
suffering state through the whole transactions of their business;
but just at the close my trumpet was again prepared to sound;
and feeling strength to arise out of great weakness, and light out of obscurity,
I so renewed the alarm among them,
as to feel quite easy and comfortable in my mind--blessed be the Lord who helped me;
for I sensibly felt, that,
had not his power arose for my deliverance I
must have sunk down under a load of distress,
and gone away burdened in spirit,
having no might nor ability to throw my heavy load off myself.
Indeed I grow weaker and weaker, blinder and blinder, in myself:
but herein I truly rejoice, for it brings into the clearness,
into deep dependance upon God alone, whereby his grace is felt to be all-sufficient,
and an unshaken evidence, that with the divine Arm there is no lack.

Many deep lessons of instruction are opened in this dependent state,
which had utterly escaped the penetration of the wise and prudent.
Therefore, O Lord! ever keep me low enough before you.
I have so clearly seen this to be the only way
for divine enlargement and true consolation,
that I desire it, I crave it of you more earnestly than corn, wine, or oil.

Oh, what numbers miss of the best instruction and the purest joy, by continuing,
even after great mortification, alive in themselves in their religious performances.
These cannot fully say, I live, yet not I, but Christ lives in me.
These have in them something of the beast which
received the wound by the sword of the spirit,
and yet did live--the deadly wound being healed; all these are in imminent danger:
and if they are not aware,
they will retard the work of the Lord in themselves and in others,
through their busy attempts to promote it:
and yet perhaps they may be pretending to wait for,
and giving out that they feel much divine influence.

Oh, the subtlety of the serpent,
especially in his resemblance of an angel of light! many has he caught,
beguiled and ruined; the pure openings of life are very different,
and distinguishable from all his false visions and likenesses; the deep, humble,
careful traveler finds it so to his unspeakable satisfaction;
and yet how many are taking the latter for the former,
for lack of depth and patience enough in waiting!--hereby the innocent,
precious life in them becomes wounded, and the true simplicity betrayed--for,
the adulteress will hunt, even '`for the precious life,`' as the wise man testifies;
and I believe the truly wise in heart, not in earthly wisdom, but heavenly,
do really find it so; for the life is the very thing the adversary strikes at,
and if he can keep us from the sensible feelings and
openings thereof in our religious engagements,
he cares not how active we are without it, nor how much we pretend to it;
for the more of all this, the securer he has us,
and the more we promote his kingdom and interest.
Oh, where will many appear at last, after all the cry of Lord, Lord,
have we not prophesied in your name, and in your name cast out devils,
and done many wonderful or mighty works?

This is a subject that greatly engages my attention,
in earnest wishes that you who read these hints may be preserved out of,
and wisely shun the dreadful snare, and yet have a care of disobedience.
But when things open in the light, give up to the heavenly vision,
and confer not with flesh and blood.
The path, though narrow, may yet be travelled in.
It is a way wherein all the true wayfaring men, though fools, may walk and not err;
but then they must carefully attend to the light for the way-marks, as the light,
and that only, makes them manifest, keeping a single eye thereto,
never once beginning to think of taking less heed to it, or that now,
after much experience,
they can do pretty well with less clearness and
less bright shining thereof than heretofore.
For alas, this is a mistake and dangerous delusion,
and he that continues to give way to it will soon walk in darkness,
not knowing where he goeth:
his feet will stumble in the dark until he falls into
the bottomless pit with the beast and false prophet.
But you, whose eye is kept carefully single and attentive to the light,
shall witness your whole body to be full of light, and shall journey forward safely,
until you arrive at that city that needs not the light of the sun nor the moon,
for the Lord God does lighten it, and the Lamb is the light thereof.
Amen.

Fifth-day 2nd. After a comfortable family visit where one lay sick,
I rode to Philadelphia,
in order to attend the approaching quarterly meeting--
visited a few families to a good degree of comfort.

Sixth-day 3rd. I went to see two or three families,
but have felt very different from that openness, freedom, cheerfulness and satisfaction,
which I felt in a good degree when here before.
I thought far less of having sufficient time now than when I first came;
but alas! there is scarce any comparison; wherever I go my load goes with me,
and I cannot yet throw it off.
But all tends to confirm and assure me that it is not of man, nor by man,
nor yet by outward observation.
So I wait in patience.

7th-day 4th. I am going presently to the select quarterly meeting.
O Lord my God, be with me; keep me low; keep me humble;
keep me also faithful and attentive to your divine movings,
whether in silence or utterance;
for I know that without you I can do nothing rightly--I
attended the above-mentioned select meeting,
and felt great weight and exercise attend me; but, sinking down to the pure gift,
I was after a little time raised up in Truth`'s dominion to
ease my mind among my brethren and sisters of this meeting,
after which I was drawn forth in supplication,
and the meeting ended to solid satisfaction.

First-day 5th. In the forenoon I attended Market-Street meeting,
and soon feeling a very weighty concern resting on my spirit,
I stood up in the fresh openings of life, and began to express what I had in commission;
but keeping carefully to the divine guide, I soon felt all to be shut up again,
whereupon I immediately sat down,
rejoicing that I was preserved from proclaiming without life,
what just before was opened in the life: so I sat quite easy,
being delivered from the great weight and exercise which I had felt,
until towards the end of the meeting,
and after another Friend had well declared the truth among us,
when I again stood up and very fully cleared my mind.
I left this meeting in true joy of heart, and rejoiced in the Lord my gracious Preserver,
who is learning me to depend on and attend to his shuttings as well as his openings:
and this is the only way of safety.
In the afternoon I went to the Bank meeting, and had good open service,
and though in a short, I hope comfortable testimony to a living remnant present.
I attended the evening at Market-Street meeting.
It is a very large house, and was now greatly crowded:--I was quite silent.

Second-day 6th. Attended the quarterly meeting for worship and discipline.
In the first I had a short open testimony,
after which our friend John Storer had a good open time, to our edification and comfort.
In the meeting for church discipline, I was shut up in silence and mourning.
There was recommended down from the yearly meeting,
a renewed care and exertion for the preservation
and recovery of the young and rising generation,
who are many of them greatly departed from primitive plainness and simplicity.
My spirit was bowed in sympathy and union with a few
tribulated souls who mourn the desolation of Zion,
and use their honest endeavors for her restoration.
One remark of dear John Storer`'s I cannot well omit to insert here: He said,
in the meeting for business, that he never knew any one to grow and prosper in religion,
who was negligent as to the attendance of religious meetings.
Now I wish this solid remark, founded on impartial observation,
may have its proper effect, to the quickening of all who heard or who may here read it,
to the diligent discharge of that great and important duty.

Third-day 7th. I had good open service at the youths meeting at Market-Street house.
It was a large solid meeting, and I laid things close home to negligent parents;
but to the honest, faithful laborers, as well as to the tender youth among them,
the language of consolation and encouragement flowed sweetly and freely.
I hope to the refreshment of some of their souls.
In the afternoon there was a meeting for the negroes;
it was not to me a very lively meeting, yet was in degree owned and favored,
and several testimonies were borne, among which I was not wholly excused;
and I believe my exercise might be of some little use to the poor blacks,
although I felt very weak, and Truth rose not into much dominion;
but my mind was quiet in the Lord.

Fourth-day 8th. I went to the select quarterly meeting at Abington,
and sat through the same under great exercise, but near the close my way opened,
and I was enabled to discharge myself.

Fifth-day 9th. This day came on the quarterly meeting for worship and discipline,
which was large and livingly favored with the flowings of life in the ministry,
and the labors of some concerned brethren for the good of Zion,
in the meeting for discipline.
I had good open service on several important subjects,
particularly the guarded education, oversight, and nurture of our youth.

Sixth-day 10th. Attended the youths meeting;
it was large and favored with the ownings of life,
and with several living testimonies --I was silent and well satisfied.

Seventh-day 11th. I got to the select quarterly meeting at Concord, where,
as at Abington, I was quite shut up,
until near the end of this day`'s sitting of said meeting; but life then arising,
I stood up in the opening thereof, had great satisfaction in my labors among them,
mostly in a way of encouragement,
but not without some cautions and admonitions as things opened.

First-day 12th, I rode to the meeting at Birmingham,
through which I sat silent and resigned.
2nd-day 13th, went back to Concord to the quarterly meeting,
and was therein shut up from words through the
meetings for worship and church discipline;
as also the next day at the youth`'s meeting and adjournment of the select meeting;
but our friend John Storer had excellent service both days.

Fourth-day 15th. I was at Wilmington monthly meeting,
and quite silent through the whole thereof--it being a low time with me,
though several Friends seemed to be favored.
Fifth-day 16th,
quite silent again at Kennet monthly meeting until towards the end of their business,
when I was concerned to point them to the life in the transactions of church affairs.
Sixth-day 17th, I went to Bradford monthly meeting held at Caln, and sat silent,
except towards the end of the last meeting,
I spoke a few words of the danger of a forward ministry.
7th-day 18th,
I attended the select quarterly meeting at London-Grove for the western quarter.--Here,
through laborious travail in the deeps,
life so far arose as to enable me to ease my mind in degree.

First-day 19th, I was at New-Garden meeting, in which I was silent.
After meeting went home with my dear friend William Jackson, who had, a few years past,
been very acceptably in our country on a religious visit.
2nd-day 20th, I attended the quarterly meeting at London-Grove,
being still shut up in silence.
3rd-day 21st, attended the youths meeting,
the adjournment of the quarterly and the select meetings,
in all which I had not a word to say.
Oh!
I was now, and mostly for a week past,
abased as in the dust--I could see no way to go forward;
nor yet could I go homeward--and though this distressing
dispensation is upon me while I write these lines,
yet through the experience I have already had, my faith fails not;
but I have an unshaken confidence that all does and will work for good,
and for my enlargement, in the Lord`'s time; but I find patience exceedingly necessary:
for thus to be shut up a week or two weeks at a time,
and feel in great degree destitute of divine enjoyment, is very trying;
and to feel it altogether out of our own power
to help ourselves out of this trying state,
brings the creature very low and humble; but, blessed be the Lord,
he never has failed to arise in his own time, and to deliver my soul from all trouble;
and I firmly believe he will, if I keep in the patience,
give the new song of praise to his eternal name.

Fourth-day 22nd. Attended their mid-week meeting at London-Grove,
where my tongue as it were still clave to the roof of my mouth,
while Mary Husbands was much favored and enabled
to lift up her voice like the song of an angel.
Fifth-day 23rd, I went to New-Garden meeting, and was still closed up in silence.
6th-day 24th,
I went to Nottingham in Maryland with some Friends who
were appointed by the quarterly meeting.
7th-day 25th, we attended their monthly meeting, where it was my place to be silent.

First-day 26th. I was still shut up in their meeting for worship.
I believe the Lord has some wise purpose in it.--I cannot find that I have offended him,
or disobeyed him: I know not that I have run too fast or lag`'d behind my guide:
I have ardently endeavored to do his will, and to endure his dispensations patiently.
O that I may be preserved in patience,
and yet live to see his purpose in all these things.

Second-day 27th.--My way is hedged up-- I see no way to go forward:
Who can comprehend my desolate state?
or understand my mournful condition?
These reflections are excited in me.
I am a man of sorrow, and acquainted with grief! the light of God`'s countenance,
which I have often eminently felt,
and which I then prized and now desire above all other joys,
seems to be quite withheld from me,
and nothing else in heaven nor in all the earth can satisfy my longing soul.
Lord, strengthen my patience that I murmur not after all that I have known of your goodness:
for I find daily bread is very desirable: fasting and hunger is painful to nature;
but shall I follow you for the sake of the loaves?
or will it do to leave you in times of emptiness and abasement?

I now remember the long fasting of your beloved Son, and that at length he hungered.
Oh! then came the tempter, but he was defeated; for he found nothing in that holy Lamb,
the Son of your bosom, that would receive any of his baits.
O my soul, may he find nothing in you!
You have often declared to others that the way
to heaven is through tribulation and sufferings;
and now when they are come upon you, see to it, that you keep the word of God`'s patience;
let patience have its perfect work,
lest the end of the Lord`'s thus proving you be frustrated;
for if all Satan`'s assaults be rightly resisted, and nothing of his offered food eaten,
you may find relief and consolation.
And though it is now very distressing to drink your Savior`'s cup,
and be baptized with his baptism into suffering,
yet it must be endured or you can never sit with him in his kingdom--
he has set you an example that you should follow his steps.
And as it pleased God, in bringing many sons unto glory,
to make the Captain of their salvation perfect through sufferings,
so will his true followers be made perfect in like manner.
Therefore, O my drooping soul! trust in the Lord, for unto whom else can you go?
He only has the words of eternal life: and you must not give back;
neither heights nor depths, things present or trials yet to come,
must not separate you from the love of God, nor from cleaving unto him,
or you will yet be undone forever.

This day I rode back to my friend William Jackson`'s, no way opening to go forward.
3rd-day 28th, no way opens yet;
my soul is brought to tenderness and my eyes to weeping and tears before the Lord.
Nature is ready to flinch,
but I am given to believe it is the Lord`'s will that his servants,
after multiplied experience of his helping and delivering hand,
should be so established on the immovable rock as to be
able to endure hardness as good soldiers,
to live by faith, and not by sight for a season,
and that as long as he pleases--and to say without dissimulation and without reserve,
under every trial meted out to them by his holy hand, It is the Lord:
let him do as seems him good.
Perhaps many trials, many deep baptisms yet unproved by me,
may be necessary for me to pass through,
before I can come up to and abide steadfastly in
this blessed renunciation of my own will;
but this is the mark, the goal at which I aim.
And it is the desire of my soul that the Lord`'s hand may not spare,
nor his eye have pity, until he brings forth judgment unto perfect victory;
until all that is in me bows to his sceptre; until I am perfectly renovated,
and can render up all, body, soul and spirit,
as a living and unreserved sacrifice unto the Lord; and until I can,
even when he hides from me,
(and to my sensation forsakes me) with perseverance and unabated confidence cry,
'`Abba Father, your will and not mine be done.`'
Even so, O Lord, work in me and for me, to the thorough completion of your own will.

4th-day 29th. Attended London-Grove preparative meeting,
and was still quite closed up from any sensible spring of the gospel.-- 5th-day 30th,
I attended New-Garden preparative meeting--this
and London-Grove make one monthly meeting.
Here the power of the word of life was renewed in me, in such a manner,
that I seemed to myself in some sort as if I had risen from the dead!
O how clearly, and beyond all doubt, am I satisfied in my own mind,
that it is nothing else than the power of an endless life that
again quickened and raised me up in a living testimony among
my brethren in this meeting.--For twenty days past,
I have not dared to open my mouth in one of the public meetings for
worship that I have attended--I have been at fifteen:
doubtless, if I would have been so presumptuous,
I could have stood up and delivered words in plenty at any of them.
I felt sensibly that I of myself could no more open any thing divine,
than a corrupt fountain can send forth sweet and wholesome waters.
I found I could not move forward in word and testimony,
to any kind of profit to the people or to my own peace,
while the cloud rested on the tabernacle;
my business was to keep silence before the Lord in abasement,
and as much as possible in patience;--before, all was shut up that none could open;
but now all seems to be so open as that no man can shut:--glory, honor and praise,
to him who leads me in the path of this blessed experience;
I can now bless his holy hand, both in his shutting and in his opening,
and rejoice with joy unspeakable,
that I have learned this experience and this dependance on him alone.

Twelfth month 1st, 6th-day.
I rested at a Friend`'s house and wrote to my dear wife,
for I had been so shut up that I scarce knew how to write before;
but now I wrote with satisfaction and comfort.

Seventh-day 2nd. I attended New-Garden monthly meeting;
here my way was opened in an eminent manner--it
was indeed a day to be remembered by many,
blessed forever be the Lord.

First-day 3rd. I was at meeting at Kennet; 2nd-day 4th, at Birmingham; 3rd-day 5th,
at Bradford; 4th-day 6th, at East-Caln; in all which I was silent.
5th-day 7th, I was at West-Caln meeting.
6th-day 8th, no way opens to go forward,
we turned back and rode about twenty-five miles towards Philadelphia,
and lodged at Isaac Thomas`'s. 1st-day 10th,
we were at the meeting at Newtown school-house.
2nd-day 11th, at Newtown; at both I was still closed up in silence.
Third-day 12th, we were at Haverford, with a little meeting of Friends, where,
blessed be the name of the Lord,
he opened the prison door and sat my soul at liberty--counsel
and doctrine flowed freely--their hearts were greatly tendered,
and my soul sang praises to the Lord.

Fourth-day 13th. Last evening we reached Philadelphia,
and went this day to Pine-street meeting, it being a good open time,
to the rejoicing of our souls.
5th-day 14th, we attended Market-Street meeting in the city, a favored open time,
to be remembered with gratitude.
6th-day 15th, I had a meeting at Germantown, where I had been shut up before,
my mind having often been drawn that way since my being there.
This was, blessed be the God of Israel,
a meeting wherein the gospel was extensively preached.
Great indeed was the power and dominion of truth this day,
wherein a close search was made.--Several other brethren having living powerful service,
and in conclusion my soul was poured forth in ardent supplication;
and light and life triumphed over death and darkness.--After
this we had a good opportunity in a Friend`'s family,
and then returned to Philadelphia with gladdened hearts.

Seventh-day 16th. We attended the burial of an ancient Friend at Derby,
where the Lord gave ability to preach the gospel in the
evidence and demonstration of the spirit and with power,
to the comfort of many minds, and I hope to the awakening of some others;
after which we had another opportunity in a Friend`'s family,
in which our souls were rejoiced together in the cementing love of God.

First-day 17th. The way having thus opened for me to go to Germantown, and then to Derby,
as above-mentioned, it now seemed clearly to open to go forward to Chester; where,
through deep wading and a living travail of soul, life rose into good dominion;
though I had to labor some time, even after I stood up, under much depression of mind,
looking carefully to see the way and find the stepping stones;
but the meeting ended well and truth reigned,
and being desirous of another meeting in this place,
accordingly one was appointed to be held next day.

Second-day 18th. The meeting was large and highly favored--and truth was triumphant.
3rd-day 19th, we had a meeting at Chichester,
where Truth gave us the victory.-- There was a little remnant of seeking souls,
to whom encouragement flowed sweetly this day.
4th-day 20th, were at meeting at Center; the forepart was painfully exercising,
but after a time of ardent breathing to the Lord, I felt a small arising of life,
in which I stood up, and as I advanced forward,
at length Truth arose into powerful dominion:
it was a baptizing time.--We were at Wilmington,
where I had been and suffered in silence some time past.
Notice being now given of our intentions of being here, it was a large crowded meeting,
and the doctrines of Truth were opened in my mind in great clearness,
and utterance being graciously afforded, it was indeed a highly favored day.
I could write much of this heavenly meeting, but all centers in the mercy,
favor and lovingkindness of the Lord,
without whom we are altogether helpless and cannot move to profit.
We had three comfortable opportunities in Friends families in this place,
one of which was with our ancient friend and elder in the church John Perry,
and his daughter, they living together.
He had been in New-England, where I saw him, on a religious visit,
(in company with our since deceased friend David Ferris) but now was very ill,
and I thought unlikely to continue long.
Truth was in good dominion while we were together,
wherein doctrine and supplication were livingly
owned by the in-shinings of the divine presence.

Sixth-day 22nd. William Jackson went home, intending to meet me again in a few days.
Hugh Judge and several others from Wilmington attending,
we had a precious meeting at White-Clay Creek;
my soul was deep in suffering for a short time;
but the power of him who is the Resurrection and the Life eminently arising,
the gospel was livingly preached in demonstration and clearness; the youth persuaded;
the faithful encouraged;
and the lukewarm warned--many minds were reached and much tendered;
and my own soul comforted and rejoiced.
But here I may note a trial that attended my utterance,
very different from that kind of exercise wherein it
seems difficult to find the stepping stones;
for here my heart was so full, and my cup so overflowed,
that I could scarce keep so deliberate as to
express myself to my own relief and satisfaction,
until, after standing a short time, I sat down and waited to get more command of myself;
when, standing up again, through a careful stepping along,
I had great peace and consolation in this day`'s service--praised be the Lord!

Seventh-day 23rd. We had a truly blessed opportunity in a meeting at Okesin,
where Truth eminently favored us, and opened several important doctrines and states,
which states were livingly spoken to in Truth`'s authority, to the tendering many minds;
may it be to their lasting benefit and instruction.
These four last meetings were in the government or state of Delaware,
and in the county of New-Castle.
After this last meeting we went to see our ancient friend Thomas Carleton,
in his eighty-eighth year, who had been in New-England in the service of the gospel,
having been esteemed a living minister of Christ.
He was, though confined at home, in a tolerably comfortable state of health;
cheerful in mind;
and seemed to retain a good savor of Truth,--being glad to see us and we him.

First-day 24th. We were at meeting at Concord, in Chester county, Pennsylvania,
at which place I had before attended a quarterly meeting,
unable then to open my mouth in a religious meeting;
but now the Lord set before me an open door,
which indeed has wonderfully been the case for several meetings past,
even the most so I think since my late long spiritual imprisonment,
that ever I witnessed, the enlargement of my mind,
clearness of the openings and strength of utterance, being far beyond my own expectation,
and greatly to the humiliation as well as consolation
of my poor exercised soul.--In this meeting at Concord,
I had some clear openings and was enabled to speak to several states, among the rest,
to a state of great unfaithfulness,
even though great had been the divine favor from time to time extended to them.
I had to sound an alarm indeed to these,
and to mention the danger of their house being left unto them desolate,
and the things belonging to their peace being hid from their eyes forever;
and of that awful declaration being sealed against them,
unless they speedily repent and turn to the Lord, namely,
"`he that is filthy, let him be filthy still.`"

After which a Friend standing up in the meeting,
in a feeling manner called upon them to accept the word of exhortation,
testifying that such was the state of some present,
and that they had repeatedly been warned, and called upon in a very pressing,
awful manner before now by such as were outwardly utter strangers to their situation.

Second-day 25th. We were at Chester monthly meeting held at Providence, where,
in the meeting for worship, I had very searching service,
yet dropping a word of comfort and encouragement to an exercised seed among them.
It was on the whole a good meeting.
3rd-day 26th, we had a good meeting at Springfield.
4th-day 27th, another at Middleton--precious also, especially the last,
wherein Truth rose into dominion, and its doctrines were livingly and largely opened;
a sifting time spoken of--better days or more reformed to succeed--
and a more general spreading of the truth among the nations.

Fifth-day 28th. We had a blessed meeting at Birmingham,
where I had been twice in this journey before, and quite closed up at both times,
but was now highly favored.
Here dear Hugh Judge and James Robinson, who had been with me several days,
left me and returned home,
my beloved friend William Jackson having met me again at this meeting,
in order to join me for some time longer.

Sixth-day 29th. We had another very precious meeting at Kennet;
here I had also been twice before under deep suffering,
my tongue as it were cleaving to the roof of my mouth;
but it was now eminently loosed and Truth reigned triumphant over all,
blessed be the Lord.
7th-day 30th, we had a good meeting at London-Grove, 1st-day 31st, we had two meetings,
the first a sweet and glorious one at Bradford, where I had been once before,
and now doctrine and advice flowed freely forth,
to the great reaching and tendering of the people.
In the afternoon we had a very laborious time in
silence at East-Caln where I had before been twice;
but blessed be the Lord who gave us the victory, Truth at length did arise,
and testimony and supplication were evidently felt to be in that which lives forever.

1787, 1st month 1st, and 2nd of the week.-- We had a highly favored meeting at Uwchlan,
wherein Truth prevailed over all,
as in several others of our late eminently baptizing seasons.
3rd-day, 1st month 2nd, we had another favored meeting at Goshen.
The doctrines of Truth distilled as the dew, and dropped as the gentle rain,
to the refreshing of many a tender plant,
and I trust to the opening of many understandings.
After the meeting at Goshen, we parted with our dear friend Edith Sharpless,
a living gospel minister, wife of Joshua Sharpless,
she having been with us at several of the last meetings;
but my friend William Jackson still continued with me.

Fourth-day 3rd. We had a good meeting at Newtown, where I had been before in silence.
Fifth-day 4th, we had a meeting at Radnor, and 6th-day 5th,
another at Merion --both heavy laborious seasons for some time;
but Truth rose into some dominion, especially in the last, which, on the whole,
proved a good and refreshing season, and ended in the savor of life:
the other also ended well.
7th-day 6th, we rode to Philadelphia, and visited several families,
rather in a way of innocent sociability, to take our leave of them,
expecting soon to return homeward--1st-day 7th, we attended the meeting at Pine-Street,
Bank and Market-Street--the first, after a time of close exercise,
was a good favored meeting--the second very dull and painful;
though a little life at length arose,
yet I did not get full relief among them--the third a very
large crowded evening meeting--and my mind was soon dipped
into a close engagement for their eternal welfare,
with an opening to stand up,
and I believe I got through to the good satisfaction of my friends,
and somewhat to the relief of my own mind,
as a parting opportunity with many beloved Friends.
Too many in this large city appear in lack of true magnanimity in the cause of Truth.
My spirit mourns over them,
with ardent wishes that they may lift up their heads above the world and all its frowns,
friendships and entanglements; and rise into the liberty of the sons of God.
May the young and rising generation shun that rock, the spirit of the world,
on which so many have been shipwrecked.
I am clear in it, that there is a precious seed among them, who, if faithful,
will shine forth in greater luster and purity,
than many of those who have gone before them.
O Lord, I pray you, hold them in your holy hand.

Second-day 8th. We attended the select meeting, where I had some small service:
and after visiting about twenty families to take leave of them, I felt clear of the city.
9th day of 1st month.
we left Philadelphia, and crossing the Delaware into West-Jersey,
had a meeting at Newtown: it was a painful and very low time for a season,
but ended to a good degree of consolation.
Now having left Philadelphia,
I felt such a flow of love and affection towards many there,
as perhaps words are inadequate to the full expression of,
with living cries to the Lord to preserve them, and bring them on the way rejoicing,
in the footsteps of the flock of the faithful companions of Christ Jesus.
4th-day 10th, we had a good meeting at Haddonfield,
but close and searching were we led in testimony, as Truth opened and enabled.
Here several beloved Friends from Philadelphia came over and
met us at this meeting.--I was truly glad to see them.

Fifth-day 11th. We had a meeting at Moores-town,
which I am abundantly convinced would have been more eminently favored,
had not my imprudence prevented; for I felt the arisings of life,
and some fresh openings, but felt with all,
that the spirits of the prophets were subject to the prophets,
and that I could not get forward in my openings until some
exercised mind or minds were relieved of their burden;
and being too hasty,
and fearing a backwardness would be given way to
in some one or other to the hurt of the meeting,
I stood up and expressed how it was with me, as if, because I clearly felt the danger,
I must speak of it! thus I hurt the meeting myself!--Oh! take heed when the ark jostles,
lest, putting forth your hand in your own time, like Uzza,
you bring death over your own soul!
Great was my distress and humiliation;
but the Lord at length in mercy opened the way again,
which had quite closed up on my unguarded motion.
Oh! his mercy endures forever! how wonderful was his goodness to Israel,
that even when Moses provoked him at the rock,
yet for their sakes he caused the waters to gush forth
from the flinty rock at the smiting thereof.
This meeting ended to good satisfaction, though marred by my own activity and folly.
Lord, correct me in mercy; bring down all in me that can move without a motion from you;
and when you have fully reduced me, then in judgment remember mercy,
that my soul may praise you forever.

Here I parted, in endeared affection, with Friends from Philadelphia,
who now went homeward; the rest we parted with yesterday.

Sixth-day 12th.--We had a meeting at Upper-Evesham; after some time of waiting,
a little light sprang up, Truth reigned, and we had a baptizing season together.
7th-day 13th, we had another at Lower-Evesham, to pretty good satisfaction.
1st-day 14th, we attended fore and afternoon meeting at Burlington, where, in the first,
after a season, ability was given me to sound a very pressing alarm to some among them,
who I found were very much unaccustomed to the yoke of Christ; which,
together with a very open time wherein I largely cleared my mind in the afternoon,
made me quite easy to leave the place,
feeling clear of a burden I had long had to feel at times respecting Burlington.--Lord,
rouse some there from their beds of ease, and comfort the honest mourners among them.

Second-day 15th.--We attended a meeting at Ancocas,
appointed for our friend Thomas Colly, from Old-England.
He and my companion W. Jackson had good service,
Truth being in comfortable dominion after a time of close inward travail;
but I sat easy in silence.
After meeting we returned to Burlington, and on 3rd-day the 16th, we rode to Stony-brook;
from there on 4th-day the 17th, to William Smith`'s near Rahway; and 5th-day 18th,
were at Rahway monthly meeting;
and being under great weight of exercise in the meeting for worship,
and way not opening to relieve my mind, I requested another meeting,
which was concluded to be held next day.
6th-day 19th, we attended the above-mentioned appointed meeting at the same place;
were shut up until time in common for meeting to end, and feeling some small openness,
I dropped some pretty close hints.

Seventh-day 20th.--I mourned and left them with a heavy heart, intending for New York,
but often looked back at Rahway,
and could not see my way so clear to go to New York as I wished; but it being homeward,
I rode forward to Elizabeth-Town Point, and there took boat for New York;
but providence prevented us; for soon after we put off, the large cakes of ice,
floating with the tide, shut us in for four hours,
that the boatmen were very apprehensive the boat would be crushed to pieces,
and we perish; but my mind was inward and stayed on God,
in the hollow of whose eternal hand and power I felt perfectly safe and easy:
faith and confidence in him and in his never-failing
providence were strong and quite unshaken.
I had not the least doubt but the winds, waves and all the elements,
were entirely at his command; and though the poor men kept crying out,
the boat would be cut to pieces, and appeared in much anxiety, I felt a perfect serenity,
and had no doubt at all but way would be opened through the ice,
either forward or backward, as the Lord pleased;
and I was quite resigned to its being either way--but at length,
after long looking and seeing no way, a way was opened, and we landed on the same shore,
and rode contentedly back to Rahway.

First-day 21st.--We attended their fore and afternoon meetings.
I had some openings in the first, but feeling no command to speak, the opening closed up,
and I suffered among them in silence.

Second-day 22nd.--We had a meeting on Staten-Island,
(where only one man Friend and his family live) among other societies:
this meeting was on my companion W. Jackson`'s concern,
and he had pretty good service among them.
I had only a few words.
There is an ear in some there to hear the truth,
and I hope, in some degree, hearts to obey it.
3rd-day 23rd, we got to New York, and 4th-day 24th,
were at their mid-week meeting: silent.
5th-day 25th, we went to the select quarterly meeting at Westbury, where I was shut up,
though William had good service.
6th-day 26th, came on the quarterly meeting for worship and discipline,
and adjournment of the select meeting, in all which I felt no strength to open my mouth.
Dear William was in some degree favored in supplication
and testimony in the meeting for worship.
7th-day 27th, I being clear of the parts, and about to return immediately home,
we had a precious parting opportunity at Fry Willis`'s,
wherein I had a few words in much tenderness to express,
and dear William was much favored in fervent supplication to
the Lord for our preservation and persevering integrity to him,
who first gathered our souls to an acquaintance with himself.
The presence of the Most High was livingly felt, and reigned over all,
to our unspeakable joy and consolation,
for words are inadequate to the full expression of it!--
magnified and adored forever be the Lord our God.

Here I parted with my dear companion William Jackson.
I have had to mourn in this journey over the declension from primitive zeal,
as also the great departure from that commendable plainness,
etc. which mine eyes have sorrowfully beheld in some places, especially in Philadelphia,
and from there too much spread in parts around them;
yet the Lord has a chosen remnant there--may they ever love and live near him,
and the others be brought home to the fold of rest, and weaned from all their vanities.
I rode this day, accompanied by Jacob Willets, towards the east end of Long-Island,
and next day, being 1st-day 28th, we rode to Sterling,--and 2nd-day 29th, took boat,
and landed in the afternoon at Grotton in Connecticut, from hence, parting with Jacob,
I rode to Abiel Gardiner`'s in Stonington.
3rd-day 30th, I reached East-Greenwich, and 1st month.
31st, 1787, and 4th of the week, got well home;
and to my joy and great thankfulness of heart to the Lord,
found my dear wife and family in pretty good health,
and much rejoiced to see and receive me again;
and I thought we were renewedly each others joy in the Lord.

I was out in this journey about six months and ten days,
and travelled by computation about two thousand miles.
