== Chapter VIII.

[.chapter-synopsis]
* Trials and exercises he passed through
* Exhortations
* A prospect of visiting the southern states
* Preparatory exercises--proceeds in the visit

After I got home from Pennsylvania,
I travelled through many heights and depths in my own mind, for about two years,
and seemed to be the nearest losing all faith and hope in God,
that I ever remembered to have experienced.
Oh! none knows, but the Lord alone,
the fulness of that bitterness of soul which I had to
endure! it was beyond all trials I ever had known,
and through which I did not always abide sufficiently on the watch-tower,
in strict patience, resignation and confidence in him who never yet has failed me,
when I have rightly trusted in him; but when I have thrown aside my shield,
and lost sight of my armor; Oh, my soul,
you only are fully sensible of the darkness and desolation
into which you have been plunged!--but magnified over all,
forever, be the great name of the Lord! he did not leave me, nor forsake me;
but after pouring out into my cup, large draughts of wormwood mingled with gall,
was graciously pleased (having thus reduced my soul, for the present at least,
to perfect resignation) to lift up the light of his countenance upon me,
in a marvelous and heart-comforting manner.

Oh, you traveler Zion-ward,
whenever you are tried with a deep and inward
sense of God`'s presence being withdrawn from you,
have a care, yes, a reverential care on your spirit, that you cast not away your shield.
It is indeed a great thing to keep the faith at such seasons.--Paul kept it,
and had to rejoice in it, near his final,
solemn close--I have fought a good fight--I have kept the faith;
but had he not kept the faith, he could not have fought the good fight,
for it is only in the faith, that any of our exercises can please God,
or benefit our own souls, or others-- all the willings,
runnings and actings out of the true and living faith,
do but run us further from that state wherein alone our
true happiness and advancement consists;
that state wherein '`God is all in all,`'--and this state we must come to, sooner or later,
or we can never know the fulness of the true
christian life.--Have a constant watchful care,
O exercised pilgrim,
that you seek not for ease before the Lord`'s
time--endure the turnings of his hand upon you;
and if the enemy of your soul present any outward delight,
or gratification of whatever kind; see that you embrace not his temptations,
however pleasing, or artfully presented and insinuated--the very sting of death is in it,
if you yield unto it; and although you may, for your trial and proving,
be left almost destitute of all sense of good,
and have scarce a grain of faith remaining;
yet though in this extremely depressed situation,
you may be ready to believe it will be of little
or no advantage to strive any longer against sin;
ready to say it is all in vain, and perhaps ready to conclude in a dark moment,
it will be no evil for you to give way to take a degree of delight in forbidden things;
yet I warn you, in the fear and dread of the living God,
touch not with the temptations of the seducer of souls.
Flee, flee for your life! flee from sin as from a serpent: if you tamper with it,
though you meanest not to yield, you are in imminent danger; and if you listen, you may,
contrary to your intentions, go near to the borders of destruction;
and if you should unhappily yield and surrender, your peace with God would be broken,
and every evil thing that thus gets in by consent,
must (if ever you know your peace again restored) be cast out,
by your suffering inexpressibly more than all the delight or enjoyment which
such a false gratification can possibly bring with it--O,
therefore, stand firm, keep on the watch-tower, resist unto blood, striving against sin,
and that in the faith, true and living faith, for it is that which gives the victory;
and though it seems almost gone, or appears as small as a grain of mustard-seed,
yet if you cast not away your confidence, but are rightly engaged to keep the faith,
it will enable you to '`fight the good fight,`'
and to say to these mountains of opposition,
temptation and besetment, be removed and cast into the sea, and it shall be done.

Remember Him who endured all Satan`'s allurements and temptations; who,
though he even fasted forty days in the wilderness, a state of desolation and trial,
yet he stood firm-- he ate nothing; he yielded not to any of the enemy`'s proposals,
but bravely repulsed him in them all.--Sing,
O you heavens! --he overcame and led captivity captive.
And after this dreadful conflict was over, the holy angels ministered unto him.
So it is, has been, and will be, with all his,
as they stand firm in the faith and patience of the saints; eating nothing,
taking in nothing of the enemy`'s alluring presentations.
God`'s grace ever was, and ever will be, sufficient for all these under every trial,
temptation and besetment.
Let Satan rage, let his messenger, the thorn in the flesh,
(however operating--in what way or thing soever insinuating) do its worst;
if the soul keeps on its armor and dwells in the patient watch and warfare,
the victory is certain, the holy promise cannot fail.

Because you have kept the word of my patience,
I also will keep you from the hour of temptation, that shall come upon all the world,
to try them that dwell upon the earth--this is your hour of trial--the very hour
and power of darkness--but stand still and see the salvation of the Lord:
let not in the temptation--give not way to carnal reasonings,
or consultations with flesh and blood; and, however severe the combat,
you will indeed be kept, and God will bruise Satan under you, yes bruise his very head,
and make you more than a conqueror.
The angel of his holy presence will indeed minister
unto you--you shall be greatly strengthened;
and verily you shall be fed, and that with food convenient for you.
Your joy shall be full, and no man, no nor evil spirit,
shall be able to take it from you, or to pluck you out of your heavenly Father`'s hand.

O the unspeakable consolation, and fulness of divine confirmation,
which my poor soul has received after seasons of
almost inexpressible conflict and besetment,
when I have abode in the true patience, kept the faith,
and so fought the good fight!--Eye has not seen indeed, nor ear heard,
nor the heart conceived, while in a natural state,
the joy and consolation which God pours into the souls which love him, and,
through all tribulations, keep the word of his patience.
O, there is abundant encouragement to stand firm through all;
yes even to press through every crowd of temptation to touch that which has the healing,
saving and preserving virtue in it.--Trials you will have,
this hour of temptation will indeed come upon all the world;
none ever were exempt from a season or seasons of probation and
conflict--and it is in order '`to try them that dwell upon the earth.`'

O my God, you have done much for my soul--you have redeemed me through judgment,
and brought me forth to see the light rejoicing--be pleased, if it be your holy will,
still to carry on your work in me,
until all that is offensive to the purity of your holiness be
consumed--until my will becomes wholly conformable to your will,
even so amen!

1788+++.+++ Having thus passed through some very trying seasons,
the Lord was pleased to lay it upon me to make a visit
to Friends and others in the southern states,
to sympathize with the suffering seed, and endeavor, as ability might be given,
to stir up the pure mind in my fellow men,
by persuading them to seek an increasing acquaintance with God,
the only source of all sure consolation.
This brought me under close trial,
and at times I had many reasonings and discouraging considerations,
with fears about a subsistence for my family;
for although I could ever say in that respect, as well as in spiritual things,
'`hitherto the Lord has helped us,`' yet it often looked almost
impossible to me that they should be in any comfortable degree
provided for if I gave up to be so much from home and out of business;
but the holy injunction was so often, so clearly repeated,
that I dare not refuse obedience to it.
So after many and various conflicts,
my soul bowed before him in a view of his omnipotence,
omniscience and unbounded goodness, I was enabled to give up,
and casting my care upon him, in regard both to temporals and spirituals,
I said in my heart, '`here am I, send me;`' send me, O holy Father, wherever you please,
I refuse not to follow you into any corner of the earth--only
do you but go with me and support me.
My life, my strength, and the length of my days,
I devote to your service--my family I resign to your
holy care and keeping--to you I dedicate them.
O, may you watch over and preserve them!

At this surrender of all things, I felt the light of heaven to fill my soul;
it shined in me and round about me, above the brightness of the sun indeed,
and opened my prospects into distant nations,
with some belief that the Lord was opening a
large field of labor for me in foreign countries,
to be entered into in his own due season.
I said, '`good is your will, O Lord!--dispose of me, your unworthy servant, as you please.`'

So at a suitable season I opened my concern respecting a visit to the southward,
in a select meeting of ministers and elders,
who expressed a good degree of unity and clearness.
After this, believing it best to remove my family to my old home at North-Providence,
and having done it accordingly,
I applied to the preparative meeting at Providence in order that my concern
might get regularly forward to the monthly meeting for a certificate.

And having obtained a certificate of the concurrence of the monthly meeting,
it was carried to the quarterly meeting in the first month 1789;
and there the Lord was pleased to fill my soul with strength,
and gave utterance to my weight of exercise and concern,
to the greatly tendering of my own heart, and the hearts of my brethren and sisters.
I opened it both in the men`'s and women`'s meeting--and
received a certificate of their concurrence with my concern:
their near sympathy with me under the exercise attending it,
and their prayers for my preservation through
every baptism and trial that I might meet with.
Being thus furnished,
and having early had a prospect of being at Philadelphia at the time of the general
spring meeting of ministers and elders to be held there in the third month 1789,
and still feeling bound to endeavor to be at that meeting, I got ready,
and my friend Daniel Aldrich having found a concern upon his mind to accompany me,
and obtained a certificate of concurrence of his friends,
we set forward on the journey the ninth of the third month 1789,
having taken an affectionate and heart-tendering farewell of my dear wife and family,
recommending them to the Lord for preservation, consolation and support,
in full confidence that he would not fail them if their trust continued firmly in him.
We rode several days,
passing through the state of Connecticut without meeting with any of our brethren,
except a few in one place, after parting with my dear father-in-law,
my beloved brother-in-law Joseph Anthony, and our kind young friend Obadiah Brown,
who rode part of the first day with us.
We met with very kind treatment among the Presbyterians in Connecticut;
and I had to believe, from the state of mind which many of them appeared to be in,
and from the impression which I had among them,
that a time would yet come when the blessed Truth would have a much freer entrance,
operation and acknowledgment among that people than has yet
been evident--may the Lord hasten his great work in the earth,
and when and so far as he pleases,
take unto him his great power and reign throughout the kingdoms of men.
We got to New York on 7th-day, the 14th of the month,
and stayed their fore and afternoon meetings on first-day, but were quite shut up therein.
Next day went to Rahway in New-Jersey, and so on to Philadelphia,
where we arrived on 6th-day the 20th, at evening,
having attended a little meeting by the way at Bordentown in Jersey,
and also the quarterly meeting at Haddonfield.
Here the Lord favored us with his presence, and opened our way to considerable service.

7th-day 21st--Began the general spring meeting of ministers and elders at Philadelphia.
Truth mercifully owned our solemnity,
and wonderfully favored in the several sittings of the select meeting--the several
meetings for public worship--as also in the three monthly meetings in the city,
which came on in course after the general meeting concluded.

We left Philadelphia on 6th-day the 27th,
and were next day at a select meeting at Wilmington, and on 1st and 2nd days,
at their general meeting for worship there, where Truth gave us the victory,
and afforded ability to exalt the precious testimony thereof,
though through deep sufferings in spirit.
After this we had meetings at Christiana-Bridge, and the Head of Elk,
among people mostly not of our society.
But though I felt a strong opposition in some at the last place,
yet Truth gave the victory at both these meetings,
the last being eminently owned by the overshadowing of divine life,
in the power and demonstration whereof the everlasting gospel was
preached among them--may it fasten as a nail in a sure place.

Fourth month.
2nd, being 5th day of the week, we tried to get to the monthly meeting at Deer Creek,
but could not get over the river Susquehanna until too late to reach meeting seasonably;
but we found we had a service among several young Friends near the river.
After we had cleared our minds to them, the way soon opened for us to cross the river:
so we had a meeting next day at Deer Creek, in which I was quite closed up.

7th, 1st and 2nd days--We had meetings at the Fawn, Bush River, and Little Falls.
3rd, 4th and 5th, we were at Gunpowder, Patapsco Forest, and Baltimore: mostly shut up.
We stayed at Baltimore until after their two meetings on first-day; were shut up,
yet favored with faith and patience.
On 3rd-day the 14th, we had a meeting at Elk Ridge; were shut up,
except the expression of a few words.
4th-day we were at their preparative meeting at Sandy-Spring,
a blessed and highly favored time--very open;
many attended the meeting for worship who were not Friends.
Truth`'s doctrines flowed freely and largely among them,
I trust in a good degree of the evidence and demonstration of the Spirit.

Fifth-day, we attended a preparative meeting at Indian-Spring,
and a select meeting after it, each exercising,
though we got a little relief through attention to that
which enabled to labor honestly as ability was afforded.

Sixth-day 17th. Were at their monthly meeting there, before which, in the morning,
we were at the adjournment of their select meeting:
it was indeed a day not to be forgotten, I trust by us,
nor by many of them who were present.
In the select meeting truth very unexpectedly opened some
important and instructive (though to the natural man
mysterious) doctrines clearly to the understanding of my mind;
and the power of the word of life accompanying, I opened them, so far as required,
to the meeting, to the great relief of my own mind.
The meeting for public worship was eminently owned by the over-shadowings of divine love,
under which covering, utterance was largely given,
and the doctrines of the gospel were opened and promulgated this day,
to the reaching and tendering many minds,
if not most present--the doctrine of God`'s free and universal grace,
and its entire sufficiency for the salvation of all, being especially illustrated,
and at the same time that the work of salvation
goes no further forward in us than we yield to,
join in, and cooperate with this blessed principle.

In the meeting for church discipline,
we had large opportunity in the fresh extendings of gospel love,
to clear our minds to both brethren and sisters, both parents and children,
on several important branches of our religious testimony.
Our souls were comforted, and the living among them rejoiced with us.
Things are low in this land;
but yet we were witnesses that a remnant are on the right foundation,
and engaged to promote the right thing, and we had a hope that the number would increase,
and that a revival might take place in these parts.

Seventh-day, we rode to a place called the Clifts.
This night, as I lay awake in bed,
I was almost overcome with the fresh extendings
of the love and goodness of God to my soul,
and seemed swallowed up in the in-shinings of his luminous and glorious presence.
In this almost ecstatic enjoyment, my soul bowed in awfulness and reverence before him,
and the whole man was renewedly offered up to his service,
to be disposed of as he pleased: and after thus continuing for some time,
subjectly given up to his holy will,
witnessing his glory to rest upon me as a royal diadem,
and receiving some sweet manifestations or confirmations of his fatherly
care having been day and night extended to and over me from my youth,
for my preservation and advancement in the way of life and salvation,
it pleased his infinite majesty to condescend once more (as at some few gracious,
solemn and peculiar seasons in the course of my pilgrimage
before) as it were to set open the windows of heaven,
and spread before the view of my mind the excellency and glory thereof;
and (which above all rejoiced my soul) he also set open the arms of his mercy;
shewing me and giving me feelingly to know that although,
at many times in the course of my life,
I had not so kept under a sense of his preserving
influence as to shun the snares of the enemy,
but had sometimes been entangled in them, yet there was nothing retained against me,
but that all was freely remitted and washed away in the blood of the Lamb;
and that if I henceforth stood firm in obedience to him,
and in the promotion of his cause, as ability was given,
I should reign with him in glory, world without end.
I found myself clothed inwardly as it were with white linen!
I saw that my garments had in days past been much defiled,
but were now washed and made clean.
I saw that I had indeed come thus far '`through great tribulation,`' and that,
had I not submitted thereto, I must have remained '`filthy still.`'
My very soul bowed in deepest prostration before the throne of God--my cry
ascended for future preservation--and I vowed continued obedience through
his help to the end of my stay here in this vale of tears.
My heart was lifted up in songs of praise for the wonders of his love to me-ward;
and I had to contemplate and adore the unmerited kindness and
goodness of his gracious dealings with me-- I could say he had
plucked my feet out of the mire and clay,
and set them upon a rock, in good degree established my goings,
and put a '`new song in my mouth, even praises to my God.`'
O Lord, hold me fast forever--keep my soul alive to the end--make of me,
and do with me what and as you please--I am yours; this is my rejoicing:
I wish ever to remain yours; and if ever my own will, my own corrupt inclinations,
presume to rend me from you, O, my gracious Father, be pleased to interpose,
and to lift a standard against all that may rise up against me
for evil.--I dare not depend on my own strength or resolutions,
but must look unto you to strengthen me in weakness, and to make effectual my strivings,
wrestlings and resolutions against sin.
I commit myself wholly to your care and keeping--be my light and my leader,
and hold me in your holy hand forever.
Amen.

Next day we had a glorious meeting at this place, at Friends meeting-house,
but mostly among such as were not Friends, many of them called Methodists,
a people that abound in this land,
and some of their hearts have been touched with a live coal from the holy altar;
but they seem very unsettled, many having hurried forward into much religious activity,
being very noisy, talkative, and almost, if not quite ranting;
yet I hope some of them will come to a settlement in the truth;
but expect many will run quite out, and finally shake off their religious exercise,
this being the natural consequence of making haste into religious
performances without the pure leadings of truth therein.
My heart and mouth were largely opened among them in
this and several other meetings--and this day,
in a special manner, the streams of life flowed plentifully and sweetly,
to my great satisfaction and comfort, and to the refreshment of many minds--glory to God,
who has hitherto helped us! we can do nothing without his help,
but can do all things required of us through his strengthening influence in and upon us.

2nd and 3rd of the week.
We had precious meetings at Herring-Creek and Bush-River, mostly among other people,
as Methodists, etc. though at Friends meeting-houses;
for Friends at these places are few in number;
there used to be many valuable Friends belonging to these meetings.
We were very clear in our judgment, that Friends, having kept such numbers of slaves,
did much contribute to the ruin of their posterity:
for the poor negroes were put to do nearly all the work,
while the children of Friends were brought up in pride, fulness of bread,
and abundance of idleness, riding about for pleasure, living at ease and in fulness:
this was productive of many evils,
and opened a wide door for unprofitable and pernicious intimacy with hurtful company,
until, alas,
the youth in some particular places are almost all departed from the way of truth,
and an almost total desolation reigns in some places in this land.
Oh the mischiefs of idleness and oppression!--may it be the special care of
all religious people strictly to bring up their children to some honest,
industrious and useful employment: I believe Truth requires it;
that a blessing attends it; and that much evil is prevented by it.
My spirit deeply mourns over the sorrowful and dangerous situation of such who have,
as they say, nothing to do--believing they will almost certainly '`soon learn to do evil.`'

Next day, my companion being unwell, we kept house;
and the day following rode near half the day towards Alexandria,
where we stayed until first-day the 26th, and were at the fore and afternoon meeting;
to both which came many of the towns people, Methodists, Baptists, Presbyterians,
etc. and the Lord was graciously pleased to give us a good time in both meetings,
especially the last, wherein Truth reigned over all--blessed be the name of the Lord.
This was the first place we were at meeting in Virginia.
Next day we rode forty-five miles to Stafford,
and had a very dull meeting there the day following; it was silent,
except a few words at the close, which I felt easy to drop with my hat on,
informing that the life was so low, and the springs so shut up,
that I had not dared to attempt any thing under pretense of preaching the gospel;
but that I felt a particular freedom to mention something that
had turned in my mind to those not of our society:
I told them, a minister of the gospel had nothing of his own to offer to the people;
his whole dependance is on Christ; he must speak as the oracle of God,
and only in the ability that God gives;
therefore is under an absolute necessity to keep silence,
unless immediately commissioned and habilitated from God--that, for their sakes,
through the flowings of the love which I felt to them,
I had rather desired as a creature, that the way might be opened for communication;
but that I found a slow of love and good-will was not a sufficient qualification to
preach the gospel--mentioning that Saul`'s forcing himself and offering,
through a fear that the people would be scattered abroad, displeased the Lord,
and Samuel his prophet--that,
therefore I had not dared to attempt to preach the gospel among them,
knowing who it was that said,
such as kindle a fire and warm themselves by the sparks of their own kindling,
shall lie down in sorrow.

My beloved companion having been unwell more or less most of the time for several weeks,
now grew worse,
so that we were under the necessity to tarry here at
the house of our friend Robert Painter several days;
during which time my said companion came to a conclusion to leave me and return homeward,
as he and I both very much doubted his being able to go through the journey.
This was indeed a trial to me in my deeply exercised state of mind,
and gladly could I have turned with him,
but could find no peace of mind in looking that way.
So on 6th-day the 1st of the 5th month, he being a little mended,
and feeling easy in his mind to go homeward, and I not daring to urge him forward,
we parted in much brotherly nearness and affection,
having travelled together in true gospel love
and harmony--he with a pilot or rather a guide,
going for Alexandria, and I with another,
rode to a place in Culpepper called Southland meeting,
crossing the river Rapahannock in our way.
This was indeed a day of deep anguish to my soul; I felt unusually disconsolate,
and could not refrain from almost excessive weeping: my heart seemed ready to break,
for I was not only left in a strange land almost without a sympathizing friend,
but was inwardly very much stripped;
yet I was favored to be in a good degree resigned under all,
and my cry was fervently to the God of all consolation,
that he would keep me steadfastly given up to do
and suffer whatever he in wisdom saw best for me.

Next day had a silent meeting here,
except a few words of information after meeting broke up, or as we parted.
The day following, being the first of the week and 3rd of the 5th month,
I was at Caroline meeting, silent here also,
and more painful and distressing than any I had been at in this journey before.
I remembered the account of Christ`'s agony, his sweating as it were drops of blood,
and crying out to his heavenly Father, My God, my God, why have you forsaken me!
I saw the propriety of his passing through this trying scene:
and I believed it necessary for me to go through that portion of sufferings assigned me:
and though he passed through his for our sakes,
he being experimentally touched with a feeling of our infirmities and
sufferings--not but that his Omniscience as God could see and behold
it all without feeling it in a body of flesh;
but as the brethren were partakers of flesh and blood,
he willingly took part of the same,
and in ail the sufferings incident to the brethren in this life,
and therein to set us an example of faith, patience and perseverance through all;
and that he might both feel and manifest this
resignation in the most conspicuous manner possible,
he was so far stripped as to feel as if he was forsaken; yet even in this extremity,
though as man, he was ready to wish the cup to pass from him,
yet he centered in--not my will, but yours be done.

I saw that there was no way for me to get rightly along, but through the like submission;
and this afternoon every painful impression was removed,
and the light of life shined into my soul with unclouded clearness; I was set at liberty,
and judgment was indeed brought forth unto victory.

Second-day 4th. Had a meeting at Cedar Creek--not painful, nor yet had I much enjoyment;
but was quite shut up as to words in the ministry;
yet had an engagement to inform the people, at the conclusion of the meeting,
of the sorrow I often had felt,
on account of the gross darkness which yet prevails in
regard to what is called preaching the gospel,
many engaging therein without divine authority and influence,
who consequently cannot profit the people.

Third-day 5th. Had a meeting at Genito, and one next day at Richmond,
among people mostly not of our society; these were both blessed meetings;
Truth`'s doctrines were largely opened to my relief,
and I trust to the refreshment of many others.
5Th-day 7th, had a meeting at the Swamp, and one next day at Black-Creek,
another the day following at Curles--all dull and almost lifeless;
yet I labored a little in the ministry in all of them in a low depressed manner,
and in the last, though dull in the forepart, yet through an honest attention,
in lowliness and deliberation, to a small motion, I found much relief.
Blessed be the Lord who kept me humble, and careful in utterance.
For I am well satisfied,
that if I had presumed with so small a motion to have
risen into much strength of utterance hastily,
I should have dried up that little spring of life which I felt,
and so run into a flow of words, to my own sorrow in the end,
and to the preventing that benefit which I hope some received.
And here I have seen that many, who have a real gift in the ministry,
do sometimes greatly hurt themselves, their services and the people,
for not lying low enough, nor taking care enough, to find the safe stepping stones,
from step to step, they run out of the little, though lively gift,
into a hasty elevation of words;
not indeed without very considerable degree of warmth and animation.

First-day 10th. I was at Wayne-Oak meeting, it was dull;
yet I did near the close say something by way of ministry,
which afforded me a little relief.
I was hereby renewedly assured that the gospel cannot be preached,
but when the Lord opens the real spring of life in the preacher,
I rode after this meeting ten miles towards another meeting-place,
expecting to go on there next day in order for a meeting;
but my way seemed so shut up next morning, that I dared not proceed;
and withal was almost too much unwell to continue riding; yet had the way been open,
I believe I should have gone forward; but believing it unsafe,
both for myself and Friends,
to appoint meetings without a sense of Truth`'s direction and assistance,
I returned to my friend John Crew`'s at Wayne-Oak.

On second-day I was reduced to a very destitute condition,
wherein all my former experience seemed to afford little or no satisfaction.
This season of stripping had been coming upon me for several days,
and continued for some time after.
But I have not the least expectation of being able, by words or writing,
ever to convey a clear and adequate idea of the darkness,
desolation and distress attending this dispensation,
to any who have not in degree experienced it: those who have may,
if they should read these lines when I am in another state of existence,
feel a lively sensibility hereof--feel as one a little before them has felt,
deeply abased, exercised and heavy laden;
like to what their poor souls may have yet for a season at times to
groan under--and if it please God to bless this present relation to
the benefit of any of his drooping children,
I grudge not my having passed through the sore conflict,
nor my pains in preserving these memoirs of my exercised life.

Third-day 12th--I attended the week-day meeting of Friends here at Wayne-Oak,
as it came in course--it was very small--I was much stripped,
nor had I ability to say any thing in the meeting until near the close of it,
feeling to myself one of the most unworthy creatures;
yet after all this I was made to rejoice,
and for this very abasement and reduction of mind;
and this rejoicing increased until I had to express a little of it in the meeting,
much to the tendering a few brokenhearted friends present,
though I could not rise into more life than just in weakness to utter a few expressions;
yet therewith felt easy; but concluded, as I had the day before,
that if way did not open with more clearness for the continuance of my
journey after the yearly meeting then soon coming on at this place,
I might return home:
fully believing that he who called me forth into his service in this land,
would open the way with clearness to proceed so far as his will was for me to go;
and that as he would not withhold the necessary openings, I might safely,
after waiting a proper time without obtaining any manifestations to the contrary,
return to my family;
yet remained given up to go forward if he should open the way for it.

Fifth-day 14th,
In silence and inward poverty I attended the select quarterly
meeting of ministers and elders at White-oak Swamp,
and next day the public quarterly meeting here; out of weakness I was made strong,
and many with my own soul rejoiced in the Lord.
7th-day 16th, began the select yearly meeting,
and this day was held the meeting for sufferings also.
Next day two large meetings for worship, and one the day following;
then the church discipline in the afternoon,
and by adjournments until 4th-day the 20th. The
meetings for worship were livingly favored times;
those for discipline, for lack of deep dwelling in the life;
and more engagement for good order, were not so lively,
yet Truth owned the faithful labors of a remnant,
and life sprang up at times to their refreshment.
The meeting for sufferings was also favored:
it appeared that the members thereof had been, and with some success,
engaged in support of the rights of the injured Africans, at which my soul rejoiced;
for many of them groan in cruel bondage in this land.
But I believe the Lord will more and more arise for their deliverance,
and work their emancipation; and that through judgments poured out upon their oppressors,
if the hard hearts of those who make them groan are not softened by milder means.
I used among Friends here a plain honest gospel freedom, which gave me great relief,
and tendered many of their hearts.
So after supplication and thanksgiving to God,
this yearly meeting concluded under a fresh sense of his divine goodness.

Fifth-day 21st--Had a meeting here with the negroes, and though silent myself,
yet my dear friend John Lloyd, from Pennsylvania, had good service therein.
Next day we had a meeting at Tyrees, wherein I was closed up,
but my friend had a pretty open time.-- 7th-day 23rd, was at Skemins; and first-day 24th,
we had a small meeting at Williamsburgh, a town where no Friends live.
I had little to say in these meetings.
It is to the poor the gospel is preached--even Jesus did not
many mighty works in some places because of their unbelief.
It remains true to this day, that unbelief and hardness of heart shuts out the gospel,
or prevents a free entrance thereof among such
as have not a sense of their own necessities,
but think themselves rich, full,
and to have need of nothing--for the word preached cannot
profit unless it be mixed with faith in them that hear it.
No wonder therefore that those who run when the Lord has not sent them,
and continue preaching to the people without feeling,
or evidently finding a door of entrance into their hearts,
do not profit them by all their long,
laborious and creaturely exercises among them--for
nothing gathers to God but what proceeds from him.

On second-day the 25th. we had a meeting among the Methodists at New-Kent.
J+++.+++ L. had a little testimony among them; I was quite shut up;
yet after meeting broke up I endeavored to impress them
with a sense of the utter uselessness of all preaching,
however much it may warm and move upon the passions,
except that which is from a real spring of divine life in the speaker.--3rd-day 26th,
went to Wayne-Oak, and 5th-day 28th, I attended Curles meeting;
it seemed almost without light or life until the latter part,
when a gleam of true light appeared; by keeping to which, though in great weakness,
victory was obtained,
and the meeting ended to comfort and rejoicing--though we found it
for a long time almost impossible to sing a song of Zion in a land
where the harp was hung on the willow! for it was truly mournful to
see the city sit solitary that was full of people.
Truth had once prospered here,
but now the posterity of faithful Friends were nearly all carried away captive--but
a little gleam of hope arose in my mind that there would be a revival in this place.

My way opening with more clearness,
I got along with much satisfaction and fulness of divine joy,
having several large and blessed meetings--one at a Friend`'s
house a few miles from Petersburgh over James River,
one at Gravelly-Run, one at Burleigh, and another at Seacock.--After that at Burleigh,
we had a good watering time in the evening, at a Friend`'s house,
among black people and some others, besides a few Friends.
Truth reigned over all in this blessed meeting--the poor negroes
blessing God in accents bespeaking heart-felt reverence,
and deep thankfulness of soul, for this favored season; one of them in particular,
saying, '`O may I ever bless and praise my great God,
for the great good he has this evening done my soul! for the sweet precious love
that I have felt--I never felt such heavenly love before--blessed forever be the
great God!'`--my heart was much affected at the feeling sensibility which this,
and several more of the poor blacks discovered in their way, of returning thanks to God,
both in the evening, and again next morning; for they seemed full of songs of praise,
even in the morning,
for the evening`'s precious favor--may the Lord Almighty hold them in his hand forever,
and may my soul never forget the descendings of heavenly rain upon and among
us at that comfortable season--for which his holy name be praised forever.
Amen! And I am renewedly confirmed,
that there is a real work of divine power among many in this land, both white and black;
though yet much unsettled--may they be brought to witness a greater
degree of clearness and establishment in the everlasting truth!

After these we had meetings at Black-Water, Stanton`'s, Vick`'s, Black-Creek,
Johnson`'s and Summerton--In the two first of these I was silent;
but believe they were all times of renewing of strength to some who attended them.
The doctrines of the gospel were livingly proclaimed in the authority of truth,
dear John Lloyd`'s way being opened.
--Next we had a glorious meeting at the western branch the 9th of the sixth month,
wherein there seemed to be no lack of openness, power and utterance;
many were deeply affected, bowed and tendered--blessed be the Lord forever! 10th,
we had two dull meetings at Bennet`'s Creek, J. L. in the first, and I in the last,
got some relief, through a little honest labor in great weakness among them,
5th-day 11th, we had a strengthening and refreshing meeting at the widow Bufkin`'s,
where a meeting is held once a month.
I had a good open time--the doctrines of the gospel were largely opened,
with strength and clearness, to the tendering of many minds.

6th, 7th and 1st days, we had meetings at Norfolk, Portsmouth and Suffolk,
places where no Friends live, except one small family,
and a young man in Suffolk--the first and last
of these meetings were held at the court-houses;
that at Portsmouth in an upper room in the market-house.
The people at Norfolk behaved undevoutly at meeting, kept running out,
talking whispering, laughing, gazing about, etc.
I reproved them for their incivility, telling them,
that the most mournful consideration of my mind respecting their behavior,
was the great inexperience of the realities of religion,
and the great unacquaintance with the nature and importance of divine worship,
which their conduct had sorrowfully manifested:
and so enlarging a little upon the subject of worship; and that God, even a present God,
is the object thereof, and not any man--that God, to be worshipped aright,
must be felt after, known and reverenced; with a little more on some other subjects.
We left them with heavy hearts, finding very little open door of utterance,
because there was scarce any door of entrance into their hearts, except in a few;
and yet I had a secret hope, and some belief,
that that day`'s work would not be altogether in vain.

The meetings at Portsmouth and Suffolk were heavenly watering seasons,
wherein Truth reigned over all.
Many minds were much reached and tendered, and a general solemnity was very prevalent.
The Lord has a visited seed in this land up and down in many places.
O that they may come to know a greater stability and settlement.
After the meeting at Suffolk on first-day,
we had a parting opportunity with many Friends,
who attended from different parts of the country around.
This was a most melting and reviving season.
The everlasting Arm was marvelously magnified and made
bare! the holy name was livingly exalted and praised;
the souls of the mourners were eminently comforted;
and the lukewarm powerfully warned--blessed be the name of the Lord forever and ever,
for his goodness to my poor soul at this precious season--may
I never forget that fulness of divine light and life,
that overflowing cup of sweetness and consolation,
wherewith he enriched my mind in that ever memorable day.

After this heavenly banquet, I parted with my dear friend John Lloyd,
who had for several weeks been agreeably my companion,
and with the rest of my friends of Virginia now present, and set out for North-Carolina,
accompanied by Robert Jordan and wife,
where I arrived next day at the house of our kind friend Thomas Newbey.
In the course of the six following days,
I had or was at eight meetings at Perquimons and Pascotank counties,
at Friends meeting-houses, as follows: 3rd-day, 16th of the month,
at that called Wellses meeting-house.
4th-day, Old Neck--and in the afternoon at Sutton`'s Creek.
5th-day, at Little River. 6th-day,
at New-begun Creek--and in the afternoon at the Narrows of Pascotank.
Seventh-day, monthly meeting at Simmons`'s Creek--and 1st-day,
at the Piney-Woods.--These were all favored open seasons, except that at Sutton`'s Creek,
and that at the Narrows; in both which I was quite shut up,
save in that at the Narrows I did express a few words at the breaking up of the meeting,
respecting the nature of gospel ministry; as that it never was in man`'s power,
merely as man, to preach the gospel, etc.
Oh! how I then mourned, and often have mourned,
to see the eager expectations of the people so widely
misplaced on the creature instead of the Creator:
and this is undeniably the case with all who expect man
to preach to them without divine assistance;
for man is but the creature,
and unless immediately filled and qualified with divine light, life and power,
is as destitute of any ability livingly and profitably to preach that
gospel which is the real power of God unto salvation,
as he is of power to cause the outward rain to descend from heaven.

In several of the foregoing meetings Truth eminently favored
us together--the gospel was preached in the life and authority
thereof--many minds were strengthened and encouraged,
and the great name was magnified and praised.
After this I went to Rich-square, and on 4th-day the 24th, was at their meeting there,
where Truth opened the way with strength and clearness to edification and rejoicing.
Next day went to Jack-Swamp, and being joined by my dear friend James Ladd,
from Wayne-Oak in Virginia,
who came with a certificate to accompany me a while in this journey,
we had a meeting on 6th-day at this place: it was an open, good time,
Truth was freely declared, and many minds reached and tendered.
7th-day 27th, we had a blessed meeting at Hallifax,
a small town where there are none of our society.
The gospel power was eminently felt, and, in the evidence and demonstration thereof,
the free grace of God to all men,
the necessity of working out our own salvation through the assistance thereof,
and several other important gospel truths were livingly and largely opened.
Next day we had a meeting at Stony-Creek, or Tar-River, as it is sometimes called.
From there we rode to Contentney, and, first of 7th month.
attended the preparative meeting of Friends there--a dull time it was,
and but little openness for gospel communication.
After meeting, and the two next days, we rode to a place called Core-sound; and,
on 7th-day attended a monthly meeting there; it was a low time,
yet way opened for Truth`'s testimony to be in some degree exalted.
Next day we were at their select and public meeting--the
public meeting was eminently overshadowed with divine favor,
and made to be a time of blessed visitation to many souls;
praised be the name of the Lord.

Second-day 6th. We had an exercising meeting at Clubfoot-Creek; there was some openness,
so that considerable labor was bestowed,
but not to much relief or satisfaction of our minds--
which was pretty much the case next day also,
at a meeting we had at Newborn.
In this town there are no Friends, and the people`'s minds very light and unstayed,
that it was painful to behold the airiness and irreverence which prevailed in too many.
They got a gentle reproof, and we left them in sorrow as to our minds,
though but little or no true sorrow appeared in them.

Fourth-day 8th. We had a very heavenly meeting at Friends meeting-place on Trent;
and another next day about twenty miles further up the river Trent,
at a place where a meeting was lately settled.
Friends appeared pretty well engaged at these two places,
and I hope an increase will be witnessed among them.
7th-day 11th,
we attended the monthly meeting at Contentney--a trying time it was to my mind;
but way opened, after long suffering in silence, to clear my mind in some good degree.
Next day we were at the first-day meeting at the same place--silent.
3rd, 4th and 5th days, we were at meetings at Nues,
Bear-Creek and Turner`'s Swamp--all trying times.
In the first, the weight I felt seemed almost insupportable, but at length way opened,
and an extraordinary time we had;
several states were remarkably opened and spoken to in Truth`'s searching authority,
and yet with that sympathetic, persuasive energy,
that it made way into almost every heart.
It was a tendering time, but, alas! the next day was a time of difficulty,
as well as distress, and no way opened to get much relief by communication,
though I could not well avoid dropping some close expressions or alarming hints,
but I saw little or no prospect of much advantage from
them to those to whom they belonged:
they seemed like those who had ears to hear, but heard not,
or as if they had shut their ears, and hardened their hearts.
I felt for them with a heart full of sorrow.
The last meeting was more comfortable, though I was quite shut up.
My dear friend James Ladd bore a lively well-adapted testimony, in which I rejoiced,
and found relief of mind.

Sixth-day, I rested at my friend Benjamin Arnold`'s, being unwell.
He and his wife were very kind, both being well-engaged Friends:
the fruits of whose godly parental care and authority very plainly and agreeably
appeared in the behavior and appearance of their well-ordered offspring.
Oh, much lies at parents doors! much may they do, through divine aid,
for their children`'s good, by proper, constant care, watchfulness, advice, reproof,
restraint, correction and commands; all in Truth`'s authority, as occasion requires;
and that not generally so much in the austerity and rigor of compulsory discipline,
as in the meekness and authority of the Lamb,
which seldom fails of reaching the witness in their minds,
and more or less to bring them under the government of Truth.
O that many, very many parents now too much at ease,
may be aroused to a due consideration of the trust reposed in them,
and see to the discharge of their duty to the precious souls under their care.
Oh, see to it, parents, I beseech you,
for your own and their precious souls sakes! see to it in season, and unremittingly;
great is the care that is necessary, constant the watch that ought to be maintained.
These remarks arose not wholly from the agreeable prospects I had in and of this family,
but have been on my mind for some time,
under a deep and painful sense of deficiency of care among parents very generally.
However, I rejoice in believing, that notwithstanding the so general neglect,
there are many deeply exercised parents who endeavor
honestly to discharge their duty in the sight of God,
and I have no doubt but they will have a rich reward,
and many of the dear youth will be greatly
benefited thereby--that these may be encouraged,
and their number greatly increased, is the fervent wish and prayer of my soul.

7th-day 18th. We were at the select quarterly meeting at Contentney--next
day at the public meeting there--and were shut up in silence in both,
except a few words in great depression in the select meeting.--
On 2nd-day came on the business of the quarterly meeting;
we were still shut up in silence, until near the close of the business,
when my way unexpectedly opened in a great degree to clear my mind
among them--though I had an opening in the beginning of this sitting,
and stood up in the opening, expecting to have had utterance therein;
but as I carefully attended to the spring and word of life,
I found the brightness of the opening gradually faded,
until all was gone--so I sat down without uttering a word,
after having stood as a gazing stock among them perhaps several minutes.
I trust some real benefit resulted therefrom, to some who were too near always ready,
as well as to my own soul, in keeping me subjectly given up to follow faithfully,
however greatly in the cross, the motions,
openings and shuttings of life.--After this we set out for Eno, it being two days ride,
besides what we rode this afternoon.

Fifth-day 23rd. We had a good open meeting there,
and another on 7th-day at Spring meeting--this was painfully exercising,
under a sense of backsliding in too many; but Truth at last reigned over all,
to the melting of many hearts!--Next day at Cane-Creek--
here again we were filled with mourning and heaviness,
under a sense of unfaithfulness, and consequent dwarfishness; but after long silence,
divine wisdom opened the way! just as I was
thinking it near time to conclude the meeting;
and in a close, short, lively manner,
we were enabled to place the burden of our exercise where it belonged,
and so came away rejoicing in God.
On the four following days we had four blessed meetings at Rocky-River, Nathan Dixon`'s,
Piney-Grove and Holly-Spring.
Truth triumphed in these meetings--its doctrines flowed like oil! the
universality and entire sufficiency of God`'s grace for the salvation of all,
if attended to, was opened and declared with divine authority;
and many minds impressed therewith.
--Oh my God! you have given me to see the wonders of your ways, in degree,
and the strength of your Arm! you have led me through the deeps! have bowed
my soul in the deepest prostration! stripped me and emptied me of all things,
and then marvelously displayed, both your wisdom, your goodness and your power!
In lifting me up again from the dust, you have given me indeed, beauty for ashes,
the oil of joy for mourning, and the garment of praise, for the spirit of heaviness.

--You are my God,
and through your aid I will serve you forever--be with me--go before
me and I will follow you--for in your presence there is life--at your
right hand a river of pleasure--therefore to whom could I wish to go,
seeing I know, to my inexpressible consolation,
that you have the words of eternal life?--You have graciously redeemed my soul,
and delivered me as it were from the den of lions--to you, and to your service,
I therefore once more dedicate the remainder of my days.
Draw me and I will run after you--command me and I will obey.--I fear to offend you,
for you have shown me your purity--I adore you,
for you have wrought wonders for my soul.--I love you,
for you are my life.--Hold me fast, O Lord forever--keep my heart clean,
by the word of your power, and never, O never, I pray you,
allow my foot to slide!--continue to fill me with the joy of your salvation,
since you have so continually shown it unto me-- Take not your Holy Spirit
from me--guide me by the right hand of your power--continue to my soul,
the quickening efficacy of the live coal from your altar; then will I, at your bidding,
teach transgressors your way, and sinners,
through the operation of your baptizing spirit, shall be converted to you--Even so,
O Lord,
hasten you your great work in the earth-- draw thousands by the cords of your love,
and tens of thousands by a clear discovery of, and a living desire after,
a full establishment in the beauty of holiness--till the nations come to serve you,
and the kingdoms of the earth to bow before your throne--till
righteousness cover the earth as waters do the sea--and light
and life reign triumphant over death and darkness,
forever.

Seventh-day, 1st of 8th month, we attended the monthly meeting at Cane-Creek,
and next day the public first-day meeting there,
and their select meeting--all these were times of favor and divine openness.
The five following days we had meetings at Sandy-Creek, Providence, Center, Back-Creek,
and Marlborough--the first was a dull meeting until near the close,
when life broke through all opposition,
so that the meeting ended to solid satisfaction--The next meeting was also dull,
--the three last were open favored times of refreshment to many.
After these meetings we attended, on 7th-day, the 8th of the 8th month,
the select quarterly meeting at Center; and an open instructive season it was,
as was the large public meeting on first-day; Truth`'s doctrines flowed like oil,
and things were opened in divine authority in both meetings,
I trust suitably to the state of each.
Next day the public meeting was very large, still and solemn,
and Truth favored our souls with a baptizing and refreshing time together.
On 3rd-day 11th, we had a good meeting, open,
and powerfully tendering to the minds of the people in general, at the widow Hoover`'s,
a member of our society-- Truth reigned powerfully over
all--blessed be the holy name of the Lord forever.

On fifth-day 13th, we had a meeting at Chatham court-house; but it being court-time,
we could not get the court-house until between three and four o`'clock in the afternoon,
by which time too many of the people appeared to be so affected with strong drink,
as to leave little room in their minds to be seriously
affected with any thing of a religious nature;
so that we had a painful dull time among them--however,
some were attentive and strove to quiet the rest: and way did open,
after a close exercise, for a little communication, to some solid satisfaction;
but our cause for mourning over them seemed much greater than our cause for joy.
1st-day 16th,
we had a dull distressing meeting at a Friend`'s house between Chatham and Peedee;
we were shut up in silence.
Next day the 2nd of the week and 17th of the month, we had a heavenly,
open meeting at Peedee-- blessed be the Lord who helped us!
On 5th-day 20th, we had a very small, yet precious meeting at Camden, South-Carolina,
where no member of our society lives, except one very ancient woman;
though once there was a settled meeting of Friends there--this
was a watering time to a few sincere-hearted,
whom my soul loved; and an awakening, and in some degree convincing time,
to some who were too much hardened in sin,
and unacquainted with that light and power which
is the authority of our meetings and ministry:
this they now felt, so that many were constrained to acknowledge,
and bear testimony thereto, in their conversation with one another.

And I am on this occasion renewedly confirmed in a sentiment I have long been settled in,
that is, that there never was, and never will be but one true religion in the world,
namely,
'`the work of the spirit of God in the souls of mankind;`' that
some of all denominations have something of this true religion,
even though some of these, through the prejudice of education,
may disallow it in profession; and that no man has any real religion,
but what he comes to the knowledge and experience of
through the alone influence of this Holy Spirit of God.
This it is that begins and carries on the work--this it is, that,
by its own divine influence operating in the minds of mankind, reveals Christ in them,
the hope of glory; or so operates from time to time,
on reading the scriptures or other good books; on hearing the gospel preached;
on meditating on the works of creation and providence; on God`'s judgments in the earth;
or his dealings with themselves as individuals; or whatever other occasion,
circumstance or thing, is ever made a mean of conviction or conversion;
the Holy Spirit so operates, I say in all these cases,
as to produce the happy effect--and without the inward operation thereof,
all these other opportunities and things would be utterly in vain, as to salvation,
and never able to produce the least degree of true religion,
or sanctification in the soul.
So that, though there are many opinions, many creeds, professions and denominations,
and some truly religious persons in them all;
yet there is and can be but one true religion;
all true religion is of one kind--all springs from one source.

And blessed and adored forever be the Lord, in order that all men may, if they will,
be benefited experimentally by this one true religion,
'`the manifestation of the spirit is given to every man
to profit withal`'--he that rightly profits thereby,
and continues so to do, will live in the exercise of the one true faith;
will witness the one true christian baptism; will know and obey the one living Lord;
will, by the Holy Ghost, in word and deed, acknowledge and call him Lord;
and so will be saved with an everlasting salvation.
And on the other hand, seeing a measure of the Holy Spirit is given to every man;
seeing the grace of God that brings salvation has appeared unto all men;
seeing the light and life of the holy word, which in the beginning was with God,
and was God, has enlightened every man that comes into the world; and seeing, moreover,
Christ Jesus has tasted death for every man;
how shall we escape if we neglect and reject so great salvation?
how great must be the condemnation of every soul, thus highly favored,
which yet stands out and rejects the strivings of the spirit, the teachings of grace,
the shinings and convictions of this divine light!
Now this light, grace and spirit of God, is all one thing,
under different appellations--it is called spirit, because it is quick,
lively and operative,
and quickens the soul to a sensibility of its state and condition--it is called grace,
because it is the free unmerited gift of God--and is called light,
because it makes manifest--as,
'`whatsoever does make manifest is light,`' says the scriptures.
And as this grace or light is attended to,
it will bring the soul into a state of grace and favor with God.--Well, therefore,
might the apostle, with holy reverence, break forth in these expressions,
'`thanks be unto God for his unspeakable gift.`'
And all who obey the light will be brought out of darkness into God`'s marvelous light;
for though the hearts of fallen men are grossly darkened;
yet the light shines in their dark hearts, and though the darkness comprehend it not,
if it is taken heed to, will shine more and more to the perfect day;
even until the whole body be full of light; but those who rebel against the light,
will grow darker and darker, until they know not the way thereof,
nor understand the paths thereof! and become vain in their imaginations,
and their foolish hearts become wholly darkened! having loved darkness rather than light,
because their deeds were evil.

After the meeting broke up at Camden, before we went away,
we felt such an evident stop in our minds as to pursuing our journey,
and such desires to have another meeting at Camden,
that we found peace in submitting to it;
and in order to procure the company of the busy inhabitants of the place,
we concluded to stay until first-day, and gave notice accordingly.
Then riding to our friend the widow English`'s, we rested there the next day;
and the day following, that is, 7th-day,
had an open precious meeting at a Baptist meeting-house at Swift-Creek,
among Baptists and Methodists, the Lord opening their hearts to receive our testimony.
The doctrines of Truth were livingly declared, most present were reached and tendered,
and our souls relieved--blessed be the name of our God, who was eminently present!

Next day we attended the meeting we had appointed at Camden,
a pretty many of the inhabitants were present,
and though it appears that there are not many religious persons in the town,
yet it was a day of precious visitation to many of their souls--a day to be remembered:
Truth`'s doctrines were largely and with demonstration opened and declared,
making much impression on many minds.
O, the preciousness of Truth! the sufficiency of its aid,
and never-failing victory when abode in!
Lie low, O my soul, forever; trust in the Lord; rely wholly on him;
be nothing without him--all things in him; be faithful to him,
and you shall never be confounded.
He is a strong rock--an impregnable fortress! a sword! a shield! yes,
all things necessary to those who faithfully trust in him --who abide
in the faith and patience of the saints.--He has loved me freely,
wrought wonders for my soul, made bare his Arm for my deliverance,
forgiven mine offenses, and carried me through manifold trials,
conflicts and afflictions; and is now leading me about, instructing me,
reducing me again and again to the loss of all things,
and filling my soul with the fat things,
the rich dainties of his own house! and putting into my
heart and mouth the songs of praise and hallelujahs!
Lord, the desire of my soul is unto you, Oh,
be pleased to exercise your rod and your staff, yes, all your good pleasure in me,
until all within me bows to your righteous scepter,
and every motion of my mind and of my body is in
conformity to your holy will manifested in me.
Therefore go on, O my most merciful God, if it be your holy will,
not letting your eye pity, nor your hand spare,
until you have thoroughly cleansed the floor of my heart-- until the
precious seed be gathered into your garner--until the chaff be burnt
up by the baptismal influence of the Holy Ghost and fire--and finally,
until my soul becomes a fit temple for your holy presence, unrivaled and uninterrupted,
to dwell in.
Make me a pillar in your holy temple, that shall go no more out forever; but,
abiding therein,
be engaged in the depth of humility and profound
reverence to return all the praise to you,
who, with your Son the Lamb, through the eternal Spirit, are worthy of all honor,
adoration and glory, world without end.
Amen.

We lodged again after this meeting, at our said friend the widow English`'s; and next day,
the 24th, took our journey for Charleston, where we arrived the 26th of 8th month,
it being one hundred and twenty miles; and on 6th-day the 28th,
we had a good little meeting at Friends meeting-house with the few Friends in the city,
and a few others that came in, and were tender.
Next day we had a large meeting at the Methodists meeting-house; many Methodists,
some Baptists, and others attending; but it was rather a dull time, and,
not feeling our minds clear,
we concluded to have another meeting there on first-day
afternoon.--In the forenoon on first-day,
we had a blessed open time at Friends meeting-house;
and in the afternoon another large crowded meeting at the Methodist meeting-house,
consisting of a mixed and very unsettled multitude.
We found a pressing engagement to declare the truth among them,
but found them so outward in their minds, and so unstayed,
that we got very little entrance in their minds in general, or relief to our own,
though I believe the Methodists were mostly quiet, and some of them, with a few others,
were reached and tendered.

Second-day 31st, We left the city with heavy hearts,
after a solid opportunity with Friends.
This day and next we rode towards Georgia, about fifty-eight miles;
and finding a little meeting of Friends, though not members,
yet such as were convinced of Truth`'s way and principles;
we stayed their meeting on fourth-day--it was dull at first,
but open and much favored towards and in the conclusion.
Several Methodists and Baptists were present,
and Truth reached and tendered most of their minds.
These friendly people had, at least part of them,
belonged to the Methodists and Baptists;
but their eyes became gradually opened to see
beyond lifeless form and creaturely performances,
as prayers in man`'s own time and will,
etc. and had now gathered into a silent waiting upon the Lord.
May they live near him, love him, and serve him in the beauty of holiness:
then they will not only enjoy great peace in themselves,
but be a blessing to their neighbors.

After meeting we went on for Georgia,
and reached Friends monthly meeting at Wrightsborough in that state, on 7th-day,
5th of 9th month.
It was a painful time; extreme poverty and inward lack bore down our souls.
We found a few words to drop among them,
but scarce found any relief.--On first-day the 6th, we had two favored meetings:
one at Wrightsborough, and the other at Friends new meeting-house,
four or five miles from the first; and next day were again at Wrightsborough,
not being clear before; it was a precious time indeed,
Truth`'s testimony flowed with power, many were greatly reached,
and some who had much opposed our principles, acknowledged to the truth with tears,
and desired us to remember them before the throne of grace--may they be preserved.

Third-day 8th, we had a large meeting at Marmaduke Mendenhall`'s,
among a religious people, Methodists, Baptists, etc.
Truth eminently overshadowed us.
In our first sitting down together, I had very bright openings,
and fulness of light and life;
but the meeting was hurt by the right time not being attended to in standing up,
by me or my companion, or both--my soul was grieved, for the people were prevented,
in degree, enjoying what seemed to be intended for them; yet many minds were affected,
and I trust some good was done.
Fourth-day 9th, we had a large meeting at a Friend`'s house, among Methodists,
Baptists and Friends.
There was strength and utterance given,
and great indeed appeared to be the entrance into the people`'s minds.
After this meeting, next day, we left Georgia, and set out for South-Carolina.
We got to a meeting among Friends at a place called Henderson`'s Settlement,
on fifth-day the 11th, and so on to Mudlick, Bush River, Rocky-spring,
Paget`'s Creek and Cane Creek, having a meeting at each of these places,
and at Bush River two, mostly to a degree of satisfaction,
yet it appeared to be a low time among Friends in these parts;
but dwelling low with the suffering seed,
we were made to reign a little with it at times.

The four following days we rode to Deep Creek in North-Carolina,
about one hundred and forty-three miles.
At this place we had a meeting with Friends and others, on 3rd-day the 22nd, and so on,
having another at Chesnut Creek over the mountain in
the edge of Virginia--from there back to -- Freeman`'s,
(not a Friend) in North-Carolina, having a meeting at his house on 7th-day the 27th,
and were next day at a Friends meeting at Westfield,
called also Tonis Creek--all these meetings were attended by Friends,
Baptists and Methodists, and some of them by some others.
And through patient waiting for the arisings of life and openings of light,
they were all solid profitable meetings; Truth`'s doctrines were largely opened,
many minds reached, and the Lord`'s name exalted over all.
Will-worship, creaturely performances, lifeless prayers at set times,
etc. were much discouraged:
for the Lord laid it upon me to expose the emptiness of these things from place to place,
and to show that they never fail of drying up the springs of life in such,
who once having had the fresh openings thereof in their own souls,
will yet go on in religious performances, without waiting for light and life therein.

After one of these meetings, a Baptist man, somewhat in years,
told me he had tried to keep up family prayers in his house,
but found he could have no satisfaction in it,
unless when he felt a divine influence inclining him thereto,
and that he had now omitted it, except when he found himself thus qualified.
Several others have confessed, that they had often,
in their attempts to pray at their set times, without waiting for divine help,
evidently felt that their words fell to the ground, were of no avail,
and answered no good purpose.--O that all may learn the
necessity of waiting upon God in the silence of all flesh,
and creaturely motions or performances,
that they may witness that renewal of divine strength,
wherein prayer is made with life and acceptance with the Lord.

I had much service in these South Lands among other societies,
particularly Methodists and Baptists, there being a living birth among many of them;
and this living birth, being in its very infancy in many of both these societies,
was near to my life, and I often breathed to the Lord to preserve it alive;
for I saw it to be in imminent danger of being stifled
by a multiplicity of lifeless performances.
But though I was led into service much among other people, as before-mentioned,
yet I generally, in the meetings of Friends,
had some clear openings into the state of things among the brethren:
for I was kept very low in my mind,
and dared not meddle with things not opened in the light of life.
I was afraid to judge after the sight of the eye,
or reprove after the hearing of the ear; my dependance was on the Lord alone;
and in that dependent state, I often felt as empty of any thing divine, any sight,
sense or knowledge of things,
as if I had been totally blind and insensible--
and indeed who is so blind as the Lord`'s servant,
and so deaf as the messenger whom he sends?
And it is necessary it should be so,
in order that his message to the people through them
may be wholly in the fresh openings of divine life,
without any mixture of man`'s fallen wisdom.
This is a great mystery to the world and all its boasted wisdom,
and will remain so forever, though clearly opened unto babes and sucklings in Christ.
And as my mind abode in this low state, in the loss of all things,
in the subjection of my own creaturely will, wisdom and workings;
I received many fresh openings,
and therein was enabled to bring forth things new and old, to the instruction, and,
I hope, lasting benefit of the brethren and many others from place to place.
All glory and praise be ascribed to him, without whom my poor soul is nothing,
knows nothing, and can do nothing, in things divine.
O that all flesh may be abased, and lie low before him forever,
that his own eternal power may be exalted over all in them.

After this meeting at Westfield,
we found a pressure in spirit to have one next day among some religious Baptists,
about six miles off at a Baptist man`'s house; it was a precious heavenly meeting,
wherein Truth opened many things in the life and demonstration.
And some confessed, they had never known before,
but that John`'s dispensation of water-baptism was part of the gospel dispensation,
and to stand to the end of time; but they seemed now to be much shaken;
for it was opened that John`'s elementary dispensation was only a forerunning one,
to prepare the way of the Lord.
After this meeting we still found a pressing engagement to
have another meeting at Friends meeting-house at Westfield,
which was held accordingly the next day, to great satisfaction: many Baptists and others,
as well as many Friends, attended-- Truth reigned over all,
and the doctrines thereof dropped as the rain,
to the tendering and refreshing many seeking
souls--blessed be the Lord for all his favors.
We next had meetings at Blues-Creek, and Muddy-Creek,
and on first and second days the 4th and 5th of the 10th month, were at Deep-River,
their large monthly meeting being held there on
second-day--all these were blessed watering seasons;
the monthly meeting abundantly so, to the bowing my soul in awfulness and praise.

On 3rd-day we had an open, refreshing meeting among the Nicholites, so called.
I had a lively evidence that some among them were humbly endeavoring to serve the Lord;
but at the same time I saw clearly that many of
them rested too much in their outside plainness;
and valuing themselves upon that,
had stopped short of a more living acquaintance with the well-spring of eternal life;
and this is a snare wherein I fear some of our society are taken,
and detained from greater experience in the real life of religion,
without which all outward things are unavailing, as to the salvation of the soul.
I labored among this people, in the openings of life,
and hope according to their condition--may it tend to
their settlement on the right foundation!-- Then,
proceeding on our journey, we had meetings at Friends meeting-houses at Springfield,
Bulrun, New-Garden, Lower Reedy-Fork, and Upper Reedy-Fork, all favored meetings,
some of them highly so.

On 4th-day the 14th, we had a meeting at the house of our friend Samuel Tomlinson,
where very few Friends live near, among Baptists, Methodists, some Friends, etc.
We evidently felt that some of them had pitched
in battle array against us in their minds;
and for a time the Lord permitted them to shut up the kingdom of heaven,
not entering themselves, nor allowing those that gladly would have entered.
At length a small degree of life arose, and I told them the battle was the Lord`'s,
and if he allowed them to shut up the kingdom, the loss would be their own;
but that it was likely those formerly,
whose unbelief prevented our Savior`'s doing many mighty works in certain places,
might be ready to vaunt over him, and to think he could not make his way among them;
and yet I thought their victory, if such they esteemed it, was in no wise glorious;
but greatly to their own loss,
or the prevention of much good that they might otherwise have received.
I then acknowledged to them freely,
that we had nothing at our own command to offer for their good;
nor any weapons of our own to oppose their warlike
preparations with-- told them I had little thought,
when in the pure constrainings of gospel love and good will,
I gave up to have a meeting with them,
that they would have come together prepared for war; but that I was assured it was so,
for I could feel the inward state and opposition of some of their minds,
as plain as I could see their bodies with my outward eyes.-- Moreover I informed them,
that if the Lord engaged me in it, I was not afraid or ashamed to fight,
even upon a retreat,
if he did not make way for an advance--that I was not at all afraid of my life,
how many Goliaths soever might defy the armies of the living God;
for my life I had given up to his disposal, to be laid down in his cause, if he pleased,
in any part of the globe.--I came not from my own land,
and all my near and dear connections in life, to do my own will, but his who sent me;
and while I stand faithful in his holy will and counsel,
in the openings and leadings of his divine light and life, I fear no evil,
danger or difficulty; nor all the art and malice of men or devils;
though I fully know that of myself I can do nothing.
However I told them, for their own sakes,
in order that they might have the full benefit of the meeting,
I desired them to lay aside their warlike weapons,
that inward opposition wherein they stood against the inward life of all true religion,
and the doctrines of the everlasting gospel;
and as they knew themselves guilty of an inward opposition to us and our message,
it began to work conviction in them: they wondered how I knew it;
but seeing I did know it, and was enabled so plainly to tell them the inward state,
and thoughts of their own hearts, it won upon them, drew their attention,
removed their prejudices,
and softened their hearts towards us and our
testimony--and when I found they had given up,
and dropped their warlike weapons and intentions, I improved the opportunity,
as Truth opened the way, and told them,
I perceived they began to incline towards a capitulation,
and willingness to sign articles of peace--this they also knew
was true of the inward alteration of their minds;
and so it greatly tended still further to gain their love and attention,
until at length (though the work, or rather warfare,
was very hard for some time) we had a heavenly
baptizing time together--Truth reigned over all,
and therein our souls triumphed over all opposition,
in the strength and power of an endless life! wherein several
doctrines of the gospel were livingly opened and enlarged upon,
in demonstration of the spirit and divine authority! yes,
that was felt and acknowledged to be so,
by many whose hearts were greatly tendered and refreshed,
after all the opposition they had at first felt against us.
Thus the Lord wrought for us, and taught our hands to war,
and our fingers to fight--Glory be to his great name
forever! for hitherto he has marvelously helped us;
and we know that without him we must have turned
our backs in this and many other days of battle.

Next day we had a heavenly open meeting at a Baptist meeting-house on Abbit`'s Creek,
about ten miles from the last meeting--many of their members,
and one of their teachers urgingly desiring us to have a meeting with them there,
they being much reached at the other meeting.
We had had thoughts of having a meeting there before this invitation, and,
the way now looking very open, we embraced it, and had one accordingly.
And as soon as I sat down in the meeting,
I felt as evidently as I ever felt any thing with my outward fingers,
that they were now come without their weapons,
in a state of mind directly reverse to what they or some of
them felt in the forepart of the meeting yesterday;
their hearts were open,
and our way was also soon opened into a living enlargement in the doctrines of Truth,
I trust to our and their mutual satisfaction and consolation of soul,
though their outward performances and lifeless
devotions were largely and livingly testified against.

Our next meeting was on the day following at Randolph Court-house,
among people of various professions; and, magnified forever be the name of the Lord,
our leader and director,
he was graciously pleased to break in upon us in a wonderful manner;
light shined superior to the shining of the sun in the outward firmament,
that divine light, the same that enlightens every man that comes into the world:
but in the wicked it often shines as in a dark place,
and the darkness comprehends it not--many whose hearts have become darkened, reject,
despise and trample it under foot; but in those who obey it, love it, walk in it,
and bring their deeds to it, it will shine more and more to the perfect day,
as the wise man says the path of the just man does,
declaring this path of the just to be a shining light: indeed it is so,
for Christ within, the just man`'s light and hope of glory, is also his path,
his only true and living way, as said Christ himself, I am the way, and the truth,
and the life; and surely the just man`'s way is his path: seeing Christ then,
the inward divine light of men, is the just man`'s path or way,
well may it be declared to be a shining light:
and experience has abundantly confirmed it to the souls of all
that have truly loved and faithfully walked in this light,
that it really does shine brighter and brighter: and in all that continue so walking,
it will more and more,
even to the perfect day--they will not only witness the day to dawn,
and the day star to arise in their hearts,
but the increasing clearness and brightness of the light will be, as Isaiah expresses it,
the light of the moon shall be as the light of the sun,
and the light of the sun shall be seven fold, as the light of seven days.

Well, in the clear shinings of this holy light,
for truly it was as a morning without clouds,
the state of the people were so opened to us in this meeting, and through us to them,
the light within their own souls confirming our outward testimony,
that scarce an individual appeared insensible of
the heavenly visitation we were favored with:
indeed most were deeply affected, greatly tendered,
and much refreshed as with a shower of celestial rain--
it seemed to me in a degree like the day of Pentecost,
the effusion of the Holy Ghost was so eminently glorious among
us!--and I believe near or quite all present,
said in their hearts, and several with their mouths in substance after this meeting,
this is the everlasting gospel of Christ; and I said in my own soul, and still say,
it was of the Lord`'s doing, and marvelous in mine eyes! holy and reverend is his name,
and that forevermore--may my soul ever acknowledge his
wonders and the riches of his love,
lying low in humiliation before him.

On 7th and 1st days, the 17th and 18th,
we were favored with the Master`'s helping hand
at the monthly and first-day meetings at Center;
in both which light and life triumphed over
death and darkness.--On 3rd-day we had a painful,
trying meeting near a water called Heworry, at a Dutch Friend`'s house,
(Michael Fout) among many Dutch people, and others.
We labored in the little ability afforded, to some degree of satisfaction.
The two next days, we attended Friends meetings as they were held in course,
at Springfield and Bulrun.
Next day we had a discouraging meeting among many other professors,
near the Upper Reedy-Fork.
I saw and felt clearly, that some of them came prepared to bid defiance;
however we labored a little,
though under great depression--for though they were
many of them high in profession of faith in Christ,
too many of them appeared to be unbelievers,
and in the state of the Scribes and Pharisees, in the inward ground of things--and such,
in all ages, are the greatest opposers and even hinderers of good,
of any people whatever; yet I believe several present were humble-hearted christians,
who thought little of themselves,
and were hungering after better food than their teachers are feeding them with:
some of these I hope got at least a little crumb of heavenly bread at this
meeting--may the Lord refresh their souls with the waters of life,
and sustain them.

Next day, being 7th of the week, and 24th of 10th month,
began the select yearly meeting at Center, in North-Carolina, for Friends of that state,
South-Carolina and Georgia-- it was a trying season,
and Friends seemed sensible it was a very low time.
I was quite sealed up in silence, as were both my companion and myself next day,
at the public meeting for worship.
On second-day the business of society came on; it continued by adjournment four days,
and though the forepart was heavy and trying,
yet the latter part was a time of eminent overshadowing of the holy presence;
many weighty subjects were considered in this yearly meeting;
and finally resulted with much unanimity, love and solemnity.
I was much bowed down, until the last day,
under a sense of the lack of due dependance on the Lord in many present;
but near and at the close of the meeting, the helper of Israel opened a way,
and helped me to be thoroughly relieved, and the song that is ever new,
was put into my heart and mouth, in a very comforting manner.
Large numbers, I believe, will at times, while they live,
bless the name of the Lord for that day`'s favor.
The shout of a King was heard in Zion, to the rejoicing of the tabernacles of Jacob.
Bless your God, O Israel, forever, and serve him with faithfulness and reverence,
O daughter of Jerusalem, for who indeed is like him?
He brings down as into the very dust,
and he raises up to the heights of salvation--He
makes the dumb to declare of his goodness;
the inhabitant of the rock to sing of his power! glory be to his name
forever--my soul will praise him in the heights of Zion!

On 7th-day 31st, we attended New-Garden monthly meeting,
and had therein a degree of satisfaction.
Next day we attended their first-day meeting there, being the 1st of the 11th month,
in solid silence, as to us; and, feeling clear of Carolina,
on the day following we rode to Virginia; and on 4th-day the 4th at night,
we got among Friends at Goose-Creek; where next day we had a meeting,
and the day following had another at the upper meeting-house on Goose-Creek,
which was silent.
We next had meetings at Hills-Creek, Seneca-Creek, and South-River;
in all which we were helped through to our comfort,
and hope to some profit.-- On 4th-day the 11th,
we had a blessed comforting meeting at Henry Christian`'s, a Methodist, and a few others,
in Amhurst county, Virginia--light and life prevailed,
to the tendering and watering many souls.
On 6th-day, we had a little meeting at Francis Walthall`'s,
a man that for some years appeared to have been convinced of our principles,
as also his wife: this was in Buckingham county.
On first-day the 15th, we had a meeting at Amelia, to a degree of satisfaction,
and that afternoon my dear companion James Ladd and I parted, in much gospel sympathy,
and endearment, he going home.
On 4th-day, I had a discouraging meeting at Camp-Creek,
and another next day at Douglass meeting,
(so called) in the first I got but little relief;
and in the last could not open my mouth in the ministry.

On the first-day following, the 22nd of 11th month.
I was at meeting at Smith`'s Creek, in suffering silence.
About this time Satan seemed almost let loose upon me, to buffet me with doubts,
even in things wherein I had been well established and assured.
And persuaded I am,
I have no words adequate to the full and clear description of the buffetings,
horror and distress, that seized and bore down my drooping soul;
but I have since clearly seen, that the Lord`'s determination was,
that if I would still be his, I should lay down my own life,
that of my own will entirely, and in all things,
and take him and his will for my only good, in and through all.
And as my own will was once more crucified and slain,
my life laid down upon the cross-- all within me bowed--
On this wise then my soul addressed my God:
'`Lord, I know you are all goodness;
I have drank of the rivers of pleasure at your right hand,
which is all of your mere bounty and grace;
I surrender my all once more to you without reserve.
Here I am--do with me whatever you please--blessed and
adored be your name forever--I yield to your will--not mine,
but yours be done.
Amen.`'

After this full surrender of my will and my all, light sprang in my soul;
darkness fled before it; Satan`'s head was bruised; God did truly bruise Satan under me;
I saw his power was limited; and that the Lord God Omnipotent still reigned over all.
Life and immortality was again, as it were,
brought to light out of the depth of obscurity,
and established over all in meridian brightness and assurance in my soul.
Great enlargement followed this sore conflict, and my consolation was full,
and unspeakably glorious-- blessed forever be the Lord my God,
and wonderful leader! in the heights my soul will praise him,
and for the depths of prostration will I magnify his name,
who makes all things work together for good to those who truly love him--Love him,
O my soul, forever, and submit your all to his holy care and keeping,
through every trying time.

After this most trying conflict, I found my way opened again,
and had meetings at Crooked-Run, Center, Mount-Pleasant, Bear-Garden, Back-Creek,
Hopewell, Middle-Creek, Tuskarorah and Bull-skin, all open good meetings,
and most of them eminently so, even to my own admiration!
Truth`'s doctrines were largely opened with divine life and authority;
many who were much unacquainted with true religion were much reached;
and such as were hungering and thirsting after something more
substantial than they had yet feelingly known,
were greatly refreshed.
My soul bowed in awfulness before that God, who,
through the deepest probations and discouragements,
safely brought me on in the right way; landed me on firm ground;
and even made my most fiery trials and extreme conflicts
promotive of almost inexpressible enlargement and consolation.

Oh! he well knows what he is about,
in allowing his chosen followers to be thus closely
tried--indeed this is the very way they become chosen;
for he ever chooses them in the furnace of affliction:
here he refines them as gold seven times tried in the fire: thus they bear his holy law:
thus they are made able to dwell with that which, to everything sinful,
is as a devouring fire and everlasting burnings, and not be hurt;
the fire shall not kindle on them to devour;
the smell of it shall not be on their garments;
but everything in them that is chaffy shall be burnt up, in,
and by this unquenchable fire;
so the weighty substantial wheat comes to be gathered into the garner.
Oh! you traveler Zion-ward, whenever the Lord leads you in this line,
think not that none have walked the way before you;
but remember it is the high-way to glory;
the only trodden path to blessedness--remember others, before you were brought forth,
have deeply experienced it, have tasted the wormwood and the gall;
and been ready to think it impossible for them ever to come forth into the light again,
or to rejoice in God, the rock and horn of their salvation.
But be patient, be faithful to death; yes, in and through this inward death,
and you shall receive a crown of life: for it is an eternal truth,
that though many are the afflictions of the righteous, yet,
assuredly the Lord delivers them out of them all.

Next I had a meeting the 4th of the 12th month,
in the Presbyterian meeting-house at Winchester:
a glorious good meeting it was --I was ready to think near as much so, as our low state,
while clothed with clay, is capable of.
Several important doctrines of the gospel were largely opened,
having strength and utterance given--every mind seemed hushed
into a degree of awfulness and reverence! all glory and praise
be ascribed to him who is our only sufficiency;
for with gratitude, and prostration of soul before him, it may be truly said,
'`hitherto has the Lord helped us!'`--On 7th-day I was helped to my own and others joy,
at Friends monthly meeting at Crooked-Run: and also next day at the meeting at Culpepper.
Indeed the arm of the Lord was marvelously made bare in our favor, from place to place,
throughout the foregoing favored meetings: and from there on to Southland, South-Fork,
Goose-Creek and Leesburg.
At Southland I parted with my dear friend Catlet Jones,
who had been very acceptably with me most of the time
since I parted with my beloved friend James Ladd;
but now he returned to his family.
I was at this place last spring, as I went southward, and though I was shut up there, then,
yet I felt such an engagement for the prosperity of that little meeting and neighborhood,
that I felt most easy, now on my return, to visit them again;
having been drawn in spirit to look towards them, at times,
ever since I was there before.
We had now a heavenly watering time together, praised be the Lord,
whose power was eminently over all.
I believe I have never known a more constant fulness of God`'s love, life,
and qualifying presence; nor a more continued cheerfulness in and out of meetings,
for so long a time, than (blessed be the Lord) I have now been favored with,
since my extreme tribulation and distress at Smith`'s Creek, and about that time.
Oh, the heights and depths;
may neither the one nor the other ever separate my soul from the love
of God!--I well know the propriety and need of our Savior`'s caution,
pray you that your flight be not in the winter; neither on the sabbath-day.

Great care is necessary,
in both these states--perhaps our Lord mentioned the winter first,
as it is the trials and distress of that painful dispensation, which prepares for,
and if patiently endured, terminates in the comfortable rejoicings of the sabbath-day.
To abound, we must be abased: if we will reign with Christ, we must suffer with him: but,
Oh the danger of letting in discouragements in the winter season,
when all seems cold and uncomfortable within; even sometimes benumbing,
and almost deadly frost.
Here you exercised traveler Zion-ward,
if you are not very watchful and careful to
abide in the faith and patience of the saints,
you will be very likely to take your flight, from walking in the light,
and firm abiding on the everlasting rock and foundation;
by letting in and giving way to doubts, disputings, distrust, murmurings and despair;
and so repine at the dispensations of Divine Providence,
who is proving you for your good.
Here many have took their flight in the winter,
and let go their hold of what they had received,
and so have lost their crown! for the terms are, '`be faithful unto death,
and I will give you a crown of life.`'
If you abide steadfast through the wintry dispensation,
the Lord will bring you to the opening spring, to the summer, and the sabbath-day;
here you will praise him on the banks of deliverance;
here you will be made to shout and sing! for, lo, the winter is past;
the rain is over and gone; the flowers appear on the earth;
the time of the singing of birds is come;
and the voice of the turtle is heard in our land.

But now, in the midst of your rejoicing, have a care; stand fast;
see you take not your flight on the sabbath-day.
Danger awaits you on every side; you are a frail mortal, and your destruction,
if it comes upon you, will be of yourself; but your help can be only in and of the Lord;
therefore look unto him, for '`he that trusts in his own heart, is a fool.`'
Let him that thinks he stands, even though his soul is filled with good,
and overflows with songs of joy,
take heed lest he fall--even now this care is eminently necessary--this is a
moment wherein the watch is peculiarly needful --hence the precious caution
in regard to these two seasons of most pressing danger-- hence,
also, he preached the watch, and that repeatedly, to his disciples, yes to all;
'`what I say unto you, I say unto all, watch.`'
He knew all needed it; not only the dejected and depressed soul, but even,
and especially, the joyful heart--the mind of him whom joy overflows.
My soul well knows the mystery of these things by repeated experience; but I have found,
that, in proportion as all pride of every kind is done away,
or hid from man (which is God`'s work) and the creature
fully humbled and reduced to the loss of all things,
the Lord is pleased more abundantly to fill us with divine good;
and to continue its blessed replenishings unto us! for through this
abasement we are enabled to bear this fulness without being puffed up,
or thinking great things of ourselves.
Man is exceedingly inclined to independence,
and a language on this wise--my own arm has
brought salvation --is not this great Babylon,
which I, great I, have builded, for mine own and kingdom`'s honor? etc.--Yes.
O, you who thus builds, be assured, whenever you begin to think much of yourself,
and that you of yourself have done something that is good, you are a Babylonish idolater;
you are erecting a Babel.
This is great Babylon indeed, which you, a poor worm of the dust, are rearing up;
and all this must be brought down, before you come to live by, say, or can say in truth,
'`I live: yet not I, but Christ lives in me,`'--and '`by the grace of God I am what I am.`'
It is truly a great attainment to be nothing but what grace makes us;
yet this is the case, in regard to the things of religion,
with all who '`do nothing of themselves: but have rested from their own works,
as God did from his,`'--here '`God is all in all.`'--O, seek it--lay hold of it,
and secure it to your soul, by dying daily;
dying unto all that can or would act of itself, make haste, or be always ready;
for this can never do any thing better, whatever it boasts,
than build for you and others a Babel of confusion.-- Therefore, let him that has an ear,
hear what the spirit says unto the churches,
in order to gather all that will follow the Lamb,
into the living gospel worship in spirit and in truth, within the inward temple.

On 7th-day the 12th of 12th month, I attended the select quarterly meeting at Fair-fax;
next day the public meeting; and,
on second-day one for public worship and the discipline of the church; and, on third-day,
a large public meeting for the youth and others.
I was shut up throughout, except some close communications in the select meeting,
and in that for public worship on first-day.
My soul was deeply distressed under a sense that
some were neglecting an inward feeling after God,
and were foolishly looking out for words.--Oh! how this wounds the living,
and adds to the bonds of those who have no other to look to
but the Lord alone! scarce any thing tends more powerfully to
shut up the springs of life.--4th-day 16th,
attended the mid-week meeting at the same place;
and next day had a good meeting at the Gap; and on 6th and 7th days,
seeing no way to go forward, I rested, wrote, and waited further directions.

On 1st-day the 20th, I attended the meeting again at Fairfax;
our friend Peter Yarnall also attended it, on a religious visit.
I sat long in suffering silence; but at length, standing up,
got forward with much difficulty; such mountains of obstruction lying in my way,
arising from the states of some present, as I believed,
that I seemed not enabled to get along far before I found it best to sit down,
rather abruptly; and sitting quiet and still in mind,
although I doubt not but many present thought me a fool,
yet I felt resigned to endure their ridicule.--But after sitting a good while,
and finding I could not leave the place easy,
and the meeting having continued already to an unusual length, I stood up again,
intending to desire another meeting next day; but as I was not hasty to utter any thing,
but waited to feel and see my way in every word,
I went on from one sentence to another for some time,
still expecting to request another meeting, but I could not find liberty so to do;
instead thereof finding my mind gradually and unexpectedly opened and enlarged,
until Truth reigned over all!
I attained at length a great degree of relief to my mind--the
meeting ended abundantly more to my satisfaction,
and some others, than I had expected--blessed be the Helper of Israel,
who still as of old, leads the blind in paths they have not known

On 4th-day the 25th, I had an open good meeting at Bush-Creek in Maryland,
having crossed the great river Patowmack on 2nd-day, being, as I hope, clear of Virginia.
On 5th-day 26th, had a very good open meeting at Pipe-Creek in Maryland;
and on seventh-day at Monallen in Pennsylvania, and so on to Huntingdon, Warrington,
Newbury and York, having meetings at each of these places to good satisfaction.
At York I had three, the two last laborious; but I felt in good degree clear of the town.
And on 6th-day the 1st of 1st month 1790, I went to a place called Wright`'s Ferry,
on the river Susquehanna,
where I had a pretty good meeting at the widow Wright`'s house--and the three next days,
three blessed meetings at Lancaster, Lampeter and Sadsbury; then on 3rd-day the 5th,
another such at East Nottingham in Maryland,--Next day
another such at West Nottingham in Maryland--and the
day following another at Little-Britain in Pennsylvania;
and on 6th-day the 8th, a blessed and very open one at Deer-Creek,
over Susquehanna in Maryland.--On first-day the 10th, through deep suffering,
I was considerably opened and enlarged in the fore and afternoon meetings at Baltimore.
I stayed a few days in this place, and then rode to Little Falls,
attending meeting there on 5th-day the 14th; and so on to Sassafras,
(on the eastern shore of Maryland) Head of Chester, George-Town, Cecil,
Chester meeting and Chester-Town; then to Churchill, Queen-Ann`'s and Tuckahoe;
having open good meetings at all these places, to the humiliation of my mind,
and bowing me into thankfulness and prostration before the Lord,
who alone gives ability for every religious service.
--Next day, being 3rd of the week, and 26th of the month,
I attended the quarterly meeting of ministers and elders at Third-Haven;
the two next days was held the quarterly meeting for church discipline;
on the day following the monthly meeting there.--The
two first of these four days were painfully exercising;
but through patience in tribulation, and not presuming to put forth a hand,
or go forward, until the Shepherd of Israel went before me,
leading me on in the openings of light and life, I at length obtained deliverance,
triumphed over all opposition,
and coming forth from under that weight of death and darkness I had felt,
found renewed ability the two last days thoroughly to relieve my mind among them;
which was not only to the reproof of the lukewarm and disobedient,
but abundantly to the watering and refreshment of those who
were truly hungering and thirsting after righteousness.
I was made sensible that there was present a little remnant who truly loved the Lord,
and whose meat and drink it was to do his will; and blessed be his holy name forever,
they, with my own soul were eminently filled.

Next day I had a meeting at the Bay-side; it was silent and dull for a long time;
after which my mouth was opened in the pure gospel spring,
and the meeting continued some considerable length of time longer,
in a very open and relieving manner;
the nature of gospel worship and of all real gospel ministry,
being largely opened to the people--may it fasten as a nail in a sure place.
Oh! how I have mourned before the Lord,
under a sense of the death and formality which reigns
in Christendom! for lack of waiting for divine help,
and through pushing forward in man`'s time and ability,
which brings forth but a form of godliness and devotion,
without the life and power of it.

On 1st-day the 31st, I had a very large and highly favored meeting at Third-Haven,
among the inhabitants of the town,
many of whom had not been at any of the preceding meetings there.
Gospel light shined eminently among us,
and I hope and believe instruction was sealed on some minds present,
in a manner not easily to be erased.--The two next days
we had meetings at Choptank and Marshy-Creek,
both precious seasons after long waiting.--The two days following these,
we were at meeting with the Nicholites (so called) at two of their meeting-houses; and,
after long and painful waiting, I labored among them,
I hope to the benefit of some of their souls.

After this we went into Delaware state,
and had meetings at our friend Baptis Lay`'s at Cold Spring, Lewis-Town, Three-Runs,
Mother-kill, Frederico and Mother-kill again.
We were helped through to profit and relief in them all;
though mostly in a way much to the subjection of our own creaturely wills.
Oh! what need there is to lie low, and rise only as the pure life arises,
lest we be found offering strange fire,
or lifting up a tool on the Lord`'s altar.--Contentment in a lowly state,
and moving on gently in the real necessity, is highly acceptable to him,
without whom we can do nothing.
Here we acknowledge his might, his right to command even faithfulness in the little,
which fails not, if we rightly obey, to make us, in his own time, rulers over much;
and sometimes to our own great admiration.--Indeed it was so in several of these
meetings--that at Lewis-Town and that at Frederico being times of high favor:
the people were mostly not of our society,
no meeting of Friends being usually held at either place.
Also the meetings at Mother-kill were, in the end, seasons of enlargement,
though through difficulty, hard labor, and close inward attention; especially the last,
wherein the Lord eminently evinced to us, beyond all room for doubt, that when he opens,
none can shut--for he did remarkably both shut and open,
'` and even before he opened the way in full clearness,
he brought us under a necessity of laboring in the little, wherein dear Mary Berry,
a skillful laborer, was made victorious; but we both found, that,
move ever so carefully and gently, as in the real necessity,
it was not for a long season the Lord`'s time or will to open fully or give us to reign:
the seed was under suffering, and we must suffer with it,
and did very deeply and painfully,
and labored in great bowedness and abasement.--But blessed be the Lord God of Israel,
in his own time ever best, he marvelously arose--opened the way with clearness:
then all that was opposed proved unable to shut it.

We then had meetings at Dover and Little Creek, both highly favored;
at the close of that at Little Creek, I had to part with my said friend Mary Berry,
Richard Bartlett, his wife a worthy friend, and John Dickenson; a tender parting it was,
not easily to be forgotten--may the Lord hold them, and my own soul,
in his holy hand forever! --On 2nd-day the 14th, we were at Duck-Creek;
3rd-day at Appoquinamink; 4th, at White-Clay Creek;
5th at Wilmington--all good open meetings--the two first very relieving --in the
two last relief was obtained through close attention and creaturely subjection.
I then went to Philadelphia.

On first-day the 20th, I attended in the forenoon the meeting at Pine-Street;
afternoon at the Bank, and in the evening at Market-Street.
On second-day the select morning meeting; 3rd-day monthly meeting at the Bank;
4th-day the monthly meeting at Pine-Street; 5th-day preparative meeting at Market-Street,
where also was a marriage;
and on 6th-day the monthly meeting of Friends belonging to Market-Street meeting.
My mind was deeply baptized into sympathy with the suffering seed in all
these meetings--but as I was favored and enabled to keep in the life,
and attentive to the openings thereof, I got relief from day to day,
in a line of close plain dealing, which was to me very laborious;
to some present very alarming; and to others greatly comforting and encouraging.

And now, finding my mind greatly relieved from a heavy weight of exercise,
I had to behold the great danger of taking my
flight on a day of rest and pleasantness.--Oh,
how careful ought we to be in all our words and actions,
lest feeling ease and liberty in our minds,
we transgress the holy limits and boundaries of Truth; offend some of the little ones;
and wound our own souls!
Oh, you only preserver of men, preserve me, I pray you, in a humble watchful state,
with mine eye single to your holy light, both in heights and depths, henceforth forever.
Amen.

On 7th-day the 27th, I left the city, and rode to Bibury,
to the house of that deeply experienced minister of the gospel James Thornton,
whom I much loved and honored--his health was ill,
but I felt him to be alive in the everlasting truth;
I felt near and dear unity with him in the inward covenant of divine life,
where I saw and felt him hid with Christ in God;
grown up to the stature of a man in Christ,
and into the heavenly authority and establishment, as a pillar in the temple of God,
that shall go no more out.-- I was much edified by his conversation,
and judicious unaffected remarks.--Oh! that my latter end may be like his!
Next day I attended the meeting at said Bibury,
and being livingly opened into the state of things among them,
and helped to discharge my mind in Truth`'s holy authority,
I felt great relief and satisfaction--And the day following,
having spent a little more time with my dear friend James Thornton,
and visited his son Joseph, a choice young man, but very low,
and likely before long to finish his course here,
I parted with them in fulness of gospel endearment, and rode to Wrightstown,
where next day I had an open precious time at their monthly meeting.
Then went home with my dear friend John Simpson, who,
having been on a religious visit in New-England since I left home,
had kindly visited my dear wife and family, to his own,
and I doubt not to their satisfaction and comfort.

Next day the 4th of the week and 3rd of the month,
I went to see my kind friend Thomas Smith and his family, of Buckingham, where,
and at whose house, my dear former companion Joseph Mitchel was sick and died.
We were glad to see each other; and Thomas kindly rode with me to Kingwood,
in West- New-Jersey, over the river Delaware, where,
on fifth-day I had a good refreshing meeting--and
another on sixth-day at our friend Joseph Moore`'s,
to a degree of satisfaction.
Then I returned to Kingwood,
parting with Thomas at Joseph Moore`'s. I stayed at Kingwood (not being
clear) until after the meeting on first-day the 7th of the month;
an open, large and enlarged meeting it was, to my great relief, and I trust,
to the lasting benefit of many others.
I then had meetings on third-day at Hardwick,
and fifth-day at Mendham--in both Truth wrought relief and enlargement.
And feeling clear of these parts, I went to New York, where, on first-day the 14th,
my mind and mouth were livingly opened,
which had never been the case in that city before,
silence having always been my lot when there before: but now my tongue was loosed,
though in a close and somewhat alarming manner, yet greatly to my own peace,
both fore and afternoon-- after which was held, by appointment, an evening meeting;
it was large, and dear Isaac Everett, of Pennsylvania,
now on his return from a religious visit into New-England,
was livingly opened and favored in this evening
meeting.--I also had a few words in this meeting,
and then felt clear of the city.
But dear Isaac appointed another meeting next day--I stayed and
attended it--he was helped to declare deep truths in Truth`'s
authority--and the desire of my heart was and is,
that they may be duly regarded.

On 3rd-day I left the city,
and was next day at monthly meeting at Westbury on Long-Island;
5th-day at monthly meeting at Jericho; 6th-day at meeting at Martinacock;
7th-day at Cow-Neck; first-day at Westbury again;
and on 2nd-day at Bethphage--on the whole being
greatly relieved in spirit after these meetings,
wherein I had known much subjection of the creaturely will,
I found my mind quite clear and easy; and so,
taking a hearty farewell of my dear friends on the Island, I sat out for New-England,
and got home to my dear wife and family on 7th-day the 27th of said third
month.--And being thankful in heart in finding them in usual health,
and having to believe that I had finished the service required of me at this time,
and had been directed and enabled to return as I went forth,
in the Lord`'s own time and will,
I bowed low in inward awfulness and prostration before him,
once more giving up and dedicating my life and my all to his service,
in full faith and assurance, that, if I rely wholly on him,
and remain to be given up to be just where and what he pleases, go at his command,
and come at his command, and at his command stand still, he will not fail or forsake me;
but will bear up, support and preserve, through all tossings, tempests and dangers,
both inward and outward; and that though the fig-tree should not blossom,
nor fruit be in the vine; though the labor of the olive should fail,
the flocks be cut off from the fold, and no herd be in the stall;
though all earthly consolation should fail; yet still I may,
and if steadfastly patient and faithful, certainly shall, amidst all conflicts,
dangers and toils, at times and seasons, rejoice in the Lord,
and joy in the God of my salvation; and finally sing his praise forever,
in that habitation, the house not made with hands, eternal in the heavens.

My dear wife and children, as also my friends,
appeared glad of my safe return to them again; and on my own part,
I was truly glad once more to be favored with their endeared company
and conversation--may we all so abide in the holy root of life,
and so under the influence and direction of the inward light,
as that we may be mutual helps and encouragements to each other,
in the arduous path and pilgrimage of a truly christian life,
through the remaining course of time allotted us in this vale of tears,
this scene of vicissitudes, tribulations and joys.

I was out on this exercising journey a year and about fifteen days, and travelled,
by computation, about five thousand three hundred miles.
And though my trials and inward exercises have often been more
deeply proving than I have words to convey to any who have not
travelled a path of like painful experience;
yet I have ever found, that as faith and patience have been abode in,
and sufferings quietly submitted to, the result has been,
a coming forth with songs of praise and hallelujahs,
into the victory and dominion of Truth,
and the glorious liberty of the sons of God.--And I think I may say,
that through divine help, without which I know I can do nothing,
I have been preserved through some of the deepest probations,
and tribulations of my life, in more constant resignation to the divine will,
than ever was for a like space of time and under equal extremity of trial,
and varied anxiety, my attainment and experience before!--Blessed forever, over all,
be the great name of the Lord, and to him be all the praise.
