== Chapter IX.

[.chapter-synopsis]
* An account of his wife`'s last sickness and death
* some of her dying sayings,
* and his peculiar exercises and trials at that time, and especially on that occasion

Having thus performed the service required of me in the southern states,
I passed near three years at and about home; and had, as usual,
many close trials and besetments to pass through from time to time,
until in the 7th month 1791,
it pleased the Most High to prove me in a very near and heart-exercising manner,
in the removal by death of my dearly beloved wife.
This trial came at a time when I was otherways deeply plunged into many probations,
both inwardly and outwardly.--My state indeed to me bore a
lively resemblance to that of Job of old-- wave on wave,
and sorrow upon sorrow, seemed almost ready to swallow me up.
But the Lord had an end in all my sorrows.--And had he not been with me in the deeps,
and borne up my head above the waves.
I had been swallowed up suddenly, and drowned in the mighty waters of affliction!

I thought before my wife`'s sickness,
it was very doubtful whether I should ever get safely through my many besetments:
but alas! in the midst of these trials,
it pleased the Lord to take from me the dear partner of joys,
and sympathizer in my sorrows.--She was confined to her bed-chamber two weeks,
during great part of which time she was in exquisite bodily pain,
which she bore with becoming patience.
One day she lay still and quiet, as if she was in a slumber;
but on hearing it remarked at night, that it had been a favorable day to her as to pain,
she said, it had been a day of much pain to her, though she had not complained,
for she felt no liberty to complain;
but found it her place to bear all that was laid upon her patiently.
I kept an account of several lively expressions which dropped from her in her sickness,
and which abundantly evinced her resignation of mind and acquiescence
with the divine will in regard to her approaching dissolution,
which she seemed clearly sensible of, and several times spoke of;
but what I wrote got mislaid, and I have not since found it;
I much regret the loss of it,
and especially because her advice to our dear children might have been very useful.

She also gave very suitable advice to her brothers and sisters,
and expressed her thankfulness to her parents for their watchful and
even restraining care exercised towards her in her younger years,
when she used to think a little more liberty would have been no harm;
but now she saw she was then too ignorant of the dangerous tendency of those liberties,
and rejoiced that they did not give way to her inclinations.--She pressed it upon
her brothers and sisters to remember their parents in their old age--told them,
they had done much for them when they were unable to help
themselves--that now they were growing old and feeble,
and to be kind to them and not forget them.--She
also desired them not to forget their brother,
(meaning myself) saying, he will have many afflictions to pass through, with much care.
--And likewise forget not these little children, they will miss their mother,
and need the care of their uncles and aunts.
And speaking to one of her sisters, said, you have done a great deal for them,
and must not think of doing less when their mother is gone.

She charged it upon our children to be obedient to their father, loving to one another,
and good to their aged grandfather.--Two Friends coming in, who had both been widowers,
after several other weighty expressions,
she desired them not to forget the afflicted--told them they knew
something of such trials as her dear husband would be surrounded with,
and that she hoped they would not be unmindful of him.--I can scarcely write this
account without mourning the loss of that I wrote from day to day in her sickness.

One day, after expressing her entire willingness to be taken hence at this time,
she said to me,
but I have several times thought I should have been willing to
have taken the care of these dear children a little longer if
it had been the divine will--and I have thought,
if it might have been so ordered,
I could have given up everything that might have been called for,
even if it had been to give you up to travel in truth`'s service,
let the time be longer or shorter:
I have always given you up with a good degree of cheerfulness,
and have been supported in your absence beyond my expectation;
and yet I have often thought, since your return from your last journey,
that I did not know that I could ever give you up again, or bear up in your absence:
but in this sickness I have felt as though I could give up all,
if I might be spared a little longer to help along in the care of the
children--it has seemed to me that I should give you up my dear husband,
to go wherever the Lord might lead you--it has seemed so,
but may be it would not be so with me if I should be tried with it;
and perhaps I shall be taken away that you may be set more
fully at liberty to attend to the Lord`'s requirings in
whatever part of the world he may see meet to employ you.

Then she expressed her deep sense of my kindness to her in her sickness,
and her heartfelt sympathy with me in my trials, past, present and to come,
and her living desires for my support and preservation through all,
to the end of my race, in such a moving manner,
that the fresh sense thereof melts my heart when I recollect the time
and substance of the conversation--and I trust I shall not soon,
if ever, forget the endearment and solemnity attending it.

On my going into the room very shortly before the scene was closed with her here,
she expressed great gladness at seeing me,
and that she had been desiring me to come-- I believe she was sensible her
end was just approaching.--She expressed great thankfulness to her dear
young friend A. A. for the great care she had taken of her through the night.
All that was alive in me was moved at this time, for I saw she was just going.
Oh! how expressively she looked upon me! how endearing
her expressions! but she was soon past conversation,
and resigned her soul up to him who gave it,
on the morning of the 5th of the 7th month 1791, dying of a putrid disorder,
and was buried the 6th in Friends burying ground in Providence.

Through divine help my mind was pretty well stayed,
though deeply affected and tenderly moved through her sickness, death and burial.
And through all, and after all, I have this consolation,
that her soul was centered in divine love,
and sweetened with a fore-taste of heavenly enjoyment.
And though painful to me the separation, and trying in many of my lonely moments;
yet in God I have confidence and hope of consolation,
and I dare not do any other than bless his holy name in every trial;
and if he but preserves my soul alive in him, and faithful in his covenant;
all else I yield to his all-wise disposal.

Many a mournful day and anxious night did I pass through, in this my lonesome condition,
and in a deep-felt sense of the buffetings of Satan within,
and certain outward probations, in wisdom allowed to beset me.
I saw clearly I must be redeemed from many things wherein some are taking satisfaction,
if I would live wholly unto God.
I saw also that he permitted me to be many ways afflicted,
in order that I might be so redeemed.
Sometimes it seemed as if I could scarce live through
my inward baptisms and outward besetments;
yet still pressed forward, until, in a time of deep distress,
I found relief and consolation,
in remembering that some of the most distressing mornings of my life
have been followed by some of the most happy and joyful evenings;
and some of the most melancholy evenings,
by mornings of most substantial gladness--therefore drew the following conclusion:
I will strive to moderate my joy in the moment of prosperity--
and in the hour of adversity I will endeavor to hope;
for tho`' sorrow may remain for the night, yet joy comes in the morning.
