== Chapter X.

[.chapter-synopsis]
* Extracts from his diary, and an account of his visit into Connecticut.

I Feel that I stand in need of a renewal of my strength,
in regard to religious life and progress, and am afresh confirmed,
a christian`'s life is (as he minds his proper business) a continual warfare!--Oh my soul,
watch and pray continually--and think not to get
forward rightly by an intermitting watch;
a watch sometimes pretty well maintained; and anon, almost or quite wholly neglected;
for be assured the enemy will make an inroad upon you,
if you thus neglect the watch.--O holy Father, and Fountain of light, life and strength,
I pray you enable me to watch and pray without ceasing.

16th day.
Afflicted and not comforted; yet dare not let go my hold,
nor look out to visibles for enjoyment.
My state seemed that of almost total abstinence.
23rd, Humbled and bowed in grateful prostration and reverence,
in contemplating on the wonderful goodness of God to mankind through all ages,
especially in opening and revealing, by his Holy Spirit,
the deep things of his heavenly kingdom to poor frail man.

27th,
a day of great deliverance and enlargement in gospel authority
in the ministry and doctrine of Christ--and some faithful
labors for the good of the brethren in a more private way.
28th, sat under my own vine and fig-tree, where none could make afraid.
29th, I find yet need of dying daily--have in good degree submitted to it this day.
Lord, let not your hand spare, nor your eye pity,
until you bring forth judgment unto victory in me.

Fifth of 8th month, I feel that my God has greatly weaned, and is weaning me;
but I want to be able to say, through and with my Savior, '`I have overcome the world.`'
I greatly desire fully and unreservedly to die to everything that is not of the Father,
whether it be of the world, the flesh or the devil--in short,
to know an overcoming of all evil, and all evil motions and desires,
so as that they may die at the root.
And, indeed, this is the only true and effectual overcoming;
for now also the ax is laid unto the root of the tree,
not the branches only to lop and crop them, but to cut up the tree at the very root.
And talk what men will of imputation--none are those
overcomers to whom the promise is made and will be performed,
that they shall '`eat of the hidden manna`'--have a right to the tree of life--
receive a white stone and a new name--enter in through the gates into the city,
and be made pillars in the temple of God, that shall go no more out,
but those who maintain the warfare against sin, until Satan is wholly bruised under them,
and the law of the spirit of life in Christ Jesus set
them free from the law of sin and death.

Oh! blessed holy God, and Father of all our sure mercies, lead on, I pray you,
as you have begun, my exercised soul,
through all the remaining steps and stages of sanctification,
until true judgment break forth unto victory over all sin in me.

6th. Blessed be the name of the Lord!-- the work
goes on--righteousness is laid to the line,
and judgment to the plumb-line, in my soul.
Lord, spare not, nor stay your hand-- cleanse thoroughly the floor of my heart,
and burn up all the chaff in me with your baptizing unquenchable fire.
19th, I feel much reconciled to the divine will,
and therein to all my sufferings and afflictions, inward and outward;
and do not wish them removed until they have done all,
for which the Lord leads me into them.
And further, it is my desire,
that I may never seek or take satisfaction in any thing this world affords,
otherwise than according to God`'s most holy will; but that I may receive every blessing,
every favor, comfort and consolation, as also every trial, affliction,
cross and disappointment,
as coming from his hand--and so learn truly to rejoice evermore,
and in everything give thanks.

So let it be, O Lord my God, forever--and may I, in every pursuit,
attend to your counsel and direction--may I see in your light,
that it is necessary and expedient that I be engaged in this or that,
either spiritual or temporal vocation--may I be ever
ready and willing to pursue every necessary engagement,
exercise and labor,
of either kind--may a firm reliance on your providential care and blessing,
prevent all improper haste or anxiety--may I pursue, from day to day,
the work and proper business of the day, with suitable diligence,
moderation and composure, unanxious for the event, or for what may be tomorrow,
or some future time;
but firmly believing that all things will and do work together for
the good of every soul that truly loves you--and that the only right
way for me to promote the prosperity of my future days,
is, to act well my part today, in your counsel;
leaving the disposal of events to your providential wisdom and
goodness.--Thus will day unto day utter speech,
and night unto night show knowledge--One day`'s work, being rightly done,
will tend towards the right opening to, and performing aright,
the work and service of the succeeding day--and here will be
found no occasion to anticipate the difficulties of the morrow,
for sufficient unto the day is the evil thereof.

On the one hand, there will be no time to be idle--nor on the other,
to be over anxious or troubled.
--If sparrows fall not to the ground without God`'s providence--surely he will never
leave nor forsake the soul that trusts in him.--The life indeed is more than meat,
and the body than raiment.

21st. Highly favored and greatly relieved was my exercised mind,
in the meeting at Uxbridge.
Truth`'s testimony flowed like oil,
and important doctrines were therein opened to the people.
28th. This morning, I trust, my mind is in subjection to the divine will,
though heavily laden with inward exercise.-- Oh, gracious God, deliver me from all evil,
and make me wholly yours!

In our forenoon meeting my soul praised God in silent adoration,
on the banks of heart-felt deliverance.
Dear Mary Ridgeway and Jane Watson, from Ireland, attended,
and were livingly opened in the word of the Lord,
and spake with life and precision to several states present.
I think words never dropped from human lips that ever sank deeper into my heart,
than a few that dear Mary uttered towards the close of
her testimony-speaking to the Lord`'s tried servants,
mentioned, that where Christ is, there they must be;
and that she had felt her mind very nearly united in deep
sympathy with some very closely tried souls present;
she added, And it is with me just to revive in the remembrance of these,
what Christ said to his dear disciples,
You are they which have continued with me in my temptations,
and I appoint unto you a kingdom.

Oh, there is deep meaning in it;
my soul felt it in the everlasting covenant of divine light and life,
and well understood the meaning of it.-- Verily,
unless we not only know what it is to be with him in
his temptations now and then a little while,
but to continue with him to the end without forsaking him,
we cannot reign with him in his kingdom.
But ah! says my soul,
the sore and almost inexpressible tribulations and conflicts that are endured by
such for a season as do truly and faithfully continue with him in his temptations!

Formalists may dream, conceive, and talk about them; but none know the depth thereof,
but such as do, through all pain, peril and probation, continue with him.
Bow low, Oh my soul, and bless his name forever,
that he has thus far enabled you to be with him, not only in his reign,
but again and again in poverty, sufferings and death.
You know, you deeply, painfully, and joyfully know, that this leads to,
and must precede your fellowship with him in glory.
But sing, O you heavens, and shout for joy, you redeemed souls on earth;
as the pilgrimage, though painful, is rightly continued,
and he is continued with through all; the consolation that follows,
when the angels minister to him and us, as fellow-heirs of God, yes,
joint-heirs of glory; every sigh and every sorrow, is far more than compensated to us:
therefore, Oh you tribulated follower of Christ, in the regeneration, hold on your way,
faint not, hold fast that you have received; let no man take your crown;
be faithful unto death, and he will give you a crown of life.

Afternoon, my soul bowed low before the Lord in reverent, thankful adoration,
and blessed his holy name.--And may his name be blessed and praised forever by me,
and all the living.--Oh, the living,
the living-- they alone can praise him--the dead may sing in the dead letter;
but cannot praise nor celebrate the name of the Lord Almighty.
This has been a day of divine favor,
after a scene of almost unutterable anxiety and
bitterness of soul for much of many days and weeks past:
the exercises attending me through which, the Lord my God alone is fully acquainted with.
But enough it is, that he knows them thoroughly,
and that with him in secret every sigh is numbered,
and every tear bottled up in remembrance; and will certainly,
as his will is steadily abode in, be changed into wine, new, in his heavenly kingdom.
Amen, Amen--your will, O God, be done forever!

9th month 1st. The Lord, the God of my life,
was graciously pleased to fill my soul with the overflowing of divine love,
and in-shinings of divine light, which continued with me until late in the night,
and wherein I have been much instructed.--And, O Lord, my God,
I humbly crave of you to enable me, rightly, to settle, or to have and know,
through your help, rightly settled in my mind, every necessary rule,
limit and regulation of life; and that you would steadily hold my hand and guide my feet,
in ways that will please you, until every such rule and limitation,
receive the sanction in my heart of a divine law, that is not to be broken again forever;
yes,
until a confirmed and habitual observance of them shall
have conformed my whole life thereunto;
and therein to your divine will, and heavenly image.
Amen!

10th month 4th. Jesus Christ is my only hope of glory--my only consolation in every woe.
O, I long to be wholly his at all times --I long to be able to say continually and truly,
'`my soul is even as a weaned child.`'
It is delightful to me to feel myself like a child--that is,
weaned from what I most delighted in--yes,
from much if any remaining delight in any thing
but the love of God shed abroad in my soul.

10th month 6th.--Still thankful for preservation, and begging to be preserved;
much broken off from all creaturely dependance, and all human, all earthly consolation;
caring very little where I am, or may be; what I am, or may be about; or what does,
or may happen to me; so that in and through all I may be preserved from all sin.
I scarce have any wish about my life, whether I may live long, or be soon released;
whether I may have little or much of this world; little or much toil of body or mind;
little or much of the favors and friendship,
or the frowns and reproaches of man--so that through all I may
dwell steadfastly given up to the will of my God.

10th month 7th. O, you ever watchful and unslumbering Shepherd of Israel,
I beg and beseech you, on the bended knees of my prostrated soul,
that you would arise and save; and permit me not to crave your aid in vain.
O make, I pray you, my feelings, on the approach of every temptation, quick and lively,
in watchfulness and resistance against all sin; and raise, in the inmost of my soul,
an unabated and unremitting abhorrence of all evil;
and even of all that tends to lead the mind into it, or weaken its fortitude,
or abate its perseverance in holy wrestling warfare and watchfulness against it--For,
Oh my God and my all; I cannot be willing to continue in sin;
I cannot consent to let you go, or cease my wrestling with you, until you bless me,
and preserve my soul from all pollution and defilement.
Oh hasten, I pray you, my deliverance from all evil, and bruise Satan under my feet;
for yours is the power, the kingdom and glory forever.
Amen.

10th month 8th. I renewed covenant with God, in the name of our Lord Jesus Christ,
through his help, to be given up, and wholly devoted to his will and disposal: therefore,
in awful prostration, humility,
abasement and total renunciation of my own ability without you,
I cast my care wholly upon you; and look up to you and your holy habitation for aid.
I am sure I can do nothing without you --I am fully persuaded,
through you I can do all things required of me.
O holy Father, you know that I love you--that I love you above all things,
and that I would rather lay down my life, than live to sin against you.
O keep my soul alive and permit it not to have cause again to
deplore a renewed deviation from the way of life and salvation;
but as soon as Satan attempts to ensnare, give me, I pray you,
to behold him--to rise up in your invincible life and power against him,
and therein to tread him under my feet.

10th month 18th. This day I am forty years old.
I have gone through many deep probations--have made many
considerable sacrifices for the sake of peace of mind--and
have also at times come short of that strictness of life,
watch and devotion, which I have believed Truth required of me.
O Lord my God and Savior; your holy aid, I still do crave.
I know I have not yet fully and abidingly attained thereto.
My faith in the possibility and necessity of attaining it,
you have unshakenly established.
O then, I pray you, enable me to '`go on to perfection.`'
I have vowed to serve you forever, through your help,
and I wish ever to keep my covenant-- And in keeping my covenant with you,
there will be '`no condemnation;`' but will be a state of such deep and
constant dwelling '`in Christ Jesus,`' as excludes '`walking after the flesh;`'
and preserves the soul in a steadfast walking in and after the spirit.

10th month 20th. I opened my concern in our preparative meeting to make a
religious visit to some of the people in the state of Connecticut,
and 26th, laid the same before our monthly meeting.

28th of 11th month.
Riding on the road, my mind was livingly opened; and I beheld, in the visions of God,
large fields of labor allotted me in his service.
A language ran livingly through my soul,
and the whole man seemed almost swallowed up in the flowings
of life which accompanied the glorious prospect!
The language was on this wise:-- You are called and appointed,
and through many and deep tribulations I have separated you a prophet to the nations.
You have very little more ever to do in the business and affairs of this life.
Gather your mind from all cumbering things,
and stand singly and wholly devoted to my work, service and appointment.
Regard not the world; you must be about your heavenly Father`'s business;
you must attend to my directions, and submit therein to your proper allotment.
My will and purpose requires and loudly calls, and has called,
for greater dedication of heart and singleness of
devotion to my work and service in the glorious gospel.
Take no thought for the morrow: do to day what you find to do, in my light,
and in the liberty and allotment of my Holy Spirit.
Be faithful unto death, and I will assuredly give you a crown of life;
I will hold you in my holy hand forever;
I will provide for and take care of your motherless and as it were fatherless
children in your absence.--But if you decline my service and appointment,
I can, and assuredly will, blast all your undertakings.
You may think to do something for your children; but you shall find,
to your humiliation and disappointment, your labors shall be vain and fruitless;
you shall but toil in the night and attain nothing; blasting and mildew shall attend you;
your children shall not be availingly assisted by all your such like endeavors.
Your comfort in them shall be little or nothing, and above all this,
your soul shall suffer loss; temptation shall prevail against you;
Satan shall be let loose to buffet you, and shall be permitted to prevail;
your life shall be a life of bitterness and desolation;
neither the heaven nor the earth shall afford you enjoyment --
you shall drag out a miserable life in anxiety,
and wish you had never been.
But if in full and unreserved reliance on my all-sufficiency,
you give up your life and your all to my disposal,
I will never leave you nor forsake you;
no lack of any good thing shall you ever have cause to complain of.
I am Alpha and Omega--I am all in all--take me as such for your only portion,
and seek no other inheritance.
In blessing I will forever bless you--and evermore in all things will I sustain you,
and that through all time and eternity--your soul and all pertaining to you,
shall be perfectly safe in my care and disposal --The wind and the sea shall,
to your awful admiration, obey me--You shall see marvelous things in distant lands,
and wonders in remote regions--You shall view the heavings and
rollings of the ocean--the sea shall toss and roar about you,
and foam and rage tremendously--Amazement shall seize the mariners,
the sailors hearts shall tremble.
But in the midst of all this amazement, your soul shall know its anchor,
and in undoubting reliance on my Omnipotence,
your heart shall take fast hold on me--Calmness and assurance shall preside in your soul;
confidence and tranquillity shall gird you--My over-ruling,
all-controlling government shall be visibly set forth before you--you
shall lean in safety upon me--and inwardly you shall magnify my holy
name--and in fulness of faith shall sing of my goodness--saying,

The Lord on high is mightier than the noise of many waters.
Your heart shall leap within you--your soul shall shout
for gladness--Then shall the language of your spirit,
in awful adoration,
on this wise thankfully arise within you--The sea saw it and
fled--Jordan was driven back--the mountains skipped like rams,
and the little hills like lambs.
What ailed you, O you sea, that you fled; you Jordan,
that you were driven back-- you mountains that you skipped like rams,
and you little hills like lambs?

The foregoing livingly ran through my soul on the road this day.
I came home and penned it immediately, and whether it be ever fulfilled or not,
time will evince.
However such is my confidence in that evidence of life accompanying the opening,
that I have ventured here to record it, this 28th day of 11th month 1791.
12th month 28th, Much depressed in our monthly meeting,
tho`' Friends gave me a good certificate to travel into Connecticut,
to visit the seed there.

1st month 12th 1792.
Opened in the spring of life, in our quarterly meeting for worship --proceeded a little,
but was suddenly and unexpectedly shut up, and sat down immediately,
after which my soul rejoiced that my will was in subjection,
and that I was sensible I could do nothing of myself.
13th, The quarterly meeting for business gave me, and my dear friend David Buffum,
concurring certificates, in order to our religious visit to the people of Connecticut.
15th, Low in heart.
Oh, my God, you lead me in the valley--I accept it as your will, and as in your wisdom,
for my good.
17th, My state is depression.
Satan roars like a lion.
Lord, my heart is melted in me into tenderness: mine eyes are affected while I write,
under a sense of my utter insufficiency to stand in my own strength.
How long.
O you most Holy, will it be before you conform my whole man to your own image or likeness?
you know I groan within myself, waiting for the full adoption!

O that all within me were like you, holy as you are holy,
and at all times joined to you in the heavenly oneness.
Go on, I pray you, conquering all that opposes your reign in me,
until every thought be brought into captivity to the obedience of Christ.
Amen.

21st, I wrote the following letter:

[.embedded-content-document.letter]
--

[.salutation]
My dear friend,

I now feel in a good degree easy about my dear little motherless children.
I much desired way might be made, and could not be satisfied until it was made,
for them to be placed where I could be pretty easy,
if even I should be soon called from this probationary state.
I have now given them up to God, and their and my friends.

May the Lord Almighty be their God,
and bring them early into saving acquaintance with himself.
May those who have them, have them as their own,
and bring them along in the fear of God--whether I remain in the body or go
hence--whether I continue to live in that which has made my soul alive,
or depart from it, the dear children have souls immortal to be saved or lost.
And whatever becomes of me, my soul at present, in tenderness and prostration,
bows before the throne of grace on their account, and craves Almighty aid,
and the watchful guardianship of their friends for them.
I may again have them under my immediate care,
and I never may--God only knows--and to him I commit myself and them--and rest your

[.signed-section-signature]
J+++.+++ S.

--

31st of 1st month.
I took a solemn leave of the family (that is,
my father-in-law Daniel Anthony`'s) living in my house,
and in whose family I left my own father, and my two youngest children:
and being joined by my friend David Buffum,
(Amos Collins and Benedict Arnold having given up to
bear us company) we were on 5th day of the 2nd month.
at the new meeting-house in Gloucester, on our way towards Connecticut,
and had meetings as follows:--7th, at Killingley, had a small meeting at -- Dean`'s; 9th,
at David Brayton`'s in Pomfret; 12th, attended Friends meeting at Hopkinton; 14th,
had one by appointment at Amos Collins`'s,
my way having been hitherto much closed up as to gospel ministry,
my companion D. B. having a little to offer at times, I trust, to good acceptance; 16th,
we had a good open meeting at Stonington Point, and another in the evening; 17th,
went to New-London, and 18th,
had a small meeting there in the congregational meeting-house; 19th,
had a meeting among the Baptists at New-London Great-Neck,
found but little relief in these last meetings, though hope they were of some use; 20th,
had an evening meeting at Lime, in a school-house--The people were unsettled,
and appeared much unacquainted with spiritual worship--we labored a little among them;
and, 21st, crossed Connecticut river, by boat, and not without some danger in the ice,
and went to Saybrook; 22nd, had a meeting here in the meeting-house--the priest attended,
and a considerable number of his hearers,
and neither he nor his hearers appeared to be much acquainted with
our manner of waiting upon God in a silent travail of soul,
and feeling after him.
We labored among them according to the ability received.
After meeting he inclined to have some conversation, and we, being willing,
conversed with him on various religious subjects.
He was civil; and we parted friendly and respectfully.

23rd. We rode through Killingsworth to Guilford, where, 24th,
we had a soul-solacing meeting; among those who attended,
were many religiously exercised souls,
whose countenances declared they had been with Jesus.
25th, had another good meeting in a school-house at Wallingford.
After meeting several of the people came to our lodgings,
and we had considerable conversation with them.
A physician contended earnestly for the final salvation of all men.
We told him none could be disciples of Christ,
but such as took up their daily cross and followed him, in the denial of self;
that he wept over some, who, though he would have gathered them, they would not; that,
though many should come from the east, west, north and south, and sit down with Abraham,
Isaac and Jacob, in the kingdom of God;
yet many who were outwardly the children of the kingdom would be cast out;
that those who die in their sins, where Christ is gone, they can never come;
that some were never to have forgiveness in this world, nor in that which is to come:
that some would be punished with everlasting destruction from the presence of the Lord,
and from the glory of his power; that these must go away into everlasting punishment;
but the righteous into life eternal.
And finally, parting very friendly, he said he loved us, and wished us well;
and the company seemed very friendly; so, taking a hearty farewell of each other,
we proceeded on our way.

26th. Rode to Waterbury.
27th, had a meeting there; the people were much unsettled,
and too many of them were light;
a testimony to the principle of light and life was borne among them by my companion;
and I reproved them for their uncivil behavior,
and testified the impossibility of preaching the gospel in man`'s time.
28th, we rode to our friend Elijah Steel`'s, in Cornwall.-- 29th,
attended Friends meeting at Goshen, at the house of our friend Charles Richards.
First of 3rd month, had an appointed meeting at Goshen,
at our friend Charles Richards aforesaid; it was a precious open meeting;
after which we rode to Canaan, and, 2nd, to Hudson, in New York state.
4th, attended Friends meeting there.
7th-day, the Creek preparative meeting--it was exercising in the forepart;
but Truth reigned over all in the end.
8th,
attended Nine-Partners preparative meeting.--The searching
power of Truth set things in close order before them.
9th, took leave of several Friends, and rode towards home; where, on the 14th day,
I reached, and found all pretty well.
In this journey I rode, by the account I kept,
488 miles--a painful exercising journey it has been;
but a good degree of patience was afforded us.-- 28th, contented in a low state,
in our monthly meeting.
I am yet weak,--Lord help, help my soul, and give it stability.

31st,
I opened in our select meeting a concern that
had been about 14 years ripening in my mind,
to pay a religious visit to Friends in Europe.
My heart had of late been pressingly full of it, as a vessel needing vent.
Friends left me at liberty to move the matter in our monthly meeting,
when I might feel the way open for it.
They were feelingly dipped into a sense of the travail of my exercised soul,
and Truth was prevalent.
4th month 11th,
I laid before the meeting for sufferings a treatise I had written on baptism.
25th, opened my concern to make a visit to Europe in our monthly meeting.
6th month 6th, attended the first sitting of our yearly meeting,
which continued until the 12th. It was a very comfortable yearly meeting: much unity,
concord and love prevailed throughout.
6th month.
27th, in our monthly meeting, I asked for,
and obtained a certificate to pay a small debt,
by a visit within Salem quarterly meeting, and, 30th,
set out on said visit into that quarter, and rode as far as Boston, and,
first day of the week, and 1st of 7th month,
attended meeting there--silent--the meeting small;
yet I hoped Truth`'s testimony was not quite lost among them.
May a revival take place, and Truth yet prosper there.
Rode to Lynn, and 2nd of the month, had a meeting there: the way not very open;
but I labored in weakness.
There is a number of panting souls in that place.
3rd, had a laborious meeting at Salem; found some relief.
4th, had a pretty open meeting at Newbury.
5th and 6th. was at Almsbury and Seabrook; painfully exercised in both.
7th, 8th and 10th, was at Dover, Berwick and Wyndham;
had a good meeting at the last place, and returned to Falmouth.
11th. attended the meeting there; it was a close, searching, laborious time.
12th, had a good open rejoicing meeting at Durham and rode from there to Bath.
13th, had a very trying meeting there; my mind was deeply sensible,
though an entire stranger, that there was either a wolf or wolves among us,
in sheep`'s clothing; the which gave me much and long painful, inward labor,
and also lengthy vocal exercise.
The testimony of the word of life I felt as a
flame against antichrist in the temple of God,
against likenesses in religion; forms without substance; words without life and power:
at length my spirit was clear and easy, and after meeting I was informed a man was there,
who was a preacher among a people at some distance from Bath,
and that he was not a religious, or even a moral man.
Thanks be unto God, who gave us the victory this day.

15th, was at Vasselborough: and 16th at Fairfield,
where I had a good open relieving time,
having much to declare of the impossibility of salvation in sin;
and I apprehend there was a state present to whom it was applicable.--17th,
rode to Green, and 18th to Falmouth.--19th, had a meeting at Portland in Falmouth,
a place that used to be called Casco-Bay, in a congregational meeting-house,
a good open meeting, and in the afternoon at Friends meeting-place.--20th,
rode to Berwick; and, 21st, attended monthly meeting there; and, 22nd,
their first-day meeting.--23rd, returned to Falmouth, and, 25th,
attended monthly meeting there, was favored in opening divine truths.--26th,
rode to Durham; 27th, favored in the monthly meeting there.--29th,
opened in Truth`'s doctrines at Falmouth, being their first-day meeting.

1st of 8th month, had a good meeting at Rochester,
among Friends and others--blessed be the name of the Lord.--2nd, had a meeting at Lee,
where, among Friends and others,
my mind was much relieved in a close searching testimony.--3rd, was at Epping, and 4th,
at Newtown; had laborious service in each, but relief in the conclusion.--5th,
being first of the week, I attended the fore and afternoon meetings at Salem;
and after a close searching testimony, left the town relieved in mind,
and rode to Lynn--and 6th of the month rode home--having been
out about five weeks and a half in this journey,
and rode about seven hundred and fifty miles; passed through many deep,
trying and exercising seasons; and blessed the name of the Lord for his holy help, who,
in the day of battle, gave me the victory.--9th day of the 8th month,
attended our quarterly meeting; it was a favored time.
Dear John and Benjamin Reeve, from Jersey, attended this meeting.

Having passed the time since my return from the Eastern Quarter at and about home,
in the attendance of meetings and revision of my journal, some other writings,
and preparing for my European journey,
having now obtained certificates from our
monthly and quarterly meetings for that purpose,
placed my children to satisfaction, and settled my outward affairs,
am this 26th day of the 11th month, about ready and expect this day to leave home.--Lord,
you have held my hand, and covered my head in many battles--be with me, I pray you,
through all; and keep me from evil.
Be with my dear motherless children; visit them, I pray you, by your Holy Spirit;
lead them in the way of refinement and self-denial; and, finally,
bring them unto glory.--Visit and revisit, bless and preserve, O Lord my God,
I humbly pray you, all my near relations and friends;
make bare your Arm for poor New-England; and if it be your holy will,
make yourself more livingly known to many within her borders:
and hasten your great work over the face of the earth,
that nation may cease warring with nation,
and righteousness cover the earth as water does the sea.
