== Chapter XI.

[.chapter-synopsis]
* Account of his voyage to Europe

ON the 26th day of the 11th month, 1792, I took a solemn leave of my dear father,
father and mother-in-law, my two youngest children, whom I left in their care,
and of my brothers and sisters-in-law,
and accompanied by my kind friends Thomas Arnold and Smith Brown, went to Boston.
27th, the ship not ready to sail, I made some preparations for the voyage.
29th, my two said friends returning home,
I attended the meeting in Boston which was small;
I had however a few words of invitation for them.
30th, I went to Lynn, and 1st of the 12th month, visited several families there; and 2nd,
attended their large meeting in silence; 3rd, returned to Boston; 4th,
wrote letters home; and 5th, went on board the ship Mercury of 240 tons,
bound for Dunkirk, Benjamin Glover, of Nantucket, master.
We sailed about noon: some time in the afternoon we lost sight of Boston.
In the night all hands were called up,
and the ship put about in order to return to the harbor, she leaking,
and the leak rapidly increasing, that is,
from the rate of one hundred strokes of the pump an hour to six hundred.
The captain, mates and crew, were alarmed; but she soon leaked less on this tack,
and they put about again.--6th, the ship still leaking,
the captain and several men searched on the outside for the leak, but sound none;
after which, the leak moderating, cheerfulness returned in the faces of the company.

7th, the leak greatly increased, to near one thousand strokes an hour.
Sadness again resumed its empire over the crew.
The captain knew not what to do; at length he put about again,
and sailed homeward a while.
The weather was pretty rugged during the time of this increasing leak.
The leak continuing,
the captain ordered a hole to be cut through the second deck to go in and search for it,
which was done, and the leak soon found,
which was an open auger-hole of about an inch and a half, at the ship`'s stem,
so high up as not to leak constantly, which being stopped,
the number of strokes were soon reduced to twenty-five an hour.
Oh! what a change this wrought in the countenances of the poor sailors.
They soon seemed as if they had forgot all their sorrows.
They put ship about, and now seemed as if they were going to sea in earnest.
The captain`'s looks proclaimed the relief of his heart,
though he was moderate through all.
My trust was only in God my hope, refuge and defense.
I appealed to him who knew all hearts,
that he knew my motives in this voyage were none other
than that I might be found obedient to his holy call,
and faithful in his service;
and if it was now his will to allow my body to descend into a watery grave,
'`your will be done.`'
was the honest language of my heart.
I could not wish myself on shore, nor on board another vessel;
for I had felt quite easy in taking passage in this, and remained so.
I believed the winds and waves obeyed him,
and that his providential care is over all his creatures.
I felt safe in his hand,
and reposed myself as in the hollow of it--blessed be his name forever.

8th, all cheerful on board.
The motion of the ship has kept me a little sea-sick.--9th,
cloudy and rainy.--I sat a while in solemn silence, waiting upon the Lord my God;
but though my mind was somewhat stayed, it was inwardly as outwardly, a cloudy time,
indeed a time of deep proving to me.--10th, At evening the wind arose,
and roared tremendously; it held all night: the men tied up the sails, lashed the helm,
and let the ship drift in the wind and waves.--11th,
the gale still continued all the last night, and all this day and night with violence.
The captain said this morning he had not, for eight years past, known so terrible a time,
for so long continuance, though that was but about the middle of it:
and indeed it was considerably more violent the night following than at all before.
It stormed through the whole; but this night the storm and tempest of wind was dreadful.
The ship was bound on a whaling voyage from Dunkirk,
and for that purpose had boats on board.
One of these was considerably dashed to pieces this night:
three or four yards or spars were lost: several fowls died,
and the only live sheep we had on board came near dying, even under deck.
I felt resigned through all; and, though poor in spirit, I never wished myself elsewhere,
or in any wise repented my voyage.
I saw God`'s wonders in the deep,
and it would almost seem at times as if the briny waves might prevail against us--
though I cannot say there was a moment wherein I really lost my confidence.

I had steadily, for many months,
firmly expected and believed I should see wonders on the mighty waters.
My God had sealed it on my soul,
that the loud roar of winds and the dread rolling of
the waves should awfully attend my passage,
and prove my hold on heaven.
And, therefore, when the time of trial came, I said in my heart, it is the Lord,
let him fulfill his purposes: let him do what he will with me:
nought besides his holy will can be good for me;
and why should I wish even the most disagreeable parts of it averted,
mitigated or even shortened?
I believed I had had his holy promise who cannot lie,
that I should live through these dreadful tossings on the bosom of the ocean,
and once more set my foot on firm ground; yes, bless his holy name,
in wonders yet to come on shore.
I cannot say I was not nearly proved in regard to his divine superintendency,
nor that I did not almost doubt the certainty of
his in-spoken word of promise to my soul,
though I well remembered the clearness of the prospect,
and the holy warmth and energy that did livingly attend the same, months before.
And though the evidence of divine things was very low in my mind,
yet I could not cast away my confidence, being still persuaded, that,
if I had ever known the holy word at all, I had had it in the present instance.
Here my foot fixed, and my all I still surrendered up to his disposal,
who is God over all forever.

12th. About noon the wind and storm was so far abated
that the captain had the ship under sail again,
though still the roar of elements remained.
13th, It is still cloudy and rainy.
The sun has been seen but little since we left Boston;
and I think it has rained or snowed, more or less, every day and night but one.
14th, Very little sunshine--some rain.
15th, Rainy all day, at night it cleared up,
and gave us to hope for settled and comfortable weather; but 16th, it stormed again,
and snowed plentifully; but at night it cleared off.
17th, Stormy again.
We had soundings on the grand banks of Newfoundland at forty fathoms;
but little wind for two or three days.
Afternoon cleared up so pleasantly,
that great hopes were entertained of having good weather.
18th, Forenoon stormy with but little wind, the storm continued until near night;
then the wind springing up fresh and fair, it cleared away.
The captain said he had not been able to get but
one good observation during our being at sea,
so little sunshine have we had for this almost two weeks.
But my soul is satisfied in the divine disposal.

19th. Fair weather and a good fresh breeze.
We now seem to look forward with cheerfulness.
20th and 21st, a very good breeze continued most of these days.
22nd, this day a good fresh breeze at S. W. the weather cloudy;
but the cloud over my mind is in degree dispelled;
blessed be the name of the Lord.--Lord, hold me in your holy hand,
and make me ever truly watchful, thankful, and steadfastly believing.
Amen.
23rd, we are still favored with a good lively breeze, and make good way a-head.
24th, the same as yesterday; during the last night I got very little sleep;
(though this is usual with me on this voyage) yet in most fervent
intercessions I besought the Lord to be with me through all.
25th, 26th and 27th, still good winds.
O the wonders of the rolling foaming deep!
If the Lord`'s hand was not underneath, we should surely sink beneath the raging waves!
Who can be an atheist?
or what can be an atheist`'s hope?
28th, a very good lively wind, cloudy and small rains.
Last night, a night of anguish to my proved soul.
All former experience cannot prevent renewals of unspeakable anxiety,
when the Lord is pleased to prove his own as '`at Massah,`' and to
'`strive with them (in his own way) as at the waters of Meribah.`'
29th, an excellent wind, cloudy and wet.--The mariners cast the lead,
found soundings at about 90 fathoms.
30th, fair wind and weather.
It was agreed on board, that this morning,
when the sun was about two hours and a half high,
that we had not had so much fair weather at a time, since we left Boston,
as this morning.
31st, in the morning found sixty fathom water;
we were now abreast Scilly islands according to our calculations.
This afternoon we saw the Lizard.
Fresh wind and cloudy.
Thus ends the year 1792.

1st of the 1st month 1793.
The wind increased from a good fresh breeze,
to a strong gale--saw land several times this day,
and a number of ships going up and down the English channel.
2nd, almost calm.
Thus, after a storm, comes a calm.
May my soul take courage to weather out the yet remaining storms of life,
in consideration that, now and then, it will be calm;
and in full hope of a safe entrance before long,
and eternal calm abode in the haven of immortal bliss; as we are now, I trust,
about entering in a few days our outward port.
3rd, in the morning we were off Calais cliffs, almost becalmed, gained no ground all day.
4th. after beating to and fro all night, just in by the land near Calais,
we took a pilot on board from there this morning, and tried to work up the straits,
but made little advance by reason of contrary winds and tides.
We lay at anchor this night between Calais and Dunkirk.

5th, Got within about four miles of Dunkirk harbor; could get no further,
so cast anchor again.
But being desirous to be with the few Friends at Dunkirk next day at meeting,
I went on board the pilot boat, among coarse uncouth Flemmings, and a Frenchman or two,
all strangers, and got safe ashore,
and soon to the house of my dear friend William Rotch and family, of Nantucket,
now resident here at Dunkirk in French Flanders, where I met a very cordial reception.
My soul bowed in thankfulness to Israel`'s God, whose unfailing Arm had thus far borne up,
and whose goodness so far had fulfilled his holy word,
as to bring me safe through all to shore.
6th, I sat with the few Friends of this place, in their meeting,
and rejoiced in the divine presence,
of which my enjoyment was greater than at any time during my whole passage from America.
My way opening in a small testimony, my soul was relieved and praised God,
on the banks of deliverance, both outward and inward.

7th. Wrote letters home to my friends.
8th and 9th, visited some families.
Dear Robert Grubb, of Ireland, came here from Paris the last evening.
13th, I found a good degree of relief in the public meeting;
but became much more thoroughly relieved in an
evening meeting which we found a concern to hold,
at the sixth hour.
The meeting-place being filled by Friends and others; it was a good time;
and at the close we had a solid opportunity with the members only,
and advised and encouraged, as way opened in the life;
and several young Friends being sensibly impressed with a living
sense of the necessity of pressing forward in the line of duty,
my soul rejoiced among them, after several days of close inward exercise.
14th, I left Dunkirk, accompanied by my dear friends William Rotch and Robert Grubb,
and rode to Calais; and feeling quite clear of Dunkirk, it was to me a pleasant ride,
though the ways were very broken and difficult.
15th, the wind being very high, we were detained in Calais, from crossing to England;
and though the detention was not desirable, yet being resigned,
we fell into a field of instructive and cementing conversation,
which I trust will not soon if ever be erased.
16th and 17th, still detained at Calais.
18th, crossed to Dover,
and was glad to find myself at last in the company of my dear friends in England.

20th. At the fore and afternoon meetings,
and an evening sitting at the house of my dear friend Richard Baker,
with a pretty large number of Friends,
I had full opportunity to become relieved in mind in regard to the
deep travail of spirit which I felt for Friends of this place:
May they live loose to the world,
and separate from its beguiling friendships and influence.
21st and 22nd, much unwell with a cold, and a deep heavy cough, so that I kept house.
23rd. rode, accompanied by my dear friend William Rotch, by post-chaise to Rochester,
lodged at our friend Dr. William Cooper`'s. 24th, attended the meeting at Rochester;
long silent,
but at length I was a little helped in testimony--my travail was and
is that Friends there may live and move in the life of true religion.
25th, we went to London, and attended the meeting for sufferings there.
26th, we attended two sittings of said meeting and my concern was,
that Friends might dwell deep,
and act in the current of life in their religious movements:
I labored a little to that purpose and sound satisfaction.
27th,
attended in the forenoon Grace-Church-Street meeting--afternoon that at Devonshire-
House--in the evening we again attended the meeting for sufferings,
where my concern and labor still was,
that Friends should dwell and act in the divine life.
28th, we attended the select morning meeting,
where my service was in silent travail among them.
29th, attended Horseleydown meeting, silent, as also next day at the Peel meeting.
31st, livingly opened in Ratcliff meeting, to a degree of unspeakable rejoicing;
but at the Park meeting, in the evening, I stood up in a feeling sense of some good,
and much good-will; but could not get forward, the way quite closed up, and I sat down.

1st of 2nd month.
I attended the meeting for sufferings.
3rd. In the forenoon I attended Westminster meeting, and afternoon the Peel;
in both I had divine relief in bearing gospel testimony.
4th, Attended the select morning meeting.
5th, We attended Devonshire-House monthly meeting, my way was much closed up.
6th, My soul was made glad in gospel testimony, at Grace-Church-Street monthly meeting.
7th, We rode out about seven miles to the monthly meeting at Tottenham,
where the Lord livingly helped us.
It was a good time, and we returned in the evening.
8th, attended the meeting for sufferings.
9th, We visited several Friends families.
10th, We attended in the forenoon the Park meeting,
and in the afternoon that at Horseleydown; in both the Lord dealt bountifully with us,
Truth rising over all, and we may thankfully say, '`hitherto the Lord has helped us.`'
11th, Found relief in clearing my mind in a good degree in the select meeting.
12th, We attended the monthly meeting at Horseleydown.
13th, I rejoiced in Truth`'s victory over death,
in a meeting at the school-house for Friends at Peel meeting.
Also on 14th, at the monthly meeting at Westminster.
15th, Had a hard cold and cough; kept house.
16th and 17th, Still unwell.
18th, I got out though weak to the select morning meeting.
19th, We went out to Barking monthly meeting held at Plasto,
about four or five miles from London.
20th, attended Peel monthly meeting, where I was much closed up except in discipline.
21st, that at Ratcliff, much in the same way.
22nd, attended the school meeting at Islington, and the meeting for sufferings:
still I was quite shut up in silence.
23rd, I wrote letters to my friends.
24th, attended Devonshire-House and Grace-Church-Street meetings,
and select meeting in the evening at Devonshire-House, besides a family visit;
in all which Truth triumphed over all, the Lord himself gave the word,
and in his divine life and authority it was published.
25th, we attended the select meeting to a good degree of satisfaction.
26th, at Horseleydown,
and 27th at Deptford--the testimony and word of life
were rejoicingly witnessed in eminent exaltation,
many persons attended not of our society--the spring of the
gospel and its glorious doctrines were livingly opened.
28th, Truth opened gospel doctrines,
and brought forth necessary admonitions and warnings in its own pure life at Westminster,
where we sat up our Ebenezer, and thankfully acknowledged, as on many former occasions,
'`hitherto the Lord has helped us.`'

1st of 3rd month.
I was at the meeting for sufferings, shut up in silence.
2nd. I wrote, visited a sick friend, and rode to Plasto, to attend meeting there next day.
I may here mention,
my mind has been deeply affected under some serious
considerations of the state of things in the world,
and particularly in this nation.
What a number of men are there who assume the station of gospel ministers; and,
under that pretense,
drain and even violently force away from the proper owners large sums of money,
which they do very little to earn!--Even if it were right to preach for hire,
and if Christ`'s true ministers could freely and
righteously receive money for their ministry,
(which they by no means can) yet to see a set of almost idle
drones living on the honest labors of the industrious,
as great numbers of the upper clergy do,
while they not only thus oppress many poor laymen, as they choose to call them,
but also press down to a very low price and poor living,
even many of the lower clergy who do the work for them,
as if a minister of Jesus could have his work done and
his ministry performed faithfully in the sight of God,
by hiring another to preach for him,
and with money extorted from those it properly and honestly belongs to,
while themselves live in luxury and at ease, in their paneled houses,
and but seldom visit their flock; the prospect of these things is deeply affecting.

Oh! most assuredly the land mourns, and God is angry because of these things,
and in some way or other he will arise and shake the earth,
and also this false heaven--this vain and oppressive ministry,
and rend the power from the idle, lordly clergy.
But whatever be the means, so that it is in the pure counsel of God,
my very soul breathes to the Almighty, that he may, in the way of his own good pleasure,
hasten the downfall even of protestant Babylon; rend the power of the idle,
useless clergy,
and thus emancipate the people from the bondage and oppression they groan under,
that the earth may enjoy her sabbaths again.
But how these deeply to be pitied, these too worthless, too worldly,
and too cruel pretenders to the ministry of the gospel of Christ;
or how those civil rulers who, to answer the purposes of aggrandizement and power,
support them; will be able to settle their accounts in the great day of the Lord,
the solemn settlement of all things, is a consideration truly awful!

If these hints are ever published,
let not delicacy prevail to affect any unnecessary mitigation
of the close expressions in which they are couched.
It is time these deceivers of men, these dark bodies,
who form an eclipse between God and the souls of men,
should hear and seriously hearken to the voice of plain, honest and undisguised truth.
And whether they will hearken and hear, yes or no, let them be assured God is arising,
and will shake and remove them out of the way;
and their domination shall be remembered with abhorrence!

3rd of 3rd month.
We had a good open meeting at Plasto.
4th, I had solid relief in the select morning meeting there,
through deep dwelling and plain dealing:
may the Lord fasten it as a nail in a sure place.
5th, we attended the monthly meeting at Devonshire-House.
6th, that at Grace-Church-Street.
7th, that at Tottenham; in all which I had solid satisfaction;
as also at an evening meeting which I was concerned to appoint on the 8th,
at said Tottenham: general notice was given, and it was a large crowded meeting,
many not of our society attending.
It was long silent; but after that,
Truth`'s doctrines were largely opened and declared to the people,
who behaved very commendably, and were remarkably still and quiet,
through the long silence, and to the close of the meeting.

9th, I visited several families, and therein had peace.
10th, attended meeting fore and afternoon at Tottenham.
11th, the select morning meeting at Grace-Church-Street; and 12th,
the meeting at Devonshire-House; all to solid satisfaction in the Lord.
13th, we attended the monthly meeting at Stains, seventeen miles from London;
and next day their particular meeting at the same place;
in both which Truth reigned over all: thanks be unto God who gave the victory.
Many not of our society, being notified, attended the last meeting:
and I believe some of them were, through the openings of divine life,
solidly instructed and solemnized in spirit.
15th, we had a good open meeting at Long-ford, and, on 16th,
another at Uxbrigde 17th. one at Brentford,
and in the evening one at Hammersmith--all favored meetings;
though many of the people`'s views and expectations being too
much outward caused the spring to be long shut up in several
of them.--This may be strange doctrine to some;
but some others know that the spring must be opened in the hearer,
or else there can be but little profitably done by the speaker.
And he that speaks only in the ability that God immediately gives,
must feel a door of entrance in the people`'s minds,
or it is very difficult to get safely and relievingly forward.
But when the spring is livingly opened in him that speaks, and in those that hear,
then it is that deep calls unto deep, at the sound of the waterspouts of life,
and here instruction is sealed.

After these meetings we rode to London,
and were affectionately received by our dear friend John Elliot,
his wife and children 18th, we again attended the select morning meeting in the city,
to a degree of satisfaction.
19th, we were at monthly meeting at Barking.
20th, at a meeting appointed at Plasto; and, on 21st, at their meeting at Barking;
all affording some consolation.
22nd, we attended the meeting for sufferings at London.
23rd, I wrote letters home, and went out to Wandsworth.
24th, the word of the Lord was powerful through me, a poor instrument,
to the people at Wandsworth; and I can truly say with Paul, according to his working,
which works in me mightily, in many of these meetings:
may it have its full effect on the minds of the people.

25th, we attended the select quarterly meeting in London, at Grace-Church-Street,
where I was silent.
26th, and the quarterly meeting for worship and discipline was large and favored.
27th, we attended its adjournment, and in the evening,
the youth`'s quarterly meeting for worship.
28th, were at the meeting at Kingstown upon Thames,
where some hardened hearts were felt to oppose
in spirit the arising of Truth`'s testimony,
they being in a dark and unbelieving state.
In the evening we had a meeting at Esher, to solid satisfaction.
29th, attended the burial of a Friend at Alton: dark spirits here also, I apprehended,
inwardly opposed the truth: however, the testimony arose through deep wading over all,
blessed be the name of the Lord!

30th, we had an evening meeting at Gadalming, to some solid instruction.
31st, attended the fore and afternoon meetings at Guildford, in which Truth reigned,
though things are low there.
In the evening we attended the select quarterly meeting, and, 1st of 4th month.
Truth livingly qualified to labor, both in the quarterly meeting for worship,
and in the men`'s and women`'s meetings for church affairs.
2nd, we rode to Reading and 3rd. had a meeting there, and in the evening at Kerby.
4th, one at Shillingford, and at evening at Wallingford, and, 5th, one at Abingdon;
in all which many besides Friends attended,
but seemed in general to have very little sense of any thing
more in religion than the customary formal performances--which,
according to my observation,
is too generally the case with the professors of religion in England.
Tell them any thing about divine life in religion,
and they seem to think one an enthusiast,
and perhaps some of them would give a smile of ridicule: yet, to do them justice,
they are pretty generally civil;
but appear very insensible and unbelieving as to divine influence.
There is indeed so little entrance into their hearts in many places,
that it almost prevents a door of utterance; and when something opens,
it requires great humility and watchfulness to keep on the right foundation.
I had some satisfaction in these last meetings,
though Truth did not reign triumphant over all, as at some other times.

7th, We had a large meeting at Oxford, silent for a considerable time;
but Truth gradually arose,
and light shined through and over great obscurity and insensibility.
Oh! the deadness of professors!
Oh! the flat formality that too generally reigns!
The English Episcopal hierarchy must and will be shaken!
Yet once more I shake not the earth only, but also heaven.
One stone must not be left upon another, of mere creaturely performances,
where God is known to be all in all, and so he is known,
where Christ has reigned in the heart, until he has put down all rule and all authority,
but that of the pure truth;
for this is the state in which is fulfilled the precious prediction and promise,
that the Lord alone shall be exalted in that day,
and that the professors of Christianity may be
shaken from their dead forms and lifeless images,
and come to know '`that day,`' and therein God`'s exaltation over all that is of man,
is the travail and prayer of my soul to the God and Father of our Lord Jesus Christ.
And, O my God, if it be your will, I pray you,
hasten the more general coming and knowledge of that day among the nations.
Amen.
After meeting we rode to Witney, and 9th,
attended the quarterly meeting there--I was helped a little, but got very low in mind.

10th. I could not see my way to go forward, so staid the meeting for worship,
in which I felt and observed a total silence,
I believe ordered in divine wisdom as a lesson of instruction to others.
11th, we had a meeting at Farringdon.
12th, rode to Circencester, and had an evening meeting there.
13th, went to Hampton, and, 14th, were at meeting at Nailsworth;
and in the evening at Painswick.
15th, we had two meetings at Gloucester, and, 16th, one at Ross.
In all these the one universal and only principle of
all true religion and godliness was our help,
and, through its own living and helping influence,
was declared and testified of to the people,
though sometimes with but little evidence of entrance;
yet at others it seemed evidently to prevail over all.
17th,
we had a painful evening meeting at Monmouth in South-
Wales--several of the people were whispering,
talking, and some laughing, near all the time,
for which they were pretty closely reproved.
We concluded the meeting without any attempt to preach the gospel among them,
for no way seemed to open for it.

18th, we had a pretty large evening meeting at Pontypool, to a degree of satisfaction;
from there we went to Llandilo, and, 21st, were at meeting there,
and though I was sensible there was great place in the people`'s minds,
with seriousness and tenderness,
I could not express a word of what I felt flowing in my heart towards them;
but for some cause, was made an example of silence among them.
O Lord, I pray you preserve my spirit alive in you, and keep me subjectly given up,
whether to speak or keep silence.
After this meeting we rode to Caermarthen, and, 22nd, had a meeting there, and, 23rd,
came on the select meeting of ministers and elders there, for North and South Wales,
wherein I experienced considerable exercise among them.
Afterwards came on a meeting for worship, of Friends only;
and then the business of the quarterly meeting transacted at this season of the year,
by what is called the yearly meeting.

24th, Were held two large public meetings,
one in the sore and the other in the afternoon; silence was my lot.
25th, the select meeting and meeting for discipline met again,
after which Friends held another meeting for worship among themselves in the evening,
my pain and affliction continued through all,
tho`' I dropped some close hints in the select meeting respecting ministry,
and made a few remarks in the evening meeting, which afforded some relief to my mind.
After all these meetings, I felt not clear of the people of Caermarthen:
so when Friends were mostly gone from the place, dear Deborah Darby,
Rebecca Young and myself, staid one more meeting on 26th,
in which I received much relief; and 27th, rode with a very peaceful mind to Swansea;
28th, had great enlargement and relief in the meeting there.
The four following days we had meetings at Neath, Cowbridge, Cardiff and Newport.
These were almost wholly of people not of our profession,
among whom gospel doctrines were opened (though under
some depression at times) in Truth`'s life and authority.
An increase of true religion in England and Wales is much lacking; yet,
blessed be Jehovah`'s holy name, a few are found from place to place,
who know it in a good degree of dominion.

3rd. We left Wales and went to Bristol,
where I met with my dear friend Samuel Emlen from Philadelphia, in America,
on a religious visit to this country, who had been in this city some time:
Our joy was mutual, and mingled with tears of affection,
in remembrance of past seasons of divine refreshment together in our native country.
5th, We attended three large public meetings at the Fryar`'a
meeting (so called) in the city of Bristol.
6th, one more select, though large; and, 7th, two more large public meetings;
these concluded the yearly meeting at Bristol.
I was silent through all these meetings, as was also dear Samuel Emlen;
and on first-day afternoon the meeting was silent likewise.
I was led to deplore the low state of the ministry, with renewed desires,
that our preaching might be such, through him who is the Resurrection and the life,
that the dead may be raised: for the letter will kill, does kill,
and has killed its tens of thousands.

8th. I attended meeting at Lawrence-Weston, where, in the power of the gospel,
I labored among them.
9th, I sat the meeting in silence again at Bristol; and, though I expected,
from the exercise of my mind, my bonds would burst in sunder, it proved not so:
the time was not come.
We went to Melksham, and visited several families, in true gospel openness;
and 12th. attended the fore and afternoon meetings there, in both which Truth preveiled.
13th, we attended the monthly meeting at Broomham;
at six in the afternoon we had a meeting at Devizes, and one next day at Marlborough,
after which I again thankfully acknowledged, '`hitherto has the Lord helped us.`'

15th and 16th, We had relieving and edifying meetings at Newbury and Maidenhead;
our dear friend Samuel Emlen being with us at these, to our rejoicing.
17th, we attended the meeting at Uxbridge, after which,
conducted by my kind friend John Hull, who had been with me several weeks,
I went to London, where I attended the yearly meeting,
which began for ministers and elders the 18th of 5th month.
19th, I attended the Peel meeting; silent.

20th, Began the yearly meeting for church discipline,
for inspecting into the state of the society, and regulations thereof;
which continued by adjournments until the 28th, as did the select meeting until the 29th,
the latter not meeting every day like the former:
and though I was silent in several of these meetings,
yet I had some service in some of them, both public and in a more select capacity; and,
on the whole, I had a good degree of solid satisfaction in this yearly meeting:
the great Helper of Israel was graciously pleased to shine upon our hearts,
and qualify for service in his church.
And many deeply exercised souls being gathered together,
they were a strength to each other.
Friends generally appeared condescending to what arose as Truth`'s judgment,
whomsoever it was through and however contrary to what they had conceived or expressed.
The Lord is raising up a living army in this nation, who are,
and if they stand faithful will yet become more and more useful in the militant church.
Oh, the need there is of wisdom and forbearance in the church! may the God of Israel guide,
guard and preserve the honest-hearted, and may they,
in the becoming meekness of true wisdom, keep singly to his divine directions.

30th, I attended Westminster meeting, to the relief of my mind.
31st, the school meeting for children at Clerkenwell,
in which I found little exercise in the ministry.
In this meeting dear Mary, the wife of our friend George Stacy,
and daughter of our beloved friend Rachel Wilson,
for the first time appeared in public testimony--may the Lord preserve her;
she appeared to be a deeply exercised woman, and to have given up greatly in the cross,
thus to be exposed.

First of 6th month.
I wrote letters and visited the sick and afflicted.
2nd, I attended Peel and Westminster meetings, to the solid peace of my mind.
3rd, the morning meeting of ministers and elders; 4th,
then monthly meeting at Devonshire-House--an open and triumphant season.
5th, the monthly meeting at Grace-Church-Street.
6th, that at Tottenham, silent as to public testimony.
7th and 8th, Joseph Nicholson going with me for Ireland, we rode to Birmingham,
a large town; and 9th, were at their two meetings, and preparative meeting; and 10th,
had a meeting at Tamworth--In all which Truth reigned, and life was in dominion,
though things are but low at those places.

11th, we had a meeting at Uttoxeter, wherein, though I had much to say,
I found very little satisfaction;
but had great need of patience after it was ended in order to my inheriting the promises.
12th and 13th, attended the quarterly meeting at Leek, to solid satisfaction.
Then went to Macclesfield, Stockport and Morley;
the last a very large but exercising meeting.
I found much to say, but got little solid relief.
17th, we rested at our dear friends Richard and Martha Routh`'s. 18th,
attended monthly meeting there.
19th, we had a good meeting at Oldham, and 20th, another at Crawshay booth,
also attended monthly meeting there.
21st, we had a blessed large meeting at Marsden, and one the same day at Sawley.
From there we went to Newton, and, 23rd, were at meeting there;
had much labor and little relief.
25th, we had a meeting at Preston, to some satisfaction,
a few serious people attending among others.
We went on to Liverpool; where, 26th, at dear Robert Benson`'s,
I wrote letters to my friends both in New and Old-England,
and next day attended meeting there; the spring was low, but rose gradually,
some of us singing joyfully unto it.

28th and 29th, I was unwell, and the wind was against our passage to Ireland,
and after several days detention by contrary winds,
and attending their meetings on first-day, on the 4th of the 7th month,
we sailed for Ireland, in the Viceroy Packet, of Liverpool.
The wind was mostly contrary during the passage,
which was therefore a long and trying one of near six days.
9th, we landed at Dublin, where I received comfortable letters from home;
and after writing letters and visiting a few families,
on the 12th attended meeting at Sycamore-Alley in Dublin,
in the life and power of the gospel.

14th, I attended the meeting at Meath-street and Sycamore-Alley,
to my own great relief of mind; 16th, the monthly meeting at Meath-Street,
in the enlargement of the gospel; and, through some close searching labors,
got great relief.
Meath-Street and Sycamore-Alley meetings are both for the same Friends,
but held alternately to accommodate, both parts of the town.
17th, accompanied by my kind young friend Thomas Bewley, junior,
son of dear Thomas Bewley, at whose house I lodged at Dublin, I went to Baltebois,
and had there an open meeting among a few Friends and others, and we rode to Ballitore,
where I was sick all the next day, being taken the day before.

19th, had a pretty good meeting here, and next day another at Castle-Dermot;
the day following at Carlow, where, near the close of the afternoon meeting,
I had to bear testimony to a good degree of peace and satisfaction.
22nd, long silence of prevailed in a meeting I had at Kilconner;
but truth gave us the victory at last: blessed be the name of the Lord forever.
Then we had meetings at Ross, Forest, Ennescortha, Cooladine, Ballantore, Ballanclay,
Ballicone and Wicklow,
taking two in a day--all pretty open satisfactory meetings except the last,
which was somewhat painfully exercising.

29th, we returned to Dublin, and next day attended the meeting for worship,
and adjournment of the monthly meeting at Meath-Street; and the day following,
wrote to my family and some other friends in America.
From there accompanied still by dear Thomas Bewley, jun.
we went to Rathfriland, and 3rd of 8th month, had a good meeting there.
4th, attended the meeting there, both fore and afternoon,
I was considerably enlarged in testimony, but in so low and feeble a manner,
that after meeting I sunk into great discouragement,
to think that though I stood up and proceeded in the evidence and feeling of duty,
yet very little life or relief of mind was experienced.
The meeting was large.
5th, exercise of mind and pain of body caused the
last to be unto me a night of much uneasiness;
but endeavoring this morning to '`possess myself in patience.`'
I became at length composed.
6th, I remained unwell, but rode to Lurgan, and was at meeting there next day.
I felt no freedom that public notice should be given, which was very unusual;
and near the close of the meeting, (having sat in silence) I stood up,
though not expecting to say any thing in the usual line of the ministry, and told them,
those who go to their religious meetings with expectations and desires of outward help,
and are thereby diverted from looking inward and feeling after divine help,
go to their meetings in a deviation of mind from a true
gospel state and dependance--and all who are looking to
instruments for help in their meetings,
otherwise than helped of God through them,
and in his own time and according to his own will,
are not true worshippers in spirit and in truth.
But I have cause to believe, that even some of our society, at times,
who attend meetings and sit very still and orderly,
know little or nothing of true silence,
and feel very little of that exercise of soul by which
they may experience true christian watch and prayer,
when assembled together before God,
and in his awful presence.--The meeting then broke up, and I felt solid peace,
in a living sense, that I had not kindled a fire of my own;
but had been limited to Truth`'s pure motion, which is ever safe.

8th. I was at the meeting at Lisburn: public notice was given, but the meeting was silent.
9th, I had a meeting at Killsborough, wherein I labored in a low way,
I hope to some edification.
Truth rose not very high, and I rejoiced that the animation of nature rose not above it.
11th, I was at meeting at Ballenderry in the forenoon,
and in the afternoon was again at Lisburn, both good open meetings.

13th, I had a large painful meeting among the Presbyterians,
at Newtown-Aras near Mile-Cross.
They were too wise, rich and full, for instrumental help much to reach or benefit them.
I left them with a heavy heart,
and returned with my kind friend John Hancock to his house near Lisburn, and 15th,
attended monthly meeting there, to a good degree of satisfaction,
and next day had a good meeting at Antrim; and the day following another at Grange;
and then went to Ballimany, where, on the 18th, I had a very large one.
An ear was open in a few to hear the true gospel preached;
but the crowd and concourse was so great, and large numbers so light and unsettled,
and some so noisy,
that we were under a necessity of concluding the
meeting much sooner than otherwise we might have done;
after which several of the sober people with tears desired we would have another meeting,
and proposed our having a large meeting-house in the town for the purpose.
They appeared greatly grieved at the behavior of some of their neighbors,
and much disappointed at hearing so little of Truth`'s living testimony declared.
My bowels yearned towards them,
but we could not see a way open in the light to appoint another meeting.
Indeed what little was uttered among them was so much
in the life that they greatly hungered for more;
and I thought it much better to leave them hungering,
than to fill them until they might even loathe the honey-comb.
So in much love we left them, and rode to Ballynacree.

19th, we had good open meetings at Ballynacree and Colerain.
My openness and service was as usual mostly towards people not of our society;
and next day at Toberhead, which appeared to be a feeble one;
and the day following I had good satisfaction in the monthly meeting at Grange,
near Charlemont, both in the public and in the more select part.
There is a little living remnant of valuable Friends belonging to that monthly meeting.
22nd, we had a good meeting among Friends and others, at Ballahagan;
next day a relieving one at Moy; and, 25th,
the fore and afternoon meetings at Grange were large and highly favored,
as was that held next day at the Presbyterian meeting-house in Dungannon.
The doctrines of the everlasting gospel, in most of these meetings in the north,
flowed like oil upon the spirits of the people.
But this last meeting was hurt by an unskilful and unseasonable appearance,
after the people were risen to go out.

27th, we had a meeting at a place called Carborough,
among a few Friends and a pretty many Presbyterians.
In this meeting gospel truths flowed somewhat largely
in a gentle current of life to the people;
but there was too little of a door of entrance into their hearts to
admit of any great dominion of the life divine among them.
Even Jesus wrought not many mighty works in some places,
because of the people`'s unbelief; they shut up the kingdom of heaven against themselves,
which is often the case in our day.
Next day I attended at Grange; and from the 31st of the 8th month to the 3rd of the 9th,
was held the quarterly meeting there, in the course of which Truth reigned over all,
both in public testimony, and at times in solemn silence,
though some spirits seemed opposed thereto.
4th, attended again the meeting at Grange, and next day rode to Lurgan,
and had a painful meeting there.
Notice was given to the town`'s people, and many attended;
but it seemed as though they knew scarce any thing about the life of religion.
I got little relief among them.
Friends there, as well as others, are in a low state.

After this I was at two meetings at Moy-Allen, one silent, and the other nearly so.
One at Ballahagan, long silent and suffering, but ended triumphant.
One at Richhill, dull and painful.
One at Castleshane, silent until near the close,
when I opened to the people the impossibility of man`'s
preaching the gospel without immediate divine help.
One at Coothill, wherein the joy of the Lord was our strength,
and in true gospel authority the people were instructed
in the gospel mysteries of Christ in man,
his hope of glory.
At Coothill there was a great fair, and a fight,
which was in some degree bloody considering the occasion,
between the soldiers with swords, and country people with clubs,
about a lad just enlisted, who attempting to make his escape,
the soldiers endeavoring to secure him, the country people were enraged,
and aiming to support his escape,
the quarrel ran so high that the street was in an uproar from end to end;
and being crowded full of country people, town`'s people and soldiers,
to the amount I suppose of several thousands, the scene was truly affecting;
and though I believe there were no lives lost, yet as there was considerable bloodshed,
and many wounded, it afforded a very horrid spectacle of the depravity of human nature.
And I thought it not amiss to give a hint of it here,
as it led me to mourn over the benighted and dreadful state of poor mankind.

What dreadful wars have raged, through almost all ages and nations!
What rivers of blood have human beings drawn from human beings!
and what havoc are men still making of human lives,
who say they are christians!
At this very day (Oh, sad to mention) is France and England,
and several other European nations embroiled in cruel wars!
Will the state of mankind never be meliorated!
Will the sword devour forever, and the glorious and benign influence of the gospel,
by the wrath of men forever be defeated!
Forbid it, gracious heaven!
Indeed, I firmly believe,
the time will yet come when '`nation shall not lift up sword against nation,
neither shall they learn war any more.`'
O, blessed day!
O, precious state of peace, harmony and happiness!
My spirit breathes unto God,
that he may arise and hasten this great work of reformation on the earth;
that the kingdoms of this world may become the kingdom of God, and of his Christ.
Amen says my soul.

After this, from the 15th to the 21st, we had meetings at Old-Castle, Edenderry,
Timmahoe, Rathangan, Athy and Ballanakill-- the first of these was open and edifying,
the next very eminently overshadowed and owned of the Shepherd of Israel,
notwithstanding there were some strong opposers present.
Blessed be the name of the Lord God Omnipotent, who reigns and will reign over all,
convincing his enemies that they are but as dust beneath his feet,
and all their opposition to his spiritual reign and government,
as a cloud which the sun dispels.

The rest of these meetings were mostly dull painful seasons, several almost silent,
and the others laborious and but little relieving.
At Rathangan a young man sat and behaved very irreverently during much of the meeting;
at the close I reproved him; he retorted, was angry and denied the charge,
and complained of ill treatment.
I felt the power of truth increasing over the meeting,
and when he had vented himself and spent his venomous shafts,
I stood up and delivered what was further on my
mind respecting the poor dark depraved creature,
and addressed the people in the love of the gospel,
the meeting closed to solid satisfaction.
I found afterwards he was a dissolute stage-player.
Oh the mischiefs of the theatre! what dissipation it promotes!
it operates directly against the life of religion,
and tends to the destruction of morals! where
shall we go to find the fear of God in an actor?
yet, sorrowful to say, too many great professors of christianity,
and some of the pretended ministers of the gospel, are not ashamed openly to plead for,
and with all their eloquence promote the destructive practice of stage-playing.
My very soul is grieved within me when I view
the fallen state of poor degenerated christians,
and above all the dead, dark and carnal-minded state of the clergy, so called,
like swarms of locusts they darken the air,
and in many places eat up almost every green thing.
Instead of turning the people to God,
they bring them under the administration of the letter that kills,
and thus the spiritual freshness or greenness, begotten of God,
at times by his Holy Spirit in some, is as it were, eaten out.
But God Almighty will sweep them from the face of the earth.
The time assuredly comes when great Babylon`'s merchandize and traffic shall fail,
and when her flesh shall be burnt with fire.
The Lord of hosts has spoken it.

The testimony at Athy was much by way of opening the deceits, worldly-mindedness,
and lack of real gospel qualification, in those hireling teachers, who,
if ever such in any age existed, are the '`blind leaders of the blind.`'
And I am persuaded that no class of men in these
nations do more to obstruct the true work of the gospel,
and the coming of Christ`'s kingdom on earth as in heaven, than these;
but I repeat it again, God will do them away!
For false religion and worship shall be shaken,
as well as earthly-mindedness and corrupt government,
in order to make way for that which cannot be shaken,
the work of God`'s Holy Spirit in men`'s hearts,
and that worship and religion which the holy operation thereof
enables man to persevere in to his own unshaken peace,
and the exaltation of the divine glory.

At Ballanakill there was so little sense of true religion among the people,
and so much lightness and irreverence,
that no way opened in the spring of the gospel
to preach Jesus and the resurrection among them;
so the meeting was necessarily silent, for we preach not ourselves;
and not being able rightly to call Jesus Lord, but by the Holy Ghost,
dared not attempt to preach his gospel without that divine unction and influence,
well knowing it cannot be done; and that so many thousands attempting to do it,
has been the means of overrunning the nations with the dead formal image of worship,
consisting of words without life and sounds without substance.

When the meeting concluded I reproved the levity and irreverence of the people,
endeavored to put them upon a serious enquiry respecting a preparation for death,
and left them with an aching heart.
Many of them seemed not to know their right hand
from their left more than the Ninevites did;
which is indeed the case with too many of the
professors of christianity in England and Ireland;
and the priests above all men have mournfully contributed to its being so;
and this I believe will ever be the case,
where and so long as the preachers are mere hirelings: For,
God will not give his glory to another,
nor his praise to graven images or the works of men`'s hands of any kind,
however specious or refined.
He will indeed glorify the house of his glory, where his honor dwells;
where his Holy Spirit is the spring of action;
and where he is '`the worker of all things;`' where his people will be still,
and know that he is God; where they patiently wait for him,
and '`let him arise,`' not arising themselves before him or without him.

But alas! alas! who and where are these?
Truly not all who are professing so to do.
But this is the standard unto which the true and
thorough gospel worshipper must be reduced.
And though too many among us are falling short of this standard,
yet there are many who are alive in the power and dominion of Truth, our first principle,
and which is the everlasting principle and support of all that
is truly religious in every society to the world`'s end.

Under these considerations I do most fervently desire we may be a living, faithful,
spiritual people; firmly believing, if we are sufficiently so, we shall,
above all the families of the earth, show forth God`'s praise;
many thousands will flow unto Zion, there they will behold Jerusalem a quiet habitation;
be blessed with the dew of Hermon,
and rejoice in the dew that descends on the mountains of Zion,
where the Lord commands the blessing, even life for evermore; while the mere self-active,
formal hirelings, remaining in their self-active state,
promoting abolished shadowy observations,
will not ascend far into the mountain of myrrh and hill of frankincense,
but continue to wither and die.--Read William Penn`'s
rise and progress of the people called Quakers,
wherein is shown how one people after another sunk into formality.
Consider deeply how lamentably it has been the case with some of us; and know assuredly,
that if we keep not in the divine life, we shall be rejected as well as others.

However, if I am given to discern the signs of the times,
a revival will take place among us;
but it will be only through faithfulness and deep dwelling, being baptized into death,
and arising in the newness of life with Christ.
It will not be through a great increase of rules of discipline;
many have been zealous therein, and centered too much in the letter that kills.

The scriptures are good, very good; discipline, good rules and good order,
all very necessary; but still it is the spirit that quickens and gives life;
and every departure from a right dependance on it,
every zealous movement in support of Truth`'s testimony independent of its necessary aid,
tends to introduce death, and set man on the throne,
instead of him who is God over all forever.

22nd, we attended meeting both fore and afternoon at Mountmelick,
where live our beloved friends Mary Ridgeway and Jane Watson,
lately on a religious visit to America; they were both at this time at home,
where I was glad to feel unity with their spirits in
the fresh life of the everlasting covenant.
It was a time of considerable openness and enlargement in the gospel.
I had, as at many other places,
to bear testimony against the blind leaders of the blind which swarm through the land,
and are a grievous oppression upon the poor people, grinding them down exceedingly,
and yet in general doing them no good;
but a great deal of injury in regard to the things of religion.
Indeed, if ever people spent their money for that which is not bread,
they do it most sorrowfully so, both in England and Ireland.

23rd, I visited two schools, attended a meeting of ministers and elders,
and then rode to Tullamore,
where we had a meeting consisting of the people of the town chiefly.
25th, we had a lively precious meeting at Ballamurry.
Next day I rested and wrote, and endeavored to be content in my present allotment,
though truly it is sometimes difficult to feel resignation in
so painful a pilgrimage as much of mine has been in Ireland.
There is so much superstition and lifeless formality among the people in general;
so little real religious exercise, or true knowledge and experience of divine things;
and such striving to make forms and creaturely
performances answer instead of life and substance;
that it is often almost impossible to obtain much solid relief,
by expressing among them even what opens and impresses
the mind in the life and love of the gospel.

This was a most trying day to me.
The elements seemed all in commotion.
Strife, contest and alarm seemed almost continually to pervade the whole man,
and agitate all that was alive within me.
I strove for calmness and patience; but great was the distress,
which I was left to labor under,
and extreme the desertion of all sensible comfort or divine good.
I looked up towards heaven; I tried to draw inwardly near unto God,
and to crave his assistance, and the return of his countenance and presence;
but he hid himself in thick darkness, and stood as it were aloof from my cry.
I was greatly overwhelmed with sorrow, and swallowed up of distress!
I retired several times; I lay down on my bed;
I read the bible and some other precious writings;
but through all I felt almost as if I was entirely forsaken!--
At length I yielded up my whole life and being,
as I had often done before, to go through and endure every pang, peril and perturbation,
which God all-wise might see meet to prove me with,
and for as long continuance as he should see needful.--So, in the evening,
the waves of the sea began to subside a little
at his voice whom both wind and sea obey forever.
I grew more tranquil, and had a pretty good night`'s rest.
This morning when I awoke, being 27th,
I felt in my body as it I had been all over bruised,
such had been my extreme agony of soul yesterday,
and such is the sympathy between soul and body.
Some may scarce believe me; but there is one who knows I lie not.
I read, and then walked out a while; the sun shone pleasantly; the birds sang,
and the whole face of nature was beautiful;
but my soul remembered the gall and the wormwood,
and I seemed forbidden to take much satisfaction in any thing visible.
Oh, my God, you are weaning me still more and more,
and much more than I once thought necessary, from the world,
and from all that is in it--Well, good is your will,
and your counsel is excellent.--Do with me what you will; form,
fashion and reduce me as you please.
You have given me clearly to see,
that many who have even been in your furnace came out too soon,
and remain drossy and impure all their days by not abiding your judgments,
and not enduring the turnings of your holy hand upon them,
and not following you fully into all that separates and
weans from all that flesh and blood delights in,
which you call for, and are graciously leading such as will follow you into.
Oh! redeem my soul from all that hinders its full and unimpeded access to you,
the fountain of living waters: set my affections wholly on things divine,
and make me entirely your own in the heavenly image and fellowship forever.

28th, In deep depression of spirit I attended the select quarterly meeting at Moat,
held for ministers and elders of the province of Leinster;
and next day I attended the public quarterly meeting, was silent excepting a few words;
and the day following I attended almost in silence the meeting for church affairs;
and Oh! the lack of deeper dwelling in the divine life!

1st of 10th month.
Having thus spent four or five days mostly in deep distress and agony of foul,
the Lord was graciously pleased to open the spring of life, unseal my lips,
and make me dip my foot in oil,
treading on high places in the name and strength of the highest.
He tuned my harp anew, put a new song in my heart and mouth,
and divinely strung my bow for battle:
thus the concluding meeting held for worship this last day of
the quarterly meeting was eminently owned of the Lord:
and Christ the resurrection and the life was joyfully known among us:
in his resurrection we arose with him; and because he lived, we lived also;
I mean principally such as had been baptized in the likeness of his death,
watched faithfully with him, and continued with him in his temptations and sufferings;
for unto these it was he appointed a kingdom: theirs it is;
and they continuing steadfast with him through all tribulation, shall,
in spite of death and hell, enjoy it.
Much searching work prevailed in testimony, through the openings of life,
and much consolation to the mourners in Zion, was graciously vouchsafed.

2nd, was at Birr; and, 4th, we had a most triumphant meeting at Montrath;
the testimony of the gospel flowed like oil to many,
and yet antichrist was exposed in his true colours: blessed forever be the Lord,
who hitherto has helped us.
After this we had meetings at Knock-Ballamaher, Ross-Crea, Limerick, Cork, Boudon,
Younghall, Garryrian, Clonmel,
and the several sittings of the quarterly meeting at Waterford,
for the province of Munster.
Several of these were highly favored seasons,
but some of them afforded far less satisfaction than others.
From there we went to Dublin in order to attend the national half-year`'s meeting,
where I was again kindly received by my kind friend Thomas Bewley and children;
and many other dear friends gave me a hearty welcome:
this has also been my experience in many other places.
On the 26th, the national select meeting opened; it was large, and the members,
at least some of them, appeared to be alive in a good degree in the holy root.

27th, In the meeting at Meath-Street and Sycamore-Alley, I was greatly favored;
Truth`'s divine testimony was, like fire among rubbish, against worldly-mindedness,
indifference and revolt; and some fresh encouragement flowed to the mourners in Zion,
the drooping-spirited and young and tender;
the doctrines and consolations of the gospel being pretty largely opened.
The four days following were held and concluded the
national meeting for good order in the society.
Also two more meetings for worship, and the concluding select meeting,
all these as parts of the national meeting.
A good degree of zeal appeared in many for the support of our christian discipline;
and things were conducted in a degree of brotherly love and concord.
And yet the lack in too many of the divine anointing oil, in the several movements,
was so sensibly felt, that I sat rather a mourner in most of these meetings,
and could say but very little in them from first to last.

I may here relate a remarkable occurrence: When I was in Dublin,
soon after my first landing, I was livingly opened in the life and power of the gospel,
at a meeting at Sycamore-Alley, in which, among other things,
I had a good deal to say about the spiritual fire of the Lord which is in Zion,
and his furnace which is in Jerusalem,
for the refining of all such as ever become his sons and daughters.
A man, in a stable near by, made a great noise to drown my voice,
which he continued for some little time, and as my voice raised he increased his noise;
and I was told that some heard him saying
something in contempt about the fire I spake of,
or however he was heard speaking about the burning of the fire.
Another person discharged a gun just by the meeting-house,
when I was in the midst of my most fervent engagement;
the report was very loud and disturbed many;
but I was carried through as if nothing had happened; blessed be the name of the Lord.
But now on my return to Dublin, I was fully informed that the poor wretched man,
who shouted so loudly in the stable to drown my voice,
and spake so ignorantly about the burning of the fire,
was in less than two weeks after consumed to death by fire in
the same stable where he had thus impiously behaved;
for the stable taking fire by some means when he was in it,
he was burnt before he could be got out.

This I heard of several weeks before my return,
but I chose not to insert it until I had got
fuller information and confirmation in the city;
but finding it fact,
and much noticed by many people of different religious professions in Dublin,
as a very remarkable instance of the providence or judgment of God;
I thought proper to give the relation of it a place here,
and I do it without presuming to say how far it was in special judgment.
But as God`'s dealings are all in wisdom,
perhaps such an instance of his all-wise government as this may have a striking and
profitable effect upon some of the hardened and daring who may read it,
or at least may tend to guard and caution some of the less
abandoned against giving way to the suggestions of infidelity,
profaneness or audacity.
For most assuredly there is a God of justice as well as mercy,
who sees and knows all our thoughts, words and actions,
and for every evil will bring us into judgment; yes,
for every thing contrary to his holy will and wisdom.

After the national meeting, which ended on the last day of the 10th month,
I staid in Dublin some days, not seeing my way open to go for England or elsewhere.

The 1st of the 11th month, I was again silent at the meeting at Sycamore-Alley,
as I also was at the meeting in the forenoon on the first-day following;
but in the afternoon at Sycamore-Alley, I was somewhat enlarged,
though not a great deal relieved, My soul was indeed, for a number of days,
in deep affliction in that great city;
insomuch that I greatly doubted my being enabled to leave it with pleasantness.
3rd, I attended a meeting at Ballabrigan, about fifteen miles from Dublin,
appointed for my dear friend Ann Tuke, daughter of William Tuke of Yorkshire, in England.
This meeting was very distressing:
the people seemed to know but very little of the real nature of divine worship.
I returned in heaviness to the city,
and next day got a degree of refreshment in the meeting at Meath-street,
through deep dwelling and keeping low in and with a little low stream of life,
which at length enlarged to something of a river;
but still I could not quite ease off my burden,
nor rise above my deep depression of spirit.
Another meeting at the same place in the afternoon, appointed by A. Tuke,
afforded me a degree of additional relief, so that I began to feel a little cheerful.
5th, I felt restrained from attending a meeting appointed for the same Friend at Dunlary;
I knew not why, but I felt easiest to decline going,
so I rested and wrote at the house of my dear friend Thomas Bewley,
bringing up this account to the time of said day of rest and writing.

After writing thus far, our dear friend, not feeling himself at liberty to leave Dublin,
until the 9th of 11th month,
when by accounts received he attended a public meeting at Johnstown,
and being accompanied by S. S. and A. S. went that evening to Ballitore,
to the house of our friend Elizabeth Shackleton.
On first-day the 10th he spoke largely in the morning meeting,
and very powerfully in a public meeting which was held in the evening at his request,
after which, he imparted weighty and instructive counsel in a Friend`'s family,
concluding in awful supplication.
The following night he was taken unwell, which continued to increase until the 14th,
when an eruption appeared which proved to be the small-pox,
during which time his mind was preserved in calmness and resignation,
and mentioned that it mattered little what part of the world he died in;
that he sometimes hoped to see New-England again and his dear children,
but that he had no will in it;
that he had looked closely towards home and his connections,
and into the state of his own mind,
though he did not know how the disorder would terminate.

During the progress of the disorder he was kindly attended by several Friends,
and among them was our friend Ann Tuke, who preserved the following daily account.

5th-day 14th, He said, there is an eternal Arm underneath each of us,
which is sufficient to bear up and support, and will do it,
as far as is needful we should be supported.
I have long been confirmed in the sentiment,
that nothing could possibly happen that would
harm me while I keep under the divine influence.

A physician from Dublin having been sent for, came this evening,
with which he expressed satisfaction, saying, he desired that he would continue near him,
which he did accordingly.
Some time after, he said, though I am not without some considerable bodily pain,
yet I feel such a portion of that good which is infinite,
that it does not seem worth mentioning, and if there was no greater enjoyment hereafter,
the present would be a state truly, desirable, through a never-ending eternity,
and yet the fulness is still more desirable.

The evening of the 14th, he dictated a letter to his relations and friends at home,
from which the following are extracted.

[.embedded-content-document.letter]
--

[.salutation]
Dearly beloved parents, (all three) brothers and sisters, relations and friends,

I am now at Ballitore, twenty-eight Irish miles from Dublin,
and I suppose undoubtedly entered five days into the small-pox;
the eruption began yesterday, and is very greatly increased to-day.
I am very agreeably attended by physicians and
the kindest of friends.--My distress of body,
through extreme difficulty of breathing, etc. has, for a short space of time,
been almost equal to any thing I can suppose human nature capable of,
but (it is now half past nine at night) this has been a very comfortable day;
and just now, and for some hours past,
I have been almost as easy as at any time in my life,
I think certainly never more so in mind--I feel no kind of alarm;
but the issue is certainly very doubtful.
I feel easiest to address you in this manner, principally,
that you may know that my mind enjoys a fulness of that
which removes beyond the reach of all sorrow.

My dear children are placed so that I have been pretty easy,
but I could wish them to get a little more learning
than some of them are at present in the way of;
and although I do not wish much of the world`'s polish, yet it is, at this awful moment,
my desire that they may not be brought up with much rusticity,
for this I believe has not very often contributed
either to civil or religious usefulness.

My desires for my children`'s substantial growth in the truth,
and strict adherence to all its discoveries to the close of their days,
is by far the principal wish I have for them.
Out of the enjoyment of a good degree of this precious
inheritance I know of nothing in this world worth living for.
You that know it, permit nothing, I most cordially beseech you,
ever to divert your minds from an increasing and fervent pursuit after the fulness of it,
even unto the measure of the stature and fulness of Christ.

It is almost marvelous how my strength of body
and mind holds out to address you in this manner.
I may now just mention,
that nothing will be knowingly neglected for my comfort of body or mind,
that my physicians or friends can afford: and greater cheerfulness,
and even pleasure in doing all they can, I have not met with among my nearest relations.
I pray the Lord, in the riches of His grace, to reward them with flowings of his love.

At the present day things are considerably ripening, and I have not the least doubt that,
before a great while, a high-way will be opened through kingdoms and nations,
where darkness has long reigned,
for the publication of the everlasting gospel in its true life and authority;
and as what is revealed in the ear, is in due time to be declared on the housetop,
I have little or no doubt that the true doctrine
of Christ will be much better understood,
than has hitherto been generally the case.

It is now eleven, I need rest;
whether I shall be able to add further is to me at present unknown;
and however it may be, in the fulness and almost unlimited flowings of true gospel love,
I am, and trust shall ever remain in best affection, your sincere relation and friend,

[.signed-section-signature]
JOB SCOTT.

--

15th. The disorder is pretty strongly making its progress; I can scarce get any sleep;
my strength fails a little, but I admire at its holding out so well;
the pock on the face is, if not quite, very nearly confluent;
the face considerably swelled; on the body it is pretty distinct.
The physicians speak very encouragingly, I believe in my absence as well as presence;
but were it not that little or no sense seems
given me as to the issue one way or the other,
I believe from the symptoms as they are,
and from my knowledge of my own constitution and the very different climate from America,
I should pretty strongly look out for dissolution,
although my spirits are under little or no depression at all.
Perhaps I never saw a time before,
when all things not criminal were so near alike
to me in point of any disturbance to the mind.
I do not know but when awake and capable of contemplation,
I nearly rejoice and give thanks in all.
When I verge a little towards sleep I am all afloat from the state of my nerves,
and from the extreme irritation forced almost immediately,
and with very unpleasant sensations from beginning repose,
but through all the soul seems deeply anchored in God.

Many and painful have been the probationary exercises of this life to me.
Ah! were there probability of strength, how I could enlarge,
for my heart seems melted within me in retrospective view; but all the former conflicts,
however grievous in their time, are lighter now than vanity,
except as they are clearly seen to have contributed
largely to the sanctification of the soul;
as they are remembered with awfulness and gratitude before Him
who has not failed to preserve through them all;
and as they seem likely to introduce either very shortly,
or before a very long time to an exceeding and eternal weight of glory.
Some have anxiously wished to have their time to live over again;
but though some of my early foibles and after deviations, might possibly,
on a second trial,
be escaped yet I know not but there is quite as much reason to
think a second might fall very short of the first,
as in any degree to exceed it; however,
I have no kind of self-complacency on account of any good works properly mine.
My own works I have long seen the necessity to cease from, and trust,
through the grace of God, by which I am what I am, I have been enabled,
in some precious degree, to do so.
It is the Lord who works my works in me, and magnified be his name forever,
he has often worked in me mightily, to my own humbling admiration, and I trust, at times,
to the thankful acknowledgment of many others; and as certainly as he lives,
he would work mightily in many thousands,
if they would but let him arise over all in them.
Indeed he works in all as far as they give way to his arising.
This doctrine is to me as clear and certain at this moment as ever it has been,
and I have often been constrained to proclaim it to the nations,
sometimes with almost invincible authority,
and sometimes under a great deal of weakness and obstruction.
The last has tended much to keep the creature rightly dependent and humble,
and through every dispensation the Leader of Israel has seen best what was best for me.

Let my children be engaged in some innocent employments, as much as well may be,
out of the way of a great deal of temptation, and if I had need to add it,
out of the way of very great accumulation;
and yet through industry and perseverance moderately productive.
My very soul abhors the idea that a christian can ever be at liberty,
while under the influence of heavenly good, to seek or even desire much wealth,
though this disposition, in direct opposition to the life and doctrine of Christ,
have gone far towards the destruction of true spiritual religion,
I believe in almost every religious society in the world.

16th. The fore part of the night and this morning he slept;
in the course of the day said to A. T. I have seen the magnanimity of a true believer,
and how one that is really so would bear all the trials permitted to
attend him;`' and by way of illustration added very forcibly,
'`Do you believe in God, you must also believe in the justness of all his dispensations.
It is a comfort to me your lot is cast among us.
This is a service, if I had not any other in Ireland.
Death is a service we all owe to our great Creator,
and sickness is a service required of many.
Oh!
Ireland, Ireland!
The Lord your God has service for you in Ireland,
was often sounded through the ear of my soul, before I left home,
as distinctly as you hear me now speak it.

In the morning, when speaking to the doctors who attended him, he said to this purpose,
I believe my having the disorder, and being here, is in the ordering of Providence.
It is not given me to know the event;
but if there be a field of future labor for me to enter into,
it is as possible for the Master to raise me up now as it was at the first;
but I have no will in it I think.`'
The fore part of this day he seemed easy and walked down stairs,
expressing that he could do it nearly as well as ever.

The fever came on towards evening, and he became very restless;
his swallowing was also difficult, but had no other unfavorable symptom,
and this was not deemed more than usual in this afflicting disorder.
In the night got some uneasy sleep,
swallowing and expectoration very difficult and painful.

First-day morning the 17th, on being asked how he rested, replied,
I have got through with what we call much difficulty to obtain a little relief.
He desired his affectionate love to M. B. the family and friends in Dublin,
intimating the weight of the disorder, and his escape from many trials,
if he should be removed; yet said,

The Lord is able to raise me up, his Arm is underneath, but from my present feebleness,
it is very uncertain; and seemed not to have any conclusion how it would terminate.
He desired to be remembered to dear M. R. and J. W. in the love of the everlasting gospel.
At another time said, I am in a very low way, cannot see about the event,
but must leave all to the Lord; the strength of nature seems very doubtful.

He continued all this day under much oppression from the load of matter,
took wine and bark every hour,
but no alarming symptoms appeared.--He requested that if he was removed,
some further particulars might be transmitted to his friends at home,
adding in substance.

The Lord`'s will is blessed, and I feel no controversy with it.
It is the Lord that enables us to coincide with his will,
and say amen to all the trials and conflicts he permits to attend us.
My mind is centered in that which brings into perfect acquiescence:
there is nothing in this world worth being enjoyed out of the divine will.
It is his will that brings us into a state of existence,
and it is for a purpose of his glory.
When my mind is abstracted and capable of deriving satisfaction from any thing outward,
it is an inexpressible satisfaction that my lot is cast here,
and that I am surrounded by such near and dear friends, both from within this family,
and these without who have accompanied.

The fore part of this night he slept more than usual,
and remained through the whole of it tolerably easy.

18th, 2nd-day.
Frequently expressed that nature had a hard struggle,
and his getting through was very doubtful.
The symptoms, considering the load of matter, continued favorable.
He gave directions, that, if he should go hence,
every thing about his interment should be plain and simple,
and said that he who raised up Lazarus could, if he had further labor for him to do,
break his bands asunder; but that,
when he reasoned upon the nature of the disorder and his own constitution,
and felt the conflicts of nature,
it seemed as if he was gradually advancing towards his everlasting home.
To two Friends from Mountmelick he expressed his entire resignation to divine disposal,
and that he found nothing to stand between him and the fountain of everlasting love:
said, he knew many Friends in Ireland loved him, and he loved them in the Lord Jesus,
and desired to be affectionately remembered to such as might enquire after him.

This night, and until three in the morning,
(3rd-day 19th) he patiently and quietly suffered much; yet got several naps.
About seven in the evening his stomach, too weak to bear the bark and wine,
discharged the last potion; he remarked these efforts to support nature failing;
and added, There are many resources in nature,
but if the great Author of nature does not think fit that any of them should be for me,
all is well: I could not desire to have such another struggle to go through, and I think,
if you can part with me, I can with you with a degree of cheerfulness.

--The fore part of the night spent quiet and patient as usual,
much oppressed and worn down with this grievous malady: he said, I have no fear,
for perfect love casts out all fear, and he that fears is not perfected in love.

20th, About five o`'clock on fourth-day morning he supplicated thus: O Lord my God,
you that have been with me from my youth to this day;
if a man who has endured with a degree of
patience the various turnings of your holy hand,
may be permitted to supplicate your name; cut short the work in righteousness,
if consistent with your will; you, who have wrought deliverance for Jacob,
evince that you are able to break my bonds asunder, and show forth your salvation,
that so my soul may magnify your name forever and ever.

And after a pause, wherein he seemed to feel the earnest of his petition, added,
'`So be it says my soul.`'-- After two o`'clock his stomach refused all nourishment,
and a hiccough came on; he said, Do not force nature,
let me pass quietly away to the eternal inheritance, to which I have no objection to go,
and the sooner the better if the work be done,
I have no wish to lay here.--His oppression seemed to increase,
and in a little while he said, I am waiting patiently to see the salvation of God:
do you wait patiently with me.
I have no desire, nor the shadow of desire, to be restored.
I hope the doctors will soon find that they have done their part.

The fore part of this night he could take little except water,
slept at times pretty easy to appearance, at others his breathing very difficult.
On P. J. assisting him, he said, I am no flatterer,
but you are one I depended on for outward assistance.
You have contributed much to the relief of this body,
and your being here has been an inexpressible satisfaction to me.

21st. At three o`'clock on 5th-day morning, said,
You have seen the awful progress of this disorder; as to me,
it matters little only present pain--may the Lord release me shortly.

Complained of the need of more air, and seemed declining fast.
Towards evening said, You may tell my friends in New-England,
and every part of the world,
that never did my soul bless the Lord on account of any worldly enjoyment, as I do now,
in the blessing felt by me to be contained in the prospect of a very speedy release.

To a person who came to see him he said, Oh!
Charles!
Charles! an inheritance in the eternal truth is infinitely,
infinitely superior to all the enjoyments this world can afford;
remember it as long as you live.

Some time after he said, I do not wish hastily to make my escape;
but if the Lord will be pleased to release me from the
bonds of mortality and the struggles of life,
and to cut the work short, considerably short, in righteousness,
I think I shall be willing to enroll it in the list of his unspeakable favors.

To the aforesaid, Farewell Charles,
let no possible consideration divert you from a close attention to that,
without which life must be lived in vain.

At another time said,
Some of my wishes for myself are centered in as speedy a release as may be,
consistent with the will of our heavenly Father, and an admission,
which I have no doubt at all, not in the least degree, of obtaining,
into that glorious kingdom, where the wicked cease from troubling,
and the weary soul is eternally at rest.

In a while after he said, I think I have not, for several years past,
known much or any thing of boasting;
I have known something of that law of grace whereby all boasting is entirely excluded;
but I may say,
through that which has supported me under all the trials and
conflicts which have attended my passage through life,
to you my beloved friends as to dear children,--follow
me as I have endeavored to follow Christ Jesus,
the Lord of life and glory, and the Rock of my eternal salvation.

At another time said,
It would have been desirable to me to have been favored with a clearer and
more certain prospect respecting the termination of this event;
yet if I should be continued a while longer,
I do not dispute but my end would be unspeakably glorious.--It would be painful to
me to have to return again to combat the trials and conflicts of mortality;
but if the Lord should see meet to continue me a while longer, I must submit,
after having in humility and resignation put up my
intercessions to be released from the struggle of nature;
to have had prospects of further labor is not uncommon, it has happened to many;
and the Lord can raise up and qualify others for his own work and service,
and he will send by whom he will send, and is able to save by many or by few.
I feel, and I wish you to feel for and with me,
after the eternal Rock of life and salvation; for, as we are established thereon,
we shall be in the everlasting unity, which cannot be shaken by all the changes of time,
nor interrupted in a never-ending eternity.
I do expect considerable derangement will now take place; it is no discouragement to me,
and ought to be none to those who trust in the Lord, and put no confidence in the flesh.

--In a while said,
I must not expect a release but by suffering a due proportion
of pain and distress.--You may feel sympathy with me,
but you cannot feel the reduction which must precede a release.

In the course of fifth-day he was rather more lightsome,
and tried several things to find what would best suit his stomach;
seemed considerably relieved from the extreme difficulty of breathing,
but altered much towards evening, and increased in weakness.
About one o`'clock on sixth-day morning, after suffering great uneasiness,
and getting little or no rest, he said, O Lord! if it be consistent with your holy will,
let loose my bands, and send the moment of relief to my poor body and soul.

Afterwards he said,
We cannot approve or disapprove by parts the works of Omnipotence rightly;
we must approve the whole and say, Your will be done in all things.

From one to three he was extremely restless and uneasy,
from (as he expressed it) the extreme irritability of the whole nervous system,
which he said was as great as could be imagined.
At times he rambled a little, but said, "`I find all things must be endured.
Do you, who judge in the light, judge me for impatience?`"

I answered, quite the reverse, and that we were sensible his bodily distress was great,
and wished to alleviate it.
He added, I cannot charge myself on that account, meaning impatience.
About four he seemed in great agony and conflict,
turning his head frequently on the pillow; and said,
"`Can it be upon any other ground but that the
time is come that the purpose must be effected.`"

Quarter past four, he desired to be turned on his right side,
which seemed a momentary relief.
Calling to P. J. he said, Make great allowance for me,
my distress is nearly as much as is supportable by human
nature.--Is there no possibility of my getting any sleep?
Oh! The pain, the inexpressible pain of my lungs!

P+++.+++ J. telling him that, from appearances,
there was a likelihood of his being very soon released, perhaps within an hour or two,
he replied,

If so, the Lord`'s name be blessed and praised forever;
I had much rather it were so than otherwise; for some time I perceived it hastening fast.
Afterwards he added, The desire of my heart is,
the great blessing of time and the consolation of eternity.

In a while he said to a friend, Guard against right hand errors and left hand errors;
let self be of no reputation; trust in the Lord, and he will carry you through all.

About five he appeared to be wrestling with death;
but struggled little considering his remaining bodily strength.
Being asked to take a little drink, he appeared quite sensible, and said, Yes,
yes--Took it, and continued without much struggling until about a quarter before seven,
when he moved to the side of the bed, but soon returned to his former position;
and drew his breath gently shorter and shorter, until seven o`'clock,
after which he breathed no more, but ascended with joy to his heavenly mansion,
and the glory of an incorruptible crown and inheritance with the saints in light.
His remains were interred on first-day, 24th of the 11th month 1793,
in Friends burial ground at Ballitore.

[.the-end]
FINIS.
